### ISSUE TITLE
 Failed to Configure Amplify

### ISSUE THREAD

**Issue by horgag** [aws-amplify/amplify-flutter#100]
**Describe the bug**
Hi, I'm using existing resources (user pools and identity pools) for my amplifyconfiguration.dart. But I'm unable to configure amplify. 

```
VERBOSE-2:ui_dart_state.cc(171)] Unhandled Exception: PlatformException(AmplifyException, Failed to Configure Amplify, The operation couldn’t be completed. (Amplify.ConfigurationError error 0.))
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:571:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:333:12)
#3      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
#4      Amplify.configure (package:amplify_core/amplify_core.dart:71:35)
#5      _MyHomepageState._configureAmplify (package:Rio/main.dart:42:27)
#6      _MyHomepageState.initState (package:Rio/main.dart:31:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4702:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4538:5)
```
**To Reproduce**

I presume this is a problem with my amplifyconfiguration.dart file. So I'll post it here and see if you can see anything wrong...
I'm finding it hard to debug the problem so any debugging advice would be great!

```
const amplifyconfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CredentialsProvider": {
                  "CognitoIdentity": {
                      "Default": {
                          "PoolId": "eu-west-1:2dxx4dxxxx0740-xxx-4f40-aa90-xxxxcxx",
                          "Region": "eu-west-1"
                      }
                  }
              },
              "CognitoUserPool": {
                  "Default": {
                      "PoolId": "eu-west-1_xxxxxxxxxj",
                      "AppClientId": "xxxxxxxxxxxxxxxxx",
                      "Region": "eu-west-1"
                  }
              },
              "Auth": {
                  "Default": {
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
          }
      }
  }
}''';

```

**Expected behavior**
That amplify configure works without any errors

**Screenshots**

**Platform**
Both Android and iOS 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fjnoyp** [comment]
Hi @horgag 

Make sure to follow the exact setup provided in our documentation: https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter

If you compare what you have with the example online, you'll see that you're missing a `"AppClientSecret": "[COGNITO USER POOL APP CLIENT SECRET]"` under CognitoUserPool / Default.

**Comment by horgag** [comment]
The AppClientSecret is optional

**Comment by fjnoyp** [comment]
Thanks for the followup @horgag 
Yes if you include an Amplify Flutter library such as Analytics, you will need to provide the necessary resources for that library to function within the amplifyConfiguration.dart either manually or by using the Amplify CLI.  

We will update our documentation to clarify this point for future users - we really appreciate that you brought this to our attention.
