### ISSUE TITLE
Requesting ability to Delete User in-app

### ISSUE THREAD

**Issue by djsjr** [aws-amplify/amplify-flutter#1005]
Apple's updates to the App Store Review Guidelines stipulate that "If your app supports account creation, you must also offer account deletion within the app." [(5.1.1 (v))](https://developer.apple.com/app-store/review/guidelines/#data-collection-and-storage). This goes into effect Jan 31st. Therefore I am requesting a method for doing so in-app—as far as I can tell there is not one already.

[This news post about the change](https://developer.apple.com/news/?id=mdkbobfo) from apple indicated that deletion must be able to at least be "initiated" within the app. Maybe a disable user method would suffice.

Any suggestions for a straightforward way to comply in the meantime are appreciated of course.

**Comment by abdallahshaban557** [comment]
Hi @djsjr  - we are aware of this update to Apple's guidelines and are currently working on features to support this in the near future. We will update this issue when the feature is available.

**Comment by haverchuck** [comment]
@djsjr  As noted in #1297,  We have implemented the [deleteUser](https://docs.amplify.aws/lib/auth/delete_user/q/platform/flutter/) API and released it in [version 0.3.2](https://pub.dev/packages/amplify_auth_cognito/changelog). For the moment it is ios-only, but are hoping to add Android support soon.  We are keeping the other issue open until android support is added, but I am closing this issue now.
