### ISSUE TITLE
How to achieve multipart upload of large files to S3 bucket

### ISSUE THREAD

**Issue by rabi-palmtree** [aws-amplify/amplify-flutter#1016]
We are currently able to upload files to S3 via the following code

    try {
      final UploadFileResult result = await Amplify.Storage.uploadFile(
        local: file,
        key: s3Url,
      );
    } on StorageException catch (e) {
      print('Error uploading file: $e');
    }

Now we want to upload large files. 
Would  transfer-utilty/multipart be the way to go?

https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios/
indicates that this is available for ios/android but  flutter specific documentation is not there (yet).

Please guide on how to proceed with handling large files.

**Comment by HuiSF** [comment]
Hi @rabi-palmtree Thanks for inquiring about multipart upload. The document you linked is for iOS/Android SDK, amplify-flutter consumes amplify-ios and amplify-android libraries, however, and not directly consuming the SDKs. 

According to [amplify-ios documentation](https://docs.amplify.aws/lib/storage/upload/q/platform/ios/#multipart-upload), the upload automatically enables multipart upload for files that is larger than 5MB.

I'm not sure how amplify-android handles multipart upload at this moment.

**Comment by HuiSF** [comment]
It looks like that in Android, it takes the same approach, [automatically using multipart uploading when file is larger than 5MB](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L571). 

Do you see any issues that multipart uploading doesn't work as expected for you @rabi-palmtree ?

**Comment by rabi-palmtree** [comment]
Thanks, very useful to know.
Will get back after testing for files larger than 5MB.

**Comment by rabi-palmtree** [comment]
Is there a way to get percent indicator for the UX for large file uploads?

**Comment by HuiSF** [comment]
Yes @rabi-palmtree with the `0.2.6` release, a new parameter added to the [`uploadFile`](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_storage_s3/lib/amplify_storage_s3.dart#L49) API that you can get metadata regarding the progress. Please try it out, and follow up if you have any questions.

**Comment by offlineprogrammer** [comment]
Hey @rabi-palmtree 

I am closing this issue for now. We can reopen it if needed and when you provide details.

Regards
Mo
