### ISSUE TITLE
[S3][Android]lastModified in the result of Amplify.Store.list seems wrong (always in 12hours)

### ISSUE THREAD

**Issue by hexch** [aws-amplify/amplify-flutter#1043]
**Describe the bug**
When run  Amplify.Store.list on Android devices to get the file list that stored in S3, the lastModified date time is always in 12-hours.
eg. save a file at 23:00:00 , lastModified will be 11:00:00
(iOS device works fine)

**To Reproduce**
1. upload a file to S3 at 23:00:00
2. run  Amplify.Store.list on Android device
3. the lastModified of the file uploaded in[1.] will be 11:00:00

**Expected behavior**
looks like a bug in this file [line 161]:
https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_storage_s3/android/src/main/kotlin/com/amazonaws/amplify/amplify_storage_s3/AmplifyStorageOperations.kt

**Platform**
[x] Android

**Smartphone (please complete the following information):**
 - Device: [pixel 4a]
 - OS: [Android 11]

**Comment by dnys1** [comment]
Hi @hexch - this has been released with version 0.2.8! 🎉 

Thank you for your contribution to the Amplify framework!

**Comment by hexch** [comment]
Thank you @dnys1 .
