### ISSUE TITLE
Request for one of Flutter's future release to contain only one specific version of Amplify iOS

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-flutter#1065]
Ampify iOS will be releasing https://github.com/aws-amplify/amplify-ios/pull/1490 as a single patch version containing only this change. The reason is to isolate the changes in case there is a need for rollback. Rolling back from this version isn't impossible but comes with some developer painpoint that can't avoided. The migration script in the PR will modify the local metadata keys to a new key format. Older versions of the library operate on the old key format so downgrading requires clearing the local store. 

The request is for when Flutter upgrades its dependency on iOS, to upgrade to the last version of Amplify iOS before the migration version, then release Flutter. Then upgrade to the migration version, and release Flutter again. This way, the changes released in the second Flutter release only contains the migration PR, downgrade will only remove the migration PR, and new Flutter releases will take new changes related to other features/fixes. 

Does Flutter already take patch versions of the native libraries individually or does it upgrade by jumping to the latest released patch version? If the former, then you can ignore this request.

amplify iOS migration version: `1.15.6-unstable.2`

I believe this should be done with Android's [1.28.3](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.28.3) as well.

**Comment by lawmicha** [comment]
Looks like for Android, this is already the latest version minus 1 https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/android/build.gradle#L60-L61

So the request here is that the next time Flutter is released is to release Android 1.28.3

**Comment by HuiSF** [comment]
This request has been fulfilled with amplify-flutter 0.3.0 release.
