### ISSUE TITLE
Datastore Mutation for update cannot be synced to cloud.

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/amplify-flutter#1066]
**Describe the bug**
Datastore Mutation for update cannot be synced to cloud.
We are unable to save data to cloud despite API set up.

**To Reproduce**
1. Follow codelab
2. Fetch an item
3. Create new item with oldItem.copyWith
2. Call Amplify.DataStore.Save(newItem)

**Expected behavior**
Data saved to cloud

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android

<details>
W/amplify:aws-datastore(19416): Error ended observation of mutation outbox: 
W/amplify:aws-datastore(19416): java.lang.RuntimeException: DataStoreException{message=Wanted 1 metadata for item with id = f72a65f3-674d-4a5c-89d3-7632f23429b5, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
W/amplify:aws-datastore(19416): 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
W/amplify:aws-datastore(19416): 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
W/amplify:aws-datastore(19416): 	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)

</details>

**Comment by HuiSF** [comment]
Hi @GMerakis  thanks for reporting this issue. Could you provide some more info for me for triaging this issue?

* Could you provide the model schema that you couldn't save data to cloud?
* Could you please provide a complete code example you executed for the update mutation? (copyWith etc.)

**Comment by GMerakis** [comment]
Thanks!

The schema:
`
type ShoppingSession @model @auth(rules: [{ allow: owner, operations: [create, delete, update] }]) {
    id: ID!
    user_id: ID!
    creation_timestamp: AWSTimestamp
    total: Float!
    status: SessionStatus!
}
`

The Code:
`
Future<void> expireShoppingSession(String shoppingSessionId) async {
  List<ShoppingSession> shoppingSessions =
      await fetchActiveShoppingSessionUserById(); // gets active session

  if (shoppingSessions.length == 1) {
    ShoppingSession newSession = shoppingSessions[0]
        .copyWith(id: shoppingSessions[0].id, status: SessionStatus.EXPIRED);
    await Amplify.DataStore.save(newSession);
  }
}
`

In our screen, this is only called on press like this
`
onPressed: () async {
 ...get session...
 await expireShoppingSession(session.id);
}
`

**Comment by HuiSF** [comment]
Hi @GMerakis sorry missed your comment somehow. 

Were you able to inspect the value of `creation_timestamp` field in the object returned by `copyWith`? 

As this field is `AWSTimestamp`, AppSync will perform service side validation on its value. If the validation fails the data won't written into DynamoDB so you won't be able to see the data in cloud. Currently amplify-flutter doesn't provide unrecoverable error handler, so this type of issue is a bit difficult to be spotted.

In addition, the [preview release `0.3.0-rc.2`](https://pub.dev/packages/amplify_datastore/versions/0.3.0-rc.2/changelog#030-rc2-2021-11-08) of amplify-flutter now provides service managed timestamp fields, so `creation_timestamp` could be omitted. I'd recommend to give it a try :)

**Comment by HuiSF** [comment]
I had a observation regarding this issue:
When any error happened during the initial sync (cold start the App), or anything causes locally saved data syncing to cloud, and after quit the App completely and restart, Android tries to send the locally saved model to cloud, that the exception described in this issue will occur. In this case, the local DB seems fell into a bad state. When delete the App and restart, this error will be eliminated.

**Comment by Jordan-Nelson** [comment]
@GMerakis - If you are still experiencing this issue can you provide the value of `creation_timestamp` field in the object returned by copyWith?
