### ISSUE TITLE
Is it possible to do custom auth with this plugin

### ISSUE THREAD

**Issue by stevegaunt** [aws-amplify/amplify-flutter#1067]
### Discussed in https://github.com/aws-amplify/amplify-flutter/discussions/459

<div type='discussions-op-text'>

<sup>Originally posted by **ggmon** March 19, 2021</sup>
I am trying to do custom auth flow with the user pool I configured following the link https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

I am successful using the JS library, but still not able to with this library on flutter</div>

**Comment by dnys1** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-flutter/issues/410. Updates on support for the custom auth flow will be posted there.
