### ISSUE TITLE
Amplify Pinpoint Event Type - Not appearing in pinpoint console

### ISSUE THREAD

**Issue by adamfillion** [aws-amplify/amplify-flutter#107]
**Describe the bug**
I have an app that is configured with both AWS Cognito and Pinpoint. When I create new AnalyticsEvents (with a non-auth'ed user), the events are logged in the console numerically, but the 'event-type' drop-down never changes to accommodate the new events that I have added. 

For example, if I create a new analytics event of type 'example' and create 10 events and then flush, I will get 10 events in my console but I won't have an event type 'example' under filters->Event.

**To Reproduce**
1. Go to https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_pinpoint/example
2. Initialize a project using `aws analytics add` and `aws push`
3. Create new events and flush them through the app's UI

**Expected behavior**
Upon creating new events with different event types, the AWS Pinpoint -> Analytics -> Events -> Filter -> Event dropdown should reflect the new event types that I created. Thus far, it updates the count but doesn't show that there are new types.

**Screenshots**
![image](https://user-images.githubusercontent.com/33565735/92435118-8d269000-f16f-11ea-9f02-cb1a9e2d78cc.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
Pixel 2 API 3, Android 10+

**Comment by adamfillion** [comment]
Alright, so I just woke up after working on this last night, and it seems to be a latency issue. All of the event types that I submitted are now visible.

I assume this is just a feature of the platform and has nothing to do with Amplify Flutter - so this ticket can probably be closed.

**Comment by fjnoyp** [comment]
Hi @adamfillion thanks for posting the question and the result :) 

I'll close the ticket for now then.
