### ISSUE TITLE
How to use S3 upload without auth through Cognito?

### ISSUE THREAD

**Issue by SahajRana** [aws-amplify/amplify-flutter#108]
Hi Aws team, thanks for bringing an official lib for Flutter!

How can we use S3 (upload) without auth through Cognito?

**Comment by Amplifiyer** [comment]
@SahajRana currently it's not possible to use S3 plugin without Cognito as it is used to sign the S3 requests. You can enable guest access while configuring Auth through CLI such that your app's users wouldn't have to sign in to use S3 resources (by using the guest access)

**Comment by SahajRana** [comment]
I will give `guest access` a try. Thanks.
