### ISSUE TITLE
AWSJSON not showing data

### ISSUE THREAD

**Issue by latheeshvmv** [aws-amplify/amplify-flutter#1082]
**Describe the bug**
I have a model like this
```
type Order
	@model
	@key(name: "byUser", fields: ["playerID"])
	@key(name: "byEmail", fields: ["userEmail"])
	@auth(
		rules: [
			{ allow: owner, identityClaim: "email" }
			{ allow: groups, groups: ["Admins"], operations: [read, create, update, delete] }
		]
	) {
	id: ID!
	qrCodeData: String!
	orderType: OrderTypeEnum
	products: AWSJSON
	productss: [ProductsOrder] @connection(keyName: "byOrder", fields: ["id"])
}
```

Now if I pass the AWSJSON along the mutation
`var operation = Amplify.API.mutate(request: GraphQLRequest<String>(document: document));`

The json data
`[{"id":"2f4f6d37-6351-4ae7-ad3c-f6859b00e1cc","title":"Testing Product 2","image":"{\"bucket\":\"4d751b4dd50548f1b4819e95919c2d17220339-cnewenv\",\"region\":\"ap-southeast-2\",\"key\":\"apppublic/ap-southeast-2:7f0bf265-8e7e-4649-9d38-50515a228d50/1635127878536-food1.jpg\"}","price":34.0,"quantity":1}]`

Even though the mutation happens without any error,  the **data in the backend is empty {}**

Why is this happening? 

Also what is the proper json for the AWS Json Field?

if I try `'{}'` it works, if I try `'{"hello": 20}'` it fails

**To Reproduce**
Pass the above json data to an AWSJSON field

**Expected behavior**
Have the json data show up instead of being an empty json

**Screenshots**
![image](https://user-images.githubusercontent.com/44595562/141403909-66117404-fb2f-450d-bff7-ef04c3d9c381.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[✓] Android
[✓] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/latheeshvm/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/latheeshvm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 017AED16-E1E9-4F95-B699-55A6441612EC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  # Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  amplify_storage_s3:
    dependency: "direct main"
    description:
      name: amplify_storage_s3
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.4"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.1"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  cached_network_image:
    dependency: "direct main"
    description:
      name: cached_network_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  cached_network_image_platform_interface:
    dependency: transitive
    description:
      name: cached_network_image_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  cached_network_image_web:
    dependency: transitive
    description:
      name: cached_network_image_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  convex_bottom_bar:
    dependency: "direct main"
    description:
      name: convex_bottom_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1+5"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  dots_indicator:
    dependency: transitive
    description:
      name: dots_indicator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  editable:
    dependency: "direct main"
    description:
      name: editable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  equatable:
    dependency: "direct main"
    description:
      name: equatable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_blurhash:
    dependency: transitive
    description:
      name: flutter_blurhash
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.2"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  flutter_spinkit:
    dependency: "direct main"
    description:
      name: flutter_spinkit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  flutter_stripe:
    dependency: "direct main"
    description:
      name: flutter_stripe
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  freezed_annotation:
    dependency: transitive
    description:
      name: freezed_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.3"
  get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.8"
  horizontal_data_table:
    dependency: "direct main"
    description:
      name: horizontal_data_table
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.3"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.4+2"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.1"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  introduction_screen:
    dependency: "direct main"
    description:
      name: introduction_screen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.3"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  octo_image:
    dependency: transitive
    description:
      name: octo_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0+1"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  persistent_bottom_nav_bar:
    dependency: "direct main"
    description:
      name: persistent_bottom_nav_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.3"
  provider:
    dependency: transitive
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.0"
  pull_to_refresh:
    dependency: "direct main"
    description:
      name: pull_to_refresh
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0+4"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1+1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  stripe_android:
    dependency: transitive
    description:
      name: stripe_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  stripe_ios:
    dependency: transitive
    description:
      name: stripe_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  stripe_platform_interface:
    dependency: transitive
    description:
      name: stripe_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.9"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
sdks:
  dart: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

  ```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by latheeshvmv** [comment]
```
final jsonEncoder = JsonEncoder();
const JsonEncoder encoder = JsonEncoder.withIndent('  ');
String sta = jsonEncode(encoder.convert(_products));
```

then passing

`products: $sta`

this worked for me. Please correct me if I am wrong

**Comment by HuiSF** [comment]
Hi @latheeshvmv thanks for reporting this issue. A quick side note: I understood that you are using `AWSJSON` as amplify-flutter didn't support CustomType. With the [preview release (0.3.0-rc.2)](https://pub.dev/packages/amplify_datastore/versions/0.3.0-rc.2/changelog#030-rc2-2021-11-08) of amplify-flutter, it now supports CustomType.

```graphql
type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```

**Comment by HuiSF** [comment]
```
'{"hello": 20}'
```

Did you try to escape `"`? e.g.
```
'{\"hello\": 20}'
```

**Comment by latheeshvmv** [comment]
@HuiSF Thanks. Yes I did tried '{\"hello\": 20}'. 

Note sure why it is not working. It's strange.

But this worked https://github.com/aws-amplify/amplify-flutter/issues/1082#issuecomment-967249802 

I had to change my workflow for current project as support for custom  type was missing earlier. Will try it for new projects.

Products might get updated then that will cause the order details to change that's why `@connection `was avoided.

**Comment by HuiSF** [comment]
>But this worked #1082 (comment)

Oh OK, I think `JsonEncoder` is expected to be used in this scenario. It helps to generate a valid json string as what [AppSync requires](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html).
 
>Products might get updated then that will cause the order details to change that's why @connection was avoided.

Got it, you'd like to have a "snapshot" of a `Product` in an `Order`.

>Will try it for new projects.

Just FYI - The CustomType and AWSJSON data stored in DynamoDB is the same under the hood, you should be able to migrate easily by replacing AWSJSON with a CustomType.

**Comment by latheeshvmv** [comment]
@HuiSF Thank you! Yeah sure I will check the preview.

**Comment by latheeshvmv** [comment]
@HuiSF Hello I am still having issues, the solution seemed to be working on simulator. But when I had it implemented on the android real device. It is showing this error Invalid 
**JSON payload in GraphQLAuth POST request.**

How can this be invalid json? 
`"[{\"id\":\"c0de3e1a-7095-4581-8aa0-28d43cf43ae6\"}]"`
`[{"id":"c0de3e1a-7095-4581-8aa0-28d43cf43ae6"}]`

I am just stuck here, with no solutions around.

**Comment by hiru-vn** [comment]
In my case I use variables

```
mutation MyMutation(\$locationData: AWSJSON!) {
   createLocation(input: { locationData: \$locationData }) { id }
}
```

and then put variables like this

 var request = GraphQLRequest<String>(
        document: graphQLDocument,
        variables: {"locationData": "{\"city\" : \"Melborne\"}"});

**Comment by Jordan-Nelson** [comment]
@latheeshvmv - It looks like this fell off of our radar after it was closed. If you are still facing this issue, can you please let us know? Thanks.

**Comment by latheeshvm** [comment]
Yes, It's okay to close this. This happened as I modified the string directly rather than the documented method
