### ISSUE TITLE
API with AuthMode API_KEY giving error "No client information for API"

### ISSUE THREAD

**Issue by rahul-insight** [aws-amplify/amplify-flutter#1090]
**Describe the bug**
We are primarily using AMAZON_COGNITO_USER_POOLS as auth mode for Amplify APIs. For an API to be made public, we have added API_KEY auth mode. The new API with API_KEY works correctly on AWS AppSync console and returns the right response.

After following the steps over [here](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#use-amplify-cli-to-configure-authorization-modes) the new API_KEY configuration is appearing in the "auth" section of amplifyconfiguration.dart instead of the "api" section as mentioned in the document [here](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes)

"auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
               "AppSync": {
                    "[MY_FRIENDLY-NAME-API-WITH-API-KEY]": {
                    "endpointType": "GraphQL",
                    "endpoint": "[GRAPHQL-ENDPOINT]",
                    "region": "[REGION]",
                    "authorizationType": "API_KEY",
                    "apiKey": "[API_KEY]"
                },
},
},
}

Because of this calling the public API with API_KEY auth mode fails with the below error:

`ApiException{message=No client information for API named [MY_FRIENDLY-NAME-API-WITH-API-KEY] cause=null, recoverySuggestion=Check your amplify configuration to make sure there is a correctly configured section for [MY_FRIENDLY-NAME-API-WITH-API-KEY]}`

**To Reproduce**
1. Configure additional auth mode API_KEY as described [here](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#use-amplify-cli-to-configure-authorization-modes)
2. Check that the newly added API_KEY configuration with [MY_FRIENDLY-NAME-API-WITH-API-KEY] is available in amplifyconfiguration.dart
3. Call the API as described in the documentation here 

```
var operation = Amplify.API.string<String>(
    request: GraphQLRequest(
        document: graphQLDocumentString,
        apiName: '[MY_FRIENDLY-NAME-API-WITH-API-KEY]',
    ),
);
var response = await operation.response;
var data = response.data;
```

4. See error:
`No client information for API named [MY_FRIENDLY-NAME-API-WITH-API-KEY] cause=null, recoverySuggestion=Check your amplify configuration to make sure there is a correctly configured section for [MY_FRIENDLY-NAME-API-WITH-API-KEY]}`

**Expected behavior**
The configuration for the API_KEY should be added in amplifyconfiguration.dart in  the "api" section as mentioned in the document [here](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes), so that the API with API_KEY mode can be called and return the results.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.318], locale en-US)
    • Flutter version 2.5.3 at C:\Users\rahul\Projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\rahul\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\rahul\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.78

! Doctor found issues in 1 category.```

</details>

**Comment by rahul-insight** [comment]
Can someone please suggest a solution? We're unable to call the API with API_KEY auth mode.

**Comment by HuiSF** [comment]
Hum that seems odd the API_KEY config got merged under the auth plugin configuration. Need to test the CLI behavior. 
Did you try to manually cut/paste the API_KEY configuration to the `awsAPIPlugin` section and did it work, @rahul-insight ?

**Comment by rahul-insight** [comment]
@HuiSF Yes, I manually copy-pasted that section in `awsAPIPlugin` section and the error disappeared.

**Comment by HuiSF** [comment]
Thanks for confirming @rahul-insight good that manually editing is working, please take it as a workaround for now while we are looking into this issue.

**Comment by rahul-insight** [comment]
@HuiSF 

**Amplify CLI version**: 5.1.2

**Dependencies tree**:

+-- @aws-amplify/cli@5.1.2
| +-- amplify-app@3.0.4
| +-- amplify-category-analytics@2.21.13
| +-- amplify-category-api@2.31.15
| +-- amplify-category-auth@2.35.1
| +-- amplify-category-function@2.33.1
| +-- amplify-category-hosting@2.7.13
| +-- amplify-category-interactions@2.6.2
| +-- amplify-category-notifications@2.19.4
| +-- amplify-category-predictions@2.9.4
| +-- amplify-category-storage@2.12.1
| +-- amplify-category-xr@2.8.13
| +-- amplify-cli-core@1.24.1
| +-- amplify-cli-logger@1.1.0
| +-- amplify-codegen@2.26.2
| +-- amplify-console-hosting@1.9.4
| +-- amplify-container-hosting@1.3.15
| +-- amplify-dotnet-function-runtime-provider@1.6.1
| +-- amplify-dotnet-function-template-provider@1.5.13
| +-- amplify-frontend-android@2.15.3
| +-- amplify-frontend-flutter@0.4.3
| +-- amplify-frontend-ios@2.20.6
| +-- amplify-frontend-javascript@2.23.1
| +-- amplify-go-function-runtime-provider@1.8.7
| +-- amplify-go-function-template-provider@1.3.9
| +-- amplify-java-function-runtime-provider@1.8.6
| +-- amplify-java-function-template-provider@1.5.8
| +-- amplify-nodejs-function-runtime-provider@1.6.3
| +-- amplify-nodejs-function-template-provider@1.6.13
| +-- amplify-provider-awscloudformation@4.55.1
| +-- amplify-python-function-runtime-provider@1.9.3
| +-- amplify-python-function-template-provider@1.3.11
| +-- amplify-util-import@1.5.4
| +-- amplify-util-mock@3.33.5
| +-- aws-sdk@2.963.0
| +-- chalk@3.0.0
| +-- ci-info@2.0.0
| +-- cli-table3@0.6.0
| +-- cloudform-types@4.2.0
| +-- colors@1.4.0
| +-- ejs@3.1.6
| +-- enquirer@2.3.6
| +-- env-editor@0.5.0
| +-- esm@3.2.25
| +-- execa@4.1.0
| +-- folder-hash@4.0.1
| +-- fs-extra@8.1.0
| +-- glob@7.1.7
| +-- global-prefix@3.0.0
| +-- graphql-transformer-core@6.28.13
| +-- gunzip-maybe@1.4.2
| +-- hidefile@3.0.0
| +-- ini@1.3.8
| +-- inquirer@7.3.3
| +-- lodash@4.17.21
| +-- node-fetch@2.6.1
| +-- open@7.4.2
| +-- ora@4.1.1
| +-- parse-json@5.2.0
| +-- progress@2.0.3
| +-- promise-sequential@1.1.1
| +-- semver@7.3.5
| +-- tar-fs@2.1.1
| +-- update-notifier@4.1.3
| +-- which@2.0.2
| `-- winston@3.3.3

**Comment by dnys1** [comment]
@rahul-insight - Can you try upgrading to the latest CLI version with `npm install -g @aws-amplify/cli`, delete the `amplifyconfiguration.dart` file and run `amplify pull` again?

**Comment by Jordan-Nelson** [comment]
@rahul-insight - Have you had a chance to attempt upgrading to the latest CLI version and regenerating the `amplifyconfiguration.dart` file?

**Comment by Jordan-Nelson** [comment]
@rahul-insight - I am going to close this out since we have not heard back for some time. Please feel free to open a new issue if you are still facing this.
