### ISSUE TITLE
"There is already a user which is signed in. Please log out the user before calling showSignIn." Error while login

### ISSUE THREAD

**Issue by bhautikcoretus** [aws-amplify/amplify-flutter#1091]
**Describe the bug**
when I Sign Out with "Amplify.Auth.signOut()"and login again than I got this error.

**Login Provider**
- Apple

**Platform**
[] iOS

**Comment by Jordan-Nelson** [comment]
Hello @bhautikcoretus - Was there previously a user signed in on that device? If so, what login method was used (username/password, social sign in, etc.)?

**Comment by Jordan-Nelson** [comment]
@bhautikcoretus - If you are still experiencing this issue, please provide the info requested above. Thanks.
