### ISSUE TITLE
How to handle CONFIRM_SIGN_IN_WITH_NEW_PASSWORD after authentication

### ISSUE THREAD

**Issue by danielvtan** [aws-amplify/amplify-flutter#110]
**Describe the bug**
How to handle CONFIRM_SIGN_IN_WITH_NEW_PASSWORD after authentication

**To Reproduce**
1. Register new user in cognito
2. Login new user in app
3. Will not be able to login with result of res.nextStep.signInStep "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD"

**Expected behavior**
Cant seem to find this feature in docs

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[x] Android
[] iOS

**Comment by danielvtan** [comment]
This is blocking for us in our development progress. do you have any idea when will this be available? Can you point where this issue is, maybe we can help?

thank you!

**Comment by danielvtan** [comment]
We made a temporary solution thru our backend. We automatically verify our users using adminInitiateAuth and adminRespondToAuthChallenge right after cognito registration.

Thanks!

**Comment by fjnoyp** [comment]
Hi @danielvtan thanks for explaining the issue and your subsequent workaround.  We are aware of this issue and will look into it.

**Comment by gatanaso** [comment]
Hi @danielvtan,

What worked in our case is that after step 2 (when we receive the `CONFIRM_SIGN_IN_WITH_NEW_PASSWORD`), we call `Amplify.Auth.confirmSignIn(confirmationValue: password)`  where `password` is the user's new password value which they enter in a text field.

Not sure if this is the "correct" way to handle this sign in step, but after the call to `confirmSignIn` the user is also marked as `CONFIRMED` in the Cognito console.

Hope this helps,
Goran

**Comment by haverchuck** [comment]
Thanks @gatanaso!  I'm closing this issue for now.

**Comment by SalahAdDin** [comment]
@haverchuck this repository should have the @gatanaso answer as documentation.
