### ISSUE TITLE
Amplify Storage : How to copy a file to a different key

### ISSUE THREAD

**Issue by rabi-palmtree** [aws-amplify/amplify-flutter#1114]
**Describe the bug**
We are effectively using Flutter Amplify Storage to manage S3 storage usecases.
One requirement is to copy(duplicate) an existing S3 resource to a new key.
Basically do what amplify JS does with Storage.copy
https://docs.amplify.aws/lib/storage/copy/q/platform/js/

How do we that?
The only workaround I can think of is from the app to 
1. First do Amplify.Storage.downloadFile  
2. Then do Amplify.Storage.uploadFile with the new key

But clearly that is wasteful use of resources

**Expected behavior**
Please support Amplify.Storage.copy as in your JS implemenation

**Comment by abdallahshaban557** [comment]
Hi @rabi-palmtree  - Thank you for your feedback! We are adding this request into our backlog.

**Comment by fjnoyp** [comment]
Hi @rabi-palmtree Amplify-Flutter is built on native behavior on Amplify-iOS and Amplify-Android.  Unfortunately they do not yet support doing this copy operation and have no plans to implement it at the moment.  

Consequently, for now we don't have any plans to add this feature-request. I'll mark this as pending close. If you disagree with this decision please let us know the reason and we can consider reopening and reprioritizing.

**Comment by HuiSF** [comment]
Hi @rabi-palmtree we've released amplify-flutter [v1.0.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0). The Storage S3 plugin now provides the [`copy` API](https://docs.amplify.aws/lib/storage/copy/q/platform/flutter/) to support a use case like this. Please check out the linked documentation to learn about the detail.
