### ISSUE TITLE
Question about Database Support

### ISSUE THREAD

**Issue by adamfillion** [aws-amplify/amplify-flutter#112]
Hey guys, 

I have received a few questions regarding database support for Amplify Flutter (eg. what is the equivalent to Firestore?). 

What are the future plans for integrating some of AWS database solutions with Flutter?

Thanks a lot,

Adam

**Comment by Ashish-Nanda** [comment]
Hi @adamfillion 

We are currently working on adding support for data related categories like API (Rest & GraphQL) and DataStore.

DataStore is what I believe you are looking for, as it provides a programming model for leveraging shared and distributed data and supports real-time and offline scenarios. Amplify JavaScript, iOS & Android already support this and you can learn more about it in our [docs](provides a programming model for leveraging shared and distributed data without writing additional code for offline and online scenarios, which makes working with distributed, cross-user data just as simple as working with local-only data)

Support for DataStore in Amplify Flutter is being worked on right now. You find out more about this and other details about the library design and upcoming features in our [RFC](https://github.com/aws-amplify/amplify-flutter/issues/5). I suggest you engage with us on the RFC itself if you have further questions or suggestions about DataStore as we are using that to track the feature.

**Comment by adamfillion** [comment]
Perfect, I will definitely check it out. Thank you for the prompt reply.
