### ISSUE TITLE
Amplify Notification being created in wrong region?

### ISSUE THREAD

**Issue by latheeshvmv** [aws-amplify/amplify-flutter#1130]
**Describe the bug**

I used the `amplify add notification` in my flutter project. I have the server in Sydney but this resource got created on the **Oregon**? . Why is this happening.

I have managed to do the push notification using the Firebase and Pinpoint. Tested the pinpoint using device token and it is working fine. 

I have a react admin backend for the the flutter app.

Is it possible to provide an admin UI(react) so that it connects to pinpoint? So that notifications can sent via admin side? If yes. Please let me where can I find the documentation for that. 

Also the pinpoint seems to require device token? How can I get the device token for each user? Do I have to generate this and save it some where?

Thanks

**To Reproduce**

1. Have a flutter project in sydney
2. Do the `amplify add analytics`
3. Do the `amplify add notifications`

**Expected behavior**
Resource be under same region?

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[✓] Android
[✓] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/latheeshvm/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/latheeshvm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 017AED16-E1E9-4F95-B699-55A6441612EC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  Paste the contents of your "pubspec.lock" file here
  ```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by HuiSF** [comment]
Hi @latheeshvmv Sorry, I don't think amplify-flutter supports the notification category at this moment. 
We have a feature request tracking issue https://github.com/aws-amplify/amplify-flutter/issues/319

Therefore, using CLI adding `notifications` category is currently out of scope. I will close this thread in favor of #319 for now.
