### ISSUE TITLE
GraphQL mutate operation failing with NonRetryableException using Amplify appsync API

### ISSUE THREAD

**Issue by CyberIkshit** [aws-amplify/amplify-flutter#1140]
I'm getting the error: Invalid JSON payload in GraphQLAuth POST request from Amplify.API.mutate with `NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}`, but if I try running the same mutation directly in aws console, the mutation is working just fine.

Here's the mutation string that I am using-:
```
static String updatePaxJourneyQuery =
      '''mutation updateJourney(\$paxId: Int!, \$currentLocationId: Int, \$reportLocationId: Int, \$ssrRemarks: String, \$updatedBy: String, \$reportedTime: String, \$expectedLocationId: Int, \$expectedDateTime: String){
updatePaxJourney(paxId: \$paxId, currentLocationId:  \$currentLocationId, reportLocationId: \$reportLocationId, ssrRemarks: \$ssrRemarks, updatedBy:  \$updatedBy,reportedTime:	 \$reportedTime, expectedLocationId: \$expectedLocationId, expectedDateTime: \$expectedDateTime){
	paxGantt
	}
}''';
```

And the mutation function that I am calling-:
```
static Future<Map<String, dynamic>> updatePaxJourney(
      {int paxId, int currentLocationId, int reportLocationId, String ssrRemarks, String updatedBy, String reportedTime, int expectedLocationId, String expectedDateTime}) async {
    Map<String, dynamic> listValues;
    try {
      var operation = Amplify.API.mutate(
          request: GraphQLRequest<String>(
              document: updatePaxJourneyQuery,
              variables: {
            "paxId": paxId,
            "currentLocationId": currentLocationId,
            "reportLocationId": reportLocationId,
            "ssrRemarks": ssrRemarks,
            "updatedBy": updatedBy,
            "reportedTime": reportedTime,
            "expectedLocationId": expectedLocationId,
            "expectedDateTime": expectedDateTime
          }));
      var response = await operation.response;
      var data = response.data;
      print("Response from update pax journey" + data.toString());
      if (data != "") {
        Map<String, dynamic> res = json.decode(data);
        return res;
      }
      print("Data not available " + response.errors.toString());
      return listValues;
    } on ApiException catch (e) {
      print('Mutation failed: $e');
      return listValues;
    } catch (e) {
      print('Fatal Error: ' + e.toString());
      return listValues;
    }
  }
```

On calling the above mentioned function, I am getting this error-:
```
GraphQL mutate operation failed
NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
[GraphQLResponseError{
  "message": "Invalid JSON payload in GraphQLAuth POST request.",
  "extensions": {
    "errorType": "MalformedHttpRequestException"
  }
}]
```

Pls someone look into this issue.

**Comment by Jordan-Nelson** [comment]
Hello - can you confirm that you are experiencing this on Android?

Can you share your grapghql schema?

**Comment by Jordan-Nelson** [comment]
Hi @CyberIkshit - Do you have a schema.graphql file in your project that you can share?

Can you also share an example code snippet with the values you apr passing into `updatePaxJourney()`? Something like:

```dart
updatePaxJourney(
  paxId: 123,
  currentLocationId: 1,
  reportLocationId: 1,
  ssrRemarks: 'foo',
  updatedBy: 'foo',
  reportedTime: 'foo',
  expectedLocationId: 1,
  expectedDateTime: 'foo',
)

Thanks!

**Comment by CyberIkshit** [comment]
Hi @Jordan-Nelson, 

Here's an example code snippet that u were asking for-:
```
  updatePaxJourney(
    paxId: 2245,
    currentLocationId: 56,
    reportLocationId: 56,
    ssrRemarks: "WCHC",
    updatedBy: "ikshit@gmail.com",
    reportedTime: "2021-11-29T13:01:58Z",
    expectedLocationId: 0,
    expectedDateTime: "2021-11-29T13:01:58Z",
  )
```

and the schema.graphql file for your refernce-:
[schema.zip](https://github.com/aws-amplify/amplify-flutter/files/7618219/schema.zip)

**Comment by Jordan-Nelson** [comment]
Hello @CyberIkshit - That looks like it is a schema file exported from the app sync console. Do you have a local schema.graphql file you are using with amplify? It should be located at `/amplify/backend/api/<APP_NAME>/schema.graphql`.

I think there are some issues with the grapphql document you are using. There are examples that you can look at [here](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter/). See below an updated grapphql document for an update. I removed several fields just for simplicity, but you should be able to add them back. I also added an ID for the `PaxJourney` object, which will be the ID of the object to update.

```dart
const String graphQLDocument =
    '''mutation UpdatePaxJourney(\$id: ID!, \$paxId: Int, \$currentLocationId: Int){
          updatePaxJourney(input: { id: \$id, paxId: \$paxId, currentLocationId: \$currentLocationId}) {
            id
            paxId
            currentLocationId
          }
        }''';
```

**Comment by CyberIkshit** [comment]
We don't use ID as it was creating problems in maintaining our project so we are using an integer for ID too...Same mutation is working fine in our angular web project. Pls find the attached local schema.graphql file for ur reference
[schema.zip](https://github.com/aws-amplify/amplify-flutter/files/7625272/schema.zip)

**Comment by ragingsquirrel3** [comment]
@CyberIkshit thanks for all the helpful info. I was able to reproduce this and can suggest some fixes/workarounds, although there may still be some missing info.

I was able to make the mutation work like this:
```dart
      // indent with spaces, not tabs
      String updatePaxJourneyQuery =
          '''mutation updateJourney(\$currentLocationId: Int, \$paxId: Int!, \$reportLocationId: Int, \$ssrRemarks: String, \$updatedBy: String){
              updatePaxJourney(currentLocationId: \$currentLocationId, paxId: \$paxId, reportLocationId: \$reportLocationId, ssrRemarks: \$ssrRemarks, updatedBy: \$updatedBy){
                paxGantt
              }
            }''';

      var operation = Amplify.API.mutate(
          request: GraphQLRequest<String>(
              document: updatePaxJourneyQuery,
              variables: <String, dynamic>{
            "paxId": paxId,
            "currentLocationId": currentLocationId,
            "reportLocationId": reportLocationId,
            "ssrRemarks": ssrRemarks,
            "updatedBy": updatedBy
            // had to remove these from here and document
            // "reportedTime": reportedTime,
            // "expectedLocationId": expectedLocationId,
            // "expectedDateTime": expectedDateTime
          }));
      var response = await operation.response;
      var data = response.data;
```

Let me explain what I found and how I got here. I found the following issues:
1) the graphql document string, at least as I found in above correspondence was indented with tabs, not spaces. This seems to cause the android amplify client (which is used here) to throw the malformatted exception. This does not seem to be an issue on ios. Replacing tabs with spaces caused the request to at least go out through the client.
2) the mutation request has some variables which are not in the mutation schema `updatePaxJourney`. In ios and android (once tabs were replaced) I got an error from appsync response indicating that `reportedTime` `expectedLocationId` and `expectedDateTime` were not in the `updatePaxJourney` mutation. When I look at the schema you included, I see that indeed those variables were not included in the schema. Per the graphql spec, the variables must be explictly defined so I believe the appsync behavior is expected here. If you want to include these variables in the mutation, you might try adding them to the `updatePaxJourney` in your schema, updating and seeing if it works. It's also helpful to debug this in appsync console as these errors can be reproduced there (at least in the amplify backend I made from your schema)

You mentioned the same mutation works on web from an angular client. Is that client using the same AppSync backend/schema? If so, I might be missing something as I would expect all clients to be unable to pass those extra variables along.

Hopefully this is helpful. Thanks again for all the helpful info.

**Comment by ragingsquirrel3** [comment]
added https://github.com/aws-amplify/amplify-flutter/issues/1175 for tab issue here

**Comment by CyberIkshit** [comment]
Hi @ragingsquirrel3 @Jordan-Nelson , thanks for all ur time and support...and really sry for the late reply actually I was trying to get the job done by following the suggestions/improvements you've provided above. Finally, I was able to make it work by writing the string in notepad and I guess problem was with some spaces/tabs only.

Ps-: Just a suggestion, that it would be better if you could add graphQL string validation in future updates, eventually it will save a lot of time and effort of developers. As writing and debugging errors in strings is quite stressing.

You can close this issue, and **thanks again for your help!**
