### ISSUE TITLE
Invalid JSON payload in GraphQLAuth POST request. For android devices

### ISSUE THREAD

**Issue by latheeshvmv** [aws-amplify/amplify-flutter#1143]
**Describe the bug**
I am having the strange issue which works fine on ios simulator and graphql console but fails on android device.

The error is
**Invalid JSON payload in GraphQLAuth POST request.**

This is my model ( Note I am using graphQL for the app)
```
type Order
	@model
	@key(name: "byUser", fields: ["playerID"])
	@key(name: "byEmail", fields: ["userEmail"])
	@auth(
		rules: [
			{ allow: owner }
			{ allow: groups, groups: ["Admins"], operations: [read, create, update, delete] }
		]
	) {
	id: ID!
	orderStatus: OrderStatusEnum!
	paymentStatus: PaymentStatusEnum!
	orderProcessStatus: OrderProcessStatusEnum!
	qrCodeData: String!
	orderType: OrderTypeEnum
	products: AWSJSON
	playerID: String!
	orderTotal: Float!
	userLocation: String
	userFullName: String!
	userEmail: String!
	userPhoneNumber: String
	orderData: AWSJSON
	stripeCustomerID: String!
	productss: [ProductsOrder] @connection(keyName: "byOrder", fields: ["id"])
}
```

```
mutation MyMutation {
              createOrder(input: { 
                  userEmail: "wp@gmail.com", 
                  playerID: "4393f66b-9247-4466-bfa1-494fcc95f787", 
                  userLocation: "Table 30", 
                  userPhoneNumber: "+91965613",
                  orderStatus: YETTOPROCESS,
                  orderTotal: 57.0,
                  orderType: ONCOURSE,
                  paymentStatus: PAID,
                  qrCodeData: "QR Table 1",
                  stripeCustomerID: "cus_Kd7D7dglzOJ",
                  userFullName : "Team wp",
                  orderProcessStatus : PENDINGAPPROVAL,
                  products: "[\n  {\n    \"id\": \"2f4f6d37-6351-4ae7-ad3c-f6859b00e1cc\",\n    \"title\": \"Testing Product 2\",\n    \"image\": {\n      \"bucket\": \"4d751b4dd50548f1b4819e99c2d17220339-oxlnewenv\",\n      \"region\": \"ap-southeast-2\",\n      \"key\": \"apppublic/ap-southeast-2:7f0bf265-e-4649-9d38-50515a228d50/1635127878536-food1.jpg\"\n    },\n    \"price\": 34.0,\n    \"quantity\": 1\n  },\n  {\n    \"id\": \"c0de3e1a-7095-4581-8aa0-28d43cf43ae6\",\n    \"title\": \"Testing\",\n    \"image\": {\n      \"bucket\": \"4d751b4dd50548f1b4819e9591d17220339-oxlnewenv\",\n      \"region\": \"ap-southeast-2\",\n      \"key\": \"apppublic/ap-southeast-2:7f0bf265-8e7e-4649-9d38-55a228d50/1635057833949-food2.jpg\"\n    },\n    \"price\": 23.0,\n    \"quantity\": 1\n  }\n]",
                  orderData : "[\n  {\n    \"id\": \"2f4f6d37-6351-4ae7-c-f6859b00e1cc\"\n  },\n  {\n    \"id\": \"c0de3e1a-70981-8aa0-28d43cf43ae6\"\n  }\n]",
                }) {    
                orderProcessStatus
                orderStatus
                owner
                id
                orderData
                orderTotal
                orderType
                paymentStatus
                playerID
                products
                qrCodeData
                stripeCustomerID
                updatedAt
                userEmail
                userFullName
                userLocation
                userPhoneNumber
                createdAt
              }
            }
```

and I am passing the doument
 ```
 var operation = Amplify.API.mutate(request: GraphQLRequest<String>(document: document));

      var response = await operation.response;
      inspect(response);
```

**To Reproduce**
1.create a model with AWSJSON
2.pass the json I have used
3.Check the response in app sync console ( It will work fine)
4.Check the response in connected android device. ( it will throw error)

**Expected behavior**
Mutation to happen on all devices

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[✓] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```latheeshvm@Latheeshs-iMac ox_top_stroke % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/latheeshvm/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/latheeshvm/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • RMX3081 (mobile)   • 5b331ab8                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile) • 017AED16-E1E9-4F95-B699-55A6441612EC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  # Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  amplify_analytics_pinpoint:
    dependency: "direct main"
    description:
      name: amplify_analytics_pinpoint
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_core:
    dependency: "direct main"
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  amplify_storage_s3:
    dependency: "direct main"
    description:
      name: amplify_storage_s3
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.1"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  cached_network_image:
    dependency: "direct main"
    description:
      name: cached_network_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  cached_network_image_platform_interface:
    dependency: transitive
    description:
      name: cached_network_image_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  cached_network_image_web:
    dependency: transitive
    description:
      name: cached_network_image_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  convex_bottom_bar:
    dependency: "direct main"
    description:
      name: convex_bottom_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1+5"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  dbus:
    dependency: transitive
    description:
      name: dbus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.6"
  dots_indicator:
    dependency: transitive
    description:
      name: dots_indicator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  editable:
    dependency: "direct main"
    description:
      name: editable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  equatable:
    dependency: "direct main"
    description:
      name: equatable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  extended_image:
    dependency: "direct main"
    description:
      name: extended_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.3"
  extended_image_library:
    dependency: transitive
    description:
      name: extended_image_library
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.0"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "11.1.0"
  firebase_messaging_platform_interface:
    dependency: transitive
    description:
      name: firebase_messaging_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.9"
  firebase_messaging_web:
    dependency: transitive
    description:
      name: firebase_messaging_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_blurhash:
    dependency: transitive
    description:
      name: flutter_blurhash
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.2"
  flutter_local_notifications:
    dependency: "direct main"
    description:
      name: flutter_local_notifications
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.1.2"
  flutter_local_notifications_linux:
    dependency: transitive
    description:
      name: flutter_local_notifications_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
  flutter_local_notifications_platform_interface:
    dependency: transitive
    description:
      name: flutter_local_notifications_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  flutter_spinkit:
    dependency: "direct main"
    description:
      name: flutter_spinkit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  flutter_stripe:
    dependency: "direct main"
    description:
      name: flutter_stripe
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  freezed_annotation:
    dependency: transitive
    description:
      name: freezed_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.3"
  get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.8"
  horizontal_data_table:
    dependency: "direct main"
    description:
      name: horizontal_data_table
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.3"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  http_client_helper:
    dependency: transitive
    description:
      name: http_client_helper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  im_stepper:
    dependency: "direct main"
    description:
      name: im_stepper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.4+2"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.1"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  introduction_screen:
    dependency: "direct main"
    description:
      name: introduction_screen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.3"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  octo_image:
    dependency: transitive
    description:
      name: octo_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0+1"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.3.0"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.7.0"
  persistent_bottom_nav_bar:
    dependency: "direct main"
    description:
      name: persistent_bottom_nav_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.3"
  provider:
    dependency: transitive
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.0"
  pull_to_refresh:
    dependency: "direct main"
    description:
      name: pull_to_refresh
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  qr_code_scanner:
    dependency: "direct main"
    description:
      name: qr_code_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  rxdart:
    dependency: "direct main"
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0+4"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1+1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  stripe_android:
    dependency: transitive
    description:
      name: stripe_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  stripe_ios:
    dependency: transitive
    description:
      name: stripe_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  stripe_platform_interface:
    dependency: transitive
    description:
      name: stripe_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  timeline_tile:
    dependency: "direct main"
    description:
      name: timeline_tile
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  timezone:
    dependency: transitive
    description:
      name: timezone
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.0"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.9"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.3.1"
sdks:
  dart: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

  ```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Jordan-Nelson** [comment]
Hi @latheeshvmv - Can you share the definitions for the enums you are using? It would be helpful to see the definition in the graphql as well as the dart code.

**Comment by latheeshvmv** [comment]
@Jordan-Nelson Kindly ignore the enums. The problem is only with the AWS JSON field.

**Comment by latheeshvmv** [comment]
just incase if you need it
enum OrderTypeEnum {
	ONCOURSE
	ONTABLE
}

enum OrderProcessStatusEnum {
	PENDINGAPPROVAL
	APPROVED
	PROCESSING
	READYTODELIVER
	DELIVERED
}

enum PaymentStatusEnum {
	PAID
	PENDINGPAYMENT
	BANKDECINED
	REFUNDED
}

enum OrderStatusEnum {
	COMPLETED
	CANCELED
	REFUNDED
	YETTOPROCESS
}

**Comment by latheeshvmv** [comment]
@Jordan-Nelson Wasted another day.

How can this be an invalid json? Why this fails on android alone. Works on ios simulator and graphql console
`[{\"id\":\"c0de3e1a-7095-4581-8aa0-28d43cf43ae6\"}]`

Invalid JSON payload in GraphQLAuth POST request."

```
mutation MyMutation {
              createOrder(input: { 
                  userEmail: "wpheesh@gmail.com", 
                  playerID: "4393f66b-947-4466-bfa1-494fcc95f787", 
                  userLocation: "Table 30", 
                  userPhoneNumber: "+9196559613",
                  orderStatus: YETTOPROCESS,
                  orderTotal: 23.0,
                  orderType: ONCOURSE,
                  paymentStatus: PAID,
                  qrCodeData: "QR Table 1",
                  stripeCustomerID: "cus_K9iH7dglzOJ",
                  userFullName : "Team wp",
                  orderProcessStatus : PENDINGAPPROVAL,        
                  orderData : "[{\"id\":\"c0de3e1a-7095-4581-8aa0-28d43cf43ae6\"}]",
                }) {    
                orderProcessStatus
                orderStatus
                owner
                id
                orderData
                orderTotal
                orderType
                paymentStatus
                playerID
                products
                qrCodeData
                stripeCustomerID
                updatedAt
                userEmail
                userFullName
                userLocation
                userPhoneNumber
                createdAt
              }
            }
```


```
 JsonEncoder encoder = JsonEncoder();
var _orderData = jsonEncode(encoder.convert(data["orderData"]));
```

this being passed to 

```
String document = '''mutation MyMutation {
        createOrder(input: { 
            userEmail: "$_userEmail", 
            playerID: "$_playerID", 
            userLocation: "$_userLocation", 
            userPhoneNumber: "$_userPhoneNumber",
            orderStatus: $_orderStatus,
            orderTotal: $_orderTotal,
            orderType: $_orderType,
            paymentStatus: $_paymentStatus,
            qrCodeData: "$_qrCodeData",
            stripeCustomerID: "$_stripeCustomerID",
            userFullName : "$_playerName",
            orderProcessStatus : $_orderProcessStatus,        
            orderData : $_orderData,
          }) {    
          orderProcessStatus
          orderStatus
          owner
          id
          orderData
          orderTotal
          orderType
          paymentStatus
          playerID
          products
          qrCodeData
          stripeCustomerID
          updatedAt
          userEmail
          userFullName
          userLocation
          userPhoneNumber
          createdAt
        }
      }''';

```

**Comment by abdallahshaban557** [comment]
@latheeshvmv  - just noticed you closed this issue. Was your issue resolved?

**Comment by hiru-vn** [comment]
how to fix this issue?

**Comment by latheeshvmv** [comment]
@abdallahshaban557 @hiru-vn Missed the git notification email. It works. Make sure you are doing the mutation exactly as documented. 

 var operation = Amplify.API.mutate(
          request: GraphQLRequest<String>(document: documentup, variables: {})); if you are modifying the document without variables then it will not work.
