### ISSUE TITLE
Amplify.Auth.signInWithWebUI with Apple don't work

### ISSUE THREAD

**Issue by joshuafriso** [aws-amplify/amplify-flutter#1146]
**Describe the bug**
I configured the Amplify to sign-in with Facebook and Apple, but when I try to sign-in with Apple the error occours in the last part, when need to return to the app and finsih login.
Facebook sign-in work well

**To Reproduce**
1. Go to login with Apple
2. Do login, insert the auth code
3. Click in Continue
4. See error on console

**Screenshots**
![error_login_apple](https://user-images.githubusercontent.com/17890321/143935271-deb29f50-f2e8-4710-a35c-9fddd5be1e51.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  
![image](https://user-images.githubusercontent.com/17890321/143935318-8cc475e8-c0d2-4352-99c6-84ea8479706c.png)

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
 ![image](https://user-images.githubusercontent.com/17890321/143935402-6025f4a3-1297-4471-8dff-81ef9b2932a9.png)

</details>

**Additional context**
![image](https://user-images.githubusercontent.com/17890321/143935453-a6695a4f-1fea-4cfb-937e-2416d75f2475.png)
![image](https://user-images.githubusercontent.com/17890321/143935480-73ba758a-882f-4fbd-8243-6b7d3a9e852e.png)
![image](https://user-images.githubusercontent.com/17890321/143935507-5e6c0d99-913a-48f4-a970-6334e768e267.png)

![image](https://user-images.githubusercontent.com/17890321/143935784-74a888cc-47fc-4a7c-9565-e6e2375f0aa3.png)

**Comment by Sunsiha** [comment]
@joshuafriso Hi, Have u got any solution for this?

**Comment by Jordan-Nelson** [comment]
Hello @joshuafriso - Can you please fill out the information in the [issue template](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=bug_report.md&title=)? Thanks.

**Comment by joshuafriso** [comment]
@Jordan-Nelson done

**Comment by Jordan-Nelson** [comment]
Thanks @joshuafriso

Just to clarify, you are experiencing this behavior on iOS and Android, correct? The screenshots appear to be Android, but I see that you have selected iOS and Android in the template. 

Are you running it on a physical device or on a simulator/emulator?

Can you verify that you have followed all of the steps for [sign in with apple from the amplify-flutter docs](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/)?

**Comment by joshuafriso** [comment]
@Jordan-Nelson 
I verified all the steps more than once but I recieve the same error.
Using the url to test in browser I can see on the console this error:

![image](https://user-images.githubusercontent.com/17890321/143946567-c9b65878-714d-48ce-a460-0412d53ebb96.png)
![image](https://user-images.githubusercontent.com/17890321/143946627-a8236cf6-c6b2-419e-b026-14b69dbfe188.png)
![image](https://user-images.githubusercontent.com/17890321/143946678-fa21cae1-dc5b-481c-bc14-df2bc012d66f.png)

**Comment by Jordan-Nelson** [comment]
@joshuafriso do you have "name" as a required attribute in Cognito?

**Comment by joshuafriso** [comment]
@Jordan-Nelson yes, when I created another pool without name as required I received invalid_client but the user was created in cognito and the signin didn't work

**Comment by Jordan-Nelson** [comment]
Okay. `invalid_client` might indicate something is configured incorrectly. Do you have that full error message?

**Comment by joshuafriso** [comment]
AuthException (AuthException(message: Sign-in with web UI failed, recoverySuggestion: See attached exception for more details, underlyingException: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_client))

**Comment by Sunsiha** [comment]
social loginAuthException(message: Sign-in with web UI failed, recoverySuggestion: See attached exception for more details, underlyingException: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request)

**Comment by joshuafriso** [comment]
@Jordan-Nelson using my original pool, i was able to log in when i created a new apple ID, it worked fine, but using my own Apple ID is not working

**Comment by Jordan-Nelson** [comment]
I am going to close this out since I have not heard back. Please open a new issue if you are still experiencing this issue.
