### ISSUE TITLE
WebSocket api support in amplify-flutter

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#1147]
**Feature Request**
Hello team!, is there any planning to support WebSocket API with amplify?

Here is the use case in which I need WebSockets: 
Using Graphql API queries doesn't seem to be a good practice in front-end, due to hard-coded queries, easily interceptable and modifiable queries using burp, etc. There is a solution that can be done by writing auth rules for each field, but it's not very good for a big application that has many data models. 
So I am just using Rest APIs to make GET/PUT/POST/DELETE request with IAM_AUTH, validating the request and sending back what is meant for the user, with a custom response. But for subscription on any doc, there is no solution, that's why for this use case, I need WebSocket so that user can subscribe for a blog and get an update when someone hit an upvote or comment.
 
Thanks.

**Comment by Jordan-Nelson** [comment]
Hello - Graphql API [supports subscriptions](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/flutter/). Would this meet your use case?

**Comment by hackrx** [comment]
Hey @Jordan-Nelson, I no longer need any WebSocket API, now I am using subscriptions only.
Thanks.
