### ISSUE TITLE
[Docs] Fix typo: "_fetchTodos()" -> "_configureAmplify()"

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#1150]
**Description**

Fix the typo noted here: https://github.com/aws-amplify/docs/issues/3495 by replacing the text: "_fetchTodos()" -> "_configureAmplify()"

**Comment by abdallahshaban557** [comment]
@dnys1  - I believe this is no longer needed. I have resolved the docs issue.
