### ISSUE TITLE
[Docs] Improve documentation of `DataStore.observe`

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#1151]
**Description**

https://github.com/aws-amplify/docs/issues/3233

Improve the documentation of the `DataStore.observe` API with examples and explanations: https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/

**Comment by abdallahshaban557** [comment]
I am closing this issue as a duplicate of the Docs issue https://github.com/aws-amplify/docs/issues/3233
