### ISSUE TITLE
Amplifyconfiguration.dart

### ISSUE THREAD

**Issue by Pavi08** [aws-amplify/amplify-flutter#1152]
can you share amplifyconfiguration.dart file you mentioned in your example.

**Comment by HuiSF** [comment]
Hi @Pavi08 thanks for opening this issue.

`amplifyconfiguration.dart` usually contains credentials of a AWS service, therefore unfortunately it's not sharable. However, you can follow [the instruction](https://github.com/aws-amplify/amplify-flutter/tree/main/example#getting-started) to generate a `amplifyconfiguration.dart` that is specific to your own AWS service account.

**Comment by Pavi08** [comment]
Can you please share some instructions  to generate amplifyconfiguration.dart

**Comment by Pavi08** [comment]
Thank you

**Comment by fjnoyp** [comment]
Great let us know if there's any issues in the doc.  For now will close the issue.  @Pavi08

**Comment by CartmanGD** [comment]
How do I generate the `amplifyconfiguration.dart` file for an existing AWS project? All AWS examples are for initiating new projects from scratch.

**Comment by AlbertoBaroso** [comment]
> How do I generate the `amplifyconfiguration.dart` file for an existing AWS project? All AWS examples are for initiating new projects from scratch.

Try running `amplify init` in the root directory of your project, it should generate the `amplifyconfiguration.dart` file even for an already existing AWS project.

**Comment by akhilgadwal** [comment]
how connect to existing AWS resources in flutter app as I don't have amplifyconfiguration.dart file in project 
and how to use  api gateway base URL, the s3 bucket we are using, the cognito user pool ID, the app client ID and the IAM identity pool ID in flutter app
