### ISSUE TITLE
graphql document string with tabbed (not spaced) indent causes client NonRetryableException Android

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-flutter#1175]
**Describe the bug**

Send a graphql request with a document string indented with tabs (not spaces). Like

```dart
    String graphQLDocument = '''query MyQuery {
      listBlogs {
      \titems {
          id
          name
          createdAt
        }
      }
    }''';

    var operation = Amplify.API
        .query<String>(request: GraphQLRequest(document: graphQLDocument));
```

On android, throws:

```
E/amplify:flutter:api(22539): GraphQL mutate operation failed
E/amplify:flutter:api(22539): NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E/amplify:flutter:api(22539): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
E/amplify:flutter:api(22539): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:flutter:api(22539): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:api(22539): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:api(22539): 	at java.lang.Thread.run(Thread.java:923)
I/flutter (22539): Result data: 
W/AtomicResult(query)(22539):                     Attempted to send error value after initial reply:
W/AtomicResult(query)(22539):  PlatformException{code=ApiException, message=Translating platform exception failed. Please take a look at
```

works fine on iOS

**Expected behavior**

Request should work the same if indented with tabs/spaces.

This may be android issue https://github.com/aws-amplify/amplify-android/issues/1596 but flutter could workaround by removing this whitespace on dart side before sending to platform.

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Paste your output of "flutter doctor -v" here```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  Paste the contents of your "pubspec.lock" file here
  ```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Hevton** [comment]
How can i fix it..?
in my case, sending '\n' makes NonRetryableException...

**Comment by chrisbonifacio** [comment]
> How can i fix it..? in my case, sending '\n' makes NonRetryableException...

Hi, can you provide an example query and/or code snippet that is reproducing that error?
