### ISSUE TITLE
Able to sign in, after deleting the user from aws cognito console

### ISSUE THREAD

**Issue by dineshkumar02** [aws-amplify/amplify-flutter#118]
After completing the signup, and sing in, I deleted the user from cognito console. And tried to sign in from the device, which is still working.

**To Reproduce**
1. Do signup
2. Do signin
3. Delete the user from aws cognito console (Web UI)
4. Try sign in again from the code.

**Expected behavior**
User should not sign in 

**Log message**

D/AWSMobileClient(19143): _federatedSignIn: Putting provider and token in store
D/AWSMobileClient(19143): Inspecting user state details
D/AWSMobileClient(19143): hasFederatedToken: true provider: cognito-idp.***
D/AWSMobileClient(19143): Inspecting user state details
D/AWSMobileClient(19143): hasFederatedToken: true provider: cognito-idp.***
D/AWSMobileClient(19143): waitForSignIn: userState:SIGNED_IN
I/flutter (19143): DONE

**Comment by haverchuck** [comment]
@dineshkumar02 Does this happen in both Android and iOS?

**Comment by haverchuck** [comment]
https://github.com/aws-amplify/amplify-flutter/issues/93

**Comment by dineshkumar02** [comment]
Hi @haverchuck 

I tested only on Android and did not get chance to test it in IOS.

After sign out, when I try to sign in back, then it is not accepting the deleted user details.
The behavior is, once is user is signed in, then the subsequent sign in with any password is working.

I think, there is a kind of token which is getting created while the user sign in, and until the token expires, this amplify auth library is letting the users sign in with any password. I think, I forgot to mention the token expire time while sign in?? OR, not sure what the existing behavior is.

--Dinesh

**Comment by fjnoyp** [comment]
Hi @dineshkumar02 thanks for brining this issue to our attention.  We are looking into it.

**Comment by markpearl** [comment]
Is there any update on this?  Experiencing the same thing.

**Comment by Jordan-Nelson** [comment]
It looks like this was marked as a bug that requires a fix in Amplify-Android, but no Amplify-Android issue was linked. I'm marking this as pending triage until we track down what fix is required from Amplify-Android.

**Comment by Jordan-Nelson** [comment]
@dineshkumar02 @markpearl - Are you only experiencing this using hosted UI?

I am a little bit confused by the reproduction steps. Are you signing out before calling sign in again? If not, what is the purpose of calling signIn when the user is already signed in?

**Comment by Jordan-Nelson** [comment]
@dineshkumar02 @markpearl - If you are still experiencing this issue, please provide the info above so that we can reproduce this. Thanks.

**Comment by dineshkumar02** [comment]
@Jordan-Nelson ,
I was exploring the amplify with flutter 2 years ago and reported the case which I faced.
Let me close this issue for now, as I understood how the internal auth token works.


What I was doing is like

1. Sigin with cognito user
2. In background, delete the user from aws console
3. Close the application and start it again (Auto sign in happened)

I thought, for the deleted users `auto sign in` do not work, but it seems the `auto sign in`
happens based on the token and it's expire time
