### ISSUE TITLE
Need a value to check if already subscribed using API plugin in case of refresh screen on mobile app

### ISSUE THREAD

**Issue by rakeshshahu** [aws-amplify/amplify-flutter#1181]
**Describe the bug**
Currently, when the app is reloaded (back from inactive/detached... state), we are unable to figure out if the subscription is already established.  Hence  we end up with multiple subscription and receive messages multiple time. Is there a bool value to check if subscription is established and healthy. Also, in case mobile phone loses 4G, we get subscription onError, but then the state of subscription is not known. Difficult to code and handle exception due to missing query on object state.

**Comment by HuiSF** [comment]
Hi @rakeshshahu thanks for opening this issue.

DataStore plugin [emits a hub event `networkStatus` via event hub](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/lib/amplify_datastore_stream_controller.dart#L58-L62). The event contains a boolean value `active`, I believe its value presents the network status for DataStore (unnecessarily indicates if the device is offline, but rather DataStore is unable to sync with the cloud). You can find example of listening to hub event [here](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/lib/main.dart#L174-L181).

 In addition, if you would like to make sure no duplicate subscription before you making a new one, you can call the API [`Amplify.DataStore.stop()`](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/flutter/#start). This API to stop API syncing processes, and clear existing subscriptions. Then you can restart by calling API [`Amplify.DataStore.start()`](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/flutter/#stop), this will create new subscription for you.

**Comment by rakeshshahu** [comment]
Thanks @HuiSF,

Apologies i was not clear in my last message. I am using Amplify.API.subscribe for my subscription to graphql API. Not sure about datastore. However, if you still think datastore will help then after your confirmation, i will read through and implement. 

regards
Rakesh

**Comment by rakeshshahu** [comment]
hi

Just looking to see if any update. We are facing issue in the below scenario

1. After successful subscription, when we disable wifi/internet on phone, onError is invoked but the state of GraphQLSubscriptionOperation variable is unknown, we try to cancel subscription, the app crash in IOs only (crash log below)
2.  When is app is refreshed (lifecycle from inactive to active), we referesh data. At the time, we have no way to know if the subscription is still working, hence we follow cancel-subscribe steps. This work but also result in multiple subscriptions and app receiving multiple notification for same event

**Comment by HuiSF** [comment]
Hi @rakeshshahu thanks for the clarification. Could you attach the iOS logs you mentioned in the last comment?
