### ISSUE TITLE
Invalid JWT Signature using Cognito JWK

### ISSUE THREAD

**Issue by jherjati** [aws-amplify/amplify-flutter#120]
**Describe the bug**
If we do _amplify add auth_ and do sign in using our flutter app as described in [this official AWS tutorial](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter), we can then get our idToken from _CognitoAuthSession.userPoolTokens_ . The problem is, when i try to verify the token using Cognito JWK as described in [this official AWS docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html) it says invalid signature.

Side Note : I compare this behaviour with Amplify Javascript too and i don't find any problem, is there any difference between web app (reactJS) and mobile app (flutter)?

**To Reproduce**
1. Do [this AWS flutter amplify tutorial](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter)
2. Get the idToken in CognitoAuthSession.userPoolTokens.idToken  
3. Do JWT Signature Validation using procedure in [this official AWS cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html)
4. See error message: 'invalid signature'

**Expected behavior**
No error, valid signature.
![image](https://user-images.githubusercontent.com/37134979/93711702-87bb4380-fb7a-11ea-922e-a37794693862.png)

**Screenshots**
Invalid signature.
![image](https://user-images.githubusercontent.com/37134979/93711709-a1f52180-fb7a-11ea-9b1b-623c16c07ad9.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in :
[v] Android
[v] iOS

**Smartphone :**
 - Device: Pixel_2_API_28 Emulator, iOS Simulator
 - OS: Android 9 (Pie), iOS 12
 - Browser Google Chrome
 - Version 85

**Additional context**
I use Flutter Ampliy with Hasura that is deployed in AWS Elastic Beanstalk. I hope i don't need to migrate from cognito to auth0 / firebase.
Region : ap-southeast-1

Thank you

**Comment by martunta** [comment]
can you paste code of your jwk2pem.js ? I just followed your steps and it all worked perfectly. 

btw, thanks for the tip about `CognitoAuthSession` - before this issue I coulnd't find a way how to get the token, as that was missing in the tutorial!

**Comment by jherjati** [comment]
> can you paste code of your jwk2pem.js ? I just followed your steps and it all worked perfectly.
> 
> btw, thanks for the tip about `CognitoAuthSession` - before this issue I coulnd't find a way how to get the token, as that was missing in the tutorial!


`var jwkToPem = require("jwk-to-pem");`
`var jwt = require("jsonwebtoken");`

`var jwk = {
    alg: "RS256",
    e: "AQAB",
    kid: "KynZimFU3MxozCoO2i+W6mdnXIQ+QVzP/pwyAx3khfg=",
    kty: "RSA",
    n:
      "hLGfa089DWIs2PG4z47WFKTiOHTptANOniK4jp0RstGRjuy8muaECu6YsyN8mFSYfWNIXpJRgRONE39-7LvthVrtH3T_Cj3jxbyaccYPLPn16svyDxphmRNmKyYahomadA9NU59M3uxvjJXUIMKKvuSz1J2ALSuNEjBFTqQK_-TS7TOnL86shCMvRuMdSrjClqvAFdZwdN11rrtDkE5vH09a8ewhCVtQT3rc5WTXEATCwIJVWQsW7a1_YCbSJI2lLpQZmpPudwznrw8smmi6hYSoJyObqNaDA26IpwM5vPgB5T2RiE3q58sr9mz6pY6rmjoLbiaa88VO24H3Ze6IMQ",
    use: "sig",
  },
  pem = jwkToPem(jwk);`

`var token = "eyJraWQiOiJLeW5aaW1GVTNNeG96Q29PMmkrVzZtZG5YSVErUVZ6UFwvcHd5QXgza2hmZz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiMzMxZTZmYi0wMGMxLTQ0MTktODc5MS0yY2RmOTMxNjkyYzQiLCJhdWQiOiI2bXJ0N2ttOTEwcGJnMzhwOWp1aXVtdGYxayIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6ImY4ZjRiNDY3LWU5YTMtNDVlYy05ZmY0LWYzZTliMWI3ZTExNCIsInRva2VuX3VzZSI6ImlkIiwiaHR0cHM6XC9cL2hhc3VyYS5pb1wvand0XC9jbGFpbXMiOiJ7XCJ4LWhhc3VyYS11c2VyLWlkXCI6XCJiMzMxZTZmYi0wMGMxLTQ0MTktODc5MS0yY2RmOTMxNjkyYzRcIixcIngtaGFzdXJhLWRlZmF1bHQtcm9sZVwiOlwidXNlclwiLFwieC1oYXN1cmEtYWxsb3dlZC1yb2xlc1wiOltcInVzZXJcIl19IiwiYXV0aF90aW1lIjoxNjAwNjA0NjMwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfQmdPUTdMVVdOIiwiY29nbml0bzp1c2VybmFtZSI6ImpoZXJqYXRpIiwiZXhwIjoxNjAwNjA4MjMwLCJpYXQiOjE2MDA2MDQ2MzAsImVtYWlsIjoiamhlcmphdGlAZ21haWwuY29tIn0.Ivju8tpkoxmdIGB4psM6vFovtbC0bTj2m7BRIPawQnDtmvbkESst-5xLbthgV63hficnIbEjNBTHKcjnSublkKAlB2XWSscDZenF7vyZDCz0wmDPdSLm6guX96enDvDnOjzC7rcdwgPWZIFgNWsUdd5v2VD5Ap1WnoEDQN694R2Qpc0-4OiIJKCAZPVgBjpBkriwq3kH1wMcsDqhfAkhjZ2CxK1xUKvoDdw0iIMastiC4a877MHhwTFWSGIW8YqNx2g1v0uGNKVGINT70uSsLzTjkqdtdcFEzkro65mP-hLhGqXv1jCTxHqZV9KflvjgCqXDVni0AonxLsTwZvH5ag";`

`jwt.verify(token, pem, { algorithms: ["RS256"] }, function (err, decodedToken) {
  console.log(decodedToken);
  console.log(err);
});`

Yes, please @martunta

**Comment by martunta** [comment]
I don't get your pem definition. anyway here is my version, that is working for me:

~~~
var jwt = require('jsonwebtoken');
var jwkToPem = require('jwk-to-pem');
const axios = require('axios');

const verifyToken = async () => {

  var jwks;
  var jwks_address = "https://cognito-idp.eu-central-1.amazonaws.com/REPLACE_HERE_WITH_YOUR_ID/.well-known/jwks.json"
  var res = await axios.get(jwks_address);
  console.log(res.data)

    
  console.log("jwks.json");
  //console.log(data);
  jwks = res.data;

  //console.log(jwks);

  var access_jwk = jwks.keys[1]
  var id_jwk = jwks.keys[0]
  //console.log(jwk);


  access_token = "eyJraWQiOiJHcTIxck9GUm1UM....replace_wih_your_own"
  id_token = "eyJraWQiOiJWMlwvR1ZtX....replace_wih_your_own"

  var access_pem = jwkToPem(access_jwk);
  jwt.verify(access_token, access_pem, { algorithms: ['RS256'] }, 
    function(err, decodedToken) {
      console.log("decoded access token");
      console.log(decodedToken);   
  });

  var id_pem = jwkToPem(id_jwk);
  jwt.verify(id_token, id_pem, { algorithms: ['RS256'] }, 
    function(err, decodedToken) {
      console.log("decoded id token");
      console.log(decodedToken);   
  });

}


verifyToken();
~~~

**Comment by fjnoyp** [comment]
Hi @jherjati have you been able to resolve your problem?

**Comment by jherjati** [comment]
> I don't get your pem definition. anyway here is my version, that is working for me:
> 
> ```
> var jwt = require('jsonwebtoken');
> var jwkToPem = require('jwk-to-pem');
> const axios = require('axios');
> 
> const verifyToken = async () => {
> 
>   var jwks;
>   var jwks_address = "https://cognito-idp.eu-central-1.amazonaws.com/REPLACE_HERE_WITH_YOUR_ID/.well-known/jwks.json"
>   var res = await axios.get(jwks_address);
>   console.log(res.data)
> 
>     
>   console.log("jwks.json");
>   //console.log(data);
>   jwks = res.data;
> 
>   //console.log(jwks);
> 
>   var access_jwk = jwks.keys[1]
>   var id_jwk = jwks.keys[0]
>   //console.log(jwk);
> 
> 
>   access_token = "eyJraWQiOiJHcTIxck9GUm1UM....replace_wih_your_own"
>   id_token = "eyJraWQiOiJWMlwvR1ZtX....replace_wih_your_own"
> 
>   var access_pem = jwkToPem(access_jwk);
>   jwt.verify(access_token, access_pem, { algorithms: ['RS256'] }, 
>     function(err, decodedToken) {
>       console.log("decoded access token");
>       console.log(decodedToken);   
>   });
> 
>   var id_pem = jwkToPem(id_jwk);
>   jwt.verify(id_token, id_pem, { algorithms: ['RS256'] }, 
>     function(err, decodedToken) {
>       console.log("decoded id token");
>       console.log(decodedToken);   
>   });
> 
> }
> 
> 
> verifyToken();
> ```

Yes, i did the same, only hiding the axios part, i directly copied the jwk from my browser. Still facing the same issue.

@martunta Did you generate your token in flutter? Did you do some additional AWS Cognito config? Thank you..
@fjnoyp Not yet, unfortunately

**Comment by martunta** [comment]
@jherjati yes, I copied access and id tokens from the flutter debug log. AWS Cognito I configured both in auto-generated way with amplify cli and also manually, it worked in both ways. Maybe try to start from beginning, create new cognito with amplify cli and try to avoid any extra manual configs. I am not sure what else to suggest. good luck.

**Comment by Tapasm1212** [comment]
I am getting the same Invalid JWT Signature in Cognito token. I am using flutter SDK "amplify_auth_cognito" in pubspecs.yml file but it's not working.

**Comment by KrisWozy** [comment]
Had this issue, was copying the jwt from flutter debug log in vscode and it was chopping off the last 2 characters of the code giving it an invalid signature when testing the copied token. Could be the same for others.

**Comment by ps0296** [comment]
I had same issue, spent hours. It's likely b/c of copy & paste, debug log truncates last few characters.

try checking this way
```
print("TOKEN: ${sess.userPoolTokens.accessToken}");
print("END OF TOKEN: ${sess.userPoolTokens.accessToken.substring(sess.userPoolTokens.accessToken.length - 50)}");
```

make sure all the characters are there before you copy token

**Comment by haverchuck** [comment]
@jherjati @Tapasm1212 Did you try looking into the possibility that characters are being sliced off the end of the token when you copy and paste, as described by @KrisWozy and @ps0296 ?

**Comment by haverchuck** [comment]
Closing this issue as there seems to be a solution and activity on this thread has stopped.
