### ISSUE TITLE
Unsupported value: org.json.JSONException: No value for region)

### ISSUE THREAD

**Issue by horgag** [aws-amplify/amplify-flutter#121]
**Describe the bug**
Amplify.configure() doesn't work. Problem loading `amplifyconfig` string. Seems to be a parsing problem. 

**Expected behavior**
config file should load

here is the file:

```
const amplifyconfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CredentialsProvider": {
                  "CognitoIdentity": {
                      "Default": {
                          "PoolId": "xxxxxxxxxxxxx
                          "Region": "eu-west-1"
                      }
                  }
              },
              "CognitoUserPool": {  
                  "Default": {
                      "PoolId": "xxxxx",
                      "AppClientId": "xxxxxxxxxxxxxxxxx",
                      "Region": "eu-west-1"
                  }
              },
              "Auth": {
                  "Default": {
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
          }
      }
  }
}''';

```

**Platform**
Android

**Additional context**
was working before. Not that I think it matters but I updated amplify cli.

**Comment by fjnoyp** [comment]
HI @horgag sorry to hear you're having this issue.  We'll need more information before to help you resolve this issue. 

Can you provide more information such as the console output when running your application? 

Also could you provide the Amplify CLI version number (in console type "amplify -v").  Lastly, can you provide what Amplify Flutter plugins you have included in your pubspec.yaml?

**Comment by fjnoyp** [comment]
Based on your title, have you tried manually changing your region to something like: 

                    "region": "us-east-1"

**Comment by dineshkumar02** [comment]
I am facing the similar problem.

pubspec.yaml file I've this

  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'
  amplify_storage_s3: '<1.0.0'

Amplify version is
amplify -v
4.26.1-flutter-preview.0

**Comment by dineshkumar02** [comment]
I am able to fix it.

In my case, I mentioned 'amplify_storage' in pubspec.yaml file, **but I am not actually using any storage related stuff**.
Removed it from pubspec.yaml and it worked. I also did **flutter clean** before building the application(which is not required I think).

@horgag , 
See if this is the same situation in your case.

**Comment by prerakkumar** [comment]
@dineshkumar02  thank you so much bro.it worked

**Comment by Amplifiyer** [comment]
@horgag does this problem still exist for you?

**Comment by horgag** [comment]
no @dineshkumar02 solution worked for me
