### ISSUE TITLE
Adding Headers to Outgoing Requests

### ISSUE THREAD

**Issue by krunduev** [aws-amplify/amplify-flutter#1217]
Feature request.
Need to add custom header to GraphQL request like in Android/iOS

https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android/#adding-headers-to-outgoing-requests

**Comment by ragingsquirrel3** [comment]
Hello, please note there is an open [RFC](https://github.com/aws-amplify/amplify-flutter/issues/2035) for changes to the API category in amplify-flutter with this being one of the proposed changes.

**Comment by ragingsquirrel3** [comment]
Hello  - We have recently released a new developer preview version of the API category ([amplify_flutter v1.0.0-next.1](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.1)). This new version is a full re-write of the API category in dart, and it supports Mobile, Desktop, and Web. The new version supports custom headers in a `GraphQLRequest`. You can see more info/examples [in the docs](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#adding-headers-to-outgoing-requests). I will update this issue again once this new version is out of developer preview.

Let me know if you have any questions!

**Comment by Jordan-Nelson** [comment]
Support for this was added in v1.0.0 of Amplify Flutter, which is now stable. You can see the docs on customizing http requests [here](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#adding-headers-to-outgoing-requests).

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
