### ISSUE TITLE
Non-null safe codegen is broken for hasMany relationships

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#1218]
With latest CLI (7.6.3)

```graphql
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } }

type Todo @model {
  id: ID!
  name: String!
  description: String
  ref: [Ref] @hasMany
}

type Ref @model {
  id: ID!
  name: String
}
```

Running `amplify codegen models` produces the attached models, incorrectly using null-safe syntax for the `toJson` method.

<img width="435" alt="Screen Shot 2021-12-16 at 8 40 51 AM" src="https://user-images.githubusercontent.com/24740863/146402127-ef786b8a-8c3a-42dc-a838-09aab8c2c050.png">

[models.zip](https://github.com/aws-amplify/amplify-flutter/files/7728629/models.zip)

**Comment by HuiSF** [comment]
It looks like the fix for https://github.com/aws-amplify/amplify-codegen/pull/227 didn't create branches for non-nullsafety vs nullsafety, will create a PR to amplify-codegen to fix.

**Comment by HuiSF** [comment]
The fix has been released from ampliy-codegen. Install `@aws-amplify/cli@7.6.10` to ensure get the fix.
