### ISSUE TITLE
Exceeded daily email limit, Number of allowed operation has exceeded.

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1221]
Hi,

Need a solution for the following errors;

For the following I read a stackoverflow(https://stackoverflow.com/questions/49086610/how-to-edit-the-limit-of-attempts-to-change-a-password-in-aws-cognito) answers, but what if the same scenario happened for real people. I know that no one will do 5times attempt at a same shot only testers will do. But how can I solve this issue for testers?

<img width="250" alt="Screenshot 2021-12-17 at 7 54 18 PM" src="https://user-images.githubusercontent.com/27992382/146559050-27bfee8c-6783-4f99-8f50-6ce9077445b2.png">

<img width="226" alt="Screenshot 2021-12-17 at 7 54 36 PM" src="https://user-images.githubusercontent.com/27992382/146559159-f92e59e9-8fb3-427e-a85b-a06be3adc8df.png">

Using the following packages version;

` amplify_flutter: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10
  amplify_storage_s3: ^0.2.10`

**Comment by HuiSF** [comment]
Hi @Sunsiha thanks for reaching out.

Want to clarify, do you see the screenshot shown error in the Cognito console? 
Does the Auth API calls in your App receive any specific error?

**Comment by haverchuck** [comment]
@Sunsiha  - Which API method are you calling which returns this exception?

**Comment by Sunsiha** [comment]
@HuiSF @haverchuck  when i call the particular API's;

When I do for Signup and Reset Password;
` ResetPasswordResult res = await Amplify.Auth.resetPassword(
        username: usernameController.text.trim(),
      );`


`LimitExceededException(message: Number of allowed operation has exceeded., recoverySuggestion: Please wait a while before re-attempting or increase the service limit., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException: Exceeded daily email limit for the operation or the account. If a higher limit is required, please configure your user pool to use your own Amazon SES configuration for sending email. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: LimitExceededException; Request ID: 2908744c-be50-4379-89e7-213eac8fcde0))`

**Comment by haverchuck** [comment]
@Sunsiha Are you calling this API repeatedly with the wrong parameter? Or have you called it repeatedly with the correct parameter and are truly hitting email limitations? If the latter, have you tried setting up an SES config as the exception suggests?

**Comment by Sunsiha** [comment]
We are working on setting up on SES configuration .

**Comment by haverchuck** [comment]
@Sunsiha Ok - please keep us posted on this issue!

**Comment by haverchuck** [comment]
@Sunsiha Did you resolve your SES issue?

**Comment by offlineprogrammer** [comment]
Hey @Sunsiha 

I am closing this issue for now as we didn't hear from you.
We can reopen it if you are still facing the issue and when you provide details.

Regards
Mo

**Comment by Sunsiha** [comment]
> Hey @Sunsiha
> 
> I am closing this issue for now as we didn't hear from you. We can reopen it if you are still facing the issue and when you provide details.
> 
> Regards Mo

Haven't done SES part still. If I face the issue again will let you know.

**Comment by hamzasintov** [comment]
Also I am facing the same issue. just I can login to my app. but on the forget password and the other api requests are giving that error. 

Error: Number of allowed operations has exceeded. Please wait a while before re-attempting

**Comment by hamzasintov** [comment]
@offlineprogrammer

**Comment by Vioguy** [comment]
I have the sasme issue trying to sign in to a different website: gptsubtitler
