### ISSUE TITLE
Not able to signin, the rest all of the functionalities are working. Unhandled Exception: AnalyticsException(message: Unable to read appId or region from the amplify configuration json., recoverySuggestion: Make sure amplifyconfiguration.json is a valid json object in expected format. Please take a look at the documentation for expected format of amplifyconfiguration.json., underlyingException: org.json.JSONException: No value for pinpointAnalytics)

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1222]
I/amplify:flutter:auth_cognito(20156): Added Auth plugin
I/AmplifyFlutter(20156): Added StorageS3 plugin
I/amplify:flutter:analytics_pinpoint(20156): Added AnalyticsPinpoint plugin
D/AWSMobileClient(20156): Using the SignInProviderConfig from `awsconfiguration.json`.
W/AWSMobileClient(20156): Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json
W/AWSMobileClient(20156): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient(20156): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/AWSMobileClient(20156): 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/AWSMobileClient(20156): 	at org.json.JSONObject.<init>(JSONObject.java:168)
W/AWSMobileClient(20156): 	at org.json.JSONObject.<init>(JSONObject.java:185)
W/AWSMobileClient(20156): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:713)
W/AWSMobileClient(20156): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:614)
W/AWSMobileClient(20156): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(20156): 	at java.lang.Thread.run(Thread.java:920)
D/AWSMobileClient(20156): initialize: Cognito HostedUI client detected
D/AWSMobileClient(20156): Inspecting user state details
D/EGL_emulation(20156): app_time_stats: avg=13857.06ms min=46.62ms max=55022.48ms count=4
E/flutter (20156): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: AnalyticsException(message: Unable to read appId or region from the amplify configuration json., recoverySuggestion: Make sure amplifyconfiguration.json is a valid json object in expected format. Please take a look at the documentation for expected format of amplifyconfiguration.json., underlyingException: org.json.JSONException: No value for pinpointAnalytics)
E/flutter (20156): #0      AmplifyClass.configure (package:amplify_flutter/amplify.dart:170:9)
E/flutter (20156): <asynchronous suspension>
E/flutter (20156): #1      _SignInState._initAmplifyFlutter (package:aaa/cognito/signin_screen.dart:63:7)
E/flutter (20156): <asynchronous suspension>
E/flutter (20156): 

Pubspec
---------
```
  amplify_flutter: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10
  amplify_storage_s3: ^0.2.10
```

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxxx-xxx-xxx-xxx-xxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxx",
                        "AppClientId": "xxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxx.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "xxxxxx",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

```

**Comment by Jordan-Nelson** [comment]
Hello @Sunsiha - It looks like you are trying to use Auth, Analytics, and Storage. However, the amplify config file you shared only seems to have Auth plugin info. Have you added Analytics and Storage to the Amplify project (`amplify add analytics` and `amplify add storage`)?

**Comment by Sunsiha** [comment]
@Jordan-Nelson i tried to remove that and checked..That time am getting different error.

`I/amplify:flutter:auth_cognito(21655): Added Auth plugin
D/AWSMobileClient(21655): Using the SignInProviderConfig from `awsconfiguration.json`.
W/AWSMobileClient(21655): Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json
W/AWSMobileClient(21655): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient(21655): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/AWSMobileClient(21655): 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/AWSMobileClient(21655): 	at org.json.JSONObject.<init>(JSONObject.java:168)
W/AWSMobileClient(21655): 	at org.json.JSONObject.<init>(JSONObject.java:185)
W/AWSMobileClient(21655): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:713)
W/AWSMobileClient(21655): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:614)
W/AWSMobileClient(21655): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(21655): 	at java.lang.Thread.run(Thread.java:920)
D/AWSMobileClient(21655): initialize: Cognito HostedUI client detected
D/AWSMobileClient(21655): Inspecting user state details
`

**Comment by Jordan-Nelson** [comment]
@Sunsiha - Can you share the Dart code from your app where `Amplify.addPlugin()`/`Amplify.addPlugins()` and `Amplify.configure()` is called? It should look something like the example below.

```dart
  Future<void> _configureAmplify() async {
    try {
      await Amplify.addPlugin(AmplifyAuthCognito());
      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      print('An error occurred configuring Amplify: $e');
    }
  }
```

**Comment by Sunsiha** [comment]
@Jordan-Nelson after flutter clean it got sorted. Something weird happened .

**Comment by offlineprogrammer** [comment]
Hey @Sunsiha 

I am closing this issue based on your comment above 
We can reopen it if you are still facing the issue and when you provide details,

Regards
Mo

**Comment by SettiNitesh** [comment]
@offlineprogrammer  for me it is not working after flutter clean .
