### ISSUE TITLE
How change DataStore’s authModeStrategyType  ?

### ISSUE THREAD

**Issue by nazarcybulskij** [aws-amplify/amplify-flutter#1225]
I  am developing a project with mixing authorization modes in DataStore. Model  UserInfo must be available  only  users  from  Cognito user pool.

but  I  get error "Not Authorized to access listUserInfo on type Query" 🤷‍♂️    when a call  Amplify.API.query

Please, help me 🆘
I will be glad for your help))

**Comment by HuiSF** [comment]
Hey @nazarcybulskij thanks for opening this thread.
Could you provide schema example of how were you setting up the auth rules for this use case?

**Comment by nazarcybulskij** [comment]
> Hey @nazarcybulskij thanks for opening this thread. Could you provide schema example of how were you setting up the auth rules for this use case?

```
type Post @model @auth(rules: [{allow: public}]) {
  id: ID! @primaryKey
  title: String
  description: String
}

type UserInfo @model @auth(rules: [{allow: private}]) {
  id: ID!
  likes: [String]
}
```

**Comment by HuiSF** [comment]
Thanks @nazarcybulskij .

This rule `@auth(rules: [{allow: private}])` on the `UserInfo` specifies that this model can be accessed for a user who is with valid JWT token from Cognito user pool, meaning you will need to have a valid user session to make the API request.

Did you sign in a user for making the API request?

Here's also a good document to learn about model auth rules https://docs.amplify.aws/cli/graphql/authorization-rules/

**Comment by nazarcybulskij** [comment]
> Thanks @nazarcybulskij .
> 
> This rule `@auth(rules: [{allow: private}])` on the `UserInfo` specifies that this model can be accessed for a user who is with valid JWT token from Cognito user pool, meaning you will need to have a valid user session to make the API request.
> 
> Did you sign in a user for making the API request?
> 
> Here's also a good document to learn about model auth rules https://docs.amplify.aws/cli/graphql/authorization-rules/

Yes , I sign in a user for making the API request, but a get error `Not Authorized to access listUserInfo on type Query`

**Comment by HuiSF** [comment]
Could you try with a different user see if the issue persists? @nazarcybulskij 
There was a similar issue https://github.com/aws-amplify/amplify-flutter/issues/1179
Was caused by the API category configuration was not fully deployed. Maybe you can also try to delete the API category and reconfigure.

**Comment by offlineprogrammer** [comment]
Hey @nazarcybulskij 

Did you tried the approach provide by @HuiSF above?

Regards
Mo
