### ISSUE TITLE
Datastore exception , Tried to get a plugin before it was configured

### ISSUE THREAD

**Issue by dfourcfive** [aws-amplify/amplify-flutter#1231]
here I'm adding my plugins

```dart
 if (!Amplify.isConfigured) {
        try {
          await Amplify.addPlugins(
              [AmplifyAuthCognito(), AmplifyDataStore(modelProvider: modelProvider), AmplifyAPI(), AmplifyStorageS3(), AmplifyAnalyticsPinpoint()]);
          await Amplify.configure(amplifyConfig);
        } catch (e) {
          dbg(e.toString(), isError: true);
        }
      }
```

the datastore doesn't get ready yet when the app is installed (debug mode) , means i'm not getting any ready state when listening to the hub events 
also the exception occurs when i try to query the user model  
note : this method is only called after a successful login
```dart
          results = await Amplify.DataStore.query(this.getClassTypeByModelName(modelName!) as ModelType<T>, where: queryParams);
```
user model rules 
```graphql
type User @model @auth(rules: [{ allow: owner }, { allow: private, provider: iam }]) {
    id: ID!
    families: [FamilyMember] @connection(keyName: "byMember", fields: ["id"])
    email: String!
    status: GenericStatus!
    data: String
}
```

the datastore state only gets ready when the user is already logged in ,only after i close the app and open it again 
```dart
 hubSubscription = Amplify.Hub.listen([HubChannel.DataStore, HubChannel.Auth], (hubEvent) async {

        switch (hubEvent.eventName) {
          case 'syncQueriesReady':
            break;
          case 'modelSynced':
            break;
          case 'ready':
            // Datastore is initialized
            print('is ready');
            break;
          case 'subscriptionsEstablished':
            break;
          case 'syncQueriesStarted':
            break;
          case 'networkStatus':
          
            break;
          case 'SIGNED_OUT':
            break;
          case 'SIGNED_IN':
           
            break;
          case 'SESSION_EXPIRED':
            break;
        }
      });
    } catch (e) {
      dbg(e, cat: "EXCEPTION");
      this.goNextStep(state: this.problemState);
    }
```
debug console:
```
E/MethodChannel#com.amazonaws.amplify/datastore(24521): Failed to handle method call
E/MethodChannel#com.amazonaws.amplify/datastore(24521): java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
```

```
DataStoreException(message: An unknown exception has happened.           Please take a look at
package:flutter_amplifysdk/exception.dart:17
               https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that 
               match your scenario, and file an issue with the details of the bug if there isn't.
         , recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: PlatformException(error, Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first., null, java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
       	at com.amplifyframework.core.category.Category.getPluginIfConfiguredOrThrow(Category.java:239)
       	at com.amplifyframework.core.category.Category.getPlugin(Category.java:186)
       	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onQuery(AmplifyDataStorePlugin.kt:249)
       	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onMethodCall(AmplifyDataStorePlugin.kt:121)
```

**Comment by parad0x96** [comment]
> here I'm adding my plugins
> 
> ```dart
>  if (!Amplify.isConfigured) {
>         try {
>           await Amplify.addPlugins(
>               [AmplifyAuthCognito(), AmplifyDataStore(modelProvider: modelProvider), AmplifyAPI(), AmplifyStorageS3(), AmplifyAnalyticsPinpoint()]);
>           await Amplify.configure(amplifyConfig);
>         } catch (e) {
>           dbg(e.toString(), isError: true);
>         }
>       }
> ```
> 
> the datastore doesn't get ready yet when the app is installed (debug mode) , means i'm not getting any ready state when listening to the hub events also the exception occurs when i try to query the user model note : this method is only called after a successful login
> 
> ```dart
>           results = await Amplify.DataStore.query(this.getClassTypeByModelName(modelName!) as ModelType<T>, where: queryParams);
> ```
> 
> user model rules
> 
> ```graphql
> type User @model @auth(rules: [{ allow: owner }, { allow: private, provider: iam }]) {
>     id: ID!
>     families: [FamilyMember] @connection(keyName: "byMember", fields: ["id"])
>     email: String!
>     status: GenericStatus!
>     data: String
> }
> ```
> 
> the datastore state only gets ready when the user is already logged in ,only after i close the app and open it again
> 
> ```dart
>  hubSubscription = Amplify.Hub.listen([HubChannel.DataStore, HubChannel.Auth], (hubEvent) async {
> 
>         switch (hubEvent.eventName) {
>           case 'syncQueriesReady':
>             break;
>           case 'modelSynced':
>             break;
>           case 'ready':
>             // Datastore is initialized
>             print('is ready');
>             break;
>           case 'subscriptionsEstablished':
>             break;
>           case 'syncQueriesStarted':
>             break;
>           case 'networkStatus':
>           
>             break;
>           case 'SIGNED_OUT':
>             break;
>           case 'SIGNED_IN':
>            
>             break;
>           case 'SESSION_EXPIRED':
>             break;
>         }
>       });
>     } catch (e) {
>       dbg(e, cat: "EXCEPTION");
>       this.goNextStep(state: this.problemState);
>     }
> ```
> 
> debug console:
> 
> ```
> E/MethodChannel#com.amazonaws.amplify/datastore(24521): Failed to handle method call
> E/MethodChannel#com.amazonaws.amplify/datastore(24521): java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
> ```
> 
> ```
> DataStoreException(message: An unknown exception has happened.           Please take a look at
> package:flutter_amplifysdk/exception.dart:17
>                https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that 
>                match your scenario, and file an issue with the details of the bug if there isn't.
>          , recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: PlatformException(error, Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first., null, java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
>        	at com.amplifyframework.core.category.Category.getPluginIfConfiguredOrThrow(Category.java:239)
>        	at com.amplifyframework.core.category.Category.getPlugin(Category.java:186)
>        	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onQuery(AmplifyDataStorePlugin.kt:249)
>        	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onMethodCall(AmplifyDataStorePlugin.kt:121)
> ```

Same problem here only works after second try
