### ISSUE TITLE
How to do a signup with custom attributes?

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1243]
How to do a signup with custom attributes? The following is my code. When am trying to call this API am getting error as the following;

> NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: A client attempted to write unauthorized attribute (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: xxxxx-xxx-xxx-xx-xxx), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
```
 Map<String, String> userAttributes = {
      "name": fullNameController.text,
      'custom:isCompany': 'Y',
      'custom:companyName': companyNameController.text
    };
 SignUpResult res = await Amplify.Auth.signUp(
          username: emailController.text.trim(),
          password: passwordController.text.trim(),
          options: CognitoSignUpOptions(userAttributes: userAttributes));
```

**Comment by haverchuck** [comment]
@Sunsiha Have you added the attributes on the Cognito User Pool console?

**Comment by Sunsiha** [comment]
@haverchuck yes I have added.

**Comment by haverchuck** [comment]
@Sunsiha Which version of amplify_auth_cognito are you using?

**Comment by haverchuck** [comment]
@Sunsiha Also, you need to check the attribute permissions in the user pool. All attributes are readable/writable by default UNLESS you set a permission on a single attribute. If you do this, you will need to set the permissions for all attributes. If you have already changed permissions for any attributes, you may need to set permissions for the custom ones as well.

These settings can be found in the Cognito console under the user pool's app client(s).

**Comment by Sunsiha** [comment]
> @Sunsiha Which version of amplify_auth_cognito are you using?

amplify_auth_cognito: ^0.2.10

**Comment by Sunsiha** [comment]
> @Sunsiha Also, you need to check the attribute permissions in the user pool. All attributes are readable/writable by default UNLESS you set a permission on a single attribute. If you do this, you will need to set the permissions for all attributes. If you have already changed permissions for any attributes, you may need to set permissions for the custom ones as well.
> 
> These settings can be found in the Cognito console under the user pool's app client(s).

But this one is already working for web javascript code. So there is no permission issues right. I hope the code which I shared it should be like that only.

**Comment by haverchuck** [comment]
@Sunsiha The Javascript and Flutter apps are using the same app client?

**Comment by Sunsiha** [comment]
> @Sunsiha The Javascript and Flutter apps are using the same app client?

No. We are using different App clients.

**Comment by haverchuck** [comment]
@Sunsiha When you look at the app client used by flutter, and look at the read/write permissions for the attributes, do you see this exact message? `All attributes are readable and writable by default because none are selected. Select attributes to make only those readable or writable.`

Are any attributes selected?

**Comment by Sunsiha** [comment]
> @Sunsiha When you look at the app client used by flutter, and look at the read/write permissions for the attributes, do you see this exact message? `All attributes are readable and writable by default because none are selected. Select attributes to make only those readable or writable.`
> 
> Are any attributes selected?

But we are using same cognito pool only app clients difference is there. But the attributes and all same for both web and flutter. 
<img width="1105" alt="Screenshot 2022-01-05 at 5 33 41 AM" src="https://user-images.githubusercontent.com/27992382/148140353-b7d76266-47ad-4ffe-b38d-f2f95469c233.png">

**Comment by Sunsiha** [comment]
> @Sunsiha When you look at the app client used by flutter, and look at the read/write permissions for the attributes, do you see this exact message? `All attributes are readable and writable by default because none are selected. Select attributes to make only those readable or writable.`
> 
> Are any attributes selected?

Am not getting this kind of exception. I have already mentioned what exception I was getting.

**Comment by haverchuck** [comment]
@Sunsiha The screen shot you shared is from the 'Attributes' screen in the cognito console. Can you select the 'App Clients' screen, and then (under the App Client used by your Flutter App) select "Set Attribute Read and Write Permissions":

![image](https://user-images.githubusercontent.com/10621276/148141127-a1feb51e-5b15-4410-b2a1-30d1dde71344.png)

You should see a message saying that all attribute are "readable" by default, OR the custom attributes should be marked as readable.

**Comment by Sunsiha** [comment]
@haverchuck its working now. Thanks.

**Comment by Sunsiha** [comment]
> @Sunsiha The screen shot you shared is from the 'Attributes' screen in the cognito console. Can you select the 'App Clients' screen, and then (under the App Client used by your Flutter App) select "Set Attribute Read and Write Permissions":
> 
> ![image](https://user-images.githubusercontent.com/10621276/148141127-a1feb51e-5b15-4410-b2a1-30d1dde71344.png)
> 
> You should see a message saying that all attribute are "writable" by default, OR the custom attributes should be marked as writable.
> 
> *Update *: When I first posted this response I said 'readable' instead of 'writable'. Apologies.

@haverchuck its working now. Thanks.
