### ISSUE TITLE
Signin with apple name is getting as email id.

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1244]
Hi I have created a cognito user pool with name. And when I try to sign in with apple name is getting as email id. the following way, that too it's not getting apple email id. It's getting the following way;

<img width="416" alt="Screenshot 2022-01-04 at 11 24 32 PM" src="https://user-images.githubusercontent.com/27992382/148102875-e4c096b1-7204-4bff-9984-c7869fa1be4a.png">

The following way attribute mapping is done;
<img width="927" alt="Screenshot 2022-01-04 at 11 28 20 PM" src="https://user-images.githubusercontent.com/27992382/148102951-d32d2663-7a31-48a3-921a-e8d2ef1ab680.png">

If I change the it like apple attribute name and user poll attribute name into name am not able to login only. It's throwing error. What is the solution for to to get the name not as email id.

**Comment by cshfang** [comment]
Hi @Sunsiha can you make sure that the mapped user pool attributes are set to mutable? Could you also share the exact error message that is being thrown? It would also be helpful if you could tell us about the versions of Flutter as well as the Amplify plugins you are using.

**Comment by Sunsiha** [comment]
> Hi @Sunsiha can you make sure that the mapped user pool attributes are set to mutable? Could you also share the exact error message that is being thrown? It would also be helpful if you could tell us about the versions of Flutter as well as the Amplify plugins you are using.

By default attribute am using, once we created means we won't be able to edit, Can you please tell me how can i check that. This is how my attributes are now.

<img width="1105" alt="Screenshot 2022-01-05 at 5 33 41 AM" src="https://user-images.githubusercontent.com/27992382/148140585-ab490b05-59de-4e53-b352-99b190e14c1a.png">

When I changed the attribute like the below, 
<img width="956" alt="Screenshot 2022-01-05 at 5 19 08 AM" src="https://user-images.githubusercontent.com/27992382/148140942-33e036e4-e1d7-4b1b-8371-87bea2ff88f1.png">

 throwing error like `social loginAuthException(message: Sign-in with web UI failed, recoverySuggestion: See attached exception for more details, underlyingException: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request)`

Using the version of `amplify_auth_cognito: ^0.2.10`

**Comment by cshfang** [comment]
Hm, thank you for the additional info. After remapping, are you also signing up the user again? Would be feasible for you to try to recreate the user pool with the correct mappings to begin with?

**Comment by Sunsiha** [comment]
> Hm, thank you for the additional info. After remapping, are you also signing up the user again? Would be feasible for you to try to recreate the user pool with the correct mappings to begin with?

Answers;

After remapping, are you also signing up the user again?

**Scenario 1:**

Step 1: Map name attribute with  email.
Step 2: Try to sign in(You will be able to see near to name it will b saved as email id)
Step 3: Change the mapping like name with name.
Step 4: Try to sign in(You will be able to see name).

**Scenario 2:**

Step 1: Map name attribute with  email.
Step 2: Try to sign in(You will be able to see near to name it will b saved as email id)
Step 3: Change the mapping like name with name.
Step 4: Delete the user from cognito.
Step 5: Try to do sign in again.
Step 6: It will throw an error as I mentioned.

Would be feasible for you to try to recreate the user pool with the correct mappings to begin with?

You mean I need to create a fresh cognito user pool from beginning? But I have already created two user pool both is behaving same way.

**Comment by Sunsiha** [comment]
> > Hi @Sunsiha can you make sure that the mapped user pool attributes are set to mutable? Could you also share the exact error message that is being thrown? It would also be helpful if you could tell us about the versions of Flutter as well as the Amplify plugins you are using.
> 
> By default attribute am using, once we created means we won't be able to edit, Can you please tell me how can i check that. This is how my attributes are now.
> 
> <img alt="Screenshot 2022-01-05 at 5 33 41 AM" width="1105" src="https://user-images.githubusercontent.com/27992382/148140585-ab490b05-59de-4e53-b352-99b190e14c1a.png">
> 
> When I changed the attribute like the below, <img alt="Screenshot 2022-01-05 at 5 19 08 AM" width="956" src="https://user-images.githubusercontent.com/27992382/148140942-33e036e4-e1d7-4b1b-8371-87bea2ff88f1.png">
> 
> throwing error like `social loginAuthException(message: Sign-in with web UI failed, recoverySuggestion: See attached exception for more details, underlyingException: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request)`
> 
> Using the version of `amplify_auth_cognito: ^0.2.10` Flutter version details: `Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700 Engine • revision d3ea636dc5 Tools • Dart 2.14.4 `

@cshfang I doubt it's an issue with fluttter. Because same behaviour is happening or web also. So may be something with cognito user pool only.

**Comment by cshfang** [comment]
@Sunsiha I agree that this does not appear to be a Flutter issue. It seems like a configuration issue with the user pool - perhaps during the remapping step. I am not yet able to reproduce this on my end but will try to set up a project and remap the federated login attributes. Did you set up your auth using Amplify CLI? It could be helpful to know the options you selected via the CLI as well in helping me repro on my end.

**Comment by Sunsiha** [comment]
> @Sunsiha I agree that this does not appear to be a Flutter issue. It seems like a configuration issue with the user pool - perhaps during the remapping step. I am not yet able to reproduce this on my end but will try to set up a project and remap the federated login attributes. Did you set up your auth using Amplify CLI? It could be helpful to know the options you selected via the CLI as well in helping me repro on my end.

No, I didn't created the user pool using Amplify CLI. Directly from AWS console I have created. 

<img width="235" alt="Screenshot 2022-01-07 at 12 29 23 AM" src="https://user-images.githubusercontent.com/27992382/148436633-fd95a37e-9c7b-40d2-a5ae-0e7c1fee0ab8.png">

**Comment by Sunsiha** [comment]
@Jordan-Nelson Any update on this?

**Comment by Sunsiha** [comment]
@Jordan-Nelson Any progress on this ticket?

**Comment by Jordan-Nelson** [comment]
@Sunsiha - I don't have an update at the moment. This is in our backlog of issues to try to reproduce.

**Comment by Jordan-Nelson** [comment]
@Sunsiha - Apologies for the long delay in an update. I attempted to reproduce this today. I do not see "name" listed as of the presets in Cognito (see screenshot below). Was this added as a custom attribute mapping?

![Screenshot 2024-01-24 at 12 52 55 PM](https://github.com/aws-amplify/amplify-flutter/assets/20613561/f13db1ea-a470-4e06-9c0a-24d88e08916f)

If you are still facing this issue I think it may be best to create an AWS support case for this from [Support Center](https://support.console.aws.amazon.com/support/home) as this should get directed to Cognito and they can likely assist you better.

**Comment by Jordan-Nelson** [comment]
@Sunsiha - I am going to close this out. As mentioned above, if you are still facing this issue I think a good next step would be to open an case in the support center.
