### ISSUE TITLE
SMS verification whatsapp code cognito

### ISSUE THREAD

**Issue by miguelflores1993** [aws-amplify/amplify-flutter#1253]
Good morning everyone.

We currently have the verification of telephone numbers through cognito.
but we have some inconveniences ones in my country BOLIVIA, that some operators do not receive the SMS.
so we are wanting to see an option to send the SMS by whatsapp.

This is possible?
I attach a photo
![WhatsApp Image 2022-01-08 at 9 22 49 PM](https://user-images.githubusercontent.com/67565934/148766679-80eeb24c-ec8e-41f0-b919-700215b5b8c8.jpeg)
.

**Comment by Jordan-Nelson** [comment]
Hello @flutteresbolivia - As long as you can programmatically send the message via WhatsApp (through a service such as Twilio, for example) you should be able to do this with a custom auth challenge. A custom auth challenge can be set up to trigger a lambda function each time a verification code is sent. That lambda can send the code to the user via the service you choose.

- Here are [the CLI docs on custom lambda triggers](https://docs.amplify.aws/cli/usage/lambda-triggers/)
- This [blog post on integrating AWS Pinpoint and WhatsApp](https://aws.amazon.com/blogs/messaging-and-targeting/adding-whatsapp-as-an-amazon-pinpoint-channel/) has an example lambda function that invokes the Twilio API to send a message via WhatsApp. Most of the steps in this blog post probably won't be that relevant for your scenario, but the lambda might be of interest. See "Step 3: Create an AWS Lambda."
