### ISSUE TITLE
Amplify CLI installation instructions

### ISSUE THREAD

**Issue by JamesMcIntosh** [aws-amplify/amplify-flutter#126]
The setup instructions should say that you need the flutter preview version of the CLI else you can't setup the app as when you run `amplify init` there is no Flutter option for `Choose the type of app that you're building`

`npm install -g @aws-amplify/cli@flutter-preview`

**Comment by haverchuck** [comment]
@JamesMcIntosh - Thanks for submitting this issue.  Our [getting started tutorial ](https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter#prerequisites) and our[ project setup docs](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/flutter#option-2-follow-the-instructions) both reference the command you've included to install the flutter preview.  Can you point us to the documentation section you're using that doesn't cite the flutter-preview?

**Comment by JamesMcIntosh** [comment]
@haverchuck In the README.md Flutter Development Guide section - step 3
https://github.com/aws-amplify/amplify-flutter/blob/master/README.md#flutter-development-guide

It has `See Amplify CLI Installation` which links to https://github.com/aws-amplify/amplify-cli#install-the-cli

It should probably be linking to the same link earlier in the document for `Install the Amplify CLI`.
https://docs.amplify.aws/lib/project-setup/prereq/q/platform/flutter#install-and-configure-the-amplify-cli
