### ISSUE TITLE
signInWithWebUI doesn't opens the browser for Social Login on some Android Phones

### ISSUE THREAD

**Issue by rahul-insight** [aws-amplify/amplify-flutter#1265]
**Describe the bug**
On certain Android phones on calling social sign-in with `signInWithWebUI `  the default browser (Chrome) doesn't open, so the user is not able to enter the login credentials.

The issue is seen on the following devices. They are reported by our users. Since we don't have those devices, we don't have the exact logs for them.

1. OPPO F19 PRO | Android version: 11  | Default browser: Chrome | Chrome version: 97.0.4692.70
2. Redmi Note 6 Pro | Android version: 9 | Default browser: Chrome | Chrome version: 96.0.4664.104
3. Samsung Galaxy S20 | Android version: 11

We have made the necessary setup in AndroidManifest.xml as mentioned here
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#android-platform-setup

**To Reproduce**
1. Call signInWithWebUI with Google or Facebook on any of the phones mentioned above
2. Check whether the browser with custom tab opens up for entering social credentials

**Expected behavior**
A browser should open up for the next steps in the Social SignIn workflow

**Screenshots**
System configuration for the devices where the issue us observed:

![WhatsApp Image 2022-01-07 at 6 14 46 PM (1)](https://user-images.githubusercontent.com/87314176/149362080-2ebed294-9bc2-48a8-af0b-55da9098d591.jpeg)

![WhatsApp Image 2022-01-03 at 12 38 20 PM (1)](https://user-images.githubusercontent.com/87314176/149362094-5e426081-8bcb-411d-96a9-3f87c3de8247.jpeg)

![software info](https://user-images.githubusercontent.com/87314176/149378386-02b7a4ef-b87e-4091-8d96-fad01926a4b3.jpg)

**Platform**

Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

**Smartphone (please complete the following information):**
1. OPPO F19 PRO | Android version: 11  | Default browser: Chrome | Chrome version: 97.0.4692.70
2. Redmi Note 6 Pro | Android version: 9 | Default browser: Chrome | Chrome version: 96.0.4664.104
3. Samsung Galaxy S20 | Android version: 11

**Comment by quirkeer** [comment]
got same issue on Samsung Galaxy S21, same OS version Android 11.

btw it works fine on my another device which is a Samsung Galaxy Z Fold3 basing on Android 12.

**Comment by quirkeer** [comment]
For my Galaxy S21, error fixed after I change my default browser from `Quark` to `Chrome` or `Samsung Browser`

**Comment by Sunsiha** [comment]
any update on this?

**Comment by Jordan-Nelson** [comment]
Hello - Sorry for the delay on an update. This looks like it could be related to https://github.com/aws-amplify/amplify-android/issues/1587, an underlying issue that was addressed in Amplify-Android. That fix would have been available starting in 0.3.2 of Amplify-Flutter. If you are still experiencing this issue with 0.3.2 or later, please let me know.

I also just want to note that the original issue notes that Chrome is installed on these devices. There is a separate issue for devices that do not have Chrome installed that can be found here: https://github.com/aws-amplify/amplify-flutter/issues/587

**Comment by Jordan-Nelson** [comment]
@rahul-insight @quirkeer @Sunsiha - Please let us know if you are still experiencing this with amplify-flutter 0.3.2+. Thanks.

**Comment by Jordan-Nelson** [comment]
I am going to close this since we have not heard back for some time. If any of you are still experiencing this with version 0.3.2+, please feel free to open a new issue. Thanks.

**Comment by ilyasarafathemvigo** [comment]
@Jordan-Nelson getting the same issue in sSamsung SM-A528B . using the version "amplify_auth_cognito: ^1.7.0" 
captured the error in sentry.Attaching screenshot below.
<img width="932" alt="Screenshot 2024-04-12 at 11 07 02 AM" src="https://github.com/aws-amplify/amplify-flutter/assets/121234451/1fefe6db-09a7-4990-97b9-f7a27f765584">
