### ISSUE TITLE
Subscribe to a GraphQL Subscription via a Stream

### ISSUE THREAD

**Issue by jamesblasco** [aws-amplify/amplify-flutter#1269]
**Describe the bug**
Right now it is very difficult to mock an APICategory.subscribe method. The events are passed on callbacks as parameters making it difficult to use with mocktail and mockito libraries.

I would like to give the option to subscribe with a native dart stream instead. I think that not only could provide a lot of use while testing, but also connect the reactive subscription to the rest of the layers of the app that make use of Streams for that purpose.

```dart
/// Subscribes to an Amplify query via a stream
  Stream<String> subscribeAsStream(GraphQLRequest<String> request) {
    late final streamController = StreamController<String>();
    late GraphQLSubscriptionOperation<String>? subscription;

    streamController.onCancel = () {
      // ignore: avoid_dynamic_calls
      subscription?.cancel();
    };

    try {
      subscription = _apiCategory.subscribe(
        request: request,
        onData: (event) {
          if (event.errors.isNotEmpty) {
            streamController.addError(
              GraphQLOperationException(event.errors),
            );
          }
          streamController.add(event.data);
        },
        onError: (dynamic e) {
          streamController.addError(e as Object);
        },
        onEstablished: () {},
        onDone: () {
          if (!streamController.isClosed) {
            streamController.close();
          }
        },
      );
    } catch (e, s) {
      streamController.addError(e, s);
    }
    return streamController.stream;
  }
```

Example on how it would lool like the testing with mocktail:

<img width="474" alt="Screenshot 2022-01-14 at 08 50 43" src="https://user-images.githubusercontent.com/19904063/149470895-b37afef7-9bcb-435f-aafa-87389eb4cc9b.png">

How is now:

<img width="530" alt="Screenshot 2022-01-14 at 08 53 54" src="https://user-images.githubusercontent.com/19904063/149471316-f8c3745e-3cac-4a14-b076-7289740fc074.png">

<img width="571" alt="Screenshot 2022-01-14 at 08 54 00" src="https://user-images.githubusercontent.com/19904063/149471329-aedfeb9a-3593-46db-a765-5ff6be295c59.png">

<img width="559" alt="Screenshot 2022-01-14 at 08 55 00" src="https://user-images.githubusercontent.com/19904063/149471434-8cc1ac9c-5cfc-4ba0-938e-ad20ffe94b41.png">

**Comment by dnys1** [comment]
This has been released in v0.3.0
