### ISSUE TITLE
How to use Authenticator component to protect only some routes

### ISSUE THREAD

**Issue by andrewcrayden** [aws-amplify/amplify-flutter#1277]
**Describe the bug**
The team here seemed very receptive to some [feedback I submitted about Authenticator navigation](https://github.com/aws-amplify/amplify-flutter/issues/1238), so I wanted to use Github again to submit further feedback and ask for some guidance.

It is not clear how to use the Authenticator component to protect only part of an app. The documentation suggests putting the entire `MaterialApp` inside of the Authenticator widget, and then calling `builder: Authenticator.builder()` within the `MaterialApp`.

Has the Authenticator component been designed to allow for protecting only some of the app routes? Is this possible?

Documentation that I referenced:
[Authenticator UI Component docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/flutter/) - Amplify Docs
[amplify_authenticator: ^0.1.0-rc.3 readme and example](https://pub.dev/packages/amplify_authenticator) - pub.dev

```
@override
Widget build(BuildContext context) {
  return Authenticator(
    child: MaterialApp(
      title: 'Authenticator Demo',
      builder: Authenticator.builder(),
      home: const Scaffold(
        body: Center(
          child: Text('You are logged in!'),
        ),
      ),
    ),
  );
}
```

**Comment by dnys1** [comment]
Hi @andrewcrayden - this is not possible yet, although we are planning to release support for this soon.

**Comment by dnys1** [comment]
Great question, and I wish I had a great answer for you haha. I believe the best way is to check the `pub.dev` listing and Github releases page regularly. No firm timelines but within the next few weeks for sure!

**Comment by andrewcrayden** [comment]
@dnys1 checking the `pub.dev` is more than satisfactory. Really appreciate that I can drop feedback here on Github.. Love what your team is doing for Flutter in Amplify!

**Comment by dnys1** [comment]
My pleasure! Thanks for all the feedback :-)

**Comment by Jordan-Nelson** [comment]
Hey @andrewcrayden - This is available in `0.1.0.rc.4`. You can find the docs for it [here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/flutter/#unauthenticated-routes). Let me know if you have any questions or issues while using it. I'll leave this issue open for now if you have any feedback to provide while using it.

**Comment by Jordan-Nelson** [comment]
The docs for this are now located here: https://ui.docs.amplify.aws/components/authenticator?platform=flutter#unauthenticated-routes

I am going to close this issue out.

**Comment by jobypthomas** [comment]
@dnys1 @Jordan-Nelson any update on this feature? I want to have an unprotected route in my app.

**Comment by jobypthomas** [comment]
Currently I have the MaterialApp wrapped in Authenticator so all the routes are protected. I would like to have few routes unprotected.
This is my current setup:
`
return Authenticator(
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,
        routeInformationParser: router.routeInformationParser,
        routeInformationProvider: router.routeInformationProvider,
        routerDelegate: router.routerDelegate,
        builder: Authenticator.builder(),
        theme: ThemeData(
          useMaterial3: true,
          colorSchemeSeed: Colors.green,
        ),
      ),
      authenticatorBuilder: (BuildContext context, AuthenticatorState state) {
        const padding =
            EdgeInsets.only(left: 16, right: 16, top: 48, bottom: 16);
        switch (state.currentStep) {
          case AuthenticatorStep.signIn:
            return Scaffold(
              body: Padding(
                padding: padding,
                child: SingleChildScrollView(
                  child: Column(
                    children: [
                      Text(
                        "Login",
                        style: GoogleFonts.raleway(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Center(
                        child: Container(
                          width: 400,
                          child: SignInForm(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          case AuthenticatorStep.signUp:
            return Scaffold(
              body: Padding(
                padding: padding,
                child: SingleChildScrollView(
                  child: Column(
                    children: [
                      // SignUpForm(),
                      Center(child: Text("Invite Only")),
                    ],
                  ),
                ),
              ),
              // custom button to take the user to sign in
              persistentFooterButtons: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text('Already have an account?'),
                    TextButton(
                      onPressed: () => state.changeStep(
                        AuthenticatorStep.signIn,
                      ),
                      child: const Text('Sign In'),
                    ),
                  ],
                ),
              ],
            );
          default:
            // returning null defaults to the prebuilt authenticator for all other steps
            return null;
        }
      },
    );
  }
`
