### ISSUE TITLE
[RFC]: Amplify Rest API 

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#128]
_This issue is a Request For Comments (RFC). It is intended to elicit community feedback regarding support for Amplify library in Flutter platform. Please feel free to post comments or questions here._

## Purpose
We are developing the Flutter plugin category for Rest API: https://docs.amplify.aws/lib/restapi/getting-started and would like to get your comments on how this API should behave. 

## Flutter API
In Flutter, we propose 2 ways in which we can implement this API:

1. Return a “RestOperation” object when calling the API. You can use this object to await for the success response and to cancel the operation.

```
RestOperation restOperation;

RestRequest restRequest = new RestRequest({
  restOptions: restOptions,
});

try{
  restOperation = Amplify.Api.get(restRequest);
} on Exception catch (e) {
  print(“Exception”);
}

// To get the success response await on the RestRequest's response field
RestResponse response = await restOperation.response;
// RestResponse contains the data retrieved in the HTTP operation 

// To cancel, simply call the cancel method on the RestRequest's 
restOperation.cancel();
```

***Analysis:*** This approach is most similar to how our existing Flutter API plugins work for Auth and Storage which return a single result object and the error via an Exception. We recommend this approach as we believe it is similar to how other Android APIs function and should be familiar to most users. 

2. Have the input “RestRequest” object include a cancelToken field. You will use this cancelToken to cancel the operation. Return a “RestResponse” object when calling the API.  This object contains the data retrieved in a successful HTTP operation. 

```
CancelToken token = new CancelToken();

RestRequest restRequest = new RestRequest({
  restOptions: restOptions,
  cancelToken: token
});

try{
  RestResponse response = Amplify.Api.get(restRequest);
} on Exception catch (e) {
  print(“Exception”);
}

// To cancel, call the cancel method with the same token
Amplify.Api.cancel(token);
```

***Analysis:*** This approach will be familiar to users of Dart’s dio (https://pub.dev/packages/dio#cancellation)package.  However, we are not leaning towards this solution because we don’t want users to concern themselves with tracking and using an additional “CancelToken”.

**Comment by Rayv1** [comment]
Definitely option 1 for exactly the reason you mentioned. I don't want to take care of the CancelToken myself and simply feel better having one object per single request.

**Comment by albemala** [comment]
I vote for option 1

Is there a timeline for when the Amplify Rest API will be implemented?

**Comment by jamesonwilliams** [comment]
@albemala We just did an initial release of Flutter REST API support in 0.0.1-dev.5. https://pub.dev/packages/amplify_api/install. Documentation is not live at time of writing, but it will be here soon: https://docs.amplify.aws/lib/restapi/getting-started/q/platform/flutter

**Comment by albemala** [comment]
Awesome, thank you for letting me know and for your hard work! I'll check it out.
