### ISSUE TITLE
GraphQL mutate operation failed

### ISSUE THREAD

**Issue by mla303** [aws-amplify/amplify-flutter#1280]
Hello, I am new to AWS, I am developing an app in which the first data is coming from dynamodb through Appsync using GraphQL Scheme, and that is working fine now I want to update the record from my app and I was trying but it giving error.

` String graphQLDocument = '''mutation updateDevicesAcepentNet(
      \$device_id: String!, 
      \$name: String!, 
      \status: String) {
          updateTodo(input: { device_id: \$device_id, name: \$name, status: \$status}) {
            device_id
            name
            status
          }
    }''';

      var operation = Amplify.API.mutate(
          request: GraphQLRequest<String>(
            document: graphQLDocument, variables: {
            'device_id': devicid,
            'name': 'my first todo',
            'status': 'todo description',
          },
            apiName: "testAppSync",
          ));

      response = await operation.response;
      var data = response.data;

      print('Mutation result: ' + data);
    

    } on ApiException catch (e) {
      print('Query failed: $e');
    }
    print(Product);

     return listResult;
  }`

![Capture](https://user-images.githubusercontent.com/62279968/150006787-14d334f9-1b2c-44f3-8989-a85bd7ba0858.PNG)

**Comment by dnys1** [comment]
Hi @mla303 - would you be able to share more of your log output? Also, can you provide the Amplify version you're using from your `pubspec.lock` file?
