### ISSUE TITLE
amplify_authenticator: 0.1.0-rc.3 confirm phone number issue

### ISSUE THREAD

**Issue by egyangel** [aws-amplify/amplify-flutter#1296]
**Describe the bug**
1- Wrong phone number prefix on the confirmation page
![image](https://user-images.githubusercontent.com/4232680/150643188-65b96dc8-273b-4496-8a94-e46c211d650b.png)

2- click on the confirm button dosn't do any thing, with or without the right confirmatin number. (No error message)

**To Reproduce**
1. Create new authentication based on phone_number
2. Signup for new account
3. enter the confirmation code recived via sms
4. click confirm button 

**Expected behavior**
Confirm button should either show an error message or confirm the registration number

**Screenshots**
amplify_flutter: ^0.3.1
  amplify_datastore: ^0.3.1
  amplify_core: ^0.3.1
  amplify_auth_cognito: ^0.3.1
  amplify_api: ^0.3.1
  amplify_authenticator: ^0.1.0-rc.3

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Dependencies (<code>
  amplify_flutter: ^0.3.1
  amplify_datastore: ^0.3.1
  amplify_core: ^0.3.1
  amplify_auth_cognito: ^0.3.1
  amplify_api: ^0.3.1
  amplify_authenticator: ^0.1.0-rc.3
  </code>)</summary>
  
  ```
  Paste the contents of your "pubspec.lock" file here
  ```

</details>

**Comment by Jordan-Nelson** [comment]
Hello @egyangel - I was able to reproduce this. Thanks for bringing it to our attention. I will let you know when we have a fix for this.

**Comment by Jordan-Nelson** [comment]
@egyangel - I just merged a fix for this. I will let you know when there is a new RC available.

**Comment by Jordan-Nelson** [comment]
@egyangel this should be resolved now in `0.1.0.rc.4`. I am going to close this issue out, but please do not hesitate to open an another if have any other issues or feedback to provide. Thanks again for bringing this to our attention.

**Comment by egyangel** [comment]
hello @Jordan-Nelson ,
I've just tested it and it works greate 

Many Thanks for your attention 👍
