### ISSUE TITLE
Auth Delete User (Android Support)

### ISSUE THREAD

**Issue by fdarsot** [aws-amplify/amplify-flutter#1297]
as per the new iOS guidelines 5.1.1, Apple requires apps to have the ability to let users delete their accounts.

is there a function or feature to allow for this? currently my team and i are using AWS cognito for user auth/signup.

please advise.

**Comment by Jordan-Nelson** [comment]
Hello @fdarsot - this feature is actively being worked on. There is an open PR for this - #1236. Please note that initially this API will only support iOS.

I have marked this as a feature request.

**Comment by haverchuck** [comment]
@fdarsot We hope to launch this feature soon!

**Comment by haverchuck** [comment]
@fdarsot We have implemented the [deleteUser](https://docs.amplify.aws/lib/auth/delete_user/q/platform/flutter/) API and released it in [version 0.3.2](https://pub.dev/packages/amplify_auth_cognito/changelog). For the moment it is ios-only, but are hoping to add Android support soon. We will keep this issue open pending the release of Android support.

**Comment by haverchuck** [comment]
@fdarsot I have a draft PR up for Android support, but it's contingent on an in-flight PR in amplify-android. We will release this feature once amplify-android releases theirs.

**Comment by 7agustibm** [comment]
Hi @haverchuck! I see you have a PR. Can you help?

**Comment by abdallahshaban557** [comment]
@7agustibm - we are currently finalizing this feature - we have some testing left to be done to ensure this feature is solid. We will update this issue when it is released.

**Comment by dnys1** [comment]
This feature has been released with v0.5.0
