### ISSUE TITLE
Apple sign in page does not appear when trying signInWithWebUI in iOS

### ISSUE THREAD

**Issue by HyconLogan** [aws-amplify/amplify-flutter#1304]
**Describe the bug**
When trying signInWithWebUI, the Apple sign in page is not displayed and the WebDomain page is displayed.

**To Reproduce**

    try {
      await Amplify.Auth.signOut();
    } on AuthException catch (e) {
      print(e);

    try {
      var res = await Amplify.Auth.signInWithWebUI(
          provider: AuthProvider.apple);
    } on AmplifyException catch (e) {
      print(e.message);
    }

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "myappdata",
                        "AppClientId": "myappdata",
                        "Region": "myappdata"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "myappdata",
                            "AppClientId": "myappdata",
                            "SignInRedirectURI": "myappdata",
                            "SignOutRedirectURI": "myappdata",                            
                            "Scopes": [
                                "email",
                                "openid",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_NUMBERS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

**Expected behavior**
When trying signInWithWebUI, the Apple sign in page is displayed.

**Screenshots**
![error](https://user-images.githubusercontent.com/90752589/150903971-d8c74d24-1c7b-47b3-9ed6-7a249441035f.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[*] iOS

**Comment by fjnoyp** [comment]
Hi @HyconLogan looks like you closed the issue so assuming it's resolved. 

It seems the setup steps on the Apple developer website might have been missed.  Docs: 

https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#prerequisites
