### ISSUE TITLE
Missing documentation for re-evaluating sync expressions

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#1315]
Amplify-flutter is missing documentation on re-evaluating sync expressions. See example of [docs for amplify-android](https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#reevaluate-expressions-at-runtime).

Original comment
---

For the Datastore I have a question, is it possible to only sync specific model to local? 

Since I'm using a data model called `User` to save some user's information like avatar url, nickname, etc. But you know that it's bad to sync other user's profile to local. So I'm supposed to call API to fetch user's profile instead of syncing all user's data. But for the other models, I want them to be synced.

_Originally posted by @quirkeer in https://github.com/aws-amplify/amplify-flutter/issues/1290#issuecomment-1019328791_

**Comment by HuiSF** [comment]
Waiting for commit https://github.com/aws-amplify/amplify-flutter/commit/06b48980028d9baebeab180db10dba517ed339d1 to be released to support the use cases listed in reevaluate sync expression documentation.

**Comment by HuiSF** [comment]
Reevaluate `syncExpression` [document](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#reevaluate-expressions-at-runtime) has been added.
