### ISSUE TITLE
after DataStore.clear(), DataStore.query() empty return.

### ISSUE THREAD

**Issue by two4zero** [aws-amplify/amplify-flutter#1316]
**Describe the bug**

after DataStore.clear(), DataStore.query() return empty. (no exceptions).

```
  /// Starts the DataStore's synchronization with a remote system, if DataStore is configured to support
  /// remote synchronization. This only needs to be called if you wish to start the synchronization eagerly.
  /// If you don't call start(), the synchronization will start automatically, prior to executing any other
  /// operations (query, save, delete, update).
  Future<void> start()
```
- synchronization started automatically in second query, also.

**To Reproduce**
1. default app start
2. Amplify.configure
3. Auth.signIn (option)
4. DataStore.query > return not empty
5. Auth.signOut (option)
6. DataStore.clear > from https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#clear-local-data
7. Auth.signIn (option)
8. DataStore.query > (same query no. 4.) return empty

**Expected behavior**

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[√] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```>flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.438], locale ko-KR)
    • Flutter version 2.8.1 at D:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\test\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\test\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.438]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.57

• No issues found!```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  amplify_flutter: ^0.3.2
  amplify_datastore: ^0.3.2
  amplify_api: ^0.3.2
  amplify_auth_cognito: ^0.3.2
  ```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by HuiSF** [comment]
Hi @two4zero thanks for opening this thread. This behavior is expected -

* When invoking `Amplify.DataStore.clear()`, existing instance of underlying Sync Engine for DataStore will be destroyed
* All local SQLite tables will be removed

After the second user sign in, if you directly invoke `Amplify.DataStore.query()`:
* DataStore reinitiate Sync Engine and trigger initial sync from cloud for currently signed user
* Return result (The query doesn't wait for the initial sync from cloud to complete)

Hence, you may get an empty list returned.

Here are two recommendations:

1. After the second user signed in, to invoke [`Amplify.DataStore.observeQuery` instead `query`](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time)
2. After the second user signed in, to invoke `Amplify.DataStore.start()`, this API reinitiate Sync Engine and triggers initial sync for currently signed user, and wait for `ready` event from `Amplify.Hub` to start other DataStore operations. For example

```dart
hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) { 
   if (msg.eventName == "ready") { 
     // logic to start query to get data for rendering
   } 
 }); 

await Amplify.DataStore.start();
```

**Comment by two4zero** [comment]
Hi, @HuiSF ~

i understand.

However, according to the comments on ```Future<void> start()``` , it should be auto-synchronized before querying (any other
operations / query, save, delete, update).
Is there an error in the comments?

**Comment by two4zero** [comment]
Hi @HuiSF 
Thanks for the kind explanation~.
```
The process of syncing data, however, is asynchronous, ...
```

**Comment by bordernone** [comment]
> Hi @two4zero thanks for opening this thread. This behavior is expected -
> 
> * When invoking `Amplify.DataStore.clear()`, existing instance of underlying Sync Engine for DataStore will be destroyed
> * All local SQLite tables will be removed
> 
> After the second user sign in, if you directly invoke `Amplify.DataStore.query()`:
> 
> * DataStore reinitiate Sync Engine and trigger initial sync from cloud for currently signed user
> * Return result (The query doesn't wait for the initial sync from cloud to complete)
> 
> Hence, you may get an empty list returned.
> 
> Here are two recommendations:
> 
> 1. After the second user signed in, to invoke [`Amplify.DataStore.observeQuery` instead `query`](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time)
> 2. After the second user signed in, to invoke `Amplify.DataStore.start()`, this API reinitiate Sync Engine and triggers initial sync for currently signed user, and wait for `ready` event from `Amplify.Hub` to start other DataStore operations. For example
> 
> ```dart
> // after the second signing in
> hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) { 
>    if (msg.eventName == "ready") { 
>      // logic to start query to get data for rendering
>    } 
>  }); 
> 
> await Amplify.DataStore.start();
> ```

the event "ready" doesn't seem to fire even after calling ` await Amplify.DataStore.start();` manually.

```javascript

        const listener = Hub.listen("datastore", async (hubData) => {
            const { event, data } = hubData.payload;
            if (event === "ready") {
                console.log("ready");
            }
        });

```

I am facing similar issue described here: https://github.com/aws-amplify/amplify-js/issues/5991#issuecomment-639168170

> I get data when I query, but after clearing the DataStore queries stop working. Hard reloading after clearing shows the data again, but my app clears the DataStore when a user logs out
