### ISSUE TITLE
Notification support with ADM 

### ISSUE THREAD

**Issue by aydemiromer** [aws-amplify/amplify-flutter#1317]
I wanna push notifications using ADM and flutter? How I can add endpoints? There is a server built on ec2. I want to communicate here with the adm and then send a notification to the app coded with flutter. Is it enough to install Amplify for endpoint? I have access tokens that can be distinguished in login processes.

**Comment by fjnoyp** [comment]
Hi @aydemiromer we currently do not support push notifications.  We have a GitHub issue to track it: https://github.com/aws-amplify/amplify-flutter/issues/319

**Comment by abdallahshaban557** [comment]
@aydemiromer  - please give issue #319 a thumbs up. It will help us get more of an understanding on the demand for this feature!
