### ISSUE TITLE
Simplify amplifyconfiguration.dart

### ISSUE THREAD

**Issue by rmelian** [aws-amplify/amplify-flutter#132]
Hello guys, thank you for putting together amplify for flutter.

After playing with the project I noticed if you want to use another tool like CDK to generate aws resources is a little cumbersome to edit the amplifyconfiguration.dart file. I have used before the amplify Auth lib and I don't remember it been that complicated. 

In simple words the file amplifyconfiguration.dart is not easy to edit by hand, so having a simplified structure would be great for users having the aws resources created already. 

Keep the awesome work 😃

**Comment by jamesonwilliams** [comment]
Thanks @rmelian for the feedback. We'll take this into account as we plan future revisions to the configuration file structure.

**Comment by dnys1** [comment]
We have released the [`AmplifyConfig`](https://pub.dev/documentation/amplify_flutter/latest/amplify_flutter/AmplifyConfig-class.html) class which can be used to parse and interact with the `amplifyconfiguration` in a fully-typed way, e.g.

```dart
import 'dart:convert';

import 'package:amplify_flutter/amplify_flutter.dart';

import 'amplifyconfiguration.dart';

final parsedConfig = AmplifyConfig.fromJson(json.decode(amplifyconfig));

// Get all API endpoints
final endpoints = config.api!.awsPlugin!.endpoints;
print(endpoints);

// {
//     "myapi": {
//         "endpointType": "GraphQL",
//         "endpoint": "<ENDPOINT>",
//         "region": "us-west-2",
//         "authorizationType": "API_KEY",
//         "apiKey": "<API_KEY>"
//     }
// }


// Add an endpoint configuration
final myApi = endpoints['myapi'];
endpoints['myapi_IAM'] = myApi.copyWith(
  authorizationType: APIAuthorizationType.iam,
);

// Configure Amplify
await Amplify.configure(json.encode(parsedConfig));
```

We plan to iterate on this concept to address the issues of #1115 and make creating a configuration from scratch a lot easier.
