### ISSUE TITLE
Amplify  REST API configuration  import  via CLI tool

### ISSUE THREAD

**Issue by rabi-palmtree** [aws-amplify/amplify-flutter#1327]
**Describe the bug**
The amplify cli tool   does not have a  "api import" option to import and access an existing REST(ECS) resource.  .
Note the amplify cli tool support   auth import, storage import, BUT NOT api import.
> amplify auth  import
> amplify storage import 

Using the auth/storage import calls the "amplifyconfiguration.dart" is locally updated.
Currently following the steps mentioned in [Use existing AWS REST API resources](https://docs.amplify.aws/lib/restapi/existing-resources/q/platform/flutter/) I have edited this amplifyconfiguration.dart locally to add access to an API Gateway resource.

"api": {
        "plugins": {
            "awsAPIPlugin": {
                "mobile-app-facing": {
                    "endpointType": "REST",
                    "endpoint": "my-existing-api-gateway",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }
Note :  "CognitoUserPool", "CredentialsProvider" are already configured in this amplifyconfiguration.dart

Now  how do I now add this API configuration to an  my Environment? 

$ amplify status

    Current Environment: dev
    
┌──────────┬─────────────────────────┬───────────┬───────────────────┐
│ Category           │ Resource name           │ Operation       │ Provider plugin   │
├──────────┼─────────────────────────┼───────────┼───────────────────┤
│ Auth                  │ myauthresource           │ No Change     │ awscloudformation │
├──────────┼─────────────────────────┼───────────┼───────────────────┤
│ Storage             │ mystorageresource     │ No Change     │ awscloudformation │
└──────────┴─────────────────────────┴───────────┴───────────────────┘

I have tried the following, none of which work

$ amplify api update
? Select from one of the below mentioned services: REST
🛑 No REST API resource to update. Use "amplify add api" command to create a new REST API

$ amplify api push

    Current Environment: dev
    
┌──────────┬───────────────┬───────────┬─────────────────┐
│ Category          │ Resource name            │ Operation            │ Provider plugin                   │
└──────────┴───────────────┴───────────┴─────────────────┘

No changes detected

$ amplify env update
? Specify an IAM Policy ARN to use as a permissions boundary for all Amplify-generated IAM Roles in the dev environment: 
Run `amplify push --force` to update IAM permissions boundary if you have no other resource changes.
Run `amplify push` to deploy IAM permissions boundary alongside other cloud resource changes.

**Comment by rabi-palmtree** [comment]
I also tried 

$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
┌──────────┬─────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name           │ Operation │ Provider plugin   │
├──────────┼─────────────────────────┼───────────┼───────────────────┤
│ Auth     │ casecontroluiv2e5ba0eb1 │ No Change │ awscloudformation │
├──────────┼─────────────────────────┼───────────┼───────────────────┤
│ Storage  │ casecontroluiv20720f9e7 │ No Change │ awscloudformation │
└──────────┴─────────────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? Yes
✔ All resources are updated in the cloud

It does not detect that I have configured an existing API gateway end point with this.

**Comment by rabi-palmtree** [comment]
Filed this  with [amplify-cli issues](https://github.com/aws-amplify/amplify-cli/issues)
[Importing existing ECS API with amplify-cli](https://github.com/aws-amplify/amplify-cli/issues/3977#issuecomment-1029639221)

**Comment by cshfang** [comment]
Hi @rabi-palmtree, this looks like a feature gap with the Amplify CLI - which is not Amplify Flutter specific. I see that you have already found and commented on the RFC - which is a much better place to track the progress of this feature - so I'm going to close this ticket at this time but please feel free to reopen if you feel it was closed prematurely.

**Comment by rabi-palmtree** [comment]
Is there a way to increase the visibility/priority if this Amplify CLI issue.
Will not most  real world/"non hello world" usages of REST API with flutter and amplify  run into this issue.

**Comment by dnys1** [comment]
Since this is a feature request, it will depend on the prioritization of the Amplify CLI team. Leaving feedback on the RFC is the best way to help that process since that is what our teams use for planning. 

You should be able to at least use the REST API by adding it to your amplify configuration. The only thing you will be unable to do is configure that API via the Amplify CLI.
