### ISSUE TITLE
Desktop Support for amplify-flutter

### ISSUE THREAD

**Issue by jeffglaum** [aws-amplify/amplify-flutter#133]
It's great to see Amplify brought to Flutter.  The attractiveness of the framework is the ability to run almost anywhere.  When might we see amplify-flutter working on desktop (Ubuntu and macOS)?

**Comment by haverchuck** [comment]
@jeffglaum We don't have specific dates on desktop or web support, but we are definitely aware that there is demand for this!

**Comment by moioo91120** [comment]
+1 for web plz :)

**Comment by jamesonwilliams** [comment]
Thanks, @moioo91120! We're tracking support for Flutter web in https://github.com/aws-amplify/amplify-flutter/issues/234.

Please 👍 on #234 for [Flutter Web](https://flutter.dev/web).
Please 👍 on this current #133 for [Flutter Desktop](https://flutter.dev/desktop).

**Comment by joekendal** [comment]
This may seem counterintuitive to the ethos of Flutter - which is designed to support packages in a platform-independent way. There doesn't seem to be a checklist of things to do and I need to implement this and open a PR if not. 

I'm not sure why it's not supported by default. Is this to do with not having a Dart implementation of any of the modules and instead having a wrapper around the original iOS and Java libraries? If so then it may be cumbersome but the only way is to actually rewrite the entire Amplify code in Dart and then it will run on all platforms. There isn't really a workaround. The iOS and Android is just a temporary fix but will never be truly Flutter.

**Comment by talamaska** [comment]
Not to be picky, but there is already web implementation for amplify. Yes it doesn't follow the same API probably, but still, a thin dart wrapper arround it should make it usable in flutter, It is already usable, but you need to play with js interop. 
@joekendal right, but Amplify Mobile SDK and Web SDK exist from some time ago. Desktop never existed, and it should be written on c/c++ in order to make it compilable for different desktops.
As Flutter first started with iOS and Android, Amplify started first with what they have to make it work as fast as possible. 
Sure the idea of writing it from scratch on Dart isn't a bad idea, it's just cumbersome to start all over again, instead of just wrapping the native sdks with thin wrapper. I'm sure that if there is a market, Amplify team will eventually port the code to desktop when it becomes stable I guess.
Why firebase would start also from mobile?

**Comment by joekendal** [comment]
@talamaska that sounds quite resource-heavy to have two processes running and have them communicate somehow. The closest thing I can think of is implementing https://pub.dev/packages/graphql_flutter to handle the offline cache and authorisation with AppSync.

**Comment by sgehrman** [comment]
Amplify is useless without desktop support.

**Comment by ugurcan** [comment]
Is there any estimated date for Windows Desktop support? For example last quarter of 2021 or first quarter of 2022? When do you plan to release (at least) beta version?

**Comment by TimWhiting** [comment]
Alternatively may I suggest a dart implementation rather than having to support interop with the native platforms for web+3desktops+2mobileOS. It seems to me that the overhead of managing 6 different bindings / interop is more work than supporting dart directly.

**Comment by pieterbergmans** [comment]
Desperately wanting Amplify Auth integration with Flutter Desktop (Windows, Mac). Any ETA? Even a rough estimate would be great: Q2, 2022....Q3, 2022, etc.

**Comment by hachirokoo** [comment]
I am waiting for this too.

**Comment by abdallahshaban557** [comment]
@pieterbergmans @hachirokoo - we do not have an exact timing at this time, but supporting web and desktop for Flutter is our highest priority for this year. We will share our estimates for timelines when we have them.

**Comment by hachirokoo** [comment]
@abdallahshaban557 Thanks for your confirmation. I am sure knowing the roadmap will help other devs / companies planning their choice of tools for their Flutter app as it did for my case. Keep us posted. Cheers.

**Comment by abdallahshaban557** [comment]
@hachirokoo - we absolutely agree with that! Thank you for sharing your feedback - and we will keep you posted over this GH issue!

**Comment by shvc** [comment]
+1 for desktop, based on dart will be better!

**Comment by alperentekay2** [comment]
+1 for desktop

**Comment by sookah** [comment]
+1 for desktop and embedded support

**Comment by MarlonJD** [comment]
+1 for desktop. Please date for this. I want to use amplify for a big project.

**Comment by abdallahshaban557** [comment]
@sookah, since this ticket is for supporting Desktop, it would be great if you can help us by submitting a [Github feature request](https://github.com/aws-amplify/amplify-flutter/issues/new) specifically for Embedded support - including some of your use cases!

**Comment by gdhananjay** [comment]
+1

Eagerly waiting for timelines. I have our current app in firebase. But wanted to evaluate amplify. But this part is stopping us.

**Comment by pieterbergmans** [comment]
Can we get a timeline update, please?  Or, can you at least tell us if you've started working on this?  I'd think if this was in your project management portfolio that you could give us a rough indication of when this we could expect this to be delivered or provide us with milestone delivery dates. Please, anything!

**Comment by MarlonJD** [comment]
Auth is really good to arrive, for me i need GraphQL API support secondary.

**Comment by abdallahshaban557** [comment]
@MarlonJD - makes sense! I think we will have support for API-REST, then API-GraphQL after Auth!

**Comment by gam3boy1** [comment]
@abdallahshaban557 Do you have a rough timeline for when a beta version for web support (especially auth) will be released?

**Comment by abdallahshaban557** [comment]
Hi @gam3boy1 - we do not have exact timelines at this point. We will be able to share additional details in the next month!

**Comment by pieterbergmans** [comment]
@abdallahshaban557 - If you could provide all the Auth features that you currently provide for Android/iOS and provide them for PC + Mac + Web, that would be great.

**Comment by PeterAkande** [comment]
+1 for desktop support..
Already had my way around it though...

Instead of using amplify, I consumed the rest APIs to do most of what we needed in our product.

**Comment by abdallahshaban557** [comment]
Hi @gam3boy1 - an alternative could be for you to use our Sigv4 client to sign HTTP requests to talk to AWS services directly. https://pub.dev/packages/aws_signature_v4. You can also try the solution mentioned by @PeterAkande to use REST APIs for your app in the meantime.

@pieterbergmans - Auth is definitely the first category we plan on supporting for web and all desktop (Mac, Windows, Linux).

**Comment by SilverLinings89** [comment]
this would be great because (together with web support) it would be possible to develop against Amplify in a single language for all platforms. Afaik the only alternatives currently would be ionic or react native which are both inferior performance wise.

**Comment by haverchuck** [comment]
**Amplify Flutter announces web and desktop support (Developer Preview) for Authentication**

Hi everyone,

Today AWS Amplify is announcing a developer preview to expand Flutter support to web and desktop, starting with the Authentication category.

With this developer preview version, developers can use a single codebase with the Amplify Authentication category to build Flutter apps that target iOS, Android, web, and desktop (Mac, Linux, Windows). Our [Authenticator UI library](https://ui.docs.amplify.aws/flutter/connected-components/authenticator) has also been upgraded to support Flutter web and desktop, providing developers with a sign in/sign up experience that works across iOS, Android, web, and desktop with minimal configurations.

You can read more about this launch in our [blog post](https://aws.amazon.com/blogs/mobile/amplify-flutter-auth-web-and-desktop/) and [docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/)

We look forward to your feedback and will continue to work hard to deliver web and desktop support for the rest of Amplify Flutter categories in future releases.

**Comment by Groseuros** [comment]
Hello

First of all, thanks for this developer preview, this is awesome !

I've tested Auth on all platforms (username / pwd and social auth with web UI) and I've only a minor issue to report so far on Linux platform : when using social auth with web UI, I have to manually close the browser tab in order to complete authentication otherwise it loops forever on a white tab.

**Comment by Jordan-Nelson** [comment]
Hi @Groseuros - Thank you for reporting this. Would you be able to open a new issue for this so that we can capture and relevant info and track a fix for this?

**Comment by pieterbergmans** [comment]
YEAH! I will test and provide you with feedback.

**Comment by abdallahshaban557** [comment]
**Amplify Flutter announces Web and Desktop support (Developer Preview) for API (GraphQL + REST), Analytics, and Storage**

Hi everyone,

Today AWS Amplify is announcing a developer preview to expand Flutter support to web and desktop for API (GraphQL + REST), Analytics, and Storage.

With this developer preview version, you can use a single codebase to build Flutter apps that target iOS, Android, Web, and Desktop (Mac, Linux, Windows). We have also written fully this developer preview fully in Dart, providing you with a consistent experience across the platforms you target. 

You can read more about this launch in our [blog post](https://aws.amazon.com/blogs/mobile/announcing-flutter-web-and-desktop-support-for-aws-amplify-storage-analytics-and-api-libraries/)

Next for us is supporting Datastore as well for Flutter Web and Desktop! Stay tuned!

**Comment by ErnestDaDev** [comment]
I am loving this! Kudos to you guys for bringing these! Cant't wait for DataStore! Should be awesome as well!

**Comment by abdallahshaban557** [comment]
@ErnestDaDev - that is awesome to hear! Thank you for the feedback!

**Comment by abdallahshaban557** [comment]
Hi everyone,

We are excited to announce that we have released the general availability of Flutter web and desktop support for Auth, API (GraphQL + REST), Analytics, and Storage. To upgrade to our latest version, you can follow our [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/). You can see a list of the features and bug fixes we have released in our [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0).

When interacting with GraphQL APIs, use the API category for all platforms or DataStore for Android or iOS. This is because we retained DataStore on the original Android & iOS implementation. We’re looking to bring data synchronization and offline-data experiences to the web and desktop in the future.
