### ISSUE TITLE
amplifyconfiguration without CognitoIdentity

### ISSUE THREAD

**Issue by mizzb** [aws-amplify/amplify-flutter#135]
I want to configure cognito auth without CognitoIdentity.
Is there anyway to do it?

**Comment by brunovsiqueira** [comment]
Hello guys. I have the same issue. Can you guys help me please?

**Comment by haverchuck** [comment]
@mizzb @brunovsiqueira By 'without CognitoIdentity' I assume you mean 'without a Cognito Identity Pool'.  If that's the case, then yes-  you can configure Cognito to use a UserPool only (although I don't believe this is necessarily recommended depending on the other Amplify categories you may wish to use).

If you're using the Amplify CLI, you can run `amplify add auth` and the select `Manual configuration`.  Then, you can select `User Sign-Up and Sign-In only`.
<img width="980" alt="Screen Shot 2021-02-17 at 3 20 37 PM" src="https://user-images.githubusercontent.com/10621276/108281023-dffb6f00-7133-11eb-909f-0c39a8130675.png">

This should create a configuration file which looks like this:

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "myID",
                        "AppClientId": "myAppID",
                        "AppClientSecret": "myAppSec",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
```
I think this answers the question - so I'm closing this issue for now.
