### ISSUE TITLE
Missing Signup options cause NoSuchMethodError

### ISSUE THREAD

**Issue by JamesMcIntosh** [aws-amplify/amplify-flutter#136]
**Describe the bug**
`AuthCategory.signUp()` parameter named `options` is treated as mandatory but is not a required field.

**To Reproduce**
Execute the following code and 
```
final SignUpResult result = await Amplify.Auth.signUp(
  username: "username",
  password: "password",
);
```
`SignUpRequest` is created within the `signUp` method which has mandatory parameter named `options` (which is null set to null). This causes the exception

```NoSuchMethodError: The method 'serializeAsMap' was called on null.```

See: [SignUpRequest Line 29](https://github.com/aws-amplify/amplify-flutter/blob/562c009884316ca5fd1823aaab35f01fb1dab675/packages/amplify_auth_plugin_interface/lib/src/SignUp/SignUpRequest.dart#L29)
```
pendingRequest['options'] = options.serializeAsMap();
```

**Fix**

1. Update method signature in `AuthCategory.signUp` to make options a required field
```
Future<SignUpResult> signUp({@required String username, @required password, @required SignUpOptions options}
```
2. Update method signature in `AuthCategory.signUp` to give options a default value
```
Future<SignUpResult> signUp({@required String username, @required password, SignUpOptions options = const SignUpOptions()}
```
3. Null check options in `SignUpRequest.serializeAsMap()`
```
if (options != null) {
  pendingRequest['options'] = options.serializeAsMap();
}
```

**Comment by haverchuck** [comment]
@JamesMcIntosh We can't make the options field required at this time, but we ARE implementing a fix to serializeAsMap call as you suggested. The result will be a response from the platform code indicating that this request is malformed, which should hopefull be more helpful.

**Comment by JamesMcIntosh** [comment]
@haverchuck Sounds good as long as the platform code error explains that it's the option field missing

**Comment by Ashish-Nanda** [comment]
@JamesMcIntosh A fix for this bug was released today in version `0.0.1-dev.3`, so will go ahead and close it out. Please give it a try and let us know if you are still facing issues, and we can look into it.

**Comment by haverchuck** [comment]
@JamesMcIntosh I don't think we are currently surfacing the specific fields that are missing, but we are looking at large, general improvement to our error handling, so please be patient.  We are aware that this (and other) error visibility issues exist.

**Comment by JuanDavid1996** [comment]
Hi, I update amplify_auth_cognito to ^ 0.2.1, then I made this solution
```
class QCSignUpOptions extends SignUpOptions {
  final Map<String, String> options;
  const MySignUpOptions({required this.options}) : super(userAttributes: options);
  @override
  Map<String, dynamic> serializeAsMap() {
    return options;
  }
}

And finally

 var options = Map<String, String>();
      options["foo"] = "foo";
      options["bar"] = "bar";

var signUpOptions = QCSignUpOptions(options: options);

      await Amplify.Auth.signUp(
          username: emailController.text,
          password: passwordController.text,
          options: signUpOptions);
```
