### ISSUE TITLE
Amplify failing to configure with Auth

### ISSUE THREAD

**Issue by michaeljajou** [aws-amplify/amplify-flutter#1371]
I am working on adding Authentication to my flutter app. I was able to successfully get the API configured, however, now when I try to add the Cognito API it seems that it is failing to configure. 

I get this message back: 

`An error occurred while configuring Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify[/auth_cognito]()))`

Here is my code

`class BaseApi {
  static Future<void> configureAmplify() async {
    try {
      await Amplify.addPlugins([
        AmplifyAuthCognito(),
        AmplifyAPI(),
      ]);
      await Amplify.configure(amplifyconfig);
      print("Amplify successfully configured");
    } catch (e) {
      print('An error occurred while configuring Amplify: $e');
    }
  }
}`

`
void main() async {
  runApp(const PurposeApp());
  await BaseApi.configureAmplify();
}
`

**Comment by haverchuck** [comment]
@michaeljajou Which amplify verison are you using, and on which platform? Can you also please post your amplifyconfig? Thanks.

**Comment by ArrowBrown** [comment]
Hey, I'm also seeing this same error 

**Error**
`An error occurred while configuring Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify[/auth_cognito]()))`

**Amplify configure upset**
` Future<void> _configureAmplify() async {
    try {
      // Add the following line to add Auth plugin to your app.
      await Amplify.addPlugin(AmplifyAuthCognito());

      // call Amplify.configure to use the initialized categories in your app
      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      print('An error occurred configuring Amplify: $e');
    }
  }`

**Amplify Config**
`const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-************************",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-**************",
                        "AppClientId": "****************",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';`

**Amplify Version**
  amplify_flutter: ^0.4.0
  amplify_auth_cognito: ^0.4.0


**Platform**
Android

**Comment by ArrowBrown** [comment]
After upgrading the issues looks as if its fixed. 

**Amplify Version**
amplify_flutter: ^0.4.1
amplify_auth_cognito: ^0.4.1

**Comment by abdallahshaban557** [comment]
Perfect! Thank you for the confirmation @ArrowBrown.

@michaeljajou - we will close this issue for now!
