### ISSUE TITLE
Is there a way to login with email and password instead of username and password?

### ISSUE THREAD

**Issue by VadimBliz** [aws-amplify/amplify-flutter#1375]
I haven't find a way to sign in using email and password, only with username and password
`
Amplify.Auth.signIn(
      username: 'name',
      password: 'Password',
    );
`
Is there a way to login with email instead of username?

**Comment by haverchuck** [comment]
@VadimBliz Yes - you can simply pass the email in the `username` parameter, i.e. 
```dart
Amplify.Auth.signIn(
  username: 'myemail@example.com',
  password: 'mypassword',
)
```

This assumes that you have your userpool configured to either use the email AS the username, or allows signing in via email with the `alias` configuration.  More information can be found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html), under 'Aliases -> Option 1 & Option 2'.

The Amplify CLI supports Option 2 as described on the page I've cited above, but either Option can be configured in the Cognito console.

I am closing this issue for now, but please open another if you have further questions. Thanks!
