### ISSUE TITLE
Uploading using the S3 storage plugin gives a cryptic error message if file does not exist

### ISSUE THREAD

**Issue by JamesMcIntosh** [aws-amplify/amplify-flutter#139]
**Describe the bug**
When uploading a file which doesn't exist using the S3 Storage Plugin an exception is thrown.

The error message gives no indication that the file does not exist on the device and is a very cumbersome to figure out what went wrong.

**To Reproduce**
```
final File file = File("this_file_does_not.exist");
final Map<String, String> metadata = <String, String>{};
metadata["name"] = "this_file_does_not.exist";

final S3UploadFileOptions options = S3UploadFileOptions(accessLevel: StorageAccessLevel.guest, metadata: metadata);
final UploadFileResult result = await Amplify.Storage.uploadFile(key: "this_file_does_not.exist", local: file, options: options);
```

Exception in the Dart stack
```
Unhandled Exception: PlatformException(AmplifyException, UPLOAD_FILE_OPERATION_FAILED, {PLATFORM_EXCEPTIONS: {
platform: Android, 
localizedErrorMessage: Issue uploading file., 
recoverySuggestion: See included exception for more details and suggestions to fix.
}})
AmplifyStorageS3MethodChannel.uploadFile (package:amplify_storage_s3/method_channel_storage_s3.dart:41:7)
<asynchronous suspension>
AmplifyStorageS3.uploadFile (package:amplify_storage_s3/amplify_storage_s3.dart:44:22)
```
I couldn't see any additional information or Exceptions in the stack trace on the Dart side.

With further digging I found the error originates on the Android side of the plugin in `AmplifyStorageOperations.uploadFile()`. This function throws away the cause of the exception and returns an uninformative wrapper AmplifyException
```
Amplify.Storage.uploadFile(
...
  { error ->
      if (!responseSent) {
          responseSent = true
          prepareError(flutterResult, FlutterStorageErrorMessage.UPLOAD_FILE_OPERATION_FAILED.name, error.localizedMessage, error.recoverySuggestion)
      } else {
          LOG.error(FlutterStorageErrorMessage.UPLOAD_FILE_OPERATION_FAILED.name, error)
      }
  }
)
...
```

**Expected behavior**

A useful error message is returned.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[/] Android
[?] iOS

**Comment by JamesMcIntosh** [comment]
@Ashish-Nanda I looked a little bit more into it and the TransferUtility:564 is correctly throwing an `IllegalArgumentException` when the file does not exist, so the behaviour is consistent. I guess the main problem is that when an error is encountered all that happens is the prepareError message is being called with the following

``` prepareError(flutterResult, FlutterStorageErrorMessage.LIST_OPERATION_FAILED.name, error.localizedMessage, error.recoverySuggestion) ```

In these error cases the recoverySuggesting is `See included exception for more details and suggestions to fix.` which is rather useless as the exception is discarded, the Exception with all the details is actually `error.cause`

**Comment by Ashish-Nanda** [comment]
@JamesMcIntosh Thanks for your detailed report on the issue. I'm looking into this today. I'll make sure to add the `error.cause` for the exception raised in the Android platform code.
However, I agree with your initial suggestion of failing fast in the dart layer itself by checking for the existence of the file using `file.existsSync()`

Will post an update once I make the change and validate the fix.

**Comment by NimaSoroush** [comment]
Any update on this?

**Comment by Ashish-Nanda** [comment]
@NimaSoroush Will be looking into this today and will update you once I have a PR up.

**Comment by NimaSoroush** [comment]
@Ashish-Nanda : That would be great. Thanks

**Comment by offlineprogrammer** [comment]
Hi @NimaSoroush @JamesMcIntosh 

You will get the error below if file does not exist 

```

flutter: UploadFile Err: StorageException(message: There is a client side validation error for the field [local] with message: The file located at the `local` URL is missing, recoverySuggestion: Make sure the file exists before uploading to storage., underlyingException: null)

```
Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by JamesMcIntosh** [comment]
@offlineprogrammer Thanks for letting me know, the error message is a lot more useful in explaining the situation.

At the moment I'm stuck back a few releases due to the version bump of the UUID dependency conflicting with other libraries and unable to test it.
