### ISSUE TITLE
 Amplify.Auth.fetchAuthSession TIMEOUT

### ISSUE THREAD

**Issue by miguelflores1993** [aws-amplify/amplify-flutter#1405]
### Description

my application works mostly without internet, so Amplify.Auth.fetchAuthSession this method, it takes almost 50 seconds to respond error, someone tell me how I can solve this?

### Categories

- [ ] Analytics
- [ ] API
- [X] Auth
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

zcx

### Screenshots

zc

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
[√] Flutter (Canal estable, 2.10.0, en Microsoft Windows [Versión 10.0.22000.493], locale es-BO)
[√] Cadena de herramientas de Android: desarrollo para dispositivos Android (Android SDK versión 32.0.0)
[√] Chrome: desarrollar para la web
[√] Android Studio (versión 2021.1)
[√] VS Code (versión 1.64.2)
[√] Dispositivo conectado (3 disponibles)
[√] Disponibilidad de host HTTP
```

### Dependencies

```bash
amplify_flutter: ^0.3.2
amplify_auth_cognito: ^0.3.2
amplify_storage_s3: ^0.3.2
```

### Device

XIAOMI MI 11T

### OS

ANDROID 11

### CLI Version

7.6.15

### Additional Context

W/AWSMobileClient(10936): Failed to federate the tokens
W/AWSMobileClient(10936): com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection reset
W/AWSMobileClient(10936): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
W/AWSMobileClient(10936): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(10936): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(10936): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:750)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:791)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:703)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:640)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:511)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getIdentityId(CognitoCachingCredentialsProvider.java:453)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:785)
W/AWSMobileClient(10936): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:703)

**Comment by dnys1** [comment]
Hi @miguelflores1993 - if the retry period is too long, you can override it by setting a timeout on the `fetchAuthSession` Future, like so:

```dart
try {
  await Amplify.Auth.fetchAuthSession().timeout(
    const Duration(seconds: 5),
  );
} on TimeoutException {
  print('fetchAuthSession timed out');
}
```

**Comment by miguelflores1993** [comment]
thanks!
