### ISSUE TITLE
AmplifyException, Error casting configuration map, Unsupported value: org.json.JSONException: No value for pinpointAnalytics, null

### ISSUE THREAD

**Issue by deimantasa** [aws-amplify/amplify-flutter#142]
**Describe the bug**
After trying to call `configure`, app crashes with exception. 

**To Reproduce**
`init` block
```
 Amplify amplify = Amplify();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    AmplifyAnalyticsPinpoint amplifyAnalyticsPinpoint = AmplifyAnalyticsPinpoint();
    amplify.addPlugin(authPlugins: [authPlugin]);
    amplify.addPlugin(analyticsPlugins: [amplifyAnalyticsPinpoint]);

    print('hi');
    await amplify.configure(amplifyconfig);
```
1. Run the code upon app startup;
2. It will throw
```
E/flutter ( 8525): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(AmplifyException, Error casting configuration map, Unsupported value: org.json.JSONException: No value for pinpointAnalytics, null)
E/flutter ( 8525): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 8525): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 8525): <asynchronous suspension>
E/flutter ( 8525): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 8525): #3      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
E/flutter ( 8525): #4      Amplify.configure (package:amplify_core/amplify_core.dart:71:35)
E/flutter ( 8525): #5      AwsAmplifyService.init (package:fluid/services/aws_amplify_service.dart:23:19)
E/flutter ( 8525): #6      _FluidAppState._initServices (package:fluid/main/main.dart:84:47)
E/flutter ( 8525): <asynchronous suspension>
E/flutter ( 8525): #7      _FluidAppState.initState (package:fluid/main/main.dart:51:5)
E/flutter ( 8525): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4812:57)
E/flutter ( 8525): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
E/flutter ( 8525): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
E/flutter ( 8525): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
E/flutter ( 8525): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4700:16)
E/flutter ( 8525): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
E/flutter ( 8525): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4654:5)
E/flutter ( 8525): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
E/flutter ( 8525): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
E/flutter ( 8525): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3377:20)
E/flutter ( 8525): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4700:16)
E/flutter ( 8525): #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4847:11)
E/flutter ( 8525): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
E/flutter ( 8525): #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2777:33)
E/flutter ( 8525): #22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:906:21)
E/flutter ( 8525): #23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:309:5)
E/flutter ( 8525): #24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter ( 8525): #25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
E/flutter ( 8525): #26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
E/flutter ( 8525): #27     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 8525): #28     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 8525): #29     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 8525): #30     _invoke (dart:ui/hooks.dart:251:10)
E/flutter ( 8525): #31     _drawFrame (dart:ui/hooks.dart:209:3)
```

**Expected behavior**
App should be launched and configured properly.

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
OnePlus6

**Additional context**
`amplifyconfiguration.dart` is left untouched - it was purely autogenerated.

**Comment by haverchuck** [comment]
@deimantasa Does your amplifyconfiguration.dart file have the values defined [here](https://docs.amplify.aws/lib/analytics/existing-resources/q/platform/flutter)?

**Comment by deimantasa** [comment]
> @deimantasa Does your amplifyconfiguration.dart file have the values defined [here](https://docs.amplify.aws/lib/analytics/existing-resources/q/platform/flutter)?

Great spot. No, it didn't have. However, I've changed initialisation by removing analytics.
```
Amplify amplify = Amplify();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    amplify.addPlugin(authPlugins: [authPlugin]);

    print('hi');
    await amplify.configure(amplifyconfig);
```

I received exactly same error. That was the case I've added it in the first place.

**Comment by haverchuck** [comment]
@deimantasa Could you please post your amplifyconfiguration.dart contents (with actual values removed/obscured)?

**Comment by ittsgit** [comment]
hi, execute
$amplify add analytics

? Select an Analytics provider (Use arrow keys)
    `Amazon Pinpoint`
? Provide your pinpoint resource name: 
    `yourPinpointResourceName`
? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analytics events? (we recommend you allow this when getting started) 
    `Yes`

amplify push

--
source
https://docs.amplify.aws/lib/analytics/getting-started/q/platform/flutter#set-up-analytics-backend

**Comment by deimantasa** [comment]
Hello both,

My team decided not to proceed further with this plugin, as there are too many issues and uncertainties at this point. Apologies.

Will close my threads for now. If someone is facing similar issues - happy to open it again.

**Comment by pkhivesara** [comment]
Having similar issue

**Comment by jpascoe** [comment]
I was having the same issue as above but got past issue. Now its reporting the region as missing.

Unhandled Exception: PlatformException(AmplifyException, Error casting configuration map, Unsupported value: org.json.JSONException: No value for region, null)

    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "obscurred",
                    "region": "ap-southeast-2"
                },
                "pinpointTargeting": {
                    "region": "ap-southeast-2"
                }
            }
        }
    }

**Comment by uttusharma** [comment]
Hi, I am having a similar issue.

this is how I  am configuring.
```
AmplifyAuthCognito auth = new AmplifyAuthCognito();
    amplify.addPlugin(authPlugins: [auth]);

    try {
      // Configure

      await amplify.configure(amplifyconfig);
      print('Successfully configured Amplify 🎉');
    } catch (e) {
      print('Could not configure Amplify ☠️');
      print(e);
    }
```
**Reproduce**
1. Code to execute 
```

 final SignUpResult res = await Amplify.Auth.signUp(
            username: event.email,
            password: event.pass,
            options: CognitoSignUpOptions(userAttributes: userAttributes));

```
2. Works when apk run with
> flutter run 
> flutter run --release

3. Doesn't work when 

-  flutter build apk --release 
-  Generate Signed APK (Android Studio)

**Error**

```
2021-01-10 23:51:24.645 29270-29270/? E/MethodChannel#com.amazonaws.amplify/auth_cognito: Failed to handle method call
    g.i: null cannot be cast to non-null type java.lang.reflect.Method
        at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterSignUpRequest.b(Unknown Source:203)
        at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterSignUpRequest.<init>(Unknown Source:90)
        at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.w(Unknown Source:10)
        at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.h(Unknown Source:150)
        at f.a.d.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:170)
        at android.app.ActivityThread.main(ActivityThread.java:7055)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
```
**Package Version** : 
``` 
  amplify_auth_cognito: ^0.0.1-dev.6
  amplify_core: ^0.0.1-dev.6
```


**amplifyconfiguration.dart**
xxxxx = Obscure


```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-south-1:xxxxx",
                            "Region": "ap-south-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-south-1xxxxx",
                        "AppClientId": "xxxxx",
                        "AppClientSecret": "xxxxx",
                        "Region": "ap-south-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}''';
```


Please help with the issues.

**Comment by joelJohanssonT** [comment]
Same problem here!

**Comment by joelJohanssonT** [comment]
Works if you skip 'await'

change 
await amplify.configure(amplifyconfig);  
to
amplify.configure(amplifyconfig);

**Comment by kzhao682** [comment]
> I was having the same issue as above but got past issue. Now its reporting the region as missing.
> 
> Unhandled Exception: PlatformException(AmplifyException, Error casting configuration map, Unsupported value: org.json.JSONException: No value for region, null)
> 
> ```
> "analytics": {
>     "plugins": {
>         "awsPinpointAnalyticsPlugin": {
>             "pinpointAnalytics": {
>                 "appId": "obscurred",
>                 "region": "ap-southeast-2"
>             },
>             "pinpointTargeting": {
>                 "region": "ap-southeast-2"
>             }
>         }
>     }
> }
> ```

Did you ever end up figuring out the issue where the region is missing? I am having similar issues with this right now.

**Comment by patoc00** [comment]
> > I was having the same issue as above but got past issue. Now its reporting the region as missing.
> > Unhandled Exception: PlatformException(AmplifyException, Error casting configuration map, Unsupported value: org.json.JSONException: No value for region, null)
> > ```
> > "analytics": {
> >     "plugins": {
> >         "awsPinpointAnalyticsPlugin": {
> >             "pinpointAnalytics": {
> >                 "appId": "obscurred",
> >                 "region": "ap-southeast-2"
> >             },
> >             "pinpointTargeting": {
> >                 "region": "ap-southeast-2"
> >             }
> >         }
> >     }
> > }
> > ```
> 
> Did you ever end up figuring out the issue where the region is missing? I am having similar issues with this right now.

Hey, having this issue, any luck?

**Comment by jpascoe** [comment]
I think I just removed pinpoint from application until I had time to get back to it.
Jason
