### ISSUE TITLE
Support custom claims

### ISSUE THREAD

**Issue by localsecurity-emily** [aws-amplify/amplify-flutter#1421]
### Description

We have a web app that is built using Angular Amplify and we are now extending some functionality to a mobile app built using flutter. Our pubsec contains:

```
amplify_flutter: ^0.4.0
amplify_datastore: ^0.4.0
amplify_authenticator: ^0.1.0
amplify_auth_cognito: ^0.4.0
amplify_api: ^0.4.0
```

The data model we are working with is:

```
type Customer
  @model
  @key(
    name: "customersByMonitoringCenter"
    fields: ["monitoringCenterId"]
    queryField: "customerByMonitoringCenter"
  )
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "monitoringCenterId"
        operations: [read]
        identityClaim: "custom:monitoringCenterId"
      }
      {
        allow: groups
        mutations: [create]
        groups: ["Owner"]
      }
    ]
  ) {
  id: ID!
  monitoringCenterId: ID!
  ...
}
```

When a user who is in the group "Owner" runs the below request, they get the Customer objects as expected. When a user who is not a member of the owner group, but does have the custom:monitoringCenterId attribute, which matches some of the data in the table, runs the below request, they do not get any results. There is no error, the items list is just blank. On our web app, the related query can be run by users in both auth categories without issue.

```
ModelQueries.list(Customer.classType);
```

I also tried extracting the query out into a custom `GraphQLRequest`, but did not receive any different results.

### Categories

- [ ] Analytics
- [X] API
- [ ] Auth
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
```


### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.2
integrator_customer_management 1.0.0+1

dependencies:
- amplify_api 0.4.0 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.0 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.0 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.0 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.0 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.0 [flutter meta amplify_core]
- amplify_core 0.4.0 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.0 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.0 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1

```
```


### Device

iPhone 13, Nexus 6

### OS

iOS 15.2, Android 11

### CLI Version

7.6.19

### Additional Context

_No response_

**Comment by ragingsquirrel3** [comment]
@localsecurity-emily thanks for reporting this issue. Quick followup question for you: When you say "There is no error, the items list is just blank" do you mean the items list is an empty list or that it's null? By "no error" do you mean that it does not throw exceptions or that there are no errors in the GraphQL response? When a request is rejected by Appsync, the plugin does not throw an exception and the response includes the errors. I want to make sure I'm not missing any info there.

**Comment by localsecurity-emily** [comment]
Sorry, I meant the items array is just an empty array. There is no error returned, rather it just appears that there is no data for the given query (which makes me suspect it's some kind of permisson issue, but the query works within our web app without issue).






EMILY CHEYNE

VP, Product
w: http://localsecurity.io e: ***@***.***




If you have a request for technical support or urgent support, please send a message to ***@***.*** This message and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the sender and delete it from your system.

--- original message ---
On March 1, 2022 at 4:50 PM MST ***@***.*** wrote:



@localsecurity-emily thanks for reporting this issue. Quick followup question for you: When you say "There is no error, the items list is just blank" do you mean the items list is an empty list or that it's null? By "no error" do you mean that it does not throw exceptions or that there are no errors in the GraphQL response? When a request is rejected by Appsync, the plugin does not throw an exception and the response includes the errors. I want to make sure I'm not missing any info there.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by ragingsquirrel3** [comment]
@localsecurity-emily off-hand, I do not, but do you mind providing your full schema here so I can try to reproduce and research?

**Comment by localsecurity-emily** [comment]
Hey, @ragingsquirrel3, our combined schema is 4670 lines long and has got some stuff in it I can't share. However, do you know if people are successfully using Amplify's flutter to successfully query the API with Auth rules like the ones we have above?

**Comment by Jordan-Nelson** [comment]
@localsecurity-emily - The web app is using Amplify-JS, correct? Did you have to customize Authorization header in the web app similar to what is show here: https://github.com/aws-amplify/amplify-js/issues/4751#issuecomment-613717344?

**Comment by localsecurity-emily** [comment]
@Jordan-Nelson, yes, we are using Amplify's Angular library for our web app.
On the web app site of things we do:

```
Amplify.configure({
  API: {
    graphql_headers: async () => {
      const session = await Auth.currentSession();
      return {
        Authorization: session.getIdToken().getJwtToken()
      };
    },
  },
});
```

**Comment by Jordan-Nelson** [comment]
@localsecurity-emily - Thanks for confirming. I believe you will have to set a similar custom header to get this to work. Adding custom headers to graphql requests is not currently supported by amplify-flutter. There is an open feature request for it. You can give that feature a 👍 to express your interest.

I am going to mark this a feature request for custom claims. I am not sure if other work will be required to support this other than the custom header support, but I think it makes sense to track as a separate feature request.

https://docs.amplify.aws/cli-legacy/graphql-transformer/auth/#custom-claims

**Comment by Equartey** [comment]
Hey @localsecurity-emily

Custom claims are available in Flutter v1 through the custom headers parameter. General docs for custom headers can be found [here](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#combining-multiple-graphql-operations-in-a-single-request). 

More specifically here is an example of how to auth a GraphQL request using custom claims:

Given the GraphQL Schema:

```graphql
# Read more about auth rules at: https://docs.amplify.aws/cli/graphql/authorization-rules/#configure-custom-identity-and-group-claims
type Todo @model @auth(rules: [{ allow: owner, identityClaim: "username" }]) {
  id: ID!
  name: String!
  description: String
}
```

Dart snippet:

```dart
final authSession = await Amplify.Auth.fetchAuthSession() as CognitoAuthSession;
final token = authSession.userPoolTokensResult.value.idToken.raw;

final todo = Todo(name: 'Todo: ${uuid()}', description: 'sample description');

final request = ModelMutations.create(
  todo,
  headers: {'authorization': token},
);

final response = await Amplify.API.mutate(request: request).response;
```
