### ISSUE TITLE
on some iOS devices hang during amplify configuration failing with Amplify.AuthError error 

### ISSUE THREAD

**Issue by rabi-palmtree** [aws-amplify/amplify-flutter#1428]
### Description

Our Flutter App is currently being tested in a beta.  
Flutter: 2.10.1
sdk: ">=2.15.0 <3.0.0"
  amplify_auth_cognito: 0.4.1
  amplify_flutter: 0.4.1
  amplify_storage_s3: 0.4.1
  amplify_api: 0.4.1
  
(We upgraded to your latest 0.4.1 because of this issue cropping up in amplify 0.2.8)
Some of our iOS phone users  are facing  this issue during Amplify Configuration ...
 
We get the following logs:

2022-03-03 21:59:15.481616+0530 Runner[1076:276986] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x282c63c80>
2022-03-03 21:59:15.481650+0530 Runner[1076:276989] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x282c13600>
2022-03-03 21:59:15.536692+0530 Runner[1076:276989] [AuthErrorHandler] **The operation couldn’t be completed. (Amplify.AuthError error 2.)**
2022-03-03 21:59:15.818263+0530 Runner[1076:276752] Sentry - debug:: Header {"event_id":"67bf13641d164c1ea61d6c9d749b93af","sdk":{"name":"sentry.dart.flutter","version":"6.3.0","packages":[{"name":"pub:sentry","version":"6.3.0"},{"name":"pub:sentry_flutter","version":"6.3.0"},{"name":"cocoapods:sentry-cocoa","version":"7.9.0"}],"integrations":["isolateErrorIntegration","runZonedGuardedIntegration","widgetsFlutterBindingIntegration","flutterErrorIntegration","widgetsBindingIntegration","nativeSdkIntegration","loadContextsIntegration","loadReleaseIntegration","SentryCrashIntegration","SentryFramesTrackingIntegration","SentryAutoBreadcrumbTrackingIntegration","SentryAutoSessionTrackingIntegration","SentryAppStartTrackingIntegration","SentryOutOfMemoryTrackingIntegration","SentryPerformanceTrackingIntegration","SentryNetworkTrackingIntegration","SentryFileIOTrackingIntegration"]}}

We have seen App failures on the following types of devices
iPhone 11, iOS 15.2.1
iPhone XR, iOS 15.1
iPhone 6, iOS 12.5.5

Note in few test devices Amplify Configuration does go through on some iOS devices and in such the App behaves normally.

The Code Snippet that checks amplify configuration
   ```
try {
      AmplifyAuthCognito auth = AmplifyAuthCognito();
      AmplifyStorageS3 storage = AmplifyStorageS3();
      Amplify.addPlugins([auth, storage]);

      if (!Amplify.isConfigured) await Amplify.configure(amplifyconfig);

      setState(() => _isAmplifyConfigured = true);
    } catch (e) {
      print(e);
      throw (e);
    }
```

### Categories

- [ ] Analytics
- [ ] API
- [X] Auth
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

At our App Start up this error occurs and the App hangs at our splash screen
NOTE:
The App DOES NOT FAIL on Android Devices tested
The App DOES NOT FAIL on the iOS xcode emulators.

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)

[✓] Chrome - develop for the web

[✓] Android Studio (version 4.0)

[✓] Connected device (2 available)



• No issues found!
```

### Dependencies

```bash
Dart SDK 2.15.1

Flutter SDK 2.8.1

casecontrol_v2 2.0.0+1



dependencies:

- amplify_api 0.4.1 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]

- amplify_auth_cognito 0.4.1 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]

- amplify_flutter 0.4.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]

- amplify_storage_s3 0.4.1 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_core]

- auto_size_text 3.0.0 [flutter]

- built_value 8.1.2 [built_collection collection fixnum meta]

- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]

- chewie 1.1.0 [cupertino_icons flutter video_player wakelock]

- device_info_plus 2.1.0 [flutter device_info_plus_platform_interface device_info_plus_linux device_info_plus_macos device_info_plus_web device_info_plus_windows]

- device_preview 1.0.0 [flutter flutter_localizations provider device_frame freezed_annotation json_annotation shared_preferences]

- dio 4.0.4 [http_parser path]

- drift 1.4.0 [async convert collection meta stream_channel sqlite3]

- emoji_picker_flutter 1.0.7 [flutter shared_preferences]

- equatable 2.0.3 [collection meta]

- f_logs 2.0.0 [flutter sembast path_provider intl xxtea meta path stack_trace]

- file_picker 4.5.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]

- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]

- firebase_messaging 11.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]

- firebase_messaging_platform_interface 3.1.6 [firebase_core flutter meta plugin_platform_interface]

- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

- flutter_bloc 7.3.3 [flutter bloc provider]

- flutter_cached_pdfview 0.4.1 [flutter flutter_pdfview flutter_cache_manager path_provider path]

- flutter_contact 0.9.1+8 [collection dartxx equatable flexidate intl logging logging_config quiver uuid flutter]

- flutter_dotenv 5.0.2 [flutter]

- flutter_i18n 0.30.0 [flutter flutter_localizations flutter_web_plugins intl yaml xml2json path toml]

- flutter_launcher_icons 0.9.2 [args image path yaml]

- flutter_local_notifications 9.3.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]

- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]

- flutter_screenutil 5.0.4 [flutter]

- flutter_slidable 1.2.0 [flutter]

- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]

- flutter_video_info 1.2.0 [flutter path]

- fluttertoast 8.0.9 [flutter flutter_web_plugins]

- getwidget 2.0.4 [flutter]

- google_fonts 2.1.0 [flutter http path_provider crypto]

- image_picker 0.8.4+10 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]

- intl 0.17.0 [clock path]

- jiffy 4.1.0 [intl]

- json_annotation 4.4.0 [meta]

- jwt_decoder 2.0.1

- kiwi 4.0.2 [meta]

- logger 1.1.0

- meta 1.7.0

- ntp 2.0.0

- package_info_plus 1.0.6 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]

- path 1.8.0

- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]

- percent_indicator 3.4.0 [flutter]

- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]

- phone_number 0.12.0+1 [flutter meta]

- photo_view 0.12.0 [flutter]

- pin_code_fields 7.3.0 [flutter]

- pinch_zoom 1.0.0 [flutter]

- provider 6.0.1 [collection flutter nested]

- pubnub 4.1.0 [async cbor convert crypto encrypt form_data meta pedantic pool xml]

- pull_to_refresh 2.0.0 [flutter]

- random_string 2.3.1

- retrofit 2.0.1 [dio meta]

- rxdart 0.27.3

- sentry_flutter 6.3.0 [flutter flutter_web_plugins sentry package_info_plus]

- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]

- sqlite3_flutter_libs 0.5.4 [flutter]

- url_launcher 6.0.10 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

- uuid 3.0.6 [crypto]

- video_player 2.2.3 [flutter meta video_player_platform_interface video_player_web]



transitive dependencies:

- amplify_analytics_plugin_interface 0.4.1 [amplify_core flutter meta]

- amplify_api_plugin_interface 0.4.1 [amplify_core collection flutter json_annotation meta]

- amplify_auth_plugin_interface 0.4.1 [flutter meta amplify_core]

- amplify_core 0.4.1 [flutter plugin_platform_interface collection date_time_format meta uuid]

- amplify_datastore_plugin_interface 0.4.1 [flutter meta collection amplify_core]

- amplify_storage_plugin_interface 0.4.1 [flutter meta amplify_core]

- archive 3.2.1 [crypto path]

- args 2.3.0

- asn1lib 1.1.0

- async 2.8.2 [collection meta]

- bloc 7.2.1 [meta]

- boolean_selector 2.1.0 [source_span string_scanner]

- built_collection 5.1.1

- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]

- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]

- cbor 4.1.0 [typed_data convert meta]

- characters 1.2.0

- charcode 1.3.1

- clock 1.1.0

- collection 1.15.0

- convert 3.0.1 [typed_data]

- cross_file 0.3.2 [flutter js meta]

- crypto 3.0.1 [collection typed_data]

- cupertino_icons 1.0.4

- dartx 0.7.1 [characters collection crypto meta path time]

- dartxx 0.5.4 [equatable inflection3 intl recase]

- date_time_format 2.0.1

- dbus 0.7.1 [args ffi meta xml]

- device_frame 1.0.0 [freezed_annotation flutter]

- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]

- device_info_plus_macos 2.2.2 [device_info_plus_platform_interface flutter]

- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]

- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]

- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]

- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]

- fake_async 1.2.0 [clock collection]

- ffi 1.1.2

- file 6.1.2 [meta path]

- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]

- firebase_core_web 1.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]

- firebase_messaging_web 2.2.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]

- fixnum 1.0.0

- flexidate 0.8.0+3 [collection dartx dartxx equatable inflection3 intl logging timezone]

- flutter_blurhash 0.6.4 [flutter]

- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]

- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]

- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]

- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]

- flutter_pdfview 1.2.2 [flutter]

- flutter_plugin_android_lifecycle 2.0.5 [flutter]

- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]

- form_data 1.0.0-nullsafety.1

- freezed_annotation 1.1.0 [collection json_annotation meta]

- http 0.13.4 [async http_parser meta path]

- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]

- image 3.1.3 [archive meta xml]

- image_picker_for_web 2.1.6 [flutter flutter_web_plugins image_picker_platform_interface]

- image_picker_platform_interface 2.4.4 [cross_file flutter http plugin_platform_interface]

- inflection3 0.5.3+2

- js 0.6.3

- logging 1.0.2

- logging_config 0.6.7+7 [js logging]

- matcher 0.12.11 [stack_trace]

- nested 1.0.0 [flutter]

- octo_image 1.0.1 [flutter flutter_blurhash]

- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]

- package_info_plus_macos 1.3.0 [flutter]

- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]

- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]

- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]

- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]

- path_parsing 0.2.1 [vector_math meta]

- path_provider_android 2.0.12 [flutter path_provider_platform_interface]

- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]

- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]

- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]

- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]

- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]

- pedantic 1.11.1

- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]

- petitparser 4.4.0 [meta]

- platform 3.1.0

- plugin_platform_interface 2.1.2 [meta]

- pointycastle 3.5.1 [collection convert js]

- pool 1.5.0 [async stack_trace]

- process 4.2.4 [file path platform]

- quiver 3.0.1+1 [matcher]

- recase 4.0.0

- sembast 3.1.2 [meta path synchronized]

- sentry 6.3.0 [http meta stack_trace uuid]

- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]

- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]

- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]

- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]

- shared_preferences_platform_interface 2.0.0 [flutter]

- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]

- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]

- sky_engine 0.0.99

- source_span 1.8.1 [collection path term_glyph]

- sqflite 2.0.2 [flutter sqflite_common path]

- sqflite_common 2.2.0 [synchronized path meta]

- sqlite3 1.5.1 [collection ffi meta]

- stack_trace 1.10.0 [path]

- stream_channel 2.1.0 [async]

- string_scanner 1.1.0 [charcode source_span]

- synchronized 3.0.0

- term_glyph 1.2.0

- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]

- time 2.1.0 [clock]

- timezone 0.8.0 [path]

- toml 0.11.0 [meta petitparser quiver]

- typed_data 1.3.0 [collection]

- url_launcher_linux 2.0.3 [flutter]

- url_launcher_macos 2.0.3 [flutter]

- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]

- url_launcher_web 2.0.6 [flutter flutter_web_plugins url_launcher_platform_interface]

- url_launcher_windows 2.0.2 [flutter]

- vector_math 2.1.1

- video_player_platform_interface 4.2.0 [flutter flutter_test meta]

- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]

- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]

- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]

- wakelock_platform_interface 0.3.0 [flutter meta]

- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]

- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]

- win32 2.4.1 [ffi]

- xdg_directories 0.2.0+1 [meta path process]

- xml 5.3.1 [collection meta petitparser]

- xml2json 5.3.2 [xml]

- xxtea 2.1.0

- yaml 3.1.0 [collection source_span string_scanner]
```

### Device

iPhone 11, iPhone XR, iPhone 6

### OS

iOS 15.2.1, iOS 15.1, iOS 12.5.5

### CLI Version

7.6.19

**Comment by dnys1** [comment]
Hi @rabi-palmtree - sorry you are facing these issues. A couple questions:

1. Can you share more logs surrounding this error? Specifically, the error in the `catch` block is not in the logs you posted.
2. Can you try awaiting the call to `Amplify.addPlugins`?

**Comment by rabi-palmtree** [comment]
@dnys1  
Thank you for the quick response

we added a bit of additional logging to relevant code

```
  @override
  void initState() {
    loadPrefs();
    print("Main: After loadPrefs");

    NotificationService.instance.start();
    print("Main: After Notification Service Start");

    logger.stream.listen((record) {
      print(
          '[${record.time}] ${Level.getName(record.level)}: ${record.message}');
    });

    gs = GlobalSingleton();
    print("Main: After GlobalSingleton Instantiation");

    super.initState();
    print("Main: After InitState");

    _configureAmplify();
    print("Main: After Configure Amplify");
  }


  Future<void> _configureAmplify() async {
    try {
      AmplifyAuthCognito auth = AmplifyAuthCognito();
      AmplifyStorageS3 storage = AmplifyStorageS3();
      //AmplifyAPI api = AmplifyAPI();
      //Amplify.addPlugins([auth, storage, api]);

      print("Add plugins before");

      await Amplify.addPlugins([auth, storage]);

      print("Configure before");

      if (!Amplify.isConfigured) await Amplify.configure(amplifyconfig);

      print("Configure after");

      setState(() => _isAmplifyConfigured = true);
    } catch (e) {
      print("Amplify Configure issue " + e.toString());
      throw (e);
    }
  }
}

```
Here are the logs  while running on one of the affected iOS devices
(Some irrelevant logging is excluded)

2022-03-04 10:45:47.608214+0530 Runner[1316:327455] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x12dd6b770] get output frames failed, state 8196
2022-03-04 10:45:47.608453+0530 Runner[1316:327455] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x12dd6b770] get output frames failed, state 8196
2022-03-04 10:45:47.609770+0530 Runner[1316:327455] TIC Read Status [1:0x0]: 1:57
2022-03-04 10:45:47.609850+0530 Runner[1316:327455] TIC Read Status [1:0x0]: 1:57
2022-03-04 10:45:47.868848+0530 Runner[1316:327261] flutter: Main: After loadPrefs
2022-03-04 10:45:47.926940+0530 Runner[1316:327261] flutter: Main: After Notification Service Start
2022-03-04 10:45:47.929423+0530 Runner[1316:327261] flutter: Main: After GlobalSingleton Instantiation
2022-03-04 10:45:47.930310+0530 Runner[1316:327261] flutter: Main: After InitState
2022-03-04 10:45:47.935281+0530 Runner[1316:327261] flutter: **Add plugins before**
2022-03-04 10:45:47.974806+0530 Runner[1316:327261] flutter: Main: After Configure Amplify
2022-03-04 10:45:47.998041+0530 Runner[1316:327456] Sentry - debug:: Request status: 200
2022-03-04 10:45:47.998207+0530 Runner[1316:327456] Sentry - debug:: Request response: {}
2022-03-04 10:45:47.998346+0530 Runner[1316:327456] Sentry - debug:: Queued requests: 0
2022-03-04 10:45:47.999653+0530 Runner[1316:327456] Sentry - debug:: Header {"sdk":{"name":"sentry.cocoa","version":"7.9.0"}}
2022-03-04 10:45:47.999873+0530 Runner[1316:327456] Sentry - debug:: Item Header {"type":"session","length":297}
2022-03-04 10:45:47.999992+0530 Runner[1316:327456] Sentry - debug:: Event {"errors" ..... }
2022-03-04 10:45:48.124308+0530 Runner[1316:327241] Sentry - debug:: Request status: 200
2022-03-04 10:45:48.124473+0530 Runner[1316:327241] Sentry - debug:: Request response: {}
2022-03-04 10:45:48.124637+0530 Runner[1316:327241] Sentry - debug:: Queued requests: 0
2022-03-04 10:45:48.330825+0530 Runner[1316:326960] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x280fcae80>
2022-03-04 10:45:48.330884+0530 Runner[1316:327457] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x280fe2c80>
2022-03-04 10:45:48.341294+0530 Runner[1316:327241] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x12de9ce70] get output frames failed, state 8196
2022-03-04 10:45:48.344385+0530 Runner[1316:327241] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x12de9ce70] get output frames failed, state 8196
2022-03-04 10:45:48.345405+0530 Runner[1316:327241] TIC Read Status [3:0x0]: 1:57
2022-03-04 10:45:48.348212+0530 Runner[1316:327241] TIC Read Status [3:0x0]: 1:57
2022-03-04 10:45:48.825522+0530 Runner[1316:327261] flutter: [flutter_i18n INFO]: New locale: en_US
2022-03-04 10:45:48.837544+0530 Runner[1316:327261] flutter: [flutter_i18n INFO]: The current locale is us
...
2022-03-04 10:45:49.381728+0530 Runner[1316:327261] flutter: Configure before
..
2022-03-04 10:45:54.253835+0530 Runner[1316:327237] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x280fbcec0>
2022-03-04 10:45:54.309271+0530 Runner[1316:327456] **[AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 2.)**
2022-03-04 10:45:54.709043+0530 Runner[1316:326960] Sentry - debug:: Header {"event_id":"1bd1a079b1ac4bb89a9989d7ebb605f4","sdk":{"name":"sentry.dart.flutter","version":"6.3.0","packages":[{"name":"pub:sentry","version":"6.3.0"},{"name":"pub:sentry_flutter","version":"6.3.0"},{"name":"cocoapods:sentry-cocoa","version":"7.9.0"}],"integrations":["isolateErrorIntegration","runZonedGuardedIntegration","widgetsFlutterBindingIntegration","flutterErrorIntegration","widgetsBindingIntegration","nativeSdkIntegration","loadContextsIntegration","loadReleaseIntegration","SentryCrashIntegration","SentryFramesTrackingIntegration","SentryAutoBreadcrumbTrackingIntegration","SentryAutoSessionTrackingIntegration","SentryAppStartTrackingIntegration","SentryOutOfMemoryTrackingIntegration","SentryPerformanceTrackingIntegration","SentryNetworkTrackingIntegration","SentryFileIOTrackingIntegration"]}}


To answer your questions:
Can you share more logs surrounding this error? Specifically, the error in the catch block is not in the logs you posted.
It seems to return  from _configureAmplify() after the Amplify.addPlugins call.
However no Exceptions caught in  the catch block.
How did that happen?

Can you try awaiting the call to Amplify.addPlugins?
Thanks for the catch.
We added the await, but it still seems to not proceed to 

Can you let me know which line is causing the error? Is it the addPlugins call or the configure call?
It clearly an issue with the addPlugins call.

**Comment by rabi-palmtree** [comment]
Refactored configuration code for clarity of logging:
```
@override
  void initState() {
    loadPrefs();
    print("Main: After loadPrefs");

    NotificationService.instance.start();
    print("Main: After Notification Service Start");

    logger.stream.listen((record) {
      print(
          '[${record.time}] ${Level.getName(record.level)}: ${record.message}');
    });

    gs = GlobalSingleton();
    print("Main: After GlobalSingleton Instantiation");

    super.initState();
    print("Main: After InitState");

    _configureAmplify();
    print("Main: After Configure Amplify");
  }

  
  Future<void> _configureAmplify() async {
    try {
      AmplifyAuthCognito auth = AmplifyAuthCognito();
      AmplifyStorageS3 storage = AmplifyStorageS3();
      //AmplifyAPI api = AmplifyAPI();
      //Amplify.addPlugins([auth, storage, api]);

      print("Add plugins before");

      await Amplify.addPlugins([auth, storage])
          .then((value) => handleAmplifyConfiguration(value));
    } catch (e) {
      print("Add plugins issue " + e.toString());
      throw (e);
    }
  }

  handleAmplifyConfiguration(void value) async {
    print("Configure amplify before");

    try {
      if (!Amplify.isConfigured)
        await Amplify.configure(amplifyconfig)
            .then((value) => handleAmplifyConfigState(value));

      print("Configure amplify after");
    } catch (e) {
      print("Configure issue " + e.toString());
      throw e;
    }
  }

  handleAmplifyConfigState(void value) {
    print("set state before");

    setState(() => _isAmplifyConfigured = true);

    print("set state after");
  }

```

Now  relevant logs are as follows:

2022-03-04 12:18:47.479891+0530 Runner[1336:341961] flutter: Main: After loadPrefs
2022-03-04 12:18:47.529353+0530 Runner[1336:341961] flutter: Main: After Notification Service Start
2022-03-04 12:18:47.532144+0530 Runner[1336:341961] flutter: Main: After GlobalSingleton Instantiation
2022-03-04 12:18:47.533022+0530 Runner[1336:341961] flutter: Main: After InitState
2022-03-04 12:18:47.537761+0530 Runner[1336:341961] flutter: Add plugins before
2022-03-04 12:18:47.566382+0530 Runner[1336:341961] flutter: Main: After Configure Amplify
2022-03-04 12:18:48.739397+0530 Runner[1336:341961] flutter: token: dqiEojhh90Tdj1Vi5EFkZx:APA91bGzdpV_Z2ZdSlZ_ibONE0YvXrxAcvB8ZrTWf50eBBe3qR7nTXyXWKOK27vnxYDdShLUGpGSB_dPAhlT-WNYNI4J-yswlavMTB9Zr5e1ucBLDzQphtB3hS6LG_dDSaFPcGYlKEt2
2022-03-04 12:18:48.752385+0530 Runner[1336:341961] flutter: Configure amplify before
2022-03-04 12:18:50.515934+0530 Runner[1336:341961] flutter: set state before
2022-03-04 12:18:50.517473+0530 Runner[1336:341961] flutter: set state after
2022-03-04 12:18:50.518038+0530 Runner[1336:341961] flutter: Configure amplify after
2022-03-04 12:18:53.162239+0530 Runner[1336:342110] [AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 2.)

**Comment by rabi-palmtree** [comment]
Same logs on a Device where Amplify configuration went through successfully

I/flutter ( 9375): Main: After loadPrefs
I/flutter ( 9375): Main: After Notification Service Start
I/flutter ( 9375): Main: After GlobalSingleton Instantiation
I/flutter ( 9375): Main: After InitState
I/flutter ( 9375): Add plugins before
I/flutter ( 9375): Main: After Configure Amplify
I/flutter ( 9375): set state before
I/flutter ( 9375): set state after
I/flutter ( 9375): Configure amplify after
D/AWSMobileClient( 9375): Inspecting user state details
D/AWSMobileClient( 9375): hasFederatedToken: true provider: cognito-idp.us-west-2.amazonaws.com/**********
D/AWSMobileClient( 9375): Inspecting user state details
D/AWSMobileClient( 9375): hasFederatedToken: true provider: cognito-idp.us-west-2.amazonaws.com/*********
D/AWSMobileClient( 9375): waitForSignIn: userState:SIGNED_IN
D/AWSMobileClient( 9375): getCredentials: Validated user is signed-in
D/AWSMobileClient( 9375): Inspecting user state details
D/AWSMobileClient( 9375): hasFederatedToken: true provider: cognito-idp.us-west-2.amazonaws.com/******

**Comment by dnys1** [comment]
Hi @rabi-palmtree - what I see is that neither `Add plugins issue` or `Configure issue` is being printed and that both of these calls are completing successfully. Could there be other code called right after this which is triggering the auth error?

**Comment by rabi-palmtree** [comment]
Sorry for the delayed response.

@dnys1 You are right that these calls were being completed successfully.
Our debugging  showed  auto login was going through successfully, 
**but as soon as  user attributes were accessed, the device hung.**

For a workaround now,  on iOS only we are forcing User to login every session, and that works.
(On App start we are forcing Amplify.Auth.signOut(), and User  has to login after that)

With this workaround the App does NOT hang.

**Comment by rabi-palmtree** [comment]
We removed the iOS Workaround for forcing Amplify.Aunth.SignOut, and  tried a varity of  login/auto login scenarios, all of which are  currently working.

One difference is that when we faced this issue, we had  a broken APNS2 push notification feature on iOS and now that has fixed.  

For now you can close this issue, and we will inform you if this come up again.

**Comment by dnys1** [comment]
Hi @rabi-palmtree, thanks for letting me know. Please feel free to re-open if you continue to experience the issue.
