### ISSUE TITLE
@hasMany on Flutter returns relationship null

### ISSUE THREAD

**Issue by willianmascimiano** [aws-amplify/amplify-flutter#1437]
### Description

My comments relationship from post model is returning null.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

When I call postById I get results from the post, but comments not.

![image](https://user-images.githubusercontent.com/19466705/156926349-dad861b0-88c0-4d14-a4ce-8e04c004752b.png)

`  
type Post @model @auth(rules : [
      {allow : owner} , 
      {allow: groups, groups : ["ADMINISTRATOR"]},
      {allow : private, operations : [read]},
      
      ]){
  id: ID!
  communityType: CommunityType!
  title: String!
  status: PostStatus!
  content: String!
  comments: [PostComment] @hasMany

}

type PostComment @model  @auth(rules : [
      {allow : owner} , 
      {allow: groups, groups : ["ADMINISTRATOR"]},
      {allow : private, operations : [read]},
      ]){
    id: ID!,
    content: String!, 
    post: Post @belongsTo
  }`

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.65.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
dependencies:
- advance_pdf_viewer 2.0.0 [flutter flutter_cache_manager numberpicker path_provider]
- amplify_api 0.4.0 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.0 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_authenticator 0.1.0-rc.6 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.0 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- amplify_storage_s3 0.4.0 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_core]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_svg_provider 1.0.3 [flutter http flutter_svg]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- image_picker 0.8.4+9 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.0 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.0 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.0 [flutter meta amplify_core]
- amplify_core 0.4.0 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.0 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.0 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- ffi 1.1.2
- file 6.1.2 [meta path]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.6 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_platform_interface 2.4.4 [cross_file flutter http plugin_platform_interface]
- infinite_listview 1.1.0 [flutter]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- numberpicker 2.1.1 [flutter infinite_listview]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- rxdart 0.27.3
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
```

### Device

IOS Simulator, Moto G9

### OS

NA

### CLI Version

7.6.22

**Comment by willianmascimiano** [comment]
![image](https://user-images.githubusercontent.com/19466705/156926637-c1741638-7135-4b9f-a25e-e2713316632e.png)

**Comment by dnys1** [comment]
Hi @willianmascimiano - can you provide the code you're using to retrieve the post?

**Comment by willianmascimiano** [comment]
> Hi @willianmascimiano - can you provide the code you're using to retrieve the post?

findById method.

`import 'package:agroeti/models/Affiliates.dart';
import 'package:agroeti/models/CommunityType.dart';
import 'package:agroeti/models/ModelProvider.dart';
import 'package:agroeti/models/Post.dart';
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_api/model_mutations.dart';
import 'package:amplify_api/model_queries.dart';
import 'package:amplify_flutter/amplify_flutter.dart';

class PostService {
  Future<Post?> findById(String id) async {
    try {
      final request = ModelQueries.get(Post.classType, id);
      final response = await Amplify.API.query(request: request).response;
      Post? post = response.data;
      if (post == null) {
        print('errors: ' + response.errors.toString());
      }
      print('Query result: ' + post!.id);
      return post;
    } on ApiException catch (e) {
      print('Query failed: $e');
    }
    throw "Erro - PostService";
  }

  Future<List<Post?>?> getAllPosts(
      {required CommunityType communityType}) async {
    final request = ModelQueries.list(
      Post.classType,
      limit: 100,
      where: Post.COMMUNITYTYPE.eq(communityType.name),
    );
    final response = await Amplify.API.query(request: request).response;
    List<Post?>? list = response.data?.items;
    print("AffiliatesService," + list!.length.toString());
    return list;
  }

  Future<String> delete(Post post) async {
    late String log = "";
    final request = ModelMutations.delete(post);
    final response = await Amplify.API.mutate(request: request).response;
    print(response.errors.map((e) => e.message));
    print(response.data?.content);

    if (response.errors.isEmpty) {
      log += "Exluído com sucesso!";
    } else {
      log += response.errors
          .map(
            (e) => e.message,
          )
          .toString();
    }

    return log;
  }

  Future<void> save(Post post) async {
    try {
      final request = ModelMutations.create(post);
      final response = await Amplify.API.mutate(request: request).response;

      Post? createdPost = response.data;
      if (createdPost == null) {
        print('errors: ' + response.errors.toString());
        return;
      }
      print('Mutation result: ' + createdPost.id);

      print('Mutation result: ' + createdPost.communityType.name);
    } on ApiException catch (e) {
      print('Mutation failed: $e');
    }
  }
}
`

**Comment by willianmascimiano** [comment]
> Hey @willianmascimiano this behavior is expected. When calling `ModelQueries.get()` the generated request does not include children, only the parent 1 level up. If you want to query for children in the same request, you will have to create a custom request and include the `modelType` and `decodePath` properties in the request. More information about this type of use case is shown in the example on https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#nested-data. Let me know if you have other questions/issues after having a look at this.

OK, i will check and answer this night.

Thanks.

**Comment by willianmascimiano** [comment]
After check the documentation I've seen just a sample to the Single Nested Data, its correct?

How can I perform a query with my model list type?

Once I've already load the first data I whant in the same communication retrieve all data I need.

Thanks.

**Comment by ragingsquirrel3** [comment]
> After check the documentation I've seen just a sample to the Single Nested Data, just returning one result, instead a List. its correct?
> 
> How can I perform a query with my model list type?
> 
> Once I've already load the first data I whant in the same communication retrieve all data I need.
> 
> Thanks.

I posted some info about that on another thread https://github.com/aws-amplify/amplify-flutter/issues/816#issuecomment-1078480074, and there is some more documentation on paginated results on https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/flutter/#list-items. I hope this helps, going to close this issue as I believe it's working as expected.

**Comment by theartofnonso** [comment]
Still on this issue, apparently, in a scenario were you want to access a bi-directional relationship from child to parent, the api is able to return the connected child.

Say you have the following:

```graphql
type User  {
  id: ID!
  events: [Event] @hasMany
}
```

```graphql
type Event  {
  id: ID!
  user: [Event] @belongsTo
}
```

Amplify flutter **can return the user** when you get an event, however it **fails to return the events** when you query the user.
