### ISSUE TITLE
DataStore - Offline Mode - Sync successful only after Airplane mode, not Wifi or Cellular

### ISSUE THREAD

**Issue by d95sld95** [aws-amplify/amplify-flutter#1440]
### Description

Flutter Amplify DataStore sync's correctly after being offline in Airplane mode. But if you disable WIFI and Cellular and come back online DataStore does not sync data and the data only remains on the original device that was offline. I have tried to stop and start the DataStore, but nothing will make the data sync again. 

Seems to be an issue on any version since 0.3.0 all the way up to 0.4.1 (haven't tried earlier versions). 

Does anyone else have this issue? Any setting that I should know of? 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

In a simple app with a simple data model (see GraphQL below) with an `id` and a `name`. Adding new records when clicking a Button and a counter that is attached to Amplify.DataStore.observe

1) Load application in IOS Simulator
2) Load app in release mode on iPhone 11 (flutter run --release)
3) With iPhone 11 online click floating action button which calls Amplify.DataStore.save(...);
4) See IOS Simulator number increments on screen (same on iPhone 11)
5) Take iPhone 11 offline by disabling `Wifi` and `Cellular` (not `Air Plane Mode`)
6) On iPhone 11 click floating action button and see number increment on device (but not on simulator)
7) Enable Cellular on iPhone 11 and go back to app
8) Expect to see number increment on Simulator, but it does not. 

If enabling Air Plane mode it does work, but Air Plane mode does not simulate environment with bad cellular coverage. 

### Screenshots

![image](https://user-images.githubusercontent.com/725599/157144391-83c2bb0e-011b-45dd-a163-c513d6207e89.png)

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.2
offline 1.0.0+1

dependencies:
- amplify_api 0.3.0 [amplify_api_plugin_interface amplify_core flutter plugin_platform_interface]
- amplify_datastore 0.3.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.3.0 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]

transitive dependencies:
- amplify_analytics_plugin_interface 0.3.0 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.3.0 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.3.0 [flutter meta amplify_core]
- amplify_core 0.3.0 [flutter meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.3.0 [flutter meta collection date_time_format uuid amplify_core]
- amplify_storage_plugin_interface 0.3.0 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
```

### Device

iPhone 11 Pro

### OS

iOS 15.3.1

### CLI Version

7.6.22

### GraphQL:
```
type Install @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
}
```
### Dart
```
import 'dart:async';

import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:offline/models/ModelProvider.dart';

// Generated in previous step
import 'amplifyconfiguration.dart';

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  bool _isLoading = true;
  int _counter = 0; // Number inserted documents

  /// Init State
  @override
  initState() {
    super.initState();
    _configureAmplify();
  }

  /// Configure Amplify
  Future<void> _configureAmplify() async {
    try {
      // amplify plugins
      final AmplifyDataStore _dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);

      // add Amplify plugins
      await Amplify.addPlugins([_dataStorePlugin, AmplifyAPI()]);

      // configure Amplify
      await Amplify.configure(amplifyconfig);

      setState(() {
        _isLoading = false;
      });
    } on AmplifyAlreadyConfiguredException {
      // error handling can be improved for sure!
      // but this will be sufficient for the purposes of this tutorial
      print("Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }

    // Listen to DataStore changes
    Stream<QuerySnapshot<Install>> stream = Amplify.DataStore.observeQuery(Install.classType);
    stream.listen((QuerySnapshot<Install> snapshot) {
      setState(() {
        _counter = snapshot.items.length;
      });
    });

    // Set current count (at startup)
    int length = (await Amplify.DataStore.query(Install.classType)).length;

    setState(() {
      _counter = length;
    });
  }
  
  void _incrementCounter() async {
    Install install = Install(name: 'Install $_counter');
    await Amplify.DataStore.save(install);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Offline'),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                  Text(
                    '$_counter',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ],
              ),
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by HuiSF** [comment]
Hi @d95sld95 Thanks for the detailed reproducing steps.

>I have tried to stop and start the DataStore

Did you do this after the 7th step?

>but nothing will make the data sync again

The new record created in iPhone 11 when the device is disconnected, never been synced to DynamoDB table?

**Comment by d95sld95** [comment]
@Jordan-Nelson 

> Did you do this after the 7th step?

Yes, I basically added a Stop and Start button (Amplify.Datastore.start() / Amplify.Datastore.stop()

> The new record created in iPhone 11 when the device is disconnected, never been synced to DynamoDB table?

No, I also check to see if the data made it to DynamoDB.

**Comment by d95sld95** [comment]
@Jordan-Nelson 

Another development, in our Prod environment, with a much more advanced application we now have it sync'ing using 0.3.0.

But, it always skips the first item created offline (like it skips index 0 in the queue). 

**Steps:**

Offline (1): Add item 1, 2, 3
Online (1): Item 2 and 3 sync's, but NOT 1
Offline (2): Add item 4, 5, 6
Online (2): Item 1, 5, 6 sync, but NOT 4 and notice 1 suddenly sync'ed

**Comment by Jordan-Nelson** [comment]
I'm having a hard time finding the root cause as I cannot reproduce this on a simulator and the debugging session on a physical device will disconnect when wifi is disconnected. I have been able to reproduce this though, so I am going to mark it as a bug.

As a next step, we could look into reproducing this in a native iOS app using amplify-iOS to see if this is an issue with Amplify-iOS.

**Comment by HuiSF** [comment]
Hi @d95sld95 sorry for the delayed follow up.

I did some testing following your steps, here are my observations:

**Scenario 1**
* Condition
  - Run App with DataStore when the device was online
  - Then turn off next work
  - Save 3 models say Todo1, Todo2 and Todo3
* Observation
  - DataStore saved all 3 models into local DB
  - DataStore pushed all 3 models into mutationOutBox
  - DataStore invoked sync engine attempting sync saved model into cloud
  - The first underlying GraphQL mutation for Todo1 failed due to no network connection
  - Sync engine thought this is an unrecoverable issue (need to confirm this with amplify-ios), hence it removed mutationOutBox event for Todo1
  - Turn on network again, DataStore resumed API sync automatically
  - Todo 2 and Todo 3 mutationOutBox events were processed and these two models synced to cloud
  - Restart App with network on, Todo 1 remained in local DB but no sync happened to it **(bug 1)**

**Scenario 2**
* Condition
  - Turn of network
  - Run App with network turned off
  - Save 3 models say Todo1, Todo2 and Todo3
* Observation
  - DataStore saved all 3 models into local DB
  - DataStore pushed all 3 models into mutationOutBox
  - There was no sign that sync engine was invoked to process mutationOutBox events
  - Turn on network
  - Invoking `Amplify.DataStore.start` invoked amplify-ios `DataStore.start` API, but [this logic](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift#L141-L144) actually prevented restarting of the sync engine **(bug 2)**

These two bugs caused the issue. I'll reach out to amplify-ios maintainers for next steps.

**Comment by d95sld95** [comment]
Seems like it is fixed in the IOS-SDK. When is it expected to be release for Flutter?
