### ISSUE TITLE
Feature Request: Handling different environments/multiple user-pools

### ISSUE THREAD

**Issue by deimantasa** [aws-amplify/amplify-flutter#145]
Hello guys, I'm trying out AWS Amplify at the moment and I've stumbled around issue, that I couldn't see how could one handle different environments or multiple user-pools.

Currently, we have `amplifyconfiguration.dart` autogenerated and for initialisation we use `await amplify.configure(amplifyconfig);` . `amplifyconfig` is the constant `String` in `amplifyconfiguration.dart`.

However, what if one has 2 or more different environments. In simplest scenario - **development** and **production**? Or multiple user-pools? Is it currently possible? Or is it in the roadmap?

Thank you

**Comment by haverchuck** [comment]
@deimantasa We don't currently support multiple user pools within a single environment, but the amplify-cli can help you manage multiple environments.  It should automatically update the amplifyconfiguration.dart file when you switch environments.

See the docs here: https://docs.amplify.aws/cli/teams/overview

**Comment by deimantasa** [comment]
> @deimantasa We don't currently support multiple user pools within a single environment, but the amplify-cli can help you manage multiple environments. It should automatically update the amplifyconfiguration.dart file when you switch environments.
> 
> See the docs here: https://docs.amplify.aws/cli/teams/overview

Thank you for your response.

If I understood correctly, it's possible to switch environments, but it's possible to do only via `amplify` itself? There is no way to switch Environment via runtime in Flutter?  Therefore there is only one config available at all times?

Simple use-case in Flutter by using Flavours or other configurations to run build environment in the app - https://medium.com/@matt.goodson.business/separating-build-environment-configurations-in-flutter-with-firebase-doing-it-the-right-way-c72c3ad3621f . If I understand correctly, with current `amplify` this scenario is hard to achieve because we have to checkout right environment first and then run specific Flavour? Is there official guide for this case?

**Comment by flodaniel** [comment]
Hey @deimantasa,
did you ever figure out if this is possible somehow?

**Comment by deimantasa** [comment]
Hi @flodaniel - If I remember correctly, we've decided to move away from this package as we couldn't figure the solution in a short run.

Apologies for possibly unexpected answer :)

Cheers
