### ISSUE TITLE
'ModelSchemaDefinition.addField' function doesn't add fields generated by 'ModelFieldDefinition.hasMany'

### ISSUE THREAD

**Issue by ThewyRogue99** [aws-amplify/amplify-flutter#1457]
### Description

Schema:

```
type Controller @model(mutations: null, subscriptions: null)
  @auth(rules: [
    { allow: owner, ownerField: "deviceOwner", operations: [read] }
  ]) {
  id: ID!
  deviceName: String!
  deviceMAC: String!
  deviceOwner: ID!
  deviceState: DeviceState!
  vehicles: [Vehicle!]! @connection(keyName: "ownerController", fields: ["id"])
}

type Vehicle @model(mutations: null, subscriptions: null)
  @key(name: "ownerController", fields: ["controllerId"])
  @auth(rules: [
    { allow: owner, ownerField: "deviceOwner", operations: [read] }
  ]) {
  id: ID!
  deviceName: String!
  deviceMAC: String!
  deviceOwner: ID!
  controllerId: ID!
  deviceState: DeviceState!
}
```

In this schema i have multiple Vehicles connected to a Controller model. I use `amplify codegen models --maxDepth 5` command to generate models.

Inside Controller class:

```
static final QueryField VEHICLES = QueryField(
      fieldName: "vehicles",
      fieldType: ModelFieldType(ModelFieldTypeEnum.model,
          ofModelName: (Vehicle).toString()));

static var schema = Model.defineSchema(define: (ModelSchemaDefinition modelSchemaDefinition) {
    // Rest of the code...
  
    modelSchemaDefinition.addField(ModelFieldDefinition.hasMany(
            key: Controller.VEHICLES,
            isRequired: true,
            ofModelName: (VEHICLE).toString(),
            associatedKey: Vehicle.CONTROLLERID));
  }
);
```
'vehicles' field is added as shown above in Controller class but when i try to create a list query with `ModelQueries.list(Controller.classType)` created document doesn't have 'vehicles' field added to it.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1586], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (2 available)

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.15.1
Flutter SDK 2.8.1
controller_app 1.0.0+1

dependencies:
- amplify_api 0.4.1 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.1 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_flutter 0.4.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- provider 6.0.2 [collection flutter nested]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.1 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.1 [flutter meta amplify_core]
- amplify_core 0.4.1 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.1 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.1 [flutter meta amplify_core]
- characters 1.2.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- json_annotation 4.4.0 [meta]
- meta 1.7.0
- nested 1.0.0 [flutter]
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
```

### Device

N/A

### OS

N/A

### CLI Version

7.6.23

**Comment by fjnoyp** [comment]
Hi @ThewyRogue99 thanks for reaching out to us. 

Can you clarify what you said: 

> but when i try to create a list query with ModelQueries.list(Controller.classType) created document doesn't have 'vehicles' field added to it.

So when you run: 

```
final req = ModelQueries.list<Controller>(Controller.classType);
final res = await Amplify.API.query(request: req).response;

```

What is the contents of the res object?

**Comment by ThewyRogue99** [comment]
I can clarify it with an example:
```
final request = ModelQueries.list<Controller>(Controller.classType);
print(request.document);
```
Output:
```
query listControllers() {
  listControllers() {
    items {
        id
        deviceName
        deviceMAC
        deviceOwner
        deviceState
        createdAt
        updatedAt
    }
    nextToken
  }
}
```
As you can see above, `request.document` doesn't contain the field 'vehicles' so when i request data from graphql api, the res object that you asked for its contents contains a Controller object (No errors too) but its 'vehicles' field is set to null so if i try to access it i get `AmplifyCodeGenModelException`.

This is the output that i want:
```
query listControllers() {
  listControllers() {
    items {
        id
        deviceName
        deviceMAC
        deviceOwner
        deviceState
        createdAt
        updatedAt
        vehicles {
            items {
                id
                deviceName
                deviceMAC
                deviceOwner
                deviceState
                createdAt
                updatedAt
            }
        }
    }
  }
}
```
If the output was like above, graphql api would have returned a Controller object with vehicles in it. I also tried this query from AWS Console and it returned the data that i just wanted.

> What is the contents of the res object?

Here are the contents that i got by using `print(res.data!.items.toString());`:

`[Controller {id=8fecf579-dc12-40e2-b349-28693a3f41f6, deviceName=My Test Controller, deviceMAC=11:22:33:44:55:66, deviceOwner=9d8b8e7d-9dc7-4251-9839-98b67040d2d3, deviceState=ONLINE, createdAt=2022-03-10T20:44:37.000000000Z, updatedAt=2022-03-10T20:44:37.000000000Z}]`

**Comment by fjnoyp** [comment]
Hi @ThewyRogue99 at the moment ModelQuery helper does not load nested data (vehicles within controller in this case) 

You can instead create the graphql request as a string and pass it to our API like in the example here: 

https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#nested-data

**Comment by fjnoyp** [comment]
Unfortunately for list requests, you'll need to manually decode the response from JSON at the moment.  
There is a fix for this that will be included in our next release:  https://github.com/aws-amplify/amplify-flutter/pull/1420

**Comment by ThewyRogue99** [comment]
@fjnoyp Thank you for your response, i will pass my own query and decode it for now. I hope it gets fixed in the next release.

**Comment by fjnoyp** [comment]
Thanks for your understanding.  I will update this issue once we release with that fix.

**Comment by fjnoyp** [comment]
Hi @ThewyRogue99 we made a new release `0.4.2` which contains this fix.
