### ISSUE TITLE
Ios Amplify.Storage.getUrl Get a presigned URL of a stored file

### ISSUE THREAD

**Issue by may215** [aws-amplify/amplify-flutter#1458]
### Discussed in https://github.com/aws-amplify/amplify-flutter/discussions/1447

<div type='discussions-op-text'>

<sup>Originally posted by **may215** March  9, 2022</sup>
Hi,
Do you have support presigned URL on ios? On the docs I only see it for javascript. 
If so, can you please elaborate? 

Thanks</div>

**Comment by HuiSF** [comment]
Hi @may215 sorry missed your question in the Discussions. 
I believe `getUrl` API returns presigned URL of a s3 object. Details please see the discussion in this thread https://github.com/aws-amplify/amplify-flutter/issues/983. 

I'm closing this issue, and will follow up in your [Discussion thread](https://github.com/aws-amplify/amplify-flutter/discussions/1447) if you have further questions. Thanks!
