### ISSUE TITLE
Feature Request: Possible to run cognito without configuring it via amplify

### ISSUE THREAD

**Issue by deimantasa** [aws-amplify/amplify-flutter#146]
Currently, Amplify has quite some limitations. For example: There is no way to allow users to sign-in via main option and toggle additional options if project is initialised via amplify CLI.
Example `Username + 
Also allow sign in with verified email address + 
Also allow sign in with verified phone number`.
![image](https://user-images.githubusercontent.com/12739071/95531104-ec472100-0a09-11eb-970b-0cfbdb8a8e0f.png)

I've found, that similar issue is opened since **2019 May** and it's not fixed yet. https://github.com/aws-amplify/amplify-cli/issues/1546 This is a huge problem and currently, Flutter is limited to cognito set-up made solely from amplify CLI.

Until this issue is not fixed or it's not possible to run cognito without setting up via CLI - I'd expect much less popularity for this plugin, as this is one of the core functionalities of `cognito`.

Would love to hear any follow-up on this.

**Comment by Rayv1** [comment]
Yes it is possible to run cognito without configuring it via Amplify. Just create it in your own Way and integrate it.
https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter

**Comment by deimantasa** [comment]
Hello Ray,
Thank you for your response.

Could you provide step-by-step guidance for that? I've tried running it without amplify - however it started to complain, that project is not setup in amplify. Would love to explore this possibility.

**Comment by haverchuck** [comment]
Hi @deimantasa - This is covered in our documentation [here](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter).

**Comment by haverchuck** [comment]
@deimantasa 
> Could you provide step-by-step guidance for that? I've tried running it without amplify - however it started to complain, that project is not setup in amplify. 

What exactly do you mean by "running it without amplify"?  A little more detail would be helpful for troubleshooting your use case.

**Comment by deimantasa** [comment]
> @deimantasa
> 
> > Could you provide step-by-step guidance for that? I've tried running it without amplify - however it started to complain, that project is not setup in amplify.
> 
> What exactly do you mean by "running it without amplify"? A little more detail would be helpful for troubleshooting your use case.

Thank you for chipping in, @haverchuck !

Current case - we're using Cognito for quite a while with Flutter and we're doing it on Flutter via https://pub.dev/packages/amazon_cognito_identity_dart_2 plugin. We can directly set-up Cognito in AWS without any Amplify interference.

What I'm asking is - to be able to use it with official `AWS` support in Flutter. Currently it's only possible via `amplify`. Therefore maybe there would be a way to import currently set-up `Cognito` to `Amplify`?

I'm raising this solely, because currently, `amplify` seems to have quite some limitations, while setting up whole `auth` part. And there seems to be no way of going around these issues but wait for fix ([which is pending for 1.5years already](https://github.com/aws-amplify/amplify-cli/issues/1546)).
