### ISSUE TITLE
How can I avoid app open with option?

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1461]
I have two application with same cognito user pool. For example App A is for client and App B is for users. Both have installed on device. So when am trying to login it's showing open with options like the following;
<img width="321" alt="Screenshot 2022-03-15 at 3 48 59 PM" src="https://user-images.githubusercontent.com/27992382/158700079-45e4c0f0-2624-4524-ad5c-13d8d277e120.png">

1. How can I avoid this? 
2.  And when am trying to do login it's going to chrome(web). How can I avoid that too? Is it happening because of signout api idk. Before calling sign in api am calling this signout api.

**Comment by fjnoyp** [comment]
Hi @Sunsiha can you clarify what you are doing to login - so you're saying by running await `Amplify.Auth.signIn(` you get this "open with" options popup? 

Can you share the code for your question 2?  Why are you calling sign out before calling sign in?  For first sign in is this an issue still?

**Comment by Sunsiha** [comment]
@fjnoyp If i installed both app in my ph means i will get open with. 

If i don't logout before signin sometimes it is showing the following error

```
FlutterInvalidStateException{message=There is already a user signed in., cause=java.lang.Exception: invalidState, recoverySuggestion=Sign out before calling sign in.}
```

**Comment by fjnoyp** [comment]
Hi can you clarify what you were doing before in the UI to get the open
with?

If you get that error a user might be logged in still.  When you get that
error what do you get when you print get current Auth user?

**Comment by Sunsiha** [comment]
@fjnoyp Hi can you clarify what you were doing before in the UI to get the open
with? I didn't get this point.

**Comment by julius-stuemmler** [comment]
> @fjnoyp If i installed both app in my ph means i will get open with.
> 
> If i don't logout before signin sometimes it is showing the following error
> 
> ```
> FlutterInvalidStateException{message=There is already a user signed in., cause=java.lang.Exception: invalidState, recoverySuggestion=Sign out before calling sign in.}
> ```

The error message overall can be fixed with checking `(await Amplify.Auth.fetchAuthSession()).isSignedIn`. If you check this condition before trying to sign in, you can handle if the user is still logged in or not. If he is signedIn, you can fetch the user (`await Amplify.Auth.getCurrentUser();`). Otherwise you can try to signin the user again.

Unfortunately for your other problem I cannot help you.

**Comment by fjnoyp** [comment]
Thank you @julius-struemmler for your solution to the error message.  @sunsiha does his solution fix your issue?

Regarding the open with window, what are you doing on your phone (what buttons are you clicking on which app do you have open etc) to get that screen you mentioned: 

![image](https://user-images.githubusercontent.com/11478656/159376883-1d9a07c1-2be2-4e6b-b7eb-63061b769d70.png)

**Comment by Sunsiha** [comment]
> Thank you @julius-struemmler for your solution to the error message. @Sunsiha does his solution fix your issue?
> 
> Regarding the open with window, what are you doing on your phone (what buttons are you clicking on which app do you have open etc) to get that screen you mentioned:
> 
> ![image](https://user-images.githubusercontent.com/11478656/159376883-1d9a07c1-2be2-4e6b-b7eb-63061b769d70.png)

I need to try this solution. Will let you know.
Regarding the open with window, This is happening only in Android.  When I click on signin in button am getting this. I have two apps with same cognito aws configuration. But both is using for different purpose. If I installed both the application in my device am getting such kind of window. Like after hitting the signin in api. 


Is it is happening because of the following code?

```
        <activity
            android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="myapp" />
            </intent-filter>
        </activity>
```

**Comment by Jordan-Nelson** [comment]
@Sunsiha - Do both apps have `android:scheme` set to `myapp`? You will want to make this something unique to each app. If both apps are using the same value I believe what you are describing would be expected.

**Comment by Sunsiha** [comment]
> @Sunsiha - Do both apps have `android:scheme` set to `myapp`? You will want to make this something unique to each app. If both apps are using the same value I believe what you are describing would be expected.

@Jordan-Nelson I have sorted like this. Forgot to update here. This worked! Thanks.
