### ISSUE TITLE
Unable to sync gradle project

### ISSUE THREAD

**Issue by nguyenthangngoc** [aws-amplify/amplify-flutter#1466]
### Description

I tried to sync gradle project but it show error like below:
```
The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Affected Modules: <a href="openFile:C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/[amplify_analytics_pinpoint](openfile:C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/amplify_analytics_pinpoint-0.4.1/android/build.gradle)-0.4.1/android/build.gradle">amplify_analytics_pinpoint</a>
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android

### Environment

```bash
None
```

### Dependencies

```bash
amplify_analytics_pinpoint: ^0.4.1
```

### Device

Android Studio

### OS

Windows 10

### CLI Version

7.6.21

**Comment by cshfang** [comment]
Hi @nguyenthangngoc, thanks for reporting this and sharing some initial context. When running `flutter doctor` at the command prompt, are there any reported issues?

It appears that you are running into this fairly early on in your workflow but it would be helpful to know exactly what steps are leading to it. Could you please share some minimal reproduction steps for this issue if possible?

**Comment by Jordan-Nelson** [comment]
@nguyenthangngoc If you are still experiencing this issue can you please provide the info requested above? Thanks.

**Comment by Jordan-Nelson** [comment]
@nguyenthangngoc - I am going to close this out since I have not heard back. Please open a new issue with the info requested above if you are still experiencing this.
