### ISSUE TITLE
Auth Get Device Details API

### ISSUE THREAD

**Issue by mithunkavullakandiyil** [aws-amplify/amplify-flutter#1472]
Currently, in Amplify Auth Library, three APIs available which are related to devices. ((void)rememberDevice, (void)forgetDevice and (list)fetchDevices).
There is no way to identify the current device from the devices list returned by fetchDevices API method.

Need a API to get the current device.

**Comment by abdallahshaban557** [comment]
Hi @mithunkavullakandiyil  - thank you for submitting this feature request! Can you please elaborate a bit more on this use case?

**Comment by mithunkavullakandiyil** [comment]
For our app users, we would like to limit the number of devices they have signed in. The users can manage their devices (Basically, remove devices) so that another device can be added to the list.

This is to limit the number of devices which can be used with a single user account.

**Comment by abdallahshaban557** [comment]
Hi @samuelcastro @mithunkavullakandiyil , we have captured this request in our backlog. Thank you for the feedback!

**Comment by dtodt** [comment]
I'm facing a different use case.
In my app, the user cannot have concurrent signed-in devices, so if he sign's in on another device, I must ask him to confirm then sign-out/forget the other device.

Are there any plans to bring this feature to the flutter version?

Thanks.

**Comment by Jordan-Nelson** [comment]
> No way to identify the current device to allow users to remove it.

@samuelcastro - Do you mind expanding on this a bit? The `forgetDevice()` API would allow you to remove the current device. Would you be able to elaborate on the experience you would like to achieve?

**Comment by Jordan-Nelson** [comment]
>  In my app, the user cannot have concurrent signed-in devices, so if he sign's in on another device, I must ask him to confirm then sign-out/forget the other device.

@dtodt - Would you be able to share how you plan to use the current device info to achieve this? Would you plan to do something like the following?
- Log user in
- Fetch known devices
- Compare list of known devices to current device
- If any known devices exist that are not the current device, display a message to the user and log them out

**Comment by Jordan-Nelson** [comment]
> For our app users, we would like to limit the number of devices they have signed in. The users can manage their devices (Basically, remove devices) so that another device can be added to the list.
> 
> This is to limit the number of devices which can be used with a single user account.

This sounds similar to @dtodt's request, although I am not sure if you also intend for there to be a hard limit of 1 device logged in. Do you mind elaborating on the experience you are hoping to achieve and how you would like to use this API?

**Comment by dtodt** [comment]
Banking like apps, @Jordan-Nelson.

**Comment by lucashfreitas** [comment]
Can't you extract it from the accessToken payload? see this issue #13244
