### ISSUE TITLE
Cannot get Cognito User Pool Tokens

### ISSUE THREAD

**Issue by fpabl0** [aws-amplify/amplify-flutter#148]
**Describe the bug**
My project only uses Cognito User Pools, no IdentityPools, and I want to get cognito user pool tokens using:
```
await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
);
```
But got error: 
`{localizedErrorMessage: Could not fetch identity Id, AWS Cognito Identity Pool is not configured, recoverySuggestion: Follow the steps to configure AWS Cognito Identity Pool and try again, platform: iOS}
`

**To Reproduce**
1. Run this function:
  ```
Future<void> signIn(String email, String password) async {
    try {
      await Amplify.Auth.signIn(username: email, password: password);
      final resp = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
      if (resp.isSignedIn) {
        final sess = resp as CognitoAuthSession;
        print(sess.userPoolTokens.accessToken);
      }
    } on AuthError catch (e) {
      print(e.cause);
      for (final exception in e.exceptionList) {
        print(exception.exception);
        print(exception.detail);
      }
    }
  }
```
**Expected behavior**
Get the cognito user pool tokens without provide an Identity Pool (because I don't need it)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS (iOS Simulator)

**Comment by horgag** [comment]
try casting with `CognitoAuthSession`. ..

`CognitoAuthSession  res = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));`

**Comment by fpabl0** [comment]
> **Describe the bug**
> My project only uses Cognito User Pools, no IdentityPools, and I want to get cognito user pool tokens using:
> 
> ```
> await Amplify.Auth.fetchAuthSession(
>         options: CognitoSessionOptions(getAWSCredentials: true),
> );
> ```
> 
> But got error:
> `{localizedErrorMessage: Could not fetch identity Id, AWS Cognito Identity Pool is not configured, recoverySuggestion: Follow the steps to configure AWS Cognito Identity Pool and try again, platform: iOS} `
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run this function:
> 
> ```
> Future<void> signIn(String email, String password) async {
>   try {
>     await Amplify.Auth.signIn(username: email, password: password);
>     final resp = await Amplify.Auth.fetchAuthSession(
>       options: CognitoSessionOptions(getAWSCredentials: true),
>     );
>     if (resp.isSignedIn) {
>       final sess = resp as CognitoAuthSession;
>       print(sess.userPoolTokens.accessToken);
>     }
>   } on AuthError catch (e) {
>     print(e.cause);
>     for (final exception in e.exceptionList) {
>       print(exception.exception);
>       print(exception.detail);
>     }
>   }
> }
> ```
> 
> **Expected behavior**
> Get the cognito user pool tokens.
> 
> **Platform**
> Amplify Flutter current supports iOS and Android. This issue is reproducible in (check all that apply):
> [] Android
> [x] iOS (iOS Simulator)



> try casting with `CognitoAuthSession`. ..
> 
> `CognitoAuthSession res = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));`

Hi, thanks, but that is not solution the function:
`Amplify.Auth.fetchAuthSession`
Throws always this error:
`{localizedErrorMessage: Could not fetch identity Id, AWS Cognito Identity Pool is not configured, recoverySuggestion: Follow the steps to configure AWS Cognito Identity Pool and try again, platform: iOS}`

**Comment by haverchuck** [comment]
@fpabl0 @horgag  Thank you - this appears to be a bug.  We will try to prioritize a fix.  Please stay tuned.

**Comment by bcrisostomo** [comment]
@haverchuck Also need this for Third Party Social Sign in. Having the same issue, is there an update on this?

**Comment by fpabl0** [comment]
@haverchuck any updates on this issue?

**Comment by SailorMobile** [comment]
What is the current status with this bug...?

**Comment by haverchuck** [comment]
@SailorMobile @fpabl0 @bcrisostomo We are opening a PR to address this.

**Comment by haverchuck** [comment]
@SailorMobile @fpabl0 @bcrisostomo  - We have included a fix for this in [our most recent release](https://pub.dev/packages/amplify_auth_cognito).

@bcrisostomo As you can see from [this PR](https://github.com/aws-amplify/amplify-flutter/pull/154), we are actively working on OAuth flows (social sign-in) with Cognito Hosted UI.  It may be some time before this PR is merged and release.

**Comment by fpabl0** [comment]
I have just tested. It works great, thanks. I think you must update the documentation as I have realized that now the library needs minSdkVersion 21 for android.

**Comment by jamesonwilliams** [comment]
> I have just tested. It works great, thanks. I think you must update the documentation as I have realized that now the library needs minSdkVersion 21 for android.

@fpabl0 Did you find some documentation that indicates otherwise? Can you please include a link? Will update. Thanks!

**Comment by fpabl0** [comment]
> > I have just tested. It works great, thanks. I think you must update the documentation as I have realized that now the library needs minSdkVersion 21 for android.
> 
> @fpabl0 Did you find some documentation that indicates otherwise? Can you please include a link? Will update. Thanks!

@jamesonwilliams Not in fact, unless I have not read carefully, in the documentation there is nothing about this requirement in Android (documentation only says iOS development target must be 11, but nothing about Android sdk version). However before the current release, I could build a project with sdkVersion 16, but now I can't, because now the libraries have the minSdkVersion set to 21.

**Comment by jamesonwilliams** [comment]
@fpabl0 Gotcha. This requirement was recently added in our public docs, [here](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter#prerequisites). Formerly, I think the API level was undocumented as you say, and there was no public contract around it.

**Comment by fpabl0** [comment]
@jamesonwilliams I see. However I think, it must be clearer if [here](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/flutter) says it too and also [here](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter).

**Comment by jamesonwilliams** [comment]
> @jamesonwilliams I see. However I think, it must be clearer if [here](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/flutter) says it too and also [here](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter).

Cool, thanks. Will update.

**Comment by fpabl0** [comment]
> Cool, thanks. Will update.

Thanks  👍

**Comment by haverchuck** [comment]
@fpabl0 We have [a PR open](https://github.com/aws-amplify/docs/pull/2752) to fix the issue in the Project Setup section. I am going to close this issue since it appears the fix for the original problem is working for you.  Thanks for posting this.

**Comment by Alexminator99** [comment]
`CognitoAuthSession res = await (Amplify.Auth.fetchAuthSession(
            options: CognitoSessionOptions(getAWSCredentials: true)) as FutureOr<CognitoAuthSession>);`

I updated to null safety version and now that is broken.

Error:

`Unhandled Exception: type 'Future<AuthSession>' is not a subtype of type 'FutureOr<CognitoAuthSession>' in type cast`

**Comment by albertms10** [comment]
> `CognitoAuthSession res = await (Amplify.Auth.fetchAuthSession( options: CognitoSessionOptions(getAWSCredentials: true)) as FutureOr<CognitoAuthSession>);`
> 
> I updated to null safety version and now that is broken.
> 
> Error:
> 
> `Unhandled Exception: type 'Future<AuthSession>' is not a subtype of type 'FutureOr<CognitoAuthSession>' in type cast`
> 
> Can this issue be reopened??

`Amplify.Auth.fetchAuthSession` returns a `Future<AuthSession>`. Instead of trying to cast its value as `FutureOr<CognitoAuthSession>`, you could leave it as follows to let Dart infer its type automatically:
```dart
final res = await Amplify.Auth.fetchAuthSession(
  options: CognitoSessionOptions(getAWSCredentials: true),
);
```

**Comment by sabindeerhold** [comment]
`final res = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      ) as CognitoAuthSession;`
      
 ` AuthSession res = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );`
can anyone please help mke on this i want to get user pool token for authorization but while doing this i only get this 
`Instance of 'CognitoAuthSession'` as a response.
