### ISSUE TITLE
Generated model doesn't allow setting null value with copyWith constructor

### ISSUE THREAD

**Issue by guplem** [aws-amplify/amplify-flutter#1480]
### Description

I have optional fields in my Amplify's tables.

They start as null. And I can set a value using my Android app.

However, I cannot update/remove that value to become null again after it has been set to a non-null value.
Instead, it simply won't change.

This is pretty annoying... and broke some of my design...

You can see what, I think, is the same issue in Amplify's Android SDK: [https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/194](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/194 )

### Categories
(I am not sure but I think...)
- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.3
time_manager 1.0.0+1

dependencies:
- amplify_api 0.4.2 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.2 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.2 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.2 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotatio
n meta plugin_platform_interface]
- cupertino_icons 1.0.4
- duration_picker 1.1.0+1 [flutter_lints flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- restart_app 1.1.0 [flutter flutter_web_plugins]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.2 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.2 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.2 [flutter]
- amplify_auth_cognito_ios 0.4.2 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.2 [flutter meta amplify_core]
- amplify_core 0.4.2 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.2 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.2 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- flutter_lints 1.0.4 [lints]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
```

### Device

OnePlus Nord 2

### OS

Android 11 (Oxygen 11.3)

### CLI Version

7.6.22

**Comment by HuiSF** [comment]
Hey @guplem thanks for reporting this issue. 
Can you share the model schema that contains the nullable/optional field you mentioned?

**Comment by HuiSF** [comment]
Hi @guplem thanks for providing the info. I built a minimal App in Android platform to replicate similar situation using below schema

```graphql
type Todo @model {
  id: ID!
  name: String!
  seField: String.    # optional field
  description: String # optional field
}
```

Dart code
```dart
var todo = Todo(name: 'a name');
await Amplify.DataStore.save(todo);

await Future.delayed(const Duration(seconds: 2));

// update the description field to non-null value
var updatedTodo = todo.copyWith(
  name: 'updated a name',
  description: 'some description',
);
await Amplify.DataStore.save(updatedTodo);

await Future.delayed(const Duration(seconds: 2));

// reset the description field to null
var updatedTodo2 = todo.copyWith(
  name: 'updated a name',
  description: null,
);
await Amplify.DataStore.save(updatedTodo2);
```

After execution, the final update that resetting `description` to `null` was working as expected. 

The underlying GraphQL network request and response looked correct as well.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/10602282/160487229-1d625960-7c94-4a5f-a8c5-05e720ff18f5.png">

Therefore I don't think there is an issue here...

Next steps:
* When you update the model, did you explicitly assign `null` to the field like what shown in above example?
* When you update the model, did you also change the fields with `AWSDateTime` or `AWSTime`? These fields require their value to be valid other wise AppSync may reject

**Comment by guplem** [comment]
Okay, I did some further testing. I do not understand why it works for you but not for me.

I managed to reset a String to "null".

First, I tried this (didn't work):

`  Future<void> _saveSettings() async {
    if (userData == null) {
      return;
    }

    String username = _usernameController.text;

    try {
      UserData newUserData = userData!.copyWith(username: username.isNotEmpty ? username : null);
      await Amplify.DataStore.save(newUserData);
      print("Username isNotEmpty? ${ username.isNotEmpty}. newUserData username = '${newUserData.username}'");
      print("UserData saved: '${newUserData}'");
    } catch (e) {
      Debug.logError('An error occurred while saving UserData: $e');
    }
  }`

But when the username was set to null for the "newUserData", the field wouldn't update. This is what was printed:
Username isNotEmpty? false. newUserData username = 'oldUsername'
UserData saved: 'UserData {id=bae78c73-e41a-4117-b5c7-cf29e61a5ec8, user=83f4d5f5-2528-4644-9d9b-44bce3d5608f, selectedTaskId=, selectedTaskOngoing=false, maxSessionDuration=00:05:00, sessionStart=2022-03-29T09:38:40.541107000Z, username=oldUsername, createdAt=null, updatedAt=null}'

So, setting the field to null and saving it won't work for me... I don't know why it works for you.

However, changing slightly the code and forcing it to an empty string ("") instead of null, did the trick **for strings only**.

This is the new code:
`  Future<void> _saveSettings() async {
    if (userData == null) {
      return;
    }

    String username = _usernameController.text;

    try {
      UserData newUserData = userData!.copyWith(username: username.isNotEmpty ? username : **""**);
      await Amplify.DataStore.save(newUserData);
      print("Username isNotEmpty? ${ username.isNotEmpty}. newUserData username = '${newUserData.username}'");
      print("UserData saved: '${newUserData}'");
    } catch (e) {
      Debug.logError('An error occurred while saving UserData: $e');
    }
  }`

This is what is printed:
Username isNotEmpty? false. newUserData username = ''
UserData saved: 'UserData {id=bae78c73-e41a-4117-b5c7-cf29e61a5ec8, user=83f4d5f5-2528-4644-9d9b-44bce3d5608f, selectedTaskId=, selectedTaskOngoing=false, maxSessionDuration=00:05:00, sessionStart=2022-03-29T09:38:40.541107000Z, username=, createdAt=null, updatedAt=null}'

The database (AWS/Amplify/Content tab) displays it as null, but I do not know if that is just a visual thing instead of saving it to null.

**Comment by guplem** [comment]
> Hi @guplem thanks for providing the info. I built a minimal App in Android platform to replicate similar situation using below schema
> 
> ```graphql
> type Todo @model {
>   id: ID!
>   name: String!
>   seField: String     # optional field
>   description: String # optional field
> }
> ```
> 
> Dart code
> 
> ```dart
> var todo = Todo(name: 'a name');
> await Amplify.DataStore.save(todo);
> 
> await Future.delayed(const Duration(seconds: 2));
> 
> // update the description field to non-null value
> var updatedTodo = todo.copyWith(
>   name: 'updated a name',
>   description: 'some description',
> );
> await Amplify.DataStore.save(updatedTodo);
> 
> await Future.delayed(const Duration(seconds: 2));
> 
> // reset the description field to null
> var updatedTodo2 = todo.copyWith(
>   name: 'updated a name',
>   description: null,
> );
> await Amplify.DataStore.save(updatedTodo2);
> ```
> 
> After execution, the final update that resetting `description` to `null` was working as expected.
> 
> The underlying GraphQL network request and response looked correct as well. <img alt="image" width="501" src="https://user-images.githubusercontent.com/10602282/160487229-1d625960-7c94-4a5f-a8c5-05e720ff18f5.png">
> 
> Therefore I don't think there is an issue here...
> 
> Next steps:
> 
> * When you update the model, did you explicitly assign `null` to the field like what shown in above example?
> * When you update the model, did you also change the fields with `AWSDateTime` or `AWSTime`? These fields require their value to be valid other wise AppSync may reject
> * Any code example that you wrote?

Can you try fetching the data before reuploading it by restarting the app?

I can reproduce the issue following these steps:
1. Open app
2. Fetch username (should be null, 1st time)
3. Upload something as username (this should work)
4. Close app
5. Open app
6. Fetch username (now it should have some value)
7. Try to save a null value as username modifying (data.copyWith) the fetched data
8. The value won't be updated

The issue doesn't get reproduced if:
1. Fetch null data
2. New dummy data is uploaded
3. **Modifying the originally fetched data**: set a null value and upload it

**Comment by HuiSF** [comment]
Hi @guplem appreciate the details. And you are right, setting `null` to a field has had non-null value is impossible with the `copyWith` named constructor due to the implementation:

```dart
  Todo copyWith(
      {String? id, String? name, String? seField, String? description}) {
    return Todo._internal(
        id: id ?? this.id,
        name: name ?? this.name,
        seField: seField ?? this.seField,
        description: description ?? this.description);
  }
```
It always ignore `null` value, if the copy source object has non-null value for a field.
Considering `description` is nullable defined in schema, I think we can tweak the implementation. I will sync up with amplify-codegen see what we can do about this.

In the meantime, you can try below approach to get around of it.

```dart
var todo = Todo(name: 'a name');
await Amplify.DataStore.save(todo);

await Future.delayed(const Duration(seconds: 2));

// update the description field to non-null value
var updatedTodo = todo.copyWith(
  name: 'updated a name',
  description: 'some description',
);
await Amplify.DataStore.save(updatedTodo);

await Future.delayed(const Duration(seconds: 2));

// reset the description field to null
// Use Todo default constructor instead of the copyWith named constructor
// assigning id field which ensures this save uses updateTodo mutation
var updatedTodo2 = Todo(id: updatedTodo.id, name: updatedTodo.name);
await Amplify.DataStore.save(updatedTodo2);
```

**Comment by jobypthomas** [comment]
I am having the same issue.

**Comment by itechevo** [comment]
I have the same issue, any update on this?

**Comment by hzhu359** [comment]
Any update on this ?

**Comment by Aidos-act** [comment]
Change this part in your Model

` Task copyWith({String? id, String? name, bool? completed, String? description, String? creator, TemporalDateTime? lastRejection, double? priority, TemporalTime? durationMin, TemporalTime? durationMax}) {
    return Task._internal(
      id: id ?? this.id,
      name: name ?? this.name,
      completed: completed ?? this.completed,
      description: description ?? this.description,
      creator: creator ?? this.creator,
      lastRejection: lastRejection ?? this.lastRejection,
      priority: priority ?? this.priority,
      durationMin: durationMin ?? this.durationMin,
      durationMax: durationMax ?? this.durationMax);
  }`
  
  `description: description ?? this.description,` this to
  `description: description ? this.description : null,` this

**Comment by Aidos-act** [comment]
> ### Description
> I have optional fields in my Amplify's tables.
> 
> They start as null. And I can set a value using my Android app.
> 
> However, I cannot update/remove that value to become null again after it has been set to a non-null value. Instead, it simply won't change.
> 
> This is pretty annoying... and broke some of my design...
> 
> You can see what, I think, is the same issue in Amplify's Android SDK: [awslabs/aws-mobile-appsync-sdk-android#194](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/194)
> 
> ### Categories
> (I am not sure but I think...)
> 
> * [ ]  Analytics
> * [ ]  API (REST)
> * [x]  API (GraphQL)
> * [ ]  Auth
> * [ ]  Authenticator
> * [x]  DataStore
> * [ ]  Storage
> 
> ### Platforms
> * [ ]  iOS
> * [x]  Android
> 
> ### Environment
> ```shell
> [√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
> [√] Android Studio (version 2020.3)
> [√] Android Studio (version 2021.1)
> [√] Connected device (4 available)
> [√] HTTP Host Availability
> 
> • No issues found!
> ```
> 
> ### Dependencies
> ```shell
> Dart SDK 2.16.1
> Flutter SDK 2.10.3
> time_manager 1.0.0+1
> 
> dependencies:
> - amplify_api 0.4.2 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
> - amplify_auth_cognito 0.4.2 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
> - amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
> - amplify_datastore 0.4.2 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
> - amplify_flutter 0.4.2 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotatio
> n meta plugin_platform_interface]
> - cupertino_icons 1.0.4
> - duration_picker 1.1.0+1 [flutter_lints flutter]
> - flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
> - restart_app 1.1.0 [flutter flutter_web_plugins]
> 
> transitive dependencies:
> - amplify_analytics_plugin_interface 0.4.2 [amplify_core flutter meta]
> - amplify_api_plugin_interface 0.4.2 [amplify_core collection flutter json_annotation meta]
> - amplify_auth_cognito_android 0.4.2 [flutter]
> - amplify_auth_cognito_ios 0.4.2 [amplify_core flutter]
> - amplify_auth_plugin_interface 0.4.2 [flutter meta amplify_core]
> - amplify_core 0.4.2 [flutter plugin_platform_interface collection date_time_format meta uuid]
> - amplify_datastore_plugin_interface 0.4.2 [flutter meta collection amplify_core]
> - amplify_storage_plugin_interface 0.4.2 [flutter meta amplify_core]
> - async 2.8.2 [collection meta]
> - characters 1.2.0
> - clock 1.1.0
> - collection 1.15.0
> - crypto 3.0.1 [collection typed_data]
> - date_time_format 2.0.1
> - flutter_lints 1.0.4 [lints]
> - flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
> - flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
> - intl 0.17.0 [clock path]
> - js 0.6.3
> - json_annotation 4.4.0 [meta]
> - lints 1.0.1
> - material_color_utilities 0.1.3
> - meta 1.7.0
> - path 1.8.0
> - plugin_platform_interface 2.1.2 [meta]
> - sky_engine 0.0.99
> - typed_data 1.3.0 [collection]
> - uuid 3.0.6 [crypto]
> - vector_math 2.1.1
> ```
> 
> ### Device
> OnePlus Nord 2
> 
> ### OS
> Android 11 (Oxygen 11.3)
> 
> ### CLI Version
> 7.6.22

Change this part in your Model

Under ` Task copyWith` 
  
  `description: description ?? this.description,` this to
  `description: description != null ? this.description : null,` this
  
 ?? This operator returns expression on its left, except if it is null.
 
 In your case Task copyWith is
```
 Task copyWith({String? id, String? name, bool? completed, String? description, String? creator, TemporalDateTime? lastRejection, double? priority, TemporalTime? durationMin, TemporalTime? durationMax}) {
    return Task._internal(
      id: id ?? this.id,
      name: name ?? this.name,
      completed: completed ?? this.completed,
      description: description != null ? this.description : null,
      creator: creator ?? this.creator,
      lastRejection: lastRejection ?? this.lastRejection,
      priority: priority ?? this.priority,
      durationMin: durationMin ?? this.durationMin,
      durationMax: durationMax ?? this.durationMax);
  }
```

**Comment by HuiSF** [comment]
We are looking into this issue, thank you all for your patience!

**Comment by HuiSF** [comment]
Hi all (cc @AdamMoroff75), Amplify CLI v12.1 has released which includes a solution to resolve this issue when generating model files.

Please upgrade Amplify CLI by running `amplify upgrade`, then run `amplify codegen models` to re-generate the models.

The newly generated models now provide a new method `copyWithModelFieldValues` allowing assigning `null` to nullable fields while copying.

For example, take schema

```graphql
type ModelA @model {
  id: ID!
  title: String!
  content: String
}
```

Copying with setting the nullable field `content` back to `null`

```dart
// original instance
final existingModelA = ModelA(
  title: 'Some title',
  content: 'Some content',
);

// keeping title, setting content to null
final updatedModelA = existingModelA.copyWithModelFieldValues(
  content: ModelFieldValue.value(null),
);
print(updatedModelA.content); // --> null

// updating title, setting content to null
final updatedModelA = existingModelA.copyWithModelFieldValues(
  title: ModelFieldValue.value('New title'),
  content: ModelFieldValue.value(null),
);
```

**Comment by d95sld95** [comment]
Has this been implemented end-to-end? I am doing something like this and it does not work.

```

// updating title, setting content to null
final updatedModelA = existingModelA.copyWithModelFieldValues(
  title: ModelFieldValue.value('New title'),
  content: ModelFieldValue.value(null),
);

await Amplify.DataStore.save(updatedModelA);

```

In the debugger I see the `content` value being `null`. But the value never changes in the Database. 

I can however set it to NULL using a GraphQL mutation: 

```
mutation MyMutation {
  updateModelA(input: {id: "1ffd16cd-46a5-4634-9495-b8c9fd918e61", _version: 7, comment: null}) {
    id
    comment   // showing NULL after executing this mutation
  }
}
```

**Comment by maziarzamani** [comment]
Have similar issue I think, it seems like when I make a mutation it adds null to all the variables that are not provided, which is insane.

**Comment by Jordan-Nelson** [comment]
@d95sld95 or @maziarzamani - Can you open a new issue and fill out the info in the issue template so that we can try to reproduce this?

**Comment by osehmathias** [comment]
This still doesn't work.

**Comment by osehmathias** [comment]
This still doesn't work when you're trying to remove a connection.
