### ISSUE TITLE
Flutter Amplify Storage FILE UPLOAD does not work - Upload never completes, no output, no error message

### ISSUE THREAD

**Issue by julius-stuemmler** [aws-amplify/amplify-flutter#1481]
### Description

Hey guys, I want to use Amplify for my app, but the problem is, that I cannot upload any file to amplify s3 storage. 
I can get a public url etc., but only uploading is not working. 

I'm using the default example from amplify docs: [example](https://pastebin.com/XfKjH0S2)

Not working means, that the future never completes. If I execute the upload, the future never finishes, so I'm never getting any result/output and nothing is uploaded in storage. Addiotionally I don't even get any error or exception.

It was the same if I add Storage via webinterface or cli.

I really like amplify, but this absolutetly needed as a core function in my app. Thanks very much.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

I tried to reduce my project as much as possible.

1. [Android Manifest](https://pastebin.com/gaQxJXsc)
2. [pubspec.yaml](https://pastebin.com/MJrAw70Y)
3. [main.dart](https://pastebin.com/CkcN1Gv8)
4. [amplifyconfiguration.dart](https://pastebin.com/hmvyPMex)

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

flutter doctor -v: https://pastebin.com/qSSKatgT
```

### Dependencies

```bash
see above in description
```

### Device

Pixel 5 Emulator (Windows 10/11)

### OS

Android API 30

### CLI Version

7.6.26

**Comment by HuiSF** [comment]
Hi @julius-stuemmler thanks for reporting this issue.
Were you able to collect Android logs around when you were calling the `uploadFile` API to help triaging this issue?

**Comment by julius-stuemmler** [comment]
@HuiSF Hey, Do you have any resource, to see how can I do that? Thanks

**Comment by HuiSF** [comment]
You can use [Android Studio](https://developer.android.com/studio/debug) to run the App, and view logs in the debug view.

**Comment by julius-stuemmler** [comment]
Ah I see, here are the logs, if I push the button: https://pastebin.com/GKLnvu2x
Messages from Debug window, when I restart the app: https://pastebin.com/qMppNUe3


So new question is, why does it say, that the Plugin is not configured?

**Comment by julius-stuemmler** [comment]
Ah I see, here are the logs, if I push the button: https://pastebin.com/GKLnvu2x
Full log (incl. pushing a button): https://pastebin.com/P9U4EBKY 
Messages from Debug window, when I do a hotrestart: https://pastebin.com/qMppNUe3

So new question is, why does it say, that the Plugin is not configured?

**Comment by HuiSF** [comment]
>So new question is, why does it say, that the Plugin is not configured?

Can you paste the code snippet to add and configure Amplify plugins? Did you `await` for `Amplify.addPlugin` and `Amplify.configure` before invoke Storage plugin APIs?

**Comment by HuiSF** [comment]
And regarding the exception in the 3rd link, please take a look at this [document](https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter/#using-flutter-hot-reload-and-hot-restart) regarding how to use Amplify with Flutter hot reload and hot restart.

**Comment by julius-stuemmler** [comment]
> > So new question is, why does it say, that the Plugin is not configured?
> 
> Can you paste the code snippet to add and configure Amplify plugins? Did you `await` for `Amplify.addPlugin` and `Amplify.configure` before invoke Storage plugin APIs?

https://pastebin.com/iXbABGDS

**Comment by julius-stuemmler** [comment]
main.dart: testbase: https://pastebin.com/d1YvAVCM
debug log: https://pastebin.com/grzxiWLZ

**Comment by julius-stuemmler** [comment]
Hey, I seems to work again. The strange part is, that I haven't touched the code for a few days and now it's working again. So I cannot present any solution for it. Thanks for your effort.
