### ISSUE TITLE
GraphQL API Subscription onCreate with Filter option

### ISSUE THREAD

**Issue by OLTApp** [aws-amplify/amplify-flutter#1482]
Use case :  Able to filter the subscription for onCreate mutation. 

Example: I would like subscription to fire for onCreate only if the user id matches the current app user. In my case the subscription is for in app notification based on the other user actions. But only when that action make sense to the current user, the app needs to respond. With out the filter option for all create mutation for a model, the subscription is triggered. 

This may be applicable to onUpdate, onDelete as well.

**Comment by ragingsquirrel3** [comment]
I believe this is possible currently using a custom subscription. There are some amplify documents about it, although we do not currently have a flutter example available https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/android/.

**Comment by ragingsquirrel3** [comment]
We added a flutter example for this use case to our documentation. It is available at https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/flutter/ . I'm going to close this issue but feel free to comment with problems or suggestions for how to improve this use case.
