### ISSUE TITLE
AuthUser username returned as email address on Android

### ISSUE THREAD

**Issue by ebo8** [aws-amplify/amplify-flutter#1513]
We're using Cognito User Pools. Signing in with username and email address is both enabled.

1. Sign in with email address
2. Run the following code block:
` AuthUser user = await Amplify.Auth.getCurrentUser();`
`    return user.username;`
3. Expected behaviour is to return the user's username
4. Android returns the email address, iOS returns the username as expected

**Comment by Jordan-Nelson** [comment]
Hello @ebo8 - I believe this issue is the same as #201. Can you take a look at #201 and see if that matches the behavior you are experiencing?

**Comment by ebo8** [comment]
Thank you @Jordan-Nelson for the reply. I'll close this and post in #201.
