### ISSUE TITLE
Case-sensitive inconsistent for queries

### ISSUE THREAD

**Issue by guplem** [aws-amplify/amplify-flutter#1518]
### Description

If you do a query using "contains" it is case-sensitive (and cannot be reconfigured to be case-insensitive). 
But using "beginsWith" it is not case-sensitive (but it can't be reconfigured either). 
Note: I found [an issue](https://github.com/aws-amplify/amplify-flutter/issues/1159) related to weird behaviour with "beginsWith".

I was expecting a way to configure the case sensitivity (or different methods like "contains" and "containsIgnoreCase") since I can't figure out how to configure a "search by username" feature in my app.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Save multiple items using upper and lower case (for example a1, A2, ...)
2. Set up a query looking for those items using "contains" and "beginsWith".
3. Check the returned results. They will differ, and no way of reconfiguring if the results should consider the upper/lower case exists.

### Platforms

- [?] iOS
- [X] Android

### Environment

```bash
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.3
time_manager 1.0.0+1

dependencies:
- amplify_api 0.4.2 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.2 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.2 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.2 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotatio
n meta plugin_platform_interface]
- cupertino_icons 1.0.4
- duration_picker 1.1.0+1 [flutter_lints flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- restart_app 1.1.0 [flutter flutter_web_plugins]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.2 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.2 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.2 [flutter]
- amplify_auth_cognito_ios 0.4.2 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.2 [flutter meta amplify_core]
- amplify_core 0.4.2 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.2 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.2 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- flutter_lints 1.0.4 [lints]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
```

### CLI Version

7.6.26

**Comment by Jordan-Nelson** [comment]
Hello @guplem - Thanks for opening the issue. There are some known inconsistencies in case sensitivity in the string related query predicates (contains, beginsWith).

It might make sense to track these under one issue, but as you noted, #1159 is specific to beginsWith. I can update it next week to cover the broader set of issues around case insensitivity.

This may not help for your use case, but I wanted to note that you can use the or() operator to combine multiple predicates as a work around for running a query that contains a string with multiple case variations.

**Comment by guplem** [comment]
Okay, thank you very much.

More flexibility in general while doing query and saving data would be great (lists, matching options like case sensitivity, accents, ...). Right now, it is one of the major constrains in my development process.

Additionally, the methods "eq", "ne", "gt", ... why do they have those names? Shouldn't they be self-explanatory?

**Comment by guplem** [comment]
> I can see how those names may not be intuitive. Currently those names are consistent across all Amplify libraries (JS, iOS, Android, Flutter). We could look into changing them, but I think adding API docs would be a big improvement here. What do you think? See the example below.
> 
> <img alt="Screen Shot 2022-04-11 at 10 32 13 AM" width="634" src="https://user-images.githubusercontent.com/20613561/162762380-d23f71bd-553c-4adc-902d-3a0f3c7faad3.png">

That would be of great help for new users at least, but the best would be to have proper naming.

**Comment by guplem** [comment]
> There is a feature request open for configuring case sensitivity in Amplify-JS ([aws-amplify/amplify-js#8516](https://github.com/aws-amplify/amplify-js/issues/8516)) but I think we can open a feature request in Amplify-Flutter as well to track interest in this. Do you mind sharing more about your use case? Would your use case require this to be configurable at runtime on a query by query basis, or would it be sufficient to configure it once per model/field?
> 

I just opened an issue to implement case sensitivity configuration in Amplify-Flutter: https://github.com/aws-amplify/amplify-flutter/issues/1535

**Comment by Jordan-Nelson** [comment]
> That would be of great help for new users at least, but the best would be to have proper naming.

I have opened a feature request for this (#1536).

> Additionally, I do believe that all methods should have "API docs" (quick documentation available from the IDE).

Agreed. This was definitely a miss. #1519 adds api docs to all of those methods. This change has not been included in a published version yet, but should be soon. 

> I just opened an issue to implement case sensitivity configuration in Amplify-Flutter: https://github.com/aws-amplify/amplify-flutter/issues/1535

Thanks. I have marked it as a feature request. We will use this to track interest.

With #1159 updated, and the two new feature requests opened, I believe this issue can be closed. Please let me know if you think there is a reason to keep this open.

**Comment by Jordan-Nelson** [comment]
@guplem - I am going to close this out since I have not heard back. Feel free to open a new issue if you believe the issues above do not cover everything.

**Comment by guplem** [comment]
> @guplem - I am going to close this out since I have not heard back. Feel free to open a new issue if you believe the issues above do not cover everything.

Ups, sorry, I was focusing on other projects during this week. Yeah, this can be closed as you did, thanks!
