### ISSUE TITLE
Required relation object 

### ISSUE THREAD

**Issue by willianmascimiano** [aws-amplify/amplify-flutter#1527]
### Description

I understand nested data in Amplify generate two fields, a ModelID and a Model from relationship.

In my example I have Modelo hasMany Marca. 

```graphql
type Modelo @aws_iam @aws_cognito_user_pools {
  id: ID!
  tipo: ModeloTipo!
  marca: Marca!
  descricao: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  modeloMarcaId: ID!
}

enum ModeloTipo {
  VEICULO
}

type Marca @aws_iam @aws_cognito_user_pools {
  id: ID!
  tipo: ModeloTipo!
  descricao: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

After generate the model files, in Modelo Model was created two fields, _marca and _modeloMarcaId. 

In my case I need just to fill them _modeloMarcaId Field to save in database, but I must specify _marca field, because this field is mandatory and I don't see some need to fill it.

Now, when I try to instante an Modelo Object, the code ask for Marca() object.

```dart
class Modelo extends Model {
  static const classType = const _ModeloModelType();
  final String id;
  final ModeloTipo? _tipo;
  final Marca? _marca;
  final String? _descricao;
  final TemporalDateTime? _createdAt;
  final TemporalDateTime? _updatedAt;
  final String? _modeloMarcaId;
```

This is my SAVE method.

```dart
onPressed: () {
          Modelo modelo = Modelo(
            tipo: ModeloTipo.VEICULO,
            descricao: nome.text,
            modeloMarcaId: marca.text,
           // marca: MarcaService().findById(marca.text) as Marca,
          );
```

![image](https://user-images.githubusercontent.com/19466705/163307187-550ee2ea-384f-4334-bf76-b703d25d6991.png)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Dependencies

```bash
Dart SDK 2.16.2
Flutter SDK 2.10.4
logistica 0.0.3+3

dependencies:
- amplify_api 0.4.4 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.4 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_datastore 0.4.4 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.4 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_native_splash 2.1.5 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_osm_plugin 0.32.2 [flutter flutter_plugin_android_lifecycle stream_transform permission_handler url_launcher dio uuid flutter_osm_interface]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.4 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.4 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.4 [flutter]
- amplify_auth_cognito_ios 0.4.4 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.4 [flutter meta amplify_core]
- amplify_core 0.4.4 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.4 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.4 [flutter meta amplify_core]
- archive 3.3.0 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- dio 4.0.6 [http_parser path]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_osm_interface 0.1.19 [flutter plugin_platform_interface stream_transform permission_handler google_polyline_algorithm dio]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_polyline_algorithm 3.1.0
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lint 1.8.2
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

### Device

Moto g9

### OS

0

### CLI Version

8.0.0

**Comment by ragingsquirrel3** [comment]
hi @willianmascimiano, I think your codegen model has `Marca!` in the schema. At the root, I think you could make that an optional field in your schema and rerun codegen command. Is there a reason you aren't using @hasMany and @hasOne directives in your schema as on https://docs.amplify.aws/cli/graphql/data-modeling/#has-many-relationship?

In your schema, looks like you are opting to manage the relationship yourself. That might get more complicated as the API plugin works a lot more smoothly if you use the directives to manage this, especially if you want to use the same encodings with model helpers like `ModelQueries.get()`. I think you could simplify your schema like:

```yaml
type Modelo @aws_iam @aws_cognito_user_pools {
  id: ID!
  tipo: ModeloTipo!
  marca: Marca! @belongsTo
  descricao: String!
}

enum ModeloTipo {
  VEICULO
}

type Marca @aws_iam @aws_cognito_user_pools {
  id: ID!
  tipo: ModeloTipo!
  descricao: String!
  modelos: [Modelo] @hasMany
}
```

Note: I also removed createdAt and updatedAt as they will get added automatically by AppSync and managed more easily if you just omit them in your schema. You would still have to supply `Marca` when you instantiate or update a modelo.

**Comment by willianmascimiano** [comment]
If the field is mandatory, I will have to instantiate every time an object that I will not use?

I can turn those fields as optionals and check every time when needed, but I couldn't understand why I need to inform both variables if in record what's matter is the Id.


Thanks for yours observations and I will make the update in my code and generate codegen again.

**Comment by ragingsquirrel3** [comment]
It will be necessary when you instantiate a new model, but the good news is the parent is automatically included in model query helpers when you set it up this way. If you run `ModelQueries.get()` on a child, all the response objects will have the parent available.

**Comment by willianmascimiano** [comment]
> It will be necessary when you instantiate a new model, but the good news is the parent is automatically included in model query helpers when you set it up this way. If you run `ModelQueries.get()` on a child, all the response objects will have the parent available.

Well, that's new for me.

I have tried thus about a month ago and I couldn't get the values from parent relationship, even in get method.

When this resource become available? Recently or I was making mistakes?

Thanks for the info and I'm updating my project with your notes.

**Comment by ragingsquirrel3** [comment]
@willianmascimiano only parents 1 level up are included in model helpers, not children. To include children, you would need to do a custom request with decoding like example on https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#nested-data

**Comment by Jordan-Nelson** [comment]
@willianmascimiano please let us know if you are still experiencing any issues with this. Thanks.

**Comment by willianmascimiano** [comment]
> @willianmascimiano please let us know if you are still experiencing any issues with this. Thanks. 

Ican close this issue
