### ISSUE TITLE
REST API exception -- incorrect authorization headers in API request -- when invoking a lambda with Cognito User Pool authorization

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-flutter#1539]
### Description

Making a simple REST API call to invoke a lambda, using the Amplify library generates an exception. The exception is of the type "IncompleteSignatureException". This is the exception (and the code that produced it is below):

```RestException (RestException{response=RestResponse{statusCode=403, headers={date: Tue, 19 Apr 2022 16:05:50 GMT, x-amz-cf-pop: PHL50-C1, content-length: 1387, x-amz-apigw-id: Q1ea3Gc8IAMFpKg=, x-amzn-errortype: IncompleteSignatureException, x-amzn-requestid: 675e16b7-040a-42db-8701-c131d8839886, access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, access-control-allow-methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT, access-control-expose-headers: Date,X-Amzn-ErrorType, via: 1.1 4e2a7874b5959279490dd3b94b18a312.cloudfront.net (CloudFront), access-control-allow-origin: *, content-type: application/json, x-cache: Error from cloudfront, x-amz-cf-id: fopmdScPl7SH28T5P0G-8wn-nmJiJD-cTMQI3HqqcH5-H8uV122zow==}, body={"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=eyJraWQiOiJxQitDb1N0UHhcL1VGY09OODAxVWlRSUlETXlmSXk4WGFUeWhJelwvUkRMZmc9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIyYWU2M2Q3Ny01NjQ4LTQ3MTgtOGYxNC0yMTkzZWYzMGM4NjgiLCJjb2duaXRvOmdyb3VwcyI6WyJldmVyeW9uZSJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV94SnhaMzBQcU0iLCJjbGllbnRfaWQiOiJodjBhYnBuOW02Zjh0MXFucG84MWdqZyIsIm9yaWdpbl9qdGkiOiJjOTJlYzdjMS00NTY5LTQwZTEtODliNy0xNjE3MzBiZDVkZGQiLCJldmVudF9pZCI6ImVjZWZhNjIyLTNmODMtNGU3ZS1iZjI5LWY1ZmI0M2ZiNDY3NSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTAzNzcwNjYsImV4cCI6MTY1MDM4Nzk0MSwiaWF0IjoxNjUwMzg0MzQxLCJqdGkiOiIyNTIzMDMxZS1hY2M0LTQ3NmYtYWRiNi0xOWZkNjc0YTQ3ZWUiLCJ1c2VybmFtZSI6IjJhZTYzZDc3LTU2NDgtNDcxOC04ZjE0LTIxOTNlZjMwYzg2OCJ9.CChosPtwByAi-GqiDyz_17CGrvYHgkGuy-ZdP_abrshtO9DwNwIYBbuVN7tuQhUztrrZn-HMvYztBSIz2BDOQyVDLIIu_QiKh2MOK3c9vySilKBPkn9eEK7VQeSHulei6kPnpXiErGzX53RjT5qAHXB_YwBLbhwThqZ-zvJQLmV1maxt0JODNebw7-Q3F1C5wvMZatu3uGBFXKrQGDeJTwioAA38BzqxkJ2ZVTnoNi8SYHBih-UhrNwJYVYpBR0csjo-OuPRQoiK2biKzLG2ojywcBkr4MrH0VcFdvqrI72Tst628x7h8kgLMuN3jb4HJarMhP5bBZ9tMI3slIfq8Q"}}})```

This is the code that throws the exception:

```dart
  Future<RestResponse> updateUserAbout(String about) async {
    final List<int> list = '{"about": "$about"}'.codeUnits;
    RestOptions restOptions = RestOptions(
        path: '/update-user',
        apiName: 'lambdaFunctionsCognito',
        body: Uint8List.fromList(list));

    RestOperation restOperation = Amplify.API.put(restOptions: restOptions);
    RestResponse response = await restOperation.response;
    return response;
  }
```

The exception occurs at the line
```dart
    RestResponse response = await restOperation.response;
```

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. create a REST API lambda via CLI, then edit the update code to support `put` in the express code (although probably the same error would show up with a `get` request too, but I have not tested this):
```
spawn amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: updateUser
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Serverless ExpressJS function (Integration with API Gateway)

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource updateUser locally.
```
2. add API Gateway for lambda
```
spawn amplify add api
? Select from one of the below mentioned services: REST
✔ Provide a friendly name for your resource to be used as a label for this category in the project: · lambdaFunctions
✔ Provide a path (e.g., /book/{isbn}): · /update-user
✔ Choose a Lambda source · Use a Lambda function already added in the current Amplify project

✔ Choose a Lambda source · Use a Lambda function already added in the current Amplify project
✔ Choose the Lambda function to invoke by this path · updateUser
✔ Restrict API access? (Y/n) · yes
✔ Restrict access by: · Auth/Guest Users
✔ Who should have access? · Authenticated users only
✔ What permissions do you want to grant to Authenticated users? · update
✔ Do you want to add another path? (y/N) · no


✅ Successfully added resource lambdaFunctions locally
```
3. call the API with code similar to the code shown in the 'Description` section above

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 31

### Environment

```bash
[✓] Flutter (Channel stable, 2.10.4, on Debian GNU/Linux 11 (bullseye) 5.10.0-13-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Changing current working directory to: /home/dtal/repos/tracktunes_app_aws
Dart SDK 2.16.2
Flutter SDK 2.10.4
tracktunes_app_aws 1.0.0+1

dependencies:
- amplify_api 0.4.5 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.5 [flutter amplify_auth_plugin_interface amplify_core amplify_auth_cognito_android amplify_auth_cognito_ios collection plugin_platform_interface]
- amplify_datastore 0.4.5 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.5 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- amplify_storage_s3 0.4.5 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_storage_s3_android amplify_storage_s3_ios amplify_core]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- hooks_riverpod 1.0.3 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.5 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.5 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.5 [flutter]
- amplify_auth_cognito_ios 0.4.5 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.5 [flutter meta amplify_core]
- amplify_core 0.4.5 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.5 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.5 [flutter meta amplify_core]
- amplify_storage_s3_android 0.4.5 [flutter]
- amplify_storage_s3_ios 0.4.5 [flutter]
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- ffi 1.1.2
- file 6.1.2 [meta path]
- flutter_hooks 0.18.3 [flutter]
- flutter_riverpod 1.0.3 [collection flutter meta riverpod state_notifier]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- riverpod 1.0.3 [collection meta state_notifier]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- state_notifier 0.7.2+1 [meta]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- win32 2.5.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

QEMU - Emulated Android Phone

### OS

Android 8

### CLI Version

8.0.2

**Comment by Jordan-Nelson** [comment]
> Set up a Cognito User Pools section in the amplifyconfiguration.dart by copying the IAM API section and changing the "AuthMode" value to "AMAZON_COGNITO_USER_POOLS"

I am not sure that you need to do this. I just went through the repro steps you added, but did not make this change. It seems to be using Cognito as the auth provider. I am unsure why it lists IAM in the config. I can look into that and get back to you, but in the mean time can you tell me if it seems to authenticate request correctly without that change?

**Comment by Jordan-Nelson** [comment]
I confirmed that I could repro the issue if I make that manual change to the config. I don't think that you should need to make that change though.

From the [CLI docs](https://docs.amplify.aws/cli/restapi/restapi/#create-a-rest-api):

> Amplify CLI restricts API access combining Amazon Cognito for authentication and AWS IAM (Identity and Access Management) for granting execution permissions on routes.

I think that is why it lists IAM in the config.

**Comment by Jordan-Nelson** [comment]
@dorontal - Let me know if you face any issues with the config as generated by the CLI. I have confirmed that Cognito auth works as expected with the config as generated by the CLI. Unauthenticated users do not have access to the endpoint and authenticated users do.

**Comment by dorontal** [comment]
I still don't understand how things work as expected with the config as generated by the CLI when your own documentation tells us to add a Cognito section to the config.

@Jordan-Nelson the change to add a Cognito section in order to authenticate API requests with Cognito was recommended to me by one of your teammates -- when I complained abut "Authorization denied" errors before.  As the documentation states, if you are to use a REST API with Cognito user pools, then you need to add a section in  the `amplifyconfiguration.dart` as described here

https://docs.amplify.aws/lib/restapi/authz/q/platform/flutter/#cognito-user-pool-authorization

Have you ever succeeded in running a lambda function from the client via a REST API while authenticating via Cognito User Pools?  If you are able to do so in any other way then please describe how you accomplished this.

**Comment by dorontal** [comment]
I forgot to mention that I did try just leaving the config alone, but then I get another error - an AuthorizationException -  with message "Permission denied".  That's because Amplify Flutter by default uses IAM for REST APIs but I've set up the API to authenticate via Cognito User Pools. This is why we have to make the change in the config for that. This why we get an auth exception.

**Comment by dorontal** [comment]
@Jordan-Nelson and @dnys1 please don't close this issue. I believe this issue still stands 100%. The authorization headers that get sent when you authenticate via Cognito User Pools are incomplete, that's all that needs to get fixed. Until that gets fixed, it will not be possible to use lambda functions that require Cognito User Pools authentication.

**Comment by Jordan-Nelson** [comment]
Hi @dorontal - Let me sync with @dnys1 and potentially our CLI team and get back to you. It is possible that I am mistaken about the setup here.

**Comment by Jordan-Nelson** [comment]
Hi @dorontal - It looks like the Amplify CLI does not fully support Rest + Cognito. As you have said, the auth headers will not be included by default. There is an issue open in the Amplify CLI repo to track this (https://github.com/aws-amplify/amplify-category-api/issues/345). Feel free to give that a 👍 to show your support.

Because of this, a workaround like you are attempting is indeed needed. There appears to be a two different ways to work around this issue. I will summarize them below and link out to other resources to explain them better.

You are currently following the docs, which is option 1. Have you taken step 2 to configure API Gateway with custom authorization?

#### Option 1: This is what the docs refer to, although the docs could probably be improved.
1. Set `authorizationType` to "AMAZON_COGNITO_USER_POOLS" as you have done.
2. Configure API Gateway with custom authorization. The docs link to [this resource](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html) to describe this process. The actual step by step process for configuring Cognito & Rest is described in one of the subtopics which you can see [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html). There is also an abbreviated step by step guide in [this comment](https://github.com/aws-amplify/amplify-flutter/issues/471#issuecomment-854858431) on another issue.

#### Option 2: Manually add the headers to the request
This is described very well [here](https://github.com/aws-amplify/amplify-flutter/issues/913#issuecomment-951217279), with screenshots and code snippets.

**Comment by dorontal** [comment]
Hi @Jordan-Nelson thank you very much for this clarification. The option I had taken was option 1 (as described by the documentation link in my previous message) but I did not realize there was a further step 2 to this. Thanks so much for outlining this step 2 of configuring API Gateway with custom authorization. I will try that and will let you know it goes.

**Comment by Jordan-Nelson** [comment]
No problem. I think the docs could be improved to make it clear there are additional steps required. Once you have been able to get this set up successfully I can mark this as a docs issue to make that clear.

**Comment by dorontal** [comment]
Unfortunately when I tried to follow the first workaround (Option 1 above) -- while I no longer get the "missing authorization headers" error, which is a good sign, I get an "internal server error and am currently asking about that here: " https://github.com/aws-amplify/amplify-flutter/issues/471#issuecomment-1152553722

**Comment by Jordan-Nelson** [comment]
Are you able to see in the AWS console if the request is reaching lambda?

**Comment by Jordan-Nelson** [comment]
@dorontal - I went through the steps, and initially I received an internal server as well. After looking through the API Gateway and Lambda logs, I found that the event was not being forwarded from API Gateway to Lambda. To address this I had to do the following:
- From API Gateway console, go to "resources" (in the side panel) and then select the method that was added previously
- Choose "Integration Request"
- Enable "Use Lambda Proxy integration" and redeploy

Once I had done this, I was able to confirm with a simple lambda like below that the authorization header is reaching the lambda in `event.headers`.

```js
exports.handler = (event, context, callback) => {
  console.log(`CONTEXT: ${JSON.stringify(context)}`);
  console.log(`EVENT: ${JSON.stringify(event)}`);

  callback(null, {
    statusCode: 200,
    body: JSON.stringify({ message: 'Hello from Lambda!' }),
    headers: { 'Content-Type': 'application/json' },
  });

};
```

Can you check you lambda logs to see if the request is reaching lambda? I also found it helpful to enable cloud watch logs for API Gateway so that I could see why the request was still failing even though everything seemed fine from the lambda. You can follow [these steps](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/) to do that.

**Comment by Jordan-Nelson** [comment]
@dorontal - What are you attempting to do in the `updateUser` function?

**Comment by Jordan-Nelson** [comment]
Here are the full set of steps that I took:
1. Follow all the required steps under "To create a COGNITO_USER_POOLS authorizer by using the API Gateway console" (4f and 5 are optional) in the [Integrate a REST API with an Amazon Cognito user pool](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html) docs.
2. Follow steps 1-5 and step 7 under "To configure a COGNITO_USER_POOLS authorizer on methods" in the [Integrate a REST API with an Amazon Cognito user pool](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html) docs.
3. Enable Lambda Proxy integration:
  a. From API Gateway console, go to "resources" (in the side panel) and then select the method that was added previously
  b. Choose "Integration Request"
  c. Enable "Use Lambda Proxy integration" and redeploy

**Comment by dorontal** [comment]
@Jordan-Nelson, thanks so much. I am working on testing your suggestions and will edit this response once done.  

To answer one question - the reason for this `updateUser` lambda in the first place is this: I need to update properties inside the user model that are inaccessible to the user/owner of the user model, e.g, the number of updates in the past 24 hours and other throttling related data.  Every time a user updates anything in their own model, I want to increment the property `nUpdatesInLast24h``, for example. The only way to do that securely is by making the update function a lambda function -- the lambda function performs checks on how many updates have been made and if too many have been done in the past 24 hours, it does nothing.  This is why I need a lambda function - to update the user in a secure way.

**Comment by Jordan-Nelson** [comment]
I had added a new method specifically for "PUT". I would think the default "ANY" would work though.

If you add some logs to your lambda, are you able to see if the `event` has the authorization header?

```js
  console.log(`CONTEXT: ${JSON.stringify(context)}`);
  console.log(`EVENT: ${JSON.stringify(event)}`);
```

Since the request is reaching lambda, I think one of two things is happening. 1) The Lambda is returning an error (possibly because it doesn't have the correct authorization, but possibly for any other reason) or 2) API Gateway isn't getting a response from Lambda it can handle.

I would take the following steps to debug this:
1. temporarily update the lambda to something simple like what I had added in the comment above.
  a. See if the basic "hello world" style lambda completes and returns 200.
  b. See if the authorization header is logged (can view this in the cloud watch logs for lambda)
2. Enable cloud watch logging in API Gateway and inspect the response from lambda to API Gateway. If API Gateway is rejecting the response from lambda, it may be in the logs.

**Comment by dorontal** [comment]
@Jordan-Nelson Thanks very much again!!  This seems to have solved everything.

1) The lambda is receiving the 'Authorization' header -- it shows up in the cloud-watch logs

2) Indeed those same logs show that the lambda had its own error - that must be what caused the internal server error. The error reported is difficult to understand but probably not related to this issue. Will look into it and report here if the error reported **is** related to this issue.  Here is the error shown in CloudWatch logs:

```
2022-06-13T15:06:13.670Z	f0d0be01-669d-4e73-9f9d-1ac2286a0c23	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'userAttributes' of undefined",
    "stack": [
        "TypeError: Cannot read property 'userAttributes' of undefined",
        "    at Runtime.exports.handler (/var/task/index.js:8:32)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

even though the code does not even contain the symbol `userAttributes`...

**Comment by Jordan-Nelson** [comment]
Great. I am going to leave this open and mark it as a documentation issue so that we can get a clearer explanation in the docs.

**Comment by dorontal** [comment]
FYI, after a re-deploy of everything with Amplify CLI v 9.0.0, it works, but the only way I got it to work was to add the following four scopes in **Step 7** of the documentation page [Integrate a REST API with an Amazon Cognito user pool](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html): `email, openid, profile, aws.cognito.signin.user.admin`

Not sure if all four are needed but adding all four worked and not adding all four gave 401 errors.

**Comment by dorontal** [comment]
@gaarlsha it is difficult for me to understand in your comment why the link to https://github.com/aws-amplify/amplify-flutter/issues/913#issuecomment-951217279 works to fix this issue for you - I searched for 'datastore' in that link/issue and that issue does not refer to Datastore. But this issue is related to Datastore. Are you able to explain why that link is relevant here? Sorry but I do not understand how it may help.

**Comment by dorontal** [comment]
@HuiSF  What is the ETA for fixing this important issue that doesn't allow anybody using multi-auth to also use Datastore?

The one year anniversary of this issue is coming up!

Thanks for taking note. This is a crucial issue if you want people to use Datastore / Amplify, IMO - this is not just some minor issue because it is a common use case to require and use (1) multi-auth, (2) Datastore.

**Comment by dorontal** [comment]
@HuiSF , @dnys1 , @Jordan-Nelson 

I'd like to also bring your awareness to the labels on this issue - which may be part of the reason for why it has been so neglected for so long - why is the "Documentation" label here - I protested this label from the start.

This is an issue with code, not with documentation at all. Please fix the labels on this issue.

This issue is with the Datastore code - why is the 'datastore' label not on here?

Please make the labels reflect more accurately what this issue is about - maybe this would help it getting solved more quickly?

**Comment by dorontal** [comment]
[ Apologies: I had made some comments here which were meant for another issue. Then, because this issue has been solved for a while, closed it, but I just noticed that it was left open on purpose for changing some documentation, so re-opening it now and I won't touch "open" or "close" on Amplify issues from now on - my mistake.]

**Comment by dorontal** [comment]
Adding A Cognito Authorizer for the REST API worked well.

The documentation that I followed thanks to the comments above and which solved it is [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html).

Please note that when adding scopes - in that step I added all four scopes `email`, `openid`, `profile`, `aws.cognito.signin.user.admin` and this worked - but I never explored whether a more minimal set of scopes is sufficient to make things work. It's quite possible that you do not need all four scopes.

As far as I'm concerned, this issue can be 100% closed now. The button to do so is available, but I will leave it up to you @Jordan-Nelson  because I don't feel that I have enough authority to do that.

Thank you for the help, all who helped here.

**Comment by dorontal** [comment]
By the way, @Jordan-Nelson, @fjnoyp - I've noticed that this issue is still open. But your suggestion to add a Cognito Authorizer completely solved the issue previously. Thanks for that! In any case, I hesitate to close it myself - just wanted to let you know that as far as I'm concerned, this issue has been completely solved thanks to your help.

**Comment by AtharvArolkar** [comment]
Im getting the similar error, Im unable to fix. it says : 
"IncompleteSignatureException: Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header."


My question is how do i create a aws signature and add it to the Authorisation header;

const data = await runWithAmplifyServerContext({
      nextServerContext: { cookies },
      operation: async (contextSpec) => {
        const authToken = await fetchAuthSession(contextSpec);
        return post({
          apiName: process.env.NEXT_PUBLIC_AMPLIFY_API_ENDPOINT_NAME as string,
          path: `${url}`,
          options: {
            headers: {
              "x-api-key": atob(
                process.env.NEXT_PUBLIC_AMPLIFY_API_API_KEY as string
              ),
              Authorization: authToken.tokens?.idToken?.toString()!,
            },
            body: payload,
          },
        });
      },
    });
