### ISSUE TITLE
Datastore: Disable synchronization to specific models with selective sync

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [aws-amplify/amplify-flutter#1553]
### Description

Hi, 

I've check and didn't find an related issue to this, which I doubt is the case.

I want to not sync specific models while configuring Amplify Datastore.

When syncing down the datastore on app start it does by default this:

```
 await Amplify.addPlugin(AmplifyDataStore(
          modelProvider: ModelProvider.instance,
          syncExpressions: [
            DataStoreSyncExpression(<model>.classType, () => QueryPredicate.all)
]));
```

On [Android](https://github.com/aws-amplify/amplify-android/issues/987) you can tell Datastore to not sync a specific model with something similar to: 
`DataStoreSyncExpression(Model.classType, () => QueryPredicate.none),`

amplify_core-0.4.4/lib/src/types/query/query_predicate.dart does include "none" already but it is not used. Would the following solve my case? 

<img width="525" alt="Screenshot 2022-04-26 at 22 28 45" src="https://user-images.githubusercontent.com/97729760/165387190-d6049f80-c83b-48ae-bd07-4757ab59d6b3.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
N/A
```

### Dependencies

```bash
N/A
```

### Device

N/A

### OS

N/A

### CLI Version

N/A

**Comment by HuiSF** [comment]
Hello, thanks for opening this issue regarding your use case.

1. `QueryPredicate.none` in amplify-android
This query predicate shortcut is not officially documented, and its implementation implies `id` field always exists in a model which could be problematic with the progress of custom primary key work. So I personally don't recommend to use it.

2. Not to sync a specific model
I want to get a clarification on this use case - while this model is not being synced, do you still use the model to write/read data into local DB?
    * If no, there is a work around is that you can delete the model reference from the generated model provider class, which will exclude the model from sync engine completely
    * If yes, you may need to try to use different sync expression
    e.g. If your model has required `id` field, you can try, as the `id` is the partition key in DynamoDB, so the sync query will use `Query` operation instead of `Scan`, which should be performant
      ```dart
      DataStoreSyncExpression(<model>.classType, () => Model.ID.eq(null))
      ```
    Please note that, currently, even though you can use sync expression to avoid syncing models, but mutation updates will still reach to end device regardless, and sync engine uses sync expression as a client filter to ignore updates on these models, which could be a performance hit.

**Comment by Simon-PumpAndUp** [comment]
Thank you, very clear. 

That would be a nice feature to have instead of a dirty equals null.

**Comment by samuelrbrt** [comment]
A better approach would be to create a subscription model provider by extending the existing `ModelProvider` and keep the models that are required to sync:

`class SubscriptionModelProvider implements ModelProvider {
  @override
  String version = "52106235e919b7830a2778af5a489be3";

  @override
  List<amplify_core.ModelSchema> modelSchemas = [
    Market.schema, // only 'Market' model will sync
  ];

  @override
  List<amplify_core.ModelSchema> customTypeSchemas = [];

  static final SubscriptionModelProvider _instance = SubscriptionModelProvider();

  static SubscriptionModelProvider get instance => _instance;
}`

Then initialise the Datastore plugin with this provider:

`   final datastorePlugin = AmplifyDataStore(modelProvider: SubscriptionModelProvider.instance);
    await Amplify.addPlugin(datastorePlugin);
`

This way you will still be able to use other models for query or mutation with direct AppSync API and the ones mentioned in this provider for realtime sync.

Cheers!

**Comment by osehmathias** [comment]
If you are trying to sync tables based on a user attribute after log in .... say, a clientID - I wrote a gist that simply explains a method that does this. 

https://gist.github.com/osehmathias/3506bffb38b0bed375e50620fd5a2dab
