### ISSUE TITLE
Authentication Type For Api

### ISSUE THREAD

**Issue by Abraham-EH** [aws-amplify/amplify-flutter#1557]
### Description

so basically as js library that have the authentication type for mutations we as flutter Developers need that , 
my users are creating on cognito and the owner auth is cognito so in flutter library is by default api and doesn't let me to decide as in js library and because of this i'm getting this err  Not Authorized to access updateUser on type Mutation

<img width="1680" alt="Screen Shot 2022-04-28 at 1 36 56 AM" src="https://user-images.githubusercontent.com/50684349/165631345-c73bc9ad-07cb-4e1d-9c76-dc07641d246e.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
.
```

### Dependencies

```bash
.
```

### Device

.

### OS

.

### CLI Version

.

**Comment by Jordan-Nelson** [comment]
@Abraham-EH - Thanks for taking the time to open this issue. I am going to mark this as a feature request since this is something Amplify-JS supports that Amplify-Flutter does not.

**Comment by ragingsquirrel3** [comment]
Hello, please note there is an open [RFC](https://github.com/aws-amplify/amplify-flutter/issues/2035) for changes to the API category in amplify-flutter with this being one of the proposed changes.

**Comment by ragingsquirrel3** [comment]
Hello  - We have recently released a new developer preview version of the API category ([amplify_flutter v1.0.0-next.1](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.1)). This new version is a full re-write of the API category in dart, and it supports Mobile, Desktop, and Web. The new version of the API category now has an `authorizationMode` property on `GraphQLRequest`s. You can see an example [in the docs](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes) at the bottom of the page. We will update this issue again when this version is out of developer preview.

Let me know if you have any questions!

**Comment by Jordan-Nelson** [comment]
Support for this was added in v1.0.0 of Amplify Flutter, which is now stable. See the comment above for a link to the docs.

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
