### ISSUE TITLE
How do I call methods from aws_signature_v4

### ISSUE THREAD

**Issue by juskek** [aws-amplify/amplify-flutter#1562]
I would like to perform an HTTP request signer for AWS Signature Version 4, as shown in the example here:
https://github.com/aws-amplify/amplify-flutter/tree/main/packages/aws_signature_v4

However, I can't use the following imports:
```
import 'package:aws_common/aws_common.dart';
import 'package:aws_signature_v4/aws_signature_v4.dart';
```

I am getting Target of URI doesn't exist.

**Comment by dnys1** [comment]
Hi @juskek - this package is not yet published to pub.dev, but will be in the near future.  Stay tuned and feel free to track this issue where we'll announce the release! #523
