### ISSUE TITLE
Appsync not syncing down after create mutation from lambda

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [aws-amplify/amplify-flutter#1577]
### Description

Hi, 

I've been stuck for a couple days trying to retrieve an entity created via a graphql call in a lambda function on my endpoint. 

When I create an entity A, it triggers a lambda function that creates an entity B and updates the newly created A. 
My user is connected via Cognito on the device and the lambda uses IAM. 

So far I get the lambda to create the entity B adding myself the "owner" (I created my own mutation in graphql.schema + resolver).

On the phone I see the update of A but not the creation of B. 

I think I don't understand how exactly the streams are supposed to work but anyway **I don't see B** in the logs. 

Am I suppose to query the new entity or is AppSync supposed to sync down the new entity ?

```
final Stream<SubscriptionEvent<Relationship>> _relationshipStream = Amplify.DataStore.observe(Relationship.classType);
Future<void> _observeRelationship() async {
    _relationshipStream.listen((event) {
      print('Received event of type ' + event.eventType.toString());
      print('Received settings ' + event.item.toString());
    });
  }
```

```
  late final StreamSubscription<GraphQLResponse<Relationship>> _createRelationshipStream;
  Future<void> _observeCreateRelationship() async {
    final subscriptionRequest = ModelSubscriptions.onCreate(Relationship.classType);
    final Stream<GraphQLResponse<Relationship>> operation = Amplify.API.subscribe(
      subscriptionRequest
    );

    _createRelationshipStream = operation.listen((event) {
        print('Subscription create relationship received: ${event.data}');
      },
    );
  }
```

```
  late final StreamSubscription _hubSubscription;
  Future<void> _observeDataStoreHub() async {
    _hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) async {
      print("HUB: " + msg.eventName);
    });
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
''
```

### Dependencies

```bash
''
```

### Device

''

### OS

''

### CLI Version

8.1.0

**Comment by HuiSF** [comment]
Hi @Simon-PumpAndUp , thanks for opening this issue.

Unfortunately, it is not officially supported that using AppSync API to operate DataStore. While DataStore is relying on AppSync as sync engine, and some use cases are working, some edge cases, however, may not work.

For your use case, you may need to take care a few things to ensure your design to work.

1. After writing model schema and deploying the schema, go to AppSync console, find the API you've added to use with DataStore
2. Navigate to schema section from the side menu
3. Read the compiled GraphQL schema closely, especially on the fields that are add for DataStore use cases, such as `_version`, `_deleted`, `_lastChangedAt` etc. And the input types that model subscription expect.
4. Make sure the selection sets of your GraphQL request documents contain all required fields, and all metadata fields added for DataStore
5. Make sure all nest model contain all required fields and metadata fields

**Comment by parad0x96** [comment]
@HuiSF I'm facing the same issue 
I'm currently doing mutations from an appsync client and returning all the selection set of the model including the nested fields,
I receive the subscription event and the data gets updated in real time but sometimes it doesn't get updated only after a log out of the user.

**Comment by HuiSF** [comment]
As this is a missing feature, I'm labeling this issue as a feature request.
Please feel free to follow up with detailed description of your use cases.

**Comment by Simon-PumpAndUp** [comment]
> Hi @Simon-PumpAndUp , thanks for opening this issue.
> 
> Unfortunately, it is not officially supported that using AppSync API to operate DataStore. While DataStore is relying on AppSync as sync engine, and some use cases are working, some edge cases, however, may not work.
> 
> For your use case, you may need to take care a few things to ensure your design to work.
> 
>     1. After writing model schema and deploying the schema, go to AppSync console, find the API you've added to use with DataStore
> 
>     2. Navigate to schema section from the side menu
> 
>     3. Read the compiled GraphQL schema closely, especially on the fields that are add for DataStore use cases, such as `_version`, `_deleted`, `_lastChangedAt` etc. And the input types that model subscription expect.
> 
>     4. Make sure the selection sets of your GraphQL request documents contain all required fields, and all metadata fields added for DataStore
> 
>     5. Make sure all nest model contain all required fields and metadata fields

I did all these steps: I pushed my schema, I can see it in the Appsync console. When I create my entity, my dynamodb stream is triggered and create the other entity (via appsync not boto3 -> dynamodb). The entity is in my table but I don't see it being sync down to my phone (even if I flush the datastore and sync it again). As if the owner field if not added from amplify is just not considered. 

So I'm even wondering if I create an entity like a message will it be sync to the receiver?

Sounds like a pretty basic use case to be able to create an entry and sync it down (and the all purpose of AppSync).

**Comment by HuiSF** [comment]
Hi @Simon-PumpAndUp I'm closing this issue now. Please feel free to follow up or reopen if you need further assistance.
