### ISSUE TITLE
Flutter Social sign in with Cognito web UI and Facebook policy

### ISSUE THREAD

**Issue by MMSaad** [aws-amplify/amplify-flutter#1579]
Followed all steps in this page for Facebook login with Web UI https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/

And app was working fine, the problem that after while Facebook disable the app since the callback only work on mobile devices and not on the web.

What's the best approach to solve this issue?

**Comment by cshfang** [comment]
Hi @MMSaad. Thanks for raising this issue.

> after while Facebook disable the app since the callback only work on mobile devices and not on the web.

Can you help me understand what exactly is happening? Are you building a web app via Flutter? What is the error you are seeing? What do you mean by "after a while"?

**Comment by MMSaad** [comment]
When create a Facebook application, it's required to add web site URL which is Cognito Hosted UI URL with callback like myapp://
Facebook considers this application as a normal web application and when they try it it's return to myapp://, Thus they disable the application.
Know it's not related to amplify but is there's any suggestions to how to handle this issue.

**Comment by cshfang** [comment]
Hmm I apologize but I am still not fully understanding. Please bear with me as I try to grasp your use case more clearly.

As I currently understand it, when you are creating your Facebook application, you are required to enter in a Site URL, is this where you are entering in `myapp://... `? By my knowledge, this ought to be the Cognito idpresponse endpoint (which *should* be a valid web URL)

Am I understanding your situation correctly or am I way off here? 😅

**Comment by HuiSF** [comment]
Hi @MMSaad are you able to resolve the issue following the doc?
(As what I read, there is no instructions setting `myapp://`) schemed url in Facebook settings page.

**Comment by haverchuck** [comment]
@MMSaad Just to confirm, you are adding your Cognito Hosted UI endpoint to the configuration on the Facebook (or Meta) developer console, like so? 

Site URL:  `https://<your-user-pool-domain>`
OAuth Redirect URI: `https://<your-user-pool-domain>/oauth2/idpresponse`

And then setting up the `myapp://` app domain in the Cognito console (or with the Amplify CLI)?

Basically, Facebook will redirect to Cognito Hosted UI, and then Cognito Hosted UI will return to your app.
