### ISSUE TITLE
How to use custom providers like with React Native?

### ISSUE THREAD

**Issue by ZRunner** [aws-amplify/amplify-flutter#1589]
### Description

Hello,

I'm looking to add authentication via custom providers to my Flutter app, as I did in another project in React Native.  
For this purpose I was able to configure Cognito to accept both Microsoft and LinkedIn authentications, and I can confirm that these authentications work on this side, but I have not been able to figure out how to implement them in Flutter despite many hours of searching.

I've seen that it's possible to not fill in any provider when calling `Amplify.Auth.signInWithWebUI()`, but this solution doesn't work for me, for some UX and aesthetic reasons.

Could you tell me how to use custom providers in a similar way to what exists in the JS library, if it is even possible? Thank you!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
- amplify_analytics_plugin_interface 0.4.5 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.5 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.4.5 [flutter]
- amplify_auth_cognito_ios 0.4.5 [amplify_core flutter]
- amplify_auth_plugin_interface 0.4.5 [flutter meta amplify_core]
- amplify_core 0.4.5 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.5 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.5 [flutter meta amplify_core]
```

### CLI Version

8.1.0

**Comment by Jordan-Nelson** [comment]
Hello @ZRunner - In your react native app, are you using identity pool federation ([docs](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#identity-pool-federation)) for this?

If so, this is not supported currently by Amplify-Flutter, but we do have a feature request for it here: https://github.com/aws-amplify/amplify-flutter/issues/1439.

> I've seen that it's possible to not fill in any provider when calling Amplify.Auth.signInWithWebUI(), but this solution doesn't work for me, for some UX and aesthetic reasons.

Yes, this should open the web UI with all the configured providers. Do you ming elaborating on some of the UX issues you faced with this? Do you not want to show all to configured providers, or did you have other UX issues in general with web UI?

**Comment by ZRunner** [comment]
> In your react native app, are you using identity pool federation ([docs](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#identity-pool-federation)) for this?

I was using `Auth.federatedSignIn({customProvider: 'Auth0-LinkedIn'})`, which seems to be what you are indeed describing (I'm still fairly new to all of this, sorry 😅)

> Do you not want to show all to configured providers, or did you have other UX issues in general with web UI?

Yup exactly, I have to customize a bit how to render the different login buttons, some may or may not appear depending on the context or just our moods, and there is indeed to a smaller degree the problem of opening a web page in addition to the already integrated Flutter page, which causes some redundancy (but I saw another ticket currently opened about that web UI "issue").

Just to make sure, there is currently no workaround to achieve what I'm looking for on Flutter, right? I only have to wait until some people implement this feature?

**Comment by Jordan-Nelson** [comment]
> Just to make sure, there is currently no workaround to achieve what I'm looking for on Flutter, right? I only have to wait until some people implement this feature?

Amplify-Flutter is built on top of Amplify-Android and Amplify-iOS, via flutter platform channels. Amplify-Android and Amplify-iOS do seem to support this (see [iOS docs](https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/)). You could in theory access these APIs via platform channels, but this is not a trivial amount of work, especially if you are not familiar with platform channels.

**Comment by haverchuck** [comment]
Related to #438
