### ISSUE TITLE
Multipart for upload lagre file

### ISSUE THREAD

**Issue by antonydieu** [aws-amplify/amplify-flutter#1601]
Hello
I use https://pub.dev/packages/amplify_storage_s3 for upload to S3. But when I upload with 2GB, speed network 9.42 Mbps. 
Please provide solution chuck file to upload faster.
Thanks

**Comment by HuiSF** [comment]
Hi @antonydieu thanks for opening this issue.

S3 multipart upload is automatically enabled when the uploaded file is larger than 5MB (Please see the discussion in issue https://github.com/aws-amplify/amplify-flutter/issues/1016).

What's the actual issue you are experiencing? Can you elaborate? Thanks.

**Comment by HuiSF** [comment]
Hi @antonydieu network throughput limits overall performance, if the network connection is slow, even with the multiparts upload, the overall progress will also be slow. This is out of control of Amplify libraries.

**Comment by offlineprogrammer** [comment]
Hi @antonydieu
 
I am closing this issue for now as we didn't hear from you 
We can reopen it if you are still facing the issue 

Regards
Mo
