### ISSUE TITLE
AWS Auth and Cognito (Username login): Forgot username and Restricting number of Signups per email

### ISSUE THREAD

**Issue by dkliss** [aws-amplify/amplify-flutter#1607]
### Description

I  have used AWS Auth for login and user management and password management.There are couple of items below, I cannot find in flutter AWS documentation:-

1) ISSUE 1: Do we have any API for forgot username? My sign up workflow includes a unique username with email ID and a verification code. I have used reset, update and forgot password functionality but not forgot username, which is an important aspect, when using a username for login.
2).ISSUE 2: I can currently sign up as many usernames using same email. Is there an API for me in current library where I can control how many username can be assigned to an email i.e. if I want to have a restriction on having one user name per email, is it achievable in current library?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Unable to find below items in AWS Flutter documents  1) Forgot username if sign up using username.  2) Restrict number of username allowed per user email.

### Screenshots

N/A

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
N/A
```

### Dependencies

```bash
#aws amplify
  amplify_flutter: ^0.5.0
  amplify_auth_cognito: ^0.5.0
  amplify_analytics_pinpoint: ^0.5.0
  #amplify_authenticator: ^0.1.0-rc.6
  amplify_datastore: ^0.5.0
  amplify_api: ^0.5.0
```

### Device

N/A

### OS

N/A

### CLI Version

8.2.0

**Comment by HuiSF** [comment]
Hi @dkliss thanks for the questions:

>ISSUE 1: Do we have any API for forgot username?

The Amplify Auth plugin currently doesn't provide "forgot username" API, as the solution varies depending on use cases for designs.

> ISSUE 2: I can currently sign up as many usernames using same email.

This is an expected behavior of Cognito. There is a way however, to make the email unique by enabling signing in with email alias.

When adding auth category using Amplify CLI, there is a step asking you "How do you want users to be able to sign in?"

<img width="689" alt="image" src="https://user-images.githubusercontent.com/10602282/169574783-0220a287-cbaa-4b1d-b969-8b963ff8f464.png">

At this step, you can choose option `Email`. This option will set email as a sign in alias in addition to username. Which makes email attribute to be unique in the user pool. Detailed explanation please see [this documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html), "Alias" section.

With setting `Email` as an alias, you can also gain a way to resolve issue 1. Where you can provide email attribute to reset the password in addition to username attribute. Detailed explanation please [this documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html).

**Comment by dkliss** [comment]
@HuiSF Thanks for your response. I will make an attempt and see if this works.

A question though. Where will I setup  an Alias on client side?

For example, below is my sign up flutter code. I was wondering, if I need to configure an Alias in under "options"? 

I can see that, "options" have parameters such as clientMetadata, Validation Data. Do I need to change anything for these to setup an Alias, which can be used for login?
 
![image](https://user-images.githubusercontent.com/45125636/169587292-05b891d4-0b05-49b3-ae4a-5e19cd7212ab.png)

**Comment by HuiSF** [comment]
>A question though. Where will I setup an Alias on client side?

This needs to be done when adding the Auth category using Amplify CLI @dkliss . Note that this option once set, you can't change it. So if you have created a user pool by adding auth category, you may need to recreate one.

Run
```
amplify add auth
```
When it prompts
```
How do you want users to be able to sign in?
```
choose `Email`

**Comment by dkliss** [comment]
Ok, thanks for this @HuiSF. What I understand is, no change to client side flutter sign up Code i.e., after I have setup Email based auth in Amplify, I shall be ale to  login both via username or email. I will try testing this in next few days.

**Comment by haverchuck** [comment]
Hello @dkliss  - were you able to test out the recommendation from @HuiSF?

**Comment by dkliss** [comment]
Hi, i had other project issues, which distracted me. I will get on this soon and should confirm in a fortnight, if the proposed  approach works.

**Comment by dkliss** [comment]
Hi @HuiSF @haverchuck 

I have done some testing on migrating my older username based login to email based login. I had attempted three different approaches as below.

My third attempt is successful and I can login now with Email. The issue I am having now is how to login with a username, which was what I was using before as my login as username is not available before Login (See Attempt 2).

What I was expecting that my the application to be able to do is able to login with both email or username i.e. a user can enter an email or username. Now with new approach, the username is generated by Amplify only after login and not before and hence I am restricted to only use Email as Login. 

Am I doing anything wrong or is there any alternative attribute  I need to use such as “preffered_username”? Please advice. 
 
Attempt 1: Unsuccessful. Attempting sign up with Email and then using “username” to confirm sign up. 
Step 1: amplify Sign Up with Email.
Step 2: Confirm Sign UP with username where username is retrieved as below:-
final _user = await Amplify.Auth.getCurrentUser();
AppLog.info('Logged in use is ${_user.username}');

This fails with exception
[log] [ERROR] [onConfirmationCodeSubmitted] Unknown Exception in sign confirmation bloc: AuthException(message: You are currently signed out. - Please sign in and reattempt the operation., recoverySuggestion: null, underlyingException: null)

This will create a user in Amplify User Management Tab though and shows as UnConfirmed. 

Attempt 2:  Unsuccessful. Attempting sign up with Email and then using “email” to confirm sign up.  And Login with username.
Step 1: amplify Sign Up with Email.
Step 2: Confirm Sign UP with ‘Email and Code.
Step 3: Login with username retrieved as below:-
final _user = await Amplify.Auth.getCurrentUser();
AppLog.info('Logged in use is ${_user.username}');

Login failed with error as below
[log] [ERROR] [onConfirmationCodeSubmitted] Unknown Exception in sign confirmation bloc: AuthException(message: You are currently signed out. - Please sign in and reattempt the operation., recoverySuggestion: null, underlyingException: null)


Attempt 3:  . Attempting sign up with Email and then using “email” to confirm sign up. Also Login with Email.
Step 1: amplify Sign Up with Email.
Step 2: Confirm Sign UP with ‘Email and Code.
Step 3: Login with Email.
Step 4: After Login, I am able to successfully retrieve username as below
final _user = await Amplify.Auth.getCurrentUser();
AppLog.info('Logged in use is ${_user.username}');

Login Successful with email as well as AWS auto generated username can be retrieved after  login.

**Comment by Jordan-Nelson** [comment]
@dkliss - flow number 3 would be the correct way to sign up & sign in with email based auth. Email is the login identifier in this scenario, so it should be used for sign up confirmation, login, forgot password, etc.

I believe the generated username you are getting back from getCurrentUser is really the user sub, not the username.

> What I was expecting that my the application to be able to do is able to login with both email or username

With email based auth, you can only sign in with email. I'm not aware of a way to configure Cognito Auth to allow two separate login identifiers (email or username). If this is what you are looking for, please let me know and I can confirm wether or not this is possible.

If you want to limit one account per email, the easiest way to do that is what to make email the login identifier, which is what you have done. This means that users will sign up and login with their email. The email address essentially becomes the username.

If you want users to be able to sign up and login with a username that is separate from their email you can use username as the login identifier, but by default Cognito will allow multiple accounts per email. If you want to keep username as the login identifier and still limit users to one account per email, this can be done via a Cognito lambda trigger that runs prior to sign up. The lambda would have to check if a user exists already with that email, and reject the sign up if there is a user already with that email. This is certainly more complex than the other option of changing the login identifier to email, but it is possible.

You can read about Cognito lambda triggers [here](https://docs.amplify.aws/cli/usage/lambda-triggers/). The type of trigger you would need to add is a pre-signup trigger. [Here is an example](https://github.com/aws-amplify/amplify-js/issues/369#issuecomment-369933670) of a pre-signup trigger that prevents users from signing up more than once with the same email.

**Comment by Jordan-Nelson** [comment]
Let us know if that answers your questions.

**Comment by dkliss** [comment]
Hi, other than above mentioned points, I also am having some differing results for Android  and iOS (iPhone 13, 15.5)emulator device 
When I run  Amplify.Auth.getCurrentUser() after migrating to Email based login.

ISSUE: Different outcomes for following function for iOS and Android.
Future<String> getCognitoUserName() async {
  AppLog.info('Attempting to get CognitoUserName',
      name: 'getCognitoUserName');
  try {
    final _cognitoUserName = await Amplify.Auth.getCurrentUser();
    AppLog.info('Current username is ${_cognitoUserName.username}');
    return _cognitoUserName.username;
  } on AmplifyException catch (e) {
    throw AmplifyException('${e.message} - ${e.recoverySuggestion}');
  }
}

Results of getUsername when Login in iOS 
[log] [INFO] [getCognitoUserName] Attempting to get CognitoUserName
[log] [INFO] [] Current username is 62bba74c-d99d-4768-98c3-3t68fbaada1e


Results of getUsername when Login in Android 
Every time I login, first I get exception below: 

[log] [ERROR] [onLoginSubmitted] AmplifyException(message: You are currently signed out. - Please sign in and reattempt the operation., recoverySuggestion: null, underlyingException: null)

And then on second attempt, I am getting an email address returned from the same function instead of a string like this 62bba74c-d99d-4768-98c3-3t68fbaada1e..

D/AWSMobileClient( 3390): getCredentials: Validated user is signed-in
[log] [INFO] [] Current username is abcdefj@gmail.com

I thought the two devices shall return same results unless I am doing something not correct.

I am using following packages.

amplify_flutter: ^0.5.1
amplify_auth_cognito: ^0.5.1
amplify_analytics_pinpoint: ^0.5.1
#amplify_authenticator: ^0.1.0-rc.6
amplify_datastore: ^0.5.1
amplify_api: ^0.5.1

**Comment by dkliss** [comment]
@Jordan-Nelson Thanks for your response to my previous query. For my use case, email based login should be good. I am still going through final testing and above issue was another one, which I wanted to know expected behaviour for await Amplify.Auth.getCurrentUser() i.e. would the "username" part will give me a AWS generated string (like iOS) or an email (like Android).

**Comment by Jordan-Nelson** [comment]
They are supposed to return the same value. However, there is a known bug that causes the "username" value from getCurrentUser to be different on iOS and Android. You can follow that bug here: https://github.com/aws-amplify/amplify-flutter/issues/201. I believe there are some work around snored in the comments of that issue.

Let me know if you have any other questions.
