### ISSUE TITLE
GraphQL mutate operation failed. NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}

### ISSUE THREAD

**Issue by anoopeashok** [aws-amplify/amplify-flutter#1612]
### Description

Graphql mutation operation fails in android but works in AppSync console

Error: 

GraphQL mutate operation failed
E/amplify:flutter:api( 4899): NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E/amplify:flutter:api( 4899):   at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:145)
E/amplify:flutter:api( 4899):   at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:flutter:api( 4899):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:api( 4899):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:api( 4899):   at java.lang.Thread.run(Thread.java:920)
W/AtomicResult(mutate)( 4899): Attempted to send success value after initial reply
I/flutter ( 4899): ApiException(message: OkHttp client request failed., recoverySuggestion: Irrecoverable error, underlyingException: null)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

code:

    final user = await Amplify.Auth.getCurrentUser();
    
    Product product = Product(
        name: 'Product1',
        description: "description",
        price: 20,
        type: ProductType.fruit,
        postType: PostType.sell,
        userID: user.userId);

    try {
      final req = ModelMutations.create(product);
      var res = await Amplify.API.mutate(request: req).response;
      print(res.data);
    } catch (e) {
      print(e.toString());
    }

Schema:

type User @model @auth(rules:[{allow:owner,operations:[create,update]}]){
  id: ID!
  name: String!
  email: String!
  product: [Product] @hasMany(indexName:"byUser",fields:["id"])
}

type Product @model @auth(rules:[{allow:owner,operations:[create,delete]}]) {
  id: ID!
  name: String!
  description: String!
  price: Int!
  type: ProductType! @index(name:"byProductType")
  postType: PostType! @index(name:"byPostType")
  userID: ID! @index(name:"byUser")
}

enum PostType{
  sell
  buy
}

enum ProductType{
  vegetable
  fruit
  spice
  other
}

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 31

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
amplify_flutter: ^0.4.5
  amplify_auth_cognito: ^0.4.5
  amplify_api: ^0.4.5
```

### Device

Pixel 3a

### OS

android 12

### CLI Version

8.2.0

**Comment by anoopeashok** [comment]
Any solution? should I change schema ?

**Comment by anoopeashok** [comment]
so I found the solution. Issue was regarding default authorisation mode

**Comment by akshatbhuhagal** [comment]
Issue is regarding default authorization mode which is API in your case, To Fix this issue you have to first update your Amplify API then Push those changes to Amplify.

Open terminal from your root/Amplify folder and then `amplify update api` ([Official docs][1]) and after completing it `amplify push`


Some other ways - Upgrade all the AWS Library/Packages & Update Amplify to new version by writing this command on terminal `amplify upgrade` (if any update is available)


  [1]: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/android/#use-amplify-cli-to-configure-authorization-modes
