### ISSUE TITLE
SyncExpression with id

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-flutter#1614]
### Description

Example models:

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  email: String!
 UserHistory: [UserHistory] @hasMany
}
type UserHistory @model @auth(rules: [{allow: public}]) {
  id: ID!
  info: AWSJSON
  user: User @belongsTo
}

Trying to add sync expression for logged in user. I can get User model to work if I pass User.EMAIL but User.ID is not working and failing with:

message='The variables input contains a field name 'user.id' that is not defined for input object type 'ModelUserFilterInput'

syncExpressions: [
        DataStoreSyncExpression(
          User.classType,
              () => User.ID.eq(cognitoId),
        ),
        DataStoreSyncExpression(
           UserHistory.classType,
               () => User.ID.eq(cognitoId),
          )

Can you guys have any suggestion? Is there some restriction on having ID in the filter expression? I also have issue with passing that same ID to UserHistory but that discussion is for later time :)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

Create a model

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  email: String!
 UserHistory: [UserHistory] @hasMany
}

Add filter expression based on ID following this documentation:
https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#reevaluate-expressions-at-runtime

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 32+

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
amplify_flutter: ^0.5.0
  amplify_api: ^0.5.0
  amplify_auth_cognito: ^0.5.0
  amplify_analytics_pinpoint: ^0.5.0
  amplify_datastore: ^0.5.0
```

### Device

N/A

### OS

N/A

### CLI Version

8.2.0

**Comment by HuiSF** [comment]
Hello @veeramneni thanks for reporting.

This is a known issue and we have implemented fixes for both amplify-flutter and amplify-codegen. We anticipate to roll out the fixes soon. 

Please follow https://github.com/aws-amplify/amplify-flutter/issues/1565 for updates. Thanks.
