### ISSUE TITLE
sync expression with relationships

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-flutter#1637]
### Description

Example models:

type User @model @auth(rules: [{allow: public}]) {
id: ID!
name: String!
email: String!
UserHistory: [UserHistory] @hasmany
}
type UserHistory @model @auth(rules: [{allow: public}]) {
id: ID!
info: AWSJSON
user: User @belongsto
}

My sync expression looks like this:

syncExpressions: [
DataStoreSyncExpression(
User.classType,
() => User.ID.eq(cognitoId),
),
DataStoreSyncExpression(
UserHistory.classType,
() => User.ID.eq(cognitoId),
)

This syncs User model fine but does not work for UserHistory. I do not get any errors, it just does not pull anything for UserHistory.

I came across this in amplify js:
https://github.com/aws-amplify/amplify-js/issues/7544

Probably related but does it mean this is not available for amplify flutter. If so, any suggestions on getting this to work? 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

Mentioned in the description

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 32+

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
amplify_flutter: ^0.5.0
  amplify_api: ^0.5.0
  amplify_auth_cognito: ^0.5.0
  amplify_analytics_pinpoint: ^0.5.0
  amplify_datastore: ^0.5.0
```

### Device

N/A

### OS

N/A

### CLI Version

8.2.0

**Comment by HuiSF** [comment]
Hi @veeramneni thanks for opening this issue. We will investigate this.

Looking at your examples, if I understood correctly, you were trying to sync models that matches `userId`.

This could lead to a performance hit on model subscription. As
* when DataStore does the base/delta sync (when the App cold starts), the sync expressions are used as sync query filter on the server side
* the model subscription, uses the sync expressions as a client filter

Look at your schema, this may happen, a device will receive subscription event on updates of every `User` and `UserHistory` record in your database. For this use case, DataStore will reevaluate sync expression on every single subscription event, and most the events may not be related to the currently signed in user. 

I recommend you to try owner based auth on the `User` and `UseHistory` models, with which you don't need sync expression, and DataStore will sync only records that are owned by currently signed user.

**Comment by veeramneni** [comment]
@HuiSF Awesome. It is exactly what I needed. Owner based auth reduces a lot of complexity at least in our use case and eliminates use of sync expression. I will be closing this. Thank you!

Just a thought but I do feel there will be some use cases which require child table with one to many relationship models having sync expression based on parent table. Probably something to think about for future releases.
