### ISSUE TITLE
Integration with databases - Dynamo

### ISSUE THREAD

**Issue by Macacoazul01** [aws-amplify/amplify-flutter#165]
It would be nice to have also the functions for saving/updating and getting data from dynamoDB, like firebase.

**Comment by fjnoyp** [comment]
Hi @Macacoazul01 we are currently working on including DataStore.  

We have a RFC open for the work we plan to do: 
https://github.com/aws-amplify/amplify-flutter/issues/160

**Comment by Ashish-Nanda** [comment]
@Macacoazul01 I'm going to go ahead and close out this issue as it is already tracked in the RFC #160 and we are actively working on it. We encourage you to share any feedback or comments there.
