### ISSUE TITLE
[GraphQL API] Field-level authorization rule seemingly ignored.

### ISSUE THREAD

**Issue by lfraker** [aws-amplify/amplify-flutter#1668]
### Description

Not sure if this is an incorrect configuration on my part or a lack of support for this feature in Amplify Flutter, but it seems like GraphQL API field-level authorization rules, which I would expect to override model-level auth rules are being ignored in a case where I attempted to make a field-level, rule read-only: https://docs.amplify.aws/cli/graphql/authorization-rules/#field-level-authorization-rules

I have the following object:
```graphql
type Couple @model(queries: { get: "getCouple" }, mutations: { create: "createCouple", update: "updateCouple", delete: "deleteCouple" }, subscriptions: null )
  @auth(rules: [
    { allow: owner, ownerField: "partners", operations: [read, update, delete] },
    { allow: private, provider: iam, operations: [create] }
  ])
  {
  id: ID!
  partners: [String!]! @auth(rules: [
      { allow: owner, ownerField: "partners", operations: [read] },
      { allow: private, provider: iam, operations: [create, read, update, delete] }
    ])
  activityCount: Int!
}
```

I would expect 'partners' to be only writable by iam - I update this property in backend Lambda functions that I trigger through in-app actions.

However, when logged in via User Pools, as an owner of the Couple object, I am able to still update this property. I would expect this to instead return an authorization error:
<img width="870" alt="Screen Shot 2022-06-01 at 1 09 09 PM" src="https://user-images.githubusercontent.com/5459537/171462378-52652d46-0102-412a-bb63-9e1f5f79a25b.png">

Is field-level authorization not supported in Flutter, or am I configuring this incorrectly? The documentation makes it seem like field-level auth rules should override model-level auth rules.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Deploy the model as indicated above.
2. Create an object of that model type.
3. Log in as a user that is an owner of that object.
4. Attempt to change the read-only field via the AppSync portal.

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
N/A
```

### Device

N/A

### OS

N/A

### CLI Version

5.3.1

### Additional Context

Excluding dependencies, because it's a long list and unnecessary/unrelated to the problem since the problem happens out-of-app as well.

**Comment by lfraker** [comment]
On another issue found that I'm using a dated version of Amplify CLI. Going through an upgrade now to see if this resolves the issue. Will request this to be closed if it does.

**Comment by haverchuck** [comment]
@lfraker Please confirm - you are seeing this behavior in the AppSync console, in addition to your Flutter application?

**Comment by lfraker** [comment]
@haverchuck I can confirm this had something to do with publishing with an older version of Amplify CLI. After migrating to the current version and Transformers v2 and republishing, I am now getting the expected unauthorized error in the AppSync Console. Sorry for the confusion, I'm closing this issue.
