### ISSUE TITLE
Document how to use query predicates with the API category

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#1695]
### Description

The current API (GraphQL) docs do not have any examples using query predicates. See the [docs on fetching data](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/flutter/).

Common use cases should be covered. For example:
- Basic equality operator: `Post.TITLE.eq(title)`
- Fetch by parent ID: `Post.BLOG.eq(blogId)`
- Comparions (gt, lt, etc.)

Docs were recently added the DS to include fetching by parent ID: https://github.com/aws-amplify/docs/pull/4353/files

There are some examples in our E2E tests. These should be cleaned up and simplified for the docs, but they can be used as a base to build on. https://github.com/aws-amplify/amplify-flutter/blob/main/packages/api/amplify_api/example/integration_test/graphql_tests.dart#L247-L262

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android

### Environment

```bash
N/A
```

### Dependencies

```bash
N/A
```

### Device

N/A

### OS

N/A

### CLI Version

N/A

**Comment by ragingsquirrel3** [comment]
I think we can close this issue as this was documented.
