### ISSUE TITLE
Adding endpoints from Flutter Amplify

### ISSUE THREAD

**Issue by cvalab** [aws-amplify/amplify-flutter#172]
I have configured Push notifications in Pinpoint
project. Test messages are successfully sent by specifying the Firebase token. How can I register an FCM token in Pinpoint? How do I add Adding endpoints from Flutter Amplify I'm trying to do it this way, but obviously it's not the right way.

`@override
  Future<void> upDateFcmToken(
      {@required String token, @required String userId}) async {
    debugPrint('@@@ upDateFcmToken userId=>$userId token=>$token ');
    final AnalyticsUserProfile analyticsUserProfile = AnalyticsUserProfile();

    final AnalyticsUserProfileLocation analyticsUserLocation =
        AnalyticsUserProfileLocation();
    analyticsUserLocation.latitude = 5;
    analyticsUserLocation.longitude = 5;
    analyticsUserLocation.postalCode = '94070';
    analyticsUserLocation.city = 'SanFrancisco';
    analyticsUserLocation.region = 'California';
    analyticsUserLocation.country = 'USA';

    analyticsUserProfile.location = analyticsUserLocation;

    final AnalyticsProperties analyticsProperties = AnalyticsProperties();
    analyticsProperties.addStringProperty('Address', token);
    //analyticsProperties.addStringProperty('OptOut', 'NONE');
    analyticsProperties.addStringProperty('ChannelType', 'FCM');

    analyticsUserProfile.properties = analyticsProperties;

    await Amplify.Analytics.identifyUser(
        userId: userId, userProfile: analyticsUserProfile);

    await Amplify.Analytics.flushEvents();
  }`

<img width="1212" alt="Снимок экрана 2020-11-03 в 12 05 03" src="https://user-images.githubusercontent.com/68106574/97981358-d6473900-1dda-11eb-8069-eb3f18144186.png">

**Comment by bostaginting** [comment]
Hi, any updates on how to Adding endpoints for notification pinpoint using FCM token?

**Comment by mannnish** [comment]
i want to update some data through update enpoints, using this code
```
                AnalyticsUserProfile analyticsUserProfile = new AnalyticsUserProfile();
                final AnalyticsProperties analyticsProperties = AnalyticsProperties();
                analyticsProperties.addDoubleProperty('wallet', 100);
                analyticsProperties.addStringProperty('login', 'google');
                analyticsUserProfile.properties = analyticsProperties;
                analyticsUserProfile.email = username;
                await Amplify.Analytics.identifyUser(userId: awsId, userProfile: analyticsUserProfile);
                await Amplify.Analytics.flushEvents();
```
the output says ```getCredentials: Validated user is signed-in```
but I cant see anything in the console
also is there any tab where i can see all the updateendpoint request in aws?

**Comment by offlineprogrammer** [comment]
Hi @cvalab 

You can add endpoints to Amazon Pinpoint by importing them from a CSV or JSON file.

![Screen Shot 2021-09-01 at 7 53 47 AM](https://user-images.githubusercontent.com/12375969/131694383-57e4da60-673d-43b4-a549-f7586629767b.png)


Regards
Mo

**Comment by mannnish** [comment]
> i want to update some data through update enpoints, using this code
> 
> ```
>                 AnalyticsUserProfile analyticsUserProfile = new AnalyticsUserProfile();
>                 final AnalyticsProperties analyticsProperties = AnalyticsProperties();
>                 analyticsProperties.addDoubleProperty('wallet', 100);
>                 analyticsProperties.addStringProperty('login', 'google');
>                 analyticsUserProfile.properties = analyticsProperties;
>                 analyticsUserProfile.email = username;
>                 await Amplify.Analytics.identifyUser(userId: awsId, userProfile: analyticsUserProfile);
>                 await Amplify.Analytics.flushEvents();
> ```
> 
> the output says `getCredentials: Validated user is signed-in`
> but I cant see anything in the console
> also is there any tab where i can see all the updateendpoint request in aws?

can anyone please revert on this?

**Comment by larinnim** [comment]
Please revert this. It's very important to have **updateEndpoint**

**Comment by aydemiromer** [comment]
is that enough for adm ? I wanna push notifications using ADM and flutter? How I can add endpoints?

**Comment by geoox** [comment]
Why is this issue closed? It's clear there is no adequate solution identified. 
It's 2022 and we are supposed to be importing tokens from JSONs just to be able to make use of the Pinpoint features?

As @larinnim mentioned we need the updateEndpoint method in the flutter library, similarly to how it is implemented for iOS and Android. I will be opening a new ticket to track this issue.

**Comment by parad0x96** [comment]
@cvalab  This won't work for you as there is a limit for the value of a custom attribute in pinpoint endpoint.
For instance:
android device tokens size exceeds 100 characters so when I tried to implement this the device_toke got truncated by pinpoint :)
Source 
https://docs.aws.amazon.com/pinpoint/latest/developerguide/quotas.html#quotas-endpoint
