### ISSUE TITLE
Datastore - Network Ready is not called when disconnect/connect device network (wifi, airplane)

### ISSUE THREAD

**Issue by yazoonic** [aws-amplify/amplify-flutter#1760]
### Description

I added the method below before calling amplify configure  yet it is being called when you start the app..  but when disconnect/connect network the status will be false and it will not come back to network ready

StreamSubscription hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (hubEvent) {
    if (hubEvent.eventName == 'networkStatus') {
        setState(() {
            networkIsUp = hubEvent.payload.active;
        });
    }
});

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. add listen to hub events for datastore 
StreamSubscription hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (hubEvent) {
    if (hubEvent.eventName == 'networkStatus') {
        setState(() {
            networkIsUp = hubEvent.payload.active;
        });
    }
});

2. lunch your app as normal and wait for network ready state 
3. disconnect wifi or put phone in airplane mode 
4. here, the network ready became false and app disconnect web socket and subscriptions. 
5. activate wifi again, nothing will happen and network ready will never be called. 

tested in physical android device 

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 29

### Environment

```bash
flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 3.0.2 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (8 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.9.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel XL (mobile) • HT6AD0202995 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos        • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

### Dependencies

```bash
Dart SDK 2.17.3
Flutter SDK 3.0.2


dependencies:
- amplify_api 0.5.1 [amplify_api_plugin_interface amplify_core amplify_api_android amplify_api_ios collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.5.1 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_auth_plugin_interface amplify_core collection flutter plugin_platform_interface]
- amplify_datastore 0.5.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.5.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- provider 6.0.3 [collection flutter nested]

transitive dependencies:
- amplify_analytics_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_api_android 0.5.1 [flutter]
- amplify_api_ios 0.5.1 [amplify_core flutter]
- amplify_api_plugin_interface 0.5.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.5.1 [flutter]
- amplify_auth_cognito_ios 0.5.1 [amplify_core flutter]
- amplify_auth_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_core 0.5.1 [collection date_time_format flutter meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.5.1 [flutter meta collection amplify_core]
- amplify_flutter_android 0.5.1 [flutter]
- amplify_flutter_ios 0.5.1 [amplify_core flutter]
- amplify_storage_plugin_interface 0.5.1 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- date_time_format 2.0.1
- json_annotation 4.5.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
```

### Device

Pixel 1

### OS

Android 10

### CLI Version

7.6.21

**Comment by HuiSF** [comment]
Hello @yazoonic thanks for opening this issue.

DataStore updates `networkStatus` not depending on network connection, i.e. DataStore does not detection network condition actively, but it attempts reconnect when DataStore APIs (start, save, delete, query, observe, observeQuery etc.) are invoked.

So if you hope to automatically restart DataStore syncing again when device is back online, you may need to implement the logic yourself. e.g. using [connectivity_plus](https://pub.dev/packages/connectivity_plus) to watch network connection state, when network goes offline and goes online again, invoke `Amplify.DataStore.start()` to resume datastore syncing.

**Comment by HuiSF** [comment]
Hi @yazoonic I wanted to follow up on this issue. Does my last comment make sense to you? Please let me know if you need further help.

**Comment by yazoonic** [comment]
@HuiSF  I fixed it using connectivity plus package(thank you). However; this is not the same behavior  when I used AWS amplify for IOS..

my current app in IOS is checking network ready without restart datastore (as far as I remember) ..

**Comment by HuiSF** [comment]
Which version of amplify-ios you are using for your native iOS App? @yazoonic

**Comment by yazoonic** [comment]
@HuiSF  1.19.2

**Comment by HuiSF** [comment]
Hum OK, all sync engine functionality and low level network communication in amplify-flutter depend on amplify-ios, it should be exactly the same behavior as amplify-ios. 

DataStore syncing is resumed on any DataStore API call as well in amplify-ios.

**Comment by yazoonic** [comment]
@HuiSF I think you can close the issue till I verify again the behavior on my ios app.. but this will take time maybe next month.

**Comment by HuiSF** [comment]
Thanks @yazoonic that sounds good.
Please feel free to reach out anytime if anything that I can help with. 👍
