### ISSUE TITLE
[iOS] Amplify.Auth.fetchAuthSession() sessionToken is null

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#178]
Hi,

my code to get the session:

```
  Future<bool> getSessionFromAmplify() async {
    try {
      session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));

      return true;
    } on AuthError catch (e) {
      return false;
    }
  }

```
The returned CognitoAuthSession has a valid awsAccess & SecretKey but the sessionToken is just null. On Android its working fine. Is this just not implemented, is it a bug or is there an option for getting the sessionToken on iOS?

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone:**
 - Device: [Simulator iPhone 11 Pro / Hardware iPhone X ]
 - OS: [iOS 14]

**Comment by Rayv1** [comment]
Any Updates on this? Is the behaviour reproducible?

**Comment by haverchuck** [comment]
@Rayv1 Do you have an identity pool configured?

**Comment by mdridley** [comment]
I am having the same issue. Possible that some of the PRs will fix... but even though they are merged, we are two months since the last push.

**Comment by mdridley** [comment]
Latest update still has the issue?

**Comment by haverchuck** [comment]
@mdridley  - What is the result you are seeing from the fetch session request (please redact sensitve information)?

**Comment by haverchuck** [comment]
@Rayv1 Have you been able to test the new version?

**Comment by Rayv1** [comment]
@haverchuck yep, its fixed! Thanks!
