### ISSUE TITLE
How to refresh the token ?

### ISSUE THREAD

**Issue by FirdousNath** [aws-amplify/amplify-flutter#186]
Whenever I am using rest Api it works fine for certain time period but after that it gives
` {"message":"The security token included in the request is expired"}`
I need to manually logout from app and re-login back. Then it works again but is there any way to refresh token automatically ?

**Comment by haverchuck** [comment]
@FirdousNath You are using the Amplify.Auth category for flutter to manage authentication?  Which platform are you seeing this behavior on?

**Comment by Rayv1** [comment]
@FirdousNath i had the same Issue and and since then, iam doing 
```
      session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));
```
before every API call. The Issue is fixed with it.

@haverchuck is this the right "workflow" to refresh a Session?

**Comment by FirdousNath** [comment]
> @FirdousNath You are using the Amplify.Auth category for flutter to manage authentication? Which platform are you seeing this behavior on?

Yes & this is seen on both  Android emulator and physical devices

**Comment by FirdousNath** [comment]
> await Amplify.Auth.fetchAuthSession(
>           options: CognitoSessionOptions(getAWSCredentials: true));

Thanks alot , this trick works for me too. But I am only doing `Amplify.Auth.fetchAuthSession` when actually token get expired. So its saves time & network usage.

**Comment by jamesonwilliams** [comment]
The intended behavior for Amplify Auth is to automatically handle token refreshes. Calling `Amplify.Auth.fetchAuthSession(...)` is a work-around for a bug in Amplify Android. It should not be included in the documentation, Amplify Android should fix the bug.

**Comment by vasilich6107** [comment]
@jamesonwilliams do you know a link to the corresponding `Amplify Android` issue to track when it will be fixed?

**Comment by ekoto4** [comment]
> @FirdousNath i had the same Issue and and since then, iam doing
> 
> ```
>       session = await Amplify.Auth.fetchAuthSession(
>           options: CognitoSessionOptions(getAWSCredentials: true));
> ```
> 
> before every API call. The Issue is fixed with it.
> 
> @haverchuck is this the right "workflow" to refresh a Session?

Not sure if I'm missing something for the work around but I can't get this to work. I'm getting a ```SessionExpiredException``` with a token expiration of 60 minutes and a refresh token expiration of 30 days. Right now I'm calling ``` fetchAuthSession(
>           options: CognitoSessionOptions(getAWSCredentials: true)) ``` before every request. Could anybody guide me here?

**Comment by CamronLDNF** [comment]
> @FirdousNath i had the same Issue and and since then, iam doing
> 
> ```
>       session = await Amplify.Auth.fetchAuthSession(
>           options: CognitoSessionOptions(getAWSCredentials: true));
> ```
> 
> before every API call. The Issue is fixed with it.

I'm facing the same issue and this workaround fixed it. After a certain time, calling just Amplify.Auth.fetchAuthSession() does not refresh the tokens. Not sure what @jamesonwilliams meant with this being a bug in `Amplify Android` -- I'm getting this issue in using `Amplify Flutter`, not `Amplify Android`.

**Comment by jamesonwilliams** [comment]
> Not sure what @jamesonwilliams meant with this being a bug in Amplify Android -- I'm getting this issue in using Amplify Flutter, not Amplify Android.

Amplify Flutter is [built on top of Amplify Android](https://github.com/aws-amplify/amplify-flutter/blob/c773828dd91ded62e25eece9b8945f07fa551957/packages/amplify_auth_cognito/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/AuthCognito.kt#L318).

**Comment by FirdousNath** [comment]
> > @FirdousNath i had the same Issue and and since then, iam doing
> > ```
> >       session = await Amplify.Auth.fetchAuthSession(
> >           options: CognitoSessionOptions(getAWSCredentials: true));
> > ```
> > 
> > 
> > before every API call. The Issue is fixed with it.
> 
> I'm facing the same issue and this workaround fixed it. After a certain time, calling just `Amplify.Auth.fetchAuthSession()` does not refresh the tokens. Not sure what @jamesonwilliams meant with this being a bug in `Amplify Android` -- I'm getting this issue in using `Amplify Flutter`, not `Amplify Android`.

I am also getting a issue when tokens aren't getting refreshed. So I put the `session = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));` inside **try catch.** So when amplify is not able to provide refresh token it throws an error caught by my catch block and  from that I am simply redirecting user to login page.

**Comment by hassan1709** [comment]
Hey, so it looks like this is an issue they are planning to fix as this thread is still open?

**Comment by Jordan-Nelson** [comment]
Hello all - It looks like this issue fell off of our radar, but I am looking into it.

I wasn't able to reproduce this in the latest version of amplify-flutter on an Android device. In a sample app with refresh tokens set to 60 minutes and access/ID tokens set to 5 minutes, I was able to continually call Amplify.API.get() and Amplify.API.put() every few minutes for 60 minutes straight. The Access/ID tokens seemed to be getting refreshed for the full 60 minutes that the refresh token is valid for.

Could anyone that is still experiencing this issue post what version of amplify-flutter is being used in your app and provide some minimal reproduction steps?

Just to clarify the expected behavior, if the refresh token is still valid, the access and ID token should automatically refresh. Once the refresh token is expired, there is no way to refresh it without re-authenticating the user. Cognito allows the refresh token to be set to expire anywhere between 60 minutes and 3,650 days, and the access/ID tokens can be set to expire anywhere between 5 minutes and 1 day.

**Comment by Jordan-Nelson** [comment]
@FirdousNath @Rayv1 @ekoto4 @CamronLDNF - If you are still experiencing this issue can you please share what version of amplify-flutter you are using and provide minimal repro steps? Thank you.

**Comment by Fernandomr88** [comment]
any news on that?

**Comment by airon-tark** [comment]
@Jordan-Nelson 

This is still an issue
reproducing on `amplify_flutter: ^0.6.8`

- Using amplify google auth
- Refresh token set for 60 min
- Access and id tokens set for 5 min
  <img width="315" alt="Снимок экрана 2022-10-11 в 17 05 20" src="https://user-images.githubusercontent.com/54197112/195113461-82b95d3d-df74-4194-8e53-4ddf78edfd78.png">


- Make an API call
- Wait for 7 minutes
- Request for the session as a workaround (it doesn't help)
```
final session = await Amplify.Auth.fetchAuthSession(
  options: CognitoSessionOptions(
    getAWSCredentials: true,
  ),
);
final tokens = (session as CognitoAuthSession).userPoolTokens;
```
- make another API call 
- Get `NotAuthorizedException`

**Comment by radumunteadevm8** [comment]
I face the same issue

**Comment by tushkaty** [comment]
I wonder why this is ignored. `await Amplify.Auth.fetchAuthSession()` Doesn't return the tokens and `await Amplify.Auth.fetchAuthSession(
              options: CognitoSessionOptions(getAWSCredentials: true))` makes an api call to get the tokens from user pools. Not a good implementation by team.

**Comment by Jordan-Nelson** [comment]
Hey folks - Apologies for missing the responses here. We don't frequently check for updates on closed issues. You can always create a new issue if you are experiencing an issue related to something that was previously closed.

I will re-open this since it sounds like several people are still experiencing this issue, or a related issue. It sounds like there are two issues that are being observed:
1. Access/ID tokens are not refreshed automatically as they should be when the refresh token is expired
2. Manually refreshing the tokens does not work, even if they are expired.

I had previously unsuccessfully attempted to reproduce issue 1. I will try attempt to reproduce this again with Google sign in, as that appears to be the only difference between my previous reproduction and what @airon-tark had listed in the repro steps (thank you @airon-tark for providing those).

**Comment by vgribok** [comment]
@Jordan-Nelson I am having this problem right now with Dev Preview (`1.0.0-next.2+1` auth lib), and it's seemingly affecting the app on Android only. FYI, I am avoiding getting credentials as I don't need them for my app's purposes, and adding them to the call does not make the problem go away.

**Comment by sourabhguptazeil** [comment]
We are facing the similar issue. Amplify authentication module doesn't return the new access token using refresh token. The details are

### Login methods are affected

1. Login with email
2. Sign in with google
3. Sign in with Apple

### The expiration time set in Cognito for all tokens (access, id, refresh)

1. Refresh token expiry is 180 days
2. Access token expiry is 1 day

### How long after login the exception is occurring

Generally it occurs when 24 hours are passed

### How do we access the token

```
Future<String?> fetchIdentityToken() async {
    final result = await Amplify.Auth.fetchAuthSession(
          options: const FetchAuthSessionOptions());
   String? identityId = (result as CognitoAuthSession)
          .userPoolTokensResult
          .valueOrNull
          ?.idToken
          .raw;
   return identityId;
}
```

### What exception are they seeing
```
  "isSignedIn": false,
  "userSub": "AWSResult [null, SignedOutException {\n  \"message\": \"No user is currently signed in\"\n}, AWSResultType.error]",
  "userPoolTokens": "AWSResult [null, SignedOutException {\n  \"message\": \"No user is currently signed in\"\n}, AWSResultType.error]",
  "credentials": "AWSResult [null, SessionExpiredException {\n  \"message\": \"The AWS credentials could not be retrieved\",\n  \"recoverySuggestion\": \"Invoke Amplify.Auth.signIn to re-authenticate the user\",\n  \"underlyingException\": \"NotAuthorizedException {\\n  message=Unauthenticated access is not supported for this identity pool.,\\n}\"\n}, AWSResultType.error]",
  "identityId": "AWSResult [null, SessionExpiredException {\n  \"message\": \"The AWS credentials could not be retrieved\",\n  \"recoverySuggestion\": \"Invoke Amplify.Auth.signIn to re-authenticate the user\",\n  \"underlyingException\": \"NotAuthorizedException {\\n  message=Unauthenticated access is not supported for this identity pool.,\\n}\"\n}, AWSResultType.error]"
}
```

**Comment by Jordan-Nelson** [comment]
@sourabhguptazeil - Thanks for the info. The exceptions you shared are consistent with the expected experience if there was no user logged in. The exceptions indicate that the tokens are not present in device storage I think it makes sense to treat this as a separate issue. Can you create a new issue [here](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=BUG-REPORT.yaml)?

Please be sure to include what device(s) you have observed this on, and reproduction steps if this issue is reproducible. If you do not have reproduction steps (for example, if this was reported by end users, but you do not have clear steps to repro) please note this in the issue.

**Comment by Jordan-Nelson** [comment]
I am unable to reproduce this on either iOS or Android using the reproduction steps from @airon-tark. 

If anyone is still experiencing this, can you please provide the following:
- Reproduction steps (if different than what was provided in https://github.com/aws-amplify/amplify-flutter/issues/186#issuecomment-1274748280)
- Platform(s) (iOS/Android) you are experiencing this on
- amplify_flutter version
- Frequency. Is this reproducible 100% of the time for all users/devices? Does this only occasionally surface?

**Comment by sourabhguptazeil** [comment]
> I am unable to reproduce this on either iOS or Android using the reproduction steps from @airon-tark.
> 
> If anyone is still experiencing this, can you please provide the following:
> 
> * Reproduction steps (if different than what was provided in [How to refresh the token ? #186 (comment)](https://github.com/aws-amplify/amplify-flutter/issues/186#issuecomment-1274748280))
> * Platform(s) (iOS/Android) you are experiencing this on
> * amplify_flutter version
> * Frequency. Is this reproducible 100% of the time for all users/devices? Does this only occasionally surface?

1. Same Reproduction steps (Provided in https://github.com/aws-amplify/amplify-flutter/issues/186#issuecomment-1274748280)
2. Issue occurs on both android and ios
3. Amplify flutter version is `amplify_flutter: ^1.0.0-next.7`
4. Yes, reproducible 100% of the time for all users/devices

**Comment by Jordan-Nelson** [comment]
@sourabhguptazeil - can you please create a separate issue for this using the link I shared above? Based on the logs you shared, it sounds like a separate issue. The issue that has been reported in this thread is that fetchAuthSession() returns an expired token. From the logs you shared, there is no token returned. While the result is similar (user is effectively logged out) it is likely a different root cause and will require a different fix.

**Comment by sourabhguptazeil** [comment]
> @sourabhguptazeil - can you please create a separate issue for this using the link I shared above? Based on the logs you shared, it sounds like a separate issue. The issue that has been reported in this thread is that fetchAuthSession() returns an expired token. From the logs you shared, there is no token returned. While the result is similar (user is effectively logged out) it is likely a different root cause and will require a different fix.

@Jordan-Nelson New issue is created https://github.com/aws-amplify/amplify-flutter/issues/2808

**Comment by Jordan-Nelson** [comment]
I am going to close this out since I have not heard back for some time. If you are able to reproduce this, please let me know and we can reopen the issue.

**Comment by adamtester** [comment]
Hello @Jordan-Nelson I have run into the same issue, I'm using Cognito (email if that helps) and the tokens aren't refreshing.

Here is a snippet of code:
```dart
  Future<List<Project>> load() async {
    var auth = await Amplify.Auth.fetchAuthSession();
    var user = await Amplify.Auth.getCurrentUser();
    safePrint(auth);
    safePrint(user);

    if (Amplify.isConfigured) {
      safePrint('Amplify is configured');
    } else {
      safePrint('Amplify is NOT configured');
      return [];
    }

    try {
      List<Project> projects = [];

      final request = ModelQueries.list(Project.classType);
      final response = await Amplify.API.query(request: request).response;
...
```

The console output is:
```
I/flutter (29471): {
I/flutter (29471):   "isSignedIn": true,
I/flutter (29471):   "userSub": "AWSSuccessResult<String, AuthException> {\n  \"value\": \"5c79fc58-xxx-f3476c7feeb6\"\n}",
I/flutter (29471):   "userPoolTokens": "AWSSuccessResult<CognitoUserPoolTokens, AuthException> {\n  \"value\": {\n    \"signInMethod\": \"default$\",\n    \"accessToken\": \"eytokenhere
I/flutter (29471): CognitoAuthUser {
I/flutter (29471):   "userId": "5c79fc58-xxx-f3476c7feeb6",
I/flutter (29471):   "username": "5c79fc58-xxx-f3476c7feeb6",
I/flutter (29471):   "signInDetails": {
I/flutter (29471):     "signInType": "apiBased",
I/flutter (29471):     "username": "xxx@gmail.com",
I/flutter (29471):     "authFlowType": "USER_SRP_AUTH"
I/flutter (29471):   }
I/flutter (29471): }
I/flutter (29471): Amplify is configured
I/flutter (29471): query
I/flutter (29471): GraphQLResponse<PaginatedResult<Project>> error: [
I/flutter (29471):   {
I/flutter (29471):     "message": "Token has expired.",
I/flutter (29471):     "errorType": "UnauthorizedException"
I/flutter (29471):   }
I/flutter (29471): ]
```

I decoded that JWT and it has indeed expired.

Pubspec
```
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_api: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_storage_s3: ^1.0.0
```

This is testing on Android in a simulator

Let me know if I can provide more info!
