### ISSUE TITLE
Unable to retrieve Authorization Code after social sign on.

### ISSUE THREAD

**Issue by Desync-o-tron** [aws-amplify/amplify-flutter#1865]
I've configured my app to let me sign in and sign out. I can see logins on my AWS user pool and for the currently signed in user, I can see my username and id with your Flutter API. However, using this library, I cannot access the Authorization Code that is normally returned in the HTTP response on sign-in.

Normally, I can get this code with a get request like this: `https://xxx-temp.auth.us-east-1.amazoncognito.com/login?client_id=3fj3Ukrlvjssd1t3juljapqk5&response_type=code&scope=openid+profile&redirect_uri=fsdfrontend://`
If the user signs in successfully, the response's header will contain: `Request URL: fsdfrontend://?code=f8fa4Uc6-bb72-47e8-b8ff-a625c7aad6de`

This can be verified to work if I open up my AWS console > Cognito > 'my user pool' > app client settings > 'my front end app client' > launch hosted UI
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/35696371/178175052-00003a59-3b09-49e0-b375-ce18a9388001.png">

However, when I do the equivalent in this Flutter Amplify library, regardless of whether I'm using Google or Facebook, no useful data is returned in the sign-in call, as can be seen in the debugger locals on the left.
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/35696371/178175465-68f02396-fdc7-4e28-8252-14b8a4656a10.png">

So, how can I get this auth code with your library? I need this code to work with my serverside app. And this aws blog recommends the pattern: https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/

**Comment by haverchuck** [comment]
@Desync-o-tron - We'd like to understand your use case a little better. How do you plan on using the authorization code that is part of the OAuth process here? The signIn API will cause User Pool Tokens and (if you're using an identity pool) AWS Credentials to be cached locally, which you can then use sign to requests. What is the authorization code for?

**Comment by dnys1** [comment]
Hi @Desync-o-tron, the authorization code is captured by the iOS/Android libraries and immediately exchanged for access, refresh and ID tokens with your user pool. Since these access codes are meant to be short-lived and are intended only for direct exchange for tokens, exposing the authorization code is not supported in the library. As Dustin mentioned, please feel free to share your use case - we are always open to suggestions. 

However, I don't believe we have any current or future intentions to expose the auth code for the reasons outlined.

**Comment by Desync-o-tron** [comment]
That makes sense, thank you.
