### ISSUE TITLE
Uploading file S3 bucket works on debug but crash on prod

### ISSUE THREAD

**Issue by vvjathavadekar** [aws-amplify/amplify-flutter#188]
I have tested many times but app works properly on debug mode but when I generate prod build for flutter, then while testing app keeps crashing as I tries to upload new file! 

I m using this fun to upload 

 `void _upload(BuildContext context) async {
try {
      ProgressDialog.showProgressDialog(context);
      print('In upload');
      // Uploading the file with options
      File local = File(widget.videoPath);
      local.existsSync();
      final key = new DateTime.now().toString();
      Map<String, String> metadata = <String, String>{};
      metadata['name'] = key;
      metadata['desc'] = 'A video file';
      S3UploadFileOptions options = S3UploadFileOptions(
          accessLevel: StorageAccessLevel.guest, metadata: metadata);
      UploadFileResult result = await Amplify.Storage.uploadFile(
          key: key, local: local, options: options);
    } catch (e) {
      Navigator.pop(context);
      showInSnackBar('Unable to upload video');
      print('UploadFile Err: ' + e.toString());
    }
  }`

now this function works proper on debug but crash on prod. I tried to check log but prod build does not give any logs. I will try to get some logs on rooted phones but meanwhile if anyone knows about this issue please let me know

**Comment by jamesonwilliams** [comment]
If your app is crashing, that will definitely show up in the device logs. Look closer, and please include the logs from the crash.

Was this on Android or iOS? Whenever there is an issue like this, where a debug build is functioning, but a prod build does not, Android's R8 shrinker could be to blame. Update your ProGuard rules configuration file, so that the needed components aren't being stripped out.

**Comment by Amplifiyer** [comment]
@vvjathavadekar This should have been fixed in the latest release of Amplify 0.0.2-dev.2. Please test and let us know if you face any issues.
