### ISSUE TITLE
Authenticator banner text is misaligned on large screen sizes

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#1898]
### Description

Banner text should be aligned with the icons, but appears too close to the top currently.

<img width="912" alt="Screen Shot 2022-07-19 at 5 57 49 PM" src="https://user-images.githubusercontent.com/24740863/179872963-65e38584-5f4f-4dd3-81c7-cc44cdea5c90.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Trigger an error on a large screen size

### Platforms

- [ ] iOS
- [ ] Android

### Environment

```bash
`next`
```

### Dependencies

```bash
N/A
```

### Device

macOS

### OS

12

### CLI Version

N/A

**Comment by dnys1** [comment]
Also, should the banner be a different color/symbol for errors? Right now, it's the same for all messages.

**Comment by Jordan-Nelson** [comment]
This have been addressed in our developer preview version.
