### ISSUE TITLE
Auth.resendUserAttributeConfirmationCode throws an error (Flutter)

### ISSUE THREAD

**Issue by adityadua24** [aws-amplify/amplify-flutter#1907]
### Description

When 
```
resendUserAttributeConfirmationCode(userAttributeKey: CognitoUserAttributeKey.phoneNumber);
```

is called on a new user with unverified phone. The following error message is shown 

Exception has occurred.
UnknownException (UnknownException(message: Unexpected error occurred with message: An unknown error occurred, recoverySuggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/adi/Desktop/skulptnet/practitioner/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80, underlyingException: The operation couldn’t be completed. (com.amazonaws.AWSCognitoIdentityProviderErrorDomain error 37.)))

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

With Cognito pool configured to login with email or phone.

1) Execute:-
```
final result = await Amplify.Auth.signUp(
        username: email, // Add support for phone number
        password: password,
        options: CognitoSignUpOptions(userAttributes: {email: email, phone: phone}),
      );
```
2) Execute resendUserAttributeConfirmationCode(userAttributeKey: CognitoUserAttributeKey.phoneNumber);

The code throws an error

### Screenshots

![image](https://user-images.githubusercontent.com/17780921/180074644-77bc28a8-61d8-41fc-84ba-2efed3c41ab6.png)

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.17.6
Flutter SDK 3.0.5
practitioner 1.0.0+1

dependencies:
- amplify_auth_cognito 0.6.2 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_flutter 0.6.2 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- get_it 7.2.0 [async collection]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- provider 6.0.3 [collection flutter nested]

transitive dependencies:
- amplify_auth_cognito_android 0.6.2 [flutter]
- amplify_auth_cognito_ios 0.6.2 [amplify_core flutter]
- amplify_core 0.6.2 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.2 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.2 [flutter]
- amplify_flutter_ios 0.6.2 [amplify_core flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.2 [meta path]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.16 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.0 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

Iphone 13

### OS

ios 15.4

### CLI Version

9.1.0

**Comment by dnys1** [comment]
Hi @adityadua24, sorry you are experiencing this issue. Would you be able to share your amplify config (scrubbed of any identifying info)? One reason this could fail is if you don't have an SMS configuration enabled in your user pool. You could see if this is the case by looking on the `Messaging` tab of your user pool and seeing if an SMS ARN is present like this:
<img width="1559" alt="Screen Shot 2022-07-25 at 2 54 41 PM" src="https://user-images.githubusercontent.com/24740863/180880468-bd3cbe1f-36d9-4431-8e9a-04c126c09dc5.png">

**Comment by adityadua24** [comment]
> 
I do have an IAM role configured for Messaging. I have pasted my amplify config below

```
const amplifyConfig = '''{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {"Default": {}},
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "",
              "Region": ""
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "",
            "AppClientId": "",
            "AppClientSecret": "",
            "Region": ""
          }
        }
      }
    }
  }
}''';
```

**Comment by dnys1** [comment]
Okay, that's good. And the result of signUp is successful? Is the value of `result.nextStep.signUpStep` equal to `DONE`? If it's anything but `DONE`, the user wouldn't be fully logged in yet.

**Comment by adityadua24** [comment]
Shouldn't i still be able to invoke resendUserAttributeConfirmationCode even if the user is not yet confirmed (since the message itself is needed to confirm the user) ?

**Comment by dnys1** [comment]
Ah, yeah sorry for the confusion. For resending verification codes during sign up, you need to use `resendSignUpCode` instead, which will send the code to either the email or phone, depending on which was configured as the verification mechanism in your user pool.

**Comment by dnys1** [comment]
@adityadua24 - I'm closing this ticket for now but please let me know if you face any other issues
