### ISSUE TITLE
Sign in page fails with AWScognitoAuthErrorDomain error -3000 in iOS simulator with Google provider

### ISSUE THREAD

**Issue by Sancho66** [aws-amplify/amplify-flutter#1920]
### Description

I develop 2  front end app on vueJS and flutter and I use Amplify for authentication.
Currently, I have as SignInRedirectURI:
"SignInRedirectURI": "http://localhost:8080/, myapp://"

This is working as expected on VueJs with "http://localhost:8080/" as redirect URI. 
However, it fails to load the sign in page in iOS iPhone 12 Pro simulator.

I have also added the following in the plist file

```
<array>
         <dict>
             <key>CFBundleURLSchemes</key>
             <array>
                 <string>myapp</string>
             </array>
         </dict>
     </array>
```

This give the below exception.
"The operation couldn't be completed. (com.amazon.cognito.AWScognitoAuthErrorDomain error -3000.)"

How do I make the SignInRedirectURI load in iOS?
I tried many redirect URI without success... 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [x] iOS
- [ ] Android

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
- amplify_auth_cognito_android 0.6.2 [flutter]
- amplify_auth_cognito_ios 0.6.2 [amplify_core flutter]
- amplify_core 0.6.2 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.2 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.2 [flutter]
- amplify_flutter_ios 0.6.2 [amplify_core flutter]
```

### Device

Iphone12

### OS

iOS15

### CLI Version

9.1.0

**Comment by dnys1** [comment]
Hi @Sancho66 - I believe this is due to the fact that the iOS/Android libraries currently use the first URI in the `SignInRedirectURI` array.

> I tried many redirect URI without success...

Can you elaborate what you mean by this?

**Comment by Sancho66** [comment]
Hi @dnys1 , 

Finally I found my error, I created the user pool and the identities federation with Terraform ( I'm not so fan of the kind of 'magic' behind amplify commands) and I use amplify libs on the front end ( I import my Cognito config only). 
I've just forgotten to add "Authorization code grant" in OAuth2.0 section for the customer app.

<img width="575" alt="Capture d’écran 2022-07-25 à 23 42 12" src="https://user-images.githubusercontent.com/9716220/180878997-9f2126f9-699a-4260-8474-3141c4d1fa8e.png">

And with many SignInRedirectURI it also works 👍

**Comment by dnys1** [comment]
Thanks for following up, @Sancho66. Glad to hear you resolved it.

> And with many SignInRedirectURI it also works 👍

And good to know, thanks! :D

**Comment by Sancho66** [comment]
Your are most welcome !  ;)
