### ISSUE TITLE
When I try to do google/ facebook sign in , it doesn't go back to the app after successful login. It redirects to the SignInRedirect Url

### ISSUE THREAD

**Issue by shakilhossain38** [aws-amplify/amplify-flutter#1925]
When I try to do google/ facebook sign in , it doesn't go back to the app after login. It redirects to the SignInRedirect Url

**Comment by dnys1** [comment]
Hi @shakilhossain38 - I believe that's working as expected. The `SignInRedirectUri` field indicates where to return the user after sign in. Have you walked through the [docs](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#how-it-works) for setting up a custom URI scheme?

**Comment by shakilhossain38** [comment]
@dnys1 thanks. I was missing android:sheme.
