### ISSUE TITLE
GraphQL mutations issues when using the Map in flutter.

### ISSUE THREAD

**Issue by selva-harivara** [aws-amplify/amplify-flutter#1937]
### Description

We are using custom mutations query in flutter. we are facing the some issues in using the Map value ( object ).

createWalletContent() async {

    try {

      String graphQLDocument =

          '''mutation createAstrCbGlobalContent(\$walletAndRecharge: Map!) {
            createAstrCbGlobalContent(input: {walletAndRecharge: \$walletAndRecharge}) {
      id
      walletAndRecharge {
        title
        subtitle
        content
        imageUrl
      }

      createdAt
      updatedAt
              }
        }''';

      var operation = Amplify.API.mutate(

          request:
              GraphQLRequest<String>(document: graphQLDocument, variables: {
        'walletAndRecharge': {
          "title": 'test title',
          "subtitle": 'test subtitle',
          "content": 'test content',
          "imageUrl": 'testing.com',
        },
      }));

      var response = await operation.response;
      dynamic data = response.data ?? 'null returns';

      print('Mutation result: ' + data);

    } on ApiException catch (e) {

      print('Mutation failed: $e');

    }

  }

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
There is no env file
```

### Dependencies

```bash
amplify_api: ^0.6.0
amplify_flutter: ^0.6.0
```

### Device

iphone 11 pro

### OS

IOS  15.4

### CLI Version

9.1.0

**Comment by dnys1** [comment]
Can you post any error messages you receive? I assume you mean the Map you've passed in the `variables` key for `walletAndRecharge`? Also, can you share your GraphQL schema?

**Comment by selva-harivara** [comment]
GraphQL schema : 
type WalletRechargeContent {
  title: String
  subtitle: String
  content: String
  imageUrl: String
}

type astrCbGlobalContent @model @auth(rules: [{ allow: private }]) {
  id: ID!
  walletAndRecharge: WalletRechargeContent!
}

Didn't get any error message from exception.

**Comment by dnys1** [comment]
What issue are you facing?

**Comment by selva-harivara** [comment]
i can't able create, update data.

**Comment by selva-harivara** [comment]
We are getting empty value after that mutations response.

**Comment by ragingsquirrel3** [comment]
@selva-harivara do you have any errors in your graphql response? I see you are checking for thrown errors, but a server-side appsync error should not throw an ApiException. Instead, will usually return a response with null data and some list of errors which provide a lot of visibility into what's happening, especially if something like invalid request/schema. You can check this by printing/debugging `response.errors` in your code example.

**Comment by selva-harivara** [comment]
Thank you so much for your response to my request for information. We are fixed this issues.
