### ISSUE TITLE
Amplify.Auth.getCurrentUser() returning userId for both userId and username

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-flutter#1942]
### Description

This is happening only for iOS but Auth is returning same value for both userId and username.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

await Amplify.Auth.getCurrentUser().then((user) {
      print('User id--->'+user.userId);
      print('User name--->'+user.username);
}

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
```

### Dependencies

```bash
amplify_flutter: ^0.6.0
  amplify_api: ^0.6.0
  amplify_auth_cognito: ^0.6.0
  amplify_analytics_pinpoint: ^0.6.0
  amplify_datastore: ^0.6.0
```

### Device

iPhone 13

### OS

iOS 15.5

### CLI Version

9.1.0

**Comment by Jordan-Nelson** [comment]
Hi @veeramneni - I believe this is a duplicate of this issue - https://github.com/aws-amplify/amplify-flutter/issues/201. Would you be able to take a look at that issue and let me know if you believe they are different? Thanks.

**Comment by Jordan-Nelson** [comment]
I also wanted to note that there are some work arounds in that issue. If the work arounds don't meet your use case, please leave a comment with your use case.

**Comment by veeramneni** [comment]
Yes. Same issue. Closing as there is a workaround. thank you.
