### ISSUE TITLE
[HELP] How to send custom challenge answer ?

### ISSUE THREAD

**Issue by sabin26** [aws-amplify/amplify-flutter#199]
I have my user pool set up with lambda triggers for custom authentication. OTP is sent to user's phone and is working as expected. But, I am stuck going forward from here. 

I tried the following but it didn't work for sending answer in CUSTOM_FLOW method:

`await Amplify.Auth.confirmSignIn(confirmationValue: code);`

How to send custom challenge answer ?

**Comment by sabin26** [comment]
If we could do something like this:  `await Amplify.Auth.sendCustomChallengeAnswer(answer: code);`

It would be very useful.

**Comment by jamesonwilliams** [comment]
This looks like a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/276, possibly also https://github.com/aws-amplify/amplify-flutter/issues/271.
