### ISSUE TITLE
Keyboard navigation - Tab and Enter - with Web and Desktop in the Auth UI

### ISSUE THREAD

**Issue by vgribok** [aws-amplify/amplify-flutter#1999]
### Description

Using Dev Preview (the all-dart) Auth v.1.0.0-next.0, observing that 
1. Using keyboard Tab key to go between Auth UI form fields, the tabbing gets diverted to other UI controls if they happen to be at about the same height as the UI controls of the form, like if the NavigationRail widget is displayed on the left. The desired behavior would be that the form had its own tab order sequence.
2. Hitting keyboard Enter key while having the focus on the Auth UI form fields does not lead to the form submission. Better experience would be form submission.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Have a side panel with tappable UI controls, along with the AuthenticatedView on the same screen.
2. Hit tab repeatedly.

### Screenshots

![image](https://user-images.githubusercontent.com/757185/182718816-a525a905-37be-45ec-b95d-882e7ef2a770.png)

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1826], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.63.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
dependencies:
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_riverpod_restorable 1.0.1 [flutter flutter_riverpod riverpod]
- google_fonts 3.0.1 [flutter http path_provider crypto]

transitive dependencies:
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- ffi 2.0.0
- file 6.1.2 [meta path]
- flutter_riverpod 1.0.4 [collection flutter meta riverpod state_notifier]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.0 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- riverpod 1.0.3 [collection meta state_notifier]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- state_notifier 0.7.2+1 [meta]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

Windows 11 laptop

### OS

Windows 11

### CLI Version

8.5.0

**Comment by luxurystorecc1** [comment]
The Global Architecture of Style: From High-Performance Sport to Elite Social Events
Introduction: Defining the Modern Dress Code
The concept of a "uniform" has evolved drastically in the 21st century. No longer confined to specific silos, our clothing must now reflect a lifestyle that moves seamlessly between athletic pursuits and high-level social networking. From the strategic design of [Air Jordan 1 high-top sneakers](https://www.airjordan-1.com/) to the sophisticated drape of a gala gown, the architecture of modern style is built on the pillars of authenticity, technical innovation, and heritage.

The Foundation: Iconic Footwear and Streetwear Heritage
In the world of urban fashion, the foundation is always the footwear. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) remain the most significant architectural achievement in sneaker history. Their silhouette provides a structural elegance that works as well on a city street as it does on a hardwood court. For those who appreciate the evolution of this design, the [classic Jordans 1 retro collection](https://www.jordan1s.com/) offers a connection to the mid-80s era of sporting excellence.

Innovation, however, never rests. The "Yeezy" movement, led by the [Yeezy 350 V2 knit sneakers](https://www.yeezyboost-350.com/), introduced a minimalist, organic structure to the market. By utilizing energy-returning foam and adaptive fabrics, these shoes represent the future of ergonomic footwear. This same design philosophy extends to leisure items like [Yeezy slides for summer wear](https://www.yeezyboost-350.com/), which have redefined the luxury lounge category with their clean lines and unmatched comfort.

Representing the Team: Professional Sports Merchandise
Sports fandom is an essential part of regional and national identity. In the United States, the NFL serves as a massive cultural touchstone. Fans searching for the [NFL shop official online store for jerseys](https://www.nflshopofficialonline-store.com/) are looking for more than just clothing; they are looking for a piece of their team’s DNA. Whether it is a home game in cold climates or a sunny stadium in the South, [authentic NFL jerseys for men and women](https://www.cheapnfl-jerseys.com/) are the ultimate fan requirement.

For the ultimate enthusiast, standard gear is often not enough. The demand for a [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) has surged, allowing supporters to immortalize their own names alongside their favorite team's colors. This level of personalization is also mirrored in the soccer world, where collectors hunt for specific [national team soccer jerseys and kits](https://www.soccerjerseysstore.com/collections/national-teams) to celebrate global tournaments and regional pride.

The Country Club Standard: Peter Millar and Golfing Excellence
While some sports focus on high-impact intensity, others emphasize precision and social grace. The golfing world requires a specific aesthetic that [Peter Millar performance golf apparel](https://www.peter-milla.com/) provides in abundance. This clothing is engineered to provide maximum range of motion while maintaining a crisp, tailored appearance. The [Peter Millar clothing for luxury lifestyle](https://www.peter-milla.com/) brand has become the go-to for professionals who transition from the golf course to a high-stakes business meeting without changing their wardrobe.

Elegant Transitions: Formal Wear and Inclusion
As we transition from the field to the ballroom, the focus shifts to silhouette and material. The fashion industry’s commitment to inclusivity has led to a renaissance in [plus size formal gowns and dresses](https://www.cheapdressesformal.com/), ensuring that every guest at a black-tie event feels confident and stylish. For younger generations, the search for the perfect [prom dress with designer styling](https://www.cheapdressesformal.com/collections/prom) is a major milestone, reflecting the latest trends from international fashion weeks.

Conclusion: A Seamless Wardrobe
The modern individual’s wardrobe is a mosaic of different influences. Whether you are shopping at a [swim outlet for professional gear](https://www.swim-outlet.com/) or selecting [MLS soccer jerseys for fans](https://www.soccerjerseysstore.com/collections/mls-jerseys), the goal is always the same: quality that performs. By investing in authoritative brands that offer genuine heritage and advanced technology, you ensure that your style is as versatile as your life.
