### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(AmplifyException, User-Agent was already configured successfully., {cause: null, recoverySuggestion: User-Agent is configured internally during Amplify configuration. This method should not be called externally.}, null)

### ISSUE THREAD

**Issue by aymane6** [aws-amplify/amplify-flutter#200]
**Describe the bug**
I can't configure the Amplify with a basic configuration. I copy / paste and follow all steps in the official documentation.
I add the auth module, but i am not able to go throw this error.

**To Reproduce**
1. Go to 'https://github.com/aymane6/AmplifyTestApp.git'
2. Click on 'Run the project TWICE'
`E/flutter (17468): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(AmplifyException, User-Agent was already configured successfully., {cause: null, recoverySuggestion: User-Agent is configured internally during Amplify configuration. This method should not be called externally.}, null)
E/flutter (17468): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (17468): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (17468): <asynchronous suspension>
E/flutter (17468): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (17468): #3      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
E/flutter (17468): #4      Amplify.configure (package:amplify_core/amplify_core.dart:71:35)
E/flutter (17468): #5      _MyHomePageState._configureAmplify (package:amplify_tester/main.dart:77:27)
E/flutter (17468): #6      _MyHomePageState.initState (package:amplify_tester/main.dart:68:5)
E/flutter (17468): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (17468): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17468): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17468): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17468): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (17468): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (17468): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17468): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17468): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17468): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17468): #27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (17468): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (17468): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (17468): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (17468): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17468): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17468): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17468): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17468): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17468): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17468): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (17468): #42     Element.rebuild (package:flutter/src/widgets/framework.dar
F/crash_dump32(20551): crash_dump.cpp:246] target died before we could attach (received main tid = 20549)
`

**Expected behavior**
should work as the documentation says

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [version 10.0.18363.1198], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)

![image](https://user-images.githubusercontent.com/36692609/99696500-0c4d1400-2a8f-11eb-9397-4ff7b88f5050.png)

I have all plugins installed

**Smartphone (please complete the following information):**
 - Device: Pixel 4 API 27

**Additional context**
The SignUp Cognito doesn't work as well

**Comment by aymane6** [comment]
Finally i close the application and i restarted the project to make the error disappear
Thanks

**Comment by rvit34** [comment]
@aymane6  I think you closed the issue early. After each change in configuration, we need to restart the app completely. It's not convenient. It should work after each hot restart.
