### ISSUE TITLE
Need to manually close browser tab in order to complete social sign in / sign out with web UI on Linux 

### ISSUE THREAD

**Issue by Groseuros** [aws-amplify/amplify-flutter#2011]
### Description

**1.0.0 Developer Preview - Linux platform**

In order to complete social sign in / sign out on Linux desktop app, it's necessary to manually close the browser tab opened by `Amplify.Auth.signInWithWebUI` and `Amplify.Auth.signOut`, otherwise it loops forever on a white screen.

Tested with Google, Facebook and Apple social auth providers.

 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Setup a basic Flutter app with amplify_flutter and amplify_auth_cognito 1.0.0 Developer Preview
2. Enable social sign in with web UI
3. Build the app for Linux
4. Run the app and sign in with any social provider
5. Face the issue on successful sign in redirect

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [X] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04.1 LTS 5.15.0-43-generic,
    locale fr_FR.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

### Dependencies

```bash
Dart SDK 2.17.6
Flutter SDK 3.0.5
amplify_preview_test 1.0.0+1

dependencies:
- amplify_auth_cognito 1.0.0-next.0 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_flutter 1.0.0-next.0 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_auth_cognito_android 1.0.0-next.0 [flutter]
- amplify_auth_cognito_dart 0.1.1 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_core 1.0.0-next.0 [async aws_common aws_signature_v4 collection http intl json_annotation logging meta uuid]
- amplify_datastore_plugin_interface 1.0.0-next.0 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.0 [flutter]
- amplify_flutter_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_secure_storage 0.1.0 [amplify_secure_storage_dart flutter]
- amplify_secure_storage_dart 0.1.0 [aws_common built_collection built_value ffi js meta win32 worker_bee]
- async 2.8.2 [collection meta]
- aws_common 0.2.1 [async collection http logging meta stream_transform uuid]
- aws_signature_v4 0.2.1 [async aws_common collection convert crypto http json_annotation meta path]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- convert 3.0.2 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- oauth2 2.0.0 [collection crypto http http_parser]
- path 1.8.1
- petitparser 5.0.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- quiver 3.1.0 [matcher]
- retry 3.1.0
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.1.0 [aws_common built_collection built_value collection convert crypto fixnum http http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.1.1 [aws_common aws_signature_v4 built_collection built_value collection crclib http intl json_annotation meta path smithy xml]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- worker_bee 0.1.0 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xml 6.1.0 [collection meta petitparser]
```

### Device

N/A

### OS

Ubuntu 22.04.1 LTS

### CLI Version

-

**Comment by dnys1** [comment]
Thanks for creating this issue and checking out the dev-preview! We've isolated the cause and will have a fix released soon.

**Comment by dnys1** [comment]
Hi @Groseuros - thanks again for filling out this issue. We've fixed this in the latest release! Please let us know if you run into any more issues.

**Comment by lokalathlet** [comment]
Hi @dnys1 , I'm facing the same issue using authentication plugin in my android kotlin implemetation. The customTab remains still open after calling signOut and the user has to manually close it. A very bad UX. Can you give any advice?
`+--- com.amplifyframework:aws-auth-cognito:1.37.3
|    +--- com.amplifyframework:core:1.37.3 (*)
|    +--- androidx.appcompat:appcompat:1.2.0 -> 1.4.2 (*)
|    +--- com.amazonaws:aws-android-sdk-mobile-client:2.52.1
|    |    +--- com.amazonaws:aws-android-sdk-auth-core:2.52.1
|    |    |    \--- com.amazonaws:aws-android-sdk-core:2.52.1
|    |    |         +--- com.google.code.gson:gson:2.8.9 -> 2.9.0
|    |    |         \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    +--- com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.52.1
|    |    |    +--- com.amazonaws:aws-android-sdk-core:2.52.1 (*)
|    |    |    +--- com.amazonaws:aws-android-sdk-cognitoidentityprovider-asf:2.52.1
|    |    |    |    \--- com.amazonaws:aws-android-sdk-core:2.52.1 (*)
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    \--- androidx.core:core:1.3.1 -> 1.8.0 (*)
|    \--- com.amazonaws:aws-android-sdk-cognitoauth:2.52.1
|         +--- com.amazonaws:aws-android-sdk-core:2.52.1 (*)
|         +--- com.amazonaws:aws-android-sdk-cognitoidentityprovider-asf:2.52.1 (*)
|         \--- androidx.browser:browser:1.3.0
|              +--- androidx.core:core:1.1.0 -> 1.8.0 (*)
|              +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|              \--- com.google.guava:listenablefuture:1.0 -> 9999.0-empty-to-avoid-conflict-with-guava
+--- com.amplifyframework:core-kotlin:0.21.3
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.7.10 (*)
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2 -> 1.6.4 (*)
|    +--- androidx.core:core-ktx:1.3.2 -> 1.8.0 (*)
|    \--- com.amplifyframework:core:1.37.3 (*)
+--- aws.sdk.kotlin:cognitoidentityprovider:0.16.0
|    \--- aws.sdk.kotlin:cognitoidentityprovider-jvm:0.16.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         +--- aws.sdk.kotlin:aws-config:0.16.0
|         |    \--- aws.sdk.kotlin:aws-config-jvm:0.16.0
|         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |         \--- aws.sdk.kotlin:aws-core:0.16.0
|         |              \--- aws.sdk.kotlin:aws-core-jvm:0.16.0
|         |                   +--- aws.smithy.kotlin:runtime-core:0.10.0
|         |                   |    \--- aws.smithy.kotlin:runtime-core-jvm:0.10.0
|         |                   |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |                   |         +--- aws.smithy.kotlin:io:0.10.0
|         |                   |         |    \--- aws.smithy.kotlin:io-jvm:0.10.0
|         |                   |         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |                   |         +--- aws.smithy.kotlin:utils:0.10.0
|         |                   |         |    \--- aws.smithy.kotlin:utils-jvm:0.10.0
|         |                   |         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |                   |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1 -> 1.6.4 (*)
|         |                   \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         +--- aws.sdk.kotlin:aws-core:0.16.0 (*)
|         +--- aws.sdk.kotlin:aws-endpoint:0.16.0
|         |    \--- aws.sdk.kotlin:aws-endpoint-jvm:0.16.0
|         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |         +--- aws.smithy.kotlin:http:0.10.0
|         |         |    \--- aws.smithy.kotlin:http-jvm:0.10.0
|         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |         |         +--- aws.smithy.kotlin:runtime-core:0.10.0 (*)
|         |         |         +--- aws.smithy.kotlin:utils:0.10.0 (*)
|         |         |         +--- aws.smithy.kotlin:io:0.10.0 (*)
|         |         |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1 -> 1.6.4 (*)
|         |         \--- aws.smithy.kotlin:aws-signing-common:0.10.0
|         |              \--- aws.smithy.kotlin:aws-signing-common-jvm:0.10.0
|         |                   +--- aws.smithy.kotlin:aws-credentials:0.10.0
|         |                   |    \--- aws.smithy.kotlin:aws-credentials-jvm:0.10.0
|         |                   |         +--- aws.smithy.kotlin:runtime-core:0.10.0 (*)
|         |                   |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         |                   +--- aws.smithy.kotlin:http:0.10.0 (*)
|         |                   \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         \--- aws.smithy.kotlin:runtime-core:0.10.0 (*)
+--- aws.sdk.kotlin:cognitoidentity:0.16.0
|    \--- aws.sdk.kotlin:cognitoidentity-jvm:0.16.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.10 (*)
|         +--- aws.sdk.kotlin:aws-config:0.16.0 (*)
|         +--- aws.sdk.kotlin:aws-core:0.16.0 (*)
|         +--- aws.sdk.kotlin:aws-endpoint:0.16.0 (*)
|         \--- aws.smithy.kotlin:runtime-core:0.10.0 (*)`
