### ISSUE TITLE
Can't configure amplify with AmplifyAPI and AWS_IAM

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-flutter#2030]
### Description

I am trying to call an API with IAM authorization. I set up amplify configuration.dart like this:
"restAPIName": {
    "endpointType": "REST",
    "endpoint": "https://xxxxxxxxxx",
    "region": "us-east-1",
    "authorizationType": "AWS_IAM"
}

As per documentation "When your API is configured to use IAM as the authorization type, your requests will automatically have IAM credentials added to the headers of outgoing requests". 

However I am getting a response of 
"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.

The String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20220811T122538Z\n20220811/us-east-1/execute-api/aws4_request\xxxxxxxxxxx'

I saw the issue [here](https://github.com/aws-amplify/amplify-flutter/issues/913) which gives workaround for cognito user pools but is there something like that for IAM based auth? (I am not passing anything in headers)

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
```

### Dependencies

```bash
- amplify_analytics_pinpoint_android 0.6.5 [flutter]
- amplify_analytics_pinpoint_ios 0.6.5 [flutter]
- amplify_api_android 0.6.5 [flutter]
- amplify_api_ios 0.6.5 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.5 [flutter]
- amplify_auth_cognito_ios 0.6.5 [amplify_core flutter]
- amplify_core 0.6.5 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.5 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.5 [flutter]
- amplify_flutter_ios 0.6.5 [amplify_core flutter]
- amplify_storage_s3_android 0.6.5 [flutter]
- amplify_storage_s3_ios 0.6.5 [flutter]
```

### Device

N/A

### OS

N/A

### CLI Version

9.1.0

**Comment by veeramneni** [comment]
Looks like it started working all of sudden. Don't know if AWS policies took a while to take effect but will keep testing and re-open if there are issues.

**Comment by dnys1** [comment]
No worries. Please re-open if you face the issue again.

**Comment by veeramneni** [comment]
So it looks like this is an issue with iOS build only. Same REST API configured for IAM works in android but not on IOS. I am getting "Forbidden" error. Please confirm and I hope I did not miss anything trivial.

**Comment by veeramneni** [comment]
Sorry closing this again. Ended up its path issue. Looks like Android does not care about backslash in the path but iOS sdk requires it.
