### ISSUE TITLE
Update Authenticator state when Sign In is initiated outside of Authenticator

### ISSUE THREAD

**Issue by simranjeet09** [aws-amplify/amplify-flutter#2041]
### Description

We have implemented custom signing in our mobile application using custom challenge.
Our GetMaterial app has been wrapped with  Authenticator Widget. When a user signs in, it does not change the current authentication steps and always prints `AuthenticatorStep.signIn ` which results in staying on same screen after a successful sign in. 

Once I am logged in,  restarting the app helps to login without any issue. 

Amplify.Hub listener catches event as soon as it is triggered. 

Things i have tried:
1. Set state when state changes >> Not worked 
2. Rebuild whole widget >> Not worked 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Wrap the GetMaterialApp with Authenticator widget

login into Cognito using custom challenge 

Define auth builder
```
authenticatorBuilder: (BuildContext context, AuthenticatorState state) {
          switch (state.currentStep) {
            case AuthenticatorStep.signIn:
              return const SomeWidget();
            default:
              return null;
          }
        },
```

Define route/home in material builder. 

Login using custom amplify sign in in SomeWidget class 
After successful login, user remains on the same screen. 

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-arm, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.17.1
Flutter SDK 3.0.1
APP_NAME_HERE 1.0.0+1

dependencies:
- amplify_api 0.6.5 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.5 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_authenticator 0.2.2 [amplify_auth_cognito amplify_core amplify_flutter aws_common collection flutter flutter_localizations intl]
- amplify_flutter 0.6.5 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- auto_route 4.2.1 [flutter path collection meta universal_html]
- connectivity_plus 2.3.6 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cool_alert 1.1.0 [flutter flare_flutter lottie vector_math]
- cupertino_icons 1.0.5
- dio 4.0.6 [http_parser path]
- easy_colors 0.0.2 [flutter args path]
- firebase_crashlytics 2.8.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_appauth 4.2.0 [flutter flutter_appauth_platform_interface]
- flutter_image_slideshow 0.1.4 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- get 4.6.5 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- intl 0.17.0 [clock path]
- one_context 2.1.0 [flutter shared_preferences back_button_interceptor]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]

transitive dependencies:
- amplify_api_android 0.6.5 [flutter]
- amplify_api_ios 0.6.5 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.5 [flutter]
- amplify_auth_cognito_ios 0.6.5 [amplify_core flutter]
- amplify_core 0.6.5 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.5 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.5 [flutter]
- amplify_flutter_ios 0.6.5 [amplify_core flutter]
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- back_button_interceptor 6.0.1 [collection flutter]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dbus 0.7.7 [args ffi meta xml]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.12 [collection firebase_core flutter meta plugin_platform_interface]
- flare_flutter 3.0.2 [collection flutter meta]
- flutter_appauth_platform_interface 5.2.0 [flutter plugin_platform_interface]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- lottie 1.4.1 [archive flutter path vector_math]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nm 0.5.0 [dbus]
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.17 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

IPHONE 13, SAMSUNG A22

### OS

iOS 15.5

### Deployment Method

Amplify CLI

### CLI Version

9.0.0

### Amplify Config

{
"UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0"
}

**Comment by Jordan-Nelson** [comment]
Hello @simranjeet09 - How are you attempting to sign the user in? There are a few ways that it can be done with the authenticator.
1. Using one of the prebuilt widgets, for example `SignInButton()`
2. Using one of the method on the `AuthenticatorState` class, for example `state.signIn()`
3. Calling the underlying APIs directly, for example `Amplify.Auth.signIn(...)`

The first two options are currently supported by the authenticator. The last one is not at the moment, but we can mark this as a feature request if you are looking for that to be supported.

**Comment by simranjeet09** [comment]
> Hello @simranjeet09 - How are you attempting to sign the user in? There are a few ways that it can be done with the authenticator.
> 
> 1. Using one of the prebuilt widgets, for example `SignInButton()`
> 2. Using one of the method on the `AuthenticatorState` class, for example `state.signIn()`
> 3. Calling the underlying APIs directly, for example `Amplify.Auth.signIn(...)`
> 
> The first two options are currently supported by the authenticator. The last one is not at the moment, but we can mark this as a feature request if you are looking for that to be supported.


Thankyou @Jordan-Nelson  for a quick reply. 

Currently we are using the third option. It would be better if this feature could be added otherwise there will be a lot more boilerplate code implementation is required to handled the auth process. 


` final challengeRsp = await Amplify.Auth.signIn(
        username: username,
        options: CognitoSignInOptions(
          authFlowType: AuthenticationFlowType.customAuth,
        ),
      );
      String? challengeHint = challengeRsp.nextStep?.additionalInfo?['code'];
      final signInResult = await Amplify.Auth.confirmSignIn(
        confirmationValue: challengeHint!,
        options: CognitoConfirmSignInOptions(
          clientMetadata: {'KEY': 'VALUE'},
        ),
      );`

**Comment by Jordan-Nelson** [comment]
@simranjeet09 - Thanks for sharing more about the use case. This is a feature we have considered supporting. I will mark this as a feature request and post any updates here.

**Comment by andr3i4o** [comment]
That's exatly the same scenario we would need for our application so +1!

**Comment by simranjeet09** [comment]
Hi  @Jordan-Nelson,

Could you please share an Idea that when we are planning to officially release this fix for Flutter? We are eagerly waiting for this as we are dependent on Custom auth and this feature is acting like a major blocker to us. 

Thanks

**Comment by Jordan-Nelson** [comment]
Hello @simranjeet09 - Apologies for not updating this issue. The latest version of amplify_flutter (0.6.8) / amplify_authenticator (0.2.3) includes this change. You can see the latest release notes here: https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.6.8.

With these changes, you can call `Amplify.Auth.signIn()` from anywhere in your app and the authenticator will respond to this. The authenticator now listens to all events for sign in from authentication hub.

Please try this out and let me know if you face any issues.

Note: For anyone using the latest pre-release versions of Amplify, this change has also been included in the pre-release track.

**Comment by simranjeet09** [comment]
@Jordan-Nelson  Apologies for updating late, this bug has been fixed and we are able to use and continue our development.
Thank you team for your quick response to our query. I hope this feature will help a lot of developers around the world. 

Thank You 🎉 💫

**Comment by solarsiva** [comment]
Thansk a lot. The new release fixed the issue.
