### ISSUE TITLE
Unable to have both basic sign in and social sign in

### ISSUE THREAD

**Issue by ben-the-developer** [aws-amplify/amplify-flutter#2046]
Hi, I am having some difficulties to get basic sign in and social sign in together in the same app. My flutter version is 3.0.5, amplify_flutter version is ^1.0.0-next.0+1. At the moment, I only tested with Android emulator Pixel 4 API 33 (android-x64 emulator). Can you please help to see what could be wrong? Thank you

**The problem:**

I can sign up a user but when I sign in with username and password, I get `UserNotFoundException` with error message `User does not exist.` However, when I remove the following part from awsconfiguration, the basic sign in can work and the user can be found

```
 "OAuth": {
    "WebDomain": "<user-pool-url-without-https>",
    "AppClientId": "$appClientId",
    "SignInRedirectURI": "myapp://",
    "SignOutRedirectURI": "myapp://",
    "Scopes": [
        "phone",
        "email",
        "openid",
        "profile",
        "aws.cognito.signin.user.admin"
    ]
},
```

**Some details:**

<details>
  <summary>Sign in implementation</summary>

**For basic sign in**
  
```
Amplify.Auth.signIn(username: username, password: password);
```

**For social sign in**

```
Amplify.Auth.signInWithWebUI(provider: authProvider)
```
</details>

<details>
  <summary>awsconfiguration for both basic and social sign in</summary>
  
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CredentialsProvider": {
                  "CognitoIdentity": {
                      "Default": {
                          "PoolId": "<pool-id>",
                          "Region": "<region>"
                      }
                  }
              },
              "CognitoUserPool": {
                  "Default": {
                      "PoolId": "$podId",
                      "AppClientId": "$appClientId",
                      "Region": "<region>"
                  }
              },
              "GoogleSignIn": {
                  "Permissions": "email,profile,openid",
                  "ClientId-WebApp": "<client-id-webapp>.apps.googleusercontent.com",
                  "ClientId-iOS": "<client-id-ios>.apps.googleusercontent.com",
                  "ClientId-Android": "<client-id-android>.apps.googleusercontent.com"
              },
              "Auth": {
                  "Default": {
                      "OAuth": {
                            "WebDomain": "<user-pool-url-without-https>",
                            "AppClientId": "$appClientId",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                      },
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
          }
      }
  }
}
```
</details>

<details>
  <summary>AndroidManifest.xml</summary>
  
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="package-name">
<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
   <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true">
        ...
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            ...
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
            </intent-filter>
        </activity>
   </application>
   ...
</manifest>
```
</details>

Exception Detail
![image](https://user-images.githubusercontent.com/106507310/185405253-03e211cd-4754-4ee9-bf06-b722f8cb89a3.png)

Cognito User Pool configuration
![image](https://user-images.githubusercontent.com/106507310/185403659-b553537e-43b2-48c2-84d3-8995157a9523.png)

**Comment by bibaswan-bhawal** [comment]
Hi, are you using socialSignIn to sign up and then email and password to log in? or are you using the same system you used to sign up to sign in?

**Comment by ben-the-developer** [comment]
Hi @bibaswan-bhawal , here is how I sign up a new user for basic sign in. I am using `amazon_cognito_identity_dart_2` library to implement that because for some reason amplify flutter does not return cognito user id  after registration, not sure if it supports now or not. https://github.com/aws-amplify/amplify-flutter/issues/180.

```
  Future<String?> register(String username, String password, String email) async {
    final AttributeArg emailAttribute = AttributeArg(name: 'email', value: email);
    final CognitoUserPoolData userPoolData =
        await _cognitoUserPool.signUp(username, password, userAttributes: <AttributeArg>[emailAttribute]);
    return userPoolData.userSub!;
  }
```

**Comment by dnys1** [comment]
Hi @ben-the-developer - the user ID should be available on the AuthUser returned from `Amplify.Auth.getCurrentUser()`. It is, however, only available after sign in. If you think there's value in returning this from `signUp` as well or having `getCurrentUser` work after signUp, I can discuss that with my team.

Depending on your Cognito configuration, an additional call to `confirmSignUp` may be required after your call to `signUp`. This information is available in the return value from `Amplify.Auth.signUp` as `signUpStep` and `codeDeliveryDetails`, and I would guess is available in some form in the method you have listed.

Do you call `Amplify.Auth.signIn` or `Amplify.Auth.signInWithWebUI` after signing up a user?

**Comment by ben-the-developer** [comment]
Hi @dnys1, thank you for you advice.

For the scenario of getting user sub after signing up is that, I just want Cognito to manage user sign in credentials and want to manage all other user profile information in my own local database. Therefore, I am currently using user sub guid as the link between the account in Cognito and user profile in my database. When a user signs up, some data, such as email and credentials will be used to sign up a user account in Cognito. When the user account is created, a user profile record, including the user sub, will be created immediately in my own database. That's the reason why I would like to have the user sub guid from sign up step. It will be great to have such feature in amplify flutter since I am a bit hesitate to create a Lambda or something just for the purpose of getting user sub.

For having a `confirmSignUp` after call to `signUp`, I confirm the user's email has been confirm before signing in with basic sign in. The workflow in my app is as follow

1. user enter username and password in my app and click sign up button (use `amazon_cognito_identity_dart_2` library)
2. user is notified to get the confirmation link in their email
3. user goes to the email inbox and click the verification link
4. user goes back to the app and try to sign in (call `Amplify.Auth.signIn` function)

I am not sure if calling the `confirmSignUp` works the same as the verification link. I saw the `confirmSignUp` function requires the username and the confirmationCode. I guess the confirmationCode is sent to user's email when sign up.

Any further help would be appreciated. Let me know if you would like to have more detail of my implementation.

**Comment by dnys1** [comment]
Thanks for the information! I'm not too familiar with the verification link approach, but will give that a try today and see what the issue could be.

I'll bring up the user sub issue at our next weekly discussion of auth issues.

**Comment by ben-the-developer** [comment]
Thank you @dnys1. I will also keep trying and update here if I can find anything.

For the verification link, I can set in UserPool of Cognito as follow

![image](https://user-images.githubusercontent.com/106507310/185634594-db306558-a296-46db-84ef-edb2da5da7c2.png)

![image](https://user-images.githubusercontent.com/106507310/185634428-c2a10e47-77f3-4842-8203-9b23b61dc8c8.png)

**Comment by dnys1** [comment]
I tried this with `signUp` and `signIn` from the Amplify libraries. My user pool was configured with Hosted UI, username sign-in, and email verification link. The steps I did:
- `Amplify.Auth.signUp` with username, email, and password
- Click link in email
- `Amplify.Auth.signIn` with username and password

This worked well for me. I'm wondering if it might be a configuration issue - do you potentially have multiple user pool IDs or app client IDs you work with? 

I also tried retrieving the user sub with the AWS SDK internal to our Dart pkg. If you want to give that a try, I'd encourage it over the unofficial package (and would appreciate any feedback around your experience, if you choose to use it). The only catch is that the API may slightly change in the future.

```dart
import 'package:amplify_auth_cognito_dart/src/util/credentials_providers.dart';
import 'package:amplify_auth_cognito_dart/src/sdk/cognito_identity_provider.dart'
    as sdk;
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:built_collection/built_collection.dart';

import 'amplifyconfiguration.dart';

final config = AmplifyConfig.fromJson(
  jsonDecode(amplifyconfig) as Map<String, dynamic>,
);
const client = sdk.CognitoIdentityProviderClient(
  region: 'us-west-2',
  credentialsProvider: AnonymousCredentialsProvider(),
);

final clientId =
    config.auth!.awsPlugin!.cognitoUserPool!.default$!.appClientId;
final signUpResp = await client.signUp(
  sdk.SignUpRequest(
    clientId: clientId,
    username: '<username>',
    password: '<password>',
    userAttributes: BuiltList([
      sdk.AttributeType(name: 'email', value: '<email>'),
    ]),
  ),
);
safePrint(signUpResp);

/// I/flutter ( 6102): SignUpResponse {
/// I/flutter ( 6102):   codeDeliveryDetails=CodeDeliveryDetailsType {
/// I/flutter ( 6102):     attributeName=email,
/// I/flutter ( 6102):     deliveryMedium=EMAIL,
/// I/flutter ( 6102):     destination=n***@a***,
/// I/flutter ( 6102):   },
/// I/flutter ( 6102):   userConfirmed=false,
/// I/flutter ( 6102):   userSub=86cad277-d55c-461a-be6c-706de6a84cda,
/// I/flutter ( 6102): }
```

**Comment by ben-the-developer** [comment]
Hi @dnys1 , thank you for confirming it's working in your end. Indeed I have two user pools, for production and for development. Each user pool is associated with two app clients. Production user pool has preview and production app clients and development user pool has development and staging app clients.

May I ask in your test, did you also enable social sign in in both Cognito and `amplifyconfiguration.dart`? To me, if I disable social sign in in `amplifyconfiguration.dart` (removing OAuth section and keep everything else not changed), the sign up and sign in work for me.

I am more than happy to try AWS SDK. I also don't want to use unofficial library.

Here are the screenshots of my user pool configuration. Let me know if you would like me to provide any more details. Thank you for your patient.

![image](https://user-images.githubusercontent.com/106507310/185658146-0b59cb3e-9dbe-4111-afa2-f9b3abb0f2bc.png)

![image](https://user-images.githubusercontent.com/106507310/185658301-427d2840-7fdd-42c9-8ead-ba8f76983504.png)

![image](https://user-images.githubusercontent.com/106507310/185658603-a26b2b77-6216-4ad9-95e0-6a0424c1ab59.png)

![image](https://user-images.githubusercontent.com/106507310/185659878-42709068-3362-4c8f-adb7-99ea302bfbdd.png)

**Comment by ben-the-developer** [comment]
Hi @dnys1 , some update regarding the sign up with AWS SDK. I can successfully sign up with it and get the user sub immediately after signing up. 

However, I am still not able to sign in if `OAuth` section is in awsconfiguration.

**Comment by dnys1** [comment]
I've tried with an identical Cognito setup and couldn't reproduce the behavior you're seeing. I'm a bit stumped as to what could be happening, since presence of the "OAuth" section alone doesn't do much. A few things to sanity check:

- Can you confirm that all the app client IDs are the same throughout your amplifyconfiguration and match what's in your backend? A `UserNotFoundException` implies to me that the user is being created with a different client ID than the one used during sign in.
- Can you confirm the user is created via the AWS console and shows "CONFIRMED" for the "Account status"?

I will keep thinking about what could be going wrong..

**Comment by ben-the-developer** [comment]
Hi @dnys1 , finally I get it working by clean all the caches of flutter, wipe emulator's data and for some reason it works. Sorry for wasting your time to replicate the issue.

**Comment by dnys1** [comment]
That's so odd. It's no worries at all - I'm just as dumbfounded as you haha. I'll close the ticket for now, but please let me know if the issue pops up again, and I'll think on why you may have experienced this.

**Comment by dnys1** [comment]
Hey @ben-the-developer - I wanted to follow up about the userSub issue for `signUp`. The currently recommended approach for creating a user in the database following sign up is to the use the [post confirmation lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html) which gets triggered after every successful signup.

Here's an example of that which makes a GraphQL request to create a user for every sign up: https://github.com/dnys1/habitr/blob/main/amplify/backend/function/habitr672b9506PostConfirmation/src/main.go.

Hope this helps!
