### ISSUE TITLE
Amplify.Auth.signOut() function is showing the sign in web UI

### ISSUE THREAD

**Issue by Eric1015** [aws-amplify/amplify-flutter#2054]
### Description

When the user clicks on sign out button in my app, with call to ```Amplify.Auth.signOut()``` function, it will open the web UI with the message of ```"..." wants to use "..."``` to sign in like the video in this [issue](https://github.com/aws-amplify/amplify-ios/issues/964).

Is this something expected?

My expectation was that this thing should only show up at the time of sign in using ```signInWithWebUI()``` function as the text on the modal itself is already misleading.

I am using Google as the social sign-in provider.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Sign in with Google using ```Auth.signInWithWebUI(provider: AuthProvider.google)```
2. Sign out using ```Amplify.Auth.signOut()```
3. The modal with message of ```"..." wants to use "..."``` to sign in should show up.

### Screenshots

Please refer to the video in this issue: https://github.com/aws-amplify/amplify-ios/issues/964

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.70.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.17.5
Flutter SDK 3.0.4
idsea_mobile 1.0.0+1

dependencies:
- amplify_api 0.6.5 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.5 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.5 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.5 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- equatable 2.0.3 [collection meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_hooks 0.18.5+1 [flutter]
- flutter_redux 0.10.0 [redux flutter]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- getwidget 2.1.1 [flutter]
- http 0.13.5 [async http_parser meta path]
- loader_overlay 2.0.10 [flutter back_button_interceptor]
- path 1.8.1
- redux 5.0.0
- settings_ui 2.0.2 [flutter]
- sqflite 2.0.3+1 [flutter sqflite_common path]

transitive dependencies:
- amplify_api_android 0.6.5 [flutter]
- amplify_api_ios 0.6.5 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.5 [flutter]
- amplify_auth_cognito_ios 0.6.5 [amplify_core flutter]
- amplify_core 0.6.5 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.5 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.5 [flutter]
- amplify_flutter_ios 0.6.5 [amplify_core flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- back_button_interceptor 6.0.1 [collection flutter]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- font_awesome_flutter 9.2.0 [flutter]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
```

### Device

iPhone SE 2nd Generation - Simulator

### OS

iOS 15.5

### Deployment Method

Amplify CLI

### CLI Version

9.1.0

### Amplify Config

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "idsea": {
                    "endpointType": "GraphQL",
                    "endpoint": "*******************",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "*****************",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "******_AMAZON_COGNITO_USER_POOLS"
                    },
                    "******_AWS_IAM": {
                        "ApiUrl": "*****************",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "***********"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "**************",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "**********",
                        "AppClientId": "***********",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "****************",
                            "AppClientId": "************",
                            "SignInRedirectURI": "*****",
                            "SignOutRedirectURI": "****",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

**Comment by dnys1** [comment]
Unfortunately, this is a limitation of iOS and the expected behavior when running on iOS. The current workaround is to use the `preferPrivateSession` flag which will prevent the popup from showing at the cost of disallowing the webview from sharing credentials with the user's Safari cache.

Here's the original iOS issue for this with the note about `prefersPrivateSession`: https://github.com/aws-amplify/amplify-ios/issues/634#issuecomment-774164469 and the docs for the flag which is used in the iOS code: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio

In Flutter, this would look like:

```dart
await Amplify.Auth.signInWithWebUI(
  provider: AuthProvider.google,
  options: const CognitoSignInWithWebUIOptions(
    isPreferPrivateSession: true,
  ),
);
```

Hope this helps and please feel free to open if this doesn't resolve your issue.

**Comment by Eric1015** [comment]
Thank you for your quick response, yeah this would help me for the time being!
