### ISSUE TITLE
I have a custom type field in amplify studio data model table that is not deployed to the Daynamo table

### ISSUE THREAD

**Issue by xiangxd** [aws-amplify/amplify-flutter#2056]
I added a custom complex type field (content: RichEditData)in the amplify studio data model table. After deployment, the complex type field (content: RichEditData) cannot be viewed in the dynamo table

schema.graphql

type RichEditData {
  type: RichEditDataType
  data: String
}

enum RichEditDataType {
  TEXT
  IMAGE
  VIDEO
}
type Comment @model @auth(rules: [{allow: public}]) {
  id: ID!
  commited: AWSTimestamp
  masterId: ID!
  doctorId: ID
  patientId: ID
  postId: ID
  content: RichEditData
}

**Comment by fjnoyp** [comment]
Hi @xiangxd seems like your issue is with Studio, so let's transfer this issue to that repo.

**Comment by xiangxd** [comment]
Thanks @fjnoyp first,but can I get message from that repo，about how long ?

**Comment by HuiSF** [comment]
Hello @xiangxd can you explain "cannot be viewed in the dynamo table"? 

You mean the data is not written into DynamoDB or you can't view it as a map? Any screenshots that would be helpful.

**Comment by HuiSF** [comment]
Hi @xiangxd can you provide more info requested in my last comment to help us triaging your issue? Thanks!

**Comment by dnys1** [comment]
Hi @xiangxd, I deployed this schema to AppSync using Amplify CLI version 10.0.0.

I was able to create items via the GraphQL and see the items created in Dynamo. 

<img width="1552" alt="Screen Shot 2022-09-12 at 2 34 34 PM" src="https://user-images.githubusercontent.com/24740863/189763097-c212bc25-9c30-40a5-8ea7-f000db864e3e.png">

<img width="1340" alt="Screen Shot 2022-09-12 at 2 35 41 PM" src="https://user-images.githubusercontent.com/24740863/189763126-e95319ff-c614-40cf-af45-2c45f249a567.png">

Are you asking if a separate DynamoDB table should be created for the `RichEditData` type like it is for `Comment`? If that's the case, then this is expected. DynamoDB tables are only created for `@model` types. So-called "custom" or "embedded" are embedded in the model's table as shown above.

Hope this helps. Please re-open if this did not answer your question.
