### ISSUE TITLE
GraphQL mutation from Lambda doesn't trigger datastore sync (observeQuery, observe)

### ISSUE THREAD

**Issue by kmrosiek** [aws-amplify/amplify-flutter#2065]
### Description

I have used TODO simplest app with API and Datastore. Unfortunately Datastore sync does not seem to be working as expected when inserting data with [Lambda function](https://github.com/kmrosiek/amplify_example/blob/main/amplify/backend/function/testgraphqlMutation/src/index.js).

**Expected Behaviour**
When I perform `mutation CREATE_TODO` in lambda function datastore methods `observeQuery` `observe` reflect the mutation - added TODO. 

**Actual Behaviour**
When I perform `mutation CREATE_TODO` in lambda function datastore methods  `observeQuery` `observe` do not get notified at all. Only subscription works correctly and receives newly inserted object.

**More info**
When I add Todo from Amplify console everything works fine  `observeQuery` and `observe` correctly get notified.
When I add Todo from Lambda function I have to clear app cache then when datastore syncs with the backend even objects added from lambda function are correctly synced.
When I add Todo from Lambda function, then from Amplify console only the one inserted from Amplify console is received in  `observeQuery` `observe` 

I added [git repo](https://github.com/kmrosiek/amplify_example) with minimal example. This is [schema](https://github.com/kmrosiek/amplify_example/blob/main/preview_schema.graphql) generated by Amplify.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create a fluter project (I used Flutter channel stable 3.0.5).
2. Add `amplify add api` with GraphQL, auto-merge conflict resolution, simple todo sample.
3. Add lambda function `amplify add function` with mutation permission.
4. Add observeQuery, observe, subscribe in the App.
5. Make lambda function perform `mutation CREATE_TODO` when called.
6. Verify todo is correctly added to db and subscription is called but not observeQuery, observe.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
```

### Dependencies

```bash
Dart SDK 2.17.6
Flutter SDK 3.0.5
test_graphql_lambda 1.0.0+1

dependencies:
- amplify_api 0.6.6 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.6 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.6 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_api_android 0.6.6 [flutter]
- amplify_api_ios 0.6.6 [amplify_core flutter]
- amplify_core 0.6.6 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.6 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.6 [flutter]
- amplify_flutter_ios 0.6.6 [amplify_core flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- json_annotation 4.6.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
```

### Device

IPhone 13 Simulator

### OS

iOS 15.5

### Deployment Method

Amplify CLI

### CLI Version

9.2.1

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "testgraphqllambda": {
                    "endpointType": "GraphQL",
                    "endpoint": "***",
                    "region": "eu-central-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "***"
                }
            }
        }
    }
}''';

**Comment by HuiSF** [comment]
Hi @kmrosiek thanks for opening this issue.

DataStore sync engine creates subscription with a complete selection set of each model.

Take `Todo` in your schema

```graphql
type Todo @aws_iam
@aws_api_key {
	id: ID!
	name: String!
	description: String
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime!
	_version: Int!
	_deleted: Boolean
	_lastChangedAt: AWSTimestamp!
}
```

Take your manual mutation selection set in your lambda function

```
const query = /* GraphQL */ `
  mutation CREATE_TODO($input: CreateTodoInput!) {
    createTodo(input: $input) {
      id
      name
      createdAt
    }
  }
`;
```

Due to missing required fields `updatedAt`, `_version`, `_lastChangedAt` the subscription event sent to your iOS device raises error due to non-nullable fields are `null`. Please consider list all fields in the mutation selection set.

**Comment by kmrosiek** [comment]
Thank you @HuiSF. This works.
Would be nice to show this error somehow to the developer but I guess it would be tricky to implement.
Cheers!

**Comment by HuiSF** [comment]
> Thank you @HuiSF. This works. Would be nice to show this error somehow to the developer but I guess it would be tricky to implement. Cheers!

Indeed, in the other issue you commented, we are adding the support of many-to-many to GraphQL helper, with that, you will get better dev experience, please stay tuned! :)

**Comment by taromorimoto** [comment]
@HuiSF @kmrosiek  I finally bumped into this github issue after endlessly searching for a fix to this problem. I can't believe that this is not clearly stated in the documentation.

https://docs.amplify.aws/react/build-a-backend/more-features/datastore/how-it-works/#writing-data-from-the-appsync-console
> In these cases it's important that the selection set of your GraphQL mutation includes all the required fields of the model, including: _lastChangedAt, _version, and _deleted so that the DataStore clients can react to these updates. 

It really should clearly say that if you don't include **ALL FIELDS**, not just the "required fields", then it will not trigger a sync on the client DataStore. This should be super clear as it's super weird that you need to include all the fields.

Anyways, thank you both for the question and response as this solved my issue.
