### ISSUE TITLE
Amplify Datastore initialization time is too large in flutter

### ISSUE THREAD

**Issue by anaya12345** [aws-amplify/amplify-flutter#2089]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:REGION:accountId:apps/d25znh8gyx5zne

### Region

us-east-1

### Environment name

karecirc

### What operating system are you using?

Windows

### Browser type?

Microsoft Edge

### Describe the bug

A flutter application created with aws amplify support is taking too much time to initialize amplify datastore instance. The delay averages from 2 minutes to upto 15 minutes. 
Kindly guide us to resolve this issue asap.

### Expected behavior

Datastore should be quickly initialized.

### Reproduction steps

1. Install application.
2. Initialize amplify - add auth and datastore plugins.
3. Show UI screen and fetch data from datastore using observe query. 
4. Observe isSync flag in observe query method. It becomes true after 2-15 minutes.

**Comment by Jordan-Nelson** [comment]
Hello @anaya12345 - Can you tell me how many models you have in your schema, and roughly how many total models exist in the cloud?

Are you using selective sync at all?

**Comment by Jordan-Nelson** [comment]
@anaya12345 - Would you be able to provide the info above? Thanks.

**Comment by Jordan-Nelson** [comment]
Hello @anaya12345 - I am going to close this out since we have not heard back. If you are still facing an issue, please open a new request in the amplify-flutter repo. Thanks.
