### ISSUE TITLE
SystemNavigator.pop() causes Amplify exception

### ISSUE THREAD

**Issue by wasitu** [aws-amplify/amplify-flutter#213]
**Describe the bug**
Flutter's SystemNavigator.pop() causes Amplify exception by starting app again.
(Using android's back button for closing app causes the same problem)

**To Reproduce**
1. Configure Amplify like
```
final amplify = Amplify();
amplify.addPlugin(authPlugins: [AmplifyAuthCognito()]);
await amplify.configure('~~~')
```
2. Use `SystemNavigator.pop()` for close app on root page (or press android's back button)
3. Start app again
4. You can see error on logcat

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[×] Android
[] iOS

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: 11
 - Flutter: 1.22.0 (stable)

**Comment by fjnoyp** [comment]
Hi @wasitu thanks for bringing this issue to our attention.  We'll discuss this issue and take a look.

**Comment by wasitu** [comment]
@fjnoyp 
Thanks for your reply.

Yeah, I saw those workaround but I think its not that.
Because If I remove Amplify, Everything fine. (Behavior seems to be restarted all and can use other libraries.)

**Comment by fjnoyp** [comment]
Ah I see.  Could you provide the full error log you're getting here?  Does keeping a `bool isConfigured` and only calling configure() if it's false fix your problem?

**Comment by wasitu** [comment]
@fjnoyp 
Here's log
```
W/GeneratedPluginsRegister( 9410): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@ecc66fc) but could not find and invoke the GeneratedPluginRegistrant.

E/flutter ( 9410): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/core)
E/flutter ( 9410): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter ( 9410): <asynchronous suspension>
E/flutter ( 9410): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter ( 9410): #2      MethodChannelAmplifyCore.configure
package:amplify_core_plugin_interface/method_channel_amplify.dart:25
E/flutter ( 9410): #3      Amplify.configure
package:amplify_core/amplify_core.dart:71
E/flutter ( 9410): #4      setup
package:myapp/main.dart:47
E/flutter ( 9410): #5      main
package:myapp/main.dart:24
E/flutter ( 9410): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 9410): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9410): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9410): #9      _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 9410): #10     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 9410): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 9410): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 9410): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

`bool isConfigured` can't fix problem. Since Dart seems to be reset, it's always false.
As log said, Automatically registration plugins failed with amplify one.

**Comment by wasitu** [comment]
I fixed it temporally like this.
https://github.com/wasitu/amplify-flutter/commit/80e9eb6ef058e2d8e49ea2b093c489c8739e90fc

But I dont have much time (and smart brain) to test and think if it's ok or not. Just working for me.

**Comment by brunovsiqueira** [comment]
I'm having the exact same issue mentioned by @wasitu.

**Comment by Rayv1** [comment]
Hi guys, 
i had the same Problem and i had to implement the "check-if-amplify-configured"-Fix and the from @fjnoyp mentioned FlutterActivity Workaround from [StackOverflow ](https://stackoverflow.com/questions/55539302/sending-your-application-to-background-when-back-button-is-pressed-in-flutter)

Its working now independently from how the app is closed.

**Comment by brunovsiqueira** [comment]
@Rayv1 I found different solutions in the link you provided. Which solution worked for you?

**Comment by Rayv1** [comment]
This Solution worked:
var _androidAppRetain = MethodChannel("android_app_retain");

```
@override
Widget build(BuildContext context) {
return WillPopScope(
  onWillPop: () {
    if (Platform.isAndroid) {
      if (Navigator.of(context).canPop()) {
        return Future.value(true);
      } else {
        _androidAppRetain.invokeMethod("sendToBackground");
        return Future.value(false);
      }
    } else {
      return Future.value(true);
    }
  },
  child: Scaffold(
    ...
  ),
);
```
The code in the MainActivity() should look like this:

```
class MainActivity: FlutterActivity() {

override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);

    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "android_app_retain").apply {
        setMethodCallHandler { method, result ->
            if (method.method == "sendToBackground") {
                moveTaskToBack(true)
            }
        }
    }
}
}
```

**Comment by brunovsiqueira** [comment]
Hi guys. I tried the above solution and it seems to work in the back pressed case but it still causes crashes on Crashlytics. 

@Amplifiyer is there any schedule to have this bug fixed? In my opinion it is a really important bug because it crashes the app.

**Comment by Amplifiyer** [comment]
The original issue with `MissingPluginException` has been fixed in https://github.com/aws-amplify/amplify-flutter/pull/345 Please see #99 for more details about this issue. Closing as duplicate. The fix will be available in our next release.
