### ISSUE TITLE
DataStoreException(message: The operation couldn’t be completed. (SQLite.Result error 0.), recoverySuggestion: The operation couldn’t be completed. (SQLite.Result error 0.), underlyingException: The operation couldn’t be completed. (SQLite.Result error 0.))

### ISSUE THREAD

**Issue by YawarOsman** [aws-amplify/amplify-flutter#2190]
### Description

When i'm trying to save data in `Amplify DataStore` it cause that error in the title.
it works perfectly on Android and real iphone 6 device but i tried on iphone 13 pro max simulator it caused this issue

This is my code to save the data to `DataStore` :

```
final newUser = Users(
      userId: uuid.v1(),
      userName: _nameController.text,
      email: _emailController.text,
);

await Amplify.DataStore.save(newUser);
```

And this is my GraphQL schema for `Users` table:

```
type Users @model @auth(rules: [{allow: public}]) {
  userId: ID!
  userName: String
  email: AWSEmail
  phone: AWSPhone
  bio: String
  social_links: AWSJSON
  profile_image: String
  followUsersFollower: [FollowUsers] @hasMany(indexName: "byUser_followUsersFollower", fields: ["userId"])
  followUsersReciever: [FollowUsers] @hasMany(indexName: "byUser_followUsersReciever", fields: ["userId"])
  followClubs: [FollowClubs] @hasMany(indexName: "byUser_followClubs", fields: ["userId"])
  clubs: [Clubs] @hasMany(indexName: "byUser_clubs", fields:["userId"])
  userTopics: [UserTopics] @hasMany(indexName: "byUser_userTopics", fields:["userId"])
  userChatSender: [UserChats] @hasMany(indexName: "byUser_userChatSender", fields:["userId"])
  userChatReciever: [UserChats] @hasMany(indexName: "byUser_userChatReciever", fields:["userId"])
  participants: [Participants] @hasMany(indexName: "byUser_participants", fields:["userId"])
  rooms: [Rooms] @hasMany(indexName: "byUser_rooms", fields:["userId"])
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.7 20G817 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.17.6
Flutter SDK 3.0.5
english_tech 1.0.0+1

dependencies:
- amplify_auth_cognito 0.6.8 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.8 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.8 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- async 2.8.2 [collection meta]
- cupertino_icons 1.0.5
- flashy_tab_bar2 0.0.4 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_switch 0.3.2 [flutter]
- http 0.13.5 [async http_parser meta path]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl_phone_field 3.1.0 [flutter]
- provider 6.0.3 [collection flutter nested]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- uuid 3.0.6 [crypto]
- videosdk 1.0.3 [flutter random_string flutter_webrtc events2 collection sdp_transform h264_profile_level_id flutter_foreground_task synchronized http encrypt]

transitive dependencies:
- amplify_auth_cognito_android 0.6.8 [flutter]
- amplify_auth_cognito_ios 0.6.8 [amplify_core flutter]
- amplify_core 0.6.8 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.8 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.8 [flutter]
- amplify_flutter_ios 0.6.8 [amplify_core flutter]
- args 2.3.1
- asn1lib 1.1.0
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- dart_webrtc 1.0.8 [webrtc_interface]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- events2 1.0.0
- ffi 1.2.1
- file 6.1.2 [meta path]
- flutter_foreground_task 3.8.2 [flutter platform shared_preferences shared_preferences_android shared_preferences_ios]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- flutter_webrtc 0.9.7 [dart_webrtc flutter path_provider webrtc_interface]
- h264_profile_level_id 0.2.0 [flutter]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- process 4.2.4 [file path platform]
- random_string 2.3.1
- sdp_transform 0.3.2
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- webrtc_interface 1.0.8
- win32 2.5.2 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

Iphone 13 pro max

### OS

15.0

### Deployment Method

Amplify CLI

### CLI Version

9.2.1

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "meetingApp": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://rrlwsn3iqrdorhyx2j4yn3haem.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "**********************"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://rrlwsn3iqrdorhyx2j4yn3haem.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "**********************",
                        "ClientDatabasePrefix": "meetingApp_API_KEY"
                    },
                    "meetingApp_AWS_IAM": {
                        "ApiUrl": "https://rrlwsn3iqrdorhyx2j4yn3haem.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "meetingApp_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "**********************",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_PmXmz1tuk",
                        "AppClientId": "**********************",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "meetingappauth-dev.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "**********************",
                            "SignInRedirectURI": "https://www.google.com/",
                            "SignOutRedirectURI": "https://www.youtube.com/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL",
                            "PHONE_NUMBER"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

**Comment by fjnoyp** [comment]
Hi @YawarOsman thanks for sharing this issue.  We'll take a look and see what's going on here.

**Comment by YawarOsman** [comment]
> Hi @YawarOsman thanks for sharing this issue. We'll take a look and see what's going on here.

thank you, let me know when you got it, please

**Comment by fjnoyp** [comment]
Hi @YawarOsman

I just ran the Datastore example app on an iPhone 13 pro max and am unable to replicate your issue.  I am able to save objects and retrieve them again when the app starts up. 

Can you please try uninstalling and rerunning the app on the simulator again.  There might be old data from a different schema that's still present. 

If that still doesn't fix your issue - can you please try running the Datastore example app from our github repo and see if it's broken for you as well?  

**Example app link:** 

https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore/example

**And use this schema.graphql:** 

https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/tool/schema.graphql


Lastly, when saving your objects in datastore you do not need to specify the id - we already use the uuid library to autogenerate an id for you:

```
final newUser = Users(
      userId: uuid.v1(), <== you can remove this :) 
      userName: _nameController.text,
      email: _emailController.text,
);

```

**Comment by YawarOsman** [comment]
> Hi @YawarOsman
> 
> I just ran the Datastore example app on an iPhone 13 pro max and am unable to replicate your issue. I am able to save objects and retrieve them again when the app starts up.
> 
> Can you please try uninstalling and rerunning the app on the simulator again. There might be old data from a different schema that's still present.
> 
> If that still doesn't fix your issue - can you please try running the Datastore example app from our github repo and see if it's broken for you as well?
> 
> **Example app link:**
> 
> https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore/example
> 
> **And use this schema.graphql:**
> 
> https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/tool/schema.graphql
> 
> Lastly, when saving your objects in datastore you do not need to specify the id - we already use the uuid library to autogenerate an id for you:
> 
> ```
> final newUser = Users(
>       userId: uuid.v1(), <== you can remove this :) 
>       userName: _nameController.text,
>       email: _emailController.text,
> );
> ```

thank you for your instructions, now i'm be able to save data but it only stores offline it won't sync to the cloud i don't know what is the problem i reinstalled the app and also remove and added the amplify api but it didn't fix my issue

**Comment by Jordan-Nelson** [comment]
@YawarOsman - Have you been able to try the suggestions above from @fjnoyp? Does the issue persist after removing the app from the simulator and reinstalling?

**Comment by YawarOsman** [comment]
> @YawarOsman - Have you been able to try the suggestions above from @fjnoyp? Does the issue persist after removing the app from the simulator and reinstalling?

It is fine now, thank you
