### ISSUE TITLE
Amplify return email undefined for Facebook

### ISSUE THREAD

**Issue by VinhShin** [aws-amplify/amplify-flutter#2191]
### Description

I completed config the lambda triggers, attribute mapping + scope in Cognito

but when I use signInWithWebUI with AuthProvider.facebook, although the email permission was granted but Facebook doesn't send email in lambda triggers

I have printed the event received by "Pre sign-up" Lambda and the user email is undefined.

```
{
  email: undefined,
  event: {
    version: '1',
    region: 'ap-southeast-1',
    userPoolId: 'ap-southeast-1_abc',
    userName: 'facebook_4214633792096019',
    callerContext: {
      awsSdkVersion: 'aws-sdk-unknown-unknown',
      clientId: '12345abcdf'
    },
    triggerSource: 'PreSignUp_ExternalProvider',
    request: { userAttributes: [Object], validationData: {} },
    response: {
      autoConfirmUser: false,
      autoVerifyEmail: false,
      autoVerifyPhone: false
    }
  }
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Screenshots

![Screen Shot 2022-09-29 at 15 56 18](https://user-images.githubusercontent.com/37544201/192991474-05d55f8f-a7a7-42ad-9774-f45bfcf16dbd.png)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel flutter-2.8-candidate.16, 2.10.5, on macOS 12.5.1 21G83 darwin-arm, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
- amplify_auth_cognito 0.6.8
- amplify_flutter 0.6.8
```

### Device

Iphone 13

### OS

IOS 15.6.1

### Deployment Method

Amplify CLI

### Amplify Config

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "1234abcd",
                        "AppClientId": "1234abcd",
                        "AppClientSecret": "1234abcd",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "<domain>",
                            "AppClientId": "1234abcd",
                            "AppClientSecret": "1234abcd",
                            "SignInRedirectURI": "<domain>://login",
                            "SignOutRedirectURI": ""<domain>://logout",
                            "Scopes": [
                                "email",
                                "openid",
                                "phone",
                                "profile"
                            ]
                        },
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "PHONE_NUMBER",
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS"
                            ]
                        },
                        "mfaConfiguration": "OPTIONAL",
                        "mfaTypes": [
                            "SMS",
                            "TOTP"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

**Comment by dnys1** [comment]
Hi @VinhShin, the mapping happens to the user attributes. Can you confirm the `userAttributes` field does not contain the `email` from Facebook? In your log, it shows as `userAttributes: [Object]`.

**Comment by VinhShin** [comment]
yes @dnys1, I confirm
here is the log
```
 "request": {
        "userAttributes": {
            "email_verified": "false",
            "cognito:email_alias": "",
            "cognito:phone_number_alias": "",
            "autoVerifyEmail": true
        },
        "validationData": {}
    }
```

**Comment by dnys1** [comment]
Hmm, could you try adjusting your authorized scopes to be `public_profile, email` (with a comma)? Currently, it says `public_profile email`, but according to the Cognito [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html):
> For Facebook, these should be separated by commas.

**Comment by VinhShin** [comment]
As the attached picture, I have added the commas to separate those scopes
already, I don't know which is wrong, I lost more than a week on this :(

Vào Th 6, 30 thg 9, 2022 vào lúc 22:57 Dillon Nys <
***@***.***> đã viết:

**Comment by fjnoyp** [comment]
Hi @VinhShin we're reaching out internally to get more context of what the expected behavior should be here.  Thanks for your patience.

**Comment by VinhShin** [comment]
hi @fjnoyp @dnys1 
is there any update on this issue :(

**Comment by Jordan-Nelson** [comment]
@VinhShin - Apologies for the long delay in an update. This issue fell off our radar. If you are still facing this issue please let us know and we can try to reproduce it.

**Comment by Jordan-Nelson** [comment]
@VinhShin - I am going to close this out since we have not heard back. If you are still facing this issue please let us know and we can reopen it.
