### ISSUE TITLE
Web support for amplify_api

### ISSUE THREAD

**Issue by likeconan** [aws-amplify/amplify-flutter#2192]
### Description

<img width="564" alt="image" src="https://user-images.githubusercontent.com/12960160/193044168-3a36481d-99b0-48cb-a877-258723b82905.png">
According to the plugins, I also want to use AmplifyAPI in web,

May I ask when will amplify_api graphQL support in web?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale
    zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
```

### Dependencies

```bash
none
```

### Device

Macbook

### OS

Chrome 101

### Deployment Method

Custom Pipeline

### Amplify Config

{
 "api": {
        "plugins": {
            "awsAPIPlugin": {
                "anonymous-iam": {
                    "endpointType": "GraphQL",
                    "endpoint": "$graphqlEndpoint",
                    "region": "${AppConfig().region}",
                    "authorizationType": "AWS_IAM"
                },
                "authenticated-with-user-pool": {
                    "endpointType": "GraphQL",
                    "endpoint": "xxx",
                    "region": "xxx",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
}

**Comment by fjnoyp** [comment]
Hi @likeconan thanks for reaching out.  We are actively working on implementing this for web and will let you know when we have a release schedule prepared.

**Comment by dnys1** [comment]
Hi @likeconan please follow the [Web support ticket](https://github.com/aws-amplify/amplify-flutter/issues/234) for the latest updates. The API category is scheduled to be released next, following the launch of Authentication last month which was our first category to support Flutter Web.
