### ISSUE TITLE
"amplify init" command fails with an error "init failed Error: Failed to zip code.  at WriteStream.<anonymous>...."

### ISSUE THREAD

**Issue by lanouvelleecole** [aws-amplify/amplify-flutter#220]
**Describe the bug**

On Windows 10, the command 'amplify init' starts good, but then fails,
with this error message:

init failed Error: Failed to zip code. 
at WriteStream.<anonymous> 
(C:\Users\jeanetpatrick\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\utils\archiver.js:18:14) 
at WriteStream.emit (events.js:327:22) 
at WriteStream.EventEmitter.emit (domain.js:486:12) 
at C:\Users\jeanetpatrick\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graceful-fs\graceful-fs.js:303:14 
at C:\Users\jeanetpatrick\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graceful-fs\graceful-fs.js:333:16 at FSReqCallback.oncomplete (fs.js:171:23)

**Expected behavior**

Normally a folder amplify, 
along with other files,
like amplifyconfiguration.dart and amplify.json,
should be created,
but only the folder amplify and amplify.json
get created, the file amplifyconfiguration.dart is not created

**Smartphone:**
 - Device: Xiaomi Redmi Go
 - OS: Android 8.1.0

**Comment by jamesonwilliams** [comment]
What version of the Amplify CLI was this?

```console
$ amplify -v
4.41.0
```

Please try again with the latest version.

This issue should be transferred to the Amplify CLI project, cc: @aws-amplify/amplify-flutter

**Comment by Amplifiyer** [comment]
It's been over two months with no update. Resolving as stale. Please search and create an issue here https://github.com/aws-amplify/amplify-cli/issues if you face issues with amplify cli
