### ISSUE TITLE
Following aws flutter tutorial results in xcode build error

### ISSUE THREAD

**Issue by blexo** [aws-amplify/amplify-flutter#2229]
### Description

I am experimenting with the aws amplify todo flutter tutorial - all works great (I can get the todo list working, etc) until I reach this page related to auth:

https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/#add-api-and-auth-plugins

The xcode build fails and I've isolated it to adding this library to the pubspec.yaml:
amplify_api: ^0.6.0

The error is:  
Swift Compiler Error (Xcode): Instance method 'throttle(for:scheduler:latest:)'
requires that 'DispatchQueue' conform to 'Scheduler'

Adding amplify_auth_cognito works just fine...

Thanks!

### Categories

- [ ] Analytics
- [X] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.4 21F79 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.18.2
Flutter SDK 3.3.4
theatre_insight 1.0.0+1

dependencies:
- amplify_auth_cognito 0.6.8 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.8 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.8 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_auth_cognito_android 0.6.8 [flutter]
- amplify_auth_cognito_ios 0.6.8 [amplify_core flutter]
- amplify_core 0.6.8 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.8 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.8 [flutter]
- amplify_flutter_ios 0.6.8 [amplify_core flutter]
- async 2.9.0 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- json_annotation 4.7.0 [meta]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stream_transform 2.0.1
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
```

### Device

iPhone 13 pro simulator

### OS

ios 15.0

### Deployment Method

Amplify CLI

### CLI Version

10.2.3

### Amplify Config

Not sure which config here...

{
  "usageDataConfig": {
    "installationUuid": "XXXXXXXX",
    "isUsageTrackingEnabled": true
  }
}

**Comment by ragingsquirrel3** [comment]
@blexo I believe this is related to an open issue with amplify-ios which has a workaround. Do you mind trying the workaround described in https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/92#issuecomment-1196276837 and seeing if it fixes your build?

**Comment by Jordan-Nelson** [comment]
@blexo - Please let us know if you are still facing an issue after looking at the work around above. Thanks.

**Comment by HuiSF** [comment]
Hi @blexo sorry we didn't hear back from you! Please feel free to reopen this issue and follow up if you need further assistance.
