### ISSUE TITLE
Minor Code Changes

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#223]
Several minor code changes to improve code readability and functionality: 

- Allow comparison of the modelOperation array in modelSchema for Android (for now unit tests in Android ignore the operation of the AuthRule)

- Remove testEnum in codegen folder or add in the AllTypeModel

- onConfigureModelProvider of SwiftAmplifyDatastorePlugin.swift does not throw an error if the args["modelSchemas"] is not castable to a map.

**Comment by Jordan-Nelson** [comment]
I discussed this with @fjnoyp offline and determined we can close this request.
