### ISSUE TITLE
transformRequest infinite loop

### ISSUE THREAD

**Issue by mcku** [aws-amplify/amplify-flutter#2241]
### Description

If one uses their own client such as `MyAmazonHttpClient`, the `send` method invokes transformRequest. I have not looked into it very deeply. I guess it is not supposed to behave this way. 

```
class MyAmazonHttpClient extends AWSBaseHttpClient {
  @override
  Future<AWSBaseHttpRequest> transformRequest(
           AWSBaseHttpRequest request) async =>
       request;
}
```
i am using the client like this: `signedRequest.send(client)`

the custom http client does not display this behavior.

ref:
https://github.com/aws-amplify/amplify-flutter/blob/65a770c00b2fdc434e45f7e8c8f00ec536d8af4b/packages/aws_common/lib/src/http/aws_http_client.dart#L97

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

My code is a bit different but I guess the following will trigger the bug:

```
  final myClient = MyAmazonHttpClient();
  final createResponse = await signedCreateRequest.send(myClient).response;

```
ref: 
https://github.com/aws-amplify/amplify-flutter/blob/next/packages/aws_signature_v4/example/bin/example.dart#L134

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on Fedora Linux 36 (Thirty Six) 5.15.68-1.fc32.qubes.x86_64, locale
    C.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Dependencies

```bash
Dart SDK 2.18.2
Flutter SDK 3.3.4
[...reduced clutter...]
- aws_common 0.2.3 [async collection http2 js json_annotation logging meta stream_transform uuid]
- aws_signature_v4 0.2.2 [async aws_common collection convert crypto json_annotation meta path]
- amplify_auth_cognito 1.0.0-next.0+5 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_authenticator 1.0.0-next.0+3 [amplify_auth_cognito amplify_core amplify_flutter async aws_common collection flutter flutter_localizations intl meta smithy stream_transform]
- amplify_flutter 1.0.0-next.0+3 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
```

### Device

linux

### OS

n/a

### Deployment Method

Amplify CLI

### CLI Version

10.0.0

### Amplify Config

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": 
...
...
       }
   }
}
```

**Comment by dnys1** [comment]
Hi @mcku - sorry you are facing this issue. I've opened a PR with a fix 👍

**Comment by dnys1** [comment]
This has been released in the latest version of `aws_common`. You should be able to run `flutter pub upgrade` to get the changes.
