### ISSUE TITLE
FLUTTER DATASTORE SYNC WITH MULTI AUTH THROWS EXCEPTION WITH UN-AUTHENTICATED USER

### ISSUE THREAD

**Issue by AzharRaeisi** [aws-amplify/amplify-flutter#2252]
**Page**: [`/lib/datastore/setup-auth-rules/q/platform/[platform]`](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter)

**Feedback**:

Tried to setup datastore with multi auth as
type Todo @model @auth(rules: [{allow: private}, {allow: public, operations: [read], provider: iam}]) {
id: ID!
name: String!
description: String
isComplete: Boolean!
} 

datastore sync only works when user is logged in otherwise it always throws an exception
tried with 

1.  ampifly api

- Default auth: Cognito User Pool
- IAM

2.  amplify auth

-     Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes

**Comment by dnys1** [comment]
Hi @AzharRaeisi, sorry to hear you experienced this issue. If it is still not resolved, can you please re-open with the latest [bug report template](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=BUG-REPORT.yaml) which has more information to help us diagnose the issue?
