### ISSUE TITLE
The field you are accessing is not nullable but has a null value. It was marked as required (!) in your schema.graphql but the containing model class was initialized without setting its value

### ISSUE THREAD

**Issue by RamaTechnology** [aws-amplify/amplify-flutter#2277]
### Description

Describe the bug
Hi everyone, I am trying to get data from Amplify table which have two relationships with two different tables, I got data from parent table correctly and also got data from first related table correctly, but I didn't got data from the second table, it's retrieved null, and I got this Error:

AmplifyCodeGenModelException (AmplifyCodeGenModelException(message: The field you are accessing is not nullable but has a null value. It was marked as required (!) in your schema.graphql but the containing model class was initialized without setting its value., recoverySuggestion: Please validate that the containing model class was initialized properly with all requried fields being initialized. This can happen when a nested model is returned but only its id field has been set, underlyingException: Null check operator used on a null value))

I am using Amplify.API.query

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create Three related models using @auth(rules: [{allow: public}])
2. Retrieve Data from parent table and two related table
3. See error

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.4)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.72.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
- amplify_api 0.6.8 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.8 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.8 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.8 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 0.6.8 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface path_provider path]
```

### Device

Android

### OS

0

### Deployment Method

Amplify CLI

### Amplify Config

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0"
}

**Comment by ragingsquirrel3** [comment]
Hey @RamaTechnology do you mind adding a few details here to help us understand the issue? Could you add 1) your graphql schema 2) code snippet where you having this issue.

**Comment by RamaTechnology** [comment]
Hi @ragingsquirrel3 , Thanks for your response, here my QraphQL schema

```
type MainTable @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  firstchildTableID: ID! @index(name: "byFirstChildTable")
  firstChildTable: FirstChildTable! @belongsTo(fields: ["firstchildTableID"])
  secondChildTableID: ID! @index(name: "bySecondChildTable")
  secondChildTable: SecondChildTable! @belongsTo(fields: ["secondChildTableID"])
}

type FirstChildTable @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  mainTable: [MainTable] @hasMany(indexName: "byFirstChildTable", fields: ["id"])
}

type SecondChildTable @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  mainTable: [MainTable] @hasMany(indexName: "bySecondChildTable", fields: ["id"])
}
```

And here when I got the error in this code
```
final request = ModelQueries.list(MainTable.classType);
final response = await Amplify.API.query(request: request).response;
final data = response.data?.items;
if (data == null) {
 print('errors: ${response.errors}');
}
List<MainTable> mainTableData = data.map((val) => MainTable.fromJson(Map<String, dynamic>.from(val))).toList();
```
Then I got below error in SecondChildTable model page
`
AmplifyCodeGenModelException (AmplifyCodeGenModelException(message: The field you are accessing is not nullable but has a null value. It was marked as required (!) in your schema.graphql but the containing model class was initialized without setting its value., recoverySuggestion: Please validate that the containing model class was initialized properly with all requried fields being initialized. This can happen when a nested model is returned but only its id field has been set, underlyingException: Null check operator used on a null value))
`
When Iam trying to print the retrieved data in console, I see the data from FirstChildTable has been appeared, and the data from SecondChildTable didn't not show.

**Comment by Jordan-Nelson** [comment]
Hi @RamaTechnology - Can you confirm that the nested model SecondChildTable exists for the parent MainTable? You can view the data in these tables in the AWS console for DynamoDB.

**Comment by Jordan-Nelson** [comment]
@RamaTechnology - This issue is similar to https://github.com/aws-amplify/amplify-flutter/issues/1814. v0.6.9 included a fix for this. Can you upgrade to v0.6.9 and see if you are still experiencing this issue?

**Comment by Jordan-Nelson** [comment]
@RamaTechnology - Have you had a chance to upgrade to v0.6.9 or later to see if this issue is resolved?

**Comment by MarlonJD** [comment]
Warning: I'm not the this issue's author. 0.6.9 fixed my issue (#1814).
It's the same error on amplify_api 1.0.0-next.1
Same pr #2087 can fix the issue. I'll create new pr for next branch.

**Comment by HuiSF** [comment]
Thanks @MarlonJD for confirming the fix, and thanks again for merging the fix into next branch!

**Comment by MarlonJD** [comment]
@HuiSF thanks, happy to see it's fixed again.

**Comment by jobypthomas** [comment]
@HuiSF @Jordan-Nelson  Trying to upgrade amplify api library "1.0.0" to "2.6.2". This issue re-occured. The dart version of api is "0.5.10". In 1.0.0 query generated data with parent 1 level up. However, in 2.6.2 the parent is retrieved null.
