### ISSUE TITLE
Log too verbose

### ISSUE THREAD

**Issue by Miamoto-Musashi** [aws-amplify/amplify-flutter#2284]
### Description

Amplify datastore keep writing  thousand of Info lines that should be debug

```
I/amplify:aws-datastore(11816): Orchestrator lock released.
I/amplify:aws-datastore(11816): Orchestrator lock acquired.
```

my  **App**

```
GetMaterialApp(
      title: "__",
      enableLog: false,
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
    ),
```

**init amplify**

```
Future<void> _configureAmplify() async {
    try {
      Log.d(tag, message: '_configuring Amplify');
      await Amplify.addPlugins([
        // AmplifyStorageS3(),
        AmplifyDataStore(modelProvider: ModelProvider.instance),
        AmplifyAPI(modelProvider: ModelProvider.instance),
        AmplifyAuthCognito(),
      ]);
      
      
      

      // ** uncomment to wipe data
      // await Amplify.DataStore.clear();
      // Log.w(tag, message: 'DB cleared!');

      await Amplify.configure(amplifyconfig);
...
    } on AmplifyAlreadyConfiguredException {
      Log.w(tag, message: "Tried to reconfigure Amplify; this can occur when your app restart on Android.");
    } on Exception catch (e) {
      Log.e(tag, message: '_configureAmplify $e');
    }
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

normal configuration with API

### Screenshots

<img width="869" alt="Screenshot 2022-10-26 alle 17 07 37" src="https://user-images.githubusercontent.com/283196/198063937-1c5bf838-8129-4c8b-8563-9750d2a2c6be.png">

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 29

### Environment

```bash
[✓] Flutter (Channel stable, 3.3.3, on macOS 13.0 22A380 darwin-x64, locale it-IT)
    • Flutter version 3.3.3 on channel stable at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (4 settimane fa), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.18.2
Flutter SDK 3.3.3
driver 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_secure_storage 6.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- get 4.6.5 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- here_sdk 4.11.4 [ffi intl meta flutter]
- intl 0.17.0 [clock path]
- line_icons 2.0.1 [flutter]

transitive dependencies:
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- ffi 1.1.2
- file 6.1.2 [meta path]
- flutter_secure_storage_linux 1.1.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.15 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- vector_math 2.1.2
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

Emulator

### OS

Android 29

### Deployment Method

Amplify CLI

### CLI Version

10.0.0

### Additional Context

on every operation the logger keep showing debug messages  making my log unusable

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "customer": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://*********.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "************"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "********",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "********",
                        "AppClientId": "********",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL",
                            "PHONE_NUMBER"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://****.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "******",
                        "ClientDatabasePrefix": "*****"
                    },
                    "customer_AWS_IAM": {
                        "ApiUrl": "****.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "*****"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "****",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "****",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';

**Comment by charlieforward9** [comment]
I would like to know how to turn on these verbose logs for my iOS project. I am having an error and not getting any logs to point me in the right direction.

**Comment by Jordan-Nelson** [comment]
@Miamoto-Musashi and @charlieforward9 - We are aware that there are several areas for improvement when it comes to logging. There is an open feature request to improve the experience when it comes to logging - https://github.com/aws-amplify/amplify-flutter/issues/1318. You can give that issue a 👍 and/or follow it for updates.

Improvements to logging have been implemented on the latest developer preview version of Amplify-Flutter, currently [v1.0.0-next.0+4](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.0+4).

I thought it might be helpful to provide some context on this issue. The logs in the issue description are coming from Amplify-Android, which Flutter depends on when targeting Android. We have not exposed an API to set the log level, as a result all the logs are shown. On iOS, these logs are not forwarded to flutter. You can see them if you run the app from Xcode. The actual logs will be a bit different though between the two platforms.

As I mentioned above, improvements to logging have been implemented on the latest developer preview version of Amplify-Flutter. This re-write does not depend on Amplify-iOS or Amplify-Android. Logging between the two platforms will be configurable by log level, and with the exception of a few platform specific differences, the logs generated on both platforms should be the same.

I am going to close this issue out. If you have any questions or comments, please leave them on #1318. Thanks.
