### ISSUE TITLE
[DataStore] Add custom conflict resolution handling

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-flutter#230]

**Comment by mehrdad-shokri** [comment]
2 years old, what's status of this feature?

**Comment by HuiSF** [comment]
amplify-flutter [0.5.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.5.0) has released, including capability of configuring `conflictHandler` for DataStore.
Examples please refer to [this documentation](https://docs.amplify.aws/lib/datastore/conflict/q/platform/flutter/#custom-configuration-fields).

Please feel free to follow up if anything. Thanks!
