### ISSUE TITLE
_AssertionError ('package:amplify_authenticator/src/state/auth_state.dart': Failed assertion: ....

### ISSUE THREAD

**Issue by momotaro1105** [aws-amplify/amplify-flutter#2311]
**Which Specific Feature is your question related to?**
amplify_authenticator/src/state/auth_state.dart
Staging environment for flutter app

**Provide additional details e.g. code snippets**
I haven't changed anything from the original UI component besides adding Japanese localization to it.
So far, I have seen this issue twice, once when user was trying to login after account creation, and second, when user tried resetting password. I am only using phone number auth. Both times, the program threw a similar issue to below (the latter copied here), and the app simulator froze without navigating to a different screen. 

However, when the app was relaunched, the user seemed to already be logged in without any further concerns, and signout is performed without any issues.
What am I doing wrong and how do I fix this?

`_AssertionError ('package:amplify_authenticator/src/state/auth_state.dart': Failed assertion: line 98 pos 11: 'step == AuthenticatorStep.signIn ||
              step == AuthenticatorStep.confirmSignUp': Invalid AuthenticatorStep type: AuthenticatorStep.confirmResetPassword)`

**Comment by Jordan-Nelson** [comment]
Hi @momotaro1105 - I was able to reproduce this. In my reproduction, I see the assertion error, but it does not impact the application. I am able to successfully reset a password and login. I do see the error message in the logs, and if I have my IDE setup to break on uncaught exceptions, it will break on this assertion. Is that what you are experiencing as well?

I will open a PR to remove the assertion error, but you should be able to ignore it. The assertion will be removed in a release build.

**Comment by momotaro1105** [comment]
hello @Jordan-Nelson thank you for checking, yes, I always use "Run and Debug" for which I think the break on uncaught exceptions are turned on by default.

**Comment by dnys1** [comment]
Hi @momotaro1105 - a fix for this has been published in version 0.6.10 of the library.
