### ISSUE TITLE
Social Sign-In (Google/Facebook) returning generic error.

### ISSUE THREAD

**Issue by ignitum-ryan** [aws-amplify/amplify-flutter#2320]
### Description

With no changes to our authentication code, social sign-in (specifically Google and Facebook in our case) are no longer authenticating users. This is on both Android and iOS. When choosing to sign-in, the user is is prompted that Cognito is requesting to use Sign-in permissions. When the user clicks 'Continue', the web view loads for a second and then returns the error message: 'An error has encountered with the requested page'.

There are no logs/errors/reasons popping up in both the console and AuthHubEvents. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Implement Amplify Auth into the Flutter application.
2. Setup social sign-in for both Google and/or Facebook.
3. Build the application and attempt to sign-in to the social provider.

### Screenshots

![image](https://user-images.githubusercontent.com/97566760/200334865-a9ae48eb-b772-4da4-98e5-435989347403.png)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.18.4
Flutter SDK 3.3.7
app-name 0.0.10+10

dependencies:
- algolia 1.1.1 [meta http uuid universal_io]
- amplify_api 0.6.9 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.9 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_datastore 0.6.9 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.9 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 0.6.9 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface path_provider path]
- cached_network_image 3.2.2 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.1.1 [flutter]
- crop_your_image 0.7.2 [flutter image]
- cupertino_icons 1.0.5
- dash_chat_2 0.0.15 [cached_network_image flutter flutter_parsed_text intl url_launcher video_player]
- detectable_text_field 2.0.4 [flutter]
- dropdown_search 5.0.3 [flutter]
- faker 2.0.0 [crypto]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_contacts 1.1.5+1 [flutter]
- flutter_dotenv 5.0.2 [flutter]
- flutter_form_builder 7.7.0 [flutter intl collection]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_typeahead 4.1.1 [flutter flutter_keyboard_visibility]
- get 4.6.5 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- image_picker 0.8.6 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- json_annotation 4.7.0 [meta]
- linkedin_login 2.2.1 [flutter http meta rxdart uuid webview_flutter]
- modal_bottom_sheet 2.1.2 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- sentry_flutter 6.14.0 [flutter flutter_web_plugins sentry package_info_plus meta]
- shimmer 2.0.0 [flutter]
- url_launcher 6.1.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

transitive dependencies:
- amplify_api_android 0.6.9 [flutter]
- amplify_api_ios 0.6.9 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.9 [flutter]
- amplify_auth_cognito_ios 0.6.9 [amplify_core flutter]
- amplify_core 0.6.9 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.9 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.9 [flutter]
- amplify_flutter_ios 0.6.9 [amplify_core flutter]
- amplify_storage_s3_android 0.6.9 [flutter]
- amplify_storage_s3_ios 0.6.9 [flutter]
- archive 3.3.2 [crypto path]
- async 2.10.0 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- cross_file 0.3.3+2 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- ffi 2.0.1
- file 6.1.4 [meta path]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_keyboard_visibility 5.4.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- html 0.15.1 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 3.2.2 [archive meta xml]
- image_picker_android 0.8.5+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.10 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6+1 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- material_color_utilities 0.1.5
- meta 1.8.0
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_info_plus 3.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.2
- path_provider_android 2.0.21 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- rxdart 0.27.5
- sentry 6.14.0 [http meta stack_trace uuid intl]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.0+3 [flutter sqflite_common path]
- sqflite_common 2.4.0+2 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.0.0+3
- term_glyph 1.2.1
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.21 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- video_player 2.4.7 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.7 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.4 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 3.0.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

iPhone/Android

### OS

N/A

### Deployment Method

Amplify CLI

### CLI Version

10.4.0

### Additional Context

We are using PURELY CLI created infrastructure.

### Amplify Config

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "givetoget": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "AdminQueries": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/dev",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-2_xxxxxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxxxxxxxxx.auth.us-east-2.amazoncognito.com",
                            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                            "SignInRedirectURI": "app-url://",
                            "SignOutRedirectURI": "app-url://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL",
                            "NAME"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OPTIONAL",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
                        "Region": "us-east-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "givetoget_AMAZON_COGNITO_USER_POOLS"
                    },
                    "givetoget_AWS_IAM": {
                        "ApiUrl": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
                        "Region": "us-east-2",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "appname_AWS_IAM"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "appname-randomcharacters-dev",
                        "Region": "us-east-2"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "appname-bucket-dev",
                "region": "us-east-2",
                "defaultAccessLevel": "guest"
            }
        }
    }
}

**Comment by ignitum-ryan** [comment]
I would also like to note, we did validate that the endpoints in the amplifyconfig are valid to the Cognito endpoints. (If that wasn't clear in my original post).

**Comment by ignitum-ryan** [comment]
Hey @dnys1 , that is correct. Last tuesday (11/1), it was working. On (11/2), no changes to auth at all, it no longer was working. Reviewing the git commit history of ALL changes made to anything auth related, I found the following updates to the amplifyconfig file (none which I believe would have caused this):

`                          - "SignInRedirectURI": "appname://",
                            - "SignOutRedirectURI": "appname://",
                            + "SignInRedirectURI": "appname://,appname://",
                            + "SignOutRedirectURI": "appname://,appname://",
`

I made this change because the day before this stopped working, I was instructed with a Cognito error stating that the redirect_uri for sign out was invalid. I added another record to the recordset, and it allowed successful sign-in/out after making the change. Since then, I've tried removing one of the records to make the social sign-in function again to no avail.

Second, we also made updates to the backend-config.json:
`      - "socialProviders": [],
        + "socialProviders": [
        + "FACEBOOK",
        + "GOOGLE"
        +],
`
`      - "mfaConfiguration": "OFF",
        + "mfaConfiguration": "OPTIONAL",
`

I have not attempted to revert the backend-config.json yet, but I can if you believe it may be fruitful to solving the error. It's important to note, however, that even with the above mentioned changes to the respective files, we DID have successful social logins for a few days before it started giving the error mentioned in my original post.

**Comment by Jordan-Nelson** [comment]
Can you confirm that social sign in was working for both providers (Facebook and Google) and has stopped working for both?

Is it possible that changes were made in the Cognito AWS Console?

**Comment by ignitum-ryan** [comment]
Hi @Jordan-Nelson ,

Apologies for the delay. I had not heard of these troubleshooting methods, so thank you. I was able to get the debugger tied to our simulator. Unfortunately, there was not a lot of useful information. This was the only error that I could get to show:

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/97566760/201538184-575bb835-e472-4078-9fa2-d4982d634e41.png">

**Comment by dnys1** [comment]
Hi @ignitum-ryan, I believe this is indeed the issue.

> - "SignInRedirectURI": "appname://",
> - "SignOutRedirectURI": "appname://",
> + "SignInRedirectURI": "appname://,appname://",
> + "SignOutRedirectURI": "appname://,appname://",

Amplify `0.x` versions do not do a good job of parsing multiple URIs in these properties. Reverting back to a single `appname://` for each should fix the issue.

**Comment by ignitum-ryan** [comment]
@dnys1 - I swear on my first-born that I attempted to remove these (from the UI in Cognito, not the Amplify CLI parameters file), to no avail.

HOWEVER... did confirm that after updating both the amplifyconfiguration.json and parameters.json file (inside the amplify backend files) that the Google and Facebook login are working once again. 

Thank you both so much for the help @dnys1 / @Jordan-Nelson
