### ISSUE TITLE
[web] Generated models contain `Type.toString()`

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2330]
### Description

Generated models call `toString()` on Dart `Type` instances in multiple places which breaks Web usages of `ModelType` and `ModelProviderInterface`.

- [`ModelType.modelName()`](https://github.com/aws-amplify/amplify-flutter/blob/54fa585c64e5f6d48e991e8f376c0adad6ced386/packages/amplify_core/lib/src/types/models/model.dart#L66) calls `T.toString()`
- Generated models call `Type.toString()` when referencing nested models, e.g. https://github.com/aws-amplify/amplify-flutter/blob/54fa585c64e5f6d48e991e8f376c0adad6ced386/packages/amplify_test/lib/test_models/Blog.dart#L247

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
-
```

### Dependencies

```bash
-
```

### Device

-

### OS

-

### Deployment Method

Amplify CLI

### Amplify Config

-

**Comment by jobypthomas** [comment]
@dnys any eta on the release? This issue prevents running GQL api in Flutter web when deployed.

**Comment by abdallahshaban557** [comment]
This issue has now been fixed with CLI version 10.6.0. Please update the CLI and run `amplify codegen models` in your terminal!

**Comment by jobypthomas** [comment]
@abdallahshaban557 Awesome. Amplify v10.6.0 fixed the issue. Much appreciate your help.
