### ISSUE TITLE
0.0.1-dev.4 not working on iOS Simulator

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#235]
Hi,

updated from 0.0.1-dev.3 to 0.0.1-dev.4 and iOS is no longer working. 
When i try to run my app on iOS Simulator with 'flutter run --verbose' it stucks at:

[   +7 ms] Waiting for observatory port to be available...

I can see, that the App is starting but immediately exits. 

When trying to run it with xcode (12.2) i got:
```
dyld: Symbol not found: _OBJC_CLASS_$_Reachability
  Referenced from: /Users/ray/Library/Developer/CoreSimulator/Devices/8624702A-F016-41C0-94A9-5009A1E7C283/data/Containers/Bundle/Application/4D1D0FC7-CC36-44B3-8CFD-7EEF1116C90F/Runner.app/Frameworks/connectivity.framework/connectivity
  Expected in: /Users/ray/Library/Developer/CoreSimulator/Devices/8624702A-F016-41C0-94A9-5009A1E7C283/data/Containers/Bundle/Application/4D1D0FC7-CC36-44B3-8CFD-7EEF1116C90F/Runner.app/Frameworks/Reachability.framework/Reachability
 in /Users/ray/Library/Developer/CoreSimulator/Devices/8624702A-F016-41C0-94A9-5009A1E7C283/data/Containers/Bundle/Application/4D1D0FC7-CC36-44B3-8CFD-7EEF1116C90F/Runner.app/Frameworks/connectivity.framework/connectivity
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/ray/Library/Developer/CoreSimulator/Caches/dyld/20B50/com.apple.CoreSimulator.SimRuntime.iOS-14-2.18B79
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/ray/Library/Developer/Xcode/DerivedData/Runner-gwilnoqdiooiardbsmggksmsyxsq/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Prof
(lldb) 
```

Its working on Android without an Issue. If i switch back to  0.0.1-dev.3 its working again.

flutter doctor -v:
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-DE)
    • Flutter version 1.22.4 at /Users/ray/dev/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ray/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max (Simulator) & iPhone 12 Pro (Simulator)
 - OS: iOS 14.2

**Comment by Ashish-Nanda** [comment]
@Rayv1 what plugins are you using? Can you share your `pubspec.yaml` file?

I think this might be related to this issue related to an Amplify iOS dependency: https://github.com/aws-amplify/amplify-ios/issues/797

Do you not see this issue once you switch back to `0.0.1-dev.3`?

**Comment by Rayv1** [comment]
@Ashish-Nanda sure!

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 
  carousel_slider: 
  amazon_cognito_identity_dart_2:  
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.3.3
  intl:  
  percent_indicator: 
  flutter_svg: 
  image_picker: 
  permission_handler: ^5.0.1+1 
  image:  
  mime: 
  auto_size_text: 
  pull_to_refresh:  
  dio:  
  package_info:
  bot_toast: 
  sentry: ">=3.0.0 <4.0.0" 
  sembast: ^2.4.8 
  path_provider: ^1.6.21
  fl_chart: ^0.12.0 
  collection:  
  jiffy:
  hive: ^1.4.4+1 
  hive_flutter: ^0.3.1 
  sqflite: ^1.3.1+1  
  stacked: ^1.7.6  
  auto_route:  
  stacked_services: ^0.5.4+4 
  stacked_hooks: ^0.1.3+1 
  get_it: ^5.0.1
  injectable: ^1.0.5 
  google_sign_in: ^4.5.1 
  extension_google_sign_in_as_googleapis_auth: ^1.0.1 
  googleapis: ^0.56.1 
  font_awesome_flutter: ^8.10.0 
  amplify_core: ^0.0.1-dev.4 
  amplify_auth_cognito: ^0.0.1-dev.4
  encrypt: ^4.0.2
  flutter_secure_storage: ^3.3.5  
  convex_bottom_bar: ^2.4.1 
  flutter_holo_date_picker: ^0.2.1 
  connectivity: ^0.4.9+3
  flutter_appauth: ^0.9.2+5 
  json_annotation: 
  # firebase_ml_vision: ^0.9.7
  url_launcher: ^5.7.5
  flutter_datetime_picker: ^1.4.0
  timezone: ^0.5.9
  easy_localization: ^2.3.3
  flutter_swiper: ^1.1.6 
  async: ^2.4.2 
  flutter_barcode_scanner: 
    git:
      url: https://github.com/Rayv1/flutter_barcode_scanner.git
  quiver: ^2.1.3
  flutter_localizations:
    sdk: flutter  
  

dev_dependencies:
  hive_generator: 
  auto_route_generator:
  intl_translation: 
  injectable_generator:
  build_runner: 
  json_serializable:
  flutter_test:
    sdk: flutter

**Comment by Rayv1** [comment]
Yep, its the [connectivity](https://pub.dev/packages/connectivity) Package from flutter.dev 

Does that mean I cannot use the two packages together?

**Comment by Ashish-Nanda** [comment]
@Rayv1 

We have communicated the issue with the Amplify iOS team and they are looking into it. In the meanwhile can you continue with `0.0.1-dev.3`?

**Comment by haverchuck** [comment]
https://github.com/aws-amplify/amplify-ios/issues/797

**Comment by NimaSoroush** [comment]
`amplify_datastore` needs `amplify_core: 0.0.1-dev.4` at least

**Comment by Ashish-Nanda** [comment]
@NimaSoroush
Thats correct, however from the `pubspec.yaml` provided above it seems @Rayv1 is not using amplify_datastore and can downgrade until we have the fix.

Are you having this issue ?

**Comment by Rayv1** [comment]
@Ashish-Nanda  downgrade is not possible, because there is a SessionToken Bug dev-3 which returns null for iOS. Iam using the Connectivity Package for the offline sync with Dynamodb via Appsync, which was now introduced with dev-4. As my App is still in Beta, i try to switch to datastore module. But i think its a big Issue, as the Connectivity Plugin is one of the most popular Flutter plugin.

**Comment by Ashish-Nanda** [comment]
@Rayv1 
Thank you for the additional details. I definitely agree this is an issue, and have communicated this to the iOS team internally. They are looking into it, and I will post an update as soon as we have something.

**Comment by Ashish-Nanda** [comment]
@Rayv1 do you have a sample app we can use to reproduce the issue? The iOS team is working on the fix right now and we would like to validate it.

**Comment by Rayv1** [comment]
@Ashish-Nanda create a new Flutter project and import:
  connectivity: ^2.0.2
  amplify_core: ^0.0.1-dev.4
  amplify_auth_cognito: ^0.0.1-dev.4

in the pubspec yaml file. 

Cheers

**Comment by gazreese** [comment]
I'm also running into the issue

**Comment by varun-esotec** [comment]
👋🏽 - Hi guys. 

Wondering if updating your dependency to https://github.com/aws-amplify/amplify-ios/releases/tag/1.5.2 will help resolve the issue.

🤞🏽 Hoping y'all will cut a new release with `1.5.2` so that I can mess around with GraphQL + AppSync

**Comment by marwfair** [comment]
I'm having the same issue.

**Comment by marwfair** [comment]
@Rayv1 Yes. I updated the dependencies to `0.0.1-dev.6`, but still having the issue.

**Comment by Rayv1** [comment]
@marwfair okay, thanks for sharing with me. Then i dont have to update :)

**Comment by NimaSoroush** [comment]
Any update on this?

**Comment by Rayv1** [comment]
@Ashish-Nanda do you know when this will be fixed for amplify flutter?

**Comment by Ashish-Nanda** [comment]
@Rayv1 What version of Amplify iOS dependencies do you have locally? We should be using the latest version now which has the fix that went into version `1.5.2` of Amplify iOS

Can you do the following:
```
rm -rf Pods
rm Podfile.lock 
pod update 
```
Then do 
```
flutter clean && flutter run
```
Let us know if you still face the issue.

**Comment by Rayv1** [comment]
Okay, i can confirm that it works for me with version `0.0.1-dev.6` .  I did exactly what @Ashish-Nanda wrote.

**Comment by Rayv1** [comment]
this can be closed
