### ISSUE TITLE
Model Helpers should allow setting `GraphQLRequest` parameters

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2352]
Currently, model helpers do not allow setting `GraphQLRequest` parameters like `apiName`, `authorizationMode`, `headers`, etc. This prevents them from being used in multi-auth settings.

**Current**
```dart
static GraphQLRequest<T> create<T extends Model>(T model);
```

**Expected**
```dart
static GraphQLRequest<T> create<T extends Model>(
  T model, {
  String? apiName,
  APIAuthorizationType? authorizationMode,
  Map<String, String>? headers,
});
```

**Comment by ragingsquirrel3** [comment]
released w https://pub.dev/packages/amplify_api/versions/1.0.0-next.1+1
