### ISSUE TITLE
Package uuid v3.0.7 can't be used if aws_common v0.1.1 is used

### ISSUE THREAD

**Issue by asaarnak** [aws-amplify/amplify-flutter#2371]
Because amplify_flutter >=0.6.4 <1.0.0-next.0 depends on aws_common ^0.1.1 which depends on uuid 3.0.6, amplify_flutter >=0.6.4 <1.0.0-next.0 requires uuid 3.0.6.

**Comment by Jordan-Nelson** [comment]
Hello @asaarnak - Thanks for opening the issue. We will take a look at this.

As a temporary workaround, you can likely specify a dependency override as mentioned here: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by asaarnak** [comment]
Thanks!

**Comment by Jordan-Nelson** [comment]
Hi @asaarnak - This dropped off my radar. Apologies for that. Thanks for opening the PR. I left a suggested change. If you have a chance to update it I think we can get that merged.

**Comment by Jordan-Nelson** [comment]
https://github.com/aws-amplify/amplify-flutter/pull/2372 has just been merged. This will be included in the next stable release. Thanks again for the PR.

**Comment by dnys1** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
