### ISSUE TITLE
DataStore CodeGen - Amplify CLI - Enum field problems.

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#241]
**Describe the bug**
There are a few problems with the code generated by Amplify CLI codegen for Flutter DataStore models.
1. Nullable enums aren't serialized/deserialized correctly when null and are rejected when sent to AppSync.
1. Lists of enums generate models that won't compile.

**To Reproduce**
1. Use the following schema.graphql file on a Flutter DataStore project.
```graphql
type TestModel @model {
  id: ID!

  enumVal: TestEnum!

  # Android - Appears to works locally but is rejected by AppSync if set to null.
  # iOS - Seems like this won't get saved at all, even locally, if set to null.
  nullableEnumVal: TestEnum

  # Any of the following generates a .dart model file that won't build.
  # enumList: [TestEnum!]!
  # enumNullableList: [TestEnum!]
  # nullableEnumList: [TestEnum]!
  # nullableEnumnNullableList: [TestEnum]
}

enum TestEnum {
  VALUE_ONE
  VALUE_TWO
}
```
2. You probably won't need this but I've created an [example project here](https://github.com/kjones/datastore_enum_test) just in case...

**Expected behavior**
Proper codegen .dart model generation for enums.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Smartphone (please complete the following information):**
 - iOS and Android Emulators.

**Additional context**
Serialization code produced by the Amplify CLI.
```dart
  TestModel.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        enumVal = enumFromString<TestEnum>(json['enumVal'], TestEnum.values),
        // This doesn't check for null but works since the string 'null' doesn't match any enum value.
        nullableEnumVal =
            enumFromString<TestEnum>(json['nullableEnumVal'], TestEnum.values);

  Map<String, dynamic> toJson() => {
        'id': id,
        'enumVal': enumToString(enumVal),
        'nullableEnumVal': enumToString(nullableEnumVal)  // This converts a null enum to the string 'null'.
      };
```

**Wish list**
- Generated model code should at least pass all [pedantic](https://pub.dev/packages/pedantic) linter rules and not rely on implicit or dynamic casts. Other more strict options welcome (e.g. [lint rules](https://pub.dev/packages/lint)).
- Generated filenames should match [Effective Dart Style](https://dart.dev/guides/language/effective-dart/style).

**Comment by kjones** [comment]
I am finding other problems with the dart model codgen. For now I'll list them here but if you would like separate issues opened I can do that.

**Incorrect generation of `@required` parameters**
The following schema.graphql file:
```graphql
type TestModel @model {
  id: ID!
  floatVal: Float!
  floatNullableVal: Float
  floatList: [Float!]!
  floatNullableList: [Float!]
  nullableFloatList: [Float]!
  nullableFloatNullableList: [Float]
}
```
Generates the following TestModel factory:
```dart
factory TestModel(
  {@required String id,
  @required double floatVal,
  double floatNullableVal,
  @required List<double> floatList,
  @required List<double> floatNullableList,    // Not required - List can be null
  List<double> nullableFloatList,                      // Required - List can't be null
  List<double> nullableFloatNullableList}) 
```
Looks like `copyWith()` also has this problem. This will get a lot easier when we can just use nullsafety... `List<double>`, `List<double?>`, `List<double>?`, `List<double?>?`.

**Comment by haverchuck** [comment]
@kjones Individual GH issues for each identified problem would be  much appreciated!

**Comment by Amplifiyer** [comment]
@kjones the fixes have been released, can you try with the latest amplify cli version (`npm i -g @aws-amplify/cli`) and latest amplify-flutter library. If you are working in an old amplify workspace, please also update the `cli.json` file in the amplify folder to set the flag `useAppSyncModelgenPlugin` to `true`

```json
{
    "features": {
        "codegen": {
            "useAppSyncModelgenPlugin": true
        }
    }
}
```

**Comment by kjones** [comment]
Alright, I'm going to say this is fixed with caveats.
- Setting fields to null requires #301 and an update to use Amplify Android SDK [with this nullable fix](https://github.com/aws-amplify/amplify-android/pull/1091).
- GraphQL schema definitions with arrays are [completely broken](#289) at the moment. [iOS only for me](https://github.com/aws-amplify/amplify-flutter/issues/289#issuecomment-755975418)

Also, I must be watching the wrong repo for the Flutter model codegen changes for this. I didn't see any issues or PRs in the amplify-cli repo. Can you point me to where this work took place so I can follow along in the future?
