### ISSUE TITLE
DataStore CodeGen - Incorrect generation of `@required` parameters

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#242]
**Describe the bug**
Amplify CLI codegen for Flutter DataStore models does not correctly generate `@required` parameter metadata tags.

**To Reproduce**
1. Use the following schema.graphql file on a Flutter DataStore project.
```graphql
type TestModel @model {
  id: ID!
  floatVal: Float!
  floatNullableVal: Float
  floatList: [Float!]!
  floatNullableList: [Float!]
  nullableFloatList: [Float]!
  nullableFloatNullableList: [Float]
}
```
2. Run `amplify codegen models` which produces a model with the following factory:
```dart
factory TestModel(
  {@required String id,
  @required double floatVal,
  double floatNullableVal,
  @required List<double> floatList,
  @required List<double> floatNullableList,        // Not required - List can be null
  List<double> nullableFloatList,                  // Required - List can't be null
  List<double> nullableFloatNullableList}) 
```
Looks like `copyWith()` also has this problem.

**Expected behavior**
`@required` annotations should only be placed on non-nullable fields.

**Comment by Amplifiyer** [comment]
Fix has been released. please see https://github.com/aws-amplify/amplify-flutter/issues/241#issuecomment-755565445

**Comment by kjones** [comment]
Looks good with cli 4.41.0 and `"useAppSyncModelgenPlugin": true`.
