### ISSUE TITLE
`amplify codegen models` is not implement `ModelIdentifier get modelIdentifier`

### ISSUE THREAD

**Issue by lien-dkseo** [aws-amplify/amplify-flutter#2424]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.18.1

### Amplify CLI Version

10.5.1

### What operating system are you using?

Windows

### Amplify Codegen Command

codegen models

### Describe the bug

```
abstract class Model {

  ModelIdentifier get modelIdentifier {
    throw UnimplementedError(
        'modelIdentifier has not been implemented on Model.');
  }
```
- no overriding `modelIdentifier`
- UnimplementedError('modelIdentifier has not been implemented on Model.')

![image](https://user-images.githubusercontent.com/91306431/203680942-af6cd904-fa9b-4764-92bb-46ebcdd9bae5.png)

### Expected behavior

1. implement `modelIdentifier`
2. return `model identifier`

### Reproduction steps

1. amplify codegen models

### GraphQL schema(s)

<details>

```graphql
type Todo @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  description: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by HuiSF** [comment]
Hi @lien-dkseo wanted to check in with you if the above mentioned steps helped with your issue. Please let us know, thanks!

**Comment by Jordan-Nelson** [comment]
@lien-dkseo - I am going to close this out since the suggestion above should resolve this issue

**Comment by lien-dkseo** [comment]
@HuiSF 
fixed in the latest version. thank you~
