### ISSUE TITLE
DataStore CodeGen - Amplify CLI - `@copyWith()` shouldn't have required fields.

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#243]
**Describe the bug**
`copyWith()` shouldn't have required fields on models generated by `amplify codegen models`.

**Expected behavior**
The whole point of a `copyWith()` method is that you only have to specify the fields that change.

**Wish List**
Also wished it acted more like [copyWith() from freezed](https://github.com/rrousselGit/freezed) which supports setting a member to null when making a copy.

**Comment by Amplifiyer** [comment]
Thanks @kjones for helping us test the datastore category and creating issues. I've communicated these issues with Amplify CLI team and will be fixing them on priority!

**Comment by kjones** [comment]
@Amplifiyer - Good to hear.

I've been using my [own hacked version](https://github.com/kjones/flutter-datastore-example) of a Flutter DataStore plugin for several months now and it's been working great but a bit of a pain to use every time I changed the schema.

I was hoping to switch over to the official AWS Flutter DataStore SDK but ran into several problems. Pretty much all related to model generation. My schema is [fairly simple at the moment](https://gist.github.com/kjones/fe002cb7c6b86af995a83ccc150999f4) but will get more complicated over the coming months.

Thanks again for jumping on this.

**Comment by Amplifiyer** [comment]
Fix has been released. please see https://github.com/aws-amplify/amplify-flutter/issues/241#issuecomment-755565445

**Comment by kjones** [comment]
Looks good with cli 4.41.0 and `"useAppSyncModelgenPlugin": true`.

**Comment by hyobbb** [comment]
@Amplifiyer sorry to comment on closed issue. I am using amplify 4.44.2 but still copyWith() method has required annotation.

**Comment by Amplifiyer** [comment]
@hyobbb are you using this fix https://github.com/aws-amplify/amplify-flutter/issues/241#issuecomment-755565445 along with 4.44.2 version of the cli? Can you try on a new amplify project to see if you are able to replicate your issue?

**Comment by hyobbb** [comment]
@Amplifiyer After recreate amplify project with 4.44.4 version it works fine. I think it should be mentioned in document to update amplify version before start project. Thank you!
