### ISSUE TITLE
Cognito sign in failure only in Android without any further exceptions.

### ISSUE THREAD

**Issue by saculNiot** [aws-amplify/amplify-flutter#2433]
### Description

This issue only happens in Android. When I sign in in Android, at first it will stuck at 
`W/CognitoUserSession(13691): CognitoUserSession is not valid because idToken is null.
[        ] D/AWSMobileClient(13691): Sending password.
[        ] D/AWSMobileClient(13691): Using USER_SRP_AUTH for flow type.` 
Then, at the end `[ +314 ms] E/amplify:flutter:auth_cognito(13691): AuthException
[   +3 ms] I/flutter (13691): Sign in failed`. So, I am not sure what is the error regarding the issue. I am using amplify_flutter : 0.6.10 and amplify_auth_cognito : 0.6.10

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 28

### Environment

```bash
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] VS Code (version 1.63.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
- amplify_auth_cognito 0.6.10 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_flutter 0.6.10 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- another_flushbar 1.12.29 [flutter]
- cupertino_icons 1.0.5
- flex_color_scheme 6.1.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.6.13 [flutter markdown meta path]
- flutter_screenutil 5.6.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- provider 6.0.4 [collection flutter nested]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- string_validator 0.3.0
```

### Device

Pixel 5

### OS

Android 8.0

### Deployment Method

Amplify CLI

### CLI Version

10.2.3

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "",
                        "AppClientId": "",
                        "Region": ""
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "",
                            "AppClientId": "",
                            "SignInRedirectURI": "http://localhost:3000/",
                            "SignOutRedirectURI": "http://localhost:3000/signout",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

**Comment by HuiSF** [comment]
Hi @saculNiot looking at the content of your `amplifyconfiguration.dart`, are you using [social sign in](https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#setup-your-auth-provider)?

Could you also provide entire logs around the sign in?

**Comment by saculNiot** [comment]
Hi, thanks for the reply, I am not using social sign in. However, even I have removed the OAuth from configuration, the same issue still remains. Here is the log when I sign in
`[ +108 ms] W/CognitoUserSession( 3953): CognitoUserSession is not valid because idToken is null.
[        ] D/AWSMobileClient( 3953): Sending password.
[   +2 ms] D/AWSMobileClient( 3953): Using USER_SRP_AUTH for flow type.
[  +40 ms] D/EGL_emulation( 3953): app_time_stats: avg=1036.05ms min=2.16ms max=10258.80ms count=10
[ +862 ms] D/EGL_emulation( 3953): app_time_stats: avg=9.24ms min=3.81ms max=123.33ms count=54
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.66ms min=3.32ms max=6.59ms count=60
[+1001 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.90ms min=3.50ms max=15.09ms count=60
[+1013 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.09ms min=3.32ms max=6.94ms count=61
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.17ms min=3.13ms max=5.32ms count=60
[+1015 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.99ms min=3.33ms max=9.26ms count=61
[+1001 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.79ms min=3.34ms max=7.36ms count=60
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=5.07ms min=3.43ms max=9.35ms count=60
[+1015 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.45ms min=3.43ms max=7.44ms count=61
[+1016 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.28ms min=3.11ms max=7.46ms count=61
[+1003 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.23ms min=3.28ms max=6.77ms count=60
[+1013 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.37ms min=3.27ms max=9.17ms count=61
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.11ms min=3.26ms max=6.49ms count=60
[+1016 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.16ms min=3.04ms max=8.45ms count=61
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.03ms min=3.28ms max=5.74ms count=60
[+1001 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.08ms min=3.43ms max=6.06ms count=60
[+1014 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.35ms min=3.45ms max=7.15ms count=61
[ +998 ms] I/flutter ( 3953): Error: google_fonts was unable to load font NotoSans-Regular because the following exception occurred:
[        ] I/flutter ( 3953): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/4c1661f6a9a227f31867ac2e3d3c5bede223077c546d2cd03fb342629e2eebef.ttf
[   +1 ms] I/flutter ( 3953): See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
[        ] I/flutter ( 3953): If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/google-fonts-flutter/issues/new .
[   +5 ms] D/EGL_emulation( 3953): app_time_stats: avg=3.86ms min=3.18ms max=8.07ms count=60
[+1010 ms] D/EGL_emulation( 3953): app_time_stats: avg=3.96ms min=3.34ms max=4.88ms count=61
[+1000 ms] D/EGL_emulation( 3953): app_time_stats: avg=4.29ms min=3.38ms max=7.83ms count=60
[ +421 ms] E/amplify:flutter:auth_cognito( 3953): AuthException
[   +4 ms] I/flutter ( 3953): Sign in failed`

**Comment by HuiSF** [comment]
>Hi, thanks for the reply, I am not using social sign in. However, even I have removed the OAuth from configuration, the same issue still remains

To clarify how did you remove OAuth? Via Amplify CLI `amplify update auth`?

>[ ] I/flutter ( 3953): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/4c1661f6a9a227f31867ac2e3d3c5bede223077c546d2cd03fb342629e2eebef.ttf
[ +1 ms] I/flutter ( 3953): See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.

This error suggests that your testing Android device/emulator or your App doesn't have network connectivity, can you check on this?

**Comment by saculNiot** [comment]
Okay thanks a lot, the issue is due to the Internet connection as the Android Emulator is not connected to Wifi by default.
