### ISSUE TITLE
Question: Will the DataStore start()/stop() API be exposed in Flutter?

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#245]
https://docs.amplify.aws/lib/datastore/other-methods/q/platform/android
https://docs.amplify.aws/lib/datastore/other-methods/q/platform/ios

I guess I could perform a throw-away query to emulate start(). Is there something equivalent to stop() that doesn't discard all local data like clear() does?

**Comment by jamesonwilliams** [comment]
Good callout @kjones, yes, we should add these.

**Comment by haverchuck** [comment]
@kjones Thanks for mentioning this.  I'm labeling the issue as a feature request.

**Comment by raywhiteside** [comment]
Currently I'm seeing this exception being thrown when configuring Amplify before logging in:

```
DataStoreException{message=Error during subscription., cause=ApiException{message=You must be signed-in with Cognito Userpools to be able to use getTokens, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
```

DataStore works fine after logging in, but this exception may indicate DataStore.start() is more of a bug fix than a feature request?

[This comment](https://github.com/aws-amplify/amplify-android/issues/802#issuecomment-721895666) mentions DataStore not calling start() on configuration, it's not clear to me if this is going to work its way in to amplify-flutter shortly?

**Comment by infernal008** [comment]
> Currently I'm seeing this exception being thrown when configuring Amplify before logging in:
> 
> ```
> DataStoreException{message=Error during subscription., cause=ApiException{message=You must be signed-in with Cognito Userpools to be able to use getTokens, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
> ```
> 
> DataStore works fine after logging in, but this exception may indicate DataStore.start() is more of a bug fix than a feature request?
> 
> [This comment](https://github.com/aws-amplify/amplify-android/issues/802#issuecomment-721895666) mentions DataStore not calling start() on configuration, it's not clear to me if this is going to work its way in to amplify-flutter shortly?

This is exactly what I am struggling on right now. In my case, I am using datastore as a local database with an option to sync its content whenever the user signed in. However, whenever my app runs without a signed-in user, I get the same exception thrown multiple times for multitple API Sync attempts until my app would crash.

It would be ideal to be able to start and stop syncing manually or at least be able to sync, or attempt to sync, only when a user is signed in or at least just for the plugin to swallow the error as a false alarm.

This has been a cause of frustration for a few days now.

**Comment by HuiSF** [comment]
DataStore plugin `start` and `stop` APIs have been release with version [`0.2.3`](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/CHANGELOG.md#023-2021-09-09).
