### ISSUE TITLE
How can I redirect to the signup hosted UI when I click on signup button?

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#2477]
Am using launch sign in with web UI. Things are working fine. But have few doubts. Have kept my UI like with two buttons as follows;
<img width="232" alt="Screenshot 2022-12-12 at 10 17 14 PM" src="https://user-images.githubusercontent.com/27992382/207103944-67e20485-3916-436e-a55d-52d64cc8856f.png">

So when we click on sign in and signup have to redirect to the hosted UI.
So when I click on signin following the code like;

```
Future<void> signInWithWebUI() async {
  try {
    final result = await Amplify.Auth.signInWithWebUI();
    print('Result: $result');
  } on AuthException catch (e) {
    print(e.message);
  }
}
```
<img width="343" alt="Screenshot 2022-12-12 at 10 20 30 PM" src="https://user-images.githubusercontent.com/27992382/207104804-e2064134-a963-4727-974d-a19dcec43916.png">

So the same way when I click on signup how I can redirect to the signup page of hosted UI?

<img width="346" alt="Screenshot 2022-12-12 at 10 20 07 PM" src="https://user-images.githubusercontent.com/27992382/207104668-7ebc7de8-10eb-4c8a-9095-7da84f13b86e.png">

**Comment by Jordan-Nelson** [comment]
Hi @Sunsiha - I want to make sure I understand your use case. It sounds like you want to allow users to create accounts with an email/password OR use Hosted UI (aka social sign in). Is that correct? If you only want to allow for Hosted UI, there is no need to display a form to the user as Hosted UI will prompt the user for their credentials.

As far as sign in versus sign up - `signInWithWebUI()` effectively encompasses both functions. `signInWithWebUI()` will will allow the user to authenticate for both new an returning users. Typically there would be a single button displayed in the UI (or a single button per provider), which invokes code similar to what you have for sign in. You can see an example of that in the pre-built authenticator component here - https://ui.docs.amplify.aws/flutter/connected-components/authenticator/configuration#social-providers. Do you mind sharing more about what you are hoping to achieve with the second button?

Also, I would encourage you to take a look at the pre-built authenticator component if you have not already. It adds full authentication workflows (sign in, sign up, confirm sign up, reset password, etc.) to your app. It responds to your amplify configuration to add things like social sign in.

**Comment by Sunsiha** [comment]
@Jordan-Nelson I got a clarity from your answer. So if am going with hosted UI(SSO) I should have only one button that is like signin. No need to keep sign up button, since it's gonna do the same functionality.

**Comment by Jordan-Nelson** [comment]
@Sunsiha - That is correct. If you don't have any other follow up questions, feel free to close this issue out.
