### ISSUE TITLE
Retrieve Cognito User Attributes

### ISSUE THREAD

**Issue by qodzero** [aws-amplify/amplify-flutter#248]
**Describe the bug**
I'm unable To Retrieve User Attributes For An Authenticated User

**To Reproduce**
1. Authenticate A User
2. Try to get the user attributes

**Expected behavior**

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[] iOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by haverchuck** [comment]
@qodzero I'm assuming you are referring to a method [analagous to this](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/android#fetch-the-current-users-attributes)? If so, we definitely have it in our backlog. I'll mark this as a feature request.

**Comment by qodzero** [comment]
That's exactly it

**Comment by muhlba91** [comment]
is there any progress already? :)

having access to user attributes when relying on cognito for the entire user management is quite an important feature.

**Comment by Amplifiyer** [comment]
`fetchUserAttributes` is now available in the latest release 0.0.2-dev.2. Get started here https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter#fetch-the-current-users-attributes

**Comment by SalahAdDin** [comment]
@Amplifiyer @haverchuck How can we get the user group?

**Comment by Mikopet** [comment]
> @Amplifiyer @haverchuck How can we get the user group?

As I see, there is still no solution for that...
I am using version `0.5.1`
