### ISSUE TITLE
DataStore - Unable to set nullable field to null on Android

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#249]
**Describe the bug**
When a field is defined as nullable in the GraphQL schema, once it has been set, setting it back to null does not update the backend DDB table. This only happens on Android, iOS appears to work fine.
 
**To Reproduce**
A test app can be found here: https://github.com/kjones/datastore_test
It can be deployed on both Android and iOS. When you hit the `+` button, fields in the `TestModel` class are updated and saved to DataStore.
The app observes all changes to `TestModel` so updates are propagated to all clients running at the same time.
Hit the `+` button a few times on Android. Note that the `nullableInt` field can't be set to null. You can also see this by viewing the DDB table directly.
Hit the `+`. button a few times on iOS. The backend DDB field alternates between being set and null. The change gets propagated to all clients.

**Expected behavior**
Nullable fields should be nulled out when set to null on the Android client.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Comment by Amplifiyer** [comment]
Thanks @kjones for your continued efforts and testing. This seems like an android bug. I'll create a bug in the amplify-android library based on my investigations.

**Comment by kjones** [comment]
I think this is fixed somewhere after Android SDK 1.6.8. Thx.
