### ISSUE TITLE
Smithy client codegen

### ISSUE THREAD

**Issue by scala-impala** [aws-amplify/amplify-flutter#2490]
Hi,

this is not an issue/bug, but a question on the Dart smithy codegen module/package. How experimental is the implementation? My usecase would be to codegen a client for relatively simple http service endpoints for use in a Flutter project. I guess another option would be to use the existing Rust codegen library and access it through FFI?

**Comment by dnys1** [comment]
Hi @scala-impala - great question! And thanks for your interest in Smithy Dart.

When we say the implementation is experimental, we mean that any aspect of it can change at any point - and this is unfortunately true at the moment. The API, behavior, build system, etc. is all subject to change as we develop it further.

There are several other options available in the Smithy ecosystem, however only two of them support both server and client generation (as opposed to just client generation): [smithy-rs](https://github.com/awslabs/smithy-rs), as you noticed, and [smithy-typescript](https://github.com/awslabs/smithy-typescript).

The build process for these is different than the one for Smithy Dart right now (and involves using Gradle as a build system), but they should have fewer and smaller changes than Smithy Dart will over the next year. More information about how to set up a project using one of these packages can be found in the [official guide](https://smithy.io/2.0/guides/building-models/gradle-plugin.html) and [examples](https://github.com/awslabs/smithy-gradle-plugin/tree/main/examples) repository.

That being said, Smithy Dart _is_ capable of generating a Dart client (and, potentially, a server) if you're willing to accept the potential for bugs/edge cases/changes. I'd be more than happy to field any questions you have if you'd be interested in giving this a shot. The process for creating a Smithy Dart service is fairly straightforward (although non-AWS service generation is not well-tested). I've created a repo [here](https://github.com/dnys1/library_service) with a simple demonstration.

> Note: In order to build the service, you'll need to clone the [smithy](https://github.com/awslabs/smithy) repository, and build the Docker image for it: `cd smithy && docker build -t smithy .`

**Comment by scala-impala** [comment]
Thanks for the extensive answer @dnys1

I already have a Scala backend with the API implemented with [https://github.com/disneystreaming/smithy4s](smithy4s) so at this stage I'm only looking for a suitable client code generator.

I'll be giving this a shot early next year, and will probably try Smithy Dart first before any of the other options, I can live with some instability and would prefer not to have another language and everything that comes with it in the mix. In the meantime I have another question: The service definitions in my smithy files use a non-AWS protocol for http, defined here [https://github.com/disneystreaming/alloy#alloysimplerestjson](simpleRestJson). Would I be able to generate a client using Dart Smithy if I supply it those definitions / implementations somehow?

**Comment by dnys1** [comment]
Unfortunately, generation for non-AWS protocols is not possible since it requires deeper integration in the code generator to understand the specific protocol.

**Comment by dnys1** [comment]
Closing for now. Please know that development of Smithy Dart continues and I look forward to the day we can release it publicly for stable client/server generation.

**Comment by marovargovcik** [comment]
Hi, I am exploring Scala smithy4s backend + Flutter for user facing apps and was wondering if there's any updates on Smithy Dart client generation? I see that smithy-lang repository hosts a couple of in-development client generators for languages like Ruby or Python but Flutter is not there. Doesn't sound promising but perhaps I am looking in the wrong place.

Thanks for your time, much appreciated.
