### ISSUE TITLE
[Question] Email template check with custom pattern during account creation workflow

### ISSUE THREAD

**Issue by fvisticot** [aws-amplify/amplify-flutter#2503]
### Description

I would like to check user domain email during account creation.
This feature would allow specific company domain only

By example, I would like to use a pattern check for email <username>@<company>.com
- fred@mycompany.com IS allowed
- fred@othercompany.com is NOT allowad

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
NA
```

### Dependencies

```bash
NA
```

### Device

All

### OS

NA

### Deployment Method

Amplify CLI

### Amplify Config

NA

**Comment by Jordan-Nelson** [comment]
Hello @fvisticot - This sounds like a good use case for a Cognito pre sign-up Lambda trigger. You can set up a lambda trigger to reject any sign up attempts that contain an email without the required domain. You can read more about lambda triggers and how to add them via the Amplify CLI here: https://docs.amplify.aws/cli/usage/lambda-triggers/

**Comment by Jordan-Nelson** [comment]
@fvisticot - I am going to close this out. Feel free to open a new issue if you have any other questions.
