### ISSUE TITLE
Allow the automatic detection of chunk size for queue length when using multi-part upload with S3

### ISSUE THREAD

**Issue by abdallahshaban557** [aws-amplify/amplify-flutter#2511]
When uploading files with multi-part upload, Amplify library for Flutter needs to intelligently detect the chunk size and queue length when uploading a file.

This is a feature that is implemented for iOS and Android as mentioned here https://github.com/aws-amplify/amplify-js/issues/8772#issuecomment-1344643430

**Comment by HuiSF** [comment]
Implementation of the optimal part size with multipart upload has merged and released in the latest dev-preview release.
Closing as completed.
