### ISSUE TITLE
Unhelpful error message when `sqlite3.wasm` is missing

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2524]
When a Flutter Web app is compiled with Analytics or Storage in vNext and the required `sqlite3.wasm` file is missing, the following error appears in the console:

```
Error: CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1378:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

However, this error is not surfaced by `Amplify.configure` (at least in the case of Analytics) - it happens asynchronously. This appears to be happening because the request to the `sqlite3.wasm` file is succeeding but returning something besides the WASM file. We should be capturing this error and adding a helpful recovery suggestion. Further, we should make sure the HTTP request to `sqlite3.wasm` fails if it's not there.

**Comment by HuiSF** [comment]
Is this running on a Flutter dev server where when resource doesn't exist it returns the default home page instead (`3c 21 44 4f` => `<!DO`).

**Comment by dnys1** [comment]
Yeah, just running `flutter run`

**Comment by Jordan-Nelson** [comment]
Closing this issue since sqlite3.wasm is no longer used on web.
