### ISSUE TITLE
Missing concrete implementations of 'ModelProviderInterface.getModelTypeByModelName'

### ISSUE THREAD

**Issue by nneuh07** [aws-amplify/amplify-flutter#2547]
### Description

Hello, 
this is a new issue, as the [old issue](https://github.com/aws-amplify/amplify-flutter/issues/1455) is set as resolved, but I could not find any evidence that it actually is and the comments over there suggest otherwise, too.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create a Flutter app
2. Init amplify and add api
3. Add a simpel GraphQL schema
4. Update dependencies with amplify_flutter: ^^1.0.0-next.0 and amplify_api: ^^1.0.0-next.0
5. Run amplify codegen models

### Screenshots

![image](https://user-images.githubusercontent.com/45431210/211068175-6f89eba2-ca7c-472b-b81c-deb5d23a38ad.png)
![image](https://user-images.githubusercontent.com/45431210/211068832-d03f4858-b003-4b0d-9c3f-7eabbf413fee.png)

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-x64, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.74.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.18.5
Flutter SDK 3.3.9
stt_app 1.0.0+1

dependencies:
- amplify_auth_cognito 1.0.0-next.2+1 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_flutter 1.0.0-next.2 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_riverpod 2.0.2 [collection flutter meta riverpod state_notifier]
- font_awesome_flutter 10.2.1 [flutter]
- riverpod_annotation 1.0.4 [meta riverpod]

transitive dependencies:
- amplify_auth_cognito_android 1.0.0-next.2 [flutter]
- amplify_auth_cognito_dart 0.3.1 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.2 [amplify_core flutter]
- amplify_core 1.0.0-next.2+1 [async aws_common aws_signature_v4 collection intl json_annotation logging meta retry uuid]
- amplify_datastore_plugin_interface 1.0.0-next.2 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.2 [flutter]
- amplify_flutter_ios 1.0.0-next.2 [amplify_core flutter]
- amplify_secure_storage 0.1.4 [amplify_secure_storage_dart async file flutter meta path path_provider]
- amplify_secure_storage_dart 0.1.4 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- async 2.9.0 [collection meta]
- aws_common 0.3.5 [async built_collection built_value collection http2 js json_annotation logging meta mime os_detect path stream_transform uuid]
- aws_signature_v4 0.3.1 [async aws_common collection convert crypto json_annotation meta path]
- built_collection 5.1.1
- built_value 8.4.1 [built_collection collection fixnum meta]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- convert 3.1.1 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.4 [meta path]
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http2 2.0.1
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- logging 1.1.0
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- oauth2 2.0.1 [collection crypto http http_parser]
- os_detect 2.0.1
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- retry 3.1.0
- riverpod 2.0.2 [collection meta stack_trace state_notifier]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.3.2 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.3.2 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.1
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- tuple 2.0.1
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 3.1.3 [ffi]
- worker_bee 0.1.3 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

N/A

### OS

N/A

### Deployment Method

Amplify CLI

### CLI Version

10.6.1

### Amplify Config

{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": true,
      "respectprimarykeyattributesonconnectionfield": true,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": false
  }
}

**Comment by HuiSF** [comment]
Hi @nneuh07 thanks for opening this issue. By observing your screenshot, it looks like that you haven't defined any model type in your schema, but only CustomType (types without `@model` directive). The codegen only generates `getModelTypeByModelName` method when there is `@model` type in your schema. After you adding `@model` types and rerun `amplify codegen models`, this error should be gone. 

Please let me know if this helps.

**Comment by nneuh07** [comment]
Hey @HuiSF,
thank you for responding that fast!
So is it not possible to use the code generation with an AWS AppSync project that's not relying on the `@model` annotation? Because I do not want to have the side-effects of that (e.g. the DynamoDB table), but only fetch the data from AppSync and have the .dart models generated.

**Comment by HuiSF** [comment]
> only fetch the data from AppSync and have the .dart models generated.

So you'd like to fetch data from AppSync using Amplify API plugin correct? If so, that you'd have to create tables in DynamoDB, and this is backed by creating model schema with the `@model` directive. A CustomType (type without `@model`) won't have a data source in DynamoDB within an Amplify context. 

Please let me know if I misunderstood your use case.

**Comment by nneuh07** [comment]
That is correct. But my AppSync is then "custom only". So every query has a custom lambda function as a DataSource behind it to fetch the data. Therefore no DynamoDB is needed. I only wanted to use the code generation feature to have the models in dart and use the Amplify API for authentication purposes.

**Comment by HuiSF** [comment]
Thanks for explaining @nneuh07 .
Amplify codegen, transformer, API and DataStore plugin are designed to work based on fully managed service, they may not work well with this specific use case. 

You can certainly modify `ModelProvider.dart` manually to add a dummy `getModelTypeByModelName` implementation to get around of this particular issue.

However, as the same reason I mentioned above, you may not be able to fully use functionality of the "GraphQL helper" with the API plugin.

**Comment by ragingsquirrel3** [comment]
It seems like the question was answered here so I'm going to close this one.
