### ISSUE TITLE
Document how to handle nextStep during signIn

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#2577]
We have a module called invite user, so part of that if user didn't change the password means we are asking to change the password, so for that getting the response like the following in web, but am not getting the response in mobile;

```
{ChallengeName: "PASSWORD_VERIFIER", ChallengeParameters: {SALT: "xxxx",…}}
ChallengeName
: 
"PASSWORD_VERIFIER"
ChallengeParameters
: 
{SALT: "xxxx",…}
SALT
: 
"xxxx"
SECRET_BLOCK
: 
"xxxx"
SRP_B
: 
"xxxx"
USERNAME
: 
"xxxx"
USER_ID_FOR_SRP
: 
"xxxx"
```

```
ChallengeName: "NEW_PASSWORD_REQUIRED", ChallengeParameters: {requiredAttributes: "[]",…},…}
ChallengeName
: 
"NEW_PASSWORD_REQUIRED"
ChallengeParameters
: 
{requiredAttributes: "[]",…}
requiredAttributes
: 
"[]"
userAttributes
: 
"xxx"
Session
: 
"xxx"
```
Code is entering to the else condition. How can I get the response ,
```
SignInResult res = await Amplify.Auth.signIn(
          username: usernameController.text.trim(),
          password: passwordController.text.trim());
      if (res.isSignedIn == true) {}else{}
```
```
 amplify_flutter: ^0.6.1
  amplify_auth_cognito: ^0.6.1
```

**Comment by Jordan-Nelson** [comment]
Hi @Sunsiha - If `isSignedIn` is false, there should be a nextStep object indicating that the user has a next step to complete such as Multi factor authentication or changing their password. Here is an example of how you might handle that:

```dart
  Future<void> signIn(String username, String password) async {
    final result = await Amplify.Auth.signIn(
      username: username,
      password: password,
    );

    final signInStep = result.nextStep!.signInStep;
    switch (signInStep) {
        case 'CONFIRM_SIGN_IN_WITH_SMS_MFA_CODE':
          // TODO: Handle MFA if app supports it
        case 'CONFIRM_SIGN_IN_WITH_NEW_PASSWORD':
          // TODO: prompt user to enter a new password
        case 'RESET_PASSWORD':
          // TODO: prompt user to reset their password
        case 'CONFIRM_SIGN_UP':
          // TODO: prompt user to confirm sign up 
        case 'DONE':
          // TODO: Take user to authenticated app
        default:
          throw StateError('unhandled signInStep: $signInStep');
      }
  }
```

I am going to mark this as a docs issue since it doesn't seem like the docs cover this very well.

Similar to my comment on #2578, the [Authenticator UI component](https://ui.docs.amplify.aws/flutter/connected-components/authenticator) has built in support for each possible state during the authentication flow, which often makes it the easiest way to add full authentication workflows to your app. If you had considered using it and have any feedback, please let me know.

**Comment by Sunsiha** [comment]
@Jordan-Nelson  Perfect. Documentation was not so clear. That's why posted. Thanks!

**Comment by peer-f** [comment]
I feel like the documentation for this is completely missing. https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/flutter/

Why is the next step handled by using a string? Why not use an enum? Providing the next step for authentication flows is super nice and helpful but strings are just way too error prone in my opinion. We were checking for 'CONFIRM_SIGN_UP_STEP' which seems to be an outdated string used for this.

**Comment by Jordan-Nelson** [comment]
@peer-f - Agreed. It has been updated to an enum in the latest developer preview version (1.0.0). That version is available on pub if you would like to use it while it is in preview.

**Comment by dnys1** [comment]
As @Jordan-Nelson mentioned, the next step has been migrated to an enum. There is new documentation as well in our [API reference](https://pub.dev/documentation/amplify_core/latest/amplify_core/AuthCategory/signIn.html) which gives further examples for each. Hope this helps!

**Comment by karayilanberat** [comment]
> As @Jordan-Nelson mentioned, the next step has been migrated to an enum. There is new documentation as well in our [API reference](https://pub.dev/documentation/amplify_core/latest/amplify_core/AuthCategory/signIn.html) which gives further examples for each. Hope this helps!

link is unavailable ):

**Comment by Jordan-Nelson** [comment]
@karayilanberat - There in an ongoing issue with the API docs on pub. Apologies about that. The docs on the official site have been updated to show the usage of this enum: https://docs.amplify.aws/flutter/build-a-backend/auth/multi-step-sign-in/
