### ISSUE TITLE
Document Confirm Sign In variations (new password, MFA)

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#2578]
1. How can I call the completeNewPassword API in flutter?
web : https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#complete-new-password
```
import { Auth } from 'aws-amplify';

Auth.signIn(username, password)
  .then((user) => {
    if (user.challengeName === 'NEW_PASSWORD_REQUIRED') {
      const { requiredAttributes } = user.challengeParam; // the array of required attributes, e.g ['email', 'phone_number']
      Auth.completeNewPassword(
        user, // the Cognito User Object
        newPassword, // the new password
        // OPTIONAL, the required attributes
        {
          email: 'xxxx@example.com',
          phone_number: '1234567890'
        }
      )
        .then((user) => {
          // at this time the user is logged in if no MFA required
          console.log(user);
        })
        .catch((e) => {
          console.log(e);
        });
    } else {
      // other situations
    }
  })
  .catch((e) => {
    console.log(e);
  });
```
2. How to get user.challengeName === 'NEW_PASSWORD_REQUIRED' in flutter?

```
 amplify_flutter: ^0.6.1
  amplify_auth_cognito: ^0.6.1
```

**Comment by Jordan-Nelson** [comment]
Hello @Sunsiha - It seems that the JS API is a bit different that the Flutter API. You should be able to accomplish this in Amplify Flutter like so:

```dart
  // step 1) Sign in with username and password
  Future<void> signIn(String username, String password) async {
    final result = await Amplify.Auth.signIn(
      username: username,
      password: password,
    );

    if (result.nextStep?.signInStep == 'CONFIRM_SIGN_IN_WITH_NEW_PASSWORD') {
      // direct users to a UI to enter a new password
    }
  }

  // Step 2) Using the users new password, confirm sign in.
  Future<SignInResult> confirmSignInNewPassword(String newPassword) async {
    return Amplify.Auth.confirmSignIn(
      confirmationValue: newPassword,
      options: CognitoConfirmSignInOptions(userAttributes: {
        CognitoUserAttributeKey.email: 'xxxx@example.com',
        CognitoUserAttributeKey.phoneNumber: '1234567890',
      }),
    );
  }
```

I don't believe we have this use case documented for Flutter, so I will mark this as a docs issue.

Let me know if you have any additional questions.

**Comment by Jordan-Nelson** [comment]
I also want to note that the [Authenticator UI component](https://ui.docs.amplify.aws/flutter/connected-components/authenticator) should cover this user case. By default it will only ask the user for a new password, but that can be customized to also prompt for user attributes like phone/email/etc. If you had considered the Authenticator UI component, but decided not to use it, please feel free to provide any feedback you may have.

**Comment by Sunsiha** [comment]
This will integrate and update with you asp.

**Comment by Sunsiha** [comment]
@Jordan-Nelson thanks. All issues sorted.

**Comment by dnys1** [comment]
The confirm sign-in variations have been documented in the [AuthCategory](https://pub.dev/documentation/amplify_core/latest/amplify_core/AuthCategory/signIn.html) docs. Thanks for your patience, and please let us know if there is any other information you'd like to see in them.
