### ISSUE TITLE
Can't compile auth 1.0.0-next.4 on iOS

### ISSUE THREAD

**Issue by asaarnak** [aws-amplify/amplify-flutter#2612]
### Description

Swift Compiler Error (Xcode): Value of type 'NativeAuthPlugin' has no member 'fetchAuthSession'
.pub-cache/hosted/pub.dev/amplify_auth_cognito_ios-1.0.0-next.4/ios/Classes/SwiftAuthCognito.swift:149:25

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
flutter 3.7
```

### Dependencies

```bash
amplify_flutter: ^1.0.0-next.4
  amplify_auth_cognito: ^1.0.0-next.4
```

### Device

N/A

### OS

iOS

### Deployment Method

Amplify CLI

### Amplify Config

{}

**Comment by Jordan-Nelson** [comment]
@asaarnak - I was not able to reproduce this. Could you try running `flutter clean` and then rebuilding? v1.0.0-next.4 was just released. It is possible you have something cached. 

Do you have any other amplify dependencies in your app?

**Comment by asaarnak** [comment]
Worked after running `flutter clean`. Sorry for trouble.

**Comment by Jordan-Nelson** [comment]
No problem. I'm glad you were able to get it working. Let us know if you have any other issues.
