### ISSUE TITLE
[RFC]: Amplify core refactor

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-flutter#263]
_This issue is a Request For Comments (RFC). It is intended to elicit community feedback regarding support for Amplify library in Flutter platform.  Please feel free to post comments or questions here._

## Purpose
Currently `amplify-flutter` library has a package [`amplify-core`](https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_core) which customers use to import top level `Amplify` class. This `amplify-core` package is currently at top level and depends on all the plugin interface packages such as [auth_plugin_interface](https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_auth_plugin_interface) making it impossible to add any base types to it which interface packages may need (creating a circular dependency between `amplify-core` and `amplify_plugin_interface` packages.

![image](https://user-images.githubusercontent.com/51211245/102554962-a302f580-407a-11eb-9f72-f2c73a3fa3ae.png)

## Proposed Solution
To be able to create base types in a bottom of the dependency hierarchy, we have two options:

### Refactor `amplify_core` package 
Rename the package to `aws_amplify` (or amplify_flutter) which will be a top level package that customers will import in their app. Use package `amplify_core` for adding base types and utils shared across amplify library and not used by customers.

This will be a breaking change for current developer preview customers as they will now import amplify as:

```yaml
# pubspec.yaml
dependencies:
  flutter:
    sdk: flutter

  aws_amplify: 1.0.0
```

```dart
import 'package:aws_amplify/amplify.dart';
.
.
.
Amplify.DataStore.query(...);
```

### Keep `amplify_core` as top level and create another package for base types
This new package can be called `amplify_base`. This will not be a breaking change immediately and customers will use amplify library as 

```yaml
# pubspec.yaml
dependencies:
  flutter:
    sdk: flutter

  amplify_core: 1.0.0
```

```dart
import 'package:amplify_core/amplify_core.dart';
.
.
.
Amplify.DataStore.query(...);
```

Let us know in comments if you prefer one way or the other or it doesn't impact you.

### JS
```js
import Amplify, { DataStore } from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
DataStore.query();
```

### iOS

```swift
import Amplify
import AmplifyPlugins

try Amplify.add(plugin: AWSDataStorePlugin())
try Amplify.configure()
Amplify.DataStore.query()
```

### Android
```kotlin
import com.amplifyframework.core.Amplify
import com.amplifyframework.datastore.AWSDataStorePlugin

Amplify.addPlugin(AWSDataStorePlugin())
Amplify.configure()
Amplify.DataStore.query()
```

**Comment by Ashish-Nanda** [comment]
Closing as we have picked option 1, and have an issue describing the upcoming breaking changes: https://github.com/aws-amplify/amplify-flutter/issues/274
