### ISSUE TITLE
Datastore many to many Relations

### ISSUE THREAD

**Issue by NimaSoroush** [aws-amplify/amplify-flutter#264]
**Describe the bug**
Unable to query many-to-many relations

**To Reproduce**
Having this models

```
type User @model {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  contentCategories: [UserContentCategory] @connection(keyName: "userToContentCategory", fields:["id"])
}

type ContentCategory @model {
  id: ID!
  title: String!
  users: [UserContentCategory] @connection(keyName:"contentCategoryToUser", fields:["id"])
}

type UserContentCategory
  @model(queries: null)
  @key(name:"userToContentCategory", fields:["userID", "contentCategoryID"])
  @key(name:"contentCategoryToUser", fields:["contentCategoryID", "userID"]){
  id: ID!
  userID: ID!
  contentCategoryID: ID!
  user: User! @connection(fields:["userID"])
  contentCategory: ContentCategory! @connection(fields:["contentCategoryID"])
}
```
When I query using datastore I always get null for many-to-many connection

```
var users = await Amplify.DataStore.query(User.classType, where: User.EMAIL.eq('nima'));
print(users[0].contentCategories); // Always null
```
When I check the local sqlite db I can see that `User`, `ContentCategory` and `UserContentCategory` tables are properly populated with data.
Also when I check the models locally using `Amplify mock api` the query works fine too!

**Expected behavior**
I expect `Amplify.DataStore.query` to return the many-to-many relation properly

**Screenshots**
My UserContentCategory table in sqlite db in the android emulator

![Screenshot 2020-12-20 at 18 23 19](https://user-images.githubusercontent.com/7963223/102721111-a7d0df00-42f0-11eb-89b8-00da02481d5b.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by jamesonwilliams** [comment]
Hey @NimaSoroush! This is the expected current behavior on iOS, Android, JavaScript and Flutter. Namely, if you have a 1:n or m:n relationship, the children won't get loaded during a query, when you query a given parent. We are working on an improvement to this, called "lazy loading." It will be released early next year.

We have workaround for this, but IMO they aren't well documented. So I've added a task for this in our docs project: https://github.com/aws-amplify/docs/issues/2791.

In short, you need to perform multiple queries.
1. Query `User`s that have an email of `'nima'`. Store the user IDs into a list.
2. For each user ID, query the `UserContentCategory` table. Extract the content category ID in the relationship. Store all of these into a different list, where you keep track of all the ones you've found.
3. At this point, you have a big list of `ContentCategory` IDs. You can perform `n`-many queries to look them up individually.

cc: @iartemiev who has been looking at model connections recently. Is there any optimization to this, right now?

**Comment by NimaSoroush** [comment]
@jamesonwilliams : Thanks for clarifying this. The workaround should work but the only caveat is that `UserContentCategory` model has `@model(queries: null)` which is the way it is suggested to be done in https://docs.amplify.aws/lib/datastore/relational/q/platform/flutter#many-to-many docs.

**Comment by jamesonwilliams** [comment]
Excellent point @NimaSoroush! We definitely need to improve this experience and these docs. Many-to-many feels a little half-baked right now, which isn't what we're going for. :-)

**Comment by bprayush** [comment]
Any updates on this?

**Comment by HuiSF** [comment]
Closing this issue in favor of https://github.com/aws-amplify/amplify-flutter/issues/1449
Will update the progress in the linked issue. Thanks!
