### ISSUE TITLE
how to connect my local flutter project to amplify backend server?

### ISSUE THREAD

**Issue by helpmeplease77** [aws-amplify/amplify-flutter#2641]
Hello, thank you for watch this. please help me. 

I am going through flutter tutorial from amplify official documentation right now.

What I'm working on right now is creating a Todo app.

First, I activated amplify studio.

And I created and deployed a data model,

And then, I came back to my local project (Todo app) terminal and ran amplify pull ~ .

After that, I registered these plugins and pub get. of course I import these packages. 

 amplify_flutter: ^0.6.12
  amplify_datastore: ^0.6.12
  amplify_datastore_plugin_interface: ^0.6.12
  amplify_api: ^0.6.12

And I went to the place where this code is and added the following codes as well.

amplify.configure(amplifyconfig);

I went there and added the code below.

      final _dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
      final _apiplugin = AmplifyAPI();

      // add Amplify plugins
      await Amplify. addPlugins([_dataStorePlugin,_apiplugin]);

Even though I did the same as the tutorial in the official document and the explanation video uploaded by the aws employee on YouTube, I can't connect to the server.

In other words, when I run this Todo app and add a todo list, it should be reflected in the content window of amplify studio, but it doesn't work at all.

Do I need to complete authentication setup in amplify studio, deploy it, then amplify pull again, then add auth pulgin?

Did I fail to connect to the server because I missed this part?

Please let me know.

I add this code,
amplify_auth_cognito: ^0.6.12 

And I go to below code part, (= in method)
amplify.configure(amplifyconfig);

I put the code below, and ran the whole code.
final authplugin = AmplifyAuthCognito();

And then,
The following error code came out:

I/amplify:flutter:api( 3217): Added API plugin
I/flutter ( 3217): Amplify plugin was not added
I/flutter ( 3217): An error occurred while configuring Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognitoMethodChannel was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: AmplifyException(message: Category auth has already been configured or is configuring., recoverySuggestion: Make sure that you have added all plugins before attempting configuration., underlyingException: null))
E/MethodChannel#com.amazonaws.amplify/datastore( 3217): Failed to handle method call
E/MethodChannel#com.amazonaws.amplify/datastore( 3217): java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.

I show my code about part I explained above. for more information!!

- number 1 method. 

@override
  void initState() {

    _initializeApp(); (---> this is number 2 method)

    super.initState();
  }

- number 2 metohd.

 Future<void> _initializeApp() async {

    await _configureAmplify(); (-----> this is number 3 method)

    _subscription = Amplify.DataStore.observeQuery(Mymytodo.classType)
        .listen((QuerySnapshot<Mymytodo> snapshot) {
      setState(() {
        if (_isLoading) _isLoading = false;
        _todos = snapshot.items;
      });
    });
  }
  

- number 3 method
 
Future<void> _configureAmplify() async {

    try {
      final _dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
      final _apiplugin = AmplifyAPI();
      final authplugin = AmplifyAuthCognito();

      await Amplify.addPlugins([_dataStorePlugin,_apiplugin,authplugin]);

      await Amplify.configure(amplifyconfig);

    } catch (e) {
      safePrint('An error occurred while configuring Amplify: $e');
    }
  }

**Comment by helpmeplease77** [comment]
pelase help me

**Comment by ragingsquirrel3** [comment]
Do you mind including your amplifyconfiguration.dart file's contents (with any sensitive values like API keys/user pool IDs removed/changed)? That might help determine what's going on with the local config and if amplify studio/CLI pull changes are required. Also make sure you are calling `Amplify.addPlugins` and `Amplify.configure` only one time like in your number 3 method above (i.e. ensure not called before that method).

**Comment by Jordan-Nelson** [comment]
Hello @helpmeplease77 - Let us know if you still need help with this.

**Comment by Jordan-Nelson** [comment]
@helpmeplease77 - I am going to close this out since we have not heard back. If you still need help, please open a new issue.
