### ISSUE TITLE
[Compile issue] can't compile due to missing support to intl 0.18.0

### ISSUE THREAD

**Issue by iosephmagno** [aws-amplify/amplify-flutter#2642]
### Description

We can no longer compile fue to this dependency issue.

Because no versions of amplify_storage_s3 match >0.6.12 <0.7.0 and amplify_storage_s3 0.6.12 depends on amplify_core 0.6.12, amplify_storage_s3 ^0.6.12 requires amplify_core 0.6.12.
And because amplify_core 0.6.12 depends on intl ^0.17.0, amplify_storage_s3 ^0.6.12 requires intl ^0.17.0.
So, because presence depends on both amplify_storage_s3 ^0.6.12 and intl ^0.18.0, version solving failed.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Latest master 3.8.0-8.0.pre.2 and latest stable

### Amplify Flutter Version

^0.6.12

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hi @iosephmagno - Amplify 0.6.12 has a dependency on intl v0.17.x. It looks like your app has a dependency on intl v0.18.x.

As a workaround until we release a version of amplify that supports v0.18.x, changing the dependency in your app to v0.17.x should allow you to resolve dependencies. You may also be able to use a a dependency override, but I am not sure if v0.18.x introduced any breaking changes.

**Comment by delfme** [comment]
Thx! intl 0.18 is required by other packages. We fixed issue by just forking amplify and upgrading intl there

**Comment by Jordan-Nelson** [comment]
I'm going to mark this as a bug until the version constraint has been updated to support the latest version.
