### ISSUE TITLE
When amplify storage upload start, we see an allow push notifications dialog on Android

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-flutter#2643]
### Description

When I start an upload with amplify storage, a push notification permission dialog is shown on Android. Is there a way to disable this?

If it can't be disabled, can the name of the notification channel be changes from **Amplify Transfer Channel**, this is what is now shown in the app notification settings screen?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [x] Storage

### Steps to Reproduce

` Future<String?> uploadFile(File file) async {
    try {
      final extension = p.extension(file.path);
      final key = const Uuid().v1() + extension;

      final uploadOptions = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.protected,
      );

      await Amplify.Storage.uploadFile(
          local: file,
          key: key,
          options: uploadOptions,
          onProgress: (progress) {
            uploadProgress.value = progress.getFractionCompleted();
          });

      return key;
    } on Exception catch (e) {
      debugPrint(e.toString());
      return null;
    }
  }`

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @itechevo thanks for sharing this issue. 

Can you clarify what you mean by "push notification permission dialog"?  And where you are seeing "Amplify Transfer Channel"? 

When I run the storage example app and upload a file I get a popup saying: 

"Allow amplify_storage_s3_exa... to access photos and media on your device" (Allow / Deny) 

And when I go to the app settings and notifications I see the app name listed as "amplify_storage_s3_example". 

I tested on a Motorola Android device and an Android Pixel Simulator but wasn't able to get the behavior that you described.  

If you run the storage example app [here](https://github.com/aws-amplify/amplify-flutter/tree/main/packages/storage/amplify_storage_s3/example) are you able to get the same behavior that you described in this issue?

**Comment by HuiSF** [comment]
Hello @itechevo thanks for opening this issue. The notification associated with the Amplify Storage S3 plugin is expected as amplify-android V1 initiates WorkManager to process uploads in the background, per Android specification, a notification needs to be shown for the background service. Currently, the title of the notification is not customizable. 

amplify-android v2 has been released which contain a fix to eliminate this notification, but the team doesn't have a plan, however, to port the fix into amplify-android v1, which is consumed by amplify-flutter stable release.

You can try [this workaround](https://github.com/aws-amplify/amplify-android/issues/1887#issuecomment-1218367993) to disable the notification. Please let us know if this helps with your case.

**Comment by itechevo** [comment]
Thank you @HuiSF, I will try the workaround.

**Comment by Jordan-Nelson** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
