### ISSUE TITLE
AWS Congnitive for Web is not working

### ISSUE THREAD

**Issue by devsunsam** [aws-amplify/amplify-flutter#2644]
### Description

Hi I'm a flutter user wishing to use AWS all functions with flutter

I'm encountering the issue when I run the debug with chrome so that I implement the google auth.
In Android is okay but when it comes to Chrome, it shows below

No sign in redirect URLs registered for base URL: http://localhost:3000/. Add a sign in redirect URL on that starts with "http://localhost:3000/". See the docs for more info: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/

It is catched by 
  Future<void> signInWithSocialWebUI() async {
    try {
      final result = await Amplify.Auth.signInWithWebUI(
        provider: AuthProvider.google,
      );
      print('Result: $result');
    } on AmplifyException catch (e) {
      print(e.message);
    }
  }

I set the launch.json 
{
      "name": "web",
      "request": "launch",
      "type": "dart",
      "deviceId": "chrome",
      "args": ["-d", "chrome","--web-port", "3000"],
    },

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.3

### Amplify Flutter Version

lastest

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@devsunsam - can you please provide your amplify config (with sensitive info removed)?

**Comment by devsunsam** [comment]
> @devsunsam - can you please provide your amplify config (with sensitive info removed)?

Thank you for your interest

////

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_XXXXXXXXXXXX",
                        "AppClientId": "XXXXXXXXXXXXXXXXXXXX",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "XXXXXXXXXXXXXXXXXXXXXXXXX.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "CUSTOM_AUTH",
                        "socialProviders": [
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "XXXXXXXXXXXXXXXXXXXXXXXXX",
                        "ClientDatabasePrefix": "XXXXXXXXXXXXX_API_KEY"
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "XXXXXXXX": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://XXXXXXXXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
                }
            }
        }
    }
}''';

**Comment by Jordan-Nelson** [comment]
Hi @devsunsam - it looks like you added a redirect URL for mobile, but have not added one for web. As noted in the documentation for developer-preview, you will need to add a local host redirect as well via the amplify CLI.

You can view the docs here. Make sure you have selected the developer preview tab. https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/#configure-auth-category

**Comment by dnys1** [comment]
Closing for now. Please let us know if you continue to face issues.
