### ISSUE TITLE
Custom Subscriptions not getting events

### ISSUE THREAD

**Issue by ignitum-ryan** [aws-amplify/amplify-flutter#2646]
### Description

Hey Amplify Team,

I'm currently running into an issue where no custom subscriptions (both Android and iOS) are not triggering (no events are received by subscribed devices). [I used the following document to help in the setup of the custom subscription](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/flutter/). Still no luck. I will be pasting all relevant code below, please don't hesitate to ask for more details. Thanks all!

Additional notes on below screenshots:
- I originally did not have `decodePath` and `modelType` in the GraphQLRequest object. Having them there, or not having them in the instantiation results in the same outcome, no events.
- I originally had the sender and receiver objects in my `createdFriendshipGQL` query, however, that also did not result in any events. See below screenshot.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create the models.
2. Create the custom subscriptions.
3. Establish the subscriptions upon app start-up.
4. Create records (manually or programmatically, results in same outcome)
5. See that the events never are received by the listening devices.

### Friendship Model
<img width="461" alt="image" src="https://user-images.githubusercontent.com/97566760/218768812-c4d4f4dc-1871-4fec-8ec6-be21c133c3b0.png">

### User Model
<img width="715" alt="image" src="https://user-images.githubusercontent.com/97566760/218769121-6ef43c20-5a95-4a5f-9071-bc3e779f304e.png">

### Function setting up subscription:
![image](https://user-images.githubusercontent.com/97566760/218769697-bb63c526-ccea-4e9e-98b0-090382a87441.png)

### Subscription declaration in schema
<img width="857" alt="image" src="https://user-images.githubusercontent.com/97566760/218770158-ebfc0091-3eee-48e7-bb07-104bd8fd4245.png">

### Attempted with this query as well to no avail
<img width="491" alt="image" src="https://user-images.githubusercontent.com/97566760/218771723-8bf5307c-8085-40d4-857a-a6c0b75425c8.png">

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.1

### Amplify Flutter Version

^1.0.0-next.4

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type User @model @auth(rules: [{allow: private}]) {
  id: ID! @index(name: "byUser")
  bio: String
  displayName: String!
  sentFriendships: [Friendship] @hasMany(indexName: "bySentUser", fields: ["id"])
  receivedFriendships: [Friendship] @hasMany(indexName: "byReceivedUser", fields: ["id"])
}

type Friendship @model @auth(rules: [{allow: private}]) {
  id: ID!
  status: FriendStatus!
  senderID: ID! @index(name: "bySentUser")
  sender: User! @belongsTo(fields: ["senderID"])
  receiverID: ID! @index(name: "byReceivedUser")
  receiver: User! @belongsTo(fields: ["receiverID"])
}

enum FriendStatus {
  Accepted
  Pending
  Waiting
  None
  Rejected
  Blocked
  Cancelled
}
```

**Comment by ignitum-ryan** [comment]
Also wanted to mention that I did confirm that the correct `currentUser.id` is being registered and matches what's being put inside the DynamoDB tables, before anyone wants to ask :)

**Comment by ragingsquirrel3** [comment]
Thanks for filing issue @ignitum-ryan, a few more questions:
* Can you please provide example of mutation request from step 4 or reproduction steps you provided that you are expecting to trigger the subscription? This will help repro, also common pitfall bc in [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) "subscription selection set must be a subset of the mutation selection set."
* Am I correct in understanding there is no event with errors triggered? Sounds like no events at all and your code would detect if it got a subscription event with errors.

**Comment by ignitum-ryan** [comment]
Hi @ragingsquirrel3 , thanks for the response!

To answer your question, yes, here is the current logic I'm using to create the record to trigger the subscription:

```
Future<Friendship?> saveNewFriendship(Friendship newFriendship) async {
    try {
      final request = ModelMutations.create(newFriendship);
      final response = await Amplify.API.mutate(request: request).response;
      if (response.errors.isNotEmpty) {
        print('Could not save new friendship: Response: ${response.errors}');
        throw (response.errors);
      }
      return response.data;
    } catch (error) {
      print('Could not save new friendship: ${error}');
      Sentry.captureException(error, hint: 'Could not save new friendship.');
    }
    return null;
  }
```

Regarding your second bullet, you are also correct. There are no error events being thrown either inside the catch blocks or the `onError` methods of the StreamSubscriptions. I also was unable to find any sort of error logs in the AppSync console or CloudWatch.

**Comment by ignitum-ryan** [comment]
Additional findings:

I attempted to create a subscription inside of AppSync directly. Strangely, AppSync **ALSO** did not get the event from the record being added.

![image](https://user-images.githubusercontent.com/97566760/219463600-3f746785-84b6-4c18-9af7-1940d1c480ac.png)

The text string you see below the `receiverID` variable is a copy of what was entered into the database to show that the receiverIDs do match up. Also validated that all properties in the record were populated that exist in my subscription (with the exception of the sender and receiver as those are referenced via the receiverID and senderID respectively):

![image](https://user-images.githubusercontent.com/97566760/219464016-5e409dce-b8f9-4af8-9535-e259c25cfb26.png)

**Comment by ragingsquirrel3** [comment]
@ignitum-ryan I was able to reproduce a similar issue in AppSync console. I think it's expected the mutation selection set does not include the field you are using to filter your subscription. In addition to the subscription selection set being a subset of the mutation selection set (should produce graphql error in subscribed client), the mutation selection set must include the field being used for the filter, otherwise the filtered subscription won't pick up the event. The mutation request produced by `ModelMutations.create()` won't include nested fields, so won't work in this use case and you will need a custom mutation document. I got it working with a request like this in AppSync console:

```
mutation MyMutation {
  createFriendship(input: {status: Accepted, senderID: "some-id", receiverID: "some-other-id"}) {
    id
    createdAt
    status
    updatedAt
    senderID
    sender {
      bio
      createdAt
      displayName
      id
      updatedAt
    }
    receiver {
      displayName
      createdAt
      id
      updatedAt
      bio
    }
    receiverID
  }
}
```

So, in your case, I think you would change `ModelMutations.create(user);` to custom request:
```dart
final request = GraphQLRequest<Friendship>(
    document: customRequestDocumentString, // string from above, can also pass IDs as variable if preferred
    modelType: Friendship.classType,
    decodePath: 'createFriendship',
);
```

Let me know if this works for you.

As an aside, if you recently set up this backend w newer version of CLI, I don't think you need to declare the custom subscription in your schema for this use case as server-side filters now setup by default for the normal `onCreateFriendship` subscription (documentation you linked is a bit out-of-date). I got it working w this subscription:

```
subscription MySubscription {
  onCreateFriendship(filter: {senderID: {eq: "6e8b1e69-e340-4cb7-ad68-ddf972983535"}}) {
    id
    createdAt
    receiverID
    senderID
    status
    updatedAt
    receiver {
      id
      displayName
    }
    sender {
      id
      displayName
    }
  }
}
```

**Comment by ignitum-ryan** [comment]
Awesome details, thank you so much @ragingsquirrel3 ! I'm excited to try this and will have a response to you tomorrow. Thanks again.

**Comment by ignitum-ryan** [comment]
@ragingsquirrel3 - Whew...that sent me down a path. Unfortunately I had to delete my API and entire backend because simiple onCreates were NOT being triggered inside of AppSync. After recreating all of the resources, basic subs were working again.

Onto the solution:

I did take your advice and added the `receiverID` to the mutation and was able to get subscriptions to fire inside of the AppSync console with the subscription you listed above. After looking at the document that the ModelMutations.create(user) creates, it ONLY was missing the receiverID in the selection set. In order to still utilize the Amplify helpers, I created a custom function to simply add fields to the already created GraphQLRequest:

```
import 'package:gql/ast.dart';
import 'package:gql/language.dart';

class AmplifyGQLHelper {
  static String addFieldToMutation(DocumentNode document, String fieldName) {
    final fieldNode = (document.definitions
                .firstWhere((def) => def is OperationDefinitionNode)
            as OperationDefinitionNode)
        .selectionSet
        .selections
        .firstWhere((selection) => selection is FieldNode) as FieldNode;

    final existingSelectionSet =
        fieldNode.selectionSet?.selections?.cast<SelectionNode>();
    final updatedSelectionSet = SelectionSetNode(
      selections: [
        ...existingSelectionSet ?? [],
        FieldNode(name: NameNode(value: fieldName)),
      ],
    );
    final newFieldNode = FieldNode(
      name: fieldNode.name,
      selectionSet: updatedSelectionSet,
      directives: fieldNode.directives,
      arguments: fieldNode.arguments,
      alias: fieldNode.alias,
    );
    final updatedOperationDefinition = OperationDefinitionNode(
      type: (document.definitions
                  .firstWhere((def) => def is OperationDefinitionNode)
              as OperationDefinitionNode)
          .type,
      selectionSet: SelectionSetNode(selections: [newFieldNode]),
      name: (document.definitions
                  .firstWhere((def) => def is OperationDefinitionNode)
              as OperationDefinitionNode)
          .name,
      directives: (document.definitions
                  .firstWhere((def) => def is OperationDefinitionNode)
              as OperationDefinitionNode)
          .directives,
      variableDefinitions: (document.definitions
                  .firstWhere((def) => def is OperationDefinitionNode)
              as OperationDefinitionNode)
          .variableDefinitions,
      span: (document.definitions
                  .firstWhere((def) => def is OperationDefinitionNode)
              as OperationDefinitionNode)
          .span,
    );
    return printNode(DocumentNode(definitions: [updatedOperationDefinition]));
  }
}
```

**_It's important to note, after #2655 is implemented, I don't believe the above code will be needed._**

I then utilized the above function in tandem with the Amplify model helpers as so:

```
 final amplifyRequest = ModelMutations.create(newFriendship);
      final ast.DocumentNode modifiedDocument =
          lang.parseString(amplifyRequest.document);
      final updatedDocument = AmplifyGQLHelper.addFieldToMutation(
          modifiedDocument, 'receiverID');
      final customRequest =
          AmplifyGQLHelper.getRequest(amplifyRequest, updatedDocument);
      final response =
          await Amplify.API.mutate(request: customRequest).response;
```

This created fired off the subscription correctly.

There was one more remaining issue that I had in order for the subscription to work.
The decodeType of the subscription was incorrect and the events were not being received by the listener. The decode type needed to be `onCreateFriendship`, not `createFriendship`. After making this last change, everything worked correctly!

Thanks for the help and the PR to resolve this moving forward!
