### ISSUE TITLE
(iOS) App crashes  when when trying to save/query with DataStore

### ISSUE THREAD

**Issue by jeemoney** [aws-amplify/amplify-flutter#2647]
### Description

I'm seeing this exception consistently on iOS simulator when performing any DataStore query or save call:

> DataStoreException(message: The operation couldn’t be completed. (SQLite.Result error 0.), recoverySuggestion: The operation couldn’t be completed. (SQLite.Result error 0.), underlyingException: The operation couldn’t be completed. (SQLite.Result error 0.))

I created a new Flutter project and a new Amplify app with the default Blog/Post/Comment schema to test whether or not our schema was the issue. I see the same thing with this new project and boilerplate schema. I was able to test on my iPhone and I'm still seeing the same issue, but with a bit more detail in the error message suggesting that the table for the model doesn't exist.

Both our app and this test app are working fine on Android simulator and physical device.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  List<String> posts = [];

  Future<void> addPost() async {
    final post = Post(title: 'New Post');
    final comment = Comment(content: 'New Comment', post: post);
    await Amplify.DataStore.save(post);
    await Amplify.DataStore.save(comment);
    final fetchedPosts = await Amplify.DataStore.query(Post.classType);

    setState(() {
      posts = fetchedPosts.map((post) => post.title).toList();
    });
  }

  Future<void> _configureAmplify() async {
    final authPlugin = AmplifyAuthCognito();
    final apiPlugin = AmplifyAPI();
    final datastorePlugin =
        AmplifyDataStore(modelProvider: ModelProvider.instance);
    await Amplify.addPlugins([authPlugin, apiPlugin, datastorePlugin]);

    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      safePrint(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
  }
```

This code throws an exception on the first DataStore.save call, regardless of which model. I also tried creating a blog in the web studio and allowing DataSource time to sync it down, then tried a fetch. Same result.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.2

### Amplify Flutter Version

1.0.0-next.4

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Blog @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model @auth(rules: [{allow: public}]) {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model @auth(rules: [{allow: public}]) {
  id: ID!
  post: Post @belongsTo
  content: String!
}
```

**Comment by Jordan-Nelson** [comment]
Hello @jeemoney - I was able to reproduce this using the version you noted. I could not reproduce this using the latest stable version of Amplify (0.6.12) so if you need to use data store and only targeting iOS and Android, you could use the stable version for now.

I thought this might have to do with nested models, but I was able to reproduce this just by adding a blog. We will look into this.

Below is the full app that I was using to repro:

```dart
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:issue_2647/amplifyconfiguration.dart';

import 'models/ModelProvider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  List<Blog> blogs = [];

  Future<void> addBlog() async {
    final blog = Blog(name: 'New Blog');
    await Amplify.DataStore.save(blog);
    final fetchedBlogs = await Amplify.DataStore.query(Blog.classType);
    setState(() => blogs = fetchedBlogs);
  }

  Future<void> _configureAmplify() async {
    final apiPlugin = AmplifyAPI();
    final datastorePlugin = AmplifyDataStore(
      modelProvider: ModelProvider.instance,
    );
    await Amplify.addPlugins([apiPlugin, datastorePlugin]);
    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      safePrint(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(onPressed: addBlog, child: const Text('Add Blog')),
            const SizedBox(height: 32),
            if (blogs.isEmpty) const Text('No Blogs to display'),
            for (final blog in blogs) Text(blog.name),
          ],
        ),
      ),
    );
  }
}
```

**Comment by HuiSF** [comment]
On the next branch we've changed plugins configuring process. With the changes the native DataStore plugin now is not able to be configured. 

Due to missing the configure step, the native DataStore cannot register model schemas correctly to create tables in the local DB. Hence, when saving model, SQLite throws error saving record to non-existing table. Will implement a fix for this issue.

**Comment by jeemoney** [comment]
Updated to the latest and I'm no longer seeing this issue.  Thanks for the help!
