### ISSUE TITLE
API sync failed - transitioning to LOCAL_ONLY 

### ISSUE THREAD

**Issue by anil-softuvo1** [aws-amplify/amplify-flutter#2692]
### Description

When try to save/sync the data with backend server get the below error 

API sync failed - transitioning to LOCAL_ONLY.
W/amplify:aws-datastore(29294): DataStoreException{message=Error during subscription., cause=ApiAuthException{message=Tried to use owner/group-based authorization on an API that is not configured with either Cognito User Pools or OpenID Connect., cause=null, recoverySuggestion=Verify that the API is configured with either Cognito User Pools or OpenID Connect. @auth with owner/group-based authorization is not supported for other modes.}, recoverySuggestion=Evaluate details.}

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Screenshots

![Screenshot 2023-02-23 at 9 31 02 AM](https://user-images.githubusercontent.com/125564727/220818610-77701267-eb43-418a-a1eb-7b317a1d591e.png)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.3.2

### Amplify Flutter Version

  amplify_api: ^0.6.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Trip @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  tripName: String!
  destination: String!
  startDate: AWSDate!
  endDate: AWSDate!
  tripImageUrl: String
  tripImageKey: String
}
```

**Comment by HuiSF** [comment]
Hello @anil-softuvo1 thanks for opening this issue. The exception shown in the screenshot is self-explanatory -

>Tried to use owner/group-based authorization on an API that is not configured with either Cognito User Pools or OpenID Connect

Your model schema specifies to apply owner based auth on the model `Trip`, but you might not have set the authorization  mode to `Amazon Cognito User Pool` or `OpenID Connect` which is required to support owner based auth.

Please double check your API category configuration. You can do this by running `amplify update api`, and choose `Authorization modes`.

**Comment by anil-softuvo1** [comment]
Hi, @HuiSF thanks for the response . As you said i have changed the authorisation mode to Amazon Cognito User Pool or OpenID Connect by running amplify update api, but it still give me a same error.

**Comment by HuiSF** [comment]
>As you said i have changed the authorisation mode to Amazon Cognito User Pool or OpenID Connect

After `amplify update api`, did you run `amplify push` to deploy the changes? This step should regenerate `amplifyconfiguration.dart` with the updated settings to support the owner auth logic in the library.

**Comment by anil-softuvo1** [comment]
@HuiSF It works now. Thanks for the time

**Comment by anil-softuvo1** [comment]
@HuiSF  there is one small question. When device has internet connection data is synced with Dynamodb at the same time when new record is created but when the device not have the internet connection data is preserved locally that is fine.

But the problem is that when internet connection is back data is not not auto synced with dynamo DB. Data is got synced when a create new record than the current entry and previous preserved entry got synced with db. But i want auto synced with the device internet connection is back.

**Comment by HuiSF** [comment]
> But the problem is that when internet connection is back data is not not auto synced with dynamo DB

In this case, when the device is back online, you can call the API `Amplify.DataStore.start()` to reactivate the DataStore sync engine, which will resume the sync process.

**Comment by anil-softuvo1** [comment]
@HuiSF Works . Thanks for the help and time.

**Comment by anil-softuvo1** [comment]
@HuiSF Hi, I have a one query here can we use amplify app sync/ data store services without adding the amplify auth in our project. I have a scenario where i have to authenticate user with rest api and after that i have to use the amplify app sync services to fetch and store data in dynamo db.

**Comment by anil-softuvo1** [comment]
@HuiSF any update please?

**Comment by HuiSF** [comment]
> I have an existing data table on AWS console and when i have define a model for that in schema file and tried to update a data in the existing table then that is not update in that table and new table will created with the same name.

Could you clarify what do you mean by "existing data table on AWS console"? Is that a DynamoDB table you created outside of Amplify context, and are you trying to use it with Amplify?

**Comment by Jordan-Nelson** [comment]
@anil-softuvo1 - If you are still having this issue, please let us know.

**Comment by Jordan-Nelson** [comment]
@anil-softuvo1 - I am going to close this out since we have not heard back. It looks like the original issue was resolved. If you are still facing the follow up issue can you please create a new issue? Thanks.
