### ISSUE TITLE
DataStore fails to start when close and reopen app, without signing out

### ISSUE THREAD

**Issue by adplant** [aws-amplify/amplify-flutter#2696]
### Description

I am using the Pre-Release version of some of the amplify aws packages:
```
  amplify_flutter: ^1.0.0-next.2
  amplify_auth_cognito: ^1.0.0-next.2+1
  amplify_authenticator: ^1.0.0-next.1+3
  amplify_datastore: ^1.0.0-next.2
  amplify_api: ^1.0.0-next.2+1
```

After a successful sign in and initial sync, if I close the app and re-open it, the DataStore fails to start.

See the attached to view the console output.

Of note, I have another problem, that might stem from this, that follows. When the datastore starts working, the sync happens twice. Many times, the second sync is responsible for hanging the app. You can also see this in the attached console output.
Let me know if I should file this bug separately.
[DataStoreException_fail_to_start_without_comments.txt](https://github.com/aws-amplify/amplify-flutter/files/10820294/DataStoreException_fail_to_start_without_comments.txt)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Authenticate into the app using the prebuilt `SignInForm()`
2. Let the initial sync take place
3. Close the app manually (swipe away the app and remove it from the background)
4. Open the app again and see the problem take place

NOTE: I think this happens on IOS as well, but haven't double checked it. It definitely happens on Android.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.3

### Amplify Flutter Version

10.7.3

### Deployment Method

Amplify CLI

**Comment by adplant** [comment]
Anyone have any info?

**Comment by HuiSF** [comment]
Hi @adplant thanks for opening this issue, and apologies for the delayed reponse.

I took a look at the logs you attached, I noticed that this line right after your App launched, and before the second attempt of syncing:

```
Orchestrator transitioning from SYNC_VIA_API to STOPPED
```

By checking amplify-android DataStore implementation, this log would be generated when `Amplify.DataStore.stop()` API is called. Are you calling this API somewhere in your App implementation? Can you double check if it's being called unexpectedly?

**Comment by adplant** [comment]
@HuiSF Thanks for the response. I will have a look to verify, but my gut is that the answer is no. Again, I will confirm again soon and get back to you.

**Comment by adplant** [comment]
@HuiSF Yes, I do call it one time. It looks like upon a successful sign in via the `Authenticator` widget, I call `updateSync` (which calls `.stop()` and then `.start()`) inside the child widget (which is the homepage after you've signed in).
I'm wondering if that isn't required, and upon successful sign in if the Datastore just starts on it's own (`Amplify.configure()` is called inside the `init()` function of the page that has the `Authenticator` widget).
If that is the case, I guess `updateSync` wouldn't be neccessary. Does that seem right to you?
Does `configure.Amplify()` start the DataStore sync?

**Comment by HuiSF** [comment]
Thanks for confirming @adplant 

After `Amplify.configure()` call, DataStore won't start automatically until its APIs get called (`start`, `save`, `observe` etc.) Hence, if none of the APIs are called in your implementation before the time when you want the DataStore to start syncing, you don't need to call `Amplify.DataStore.stop()`.

If you want DataStore to start syncing after a user signed in successfully, you can call `Amplify.DataStore.start()` on the [Amplify Auth Hub event `SIGNED_IN`](https://docs.amplify.aws/lib/auth/auth-events/q/platform/flutter/).

**Comment by adplant** [comment]
@HuiSF Ok, I understand that `.stop()` doesn't need to be called, but does it hurt?

Is that a reason that I'm seeing the problem I'm seeing?

**Comment by HuiSF** [comment]
It shouldn't matter but back to back calls of `stop` and `start` may cause unexpected issues, as it may introduce race condition on sync engine shutting down and restart. If it's not required by your use case I'd suggest to avoid it.

**Comment by adplant** [comment]
Ok, I will try that out @HuiSF 

Should I open another tickets to ask about why the sync happens twice (as you can see in the log) or do you have any input on that?

**Comment by HuiSF** [comment]
Could you confirm if the 2nd sync still happens after removing the unneeded `stop()` call?

**Comment by adplant** [comment]
@HuiSF Well, things look a lot better! I replaced the `updateSync` with a call to just `start`, and I no longer see the errors, and it only synced once. I think that did it. I'll comment again if I notice the problem in other attempts, but for now it looks like we can probably close this ticket.
Thanks a lot @HuiSF

**Comment by HuiSF** [comment]
Closing as the original question has been resolved. Please feel free to open a new issue if anything.
