### ISSUE TITLE
(iOS - dev preview) signInWithWebUI fails to launch URL

### ISSUE THREAD

**Issue by Groseuros** [aws-amplify/amplify-flutter#2697]
### Description

signInWithWebUI used to work for months and suddenly starts to fail (on iOS only) yesterday. I've literally no idea what could be wrong. I've tested with next.5 & next.5+1 but same result.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Try to use signInWithWebUI with any social provider

### Screenshots

![auth-fails](https://user-images.githubusercontent.com/83779618/221263250-cb088251-502c-4bcf-85a1-e6e70d446175.png)

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

^1.0.0-next.4

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @Groseuros - sorry you are facing this issue! I believe this is due to a recent change in Hosted UI logic. I will investigate and should have a fix shortly.

**Comment by Jordan-Nelson** [comment]
Hello @Groseuros - I'm sorry that you are facing this issue. We seem to have multiple issues tracking this. I am going to close this in favor of https://github.com/aws-amplify/amplify-flutter/issues/2705. It looks like a fix has been merged for this. I would expect it to be included in a release soon.
