### ISSUE TITLE
S3 protected url created with owners identityId expires

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-flutter#2703]
### Description

Similar to a social media app, when user uploads an image with his post, the image is uploaded in protected folder. Which only the owner can delete/write and can be accessed by other with a pre-signed url.

On uploading, I save the pre-signed url in a model. The users' followers can access the model and view the image.

**Upload code:**

`Future<String?> uploadFile(File file) async {
    try {
      final extension = p.extension(file.path);
      final key = const Uuid().v1() + extension;

      final uploadOptions = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.protected,
      );

      await Amplify.Storage.uploadFile(
          local: file,
          key: key,
          options: uploadOptions,
          onProgress: (progress) {
            uploadProgress.value = progress.getFractionCompleted();
          });

      return key;
    } on Exception catch (e) {
      debugPrint(e.toString());
      return null;
    }
  }`

**URL getter code:**

` Future<String> getImageUrlWithId(String key, String identityId) async {
    final GetUrlResult result = await Amplify.Storage.getUrl(
      key: key,
      options: S3GetUrlOptions(
          targetIdentityId: identityId,
          accessLevel: StorageAccessLevel.protected),
    );

    debugPrint(result.url);
    return result.url;
  }`

This issue is, the url saved in the model is getting expired. Should it expire, it is only generated once on uploading the image. Is there any workaround to stop expiring?

Thank you.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.3

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hi @itechevo thanks for the question. S3 object access is backed by presigned URL, a presigned URL [can be effective up to 7 days](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html). 

A presigned URL is only meant for short term access. For your use case, could consider storing **1)** object key, **2)** associated access level, **3)** the `identityId` of the user who originally uploaded the object, when you need to access the object, you can always use `Amplify.Storage.getUrl` to get the URL based on these 3 pieces of information, e.g.

```dart

final model = ...;

final result = await Amplify.Storage.getUrl(
  key: model.objectKey,
  options: S3GetUrlOptions(
    accessLevel: object.accessLevel,  // in your example the value should be StorageAccessLevel.protected
    targetIdentityId: object.identityId
  ),
);
```

**Comment by itechevo** [comment]
Hi @HuiSF, thank you for the response. I will do what you have suggested. Closing this ticket.
