### ISSUE TITLE
[cognito] Uri not awaited

### ISSUE THREAD

**Issue by passsy** [aws-amplify/amplify-flutter#2705]
In `amplify_auth_cognito-1.0.0-next.5+1` is discovered that the uri is not awaited, thus trying to open url `Instance of 'Future<Uri>'` instead of the actual URL. (iOS)

This results in the login not working at all

https://github.com/aws-amplify/amplify-flutter/blob/84efa67b01a580150e28e1bc7c2e5bbb01395c62/packages/auth/amplify_auth_cognito/lib/src/flows/hosted_ui/hosted_ui_platform_flutter.dart#L78

Correct would be
```dart
final signInUri = await getSignInUri(provider: provider);
```

**Comment by dnys1** [comment]
The fix for this has been released in v1.0.0-next.6 of the libraries. Apologies for the delay and thanks for your patience!
