### ISSUE TITLE
Handle password expiration

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#2716]
### Description

Hey,
I need to handle the password expiration for the user in amplify. How we can handle it? I need to set the limit for 1 month. Every used should update password after the one month.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @VishalMakwana20 - one way to do this would be to run a Lambda on a cron schedule (maybe once a day) which checked the last time each user reset their password (being tracked via something like a DynamoDB table). For each user which needed their password reset, you could call [AdminResetPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminResetUserPassword.html) which would force the user to change their password next time the logged in.

Another way would be to implement a custom authentication flow in Cognito: 
- https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-custom-authentication-flow
- https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-challenge.html

This would require a fair bit of customization, though. You would need to have place to keep track of the date/time the user last changed their password (e.g. a DynamoDB table) and implement a set of challenges which your frontend could show a corresponding UI for.

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - Let us know if you have any follow up questions. Otherwise, we will close this out.
