### ISSUE TITLE
Getting SmithyException when user is not confirmed or does not exist

### ISSUE THREAD

**Issue by primico** [aws-amplify/amplify-flutter#2718]
### Description

I am upgrading my flutter project to 1.0.0-next.5 and when I call Amplify.Auth.signIn and the user does not exist or is not confirmed, I get a SmithyException exception thrown in http_operation.dart:

```
UserNotConfirmedException {
message=User is not confirmed.,
}
UserNotFoundException {
  message=User does not exist.,
}
```

According to this, I don't think I should be getting an exception:
https://github.com/aws-amplify/amplify-flutter/issues/2390

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Call Amplify.Auth.signIn
2. SmithyException exception thrown in http_operation.dart when user does not exist or is not confirmed.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

1.0.0-next.5

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @primico - can you confirm that `Amplify.Auth.signIn` is throwing the exception and not returning? This should still be correct:

```dart
final signInRes = await Amplify.Auth.signIn(
  username: username,
  password: password,
);
final userConfirmationNeeded =
    signInRes.nextStep.signInStep == AuthSignInStep.confirmSignUp;
```

If you run your app in Debug mode with breakpoints for exceptions, it will show the exceptions being thrown, but the above code should still work.

**Comment by dnys1** [comment]
I do agree that it shouldn't be tripping the "Uncaught Exceptions" breakpoint. I've opened a PR to hopefully resolve this.

**Comment by primico** [comment]
Yes, my code is exactly what you just posted, and it works, and I use a try/catch to catch AuthExceptions which work, but this other SmithyException is something new that I have only seen after upgrading.

**Comment by brunozorima** [comment]
Hi, is this resolved?

**Comment by primico** [comment]
Along with the others above, I also get this SmithyException prior to the AuthException being caught:

NotAuthorizedException {
  message=Incorrect username or password.,
}
