### ISSUE TITLE
User Attributes uniqueness

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#2721]
### Description

Hi,
I am using email or phone signup method in AWS amplify.

**Case 1: if i signup using email than I am adding phone number in their user profile.  After that I will create new account with that phone number then new account is created with previous email user's phone number. there should be error 'this mobile number is used by other account'**

**Case 2: if i signup using phone number than I am adding email in their user profile.  After that I will create new account with that email then new account is created with previous phone number user's email.there should be error 'this email address is used by other account'**

Is there any way to provide the **uniqueness of email and phone number** attributes in cognito?

Thank you.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @VishalMakwana20 - Cognito will enforce that the "username" is unique. in this case, the "username" is the email address or phone number. Cognito will enforce that these values are unique. However, there is nothing to enforce uniqueness between the "username" value and user attributes.

I don't believe Cognito offers a way to achieve this out of the box. However, you could set up a pre sign-up trigger that does this. A pre sign-up trigger is a lambda trigger that runs prior to signing a user up. [Here is a blog post](https://dev.to/andthensumm/enforcing-attribute-uniqueness-in-cognito-with-aws-amplify-and-react-263f) that explains how to accomplish this. The use case in this blog post is a little different, but the set up would be very similar.

You could also update the sign in alias to be email only (or phone only) which would enforce unique email addresses. However, two users would still be able to sign up with different email addresses using the same phone number, which it sounds like you want to prevent.

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - Let me know if you have any other questions.

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - I am going to close this out since I have not heard back. If you need any further assistance, please open a new issue.
