### ISSUE TITLE
Google account and Normal email/password account interlink

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#2722]
### Description

Hello,
Is there any way to **interlink account of email/password and google account** in  AWS amplify? User can access same account via google login and email/password login from cognito.

Thank you.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @VishalMakwana20 - You could use a Cognito pre sign-up trigger to merge the accounts. There are some known caveats with this approach though. You can read more about that here: https://github.com/aws-amplify/amplify-flutter/issues/1716

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - I am going to close this out since there is another issue tracking this.
