### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by primico** [aws-amplify/amplify-flutter#2729]
### Description

I am getting this error in my app:
```
ConfigurationError {
  "message": "No Storage S3 plugin config detected."
}
```

So I ran:
`amplify storage update`

And I get this error:
```
amplify push
There was an error pulling the backend environment dev.
The specified bucket does not exist
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

1. amplify storage update
2. amplify push

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

1.0.0-next.5

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi have you followed the instructions here to setup storage? 

https://docs.amplify.aws/lib/storage/getting-started/q/platform/flutter/#provision-backend-storage

More specifically, have you run the `amplify add storage` and `amplify push` commands in the cli?

**Comment by primico** [comment]
When I run `amplify add storage`, I get:
`Amazon S3 storage was already added to your project.`

So that is why I am running `amplify storage update`

But then get this error when I run `amplify push`

There was an error pulling the backend environment dev.
The specified bucket does not exist

**Comment by fjnoyp** [comment]
HI @primico can you see if this issue resolution fixes your problem?

https://github.com/aws-amplify/amplify-cli/issues/1739#issuecomment-506348487

**Comment by primico** [comment]
> HI @primico can you see if this issue resolution fixes your problem?
> 
> [aws-amplify/amplify-cli#1739 (comment)](https://github.com/aws-amplify/amplify-cli/issues/1739#issuecomment-506348487)
> 
> Could you also share the console output when running those amplify cli commands?

so I was able to log into the console and create the storage there, then do `amplify pull `successfully..  I recently created a new amplify project and I'm guessing there was something in my project that was left-over from the old project, who knows... but it is working now. thanks!

**Comment by fjnoyp** [comment]
Good to hear!  I'll close this issue.  If another problem comes up feel free to create a new issue so we can help again :)
