### ISSUE TITLE
New data not getting synced to the cloud in amplify studio content management

### ISSUE THREAD

**Issue by dhruv1710** [aws-amplify/amplify-flutter#2739]
### Description

When I add content via amplify studio it doesn't sync to the cloud and shows syncing text forever. Data added through app gets updated locally but also doesn't sync.

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Screenshots

![image](https://user-images.githubusercontent.com/56288398/223953379-a8b7997e-592b-45df-89db-c2d630b4b357.png)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type DoublesMatch @model @auth(rules: [{allow: public}]) {
  id: ID!
  doublesdrawID: ID! @index(name: "byDoublesDraw")
}

type DoublesDraw @model @auth(rules: [{allow: public}]) {
  id: ID!
  Doublesmatches: [DoublesMatch] @hasMany(indexName: "byDoublesDraw", fields: ["id"])
}

type SinglesMatch @model @auth(rules: [{allow: public}]) {
  id: ID!
  Players: [Player] @hasMany(indexName: "bySinglesMatch", fields: ["id"])
  drawID: ID! @index(name: "bySinglesDraw")
}

type SinglesDraw @model @auth(rules: [{allow: public}]) {
  id: ID!
  Matches: [SinglesMatch] @hasMany(indexName: "bySinglesDraw", fields: ["id"])
}

type Team @model @auth(rules: [{allow: public}]) {
  id: ID!
  Players: [Player] @hasMany(indexName: "byTeam", fields: ["id"])
}

type Player @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  age: String
  phone: String
  Tournaments: [Tournament] @manyToMany(relationName: "PlayerTournament")
  teamID: ID! @index(name: "byTeam")
  matchID: ID! @index(name: "bySinglesMatch")
}

type Tournament @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  logo: String
  Players: [Player] @manyToMany(relationName: "PlayerTournament")
}
```

**Comment by fjnoyp** [comment]
Hi @dhruv1710 

I tried to replicate your issue by copying your schema into a Flutter app and calling amplify push.  I then went to Amplify Studio and started editing the data model.  

In Amplify Studio I am able to update the `Player` and see that the data is synced in `DynamoDb`. 

I am unsure of the unique steps you might have taken to setup within AmplifyStudio, but if you continue to have problems there I recommend reaching out to them here: 

https://github.com/aws-amplify/amplify-studio/issues

However, you mentioned that you also cannot send data through your app. 

Can you please verify that you called `amplify pull`.  Also what code are you using to upload?  Can you please share the error/messages you see in the logs?

**Comment by dhruv1710** [comment]
Hi,

Do you know where can I get the logs for adding items. The DynamoDB isn't updated and I want to check if  sync is breaking at any point due to error.

**Comment by fjnoyp** [comment]
Hi @dhruv1710 I meant providing the logs when you are running the app.  When you do that in Android Studio the logs should show up under the bottom `console` tab.

**Comment by abdallahshaban557** [comment]
Hi @dhruv1710  - just to make sure I understand your ask, you would have liked to have the logs in the console streamed to Cloudwatch so that you can debug this issue? Did you catch this issue during your development time, or was it caught after the app was deployed?

**Comment by dhruv1710** [comment]
The issue is on development time I haven't deployed the app yet. And I was asking that where can I find the logs of syncing dynamodb be found so that I can search for any errors.

**Comment by fjnoyp** [comment]
Hi @dhruv1710 it appears your primary concern is with Amplify Studio not allowing you to sync data to the cloud.  In this case I would recommend we create an issue on their Github for their team to better handle your issue.   Before doing so, can you please give more details on what exactly you did in Amplify studio or CLI before so that the team can reproduce your problem? 

https://github.com/aws-amplify/amplify-studio

**Comment by dhruv1710** [comment]
I just followed the amplify flutter guide and later I changed the schema. Anyways I will create a issue in amplify studio github.
Thanks
