### ISSUE TITLE
Upcoming breaking changes for amplify flutter repository.

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-flutter#274]
Hi all,

We have a few breaking changes coming up in our next release as detailed below. Please upgrade your apps appropriately when you upgrade amplify_flutter.

1. **[Released in 0.0.2-dev.1]**  Package amplify_core will be renamed to amplify_flutter and amplify_core will only contain base types and core utils.
For more details, see this RFC https://github.com/aws-amplify/amplify-flutter/issues/263 and PR https://github.com/aws-amplify/amplify-flutter/issues/273.

The breaking change will be the path to importing `Amplify`

```diff
- import 'package:amplify_core/amplify_core.dart';
+ import 'package:amplify_flutter/amplify.dart';
```

2. **[Released in 0.0.2-dev.1]**  Top level Amplify class is now a static singleton, so you don't need to instantiate it before calling `configure()` or `addPlugin()`
```diff
- Amplify amplify = new Amplify();
- amplify.configure(amplifyconfig);
+ Amplify.configure(amplifyconfig);
```

3. **[Released in 0.0.2-dev.1]** `addPlugin` now takes a single plugin instance without the need for named parameters. You can alternatively use a new `addPlugins([AmplifyPlugins])` to add all the plugins at the same time.
```diff
AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
AmplifyStorageS3 storagePlugin = AmplifyStorageS3();
AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();

- amplify.addPlugin(authPlugins: [authPlugin], 
-        storagePlugins: [storagePlugin], 
-        analyticsPlugins: [analyticsPlugin]);
+ Amplify.addPlugin(authPlugin);
+ Amplify.addPlugin(storagePlugin);
+ Amplify.addPlugin(analyticsPlugin);

// or alternatively Amplify.addPlugins([authPlugin, storagePlugin, analyticsPlugin]);
```

4. **[Released in 0.0.2-dev.1]**  Hub Events will be exposed as instantiated Dart types with typed payload data, instead of simple Maps.  They will also be accessed with a new API that allow for subscriptions which listen on multiple channels simultaneously:

```dart
hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) {
    /// do something with data
});
```

5. **[Released in 0.0.2-dev.2]**  Datastore Temporal types will add support for `AWSTime` and `AWSDate` via our new classes `TemporalTime` and `TemporalDate`.  Furthermore, we will introduce a breaking change by replace the underlying types for `AWSDateTime` and `AWSTimestamp`.  

`AWSTimestamp` will change from `int` -> `TemporalTimestamp` 
`AWSDateTime` will change from Dart:core's `DateTime` -> `TemporalDateTime`. 

Thus you will need to use the constructor for these classes when saving to fields for `AWSTimestamp` and `AWSDateTime`. 

TemporalDateTime constructors: 
```dart
static TemporalDateTime now() 
TemporalDateTime(DateTime dateTime)
TemporalDateTime.withOffset(DateTime dateTime, Duration offset)
TemporalDateTime.fromString(String iso8601String)
```
TemporalTimestamp constructors: 
```dart
TemporalTimestamp(DateTime date) 
TemporalTimestamp.fromSeconds(int secondsSinceEpoch)
```

6. **[Released in 0.0.2-dev.2]**  Exceptions thrown by amplify-flutter will be changing. Calling top level Amplify libraries may result in one of the following exceptions `AmplifyException` `AmplifyAlreadyConfiguredException`.

* Each category will have it's own exception (such as `AuthException`, `DataStoreException`) which are subclasses of `AmplifyException`
* There won't be a platform exceptions map, rather most exceptions will be simplified to

https://github.com/aws-amplify/amplify-flutter/blob/741a62827f90c6df156d5c437c013fe9a4ceae76/packages/amplify_core/lib/types/exception/AmplifyException.dart#L18-L26

PRs for this change: #314, #322, #329

7. **[Released in 0.0.2-dev.2]** To enable syncing data to cloud, [customers will need to add the APIPlugin() to their app](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter#add-the-api-plugin). This was done automatically before 0.0.2-dev.2.

8. **[Released in 0.0.2-dev.2]** The `userAttributes` passed to `CognitoSignUpOptions` for the `.signUp` API must consist of a Map<String, String> instead of Map<String, dynamic>:
```
 Map<String, String> userAttributes = {
    'email': 'email@domain.com',
    'phone_number': '+15559101234',
    // additional attributes as needed
  };
  SignUpResult res = await Amplify.Auth.signUp(
    username: 'myusername',
    password: 'mysupersecurepassword',
    options: CognitoSignUpOptions(
      userAttributes: userAttributes
    )
  );
  ```

**Comment by Amplifiyer** [comment]
Changes 1 through 4 are released in the new version 0.0.2-dev.1

**Comment by jcowley** [comment]
I can enter a separate issue for this, but I just want to make sure I understand these changes. If you call `Amplify.configure(amplifyconfig)` twice, you get the following error:
```
StateError (Bad state: Amplify has already been configured and re-configuration is not supported.)
```
If that's intended, and `Amplify` is now a Singleton, does that mean you are not able to ever use more than a single type of "authenticationFlowType" as you can, for example, with amplify-js: https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js.

An example of why this would be needed would be switching over to a CUSTOM_AUTH flow from the default USER_SRP flow for certain use cases.

**Comment by Amplifiyer** [comment]
Overview updated with upcoming exception handling refactor change.

**Comment by Amplifiyer** [comment]
Changes 5 and 6 are released in 0.0.2-dev.2

**Comment by kjones** [comment]
Not sure if I was just getting lucky before 0.0.2-dev.2 but another breaking change seems to be that AmplifyAPI plug must now be manually added when using DataStore for backend sync to happen.

**Comment by Amplifiyer** [comment]
> 
> 
> Not sure if I was just getting lucky before 0.0.2-dev.2 but another breaking change seems to be that AmplifyAPI plug must now be manually added when using DataStore for backend sync to happen.

Good catch. We didn't have the API Plugin implemented before so the native library's API plugin was added by default to get the online sync working. Now the customers would need to add the API plugin specifically to their app like other platforms. I'll update this issue.

**Comment by SalahAdDin** [comment]
Will this be?
