### ISSUE TITLE
Auth - WebUI - Showing Google sign in confirmation screen

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#2745]
### Description

![image (1)](https://user-images.githubusercontent.com/53246428/224680709-43a57bdf-c1d7-4de8-82eb-24dd9c414727.png)
![image](https://user-images.githubusercontent.com/53246428/224680720-4a2abf1a-c7f3-4ba5-9829-acc12c81a641.png)

Can we implement google account selection flow like shown on the above screenshots?
currently in amplify, Web page open and we select account there is no confirmation on that flow. directly user logged in after the account selection. can we update this flow?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - I want to make sure I understand the request. There should be an account chooser dialog similar to the one presented in the screenshot above. It sounds like you would also like there to be a dialog that displays the scopes being granted (name, email address, and profile picture in the example above). Is that correct?

**Comment by VishalMakwana20** [comment]
@Jordan-Nelson -  Yes, at my side second dialog will not appear. account chooser dialog is displaying only.

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - As @fjnoyp noted using Google's sign in SDK would allow you to achieve this. This isn't supported currently, but it is being tracked [here](https://github.com/aws-amplify/amplify-flutter/issues/438). I am going to close this out as a duplicate.
