### ISSUE TITLE
"confirmSignIn called on unsupported operation" when using Custom Challenge (amplify_auth_cognito For Flutter)

### ISSUE THREAD

**Issue by bostaginting** [aws-amplify/amplify-flutter#276]
**Describe the bug**
When we try to call confirmSignIn using CONFIRM_SIGN_IN_WITH_CUSTOM_CHALLENGE, it returns an error stating "AmplifyException {message=Confirm sign in failed, cause=java.lang.IllegalStateException: confirmSignIn called on unsupported operation, please file a feature request, recoverySuggestion=See attached exception for more details}". This only happens in the Android build from the Flutter project and works well with the iOS build.

**Expected behavior**
After we call confirmSignIn, if the correct (Custom) OTP is used, then user is signed in. Again, this already works with amplify-flutter on iOS.

**Screenshots**
<img width="961" alt="Screen Shot 2020-12-25 at 17 09 15" src="https://user-images.githubusercontent.com/40355270/103131653-2dc79e00-46d4-11eb-949f-a69ade9f55ec.png">

**Platform**

amplify version: 4.26.1-flutter-preview.0
Amplify Flutter supports iOS and Android. This issue is reproducible in:
[Y] Android
[N] iOS

Smartphone :

Device: [AOSP in IA Emulator]
OS: [Android version 9]
Version [Android version 9]

**Additional context**
I understand Amplify flutter library uses native libraries through channeling in flutter. I found the code that throws this exception here[1].  it looks like login by custom challenge is not implemented.

[1] https://github.com/aws-amplify/aws-sdk-android/blob/c6a24e945253206c84027d87e5bdb8ce3eab3dcf/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1332

**Comment by haverchuck** [comment]
#https://github.com/aws-amplify/amplify-android/issues/805

**Comment by bostaginting** [comment]
Hi, any solution for this problem? thank you.

**Comment by satyasrikantmantha** [comment]
Hi,

I am also experiencing the same issue with Android whereas with iOS emulators it works well. Any ideas how can we resolve this issue quickly. This is a showstopper for us.

**Comment by fjnoyp** [comment]
Hi @bostaginting @satyasrikantmantha sorry you've been having issues with this.  Our Dart Library is built on top of the native Android/iOS Amplify libraries which is where this issue is originating from.  They resolved the issue on native Android by using an escapeHatch (https://github.com/aws-amplify/amplify-android/issues/805).  We are looking into adding support for escapeHatch possibly in the future in our Dart library as well

**Comment by offlineprogrammer** [comment]
Hi @bostaginting @satyasrikantmantha

With the Android PR merged in, confirm sign-in with custom challenge now works with Amplify.

Feel free to test using the latest build and let us know if you got any issues

Regards
Mo
