### ISSUE TITLE
Selective Sync for DataStore includes records not matching the query predicate

### ISSUE THREAD

**Issue by sibyl229** [aws-amplify/amplify-flutter#2764]
### Description

Selective Sync for DataStore appears to have no effect. Instead, it seems that a full sync is performed, disregarding the syncExpressions. 

This is based on the observation that the event payload for DataStore `modelSynced` event indicates the number of records added to be greater than expected, that should match the query predicate in the SyncExpression.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

**Prerequisite**:
`Amplify.DataStore.save` was used to save and persist to backend some records, some of which created and owned by the current user, others were owned by other users and the current user is granted read access via groups.

**Steps to reproduce**:
1. Add a breakpoint via the debugger to stop at the `modelSynced` DataStore events. The line to add the breakpoint is noted in the code below.
2. Restart the app and click on continue if any breakpoint is triggered.
3. Login the app (implemented with Amplify UI Authenticator).
4. After login, the breakpoint should be triggered (programmatically by listening to Auth event SIGNED_IN, and the event payload can be inspected.

**Expected**: the `added` count in the event payload is expected to equal the number of records matching the syncExpression predicate. In this case, the query predicate specifies to sync only records owned by a particular user.
**Actual**: the `added` count is greater than the number of matching records of the syncExpression predicate. In this case, the `added` count corresponds to total records either owned by the user or the user is granted read access.

**Here is my code**:

```dart
void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late StreamSubscription? authEventsSubscription;

  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  @override
  void dispose() {
    authEventsSubscription?.cancel();
    super.dispose();
  }

  void _configureAmplify() async {
    await Amplify.addPlugins([
      AmplifyAuthCognito(),
      AmplifyDataStore(
        modelProvider: ModelProvider.instance,
        syncExpressions: [
          DataStoreSyncExpression(
            Lot.classType,
            () => Lot.OWNER.eq('A hardcoded user id'), // hardcode user id is used to reproduce the problem
            // () => Lot.ID.eq('a hardcoded ID'), // I also tested with this query. It also led to extra records being synced
          ),
        ],
      ),
      AmplifyAPI(),
    ]);

    try {
      await Amplify.configure(amplifyconfig);
      await Amplify.DataStore.stop();
      await Amplify.DataStore.clear();
      await Amplify.DataStore.start();

      final x = Amplify.Hub.listen([HubChannel.DataStore], (event) {
        if (event.eventName == 'modelSynced') {
          print(event.payload); // I added a breakpoint here to check the number of records added
        }
      });
      authEventsSubscription =
          Amplify.Hub.listen([HubChannel.Auth], (event) async {
        if (event.eventName == 'SIGNED_IN') {
          await Amplify.DataStore.stop();
          await Amplify.DataStore.clear();
          await Amplify.DataStore.start();
        } else {
          await Amplify.DataStore.stop();
          await Amplify.DataStore.clear();
        }
      });
      print('Successfully configured');
    } on Exception catch (e) {
      print('Error configuring Amplify: $e');
    }
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Authenticator(
      initialStep: AuthenticatorStep.signIn,
      child: MaterialApp(
        builder: Authenticator.builder(),
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const MyHomePage('),
      ),
    );
  }
}
```

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.3

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Lot
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groupsField: "readers", operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  readers: [String]
}
```

**Comment by HuiSF** [comment]
Hi @sibyl229 thanks for opening this issue. I couldn't reproduce this issue, however.

With sync expression, the `added` property in the payload always matches the number of record that I was expecting.

Setup:

**Schema**
```graphql
type AModel @model {
  id: ID!
  procedure: String
}
```

* Added 10 records of `AModel` assigning value `aaa` to `procedure`
* Added 5 records of `AModel` assigning value `bbb` to `procedure`

**Sync expression**

```dart
final datastorePlugin = AmplifyDataStore(
  modelProvider: ModelProvider.instance,
  syncExpressions: [
    DataStoreSyncExpression(
      AModel.classType,
      () => AModel.PROCEDURE.eq('bbb'),
    ),
  ],
);
```

**Payload of `modelSynced` event**
<img width="334" alt="image" src="https://user-images.githubusercontent.com/10602282/226069760-d14ae07b-5b9e-4c24-a570-f025df9861a8.png">

<details>
<summary>Underlying sync query</summary>
The query returned 5 items.

```
{
	"query": "query SyncAModels($filter: ModelAModelFilterInput, $limit: Int) {
		syncAModels(filter: $filter, limit: $limit) {
			items {
				id
				createdAt
				procedure
				updatedAt
				__typename
				_version
				_deleted
				_lastChangedAt
			}
			nextToken
			startedAt
		}
	}",
	"variables": {
		"filter": {
			"and": [{
				"procedure": {
					"eq": "bbb"
				}
			}]
		},
		"limit": 1000
	}
}
```

</details>

Regarding:

> Expected: the added count in the event payload is expected to equal the number of records matching the syncExpression predicate.

* How do you determine "the number of records matching the syncExpression predicate"?
* Could also try to use `Amplify.DataStore.query` using the same predicate, and get a diff what's unexpected
* Did you get a chance to check the corresponding DynamoDB table whether it contains "unexpected" records?

**Comment by sibyl229** [comment]
Hi @HuiSF thank you so much for trying to replicate my issue and the detailed write up.

You are right. There is no issue after all. It's entirely my mistake.

The reason for my observation was not doing a **full restart** after changing the syncExpression. I am new to Flutter from a web background, and I mistook the debugger restart button of VS code to do the trick of a full restart. What I should have done was to stop the debugger and start a new debugger.

Sorry about the trouble! I will close this issue now.
