### ISSUE TITLE
Problem with user attributes when creating account via Apple - family_name

### ISSUE THREAD

**Issue by Mik77o** [aws-amplify/amplify-flutter#2772]
### Description

After creating first time an account via `signInWithWebUI` method and provider as Apple, I get the first name and last name merged to one attribute: family_name.

```
     SignInResult res = await Amplify.Auth.signInWithWebUI(
        provider: AuthProvider.apple,
        options: const CognitoSignInWithWebUIOptions(isPreferPrivateSession: false),
      );
```
Also, `given_name` attribute is missing.

For Google provider and the usual registration process with password and email: `given_name` is available and `family_name` contains only the last name.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Screenshots

<img width="187" alt="Screenshot 2023-03-22 at 11 30 27" src="https://user-images.githubusercontent.com/26656256/226876336-552fe4a1-e61f-4aae-a491-e7afddbb68d6.png">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @Mik77o - for SignInWithApple, your screenshot shows that `family_name` should not be provided but `name` should contain the user's full name. Are you saying that `family_name` contains the full name and `name` contains nothing when signing in with Apple?

Can you share the result of calling `Amplify.Auth.fetchUserAttributes` when signed in with Apple?

**Comment by Mik77o** [comment]
@dnys1 Yes,` name` contains full name and `family_name` contains full name (registration via Apple). 

`Given_name` attribute is not available for this registration method. For e.g. Google registration, `given_name` is returned and `family_name` is returned. `Given_name` contains only first name and `family_name` contains only last name. 

However, when I create an account via Apple Id, `family_name` contains first and last name concatenated and `given_name` is not available.

`Amplify.Auth.fetchUserAttributes`

_AuthUserAttribute (AuthUserAttribute(userAttributeKey=name, value=John Test))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=sub, value=xxxxx))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=phone_number, value=xxxxx))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=family_name, value=John Test))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=email, value=mytestemail))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=phone_number_verified, value=true))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=email_verified, value=false))

AuthUserAttribute (AuthUserAttribute(userAttributeKey=identities, value=[{"userId":"xxxxx","providerName":"SignInWithApple","providerType":"SignInWithApple","issuer":null,"primary":false,"dateCreated":1679556644852}]))_

**Comment by Mik77o** [comment]
@dnys1 I'm not sure but maybe it's related to https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple. 

Here's an important piece of text

_Retrieve the user’s information from Apple ID servers
The information you retrieve must include the credentials required to verify the user’s identity. The server returns the credentials and user information based on the initial request. The information that returns can include user identity, **full name**, verified email address, and real user status._

**Comment by dnys1** [comment]
Hi @Mik77o, yes, Apple will only ever return the full name, not the components. This differs from Google's behavior. 

I'm not sure why the `family_name` field would be populated for Apple sign-in. Regardless, this is something you will need to manually handle in your logic since the given/family name are not available directly from Apple.

Thanks for following up. I'm going to close this issue for now since this is not something on Amplify's end. Please feel free to follow up if you have any other questions.

**Comment by SCMG7** [comment]
how did you resolve the issue?

**Comment by AnujPandeyOgma** [comment]
So, what is the solution?
