### ISSUE TITLE
 Does amplify-flutter support auth chrome extension?

### ISSUE THREAD

**Issue by Ekoios-Teddy** [aws-amplify/amplify-flutter#2775]
### Description

I'm building chrome extension and when login with chrome, i got "your file couldn't be accessed. So i wanna know this support chrome extension?
<img width="148" alt="Screenshot 2023-03-24 at 10 01 33" src="https://user-images.githubusercontent.com/83799773/227413431-3f67c779-006d-47b9-acae-a30953a9b923.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.6

### Amplify Flutter Version

1.0.0.nex-.6

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @Ekoios-Teddy. Amplify Flutter does not officially support Google Chrome extensions. If you can share any specific console errors and steps you've tried, I'd be happy to help however I can.

**Comment by Ekoios-Teddy** [comment]
@dnys1 I'm using `flutter build web --web-renderer html --csp ` to build chrome extension and import it to chrome extension to launch. Then, i login with google by this method when click on the button. 
```dart
 Future<bool> signInWithSocialWebUI(AuthProvider provider) async {
    try {
      final SignInResult result = await Amplify.Auth.signInWithWebUI(
          provider: provider,
          options: const CognitoSignInWithWebUIOptions(
              isPreferPrivateSession: true));
      if (result.isSignedIn) {
        return true;
      }
      return false;
    } catch (e) {
      rethrow;
    }
  }
```
  After click i get this warning on console and extension show back screen "couldn't be accessed". i'm guessing that when login using WebUi, the `Amplify.Auth.signInWithWebUI()` function redirect link to go to google login page (the same log in google on the website) but the extension can't open that link so it gives the above error.
<img width="997" alt="Screenshot 2023-03-27 at 10 48 48" src="https://user-images.githubusercontent.com/83799773/227836589-ed1eca54-04c1-424c-8d11-213e4dad3185.png">

<img width="152" alt="Screenshot 2023-03-27 at 10 48 57" src="https://user-images.githubusercontent.com/83799773/227836585-6cd5a7b9-63fb-4031-9328-2ed0c88e0f41.png">
