### ISSUE TITLE
Connection to existing Cognito resources insists on Identity Pool

### ISSUE THREAD

**Issue by jhw** [aws-amplify/amplify-flutter#2779]
### Description

Hello,

I'm trying to get Amplify Flutter auth to connect to existing Cognito resources, as detailed here -

https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter/

I just want email + password workflow, and have elected to use Cognito `ALLOW_USER_SRP_AUTH` flow rather than `ALLOW_USER_PASSWORD_AUTH` flow because of the extra security it seems to offer.

In particular I do not want or need social or federated auth at this stage. Noting the following from the link above -

```
If you are using a Cognito User Pool, without a Cognito Identity Pool, you can omit the CredentialsProvider section in the configuration.
```

I have therefore only defined a Cognito User Pool (and associated User Pool Client) on the backend; I have *not* defined an Identity Pool.

I start with `awsconfig` as follows -

```
final amplifyconfig = '''
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {}
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "<my user pool id>",
            "AppClientId": "<my app client id>",
            "Region": "<my AWS region>"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
''';
```

However this leads to the following errors -

```
I/amplify:flutter:auth_cognito(12188): Added Auth plugin
D/AWSMobileClient(12188): Using the SignInProviderConfig from awsconfiguration.json.
I/flutter (12188): An error occurred configuring Amplify: AmplifyException(message: Failed to instantiate AWSMobileClient, recoverySuggestion: See attached exception for more details, underlyingException: java.lang.RuntimeException: Failed to initialize Cognito Identity; please check your awsconfiguration.json)
E/amplify:flutter:auth_cognito(12188): AuthException
```

So I then tried removing the blank `Default` options -

```
final amplifyconfig = '''
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "PoolId": "<my user pool id>",
            "AppClientId": "<my app client id>",
            "Region": "<my AWS region>"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
''';
```

which leads to 

```
I/amplify:flutter:auth_cognito(14413): Added Auth plugin
D/AWSMobileClient(14413): Using the SignInProviderConfig from awsconfiguration.json.
2
D/AWSMobileClient(14413): Inspecting user state details
```

and then

```
W/CognitoUserSession(14413): CognitoUserSession is not valid because idToken is null.
D/AWSMobileClient(14413): Sending password.
D/AWSMobileClient(14413): Using USER_SRP_AUTH for flow type.
D/AWSMobileClient(14413): _federatedSignIn: Putting provider and token in store
W/AWSMobileClient(14413): Failed to federate tokens during sign-in
W/AWSMobileClient(14413): java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
```

So this feels like progress - it seems like the user was successfully signed in, but why is Amplify signalling that I need an Identity Pool, when the docs explicitly say that a User Pool can be used on its own ?

(could it be that the extra complexity of `ALLOW_USER_SRP_AUTH` over `ALLOW_USER_PASSWORD_AUTH` requires an Identity Pool ?)

TIA.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

N/A

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @jhw, sorry you are facing this issue. I'm not sure why it would be failing as all the information I can find suggests you are doing things correctly.

The `v0` Amplify libraries will soon be going into maintenance mode. I believe this will work out-of-the-box in our developer preview version (`v1.0.0-next.7`, currently). I found a few APIs which did not work (devices, and global sign out), but have a [PR](https://github.com/aws-amplify/amplify-flutter/pull/2791) up to fix those issues. Otherwise, you should able to use the version of amplifyconfiguration without `Default` to configure "user pool-only" mode.

Please let me know if you face any issues with the v1 SDKs.

**Comment by jhw** [comment]
FWIW the solution seems simply to add an Identity Pool (with associated roles and role mapping) to the Cognito backend resources. I haven't found a way to turn off federation or make it work without an Identity pool. I think the bit about "Identity pool being optional" should probably be removed from the Amplify docs.
