### ISSUE TITLE
Field with field level authorization not showing value when queried after saving

### ISSUE THREAD

**Issue by sibyl229** [aws-amplify/amplify-flutter#2782]
### Description

This problem I am experiencing has to do with DataStore. I noticed the problem when trying to edit something I have just saved to the DataStore. The DataStore.query call returns the object missing the `privateNote` field (schema attached below), while other fields are present correctly.

The `privateNote` field uses field level authorization to keep it hidden from those granted access via the model level authorization. If I remove the field level authorization, the field value is displayed correctly.

In addition, if I logout and login again (and clear the datastore in the process), the `privateNote` field appear correctly in the query response. However, simply stop and start the datasotre does not work.

Here is my code that interacts with the DataStore:

```dart
final myThingsRepositoryProvider =
    FutureProvider<MyThingsRepository>((ref) async {
  final isSignedIn = await ref.watch(userProfileProvider.future);

  if (isSignedIn == null) {
    return Completer<MyThingsRepository>().future; // loading state
  }

  return Future.value(MyThingsRepository(ref));
});

final listMyThingsProvider = StreamProvider((ref) async* {
  final myThingRepo = await ref.watch(myThingsRepositoryProvider.future);
  yield* myThingRepo.listMyThings();
});

final myThingProvider =
    StreamProvider.family<Thing, String>((ref, id) async* {
  final myThingRepo = await ref.watch(myThingsRepositoryProvider.future);
  yield* myThingRepo.getMyThingById(id);
});

class MyThingsRepository {
  MyThingsRepository(this.ref);

  final Ref ref;

  Future<void> addMyThing(Thing thing) async {
    await Amplify.DataStore.save(thing);

    // the following code is added to demonstrate the problem with the query result
    final s = await Amplify.DataStore.query(
      Thing.classType,
      where: Thing.ID.eq(thing.id),
    );
    print(s);  // breakpoint added before this line
  }

  Future<void> deleteMyThing(Thing thing) async {
    await Amplify.DataStore.delete(thing);
  }

  Future<void> updateThing(Thing thingChange) async {
    final thingOld = await Amplify.DataStore.query(
      Thing.classType,
      where: Thing.ID.eq(thingChange.id),
    );
    final thingNew = thingOld.first.copyWith(
      readers: thingChange.readers,
      privateNote: thingChange.privateNote,
      collectingStartedDate: thingChange.collectingStartedDate,
    );
    await Amplify.DataStore.save(thingNew);
  }

  Stream<List<Thing>> listMyThings() {
    return Amplify.DataStore.observeQuery(
      Thing.classType,
    ).map((event) {
      return event.items.toList();
    });
  }

  Stream<Thing> getMyThingById(String id) {
    return Amplify.DataStore.observeQuery(
      Thing.classType,
      where: Thing.ID.eq(id),
    ).map((event) {
      return event.items.toList().single;
    });
  }
}

```

Thanks in advance!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.8

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Thing
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groupsField: "readers", operations: [read] }
    ]
  ) {
  id: ID!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
  readers: [String]
  collectingStartedDate: AWSDate
  privateNote: String @auth(rules: [{ allow: owner }])
}
```

**Comment by HuiSF** [comment]
Hi @sibyl229 in general field level auth is not supported in DataStore use cases. If you are adding the field auth according the warning printed in Amplify CLI, you can ignore the warning.

Could you try to remove the field level auth and revalidate if things work as expected?

**Comment by sibyl229** [comment]
Hi @HuiSF thanks a lot for the reply! Yes, without the field level auth, the field value is correctly populated when queried.

> If you are adding the field auth according the warning printed in Amplify CLI, you can ignore the warning.
Are you referring to the warning about owners may reassign ownership? And that can/should be ignored?

Besides the owner field, there is another field that I need to restrict access to, even though the rest of the object is granted access. I will try to make this field a @hasOne relationship instead and apply a model level authorization on the corresponding model instead.

Please feel free to close the issue.

**Comment by HuiSF** [comment]
>Are you referring to the warning about owners may reassign ownership? And that can/should be ignored?

Yes, this warning can be ignore in a DataStore context. 

>I will try to make this field a @hasone relationship instead and apply a model level authorization on the corresponding model.

That's a interesting idea!

I'm closing this issue as the original problem has been resolved. Please feel free to reach out again when you need any assistance.
