### ISSUE TITLE
IOS devices logging out after OS update.

### ISSUE THREAD

**Issue by dennougorilla** [aws-amplify/amplify-flutter#2788]
### Description

IOS devices logging out after OS update.
``` 
  amplify_auth_cognito:
  amplify_authenticator:
  amplify_flutter:
```
Is there a way around this?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

>=2.17.3 <3.0.0

### Amplify Flutter Version

0.6.5

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hi @dennougorilla Thanks for reporting this issue. Could you provide more details to help triaging?

* Is this issue reported by an end user of your App or found in a testing environment?
* re: "OS update" from what version to what version?
* Was it a normal iOS OTA update, or otherwise how was the update performed?

**Comment by dennougorilla** [comment]
@HuiSF Thanks for replay!
>Is this issue reported by an end user of your App or found in a testing environment?
End user reported this issue.
>re: "OS update" from what version to what version?
Waiting for end user reply.
>Was it a normal iOS OTA update, or otherwise how was the update performed?
Maybe normal iOS OTA.

Some users seem to have problems and others do not. 
Am I correct in understanding that flutter cognito uses KeyChain and therefore does not log out after iOS UPDATE?
I have seen an issue with another iOS app that logs out after an iOS UPDATE if there is not enough storage space on the device.

**Comment by fjnoyp** [comment]
@dennougorilla  - If you are still facing this issue can you please provide the info requested above? Thanks.

**Comment by Jordan-Nelson** [comment]
@dennougorilla - Closing this out since we have not heard back. If you are still experiencing this issue, please provide the info requested above. Thanks.
