### ISSUE TITLE
Is it safe for the client secret to be stored on the frontend?

### ISSUE THREAD

**Issue by rayhaanq** [aws-amplify/amplify-flutter#280]
I'm working through the amplify docs for configuring for flutter. After running the CLI commands to create the `amplifyconfiguration.dart` file I noticed that the client secret is stored in the file too. Is this safe? My understanding was that client secrets should only be kept in the backend. I'm familiar with using amplify-js for most of my other projects. I only create an app client without the client secret and use that for those projects. 

Alternatively, is there any documentation or examples that I can use to create a custom `amplifyconfiguration.dart` file? What are all the configuration options in that file? Thanks

**Comment by Amplifiyer** [comment]
@rayhaanq, `amplifyconfiguration.dart` is equivalent to `amplify_exports.js` file generated in amplify-js library. It only contains end points configuration and no secrets. Can you expand on which key in the json you feel is sensitive and shouldn't be included?

**Comment by rayhaanq** [comment]
I've stopped using amplify-flutter but the generated `amplifyconfiguration.dart` file contained the ClientSecret under ClientId

**Comment by jamesonwilliams** [comment]
Thanks, @rayhaanq you for reporting your concern. This question looks similar to https://github.com/aws-amplify/docs/issues/2021. For a public app, the usage of the app client with a secret doesn’t present a security issue. An app client created with or without a secret provides the same level of access.

**Comment by rayhaanq** [comment]
ah, okay cool. Thanks
