### ISSUE TITLE
AWS Amplify logs out users randomly

### ISSUE THREAD

**Issue by akshat-cldcvr** [aws-amplify/amplify-flutter#2806]
### Description

I am experiencing an issue with AWS Amplify where users are logged out randomly, even when actively using the application. This is causing a poor user experience and frustration for our users.

I have checked the logs in the AWS Amplify console and there are no error or warning messages related to user authentication or session management. Additionally, the network connectivity of our application is stable and there are no intermittent connectivity issues.

I have also tried increasing the session timeout value to see if it resolves the issue, but the problem persists.

Steps to reproduce:
1. Log in to the application using AWS Amplify.
2. Use the application usually, navigating between pages and performing actions.
3. After some time, the user is logged out randomly.

Expected behavior:
Users should not be logged out randomly while actively using the application.

Actual behavior:

Users are logged out randomly while actively using the application.

Environment details:

amplify_flutter: ^0.6.3
amplify_auth_cognito: ^0.6.3
amplify_api: ^0.6.3
amplify_authenticator: ^0.2.2

Operating system: Android

Please let me know if you need any additional information or if there are any steps I can take to resolve this issue. Thanks in advance for your help

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Log in to the application using AWS Amplify.
2. Use the application usually, navigating between pages and performing actions.
3. After some time, the user is logged out randomly.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.0.0

### Amplify Flutter Version

0.6.3

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @akshat-cldcv - I have a few follow up questions.
- What length of time do you have configured for toke expiration for access token, id token, and refresh token? You can find this info in the AWS Cognito console under User Pools -> Your User Pool ID -> App Client -> Your App Client ID. If you created the app with the Amplify CLI and did not customize it, it is likely set to 60 min for access/id and 30 days for refresh tokens.
- How long after the user has authenticated do you see this occur?
- Can you share the logs from a session in which this occurred?

**Comment by akshat-cldcvr** [comment]
Hi @Jordan-Nelson 

- Yes, it's 60 min for access/id and 30 days for refresh tokens as we created it using Amplify CLI and did not customize it. 

This looks like the likely cause of the problem, so we have increased its duration to test it out.

But then why only a few users are experiencing this issue and not all of them?


I am closing this issue for now to test out this in detail.

**Comment by Jordan-Nelson** [comment]
@akshat-cldcvr - If it is set to 60 min for access/id and 30 days for refresh, all users should stay authenticated for 30 days. The only way to update the refresh token is to re-authenticated the user with username/password.

There is a [known issue](https://github.com/aws-amplify/amplify-flutter/issues/760) when a user is offline that would cause a SessionExpiredException prior to the refresh token expiring. If you are seeing some users reporting that they are being logged out early, it is possible that this is the cause. It would only happen if the user was offline though. This issue has been addressed in the developer-preview version (v1.0.0) of amplify flutter. This version is in preview right now, but we expect it to become stable soon.

**Comment by ulrickpsp** [comment]
I'm having the same exact issue the OP is reporting.
