### ISSUE TITLE
Library not loaded: @rpath/AWSAuthCore.framework/AWSAuthCore

### ISSUE THREAD

**Issue by harrynguyen2510** [aws-amplify/amplify-flutter#2816]
### Description

After Xcode build done.   
The app crashed and showed on debug console: 
(lldb) dyld[1381]: **Library not loaded: @rpath/AWSAuthCore.framework/AWSAuthCore**
  Referenced from: <8CE590C0-F3C7-3DC3-9BDD-13154E54A6A3> /private/var/containers/Bundle/Application/20204677-B039-4BF5-8DAB-4C28F126963C/Runner.app/Runner

Before that, I **run pod install --repo-update** and might be the reason got this issue 

<img width="950" alt="Screenshot 2023-04-05 at 12 33 32" src="https://user-images.githubusercontent.com/59348244/229966459-64a4dec5-a0d9-490d-861c-b97b4826fa94.png">

this is doctor inspection 

<img width="717" alt="Screenshot 2023-04-05 at 12 34 16" src="https://user-images.githubusercontent.com/59348244/229966564-a3d53719-4dd1-4575-bbe1-86b837d34786.png">

Did do flutter clean and pub get again, checked that libraries are installed 

How to fix Xcode know the path to load library 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.9

### Amplify Flutter Version

0.6.13 

### Deployment Method

Amplify CLI

**Comment by harrynguyen2510** [comment]
<img width="753" alt="Screenshot 2023-04-05 at 12 39 15" src="https://user-images.githubusercontent.com/59348244/229967235-94b47b60-2c04-49e4-81f9-a5161821dced.png">

Did follow ChatGPT guideline but can not fix

**Comment by Jordan-Nelson** [comment]
Hi @harrynguyen2510 - I am not sure what is causing this, but it appears to be related to a cached build. I would try the following:
- `flutter clean`
- `rm -rf ios/.symlinks`
- `rm -rf ios/pods`
- `rm ios/Podfile.lock`
- `flutter pub get`

What iOS device are you building for? iPhone simulator?

**Comment by Jordan-Nelson** [comment]
@harrynguyen2510 - What version of Xcode are you using?

**Comment by MarlonJD** [comment]
Go to iod/Podfile:

Add this lines between to `post_install do |installer|` and `end`

```
installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
```

it should looks like this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
```

then run `cd ios` and `pod install --repo-update`. And go to `ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh` then 

Find
```
source="$(readlink "${source}")"
```

and replace to:

```
source="$(readlink -f "${source}")"
```

now you can archive. Everytime you run pod install you have to change `Pods-Runner-frameworks.sh` file

**Comment by MarlonJD** [comment]
https://github.com/aws-amplify/amplify-flutter/issues/2818#issuecomment-1497648882

**Comment by harrynguyen2510** [comment]
@Jordan-Nelson thanks for reply, I'm using 14.3 Xcode, and have tried your suggestion but not working

**Comment by harrynguyen2510** [comment]
@MarlonJD thank you so much, it solved it
