### ISSUE TITLE
Cannot archive on iOS Xcode 14.3 - libarclite_iphoneos.a - AWSCore.framework" failed: No such file or directory

### ISSUE THREAD

**Issue by MarlonJD** [aws-amplify/amplify-flutter#2818]
### Description

On Xcode 14.3 There is an archive issue and it seems it's related to cocoapods.

without any touch, it gives this error after `pod install`:

```
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

after change podfile error will be changing to this:

```
mkdir -p /Users/marlonjd/Library/Developer/Xcode/DerivedData/Runner-cqvolenavdclupfhrmidthyfhwlm/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Runner.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSCore.framework" "/Users/marlonjd/Library/Developer/Xcode/DerivedData/Runner-cqvolenavdclupfhrmidthyfhwlm/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks"
building file list ... rsync: link_stat "/Users/marlonjd/dev/mobile/projectHelsinki/packages/helsinkimobile/ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSCore.framework" failed: No such file or directory (2)
done
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. pod install --repo-update
2. error

1. Change podfile
2. error

### Platforms

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.9

### Amplify Flutter Version

1.0.0-next.7

### Deployment Method

Amplify CLI

**Comment by MarlonJD** [comment]
We found a fix, thanks to @Jordan-Nelson 

Go to iod/Podfile:

Add this lines between to `post_install do |installer|` and `end`

```
installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
```

it should looks like this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
```

then run `cd ios` and `pod install --repo-update`. And go to `ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh` then 

Find
```
source="$(readlink "${source}")"
```

and replace to:

```
source="$(readlink -f "${source}")"
```

now you can archive. Everytime you run pod install you have to change `Pods-Runner-frameworks.sh` file

**Comment by Jordan-Nelson** [comment]
The need to update frameworks.sh will be resolved when https://github.com/CocoaPods/CocoaPods/pull/11828 is released. I am not sure if the update to the podfile is related to this specific issue or not as I haven't actually reproduced this myself.

Are you seeing the same error when attempting to archive without that?

**Comment by Jordan-Nelson** [comment]
Okay. Once the new version of cocoapods is released we can confirm that addresses the issue without workarounds.

**Comment by dnys1** [comment]
Flutter 3.3.10 has included a fix for this: https://github.com/flutter/flutter/issues/123890#issuecomment-1498164468

Cocoapods 1.12.1 will also include a fix, but is yet to be released.

Closing for now as I am no longer able to recreate the issue. Please let us know if you continue to face this.
