### ISSUE TITLE
Auth.fetchAuthSession - JWT Tokens not refreshed for email_verified claim

### ISSUE THREAD

**Issue by jazzdragon** [aws-amplify/amplify-flutter#2835]
### Description

After our users sign up and verify their email, we need to refresh the access token JWT so that it contains `email_verified: true` (this is something our backend verifies).

I tried calling `_session = await Amplify.Auth.fetchAuthSession();` but it produces the same (non verified) tokens.
Trying to call `_session = await Amplify.Auth.fetchAuthSession(options: const FetchAuthSessionOptions(forceRefresh: true));` produces a `SessionExpiredException` although the user just signed in. 

I've seen a [similar issue](https://github.com/aws-amplify/amplify-flutter/issues/2808) here but we don't use a client secret in our configuration, yet we still face the error.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Use the Auth package to sign up a new user
2. go through email verification
3. try to get a new JWT token

### Platforms

- [X] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

^1.0.0-next.7

### Deployment Method

Custom Pipeline

**Comment by fjnoyp** [comment]
Hi @jazzdragon thanks for posting this issue. 

Can you clarify where in the code you trigger calls to: 

_session = await Amplify.Auth.fetchAuthSession();
_session = await Amplify.Auth.fetchAuthSession(options: const FetchAuthSessionOptions(forceRefresh: true));z

I tried calling _session = await Amplify.Auth.fetchAuthSession(); but it produces the same (non verified) tokens.
Trying to call _session = await Amplify.Auth.fetchAuthSession(options: const FetchAuthSessionOptions(forceRefresh: true)); produces a SessionExpiredException although the user just signed in.

**Comment by jazzdragon** [comment]
Hi @fjnoyp, thanks for the quick response. I tried adding the listen code, but unfortunately the event doesn't contain the tokens. Furthermore, there is no event firing for email verification, only logging in / out.

**Comment by fjnoyp** [comment]
Hi @jazzdragon, 

One thing to note - for now, sign up does not automatically sign in the user.  It's a feature gap we are aware of and looking to prioritize.  Can you verify that sign in was called? 

For getting the tokens => 
Apologies - you'll want to try calling `fetchAuthSession` after the `signedIn` hubEvent as you know you'll be getting the auth info of the current signed in user.  Here is the code to do that: 

```
Amplify.Hub.listen(HubChannel.Auth, (event) async {
        if (event.type == AuthHubEventType.signedIn) {
          final session = await Amplify.Auth.fetchAuthSession();
          _logger.info('session: $session');
        }
      });
```

Please let me know if calling sign in and listening to hub allows you to get the token.

**Comment by jazzdragon** [comment]
- Yes, we are signing the user in
- No, the tokens are not present on the session object returned from `fetchAuthSession`.

Thanks!

**Comment by fjnoyp** [comment]
Okay, can you clarify what you mean by verifying the email on your backend? 

Amplify Auth includes email verification capabilities - it sounds like you're not using that and instead have a custom setup here?  Can you explain what you guys did so I can reproduce?

**Comment by jazzdragon** [comment]
Sure:
- We are confirming the user as soon as soon as they sign up. This is done so we can immediately sign them in without caching their credentials.
- We then sign them in.
- We trigger a validation email with otp for them to enter into the application.
- We then call `verifyEmail` on cognito.

When we call our backend API, we check if `email_verified` is true on the JWT in the header, and only provide access if it is.

**Comment by fjnoyp** [comment]
Hi @jazzdragon 

Can you give more details on what you're doing such as which methods in Auth you are calling?

1) Can you share your amplify configuration (with sensitive values removed) as that will help me know what your auth setup is. 

2) Can you provide the code that you are calling for this workflow?

For example, you mention you immediately confirm the user, do you call `confirmSignUp` and with what `confirmationCode`? 

How do you trigger a validation email?  

Unsure what you mean by `verifyEmail` in Cognito?  Did you mean that you are calling `Auth.confirmUserAttribute`?

**Comment by jazzdragon** [comment]
Yep seems to work fine with `1.0.0`. Thanks!
