### ISSUE TITLE
Datastore - Automatically restarting Online Sync on device offline/online  

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#2838]
### Description

I was building a Todo app using AWS Amplify, where users can add data offline and it should sync automatically when the internet resumes. However, I noticed that the sync does not happen automatically in my app, and I need to manually trigger it to start syncing.

config method :

 void _configureAmplify() async {
    try {
      await Future.wait([
        Amplify.addPlugin(
            AmplifyDataStore(modelProvider: ModelProvider.instance)),
        Amplify.addPlugin(AmplifyAPI()),
        Amplify.addPlugin(AmplifyAuthCognito())
      ]);
      await Amplify.configure(amplifyconfig);
    } catch (e) {
      print(e);
    }
  }

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

I was building a todo app using AWS Amplify, where users can add data online and it should sync automatically when the internet resumes. However, I noticed that the sync does not happen automatically in my app, and I need to manually trigger it to start syncing.

1. Turn off internet
2. Add todo item in offline mode
3. Turn on internet it wont sync automatically
4. Add new todo item in online mode 
5. got both todo item added in offline and online synced

### Screenshots

![image](https://user-images.githubusercontent.com/34904782/231060517-0a513054-5a2f-421a-94a2-56296ba35d45.png)
![image](https://user-images.githubusercontent.com/34904782/231060554-5ca9ab0a-5708-4300-b323-cf6c957d0461.png)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

### Schema

type Todo @model @auth(rules: [{allow: public}]) {
  id: ID!
  task: String
}

**Comment by sharadgoregore** [comment]
i am facing same issue

**Comment by fjnoyp** [comment]
Hi @sharadgoregore could you please give more details on what you are trying to do?  

Datastore is built offline first.  This means any model saves are done locally before being synced to the cloud. 

The issue here is that online sync does not automatically restart if the device went offline.  Instead, you must call Datastore.save or query to get online sync to start again after the device went offline.  Does this match your problem?

**Comment by fjnoyp** [comment]
Hi @sharadgoregore any updates here?

**Comment by sharadgoregore** [comment]
void _configureAmplify() async {
try {
await Future.wait([
Amplify.addPlugin(
AmplifyDataStore(modelProvider: ModelProvider.instance)),
Amplify.addPlugin(AmplifyAPI()),
Amplify.addPlugin(AmplifyAuthCognito())
]);
await Amplify.configure(amplifyconfig);
} catch (e) {
print(e);
}
}


I have done same steps what arul done..but not able to solve yet

**Comment by HuiSF** [comment]
Hi all, we've released Amplify Flutter [v1.0.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0). This version integrates amplify-android v2, and amplify-swift 1.29.2. Both native libraries now integrate reachability observer and automatically restart DataStore sync engine when device gets back online. We encourage to upgrade to v1 to obtain this feature, please try it out :)

**Comment by Aruljebaraj** [comment]
![image](https://user-images.githubusercontent.com/34904782/232963609-b441961d-5694-4922-b5d6-b0a1bd017cd1.png)
wasn't able to test it due to library conflicts

**Comment by HuiSF** [comment]
Hi @Aruljebaraj if you were trying to upgrade to v1, please ensure use all v1 packages.
Details please refer to https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter/#install-amplify-libraries

**Comment by cwomack** [comment]
@Aruljebaraj, we will close this issue for now as this should be fixed with the recent release of v1 for Flutter.  If you're still experiencing these problems, please let us know and we can reopen the issue.  Thanks!
