### ISSUE TITLE
Amplify.Auth.signInWithWebUI can not use custom AuthProvider

### ISSUE THREAD

**Issue by jat1168** [aws-amplify/amplify-flutter#2844]
### Description

When use custom AuthProvider, will throw Exception

```
AuthProvider provider = AuthProvider.custom("Line");
SignInResult result = await Amplify.Auth.signInWithWebUI(
          provider: provider, options: CognitoSignInWithWebUIOptions(isPreferPrivateSession: false));
```

```
I/flutter (20760): │ AuthException(message: An unknown exception has happened. Please take a look at
I/flutter (20760): │ https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
I/flutter (20760): │ match your scenario, and file an issue with the details of the bug if there isn't., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: InvalidRequestException{message=SignInWithWebUI Request malformed., cause=null, recoverySuggestion=You have passed an AuthProvider that is not supported.})
```

I found the source code to check against the auth provider
FlutterSignInWithWebUIRequest.kt: 36 

```
data class FlutterSignInWithWebUIRequest(val map: HashMap<String, *>) {
    private val stringProvider = map["authProvider"] as String?
    val provider: AuthProvider? = when (stringProvider) {
        "amazon" -> AuthProvider.amazon()
        "facebook" -> AuthProvider.facebook()
        "google" -> AuthProvider.google()
        "apple" -> AuthProvider.apple()
        is String -> AuthProvider.custom(stringProvider)
        else -> null
    }

    companion object {
        private var allowedProviders: Array<String> = arrayOf("amazon", "google", "facebook", "apple")
        private const val validationErrorMessage: String = "SignInWithWebUI Request malformed."

        fun validate(req: HashMap<String, *>?) {
            val provider: String? = req?.get("authProvider") as String?
            if (provider != null) {
                if (!allowedProviders.contains(provider)) {
                    throw InvalidRequestException(validationErrorMessage, "You have passed an AuthProvider that is not supported.")
                }
            }
        }
    }
}
```

Why not support custom auth provider?

My aws cognito host UI as screenshot

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Screenshots

![screenshot 2023-04-12 101845](https://user-images.githubusercontent.com/1092021/231331057-2b762d3b-ac50-45f0-9252-78513b2b2d45.png)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.1

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
This issue is resolved in our developer preview version of the libraries. You can get this version by setting the following constraints in your pubspec:

```yaml
dependencies:
  amplify_auth_cognito: ^1.0.0-0
  amplify_flutter: ^1.0.0-0
```

While it is not technically production ready yet, we are aiming to replace the current stable version with it shortly.

**Comment by dnys1** [comment]
Support for this was added in v1.0.0 of Amplify Flutter, which is now stable. You can now safely update your dependencies to the following:

```yaml
dependencies:
  amplify_auth_cognito: ^1.0.0
  amplify_flutter: ^1.0.0
```

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
