### ISSUE TITLE
DataStore execption can see local data though not syncing

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#2881]
### Description

Tried a store data using 
final item = ApplicationList(response: data);
          await Amplify.DataStore.save(item);

Note : earlier  it was working that i tried to add Storage and Auth then got this issue

getting error stating :

I/amplify:aws-datastore(14970): Successfully sync'd down model state from cloud.
W/amplify:aws-datastore(14970): Initial cloud sync failed for ApplicationList.
W/amplify:aws-datastore(14970): DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Transformation too large', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncApplicationLists'}]', extensions='{errorInfo=null, data=null, errorType=MappingTemplate}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
W/amplify:aws-datastore(14970): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
W/amplify:aws-datastore(14970): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
W/amplify:aws-datastore(14970): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:152)
W/amplify:aws-datastore(14970): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
W/amplify:aws-datastore(14970): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/amplify:aws-datastore(14970): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/amplify:aws-datastore(14970): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore(14970): DataStoreException{message=Initial cloud sync failed for ApplicationList., cause=DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Transformation too large', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncApplicationLists'}]', extensions='{errorInfo=null, data=null, errorType=MappingTemplate}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}
E/amplify:aws-datastore(14970): Failure encountered while attempting to start API sync.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [X] Storage

### Screenshots

![image](https://user-images.githubusercontent.com/34904782/232409469-94c99c79-2760-4b53-9b84-35427e917b2f.png)

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type ApplicationDetails @model @auth(rules: [{allow: public}]) {
  id: ID!
  response: String
}

type ApplicationList @model @auth(rules: [{allow: public}]) {
  id: ID!
  response: String
}
```

**Comment by HuiSF** [comment]
Hi @Aruljebaraj thanks for opening this issue. Looking this exception, it's normal when a GraphQL mutation attempts to process data that's larger than [AppSync's limits](https://docs.aws.amazon.com/general/latest/gr/appsync.html).

Could you inspect how much data `response: data` contains? You may need to optimize the strategy how you store data with a model. Similar issue and detailed discussion see [here](https://github.com/aws-amplify/amplify-cli/issues/9589).

**Comment by Aruljebaraj** [comment]
Hey @HuiSF getting another issue i was trying to add data in offlineMode closed the app and opened it again
getting this :
datastore(29687): Successfully cleared the store
and data is not getting synced

**Comment by HuiSF** [comment]
Closing this issue as we haven't heard back from you.
Please reach out again if you need any further assistance.
