### ISSUE TITLE
Merge Microsofts accounts in PreSignUp results in "Invalid ProviderName / Username combination. Please check again &error=invalid_request

### ISSUE THREAD

**Issue by soplan** [aws-amplify/amplify-flutter#2884]
### Description

Trying to link social accounts in cognito. 
Used this article and added 'microsoft' 
https://bobbyhadz.com/blog/aws-cognito-link-user-accounts

Google works fine, however Microsoft sign-ups (personal microsoft account) result in 
Invalid+ProviderName%2FUsername+combination.+Please+check+again+&state=VFzY5FTCDuUhmh1cbMvkSxEyp2Wbanbz&error=invalid_request

Removing 'Microsoft' / Disabling linking for Microsoft accounts allows users to sign in/sign up. It's only happening when we try to merge them

We have Microsoft configured as OIDC

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Custom Pipeline

**Comment by dnys1** [comment]
Hi @soplan, I tried reproducing this and was not able. `Invalid Provider Name/Username combo` would suggest to me that the provider name could be incorrect. This must exactly match how it's configured in your Cognito User Pool. For example, I used AWS CDK to configure an Azure AD OIDC provider like this:

```ts
const microsoftCredentials = Secret.fromSecretNameV2(
  this,
  'MicrosoftCredentials',
  'hosted-ui-merge/microsoft',
);

const microsoftProvider = new UserPoolIdentityProviderOidc(
  this,
  'MicrosoftProvider',
  {
    userPool,
    name: 'Microsoft',
    issuerUrl: microsoftCredentials.secretValueFromJson('issuerUrl').toString(),
    attributeMapping: {
      email: ProviderAttribute.other('email'),
      preferredUsername: ProviderAttribute.other('preferred_username'),
    },
    clientId: microsoftCredentials.secretValueFromJson('clientId').toString(),
    clientSecret: microsoftCredentials.secretValueFromJson('clientSecret').toString(),
    scopes: ['profile', 'email', 'openid'],
  },
);
``` 

Note the `name` property is set to `Microsoft`. In the Cognito console, this is reflected in the **Sign-In Experience** tab under **Federated identity provider sign-in** panel. For example:
<img width="897" alt="Screenshot 2023-04-26 at 10 48 30 AM" src="https://user-images.githubusercontent.com/24740863/234660750-0deb23b2-34b6-47f1-97f1-ce7f71ae007c.png">

Once I have a native Cognito user created via username/password sign up, I call `signInWithWebUI` again referencing that Microsoft name:

```dart
Future<void> _signInWithMicrosoft() async {
  final result = await Amplify.Auth.signInWithWebUI(
    provider: const AuthProvider.oidc('Microsoft',  '<my issuer URL>'),
  );
  safePrint('Sign-in result: $result');
}
```

I've created a gist for my CDK project and pre-sign up trigger code if it helps: https://gist.github.com/dnys1/a4ecd81d3415538c4e0f009fbc88052a

**Comment by dnys1** [comment]
Closing for now. Please let me know if you continue to experience issues.
