### ISSUE TITLE
"UserProfile" GQL model in generated Dart collides with the Analytics class of the same name in v.1

### ISSUE THREAD

**Issue by vgribok** [aws-amplify/amplify-flutter#2889]
### Description

My GQL model has a **"UserProfile" model type**. That was not a problem in the v.0 and v.1 dev preview libraries up until and including "next.6", but the v.1 GA has the "package:amplify_core/src/types/analytics/analytics/user_profile.dart" that is included by the generated model Dart classes, effectively preventing the app from getting compiled and requiring a deconflicting by renaming the "UserProfile" model, unless generated models find a way to not reference the Analytics' "UserProfile" class without an alias.

A compilation error in the generated ModelProvider.dart:
> The name 'UserProfile' is defined in the libraries 'package:amplify_core/src/types/analytics/analytics/user_profile.dart' and 'package:project_name/models/UserProfile.dart'.

"UserProfile" is probably a common-enough name of a model to justify fixing it on the Amplify side.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create a GraphQL schema with the 'UserProfile' model.
2. Run 'amplify codegen model' command in project's root.
3. Observe compilation error.

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.17

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type UserProfile @model
@auth(rules: [
    { allow: groups, groups: ["Admins"] }
    { allow: owner, ownerField: "id" }
])
{
    id: String! @primaryKey
    firstName: String
    lastName: String!
    profilePictures: [CloudFile!]
    preferredPictureIndex: Int
    baseLineSelfie: CloudFile
}
```

**Comment by HuiSF** [comment]
Thanks for opening the issue @vgribok I encountered the same problem while testing something else. The `UserProfile` is a newly added type refactoring Analytics support.

Here's a quick manual workaround 

```diff
-import 'package:amplify_core/amplify_core.dart';
+import 'package:amplify_core/amplify_core.dart' hide UserProfile;
```

I think we'd need to update the codegen using `import as` to avoid naming collision.

**Comment by vgribok** [comment]
The work-around works. Thanks, @HuiSF.
