### ISSUE TITLE
DataStore GraphQL Type with Array Fails to Save

### ISSUE THREAD

**Issue by raywhiteside** [aws-amplify/amplify-flutter#289]
**Describe the bug**
When saving a model with an array element Datastore throws an uncaught exception.

Error:
```
I/amplify:aws-datastore( 1302): Orchestrator lock acquired.
I/amplify:aws-datastore( 1302): Orchestrator lock released.
E/amplify:flutter:datastore( 1302): Save operation failed
E/amplify:flutter:datastore( 1302): DataStoreException{message=, cause=null, recoverySuggestion=}
E/amplify:flutter:datastore( 1302): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindValueToStatement(SQLiteStorageAdapter.java:719)
E/amplify:flutter:datastore( 1302): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:688)
E/amplify:flutter:datastore( 1302): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:744)
E/amplify:flutter:datastore( 1302): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:311)
E/amplify:flutter:datastore( 1302): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/amplify:flutter:datastore( 1302): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore( 1302): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore( 1302): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore( 1302): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore( 1302): 	at java.lang.Thread.run(Thread.java:919)
E/flutter ( 1302): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Instance of 'DataStoreError'
E/flutter ( 1302): #0      AmplifyDataStoreMethodChannel.save (package:amplify_datastore/method_channel_datastore.dart:103:7)
E/flutter ( 1302): <asynchronous suspension>
E/flutter ( 1302): #1      AmplifyDataStore.save (package:amplify_datastore/amplify_datastore.dart:72:22)
E/flutter ( 1302): #2      DataStoreCategory.save (package:amplify_core_plugin_interface/amplify_datastore_category.dart:56:45)
// my part of the stack starts here
E/flutter ( 1302): #3      ClientDataController._updateTasks.<anonymous closure> (package:bbp_todo/client_data/ClientDataController.dart:219:33)
...

```

**To Reproduce**

Example model:
```
type UserModel @model {
  tags: [String]
}
```

The same model without the array works, as soon as I add the array it fails. When changing to an array clearly I could be making a mistake in instantiating the UserModel generated class, but the issue is not in the data being incorrect. DataStore is failing to save an instance of a generated model, which I think takes the blame off me. User issues should be surfaced when creating/interacting with the generated model, and all interactions between the generated model and DataStore should be insulated from my stupidity. 

This is the generated toJson() code:

```
  Map<String, dynamic> toJson() => {
        'tags': tags
      };
```
This code isn't different compared to when it's not an array. I think just `tags` is insufficient when this variable is now of type `List<String>`.

**Expected behavior**

1. DataStore needs to support models containing arrays
2. The exception should be passed up to Amplify.DataStore.save so I can catch it more cleanly in my logic, even if I can't do much about it. I might be wrong on this point but that's my gut reaction. :)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Comment by jamesonwilliams** [comment]
Thanks for the report @raywhiteside. You've marked Android, but _not_ iOS. Is that because you tested iOS and it works? Or because you only tested Android?

**Comment by raywhiteside** [comment]
Only tested on Android.

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822
