### ISSUE TITLE
GraphQL subscription stream closes when android device goes offline and does not comes back automatically

### ISSUE THREAD

**Issue by raphire08** [aws-amplify/amplify-flutter#2897]
### Description

When android device becomes offline and is put to background after 2 or 3 mins the following error comes up in console

```
ERROR | WebSocketBloc | Shutting down with exception: AmplifyException {
I/flutter (28115):   "message": "Unable to recover network connection, web socket will close.",
I/flutter (28115):   "recoverySuggestion": "Check internet connection.",
I/flutter (28115):   "underlyingException": "GET https://tocqjdo5cvamda66o35niuhw7m.appsync-api.us-west-2.amazonaws.com/ping failed: SocketException: Failed host lookup: 'tocqjdo5cvamda66o35niuhw7m.appsync-api.us-west-2.amazonaws.com' (OS Error: No address associated with hostname, errno = 7)"
I/flutter (28115): }


```

Shortly afterwards graph QL subscription closes and sends a done event. On coming back online and bringing the application to foreground the subscription is no longer sending events on data.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

mentioned in description

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.9

### Amplify Flutter Version

1.0.0

### Deployment Method

Custom Pipeline

**Comment by Equartey** [comment]
The observed behavior is currently expected. Connection is not automatically recovered when an app enters the foreground from the background.

However, the API plugin attempts to recover subscriptions when the underlying connection gets interrupted (eg. wifi/cellular), through 8 attempts with an exponential back off. With a default duration of about 60 seconds. 

Duration can be customized through `GraphQLSubscriptionOptions`, specifically the parameter `retryOptions`, when configuring the api plugin. If all attempts failed (e.g. the network connection had not recovered during this period of time), the subscription will be closed.

```
/// Custom Subscription Options Example
await Amplify.addPlugins([
    authPlugin,
    AmplifyAPI(subscriptionOptions: GraphQLSubscriptionOptions(retryOptions: RetryOptions(...),)),
]);
```

Developers are expected to listen to the API hub events; When a ` SubscriptionHubEvent.disconnected` occurs developers need to invoke API.subscribe again to recreate subscriptions.

```
/// Hub Event Listener Example
Amplify.Hub.listen(
    HubChannel.Api,
    (ApiHubEvent event) {
        if (event is SubscriptionHubEvent) {
            safePrint(event);
        }
    },
);
```

**Comment by Equartey** [comment]
Closing this issue as it has been captured in the [docs page](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/flutter/#automated-reconnection).
