### ISSUE TITLE
Datastore query returns empty list on first app launch

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#2904]
### Description

DataStore returns an empty list every time a Flutter app is newly installed (first launch).
I am aware that this is because DataStore is not yet ready but I suggest to make the query operation wait internally since it will always return an empty list on the first launch or when the user log out and then clearing DataStore.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Make a fresh new install of the Flutter application or clear DataStore on log out and log back in.
2. Use Amplify.query in the first page after authentication.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hi @jamilsaadeh97 - The `observeQuery()` API might work for your use case. `observeQuery()`will return snapshots during the initial sync. Each snapshot has an `isSynced` boolean that will be true if the model type has completed syncing to the device. You can ignore updates until `isSynced` is true if you only want to get the data after the sync has completed.

```dart
final QuerySnapshot<Blog> snapshot = await Amplify.DataStore.observeQuery(
  Blog.classType,
).firstWhere((snapshot) => snapshot.isSynced);

final List<Blog> data = snapshot.items;
```

**Comment by jamilsaadeh97** [comment]
Hi @Jordan-Nelson thank you for your answer.
In my use case, the model I'm querying can be updated and modified by all users in my application (in my case, by changing a date and/or adding to a list)
So this means if I use observeQuery, the widgets will be rebuilt every time any user update the model item.

**Comment by Jordan-Nelson** [comment]
While observeQuery returns a stream, you can use it to retrieve a single result and then unsubscribe. This is what .firstWhere() is doing in the example above. .firstWhere() converts the stream into a future. The future will be the first item from the stream that matches the condition.

The code example above would be the same result as if query() waited until the data was ready to return a result.

**Comment by jamilsaadeh97** [comment]
Oh okay I didn't notice that firstWhere will unsubscribe after.
That's really good to know thank you @Jordan-Nelson

**Comment by agent515** [comment]
Hey @Jordan-Nelson . I'm receiving empty `snapshot.items` even after receiving the first `isSynced: true`. The list of items gets filled after a bit of delay.

```dart
final QuerySnapshot<User> snapshot = await Amplify.DataStore.observeQuery(
  User.classType,
).firstWhere((snapshot) => snapshot.isSynced);

```

**Comment by Jordan-Nelson** [comment]
@agent515 - Can you open a new issue with the reproduction steps?
