### ISSUE TITLE
Auth - how do I check if MFA is enabled?

### ISSUE THREAD

**Issue by jazzdragon** [aws-amplify/amplify-flutter#2908]
### Description

There seems to be no way to query the API to check if MFA is turned on for a user. This is useful for presenting the state of MFA in app settings.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

1.0.0

### Deployment Method

Custom Pipeline

**Comment by dnys1** [comment]
Hi @jazzdragon, at the moment we do not provide an API for this. I've marked this as a feature request and will discuss this with the team.

**Comment by dnys1** [comment]
This will be provided as part of the upcoming TOTP MFA support (https://github.com/aws-amplify/amplify-flutter/pull/3146).

**Comment by dnys1** [comment]
I'm very pleased to announce this feature has been released alongside TOTP support in v1.4.0 🚀

Please see [the docs](https://docs.amplify.aws/lib/auth/mfa/q/platform/flutter/#setting-a-users-preferred-mfa-option) to learn about the new `fetchMfaPreference` and `updateMfaPreference` APIs.
