### ISSUE TITLE
Google authentication : User's email not returning 

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#2916]
### Description

<img width="1092" alt="Screenshot 2023-04-21 at 3 49 43 PM" src="https://user-images.githubusercontent.com/53246428/233612218-db7079a7-c8a2-4a5d-b61b-ae1db75a1141.png">
<img width="1143" alt="233612336-cd753a7a-e89d-4b37-965e-7518391a39d6" src="https://user-images.githubusercontent.com/53246428/233613491-d449569f-9ea7-4c91-8513-13d4e6830425.png">

Hi, 
I am not able to receive google user email  n AWS amplify google  authentication. I also mapped the google attribute with cognito attribute. If I setup email as signup attribute in cognito than email is getting in google sign in. but in my case I can't set email attribute is required in signup. 
Please take a look on it.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
I wonder if this has something to do with also allowing email as a login alias. I will try to reproduce/find some more info.

**Comment by dnys1** [comment]
I have tried reproducing this but was not successful. Creating a user pool with email/phone number alias, the `email` attribute set to optional, and sign-in with Google included `email` and `email_verified` on the created users.

Can you confirm that the OAuth scopes are set up correct? There are two places to verify.
1. From the user pool console, click on the **Sign-in experience** tab, then on the Google provider in the **Federated identity provider sign-in** panel.

The values listed in **Authorized scopes** should be `profile email openid` in no particular order.

2. From the user pool console, click on the **App integration** tab, followed by the app client in the **App clients and analytics** panel. Note: This is the one whose name does **not** end in `web`.

The values listed in **OpenID Connect scopes** should be 

```
aws.cognito.signin.user.admin
email
openid
phone
profile
```

Again, in no particular order.

---

Another question, do you have any Lambda triggers in your user pool which might interfere with this?

**Comment by dnys1** [comment]
Closing for now since we haven't heard from you. Please let me know if you continue facing this issue.

**Comment by deejoe79** [comment]
I had the same issue with Google. 
In my case the issue was that email was not set between the scopes for google.

1. Go to Cognito
2. Select user pool
3. Under 'Federated identity provider sign-in' click Google
4. Click edit for section: Identity provider information
5. Add email to the scopes

Like this:
![image](https://github.com/aws-amplify/amplify-flutter/assets/34540450/2305c3fb-ff2e-41af-a332-6c8aa0fded17)
