### ISSUE TITLE
[API] TimeoutException after 0:05:00.000000: Web Socket Connection Timeout

### ISSUE THREAD

**Issue by xonaman** [aws-amplify/amplify-flutter#2918]
### Description

In my ```schema.graphql``` I have the following model:
```graphql 
type UserProfile @model {
  id: ID!
  firstName: String
  lastName: String
}
```
I listen to ```onUpdate``` events using the Flutter Plugin:
```dart
Amplify.Hub.listen(HubChannel.Api, (ApiHubEvent event) {
  print('${event.eventName}: ${event.payload}');
});

final Stream<GraphQLResponse<String>> stream = Amplify.API.subscribe(
  GraphQLRequest<String>(
    document: '''subscription {
      onUpdateUserProfile {
        id
        firstName
        lastName
      } 
    }''',
  ),
);
stream.listen((GraphQLResponse<String> response) {
  print(response.data);
});
```
At this point, everything works as expected. But after some time, 5-10 minutes or so, I get the following exception: ```ERROR | WebSocketBloc | Shutting down with exception: TimeoutException after 0:05:00.000000: Web Socket```. I believe this error to be from the Amplify API, because I looked into the code and saw a class named ```WebSocketBloc```. 

After this error, I get no more ```onUpdate``` events, even after creating the stream again and disposing the old one.

This is my output, including the ```ApiHubEvent``` event outputs:
```
flutter: ERROR | WebSocketBloc | Shutting down with exception: TimeoutException after 0:05:00.000000: Web Socket Connection Timeout
flutter: SubscriptionHubEvent: SubscriptionDetails {
  "networkState": "failed",
  "intendedState": "disconnected"
}
flutter: SubscriptionHubEvent: SubscriptionDetails {
  "networkState": "connected",
  "intendedState": "disconnected"
}
flutter: SubscriptionHubEvent: SubscriptionDetails {
  "networkState": "disconnected",
  "intendedState": "disconnected"
}
```
It seems to me that the server terminated the connection after a certain amount of time, so we need to re-establish it. How can this be done please?

Many thanks in advance!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

please see description above 

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

1.0.0-next.7

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hi @xonaman thank you for opening this issue. 

When you encountered this error, is your App still active in the foreground, or you put the App into background for a while and reopened it? 

The disconnection is expected to happen when the App entered background where the underlying websocket connection is not able to stay alive. Here's an issue and discussion about this: https://github.com/aws-amplify/amplify-flutter/issues/2897

**Comment by xonaman** [comment]
So, if I understand this right, I will try the following and see if the error occurs again:

```dart
if (!Amplify.isConfigured) {
  await Amplify.addPlugins(<AmplifyPluginInterface>[
    AmplifyAuthCognito(),
    AmplifyStorageS3(),
    AmplifyAPI(
      modelProvider: ModelProvider.instance,
      subscriptionOptions: GraphQLSubscriptionOptions(
        retryOptions: RetryOptions(
          delayFactor: const Duration(milliseconds: 300),
          maxAttempts: double.maxFinite.toInt(),
        ),
      ),
    ),
  ]);
  await Amplify.configure(amplifyconfig);
}
```

Is it a good practice to use `double.maxFinite.toInt()` here? I want to have "infinite" attempts, so that the connection never dies. 

(I am also calling `API.subscribe()` again after receiving the `NetworkState.failed` event, as described in the issue you mentioned.)

**Comment by HuiSF** [comment]
> I want to have "infinite" attempts, so that the connection never dies.

I don't think this is the best practice. For example, if the device is offline for any reason, you probably don't want to waste resources by keeping retrying when we know it will never be able to reconnect while the network is disconnected.

Listening to the hub event and reacting should be able to cover the use case when the subscription was disconnected due to the app entering the background. We will keep investigating the possibility of extending the current solution to make self-recovery from disconnection cover most of the use cases.

**Comment by xonaman** [comment]
Okay, thanks! I will remove the `RetryOptions` then and only keep the second part of my code I pasted here.
