### ISSUE TITLE
Amplify Authenticator UI  Full Customization Issue

### ISSUE THREAD

**Issue by nesimventures** [aws-amplify/amplify-flutter#2920]
### Description

I'm following the full UI customization example -> (https://ui.docs.amplify.aws/flutter/connected-components/authenticator/customization#full-ui-customization) however it won't allow me to change the theming of the  SignInForm() and SignInButton(). The other example on the documentation for changing the theme is to change it within the MaterialApp() widget however when I use authenticationBuilder the theme won't work anymore. Hopefully, this bugs getts addressed soon and offer more UI customization. :)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Mentioned in the description

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by nesimventures** [comment]
That part is working now. However why are we restricted to MaterialApp because when I change it to CupertinoApp it won't work anymore.

**Comment by Jordan-Nelson** [comment]
The Flutter Authenticator is built with Material widgets. We do not offer a version built with Cupertino widgets (if you have a use case for this, let me know and we can discuss making this a feature request). Material widgets inherit the `ThemeData` from the MaterialApp. If you do not use a MaterialApp, there will be no `ThemeData` to inherit. CupertinoApps have a Cupertino specific theme called `CupertinoThemeData`. Material Widgets will not inherit this theme.

If you want to use a CupertioApp and set the theme for the Authenticator widgets, you can wrap the widgets in a `Theme()` widget.

In the example below, CustomScaffold's build method returns a widget wrapped in a Theme widget. The widgets in the Authenticator will inherit this.

```dart
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  void _configureAmplify() async {
    try {
      await Amplify.addPlugin(AmplifyAuthCognito());
      await Amplify.configure(amplifyconfig);
      safePrint('Successfully configured');
    } on Exception catch (e) {
      safePrint('Error configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Authenticator(
      // `authenticatorBuilder` is used to customize the UI for one or more steps
      authenticatorBuilder: (BuildContext context, AuthenticatorState state) {
        switch (state.currentStep) {
          case AuthenticatorStep.signIn:
            return CustomScaffold(
              state: state,
              // A prebuilt Sign In form from amplify_authenticator
              body: SignInForm(),
              // A custom footer with a button to take the user to sign up
              footer: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Text('Don\'t have an account?'),
                  TextButton(
                    onPressed: () => state.changeStep(
                      AuthenticatorStep.signUp,
                    ),
                    child: const Text('Sign Up'),
                  ),
                ],
              ),
            );
          case AuthenticatorStep.signUp:
            return CustomScaffold(
              state: state,
              // A prebuilt Sign Up form from amplify_authenticator
              body: SignUpForm(),
              // A custom footer with a button to take the user to sign in
              footer: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Text('Already have an account?'),
                  TextButton(
                    onPressed: () => state.changeStep(
                      AuthenticatorStep.signIn,
                    ),
                    child: const Text('Sign In'),
                  ),
                ],
              ),
            );
          case AuthenticatorStep.confirmSignUp:
            return CustomScaffold(
              state: state,
              // A prebuilt Confirm Sign Up form from amplify_authenticator
              body: ConfirmSignUpForm(),
            );
          case AuthenticatorStep.resetPassword:
            return CustomScaffold(
              state: state,
              // A prebuilt Reset Password form from amplify_authenticator
              body: ResetPasswordForm(),
            );
          case AuthenticatorStep.confirmResetPassword:
            return CustomScaffold(
              state: state,
              // A prebuilt Confirm Reset Password form from amplify_authenticator
              body: const ConfirmResetPasswordForm(),
            );
          default:
            // Returning null defaults to the prebuilt authenticator for all other steps
            return null;
        }
      },
      child: CupertinoApp(
        builder: Authenticator.builder(),
        home: const Scaffold(
          body: Center(
            child: Text('You are logged in!'),
          ),
        ),
      ),
    );
  }
}

/// A widget that displays a logo, a body, and an optional footer.
class CustomScaffold extends StatelessWidget {
  const CustomScaffold({
    super.key,
    required this.state,
    required this.body,
    this.footer,
  });

  final AuthenticatorState state;
  final Widget body;
  final Widget? footer;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: ThemeData.from(
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.red,
          backgroundColor: Colors.white,
        ),
      ).copyWith(
        indicatorColor: Colors.red,
      ),
      child: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(16),
          child: SingleChildScrollView(
            child: Column(
              children: [
                // App logo
                const Padding(
                  padding: EdgeInsets.only(top: 32),
                  child: Center(child: FlutterLogo(size: 100)),
                ),
                Container(
                  constraints: const BoxConstraints(maxWidth: 600),
                  child: body,
                ),
              ],
            ),
          ),
        ),
        persistentFooterButtons: footer != null ? [footer!] : null,
      ),
    );
  }
}
```

**Comment by nesimventures** [comment]
Got you, thanks thats a good workaround. One last question for the pre-built widgets for example the SignInButton() and SignOutButton() widgets are we able to customize its border such as editing the button to have circular borders and etc...

**Comment by nesimventures** [comment]
Thanks, that helps a lot.

**Comment by pixnbit** [comment]
@Jordan-Nelson this is awesome! I don't know what would be a great channel to express how satisfied I'm with of the Amplify Authenticator UI package (a couple of days into trying it out). I was debating between Firebase Auth UI vs Amplify Auth Authenticator. I've used Auth0 in the past in our previous project, it was a PIA to maintain all the auth states, they didn't' even have a native SDK until very recently. 

A natural thought for an alternative would Firebase Auth for Flutter, the in-house Google solution. Wrong at least with Auth UI. I gave Amplify a try and am pleasantly surprised: Authenticator is much more configurable in a Flutter way (everything is a widget, you can swap out with full customization, state management is excellent, as a consumer, I only need to care about subscribing to the Auth state changes) I was jumping through the code I can definitely see how carefully this package is designed. Also your package is actively maintained, compared with Firebase Auth UI (on one thread I read it's in maintenance mode)

(of course Cognito identity pool and AWS stack are a plus for us but that's actually not the deciding factor)

Kudos to the team and keep up with the good work!

**Comment by abdallahshaban557** [comment]
Hi @pixnbit ! Thank you for all the positivity and great feedback!!!!
