### ISSUE TITLE
confirm SignIn With New Password 

### ISSUE THREAD

**Issue by subhankar007b** [aws-amplify/amplify-flutter#2922]
### Description

I'm unable to get which Method I need to call in "confirmSignInWithNewPassword" to complete the signin process in Flutter

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @subhankar007b - You can use `Amplify.Auth.confirmSignIn()` to confirm sign in with a new password. For example:

```dart
await Amplify.Auth.confirmSignIn(confirmationValue: 'newPassword');
```

**Comment by Jordan-Nelson** [comment]
I have marked this as a docs issue since Amplify Flutter does not have the same [documentation as Swift & Kotlin](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/ios/#confirm-signin-with-new-password) for this use case.

**Comment by subhankar007b** [comment]
I'm getting this issue when i used 

await Amplify.Auth.confirmSignIn(confirmationValue: 'newPassword');


ERROR | SignInStateMachine | Emitted error: InvalidParameterException {
I/flutter (15515):   "message": "Invalid attributes given, name is missing",
I/flutter (15515):   "underlyingException": "InvalidParameterException {\n  message=Invalid attributes given, name is missing,\n}"
I/flutter (15515): }
I/flutter (15515): package:smithy/src/http/http_operation.dart 324:7                    HttpOperation.deserializeOutput
I/flutter (15515): package:async/src/cancelable_operation.dart 416:16                   CancelableCompleter.complete.<fn>
I/flutter (15515): ===== asynchronous gap ===========================
I/flutter (15515): package:amplify_core/src/state_machine/event.dart 42:47              new EventCompleter
I/flutter (15515): package:amplify_core/src/state_machine/state_machine.dart 150:23     StateMachineManager.accept
I/flutter (15515): package:amplify_core/src/state_machine/state_machine.dart 162:23     StateMachineManager.acceptAndComplete
I/flutter (15515): package:amplify_auth_cognito_dart/src/auth_plugin_impl.dart 635:40   AmplifyAuthCognitoDart.confirmSignIn
I/flutter (15515): package:amplify_core/src/category/amplify_auth_category.dart 520:21  AuthCategory.confirmSignIn
I/flutter (15515): package:eih_demo/confirm_new_pa
I/flutter (15515): Invalid attributes given, name is missing

**Comment by Jordan-Nelson** [comment]
@subhankar007b - I am going to close this out, but we will open a new issue in our docs repro to track the docs update. Let me know if you have any issues with the API. Thanks.
