### ISSUE TITLE
Model Identifier not being implemented, cannot use ModelQueries.get()

### ISSUE THREAD

**Issue by ryanlalchand** [aws-amplify/amplify-flutter#2929]
### Description

`amplify codegen models` is not generating a modelIdentifier for any models and throws an Unimplemented Error when I try to access that attribute. This means that I cannot use ModelQueries.get() in its current form. 

Using Amplify CLI version 11.0.5 and amplify_flutter 1.0.0 on Flutter 3.7.12.

Any help would be appreciated!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hello @ryanlalchand thank you for reporting this issue.

Your Amplify project might have been created before the launch of Custom Primary Key feature. Could you check what's the value of `respectprimarykeyattributesonconnectionfield` flag in `<path-to-your-flutter-project>/amplify/cli.json`?

If it's `false`, please change it to `true`, and then rerun `amplify codegen models` see if you can get `ModelIdentifier` implementation.
