### ISSUE TITLE
Fatal Exception: FlutterError

### ISSUE THREAD

**Issue by edily-learn** [aws-amplify/amplify-flutter#2930]
### Description

We have noticed some app crashes when users try to open the app. It is hard to recreate but after some investigation we believe that Amplify Auth is returning that the user is signed in but once we attempt to send a REST request its fails authorization.

UnknownException(message: Unexpected error occurred with message: Unable to get valid sign in session from the end user., recoverySuggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/joearlia/edily/edily-mobile/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80, underlyingException: null)

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Screenshots

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/84813526/234156959-4f793857-ecd8-4bd9-8846-64316c1b2e3d.png">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Would you be able to share the code in `auth_service.dart` which is triggering this error? A `FlutterError` may just mean that an async method is being called without a try/catch and so the error goes unhandled.

**Comment by dnys1** [comment]
Given that a REST operation is failing even though the user is signed in, this could be a bug. We recently released v1 of the Amplify Flutter libraries which improves on the v0 bindings to iOS/Android by rewriting fully in Dart. If you're able to upgrade to v1, this should make debugging easier and may resolve underlying issues if there is a bug.

**Comment by edily-learn** [comment]
> Would you be able to share the code in `auth_service.dart` which is triggering this error? A `FlutterError` may just mean that an async method is being called without a try/catch and so the error goes unhandled.

```
  Future<List<AuthUserAttribute>?> fetchUserAttributes() async {
    try {
      List<AuthUserAttribute> res = await Amplify.Auth.fetchUserAttributes();
      return res;
    } on AmplifyException catch (_) {
      rethrow;
    }
  }
```

**Comment by edily-learn** [comment]
> Given that a REST operation is failing even though the user is signed in, this could be a bug. We recently released v1 of the Amplify Flutter libraries which improves on the v0 bindings to iOS/Android by rewriting fully in Dart. If you're able to upgrade to v1, this should make debugging easier and may resolve underlying issues if there is a bug.

Going to give updating a try. We are blocked with a dependency update since we are using `catcher: ^0.7.0`

**Comment by dnys1** [comment]
> We are blocked with a dependency update since we are using catcher: ^0.7.0

You should be able to work around that using dependency overrides:

```yaml
dependency_overrides:
  device_info_plus: ^8.0.0
  device_info_plus_platform_interface: ^7.0.0
```

It seems the `catcher` package needs to be updated. If that doesn't work you can try the version in this PR as well: https://github.com/jhomlala/catcher/pull/234

**Comment by SebastianEngel** [comment]
We had the same error when calling `fetchUserAttributes` on iOS. It seems like the underlying issue is coming from the Amplify iOS SDK. See [https://github.com/aws-amplify/amplify-flutter/issues/2312](https://github.com/aws-amplify/amplify-flutter/issues/2312). 

The Amplify Flutter packages in version 1.0.0 and higher (e.g. [amplify_auth_cognito](https://pub.dev/packages/amplify_auth_cognito/versions/1.0.1/changelog#100)) are written in pure Dart, which means they do not depend on the native SDKs anymore. After upgrading our Amplify Flutter packages we do not seem to have the error anymore.

**Comment by SebastianEngel** [comment]
Just saw that @dnys1 already mentioned the v1.0 update 👍🏻

**Comment by axialjoe** [comment]
@Jordan-Nelson we haven't seen the issue since we upgraded as well. Looks to be working so far! 

Thanks for the quick follow up.

**Comment by edily-learn** [comment]
[@Jordan-Nelson](https://github.com/Jordan-Nelson) we haven't seen the issue since we upgraded as well. Looks to be working so far!

Thanks for the quick follow up.

**Comment by Jordan-Nelson** [comment]
Thanks. I will close this issue then. Let us know if you have any other issues.
