### ISSUE TITLE
Delete saved or add new credentials during runtime

### ISSUE THREAD

**Issue by Smibser** [aws-amplify/amplify-flutter#2932]
### Description

Hello,
I have a question about managing the saved credentials.
We want to let the user decide whether he/she wants to save his/her credentials beyond the app runtime. I achieved not persisting the credentials to the phones file storage by passing an InMemoryStorage (basically that from the [docs](https://docs.amplify.aws/lib/auth/managing_credentials/q/platform/flutter/)) when adding the plugin and configuring amplify. 
But now for example, when a user has saved his/her credentials and decides he/her don't want them to be saved anymore, how can I delete them from the phone storage?
Or when a user didn't save his/her credentials and then wants to save them. I archived that by resetting Amplify and reconfiguring it again with the correct storage and calling `signIn` again. But there I have to call `Amplify.reset()` which is only visible for testing.

Is there a way to manage the saved credentials like deleting or adding them manually during runtime? Or am I misunderstanding managing the credentials completely?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Smibser** [comment]
That makes sense. Thank you for your answer.
But how can I access the storage and `setPersistenceMode` during runtime?

**Comment by dnys1** [comment]
You could use [`provider`](https://pub.dev/packages/provider), for example, to make it available throughout your app.

**Comment by dnys1** [comment]
Please let me know if you face any issues.

**Comment by Smibser** [comment]
Thank you for your help, but the HybridSecureStore is not working as expected.
When I change the persistence mode to true, I write every entry from the inMemStorage in the amplify secure storage. On the next app start it can read the written values from the amplify secure storage but the user is not signed in after the initialization.

<details>
  <summary>HybridSecureStore implementation</summary>

  ```dart
import 'package:amplify_flutter/amplify_flutter.dart';

class HybridSecureStorage implements SecureStorageInterface {
  static const AmplifySecureStorageScope _scope =
      AmplifySecureStorageScope.awsCognitoAuthPlugin;

  HybridSecureStorage(bool persist)
      : _persistentStorage = AmplifySecureStorage.factoryFrom().call(_scope),
        _persist = persist;

  final Map<String, String> _inMemStorage = <String, String>{};
  final AmplifySecureStorage _persistentStorage;

  bool _persist;

  Future<void> setPersistenceMode(bool persist) async {
    _persist = persist;
    if (persist) {
      for (final MapEntry<String, String> entry in _inMemStorage.entries) {
        await _persistentStorage.write(key: entry.key, value: entry.value);
      }
    } else {
      await _persistentStorage.removeAll();
    }
  }

  @override
  Future<void> write({required String key, required String value}) async {
    if (_persist) {
      await _persistentStorage.write(key: key, value: value);
    } else {
      _inMemStorage['${_scope.name}.$key'] = value;
    }
  }

  @override
  Future<String?> read({required String key}) async {
    if (_persist) {
      return _persistentStorage.read(key: key);
    } else {
      return _inMemStorage['${_scope.name}.$key'];
    }
  }

  @override
  Future<void> delete({required String key}) async {
    if (_persist) {
      await _persistentStorage.delete(key: key);
    } else {
      _inMemStorage.remove('${_scope.name}.$key');
    }
  }
}
  ```
</details>

<details>
  <summary>Amplify configure implementation</summary>
  
  ```dart
  Future<void> configureAmplify(HybridSecureStorage storage) async {
    final AmplifyAuthCognito auth = AmplifyAuthCognito(
      secureStorageFactory: (_) => storage,
    );
    await Amplify.addPlugin(auth);

    final AppConfig appConfig = GetIt.instance.get<AppConfig>();
    await Amplify.configure(
      _getAmplifyConfig(
        poolId: appConfig.amplifyCognitoAuthConfig.poolId,
        clientId: appConfig.amplifyCognitoAuthConfig.clientId,
      ),
    );
  }
  ```
</details>
