### ISSUE TITLE
I want to use a model to synchronize some data and selectively overwrite local data

### ISSUE THREAD

**Issue by Leo-tsp** [aws-amplify/amplify-flutter#2936]
I want to implement such a function using Amplify.Datastore,
The front-end will generate data, but it does not need to be synchronized to the cloud. The cloud will also generate data through other methods. There is a field in the model that is globally unique. If the unique values of the data generated locally and in the cloud are the same, the cloud will be the main one and the local data will be overwritten. May I ask if Amplify supports this feature? How to achieve better results

**Comment by HuiSF** [comment]
Hi @Leo-tsp thanks for the question.

From reading your use case, if I understood correctly, you would like to make DataStore sync functionality unidirectional, i.e. it only syncs down data from the cloud, but local operations don't make any mutations to sync local changes to the cloud. DataStore currently doesn't support sync control like this.

One way I can think of to achieve your use case at this moment is to use the Amplify API plugin, with a 3rd party local data storage (e.g. [sqlite](https://docs.flutter.dev/cookbook/persistence/sqlite)), where you can store local data operations (can still use Amplify codegen generated models), you can use [query or list APIs](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/flutter/) of the Amplify API plugin to download data from the cloud to override the local data. In addition, you can use [subscriptions](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/flutter/#setup-subscription-with-callbacks) to receive data updates and override local data in real time when there is a data change in the cloud.
