### ISSUE TITLE
Add compatibility with Android Gradle Plugin 8.0

### ISSUE THREAD

**Issue by asaarnak** [aws-amplify/amplify-flutter#2937]
Add a `namespace` attribute to the Android build.gradle, for compatibility with Android Gradle Plugin 8.0.
See:
https://github.com/flutter/packages/commit/6284c2d4e46a5d289e77cb03a9457543b97f750b

**Comment by dnys1** [comment]
Thanks for the heads up, @asaarnak! We are working on a fix now 👍

**Comment by dnys1** [comment]
This fix has been released in v1.1.0
