### ISSUE TITLE
No instance found for StorageS3Service

### ISSUE THREAD

**Issue by vishwasfoundation** [aws-amplify/amplify-flutter#2939]
### Description

I am trying to get list of all objects from existing bucket but I am always getting this error.

The code i am using is: 
try {
        StorageListResult res = await Amplify.Storage.list(
          options: const StorageListOptions(
            accessLevel: StorageAccessLevel.guest,
            pluginOptions: S3ListPluginOptions.listAll(),
          ),
        ).result;
        print(res);
      } on StorageException catch (e) {
        print("error is -- ${e.message}");
      }

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/131882982/234587591-b5a37fa4-5c08-48ef-b313-f433e736ba9e.png)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @vishwasfoundation, can you share the code you're using for configuring Amplify?

Can you make sure you're importing from `package:amplify_flutter/amplify_flutter.dart` and not from `package:amplify_core/amplify_core.dart` in your initialization code?

**Comment by vishwasfoundation** [comment]
> Hi @vishwasfoundation, can you share the code you're using for configuring Amplify?
> 
> Can you make sure you're importing from `package:amplify_flutter/amplify_flutter.dart` and not from `package:amplify_core/amplify_core.dart` in your initialization code?

Hello @dnys1 , Thanks for reply. Here is the code I am using for Amplify configuration

import 'package:amplify_analytics_pinpoint/amplify_analytics_pinpoint.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';

Future<void> _configureAmplify() async {
    try {
      AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
      AmplifyStorageS3 storagePlugin = AmplifyStorageS3();
      AmplifyAuthCognito plug = AmplifyAuthCognito();
      Amplify.addPlugins([plug,storagePlugin,analyticsPlugin]);
      try {
        await Amplify.configure(amplifyconfig);
      } catch (e) {
        print(
            "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
      }
      } on Exception catch (e) {
      print('Could not configure Amplify: $e');
    }
  }

**Comment by dnys1** [comment]
Thanks! Can you try awaiting the call to `Amplify.addPlugins`?

**Comment by vishwasfoundation** [comment]
Issue is fixed now. I added configuration code to the main.dart rather than any other controller. Thanks for contribution.
