### ISSUE TITLE
After upgrading to version 1.0.0 No builder registered for SecureStorageInterface

### ISSUE THREAD

**Issue by TriaHub** [aws-amplify/amplify-flutter#2944]
### Description

My Amplify configure looks like this:

    Future<void> _configureAmplify() async {
      try {
        final auth = AmplifyAuthCognito(
          secureStorageFactory: AmplifySecureStorage.factoryFrom(
            macOSOptions:
            // ignore: invalid_use_of_visible_for_testing_member
            MacOSSecureStorageOptions(useDataProtection: false),
          ),
        );
        final api = AmplifyAPI(
          authProviders: const [
            CustomFunctionProvider(),
          ],
          modelProvider: ModelProvider.instance,
        );
    
        Amplify.addPlugins([api, auth]);
    
        await Amplify.configure(amplifyconfig);
      } on Exception catch (e) {
        safePrint('An error occurred configuring Amplify: $e');
      }
    }

It was working perfectly fine before the upgrade, I am not sure If I'm missing something

The error output:

  WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.
  ERROR | CredentialStoreStateMachine | Emitted error: Bad state: No builder registered for SecureStorageInterface
  dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49                        throw_
  packages/amplify_core/src/state_machine/dependency_manager.dart 161:7                               create
  packages/amplify_core/src/state_machine/dependency_manager.dart 82:12                               getOrCreate
  packages/amplify_core/src/state_machine/state_machine.dart 131:26                                   getOrCreate
  packages/amplify_core/src/state_machine/state_machine.dart 397:15                                   getOrCreate
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 46:48     get [_secureStorage]
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 84:42     getVersion
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 83:44     getVersion
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 318:27    _migrateLegacyCredentialStore
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 317:45    [_migrateLegacyCredentialStore]
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 359:11    onLoadCredentialStore
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 356:37    onLoadCredentialStore
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 54:15     resolve
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/credential_store_state_machine.dart 49:23     resolve
  packages/amplify_core/src/state_machine/state_machine.dart 255:59                                   <fn>
  dart-sdk/lib/async/future.dart 424:39                                                               <fn>
  dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19                             internalCallback
  ===== asynchronous gap ===========================
  dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 977:28                                  get current
  packages/amplify_core/src/state_machine/event.dart 42:47                                            new
  packages/amplify_core/src/state_machine/state_machine.dart 179:19                                   dispatch
  packages/amplify_core/src/state_machine/state_machine.dart 32:23                                    dispatchAndComplete
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_core/src/state_machine/state_machine.dart 29:67                                    dispatchAndComplete
  packages/amplify_core/src/state_machine/state_machine.dart 190:13                                   dispatchAndComplete
  packages/amplify_auth_cognito_dart/src/state/cognito_state_machine.dart 80:36                       loadCredentials
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/cognito_state_machine.dart 79:46                       loadCredentials
  packages/amplify_auth_cognito_dart/src/state/machines/fetch_auth_session_state_machine.dart 198:34  onFetchAuthSession
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/fetch_auth_session_state_machine.dart 194:34  onFetchAuthSession
  packages/amplify_auth_cognito_dart/src/state/machines/fetch_auth_session_state_machine.dart 65:15   resolve
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                  runBody
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                  _async
  packages/amplify_auth_cognito_dart/src/state/machines/fetch_auth_session_state_machine.dart 60:23   resolve
  packages/amplify_core/src/state_machine/state_machine.dart 255:59                                   <fn>
  dart-sdk/lib/async/future.dart 424:39                                                               <fn>
  dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19                             internalCallback

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Platforms

- [X] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @TriaHub, sorry you are facing this issue. Can you try awaiting the call to `Amplify.addPlugins`?

**Comment by TriaHub** [comment]
> Hi @TriaHub, sorry you are facing this issue. Can you try awaiting the call to `Amplify.addPlugins`?

It worked!
