### ISSUE TITLE
is Amplify config file is safe to keep on app  

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#2945]
i have a doubt actually 

It is generally not recommended to keep sensitive information, such as AWS Amplify configuration files or access keys, within the app folder. This is because if someone gains access to your app's file system, they may be able to retrieve these sensitive information (reverse engineer ) and potentially use them to access your AWS resources.

need to know how amazon protects it / any steps to avoid such incident

**Comment by Jordan-Nelson** [comment]
Hello - There was a similar discussion in Amplify Android recently. See: https://github.com/aws-amplify/amplify-android/issues/2138.

Please let me know if you have further questions.

**Comment by Aruljebaraj** [comment]
can datastore access can be protected using rules?
though what rules need to be specified and How ?

Note :
For authentication we are using our own Api to validate

**Comment by Aruljebaraj** [comment]
if  tried to edit manually 
type ApplicationList @model @auth(rules: [{ allow: owner, ownerField: "licenceID" }]) {
  id: ID!
  response: String
  licenceID:String
}
even though amplify push doesnot modify the changes in Datamodel

**Comment by Aruljebaraj** [comment]
@Jordan-Nelson  we are using api created by us to validate user only for datastore and Storage amplify is been used
and i think we have configured amplify auth -- for datastore and storage

**Comment by Jordan-Nelson** [comment]
@Aruljebaraj I am not sure what you mean by this. Are you using Cognito? Are you adding the AmplifyAuthCognito plugin?

Here is a link to our docs on owner based auth: https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter/#owner-based-authorization

**Comment by Aruljebaraj** [comment]
Yes I'm using it

**Comment by Jordan-Nelson** [comment]
Okay. Is there a specific issue you are facing?

**Comment by Jordan-Nelson** [comment]
@Aruljebaraj - I am going to close this out since I have not heard back. If there is an issue you are facing, please open an issue and fill out the info in the template.
