### ISSUE TITLE
Cognito social auth not showing up on Android, hangs on iOS after login

### ISSUE THREAD

**Issue by sowens-csd** [aws-amplify/amplify-flutter#2947]
### Description

Clicking the 'Sign in with Google' button should bring up the web UI to sign in but instead I see a blank screen with the Cognito hosted URL in the title bar. This is on a Pixel 6a running Android 13. There are no errors in the debug console (VSCode)

The same app does show the Web UI on iOS and successfully takes the email address and password. A user is created on Cognito but the login dialog never redirects back to the app. Instead the web UI remains displayed with a spinner on it. I've tried deleting and recreating the app and the OAuth Web credentials numerous times with the same result. I'm using version 1.0.0 of Amplify_flutter. 

The app configuration is as suggested in the walkthrough but here's the basic flow:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:public_app/src/home_page.dart';
import 'package:public_app/amplifyconfiguration.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';

class MyApp extends StatefulWidget {
  const MyApp({
    super.key,
  });

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  Future<void> _configureAmplify() async {
    // Add any Amplify plugins you want to use
    final authPlugin = AmplifyAuthCognito();
    await Amplify.addPlugin(authPlugin);

    // You can use addPlugins if you are going to be adding multiple plugins
    // await Amplify.addPlugins([authPlugin, analyticsPlugin]);

    // Once Plugins are added, configure Amplify
    // Note: Amplify can only be configured once.
    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      safePrint(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Authenticator(
      preferPrivateSession: true,
      child: MaterialApp(
        // Providing a restorationScopeId allows the Navigator built by the
        // MaterialApp to restore the navigation stack when a user leaves and
        // returns to the app after it has been killed while running in the
        // background.
        restorationScopeId: 'app',
        builder: Authenticator.builder(),
        // Provide the generated AppLocalizations to the MaterialApp. This
        // allows descendant Widgets to display the correct translations
        // depending on the user's locale.
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [
          Locale('en', ''), // English, no country code
        ],

        // Use AppLocalizations to configure the correct application title
        // depending on the user's locale.
        //
        // The appTitle is defined in .arb files found in the localization
        // directory.
        onGenerateTitle: (BuildContext context) =>
            AppLocalizations.of(context)!.appTitle,

        // Define a light and dark color theme. Then, read the user's
        // preferred ThemeMode (light, dark, or system default) from the
        // SettingsController to display the correct theme.
        theme: ThemeData(),
        darkTheme: ThemeData.dark(),

        // Define a function to handle named routes in order to support
        // Flutter web url navigation and deep linking.
        onGenerateRoute: (RouteSettings routeSettings) {
          return MaterialPageRoute<void>(
            settings: routeSettings,
            builder: (BuildContext context) {
              switch (routeSettings.name) {
                default:
                  return const HomePage();
              }
            },
          );
        },
      ),
    );
  }
}

```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Walk through the setup tutorial for social sign on https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#full-sample
2. Run the app
3. Click the Sign in with Google button
4. on Android that's it, the app shows a blank screen (screenshot below). On iOS the web login UI shows up.
5. Login with a valid email / pwd combination. 
6. A blank screen with a progress spinner shows up. (screenshot below)
7. Go to the Cognito console and check for users, a user has been setup in Cognito (from the iOS login)

### Screenshots

Here's the app running on a Pixel 6a (not an emulator):
![Screenshot_20230427-091150](https://user-images.githubusercontent.com/53624354/234874492-aeb25ea2-f49a-423d-9016-816f21c4aa1c.png)

This is what shows up after clicking the Sign in button:
![Screenshot_20230427-091255](https://user-images.githubusercontent.com/53624354/234874528-4eae37a7-9a5f-4674-85a3-0ad120202474.png)

Here's the same app running on iOS:
<img width="381" alt="Screenshot 2023-04-27 at 9 21 46 AM" src="https://user-images.githubusercontent.com/53624354/234875374-4e002f7c-233e-4a6b-8383-794ad1854c81.png">

The web UI shows up as expected:
<img width="457" alt="Screenshot 2023-04-27 at 9 22 01 AM" src="https://user-images.githubusercontent.com/53624354/234875636-ea99941e-3ec6-470c-ac9e-cb38218eeb38.png">

Login works:
<img width="422" alt="Screenshot 2023-04-27 at 9 22 40 AM" src="https://user-images.githubusercontent.com/53624354/234875712-9008e18d-904e-4cba-8abe-87ee9c7ece1a.png">

However, after signing in this screen remains with the spinner, it never redirects back to the app:
<img width="421" alt="Screenshot 2023-04-27 at 9 22 54 AM" src="https://user-images.githubusercontent.com/53624354/234875917-7c047078-e4cf-478c-a112-eddc74e85f1d.png">

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @sowens-csd, sorry you are facing this issue. Given that you're experiencing this issue on both iOS and Android leads me to believe there may be something misconfigured. I'll be happy to help track down what that could be.

Could you please share the following information:
1. A redacted version of your `amplifyconfiguration.dart` file
2. A confirmation that you've followed the platform-specific setup instructions noted [here](https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#platform-setup), specifically around updating your `AndroidManifest.xml`.
3. A confirmation that you've followed the Google setup instructions noted [here](https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#setup-your-auth-provider) and have added your Cognito domain and redirect URI to the Google Cloud OAuth configuration.
4. Can you try logging in using the Cognito console? To do this:
- Run `amplify console auth` and choose `User pool` to open the Cognito console
- Click the **App integration** tab
- In the **App clients and analytics** panel, click on the app client not ending in `Web`
- On the top-right of the **Hosted UI** panel, click **View Hosted UI** and try logging in
- If everything is configured, you should be redirected to your app's custom URI scheme after signing in with Google
5. If you could share a screenshot of the **Hosted UI** panel mentioned above, that would be great

Thanks for your patience resolving this!

**Comment by sowens-csd** [comment]
In answer to your questions: 
1. Copied below
2. Yes, I believe so. I've copied the manifest below. 
3. Yes, I followed those directions and did set the domain and redirect URI as noted. 
4. I'll try that shortly and post once I have with a screenshot. 

Here's the manifest:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.fridgebuzz.app.public_app">
    <queries>
    <intent>
        <action android:name=
            "android.support.customtabs.action.CustomTabsService" />
    </intent>
    </queries>
   <application
        android:label="public_app"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

The Amplify configuration:
```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ca-central-1:xxxxxxxxx",
                            "Region": "ca-central-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ca-central-XXXXXX",
                        "AppClientId": "xxxxxx",
                        "Region": "ca-central-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxx-dev.auth.ca-central-1.amazoncognito.com",
                            "AppClientId": "xxxxxx",
                            "SignInRedirectURI": "whisperai://",
                            "SignOutRedirectURI": "whisperai://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "GOOGLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Comment by sowens-csd** [comment]
Hosted UI panel: 

<img width="888" alt="Screenshot 2023-04-27 at 2 48 37 PM" src="https://user-images.githubusercontent.com/53624354/234962529-f8ba38ea-1e65-43bd-95fa-0fb572baed4e.png">

**Comment by dnys1** [comment]
Thanks!

In your `AndroidManifest.xml` can you try making the following change?

```diff
-                <data android:scheme="myapp" />
+                <data android:scheme="whisperai" />
```

**Comment by sowens-csd** [comment]
After logging in to the hosted UI it goes to this URL:

https://accounts.google.ca/accounts/SetSID

**Comment by dnys1** [comment]
One more thing to check in the Cognito console.

- Click on the **Sign-in experience** tab
- Under the **Federated identity provider sign-in** panel, click on the Google provider

Can you confirm the **Authorized scopes** are `openid email profile` (in no particular order) and that there are attribute mappings for `username -> sub` and `email -> email`?

**Comment by sowens-csd** [comment]
I made that change to the Android manifest (doh!) 

I've rebuilt and run it again on the same device, now after clicking the Sign in with google button the web dialog disappears and it redirects back to the app. It doesn't ask me for an email/password. I think that's probably  correct because it's the same user as I have on the device, can you confirm? If so it then maybe it is working on Android?

**Comment by sowens-csd** [comment]
<img width="155" alt="Screenshot 2023-04-27 at 2 56 55 PM" src="https://user-images.githubusercontent.com/53624354/234964397-06bcc8f5-8d5d-40a8-ab4e-fd1e3ce5e532.png">
<img width="888" alt="Screenshot 2023-04-27 at 2 56 31 PM" src="https://user-images.githubusercontent.com/53624354/234964418-a3ea0cf7-6de2-4a60-b7a9-4145d6403501.png">

**Comment by dnys1** [comment]
Yes, that sounds like it's working on Android. It shouldn't prompt you if the user previously authenticated in the browser 👍

**Comment by sowens-csd** [comment]
Any thoughts on why it is still not redirecting on iOS?

**Comment by dnys1** [comment]
Hmm.. have you configured the iOS platform to `13.0` in the places mentioned here? https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/#ios

**Comment by sowens-csd** [comment]
Thank you! It works now. I had not done that. I had modified the Podfile to set it automatically but that apparently doesn't work. 

You can close this issue, thanks very much for the help.

**Comment by dnys1** [comment]
My pleasure and so sorry for the confusion. I’ll make sure the migration docs are updated.
