### ISSUE TITLE
Fail to sign in with Google provider: Member must satisfy regular expression pattern ...

### ISSUE THREAD

**Issue by Romain-Guillot** [aws-amplify/amplify-flutter#2949]
### Description

I cannot authenticate a user with Google Provider:

```dart
final result = await Amplify.Auth.signInWithWebUI(
    provider: AuthProvider.google,
);
```

The error:

```
UnknownException {
     "message": "(invalidRequest) 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}] ; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]  "
}
```

Device: Android 13

The process works with another Google account.  
There is no trailing space when I use the Google sign in form.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @Romain-Guillot, sorry you are facing this issue. I haven't encountered this before but want to try and understand what the error message is stating.

According to regex101.com, the regex `[\p{L}\p{M}\p{S}\p{N}\p{P}]` means the following:
> **Match a single character present in the list below:**
> - `\p{L}` matches any kind of letter from any language
> - `\p{M}` matches a character intended to be combined with another character (e.g. accents, umlauts, enclosing boxes, etc.)
> - `\p{S}` matches any math symbols, currency signs, dingbats, box-drawing characters, etc
> - `\p{N}` matches any kind of numeric character in any script
> - `\p{P}` matches any kind of punctuation character

So, the error you're receiving means that a member of the username did not fall into one of these buckets. Is that possible given your understanding of the user trying to login?
