### ISSUE TITLE
Amplify Auth methods possible exceptions

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#295]
Hey there.

I noticed a lack of documentation in getting the possible exceptions for each authentication method.

For example, when I call "Amplify.Auth.signIn" method, I need to deal with AuthError exception. By inspecting AuthError, I saw it has an exceptionList that is nothing more that a list of strings. I would like to handle this exceptions better to provide a better experience to the users when the signIn method is called. For instance, I would like to know when a User confirmation is necessary and show this info to my user.

My question is: how can I have a list of possible exceptions for each authentication method (signIn, confirmPassword, updatePassword...) so this way I could handle it differently?

**Comment by haverchuck** [comment]
@brunovsiqueira We are actively working on improving these exceptions across the entire Amplify library.  I am marking this as a feature request for now - please stay tuned.

**Comment by brunovsiqueira** [comment]
Thanks @haverchuck. Looking forward for this feature.

**Comment by elisamalzoni** [comment]
Do you guys have an estimated time for this feature?

**Comment by brunovsiqueira** [comment]
Hi guys. Any updates on this @haverchuck?

**Comment by haverchuck** [comment]
@brunovsiqueira @elisamalzoni I cannot give specific dates on when this will be delivered, but I can say that it should be soon.  Once released, you will see that errors thrown by the Auth package will get cast to an AuthException dart type, and when possible, we cast these to child classes which map to the error types defined by the Cognito service. Some of the values contained within these types may vary a bit by platform, but in general it will allow for much higher fidelity error catching than what is currently possible.

**Comment by Amplifiyer** [comment]
The error revamp is complete and released in 0.0.2-dev.2 and you can find all the possible exceptions here https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_auth_plugin_interface/lib/src/Exceptions. All of these exceptions inherit from `AuthException` which inherit from `AmplifyException`

We will work on getting these exceptions to our documentation.

**Comment by AntonYarish** [comment]
Hi guys. Any updates on this @haverchuck?

**Comment by ahmad-olu** [comment]
@Amplifiyer the link does not exist anymore.

**Comment by AmanMasipeddi** [comment]
The link does not exist anymore

**Comment by MilosKarakas** [comment]
Try with these:
[https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito/lib/amplify_auth_error_handling.dart
](auth cognito error handling)

[https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_core/lib/src/types/exception/auth](all possible auth exceptions from amplify core)
