### ISSUE TITLE
Amplify.Storage.list returning empty list

### ISSUE THREAD

**Issue by vishwasfoundation** [aws-amplify/amplify-flutter#2952]
### Description

I am using existing storage to my flutter app and then I am trying to get folders and subfolders of a bucket. But Amplify.Storage.list() always returning empty array. Bucket is publicly accessible. I have added the below policy as well.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::{bucket-name}/"
        }
    ]
}

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

Future<void> listAlbum() async {
    try {
      String? nextToken;
      bool hasNextPage;
      do {
        final result = await Amplify.Storage.list(
          // options: const StorageListOptions(
          //   accessLevel: StorageAccessLevel.guest,
          //   pluginOptions: S3ListPluginOptions.listAll(),
          // ),
        ).result;
        safePrint('Listed items: ${result.items}');
        nextToken = result.nextToken;
        hasNextPage = result.hasNextPage;
      } while (hasNextPage);
    } on StorageException catch (e) {
      safePrint('Error listing files: ${e.message}');
      rethrow;
    }
  }

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hi @vishwasfoundation thanks for opening this issue.

When you are using an exiting S3 bucket with Amplify, please ensure follow this instruction: https://docs.amplify.aws/lib/storage/existing-resources/q/platform/flutter/

In addition, Amplify Storage has restrictions regarding authentication and access levels, files that are uploaded or read using Amplify are organized by certain prefixes, please refer [the documentation about storage access level](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/) for details.

Also a side note: Amplify Storage S3 `list` API uses S3 service `ListObjectV2` API under the hood, which requires permission for `s3:ListBucket` action.

**Comment by HuiSF** [comment]
Hi @vishwasfoundation please let us know if you need further assistance.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by aaparth** [comment]
do {
                let listResult = try await Amplify.Storage.list()
                
                if !listResult.items.isEmpty {
                    for item in listResult.items {
                        let key = item.path
                        let size = item.size
                        let lastModified = item.lastModified
                        
                        // Print details of each item
                        if key.hasSuffix("/") {
                            print("Folder: \(key)")
                        } else {
                            print("File: \(key) | Size: \(String(describing: size)) bytes")
                        }
                        
                        // Optionally, print last modified date
                        if let lastModifiedDate = lastModified {
                            print("Last Modified: \(lastModifiedDate)")
                        } else {
                            print("Last Modified: Not available")
                        }
                    }
                } else {
                    print("No items found.")
                }
            } catch let storageError as StorageError {
                print("Amplify Storage error: \(storageError.errorDescription)")
                print("Recovery suggestion: \(storageError.recoverySuggestion)")
                print("Underlying error: \(String(describing: storageError.underlyingError))")
            } catch {
                print("Unexpected error: \(error.localizedDescription)")
            }
        }
        
        
        
        
        
        Not able to get any list for file and folder listResult.items isEmpty 

Can any one help please
