### ISSUE TITLE
[API] AmplifyApi.kt Unresolved reference: FlutterAuthProviders

### ISSUE THREAD

**Issue by Sandiverse** [aws-amplify/amplify-flutter#2961]
### Description

Unable to run the app after upgrading from amplify_api 1.0.0 to amplify_api 1.0.1

Already tried:

1. Flutter clean and Flutter pub get
2. Deleting pub.dev folder from local cache hosted data

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Change the version of amplify_api to 1.0.1 on pubspec.yaml
2. Run the app on any android device
3. The error will come out as the build progresses

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
@Sandiverse sorry you are facing this issue, I was wondering if you could provide a little more info to help the team reproduce the issue. Would it be possible to provide:
* the build output with this error, including stack trace
* dependencies in `pubspec.lock`
* `build.gradle` and `settings.gradle` files
*  the code snippet you are using in Flutter to configure Amplify

**Comment by ragingsquirrel3** [comment]
@Sandiverse we were actually able to reproduce this issue when using an older version of Kotlin (1.6.10). What Kotlin version are you using? If you also have an older version, would it be possible to try upgrading to a new version (> 1.7) and see if that fixes the issue for you?

**Comment by Sandiverse** [comment]
I was able to run the app without any error just by upgrading Android Studio version to Android Studio Flamingo (previous version was Electric Eel)

But just to be completely clear these are my current settings used with both Android Studio versions

**build.gradle**

`buildscript {
    ext.kotlin_version = '1.8.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
**settings.gradle**

`include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
`
**This is the code I'm using to configure Amplify but I think it is not useful since the app execution does not reach it because it was not even building the .apk to debug**

`Future<void> _configureAmplify() async {
    if (Amplify.isConfigured) return;
    final AuthBloc authBloc = BlocProvider.of<AuthBloc>(context);
    FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
    String? remoteVersion = remoteConfig.getString('v');
    var configsBox = Hive.box<String>(AppConfigs.boxName);
    String? localVersion = configsBox.get(ConfigName.appVersion.name);
    bool updateRequired = false;

    if (localVersion == null || localVersion != remoteVersion) {
      updateRequired = true;
      String? initialEndpoint = remoteConfig.getString('ie');
      await configsBox.put(ConfigName.endpointsUpdateRequired.name, 'true');
      await configsBox.put(AppEndpoint.initialEndpoint.name, initialEndpoint);
      await configsBox.put(ConfigName.appVersion.name, remoteVersion);
    }

    if (updateRequired) {
      log('UPDATING AMPLIFY CONFIG');
      FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
      String? remoteAmplifyConfig = remoteConfig.getString('ac');

      if (remoteAmplifyConfig.isEmpty) throw Exception('Remote amplify config is null');

      await configsBox.put(ConfigName.amplifyConfig.name, remoteAmplifyConfig);
    }

    String localAmplifyConfig = configsBox.get(ConfigName.amplifyConfig.name)!;

    await Amplify.addPlugins([
      AmplifyAuthCognito(),
      AmplifyAPI(),
    ]);
    log(localAmplifyConfig);
    await Amplify.configure(localAmplifyConfig);
    authBloc.add(EventInitAmplifyAuthSubscription());
    log('AMPLIFY CONFIGURED FROM APP');
  }`

**Comment by ragingsquirrel3** [comment]
I'm glad you got this working (and thanks for background info nonetheless). I'm going to close this issue.
