### ISSUE TITLE
Datastore - Selective Sync 

### ISSUE THREAD

**Issue by nithin-seenivasan** [aws-amplify/amplify-flutter#298]
Would be great to have selective sync for Flutter, similar to what exists in Amplify JS. [https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selectively-syncing-a-subset-of-your-data](url)

I would ideally like to have a proper control over the syncing process. Ideas could include: 
1.  Configure a time interval for a sync to happen 
2.   The client can trigger a sync operation
~~3. The sync can be on listening to any changes to the datasource like DynamoDB~~ (resolved using Appsync)

~~Related to issue #297~~
~~Also discussed on #5~~

**Comment by nithin-seenivasan** [comment]
Updated the post above to reflect current status.

**Comment by apolo92** [comment]
Is there any forecast of when this new functionality will be available?
If we don't have this functionality, is there any way to control the synchronization? By default I understand that it will synchronize the entire cloud DB locally. Does this mean that user A will have user B data on his local device?

**Comment by cto-leaps** [comment]
Any idea when selective sync will be available?

**Comment by seyaobey** [comment]
This is indeed a much needed feature. Amplify is an amazing product. But I have switched to another platform for my real-time database since for privacy reasons, I cannot download the whole database into every device.

**Comment by apolo92** [comment]
> This is indeed a much needed feature. Amplify is an amazing product. But I have switched to another platform for my real-time database since for privacy reasons, I cannot download the whole database into every device.

What platform have you used to replace datastore? firebase?

**Comment by nithin-seenivasan** [comment]
> 
> 
> Is there any forecast of when this new functionality will be available?
> If we don't have this functionality, is there any way to control the synchronization? By default I understand that it will synchronize the entire cloud DB locally. Does this mean that user A will have user B data on his local device?

Not really, Datastore uses Appsync, and user A will only get the data synced that they are 'subscribed' to. So even though the underlying DynamoDB table is common, the userdata will be separate with no possibility of data leaking between accounts.

**Comment by kjones** [comment]
> Not really, Datastore uses Appsync, and user A will only get the data synced that they are 'subscribed' to. So even though the underlying DynamoDB table is common, the userdata will be separate with no possibility of data leaking between accounts.

This isn't true by default. You have to explicitly add [authorization rules](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter) to your GraphQL schema to control what gets synced. The default is everything in the table.

**Comment by nithin-seenivasan** [comment]
> 
> 
> > Not really, Datastore uses Appsync, and user A will only get the data synced that they are 'subscribed' to. So even though the underlying DynamoDB table is common, the userdata will be separate with no possibility of data leaking between accounts.
> 
> This isn't true by default. You have to explicitly add [authorization rules](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter) to your GraphQL schema to control what gets synced. The default is everything in the table.

You are right, @kjones , I forgot that one had to explicitly control what gets synced in the schema. That should solve @apolo92 's issue.

**Comment by kjones** [comment]
I'm more interested in selective sync from a performance and cost perspective. Say the table has millions of records and I have auth rules set up. I don't see how AppSync can optimize this query given that all items in the table are only unique by ID. It must do a DynamoDB Scan operation on this table and then filter the results by owner. At most it can add a filter expression to the query which still scans the entire table but returns a result set with only the owner's records. With selective sync I should be able to create a GSI on the table and then [use a query expression that turns the table scan into an optimized query](https://docs.amplify.aws/lib/datastore/sync/q/platform/js#advanced-use-case---query-instead-of-scan) for the user's data.

**Comment by apolo92** [comment]
> > > Not really, Datastore uses Appsync, and user A will only get the data synced that they are 'subscribed' to. So even though the underlying DynamoDB table is common, the userdata will be separate with no possibility of data leaking between accounts.
> > 
> > 
> > This isn't true by default. You have to explicitly add [authorization rules](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter) to your GraphQL schema to control what gets synced. The default is everything in the table.
> 
> You are right, @kjones , I forgot that one had to explicitly control what gets synced in the schema. That should solve @apolo92 's issue.

Thanks @nithin-seenivasan  and @kjones I use @owner permissions in appsync and only sync data user. But during testing I have seen that the Amplify.Datastore.clear () does not work on ios. This command do not nothing :(. Do you have any issue on this topic?

**Comment by rajd90** [comment]
i really need this feature as well. selective sync is critical for performance & cost reasons, as we really need to avoid doing scans and use query (as indicated in the many dynamodb best practice examples). is it already possible and just not documented?

**Comment by rajd90** [comment]
is there any update / timeline on this issue?

**Comment by cshfang** [comment]
> is there any update / timeline on this issue?

Thanks all for your valued feedback on this feature. I am unable to provide anything close to concrete dates at this time but it is something we are investigating.

**Comment by cshfang** [comment]
As of [v0.2.1](https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.2.1), Amplify Flutter should now support selective sync. More information about this can be found in the Amplify Docs [here](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter#selectively-syncing-a-subset-of-your-data).
