### ISSUE TITLE
Codegen should reflect `@default` directive

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2985]
Currently, fields with an `@default` directive do not produce Dart models which set this on model creation.

```graphql
type Todo @model @auth(rules: [{ allow: private }]) {
    id: ID!
    name: String!
    description: String!
    isChecked: Boolean! @default(value: "false")
}
```

**Comment by HuiSF** [comment]
Here is the bug: https://github.com/aws-amplify/amplify-codegen/issues/333

**Comment by haverchuck** [comment]
Closing in favor of codegen bug.
