### ISSUE TITLE
Working with SAML Identity Provider

### ISSUE THREAD

**Issue by motucraft** [aws-amplify/amplify-flutter#2994]
### Description

I am trying to use SAML identity providers in my Cognito user pool. amplify_flutter can use SAML identity provider?

I have consulted the documentation and cannot figure out how to use SAML.
https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/

Would it work if I use AuthProvider.saml?
https://pub.dev/documentation/amplify_core/latest/amplify_core/AuthProvider/AuthProvider.saml.html

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.12

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Yes! This feature is now available in Amplify Flutter v1. To enable a SAML provider, follow the instructions in the Cognito docs for enabling [Hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html) and [adding a SAML provider](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html), then call signInWithWebUI using the name given during set up.

```dart
Future<void> _signInSaml() async {
  final result = await Amplify.Auth.signInWithWebUI(
    provider: const AuthProvider.saml('Keycloak-SAML'),
  );
  safePrint(result);
}
```

**Comment by dnys1** [comment]
Please let me know if you face any issues implementing this in your project.

**Comment by motucraft** [comment]
@dnys1 
Thanks for your response.

I would like to use localhost keycloak as Idp for SAML authentication.
However, I did not see an option to set the SAML authentication provider in "amplify auth add".

So I am thinking of creating a Cognito user pool and running "amplify auth import". Is this approach correct?

```
% amplify auth import
Using service: Cognito, provided by: awscloudformation
✔ What type of auth resource do you want to import? · Cognito User Pool only
✔ Select the User Pool you want to import: · ap-northeast-1_xxxxxxxxxx
✔ Only one Web app client found: 'samlclient' was automatically selected.
✔ Only one Native app client found: 'samlclient' was automatically selected.
⚠️ It is recommended to use different app client for web and native application.

✅ Cognito User Pool 'saml_user_pool' was successfully imported.

```

```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-northeast-1_xxxxxxxxxx",
                        "AppClientId": "zzzzzzzzzzzzzzzzz",
                        "Region": "ap-northeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

Identity provider named MySamlProvider.

![image](https://user-images.githubusercontent.com/35750184/236384255-e67a49f2-3f0d-4e89-8cfc-808c02bc6e79.png)

Sample code is follow

```dart
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  Future<void> _configureAmplify() async {
    try {
      final auth = AmplifyAuthCognito();
      await Amplify.addPlugin(auth);

      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      safePrint('An error occurred configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () async {
                    await _signInSaml();
                  },
                  child: const Text('Sign in saml'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Future<void> _signInSaml() async {
    final result = await Amplify.Auth.signInWithWebUI(
      provider: const AuthProvider.saml('MySamlProvider'),
    );
    safePrint(result);
  }
}
```

The following logs are output.

<details>
<summary>console log</summary>
 % flutter run -d chrome --web-port 8000
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             18.2s
This app is linked to the debug service: ws://127.0.0.1:60654/_gQ_JmXWRSw=/ws
Debug service listening on ws://127.0.0.1:60654/_gQ_JmXWRSw=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:60654/_gQ_JmXWRSw=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:60654/_gQ_JmXWRSw=
ERROR | HostedUiStateMachine | Emitted error: Bad state: No instance found for CognitoOAuthConfig
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49               throw_
packages/amplify_core/src/state_machine/dependency_manager.dart 69:7                       expect
packages/amplify_core/src/state_machine/dependency_manager.dart 148:22                     expect
packages/amplify_core/src/state_machine/state_machine.dart 139:26                          expect
packages/amplify_core/src/state_machine/state_machine.dart 400:60                          expect
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 34:37   get [_config]
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 35:42   get [_keys]
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 130:17  onSignIn
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                         runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                         _async
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 128:24  onSignIn
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 61:15   resolve
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                         runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                         _async
packages/amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 42:23   resolve
packages/amplify_core/src/state_machine/state_machine.dart 255:59                          <fn>
dart-sdk/lib/async/future.dart 424:39                                                      <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19                    internalCallback
===== asynchronous gap ===========================
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 977:28                         get current
packages/amplify_core/src/state_machine/event.dart 42:47                                   new
packages/amplify_core/src/state_machine/state_machine.dart 150:23                          accept
packages/amplify_auth_cognito_dart/src/auth_plugin_impl.dart 363:10                        signInWithWebUI
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                         runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                         _async
packages/amplify_auth_cognito_dart/src/auth_plugin_impl.dart 344:46                        signInWithWebUI
packages/amplify_core/src/category/amplify_auth_category.dart 951:21                       signInWithWebUI
packages/saml_sample/main.dart 60:39                                                       _signInSaml
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                         runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                         _async
packages/saml_sample/main.dart 59:27                                                       [_signInSaml]
packages/saml_sample/main.dart 47:27                                                       <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                         runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                         _async
packages/saml_sample/main.dart 46:30                                                       <fn>
packages/flutter/src/material/ink_well.dart 1096:21                                        handleTap
packages/flutter/src/gestures/recognizer.dart 253:24                                       invokeCallback
packages/flutter/src/gestures/tap.dart 627:11                                              handleTapUp
packages/flutter/src/gestures/tap.dart 306:5                                               [_checkUp]
packages/flutter/src/gestures/tap.dart 239:7                                               handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 615:9                                        handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:12                                    [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13                   forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                                   [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                                    route
packages/flutter/src/gestures/binding.dart 460:19                                          handleEvent
packages/flutter/src/gestures/binding.dart 440:14                                          dispatchEvent
packages/flutter/src/rendering/binding.dart 336:11                                         dispatchEvent
packages/flutter/src/gestures/binding.dart 395:7                                           [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 357:5                                           handlePointerEvent
packages/flutter/src/gestures/binding.dart 314:7                                           [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 295:7                                           [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1183:13                                        invoke1
lib/_engine/engine/platform_dispatcher.dart 243:5                                          invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 156:39                                             [_onPointerData]
lib/_engine/engine/pointer_binding.dart 689:20                                             <fn>
lib/_engine/engine/pointer_binding.dart 620:14                                             <fn>
lib/_engine/engine/pointer_binding.dart 303:16                                             loggedHandler
lib/_engine/engine/pointer_binding.dart 188:80                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37           _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39           dcall


Error: Bad state: No instance found for CognitoOAuthConfig
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 355:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1385:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
Error: Bad state: No instance found for CognitoOAuthConfig
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 355:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1385:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
</details>


Is there a missing SAML-related setting in amplifyconfiguration.dart?

**Comment by motucraft** [comment]
Run "View Hosted UI" in the AWS console to check the operation.

![image](https://user-images.githubusercontent.com/35750184/236464854-6d4c93ac-0ffe-412f-935b-192293478fe9.png)

In this case, you will be redirected to keycloak on localhost and the keycloak login page will be displayed.
http://localhost:8080/auth/realms/myrealm/protocol/saml?xxx...

![image](https://user-images.githubusercontent.com/35750184/236465468-04bfafa9-3084-4c28-922a-b1cc509b7917.png)

However, Flutter (AuthProvider.saml('MySamlProvider')) cannot perform this move.
That is why I am suspecting a problem with amplifyconfiguration.dart.

**Comment by dnys1** [comment]
Which device are you trying to run on? It's not an issue with Amplify, but more just a general networking problem. Devices like the Android emulator cannot automatically connect to the `localhost` domain and must be configured to do so. An alternative may be to use something like `ngrok` to allow connecting to your `localhost` over the internet.

**Comment by motucraft** [comment]
@dnys1 
Platform is the web.
Since keycloak is on localhost, Flutter web is naturally running on localhost.
As noted in the log above, we are starting with `flutter run -d chrome --web-port 8000`.

I am not sure what you mean by network problems.
I think Flutter web on localhost can access both AWS Cognito and keycloak on localhost, but is it impossible?

**Comment by motucraft** [comment]
@dnys1 
I am trying to do this by trial and error.
Rewriting amplifyconfiguration.dart as follows seemed to work.

```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-northeast-1_xxxxxxxxxx",
                        "AppClientId": "zzzzzzzzzzzzzzzzz",
                        "Region": "ap-northeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "samlsample.auth.ap-northeast-1.amazoncognito.com",
                            "AppClientId": "xyz",
                            "SignInRedirectURI": "http://localhost:8000/",
                            "SignOutRedirectURI": "http://localhost:8000/",
                            "Scopes": [ "email" ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

```

The Flutter sample code is below.
Start with `flutter run -d chrome --web-port 8000`.


<details>
<summary>Sample code</summary>

```dart
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  Future<void> _configureAmplify() async {
    try {
      final auth = AmplifyAuthCognito();
      await Amplify.addPlugin(auth);

      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      safePrint('An error occurred configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () async {
                    await _signInSaml();
                  },
                  child: const Text('Sign in saml'),
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () async {
                    final isSignedIn = await isUserSignedIn();
                    debugPrint('isSignedIn=$isSignedIn');
                    if (isSignedIn) {
                      final user = await getCurrentUser();
                      debugPrint('user=$user');
                    }
                  },
                  child: const Text('current user'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Future<void> _signInSaml() async {
    final result = await Amplify.Auth.signInWithWebUI(
      provider: const AuthProvider.saml('MySamlProvider'),
    );
    safePrint(result);
  }

  Future<bool> isUserSignedIn() async {
    final result = await Amplify.Auth.fetchAuthSession();
    return result.isSignedIn;
  }

  Future<AuthUser> getCurrentUser() async {
    final user = await Amplify.Auth.getCurrentUser();
    return user;
  }
}
```

</details>

After clicking "Sign in saml", the keycloak login screen will appear. keycloak is localhost.
After logging in to keycloak, will be redirected to the application screen.

Click on "current user" and the following will be output to the console.

```
isSignedIn=true
user=CognitoAuthUser {
  "userId": "73ae98a0-0607-42a2-b2bc-64d92f461e59",
  "username": "mysamlprovider_g-f6e1bb0c-5587-46d5-bb42-e650d6a5b7b5",
  "signInDetails": {
    "signInType": "hostedUi",
    "provider": {
      "name": "MySamlProvider",
      "identityPoolProvider": null
    }
  }
}
```

This accomplished the first thing I wanted to do.
As I mentioned above, I suspected that the amplifyconfiguration.dart was not set up correctly.

I was confused by the fact that what I wanted to do was SAML, but I needed "OAuth" in the amplifyconfiguration.dart.
And I still can't find any documentation on SAML in amplify_flutter. Isn't there a need to expand the documentation?

**Comment by motucraft** [comment]
I was not aware of the following points:

If a third-party IdP is used (in my case keycloak), I think Cognito behaves as an SP in the SAML flow. Additionally, does it mean that Cognito behaves as an OIDC OP?
And I understand that amplify_flutter performs OIDC access to Cognito.

If my understanding is incorrect, please let me know.

**Comment by dnys1** [comment]
Ah yes, my apologies. Your app communicates with Cognito using the OIDC protocol always. Cognito then handles the interaction with your SAML/OAuth provider on the backend.

Using a `localhost` endpoint for your provider will work with Flutter Web + Desktop, but my point about networking may apply if you try to use an Android/iOS device. In these cases, you can use a program like `ngrok` to expose your local service to the Internet.

Please let me know if you face any more issues.

**Comment by motucraft** [comment]
Thank you for your thoughtful comment.
