### ISSUE TITLE
fix: authenticator stuck on loading 

### ISSUE THREAD

**Issue by ALi4576** [aws-amplify/amplify-flutter#3006]
### Description

Authenticator gets stuck on loading state after all the plugins are configured. It was working fine on version 0.2.5 and stopped working on version 1.0.1

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Configure authentication for the project
2. Add authenticator plugin version 1.0.1

Plugins Used:
  amplify_flutter: 1.0.1
  amplify_auth_cognito: 1.0.1
  amplify_datastore: 
  amplify_api: 1.0.1
  amplify_storage_s3: 1.0.1
  aws_common: ^0.4.2+5

### Screenshots
![app_class](https://user-images.githubusercontent.com/33224960/236472668-d3f913e6-839a-4068-8083-1b141153f3ee.PNG)

![configure_amplify](https://user-images.githubusercontent.com/33224960/236470643-66bfdd82-52c0-414f-93ec-97bf65a1a673.PNG)

![configure_amplify_detail](https://user-images.githubusercontent.com/33224960/236472235-57982f42-15c5-438f-bdde-7e4ab52902fd.PNG)

Output:
I/flutter (13378): true (configured)
I/flutter (13378): false (not signed in)

![Screenshot_1683292528](https://user-images.githubusercontent.com/33224960/236467515-f79630c3-834d-4422-86be-4075bd3411d4.png)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.9

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@ALi4576 can you please provide all the details in the issue template, including:
- reproduction steps
- code sample
- logs
- which amplify packages you depend on

Thanks

**Comment by ALi4576** [comment]
@Jordan-Nelson I have added the screenshots. Thanks

**Comment by Jordan-Nelson** [comment]
What version of amplify_datastore are you using?

Can you add `AmplifyLogger().logLevel = LogLevel.verbose;` to the top of the bootstrap call (or to the top of the main fn) and see if there is additional log output?

**Comment by ALi4576** [comment]
@Jordan-Nelson I am closing this issue as I see the problem is with my implementation.
