### ISSUE TITLE
`observe` and `observeQuery` do not support filtering by IDs of nested models

### ISSUE THREAD

**Issue by ryu1maniwa** [aws-amplify/amplify-flutter#3020]
### Description
Thank you for creating and maintaining amplify-flutter.

I upgraded my amplify-flutter to version 1.0.1. Then I noticed that The first snapshot works fine, but Subsequent snapshots are not emitted when using Amplify.DataStore.observeQuery.
I thought it might be an internal issue and decided to create an issue.

`sortedMessages` is updated when new message is saved in the circle.

```
  List<Message> sortedMessages = [];

  @override
  void initState() {
    super.initState();
    observeQueryMessage(widget.circle);
  }

  void observeQueryMessage(Circle circle) {
    streamMessage = Amplify.DataStore.observeQuery(
      Message.classType,
      where: Message.CIRCLE.eq(circle.id),
      // sortBy: [Message.descending()]
    ).listen((QuerySnapshot<Message> snapshot) {
      print('Query snapshot received: ${snapshot.items.length} messages');
      snapshot.items.sort((a, b) => a.createdAt!.compareTo(b.createdAt!));
      });
      setState(() {
        sortedMessages = snapshot.items;
      });
    });
  }
```

When the `saveMessage` function is executed, the contents of `listen` are no longer executed and the `sortedMessages` is not updated in real time.

```dart
Future<void> saveMessage(content, sender, circle) async {
    print("start saving message");
    Message message = Message(
      content: content,
      sender: sender,
      circle: circle,
    );
    await Amplify.DataStore.save(message);
    print('message saved');
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Message @model @auth(rules: [{allow: public}]) {
  id: ID!
  content: String!
  senderID: ID! @index(name: "MessageByUser")
  sender: User! @belongsTo(fields: ["senderID"])
  circleID: ID! @index(name: "MessageByCustomMarker")
  circle: CustomMarker! @belongsTo(fields: ["circleID"])
}
```

**Comment by fjnoyp** [comment]
Hi @ryu1maniwa thanks for sharing this issue.  

You're right - I'm also able to reproduce on my side.  Calls to `Amplify.Datastore.observeQuery` with your where clause works on initial sync but does not trigger afterwards.  

However `observeQuery` which uses `where` on other fields continues to sync after initial. 

We'll look into this more and see if it's an iOS issue as well.  It will likely require changes from Amplify Android, but we'll see and get back to you.

**Comment by Jordan-Nelson** [comment]
@ryu1maniwa - Thanks for opening this issue. This appears to be specific to nested predicates (ex: `Message.ID.eq(message.id)` should be working, but `Message.CIRCLE.eq(circle.id)` is not).

I have opened a PR to address this. I will update here when it is available.

**Comment by ryu1maniwa** [comment]
@fjnoyp @Jordan-Nelson - Thank you for addressing this issue.
I have confirmed that PR to address this issue has been merged to the main branch.
Could you please let me know what I need to do to get the bug-fix to my environment?

**Comment by Jordan-Nelson** [comment]
@ryu1maniwa - we will aim to have a release out next week that includes this fix.

**Comment by dnys1** [comment]
The fix for this has been released in Amplify DataStore `1.1.0-supports-only-mobile+1`. Can you let us know if this resolves the issue?

**Comment by Jordan-Nelson** [comment]
@ryu1maniwa - Please let us know if you are still facing issues after upgrading. Thanks.

**Comment by Jordan-Nelson** [comment]
@ryu1maniwa - I am going to close this out. Let me know if you face any issues. Thanks.
