### ISSUE TITLE
Amplify_authenticator 1.01 ERROR

### ISSUE THREAD

**Issue by nesimventures** [aws-amplify/amplify-flutter#3046]
### Description

 This issue started yesterday. I don't know what happen with the new update but a lot of thing seems to be broken.
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/amplify_authenticator-1.0.1/lib/amplify_authenticator.dart:47:1: Error: Error when reading
'../../../../../.pub-cache/hosted/pub.dev/amplify_authenticator-1.0.1/lib/src/widgets/button.dart': No such file or directory
![image](https://github.com/aws-amplify/amplify-flutter/assets/130711003/1d0b6c9d-b998-44de-80e7-74c5e145b16d)

Here is my pubspec.yaml
![image](https://github.com/aws-amplify/amplify-flutter/assets/130711003/c3f238fc-1120-4775-b801-e057ab0fe297)

I upgraded flutter to 3.10.0 but alot of bugs with ios build so I downgraded to 3.7.11

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.11

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by abdallahshaban557** [comment]
Hi @nesimventures  - were you able to resolve your issue? was it an issue with Amplify?

**Comment by nesimventures** [comment]
Hi @abdallahshaban557, not completely, but I got it working for now. there are some issue with the older versions of flutter as well. However, I did `flutter upgrade` to the newest version 3.10.0. I also had to add the following code snippet to my ios Podfile to get it to work.
![image](https://github.com/aws-amplify/amplify-flutter/assets/130711003/06d72cf1-b1db-49ff-9cb0-a0cfadcb41a5)

**Comment by abdallahshaban557** [comment]
Ah - got it, so it is a Flutter issue. We were running into something similar with some apps we were working on.
