### ISSUE TITLE
SignUp/SignIn Fails in Release build apk: com.amazonaws.amplify/auth_cognito: Failed to handle method call g.i: null cannot be cast to non-null type java.lang.reflect.Method

### ISSUE THREAD

**Issue by uttusharma** [aws-amplify/amplify-flutter#305]
**Bug**
Amplify fails to signup/sign-in on release build apk. 

**To Reproduce**
1. Configure Amplify like this
```
AmplifyAuthCognito auth = new AmplifyAuthCognito();
    amplify.addPlugin(authPlugins: [auth]);
    try {
      await amplify.configure(amplifyconfig);
      print('Successfully configured Amplify 🎉');
    } catch (e) {
      print('Could not configure Amplify ☠️');
      print(e);
    }
```
2. Code to execute 
```
final SignUpResult res = await Amplify.Auth.signUp(
            username: event.email,
            password: event.pass,
            options: CognitoSignUpOptions(userAttributes: userAttributes));
 ```

3. Now run ```flutter build apk --release``` or Generate Signed Release build apk.  **Note:** Don't run ``` flutter run --release``` as it works fine with that.
4. Now run the release apk on the device and in the adb logcat you'll see 
```
 2021-01-10 23:51:24.645 29270-29270/?  E/MethodChannel#com.amazonaws.amplify/auth_cognito: Failed to handle method call
    g.i: null cannot be cast to non-null type java.lang.reflect.Method
        at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterSignUpRequest.b(Unknown Source:203)
        at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterSignUpRequest.<init>(Unknown Source:90)
        at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.w(Unknown Source:10)
        at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.h(Unknown Source:150)
        at f.a.d.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:170)
        at android.app.ActivityThread.main(ActivityThread.java:7055)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
```

**Expected behavior**
To Signup/ Sign in

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
 - Device: Oneplus 7t
 - OS: Android 11

**Additional context**
I didn't touched amplifyconfigration.dart file.
**amplifyconfiguration.dart**
xxxxx = Obscure

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-south-1:xxxxx",
                            "Region": "ap-south-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-south-1xxxxx",
                        "AppClientId": "xxxxx",
                        "AppClientSecret": "xxxxx",
                        "Region": "ap-south-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}''';
```
 This issue will not appear when 
```flutter run --release``` is used,
only when ```flutter build apk --release``` is used.
package version: 
```
amplify_auth_cognito: ^0.0.1-dev.6
  amplify_core: ^0.0.1-dev.6
```
I am properly signing apk no issue with that.
Flutter version I am using:
```
Flutter 1.22.5 • channel stable
```

**Comment by uttusharma** [comment]
### Update
If this official guide is followed [Signing APK -Flutter](https://flutter.dev/docs/deployment/android#signing-the-app)
and then If you run `flutter build apk --release` 
Then the above issue occurs at the time of Sign up with cognito.

**Workaround**

1. Open android module in android studio.
2. Set build variant to release
3. Goto `Build > Generate signed bundle/Apk `
4. Select option `Build Variant : release` & `Signature version : v2` 

**Other workaround**
Configure signing for your app by editing the `<app dir>/android/app/build.gradle` file.
```
   signingConfigs {
        config {
            storeFile file('D:\\flutterapp\\android\\app\\key.jks')
            storePassword 'yourpassword'
            keyAlias 'key0'
            keyPassword 'yourpassword'
        }
    }
```

**Comment by uttusharma** [comment]
> This issue will not appear when
> flutter run --release is used,
> only when flutter build apk --release is used.

So when I run with `flutter run --release`  what happens is that amplify is compiled in debug mode. How do I know this? Well when I shake the device It will bring up Amplify developer menu. As I said the problem exists only in the release build, not in Debug that is why It is hard to detect.

**Comment by uttusharma** [comment]
> Hi @uttusharma thank you for providing this detailed explanation of the issue and solution! Was curious why you couldn't run "flutter run --release" instead?
> 
> > This issue will not appear when
> > flutter run --release is used,
> > only when flutter build apk --release is used.
> > package version:

Thank you for responding. Well, when I test signup on `flutter run --release` I am able to signup and no issue occurs everything works fine. 
when I try to use the release build apk generated by  `flutter build apk --release`   Signup fails and an exception is thrown as can be seen in adb log

**Comment by brunovsiqueira** [comment]
Same problem was happening to me and I fixed by adding --no-shrink to the build command. @uttusharma please try "flutter build apk --no-shrink" and let me know if it works for you.

**Comment by uttusharma** [comment]
> Same problem was happening to me and I fixed by adding --no-shrink to the build command. @uttusharma please try "flutter build apk --no-shrink" and let me know if it works for you.

This works. 

So that means R8 Shrinking is causing this issue. That also explains why `flutter run  --release` works because R8 shrinking is happening only when `flutter build apk` is run.

Another way to disable R8 shrinking in android app is to add the following: 
``` android {
    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled false

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources false
        }
    }
    ...
}```

**Comment by haverchuck** [comment]
@uttusharma I have just tested the latest version of amplify-flutter (not yet released) and did not have any issues installing and running the release .apk on an emulator (signup/signin worked as expected).

Are you seeing this behavior on emulators, or only on physical devices?

**Comment by uttusharma** [comment]
>Are you seeing this behavior on emulators, or only on physical devices?

We are seeing this behavior on the physical devices only.

**Comment by Amplifiyer** [comment]
@uttusharma are you still experiencing this issue `on 0.0.2-dev.2` version of the library?

**Comment by uttusharma** [comment]
> 0.0.2-dev.2

I haven't tested this on 0.0.2-dev.2 yet

**Comment by uttusharma** [comment]
> @uttusharma are you still experiencing this issue `on 0.0.2-dev.2` version of the library?

I just tested on `0.1.0` version **issue still persists**.


``` 
  amplify_flutter: ^0.1.0
  amplify_auth_cognito: ^0.1.0
  amplify_core: ^0.1.0
```

**Comment by uttusharma** [comment]
Thanks for your support!🙏
Issue is resolved 🎉
