### ISSUE TITLE
Exception while login to flutter android  application "QueryResult(source: QueryResultSource.network, data: null, context: Context({}), exception: OperationException(linkException: UnknownException(AuthException(message: Fetching user attributes failed., recoverySuggestion: See attached exception for more details., underlyingException: java.lang.Exception: Operation requires a signed-in state)"

### ISSUE THREAD

**Issue by prakash2596** [aws-amplify/amplify-flutter#3052]
### Description

We were working on the flutter app for both Android and iOS, login purpose we are using the AWS library, it's working in iOS, but not able to login in to Android showing this exception "QueryResult(source: QueryResultSource.network, data: null, context: Context({}), exception: OperationException(link exception: UnknownException(AuthException(message: Fetching user attributes failed., recoverySuggestion: See attached exception for more details., underlying exception: java.lang.Exception: Operation requires a signed-in state)" in android app, call the sign in function,

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Screenshots

![Screenshot from 2023-05-16 12-24-13](https://github.com/aws-amplify/amplify-flutter/assets/95601891/951744cf-baf7-453c-a246-02e09892131f)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

### Schema

```GraphQL
const amplifyconfig = '''
 {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:********",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-2_********",
                        "AppClientId": "***********",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Comment by NikaHsn** [comment]
@prakash2596 thanks for reporting this issue. 
- would please confirm if this is an issue with API (GraphQL) category or Auth?  
- if this is reproducable and what are the steps to reproduce it?

**Comment by Jordan-Nelson** [comment]
@prakash2596 - Please let us know if you are unable to upgrade, or if upgrading does not resolve the issue. Thanks.

**Comment by Jordan-Nelson** [comment]
I am going to close this out since we have not heard back. Let us know if you are still experiencing this issue.
