### ISSUE TITLE
DataStore Items Duplicates

### ISSUE THREAD

**Issue by nesimventures** [aws-amplify/amplify-flutter#3054]
### Description

Hello,

I don't know if I'm missing something here but when working with Amplify.DataStore and I preform the following procedures I'm getting duplicates in DDB.

1: `Amplify.DataStore.save(ModelA)` 
2: `Amplify.DataStore.clear()` or simply deleted the application and reinstall it again which is a manual way of deleting the items stored locally.
3: Then `Amplify.query(ModelA.Type, where ModelA.EMAIL.eq(email)` return empty list.

Now I know that Amplify.DataStore interact with local and remote database and with ' Amplify.DataStore.clear()' it only clears the local database. However why when I do  `Amplify.query(ModelA.Type, where ModelA.EMAIL.eq(email)` its not querying the remote DDB if it can't find it locally.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by nesimventures** [comment]
Hi @NikaHsn,
Alright,  lets say you created an item and you saved it using the following code `Amplify.DataStore.save(item)` now this item will be stored locally and remotely. Next, if  you want to clear this item locally for any reason such as the user has signed out you will use `Amplify.DataStore.clear()` which clears all items saved locally. Now, so far the item still exists on the remote cloud (DDB Table) but then the user signs in again and tries to fetch the item using `Amplify.DataStore.query(Model.Type, where: ...)` this returns empty list because the item doesn't exist locally anymore. Now my question is why its not fetching from the remote cloud if it can't find it locally? The reason why I'm getting duplicate is because when I fetch the item and I get empty list I'm recreating the item again. Hopefully this make sense :)

**Comment by NikaHsn** [comment]
@nesimventures Thanks for clarification. `Amplify.DataStore.clear()` stops datastore sync process. `Amplify.DataStore.query()` starts datastore sync automatically but returns the local data immediately without waiting for sync to complete. 
for your case you need to wait for the sync to complete before querying. So one option is to call start(), wait for the sync to complete, and then query. Another option is to use `observeQuery` and `isSynced` status similar to this code sample:
`final myData = await observeQuery(...).firstWhere((snapshot) => snapshot.isSynced);`

**Comment by nesimventures** [comment]
@NikaHsn I have tried what you suggested but I'm still getting an empty list even though the value of `isSynced` was true.  I also want to add that after the first query everything start working normal and its able to query the data from the remote cloud. So I agree with you that the sync is not complete yet but what I don't understand is why `isSynced` returning true. Here is a snippet of the code I'm using.
<img width="681" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/130711003/14401252-6b26-4ce5-8779-517684568c36">
<img width="365" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/130711003/6aa3c6fc-d324-4c35-96dc-f3e4e04e1466">

By the way after the first query or after some time when the actual sync is complete. the query is returning all the items in DDB Table, by all the items I mean the duplicates that got created because the first query returned an empty list. I also tried `Amplify.DataStore.start()` it didn't make any difference, since when I do `Amplify.DataStore.observeQuery` it should automatically  start `Sync`.  [I'm following this Doc](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/flutter/#start)

**Comment by Jordan-Nelson** [comment]
@nesimventures it appears that the value of `isSynced` is not resetting to false after calling clear. I have opened [a bug for this](https://github.com/aws-amplify/amplify-flutter/issues/3113).

Another way to achieve this would be to wait for the ready event.

```dart
await Amplify.DataStore.clear();
await Amplify.DataStore.start();
await Amplify.Hub.availableStreams[HubChannel.DataStore]!
    .firstWhere((event) => event.eventName == "ready");
final items = await Amplify.DataStore.query(Todo.classType);
```

**Comment by Jordan-Nelson** [comment]
@nesimventures - I am going to close this out since i believe your question has been answered and we have an issue opened to track the bug in observeQuery. Please let us know if you have further questions.
