### ISSUE TITLE
delete failed, mix primarykey with GSI

### ISSUE THREAD

**Issue by jamontesg** [aws-amplify/amplify-flutter#3056]
### Description

Delete a record  in a table  with  a simple  primarykey, works  fine. I was succesfull delete records from "User" table.
But my table "Item" has  a primaryKey  (key: tenanid , sort: id) and has a GSI (key: location,  sort: ck).
ck field is a composite field.

delete trought  Appsync on "Item" table works  ok.
delete a record with datastore in "Item" table  generate this error:

```
GraphQLResponseException{message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=SerializedModel{id='"la escondida"#"group#ordeñoid#0688ebe3-7b7f-4250-9153-fef7ce447f80"', serializedData={eid=null, color=black, death=null, gender=male, document=null, description=null, createdAt=2023-05-11T20:59:29.924000000Z, dam=null, weaned=null, alias=null, id=0688ebe3-7b7f-4250-9153-fef7ce447f80, event=null, altaid=leonard, lastOwner=null, group=ordeño, updatedAt=2023-05-11T20:59:29.924000000Z, letag=null, image=null, cost=null, ck=group#ordeñoid#0688ebe3-7b7f-4250-9153-fef7ce447f80, birth=2023-05-05, weight=null, breed=angus rojo, market=null, retag=null, name=cohen, tenantId=0d2b2e7d-724f-46b6-8bf8-87ab663a6165, location=la escondida, sire=null, aid=999, status=normal}, modelName=Item}, mutationType=DELETE, mutationId=e7abce52-f45f-11ed-96c9-35aea47d06e0, predicate=MatchAllQueryPredicate}. AppSync response contained errors = [GraphQLResponse.Error{message='The variables input contains a field that is not defined for input object type 'DeleteItemInput' ', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='The variables input contains a field that is not defined for input object type 'DeleteItemInput' ', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
```

this is  selected record of "Item" to delete:

```
{
  "tenantId": {
    "S": "0d2b2e7d-724f-46b6-8bf8-87ab663a6165"
  },
  "id": {
    "S": "0688ebe3-7b7f-4250-9153-fef7ce447f80"
  },
  "aid": {
    "S": "999"
  },
  "alias": {
    "NULL": true
  },
  "altaid": {
    "S": "leonard"
  },
  "birth": {
    "S": "2023-05-05"
  },
  "ck": {
    "S": "group#ordeñoid#0688ebe3-7b7f-4250-9153-fef7ce447f80"
  },
  "createdAt": {
    "S": "2023-05-11T20:59:29.924Z"
  },
  "description": {
    "NULL": true
  },
  "group": {
    "S": "ordeño"
  },
  "location": {
    "S": "la escondida"
  },
  "name": {
    "S": "cohen"
  },
  "status": {
    "S": "normal"
  },
  "updatedAt": {
    "S": "2023-05-11T20:59:29.924Z"
  },
  "weight": {
    "NULL": true
  },
  "_lastChangedAt": {
    "N": "1683838769948"
  },
  "_version": {
    "N": "1"
  },
  "__typename": {
    "S": "Item"
  }
}
```

I believe datastore try to delete using GIS , and not primary key.
the value extracted for the id , from the log. corresponds to the "ck" field and not to the "id" field (mixing)

"PendingMutation{mutatedItem=SerializedModel{id='"la escondida"#"group#ordeñoid#0688ebe3-7b7f-4250-9153-fef7ce447f80" 

id i

This is my  delete  function:

```dart
Future<void> deleteItem(Item itm) async {
    final itemDelete = (await Amplify.DataStore.query(
      Item.classType,
      where: Item.TENANTID.eq(itm.tenantId).and(Item.ID.eq(itm.id)),
    ))
        .first;
    try {
      developer.log(itm.toString());
      await Amplify.DataStore.delete(itemDelete);
      
    } catch (e) {
      if (e.toString().contains('outboxMutationFailed')) {
        
      } else {
        developer.log('Error deleting datastore element: ${e.toString()}');
      }
    }
  }
```

Kind Regards

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

12.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Tenant @model @auth(rules: [{ allow: groups, groups: ["Admin","Manager"], operations: [create, update,read]  }]) {
  id: ID! @primaryKey  
  name: String!
  description: String
 
}

type User @model @auth(rules: [{ allow: groups, groups: ["Admin","Manager"], operations: [create, update,read,delete] }]) {
  id: ID! @primaryKey (sortKeyFields: ["tenantid"])
  tenantid: ID! 
  name: String!
  surname: String
  email: String!
  image: String
  status: String
  profile: Profile!

}

type Item @model 
@auth(rules: [{ allow: groups, groups: ["Admin","Manager"], operations: [create, update,read,delete] }])
 {
  tenantId: ID! @primaryKey(sortKeyFields: ["id"])  
  id: ID!  
  
  location: String! @index(sortKeyFields: ["ck"])  
  group: String!
  
  ck: String!

  aid: String
  altaid: String
  alias: String
  name: String
  description: String
  birth: AWSDate
 

  weight: [Weight]
  status: ItemStatus!
    
}

type Weight {
  date: AWSDateTime!
  value : Float!
  image: S3Object
  latitude:  Float
  longitude:  Float
}


enum ItemStatus {
  normal
  sold
  lost
  delete
}

enum Profile {
  admin
  adminti
  support
  manager
  api
  operative
  guest
}
```

**Comment by Jordan-Nelson** [comment]
@jamontesg - I was able to create a minimal repro of this on both iOS and Android. It seems like DataStore does not correctly handle the index with a sort key. I will need to check to see if this is intended to be supported in DataStore.

Is this an existing schema that you are trying to use within Amplify DataStore?

Below is the schema I used for a minimal repro.

```graphql
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type Item @model {
  id: ID!
  name: String!
  location: String! @index(sortKeyFields: ["ck"])
  ck: String!
}

```

Below is the code that I used to repro this. Simply adding an Item and then deleting it will cause the our box mutation error.

<details>

```dart
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';
import 'models/ModelProvider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _items = <Item>[];

  Future<void> _configureAmplify() async {
    if (Amplify.isConfigured) return;
    try {
      await Amplify.addPlugins([
        AmplifyAPI(),
        AmplifyDataStore(modelProvider: ModelProvider.instance),
      ]);
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      safePrint('Already configured.');
    }

    final snapshot = await Amplify.DataStore.observeQuery(
      Item.classType,
    ).firstWhere((snapshot) => snapshot.isSynced);
    setState(() => _items.addAll(snapshot.items));
  }

  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  Future<void> addItem() async {
    final item = Item(
      name: 'item ${_items.length + 1}',
      // location: 'location',
      // ck: '1234',
      location: uuid(),
      ck: uuid(),
    );
    await Amplify.DataStore.save(item);
    setState(() => _items.add(item));
    safePrint('item saved!');
  }

  Future<void> deleteItem() async {
    final toDelete = (await Amplify.DataStore.query(Item.classType)).first;
    safePrint(toDelete.toString());
    await Amplify.DataStore.delete(toDelete);
    setState(() => _items.removeWhere((item) => item == toDelete));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  FilledButton(
                    onPressed: addItem,
                    child: const Text('Add item'),
                  ),
                  FilledButton(
                    onPressed: deleteItem,
                    child: const Text('delete item'),
                  ),
                ],
              ),
            ),
            for (final item in _items) ListTile(title: Text(item.name))
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by jamontesg** [comment]
@Jordan-Nelson  any news about that  issue ?

**Comment by Jordan-Nelson** [comment]
@jamontesg if you are still facing this issue can you please share some details about your use case and let me know if this is an existing schema that you are trying to use with DataStore?

**Comment by jamontesg** [comment]
Hi @Jordan-Nelson , yes i still have this issue.
my Schema is a  new one.

type Itemdo @model 
@auth(rules: [
  { allow: groups, groups: ["Admin","AdminTi","Support","Manager"], operations: [create, update,read,delete]  }
  { allow: groups, groups: ["Api","Operative"], operations: [create, read]  }
  { allow: groups, groups: ["Guest"], operations: [read]  }
  ])
 {
  tenantId: ID! @primaryKey(sortKeyFields: ["id"])  
  id: ID!  
  location: String! @index(sortKeyFields: ["ck"])  
  group: String!
  ck: String!
  aid: String
  }

and the error continues ---> **The variables input contains a field that is not defined for input object type 'DeleteItemdoInput'**
I try  to  delete  unsuccessfully with custom GraphQL  query/mutation but need  field _version (this field is not available).

I am trying to use  a schema  like  this
![image](https://github.com/aws-amplify/amplify-flutter/assets/16964566/e73342fb-1794-4a12-8647-33dd7a5c6afc)

**Comment by Jordan-Nelson** [comment]
@jamontesg are you hoping to use DataStore and GraphQL together in the same app? If you are only using DataStore, can you explain what you are hoping to achieve with sortKeyFields?

**Comment by jamontesg** [comment]
@jordan My idea  is only use Datastore.  I am following  this  design.

https://www.alexdebrie.com/posts/dynamodb-one-to-many/
"Secondary index + the Query API action."

sort keys are used for  filtering a schema with  one-to-many relationships .

Can you think of another approach?
Kind Regards

**Comment by Jordan-Nelson** [comment]
@jamontesg that blog outlines how to model your data to efficiently support very specific data access patterns. It provides examples of how to efficiently query data from dynamo.

When using DataStore, data is synced to the device and stored in SQLite. The queries you run are run against the local SQLite database, not dynamo.

If you want to have fine control over your data access patterns, you might find that using the GraphQL API category directly makes more sense.

If you want to use DataStore, you can likely find a way to query the data from the local store. However I am not sure I understand what you are hoping to achieve. It's possible that query predicates and sorts will allow you to achieve your use case. See the docs here: https://docs.amplify.aws/lib/datastore/data-access/q/platform/flutter/#query-data

**Comment by jamontesg** [comment]
Thanks @Jordan-Nelson, very usefull  your answer. 
With that schema,   datastore  works  fine.   only  has that issue  on  delete case in this table.  I am  going  to  do this operation with appsync. I am in love with datastore,
Kind regards
