### ISSUE TITLE
Access token not refreshing on Android

### ISSUE THREAD

**Issue by adamtester** [aws-amplify/amplify-flutter#3057]
## NOTE
I experienced this issue last night, but now trying this morning the token refreshed... I will try and reproduce the issue, but now I'm wondering if this is due to Flutter hot-restart disabling refresh?

Also, seems to be related issues over on amplify-android: 
- https://github.com/aws-amplify/amplify-android/issues/2380
- https://github.com/aws-amplify/amplify-android/issues/1763
- https://github.com/aws-amplify/amplify-android/issues/2224
- https://github.com/aws-amplify/amplify-android/issues/1798
- https://github.com/aws-amplify/amplify-android/issues/1763

### Description

Hello I have run into the same issue as https://github.com/aws-amplify/amplify-flutter/issues/186, I'm using Cognito (email if that helps) and the tokens aren't refreshing.

Here is a snippet of code:
```dart
  Future<List<Project>> load() async {
    var auth = await Amplify.Auth.fetchAuthSession();
    var user = await Amplify.Auth.getCurrentUser();
    safePrint(auth);
    safePrint(user);

    if (Amplify.isConfigured) {
      safePrint('Amplify is configured');
    } else {
      safePrint('Amplify is NOT configured');
      return [];
    }

    try {
      List<Project> projects = [];

      final request = ModelQueries.list(Project.classType);
      final response = await Amplify.API.query(request: request).response;
...
```

The console output is:
```
I/flutter (29471): {
I/flutter (29471):   "isSignedIn": true,
I/flutter (29471):   "userSub": "AWSSuccessResult<String, AuthException> {\n  \"value\": \"5c79fc58-xxx-f3476c7feeb6\"\n}",
I/flutter (29471):   "userPoolTokens": "AWSSuccessResult<CognitoUserPoolTokens, AuthException> {\n  \"value\": {\n    \"signInMethod\": \"default$\",\n    \"accessToken\": \"eytokenhere
I/flutter (29471): CognitoAuthUser {
I/flutter (29471):   "userId": "5c79fc58-xxx-f3476c7feeb6",
I/flutter (29471):   "username": "5c79fc58-xxx-f3476c7feeb6",
I/flutter (29471):   "signInDetails": {
I/flutter (29471):     "signInType": "apiBased",
I/flutter (29471):     "username": "xxx@gmail.com",
I/flutter (29471):     "authFlowType": "USER_SRP_AUTH"
I/flutter (29471):   }
I/flutter (29471): }
I/flutter (29471): Amplify is configured
I/flutter (29471): query
I/flutter (29471): GraphQLResponse<PaginatedResult<Project>> error: [
I/flutter (29471):   {
I/flutter (29471):     "message": "Token has expired.",
I/flutter (29471):     "errorType": "UnauthorizedException"
I/flutter (29471):   }
I/flutter (29471): ]
```

I decoded that JWT and it has indeed expired.

Pubspec
```
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_api: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_storage_s3: ^1.0.0
```

I'm using the Authenticator UI. This is testing on Android in a simulator, I'll try iOS and report back if the issue is there too.

Let me know if I can provide more info!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

- Create new flutter app
- Install amplify packages
- Set up Cognito and API Backend (1 hour token time)
- Add Authenticator UI
- Add a GraphQL Query
- Wait 1 hour
- Run GraphQL Query, see token expired message

### Screenshots

<img width="781" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/2249484/9b446757-c6b8-4e05-87aa-bf74978e5d43">

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by adamtester** [comment]
I have a question about how the tokens work, do they get refreshed automatically even if no calls are made using a timer?
Or are they refreshed "just in time" before an API call?

**Comment by Jordan-Nelson** [comment]
Can you reproduce this on a physical Android device?

**Comment by adamtester** [comment]
> Can you reproduce this on a physical Android device?

Now this is interesting, just spent about 30 minutes testing on a real device (USB to Android Studio, including hot reloading and restarting) and I cannot reproduce!

I'll keep testing throughout today and let you know if I can break it there, if I can't I guess it isn't really a major problem as real users won't see it.

I'm not familiar enough with Android to understand the difference in environments

**Comment by Jordan-Nelson** [comment]
Does your emulator show the correct date and time if you check in Settings > System > Date & time ?

<img width="591" alt="Screenshot 2023-05-17 at 11 18 53 AM" src="https://github.com/aws-amplify/amplify-flutter/assets/20613561/9b3e5ea2-c96f-471d-bdbb-a3fd30af5f17">

**Comment by adamtester** [comment]
@Jordan-Nelson I think you've cracked it...

<img width="782" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/2249484/304c0138-c13e-491a-b0be-967c474b91e4">

I've not been restarting the simulator when my mac goes to sleep! Restarting it works, however I have a follow up question, I'm using the Authenticator package to show the login screen, so in this case why does the app not redirect back to the login screen? Is it because the refresh token is still valid?

Thanks for your help, I'll close the issue!

**Comment by Jordan-Nelson** [comment]
The Authenticator will redirect back to login when the access/id and refresh tokens have all expired. In this case the refresh token is likely still valid and the Auth library still thinks the access/id tokens are still valid because the system time is off.
