### ISSUE TITLE
Error: 'UserProfile' is imported from both 'package:amplify_core/src/types/analytics/analytics/user_profile.dart' and [...]

### ISSUE THREAD

**Issue by xonaman** [aws-amplify/amplify-flutter#3070]
### Description

Since upgrading to 
```yaml
amplify_flutter: ^1.0.1
amplify_auth_cognito: ^1.0.1
amplify_storage_s3: ^1.0.1
amplify_api: ^1.0.1
```
I receive the following error on build:
```
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           141.4s
Failed to build iOS app
Error (Xcode): lib/models/Claim.dart:23:1: Error: 'UserProfile' is imported from both 'package:amplify_core/src/types/analytics/analytics/user_profile.dart' and 'package:remonon/models/UserProfile.dart'.
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```
This is because one of my models is actually named `UserProfile`. I temporarily fixed this by changing
```dart
import 'package:amplify_core/amplify_core.dart';
```
to 
```dart
import 'package:amplify_core/amplify_core.dart' hide UserProfile;
```
in all affected files. Is there any better way to do this without having to rename my model? I want to avoid making this change every single time I am auto-generating my models again due to a change in my schema. 

Many thanks in advance!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
Maybe duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2889? Do you mind having a look at the [workaround](https://github.com/aws-amplify/amplify-flutter/issues/2889#issuecomment-1512121296) there and seeing if helpful?

**Comment by xonaman** [comment]
As stated in the description, yes I did and yes it works. My question was if there is a more elegant way to fix this.

**Comment by xonaman** [comment]
I see in the issue you mentioned that someone has created a pull request which solves the issue without having to use the workaround. Hope it will be available on pub soon!

**Comment by ragingsquirrel3** [comment]
Yep, there is a fix in the codegen that will be available in a future version of the CLI. Sorry there isn't something more elegant to fix at the moment.

**Comment by xonaman** [comment]
@ragingsquirrel3 No, that’s okay, I am totally fine with using the temporary workaround until then. Thank you for your help!
