### ISSUE TITLE
Execution failed for task ':amplify_flutter_android:compileDebugKotlin'

### ISSUE THREAD

**Issue by jack24254029** [aws-amplify/amplify-flutter#3071]
### Description

Error Message:
```
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.0/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt: (36, 7): Redeclaration: Amplify
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.0/android/src/main/kotlin/com/amazonaws/amplify/Latch.kt: (14, 8): Redeclaration: Latch
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.0/android/src/main/kotlin/com/amazonaws/amplify/exception/ExceptionUtil.kt: (19, 7): Redeclaration: ExceptionUtil
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.0/android/src/main/kotlin/com/amazonaws/amplify/exception/ExceptionUtil.kt: (96, 7): Redeclaration: ThrowableSerializer
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.1/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt: (34, 7): Redeclaration: Amplify
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.1/android/src/main/kotlin/com/amazonaws/amplify/Latch.kt: (14, 8): Redeclaration: Latch
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.1/android/src/main/kotlin/com/amazonaws/amplify/exception/ExceptionUtil.kt: (18, 7): Redeclaration: ExceptionUtil
e: /Users/user_name/.pub-cache/hosted/pub.dev/amplify_flutter_android-1.0.1/android/src/main/kotlin/com/amazonaws/amplify/exception/ExceptionUtil.kt: (94, 7): Redeclaration: ThrowableSerializer
```

I didn't see the change log of `1.0.1`.
Is it be hideen?

![image](https://github.com/aws-amplify/amplify-flutter/assets/13265628/4a2fd6a5-598b-4781-a3a9-08f6214b7d4a)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.1

### Deployment Method

Custom Pipeline

**Comment by Jordan-Nelson** [comment]
Hello - do believe the change log for v1.0.1 was accidentally overwritten during the v1.1.0 release. You can see the 1.0.1 change log here: https://github.com/aws-amplify/amplify-flutter/commit/d4c05d6f69e453c8b81a3bd50c9c70df4d103ca3

The error message is showing files from v1.0.0 and v1.0.1. Can you confirm you are only depending on v1.0.1?

Can you run flutter clean and then rebuild?

**Comment by jack24254029** [comment]
I had try to flutter clean and rebuild on last week, and it didn't work.
I am trying again now and it is working.

**Comment by Jordan-Nelson** [comment]
@jack24254029 I will close this issue as it sounds like everything is working now. If you continue to see this in the future, please let us know.
