### ISSUE TITLE
I checked that other amplify-swift and amplify-js are now supporting lazy loading models but amplify-flutter still lacks this support , please let me know whats the current status for this ?

### ISSUE THREAD

**Issue by amitvrm036** [aws-amplify/amplify-flutter#3072]
@HuiSF I checked that other amplify-swift and amplify-js are now supporting lazy loading models but amplify-flutter still lacks this support , please let me know whats the current status for this ?

_Originally posted by @amitvrm036 in https://github.com/aws-amplify/amplify-flutter/issues/914#issuecomment-1554532250_

**Comment by ragingsquirrel3** [comment]
We are tracking lazy/nested models in https://github.com/aws-amplify/amplify-flutter/issues/1449 and will post updates there while we work on this. I'm going to close this issue as a duplicate.
