### ISSUE TITLE
additionalAuthTypes ignored in amplifyconfiguration.dart

### ISSUE THREAD

**Issue by 0xAPPA** [aws-amplify/amplify-flutter#3075]
### Description

Although I configured [multiple authorization modes](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes) via `amplify update api` the changes are not reflected in _amplifyconfiguration.dart_. 

```json
{
  "version": 1,
  "serviceConfiguration": {
    "apiName": "my-api",
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "AMAZON_COGNITO_USER_POOLS",
      "cognitoUserPoolId": "auth-api"
    },
    "additionalAuthTypes": [
      {
        "mode": "AWS_IAM"
      }
    ],
    "conflictResolution": {
      "defaultResolutionStrategy": {
        "type": "AUTOMERGE"
      }
    }
  }
}
```

**Current Result**
```json
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "my-api": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://foobar.appsync-api.eu-central-1.amazonaws.com/graphql",
                    "region": "eu-central-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
```

**Expected Result**
```json
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "my-api": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://foobar.appsync-api.eu-central-1.amazonaws.com/graphql",
                    "region": "eu-central-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "my-api-iam": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://foobar.appsync-api.eu-central-1.amazonaws.com/graphql",
                    "region": "eu-central-1",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
```

Manual changes made to _amplifyconfiguration.dart_ are overwritten on every `amplify pull` or `amplify mock api`.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
@0xAPPA I'm having a look at the CLI now, but just wanted to point out you can use the `authorizationMode` property of a `GraphQLRequest` if you want to specify an auth mode for a request so you don not have to bother with friendly names / `apiName` for this use case.

**Comment by 0xAPPA** [comment]
@ragingsquirrel3 thank you for the quick response. Your hint actually solved my issue. Before v1 it was necessary to have two entries in api section of `amplifyconfiguration.json` in order to have different `apiNames` and therefore, being able to send requests with different auth modes. `authorizationMode` makes it much easier and the second entry in the api section is obsolete.

**Comment by ragingsquirrel3** [comment]
Glad you got that working for this use case. I'm going to close this issue as I believe the issue with the CLI/friendly names is either a problem with the docs or the CLI and not amplify-flutter.
