### ISSUE TITLE
Reset Password verification code send on phone number when username is email.

### ISSUE THREAD

**Issue by VishalMakwana20** [aws-amplify/amplify-flutter#3085]
### Description

How can I send the verification code on phone number when username set to email ? User is signup via email/password and phone number as user attribute added. 
Now whenever I am trying to forget password then verification code send on email. I want to send the verification code on mobile number. How can I achieve this. 

**Note : MFA is set as optional in cognito because of my requirements.**

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@VishalMakwana20 - I am going to close this out since I believe your question has been answered. Please let me know if you have further questions.
