### ISSUE TITLE
xml Dependency upgrade 

### ISSUE THREAD

**Issue by sanket2798** [aws-amplify/amplify-flutter#3098]
### Description

getting this error 

Because flutter_svg >=2.0.6 depends on vector_graphics_compiler ^1.1.6 which depends on xml ^6.3.0, flutter_svg >=2.0.6 requires xml ^6.3.0.
And because smithy_aws 0.5.0 depends on xml >=6.1.0 <=6.2.2 and no versions of smithy_aws match >0.5.0 <0.6.0, flutter_svg >=2.0.6 is incompatible with smithy_aws ^0.5.0.
So, because app depends on both smithy_aws ^0.5.0 and flutter_svg ^2.0.6, version solving failed.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [x] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Thanks for bringing this to our attention and apologies for the dependency mismatch. We've fixed this in https://github.com/aws-amplify/amplify-flutter/pull/3088 and will release this shortly. In the meantime, feel free to set a dependency override as such:

```yaml
dependency_overrides:
  xml: ^6.3.0
```

**Comment by dnys1** [comment]
The fix for this has been released.
