### ISSUE TITLE
Failed to upload image on s3 bucket

### ISSUE THREAD

**Issue by jvnieva** [aws-amplify/amplify-flutter#3105]
### Description

Im trying to upload image using emulator. i already have internet connection and added the permissions  `<uses-permission android:name="android.permission.INTERNET"/>` and `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` on the `AndroidManifest.xml` file (main, debug and profile) but still getting this error:
 `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AmplifyException {
E/flutter ( 5030):   "message": "The request failed due to a network error.",
E/flutter ( 5030):   "recoverySuggestion": "Ensure that you have an active network connection",
E/flutter ( 5030):   "underlyingException": "PUT https://dev.xxxxx.xxxxx.com.s3.ap-southeast-1.amazonaws.com/public/PNG_transparency_demonstration_1.png?x-id=PutObject failed: HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))"`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

1. go to VS code, run the app using emulator API 28
2. click on the upload button
3. select image to upload (png format)
4. upload selected image
5. Upload error: `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AmplifyException {
E/flutter ( 5030):   "message": "The request failed due to a network error.",
E/flutter ( 5030):   "recoverySuggestion": "Ensure that you have an active network connection",
E/flutter ( 5030):   "underlyingException": "PUT https://dev.xxxxx.xxxxx.com.s3.ap-southeast-1.amazonaws.com/public/PNG_transparency_demonstration_1.png?x-id=PutObject failed: HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))"`

### Screenshots

![Screenshot 2023-05-25 110637](https://github.com/aws-amplify/amplify-flutter/assets/38002184/4a730229-2959-4336-ae3f-0fb86a33b1f2)
![image](https://github.com/aws-amplify/amplify-flutter/assets/38002184/e74a492a-1168-4cb1-80c7-59875c37f73e)
![image](https://github.com/aws-amplify/amplify-flutter/assets/38002184/d9057b1d-efd3-429e-8fa5-37e999afcf09)

### Platforms

- [ ] iOS
- [X] Android
- [x] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by jvnieva** [comment]
yes, I already tried to run it also in new created emulator and also in my physical device. same issue.

**Comment by jvnieva** [comment]
I also tried to use different network connection still the same error message

**Comment by Equartey** [comment]
Hey @jvnieva 

Thanks for the context. 

Can you share your amplify config (you can remove any sensitive or app specific info such as API keys or app IDs)?

Was this project's backend generated with the Amplify CLI?

**Comment by jvnieva** [comment]
### Amplify config
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/1.0.0",
                "Version": "1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-xxxxx",
                            "Region": "ap-southeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1_xxxx",
                        "AppClientId": "xxxxx",
                        "AppClientSecret": "xxxx",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "dev.xxx.xxx.xxx",
                        "Region": "ap-southeast-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "dev.xxx.xxx.xxx",
                "region": "ap-southeast-1",
                "defaultAccessLevel": "guest"
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "social-cognito": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxx.appsync-api.ap-southeast-1.amazonaws.com/graphql",
                    "region": "ap-southeast-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "social-lambda": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxx.appsync-api.ap-southeast-1.amazonaws.com/graphql",
                    "region": "ap-southeast-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }

**Comment by jvnieva** [comment]
im not using backend generated Amplify CLI
