### ISSUE TITLE
iOS returns UUID string instead of username when retrieving `AuthUser().username`

### ISSUE THREAD

**Issue by graphicbeacon** [aws-amplify/amplify-flutter#311]
**Describe the bug**
The `username` field on the `AuthUser` object returns a UUID string on iOS instead of the expected username.

**To Reproduce**
Sign in a user and print out the `username` field on `AuthUser` object:

```dart
// Android
_user.username; // testamp2@mailinator.com ✅
_user.uid; // 36f36cd4-0354-4ea0-a277-17e389cc4392

// iOS
_user.username; // 36f36cd4-0354-4ea0-a277-17e389cc4392 ❌
_user.uid; // 36f36cd4-0354-4ea0-a277-17e389cc4392
```

**Expected behavior**
It should log out the correct username, in this case `testamp2@mailinator.com`

**Screenshots**
**Android**
<img src="https://user-images.githubusercontent.com/2960965/105051537-c26cb400-5a66-11eb-87b1-0a5998f33b55.png" width="300" />

**iOS**
<img src="https://user-images.githubusercontent.com/2960965/105051518-bda80000-5a66-11eb-873c-84ba8ad01a5b.png" width="300" />

**Platform**
This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
- Device: iPhone 12 Pro Max Simulator
- OS: iOS 14.3

**Additional context**
It appears that the UUID string is incorrectly assigned to `username` on iOS. This is happening with `amplify_auth_cognito` version **0.0.1-dev.6**.

**Comment by haverchuck** [comment]
@graphicbeacon This is an inconsistency between android and iOS which, I believe, only manifests when using an email/phone number as a username. We will begin investigating a solution.

**Comment by haverchuck** [comment]
https://github.com/aws-amplify/amplify-ios/issues/1029

**Comment by kjones** [comment]
Related: #201

**Comment by Amplifiyer** [comment]
Thanks @kjones resolving this in favor of #201 which is the same bug and also have a workaround for now. We will continue to update #201 with our findings and fixes.
