### ISSUE TITLE
Set owner field dynamically with Lambda on Post Confirmation trigger

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3120]
### Description

I've been following [this](https://aws.amazon.com/getting-started/hands-on/build-flutter-mobile-app-part-two/module-four/) tutorial to add a user to my UserProfile table in DataStore with a Post Confirmation Trigger.

The problem is when I set the owner field in my lambda:
```
    mutation MyMutation(
      $authID: String
      $birthDate: AWSDate
      $email: String
      $fullName: String
      $phoneNumber: AWSPhone
      $promoCode: String
      $owner: String!
    ) {
      createUserProfile(
        input: {
          id: $authID
          birthDate: $birthDate
          email: $email
          fullName: $fullName
          phoneNumber: $phoneNumber
          promoCode: $promoCode
          points: 0
          owner: $owner
        }
      ) {
        email
      }
    }
```
I get this error:
```
"Validation error of type WrongType: argument 'input' with value 'ObjectValue{objectFields=[ObjectField{name='id', value=VariableReference{name='id'}}, ObjectField{name='email', value=VariableReference{name='email'}}, ObjectField{name='owner', value=VariableReference{name='owner'}}]}' contains a field not in 'CreateUserProfileInput': 'owner' @ 'createUserProfile'"
```

Upon further investigation, I check my AppSync Console to check if the owner input field is present. I realized that it's not present in the input but is present if I wanted to query it.
![appsync](https://github.com/aws-amplify/amplify-flutter/assets/85061274/a4468954-521c-41dc-b1f1-46b026705ae0)

I want to mention that my user profile schema have  the following auth rules:
```
@auth(
    rules: [
      { allow: private, provider: iam }
      { allow: owner, operations: [read, update, create] }
    ]
  )
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create a user profile table with the auth rules set as:
```
@auth(
    rules: [
      { allow: private, provider: iam }
      { allow: owner, operations: [read, update, create] }
    ]
  )
```
2. Create  a post confirmation trigger to add a user profile to DataStore.
3. Set the owner field dynamically

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type UserProfile
  @model
  @auth(
    rules: [
      { allow: private, provider: iam }
      { allow: owner, operations: [read, update, create] }
    ]
  ) {
  id: ID!
  fullName: String
  phoneNumber: AWSPhone
  email: String
  birthDate: AWSDate
  promoCode: String
  points: Int
}
```

**Comment by jamilsaadeh97** [comment]
**UPDATE**
I manually added `owner: String` to my schema and now the user is saved to the database but I have two new issues.

1. When I see the user profile in DataStore, the owner field is only populated with the `username` even though in the request variables in my lambda, I set the owner field this way : `owner: `${event.request.userAttributes.sub}::${event.userName}`
2. When I use 
```dart
Amplify.DataStore.observeQuery(UserProfile.classType)
        .skipWhile((snapshot) => !snapshot.isSynced)
        .map((event) => event.items.single)
```
 no results is being returned.

**Comment by Equartey** [comment]
Hey @jamilsaadeh97 

Glad you were able to make some progress on this. Regarding your new issues:

1. Can you provide the output of the logger statement in the lambda event handler method?
2. Can you clarify what is not being return? Are you seeing snapshots? Are you seeing an empty items array?

**Comment by jamilsaadeh97** [comment]
Hi @Equartey , I apologize for the late answer.
I was checking it right now and it seems that it worked. I think I didn't wait long enough or it was some caching issue.

Thanks a lot!
