### ISSUE TITLE
iOS error: "There is already a user which is signed in. Please log out the user before calling showSignIn"

### ISSUE THREAD

**Issue by graphicbeacon** [aws-amplify/amplify-flutter#313]
**Describe the bug**
I'm getting the following exception whenever I stop a running iOS app with a signed in user and attempt signing in with the same user:

```
There is already a user which is signed in. Please log out the user before calling showSignIn
```
 
Not sure if this is expected functionality, however I thought I'd report it since it doesn't happen on Android.

**To Reproduce**
1. Start Flutter app in debug mode (Android Studio)
2. Sign in the user
3. Stop the app
4. Run the app again in debug mode
5. Attempt to sign in. It throws the exception message above.

**Expected behavior**
The earlier logged in state should be cleared. Current workaround I'm using is to invoke `Amplify.Auth.signOut()` and display a message asking the user to log in again.

**Screenshots**
![Screenshot 2021-01-19 at 15 14 22](https://user-images.githubusercontent.com/2960965/105054287-bafada00-5a69-11eb-99e5-96254bf18590.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
- Device: iPhone 12 Pro Max Simulator
- OS: iOS 14.3

**Additional context**
Thanks in advance for your response. Started a [tutorial series](https://youtu.be/x8xEkNCd3Vg) on this yesterday.

**Comment by Ashish-Nanda** [comment]
Thanks @graphicbeacon, this is actually due to differing behavior in the underlying Amplify iOS and Android libraries.

We are looking into getting it resolved.

**Comment by haverchuck** [comment]
@graphicbeacon This is expected behavior on iOS.  For the time being, we are going to be enforcing this behavior on Android as well. An exception to this behavior is when a logged in user has expired userpool tokens.  In this case, you can call signin without signing out first (on both platforms). Thanks for calling this out.

**Comment by matteocrippa** [comment]
@haverchuck I'm facing the same exact **issue**, in particular when I try to login on a second device with same credentials.
How to cope with this scenario? Obviously we cannot ask the user to go to the other device and signOut to signIn in the new one.

**Comment by matteocrippa** [comment]
Let's say that I have a user called `dummy1@domain.ext`
Two devices with brand new installed app:
- DeviceA
- DeviceB

- I signIn successfully in `DeviceA`
- I try to then signIn in `DeviceB`

DeviceB raises the error:

`There is already a user which is signed in. Please log out the user before calling showSignIn`

DeviceA continue to show me the user properly logged in.

**Comment by HuiSF** [comment]
Hi @matteocrippa thanks for the example.

As I mentioned, I don't think there is anything blocks sign in the same account signing in multiple devices by default.

>There is already a user which is signed in

This exception means there is an account signed in on device B already before sign in `dummy1@domain.ext` again. It could be a different account, or `dummy1@domain.ext` as well. 

Can you try to invoke `Amplify.Auth.fetchAuthSession` on Device B before signing in, see previously signed account info.

**Comment by matteocrippa** [comment]
I can try, but deviceB is a brand new instance of the iOS simulator just after a full wipe. 
So technically over there should be no data. Didn't check if you make use of keychain anywhere in the code (as source of the persistant data)

**Comment by kameshdhana** [comment]
Any update on this one?
Is this issue resolved?
