### ISSUE TITLE
Internet error after using the getPlugin function

### ISSUE THREAD

**Issue by GarbielBarbosa** [aws-amplify/amplify-flutter#3130]
### Description

Dear AWS team,

I would like to report an issue that several users have been experiencing in our application, where they are being logged out without apparent reason. Currently, we are using refresh tokens with a duration of 60 days. The observed behavior is similar to what was reported by user @brunovsiqueira in Issue https://github.com/aws-amplify/amplify-flutter/issues/1271. After confirming the call to Amplify.Auth.getCurrentUser(), we make the call to Amplify.Auth.fetchAuthSession, resulting in the error mentioned in the first image.

Following the guidance of @Jordan-Nelson, as stated in the response at https://github.com/aws-amplify/amplify-flutter/issues/1271#issuecomment-1508319420, we patiently awaited the release of a new version to address this issue. However, even after the update, the same behavior persists, albeit with a different error message. I reported this scenario in Issue https://github.com/aws-amplify/amplify-flutter/issues/1271, but @Jordan-Nelson instructed me to open a new issue.

According to @Jordan-Nelson, the error seems to be related to intermittent internet connectivity issues experienced by users. However, I firmly believe this is not the case, as it occurs for multiple users who report being able to log in normally after the logout.

To provide further insight and gather more accurate information, I have integrated the library https://pub.dev/packages/internet_connection_checker into our code. This library has the ability to check for internet connectivity by connecting to major global DNS servers. I believe this approach will provide a more definitive answer regarding whether or not connectivity is the root cause of the problem.

I have not yet released this library to our users, and I do not currently have a stack trace demonstrating the connection status. However, I am under significant pressure from our management to promptly address this issue. Therefore, I am opening the ticket in advance to allow you to evaluate the problem as quickly as possible, taking into consideration that this behavior has been occurring for quite some time.

Thank you in advance for your attention, and I look forward to a resolution for this problem.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Unfortunately, I have never been able to replicate this error on my devices. I can only monitor them through Firebase Crashlytics and track user reports within the app.

Below is the code where the error occurs:
```

Future<void> hasUser() async {
    final ILocalStorage storage = Modular.get();
    final User? user = await storage.getUser();
  
      // verifica se o usuário está logado.
      try {
        await Amplify.Auth.getCurrentUser();
      } catch (e) {
        showAlertErrorLogin(code: '1000');
        await goToLogin();
        return;
      }

      // Retorna os tokens do cognito e os fixa no usuário
      try {
        final session = await Amplify.Auth.getPlugin(
          AmplifyAuthCognito.pluginKey,
        ).fetchAuthSession();
        if (session.isSignedIn) {
          storage.user.acessToken = session.userPoolTokensResult.value.accessToken.toJson();
          storage.user.idToken = session.userPoolTokensResult.value.idToken.toJson();
          storage.user.refreshToken = session.userPoolTokensResult.value.refreshToken;
        }
      } catch (e, stackTrace) {
        await FirebaseCrashlytics.instance.recordError(e, stackTrace, reason: 'Erro ao logar fetchAuthSession');
        AnalyticsFunctions.saveLog('Erro ao logar fetchAuthSession', {'error': e.toString()});
        try {
          final session = await Amplify.Auth.getPlugin(
            AmplifyAuthCognito.pluginKey,
          ).fetchAuthSession();
          if (session.isSignedIn) {
            storage.user.acessToken = session.userPoolTokensResult.value.accessToken.toJson();
            storage.user.idToken = session.userPoolTokensResult.value.idToken.toJson();
            storage.user.refreshToken = session.userPoolTokensResult.value.refreshToken;
          }
        } catch (e) {
           bool result = await InternetConnectionChecker().hasConnection;

          await FirebaseCrashlytics.instance.recordError(e, stackTrace, reason: 'Erro ao logar fetchAuthSession 2. Has internet:$result ');
          AnalyticsFunctions.saveLog('Erro ao logar fetchAuthSession', {'error': e.toString()});
          showAlertErrorLogin(code: '1002');
          await goToLogin();
          return;
        }
      }

      // Caso o id token do usuário ou o email esteja vazio o usuário é deslogado.
      if (storage.user.idToken == null || storage.user.email == null) {
        await Amplify.Auth.signOut(
          options: const SignOutOptions(),
        );
        showAlertErrorLogin(code: '1003');
        await goToLogin();
        return;
      }

      await goToHome();
    }
  }
```

### Screenshots

Fist image

![](https://user-images.githubusercontent.com/30707007/241428761-ca7d0927-c3d4-4d44-b545-b204322ced49.png)

Second image

![](https://user-images.githubusercontent.com/30707007/241754707-4a635400-6a7d-4f26-9922-5dfbfdeb1e5a.png)

### Platforms

- [x] iOS
- [x] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by GarbielBarbosa** [comment]
@Jordan-Nelson,

Thank you for the quick response. I don't have the exact count of successful versus failed cases, but I can determine that in this version of my app on May 31st, out of 151 users, 84 users experienced an error in the function.

I already make the API call twice, as you can verify in the code snippet below:

```

 try {
        //FIST TIME
        final session = await Amplify.Auth.getPlugin(
          AmplifyAuthCognito.pluginKey,
        ).fetchAuthSession();
        if (session.isSignedIn) {
          storage.user.acessToken = session.userPoolTokensResult.value.accessToken.toJson();
          storage.user.idToken = session.userPoolTokensResult.value.idToken.toJson();
          storage.user.refreshToken = session.userPoolTokensResult.value.refreshToken;
        }
      } catch (e, stackTrace) {
        await FirebaseCrashlytics.instance.recordError(e, stackTrace, reason: 'Erro ao logar fetchAuthSession');
        AnalyticsFunctions.saveLog('Erro ao logar fetchAuthSession', {'error': e.toString()});
        try {
        //SECOND TIME
          final session = await Amplify.Auth.getPlugin(
            AmplifyAuthCognito.pluginKey,
          ).fetchAuthSession();
          if (session.isSignedIn) {
            storage.user.acessToken = session.userPoolTokensResult.value.accessToken.toJson();
            storage.user.idToken = session.userPoolTokensResult.value.idToken.toJson();
            storage.user.refreshToken = session.userPoolTokensResult.value.refreshToken;
          }
        } catch (e) {
           bool result = await InternetConnectionChecker().hasConnection;

          await FirebaseCrashlytics.instance.recordError(e, stackTrace, reason: 'Erro ao logar fetchAuthSession 2. Has internet:$result ');
          AnalyticsFunctions.saveLog('Erro ao logar fetchAuthSession', {'error': e.toString()});
          showAlertErrorLogin(code: '1002');
          await goToLogin();
          return;
        }
      }
```

A significant portion of my calls requires a valid access token for users to proceed in the app. Therefore, I prefer to block their access to prevent the error from occurring within the logged-in section of the app.

Thank you for your attention.

**Comment by Jordan-Nelson** [comment]
@GarbielBarbosa Thanks. I had missed that you already had a retry attempt. I would suggest adding a small delay since if the connection does drop off only momentarily it make take a few seconds to recover.

The crashalytics screenshot shows the logs from the first failure (`Erro ao logar fetchAuthSession`). Are you seeing logs of the second failure (`Erro ao logar fetchAuthSession 2....`)? If so, how many times per day?

**Comment by GarbielBarbosa** [comment]
@Jordan-Nelson,

In the next version, I will add the delay as well as the internet check. Regarding the quantity, I can provide you with the information, although it doesn't make much sense since "fetchAuthSession 2" occurs more frequently than "fetchAuthSession." I believe Firebase may be missing some logs.

fetchAuthSession 2: 73
fetchAuthSession: 33

Thank you for your understanding

**Comment by Jordan-Nelson** [comment]
Hi @GarbielBarbosa - Just checking it to see if you were able to resolve this issue.

**Comment by Jordan-Nelson** [comment]
@GarbielBarbosa - I am going to close this out since it has been a while with no response. If you are still experiencing this issues, please let me know and we can re-open.
