### ISSUE TITLE
Amplify.Auth.signIn stuck in infinite run

### ISSUE THREAD

**Issue by aoh-escape** [aws-amplify/amplify-flutter#3131]
If I input an invalid username/password Amplify.Auth.signIn never finishes running. Code gets stuck where Amplify.Auth.signIn is called. 

Would like to display to user if their username or password does not match one in the userbase

**Comment by dnys1** [comment]
Hi @aoh-escape, can you please share the following info?

1. Which version of the Amplify Flutter libraries are you using?
2. Which platforms does this occur on?
3. Can you share a code snippet of where you're calling `signIn`?
4. Can you share a redacted version of your `amplifyconfiguration.dart` file?

In the future, please use the default bug report template so we can better assist you.

**Comment by aoh-escape** [comment]
@dnys1 
1. Amplify_Flutter 1.0.0, Amplify_auth_Cognito 1.0.0
2. Mac
3. 
  try {
    final result = await Amplify.Auth.signIn(
      username: username,
      password: password,
    );
    safePrint("Value of result is: $result"); //DEBUGGING
    await _handleSignInResult(result);
    return true;
  } on AuthException catch (e) {
    safePrint('Error signing in: ${e.message}');
    return false;
  }
}

If i input a username/password that is not in the userbase it never gets past the signin call.

**Comment by dnys1** [comment]
I'm not able to reproduce this.

Is there any more information you can provide? For example, logs? Is this reproducible on other platforms? Have you followed the [platform setup instructions](https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/#macos) for macOS?

**Comment by Jordan-Nelson** [comment]
@aoh-escape - If you are still experiencing this issue, please let us know.

**Comment by dnys1** [comment]
Closing this for now as we have not heard back from you. Please feel free to reopen if you can provide any additional info.
