### ISSUE TITLE
Access Path Style Host option in S3 getUrl

### ISSUE THREAD

**Issue by ChristopherLinnett** [aws-amplify/amplify-flutter#3147]
The s3 bucket I need to work with is using periods "." in its name. 

I have found this is incompatible with the virtualized-style path output by Flutter's Amplify.Storage.getUrl method. Requesting an option in this method to specify the user wishes to produce the older path-style host in the signed url.

**Comment by HuiSF** [comment]
Hi @ChristopherLinnett thanks for opening this issue.

Bucket name that contains dots cannot be used virtual hosted-style URL, this a known issue to S3 service (Details please see [here](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) (the highlighted callout)). As the Path style access is in the plan of deprecation, we highly recommend to use bucket name without dots to get around of this known issue. Any reason that you can't rename the S3 bucket?

**Comment by HuiSF** [comment]
Oops didn't mean to close the issue before the actual release.

**Comment by dnys1** [comment]
The fix for this has been released.
