### ISSUE TITLE
Error compiling code using aws_common after upgrading flutter

### ISSUE THREAD

**Issue by lucasoares** [aws-amplify/amplify-flutter#3149]
### Description

Hello.

Using the following flutter version:
```bash
$ flutter --version
Flutter 3.12.0-1.0.pre.16 • channel main • https://github.com/flutter/flutter.git
Framework • revision 257c4eed43 (20 minutes ago) • 2023-06-06 16:08:07 -0400
Engine • revision 4571695f9e
Tools • Dart 3.1.0 (build 3.1.0-163.0.dev) • DevTools 2.24.0
```

My code can't run my application (-d `web-server`) anymore, with the following error:

```
<PATH_REDACTED>/.pub-cache/hosted/pub.dev/aws_common-0.5.0+1/lib/src/js/common.dart: Error: Tear-offs of external extension interop member 'start' are disallowed.
Declare a closure that calls this member instead.
Waiting for connection from debug service on Web Server...         19.9s
Failed to compile application.
```

Currently, I'm using:

```
  amplify_flutter: ^1.1.0
  amplify_auth_cognito: ^1.1.1
  amplify_authenticator: ^1.2.0
```

Thanks.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.12.0-1.0.pre.16

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @lucasoares sorry you are facing this issue. We don't test against Flutter's master branch and this seems to only be an issue there. I will see if we can remediate it. In the meantime, you should be able to use Flutter beta or stable.

**Comment by dnys1** [comment]
Merged a fix for this: https://github.com/aws-amplify/amplify-flutter/pull/3150

It will be available in the next release.

**Comment by dnys1** [comment]
The fix for this has been released.
