### ISSUE TITLE
[Critical] Missing implementation in Core

### ISSUE THREAD

**Issue by joekendal** [aws-amplify/amplify-flutter#315]
**Describe the bug**
For some reason, the Amplify Core throws a MissingPluginException as a result of this block of code
```dart
Future<bool> configure(String version, String configuration) {
  throw UnimplementedError('configure() has not been implemented.');
}
```
You'd think this wouldn't be the case as how could any of the plugins be working for others if there is an incomplete implementation of the core. This is the `dev` channel as well.

**To Reproduce**
1. Follow the [Getting Started tutorial](https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter)
2. Attempt any of [the subsequent tutorials](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/flutter) for using the plugins
3. `flutter run`

**Expected behavior**
For the button to be active and its text to appear configured, and for an analytics event to be fired off to Pinpoint

**Actual behaviour**
![Screenshot 2021-01-20 at 15 45 02](https://user-images.githubusercontent.com/13680617/105199251-79843080-5b36-11eb-994b-a901ac928c8f.png)
```
Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
[ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/core)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      Amplify.configure (package:amplify_core/amplify_core.dart:86:15)
<asynchronous suspension>
#2      _MyAppState._configureAmplify (package:app/main.dart:38:5)
<asynchronous suspension>
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [x] all

**Comment by joekendal** [comment]
Issue related to https://github.com/aws-amplify/amplify-flutter/issues/274

TODO:
- [ ] Update documentation

**Comment by Ashish-Nanda** [comment]
@joekendal  what version of Amplify flutter are you using? Are you using the package locally or the published versions?

#274 talks about upcoming breaking changes, but that has not been published yet.

Can you share your app code where you are adding the plugins and calling configure? Also share your `amplifyconfiguration.dart` file please.

**Comment by joekendal** [comment]
@Ashish-Nanda 

Version: `0.0.1-dev.6` from the published version

The code is the same as the tutorial:
### main.dart
```dart
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:flutter/material.dart';
import 'package:amplify_core/amplify_core.dart';
import 'package:amplify_analytics_pinpoint/amplify_analytics_pinpoint.dart';
import 'amplifyconfiguration.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _amplifyConfigured = false;

  // Instantiate Amplify
  Amplify amplifyInstance = Amplify();

  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  void _configureAmplify() async {
    if (!mounted) return;

    // Add Pinpoint and Cognito Plugins
    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    amplifyInstance.addPlugin(authPlugins: [authPlugin]);
    amplifyInstance.addPlugin(analyticsPlugins: [analyticsPlugin]);

    // Once Plugins are added, configure Amplify
    await amplifyInstance.configure(amplifyconfig);
    try {
      setState(() {
        _amplifyConfigured = true;
      });
    } catch (e) {
      print(e);
    }
  }

  // Send an event to Pinpoint
  void _recordEvent() async {
    AnalyticsEvent event = AnalyticsEvent("test");
    event.properties.addBoolProperty("boolKey", true);
    event.properties.addDoubleProperty("doubleKey", 10.0);
    event.properties.addIntProperty("intKey", 10);
    event.properties.addStringProperty("stringKey", "stringValue");
    Amplify.Analytics.recordEvent(event: event);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Amplify Core example app'),
        ),
        body: ListView(
          padding: EdgeInsets.all(10.0),
          children: <Widget>[
            Center(
              child: Column(
                children: [
                  const Padding(padding: EdgeInsets.all(5.0)),
                  Text(_amplifyConfigured ? "configured" : "not configured"),
                  RaisedButton(
                      onPressed: _amplifyConfigured ? _recordEvent : null,
                      child: const Text('record event'))
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

### amplifyconfiguration.dart
```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": my app id,
                    "region": "eu-west-1"
                },
                "pinpointTargeting": {
                    "region": "eu-west-1"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-west-2:{{ my pool id }}",
                            "Region": "eu-west-2"
                        }
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "{{ my app id }}",
                        "Region": "eu-west-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "eu-west-1"
                    }
                }
            }
        }
    }
}''';
```

**Comment by Ashish-Nanda** [comment]
@joekendal could you make just a single call to `amplifyInstance.addPlugin()` like so:
```
amplifyInstance.addPlugin(
        authPlugins: [authPlugin],
        analyticsPlugins: [analyticsPlugin]);
```
I think calling it multiple times is the issue. Let me know if that works.

**Comment by joekendal** [comment]
@Ashish-Nanda no, same issue :(

**Comment by fjnoyp** [comment]
@joekendal why did you add `if (!mounted) return;` to your `_configureAmplify`?  

Have you been able to debug your `_configureAmplify` method and verify that that configuration code is running?

**Comment by fjnoyp** [comment]
Hey @joekendal I'm looking to reproduce your issue on my machine.  Could you provide your pubspec.yaml as well?  I'm assuming it's just this: 


```
  amplify_flutter: ^0.0.1-dev.6
  amplify_analytics_pinpoint: ^0.0.1-dev.6
  amplify_auth_cognito: ^0.0.1-dev.6
```

**Comment by fjnoyp** [comment]
Hi @joekendal I've recreated your project copy pasting what was provided and using the above imports in pubspec.yaml   

I was not able to reproduce your error, the config works fine and I'm able to send events. 

Could you try running: `flutter clean build`?

Also, what platforms did you test on?
Are you using an emulator or a physical device?

**Comment by joekendal** [comment]
@fjnoyp this seems to be an issue on desktop. shouldn't flutter packages be compatible with any flutter runtime environment? Where do I need to look in the code to fix this? Happy to try and open a PR to address if someone can give me a clue

**Comment by Amplifiyer** [comment]
@joekendal, amplify-flutter currently only supports android and iOS environments. +1 here https://github.com/aws-amplify/amplify-flutter/issues/133 for Desktop support.

**Comment by joekendal** [comment]
@Amplifiyer clever bot this is
