### ISSUE TITLE
Deleted user on cognito freezes my app in an error state

### ISSUE THREAD

**Issue by lucasoares** [aws-amplify/amplify-flutter#3160]
### Description

Hello.

I was testing my app and discovered that when I delete a user from my Cognito user pool, the app stops working indefinitely.

The application is using a basic user authentication flow using Authenticator.

How I configure the amplify:
```dart
    await Amplify.addPlugin(AmplifyAuthCognito());
    await Amplify.configure(amplifyconfig);
```

After configuring amplify my application tries to get a few user attributes from my backend API using the user's access token. To get the access token I'm using the following code, which I don't even know if this is the best option since documentation for amplify is very limited:
```dart
  Future<String> getBearerToken() async {
    final session = await Amplify.Auth.fetchAuthSession();

    if (!session.isSignedIn) {
      throw Exception('User is not signed in');
    }

    final sessionJson = session.toJson();

    if (sessionJson['userPoolTokens'] == null) {
      throw Exception('User in an invalid state');
    }

    final CognitoUserPoolTokens userPoolTokens =
        sessionJson['userPoolTokens'] as CognitoUserPoolTokens;

    return userPoolTokens.accessToken.raw;
  }
```

This code will throw the exception if the user is deleted (userPoolTokens = null):
```
// Result of session.toJson()
{isSignedIn: true, userSub: null, userPoolTokens: null, credentials: null, identityId: null}
```

When my application can't get the user access token to make requests to the backend API, we automatically log out the user using `Amplify.Auth.signOut()` but since the user doesn't exist anymore the `signOut` will also throw an error, and will never clear amplify's internal state/session, making it impossible for my app to return to a "valid" state:

```
ERROR | SignOutStateMachine | Emitted error: UserNotFoundException {
  "message": "User does not exist.",
  "underlyingException": "UserNotFoundException {\n  message=User does not exist.,\n}"
}
dart:sdk_internal 5463:11                                                                     throw_
packages/aws_common/src/util/debuggable.dart.js 1208:19                                       get value
packages/amplify_auth_cognito_dart/src/model/signup/cognito_sign_up_options.dart.js 3554:49   getUserPoolTokens
dart:sdk_internal 41426:33                                                                    <fn>
dart:sdk_internal 41259:59                                                                    runUnary
dart:sdk_internal 36462:29                                                                    handleValue
dart:sdk_internal 37033:49                                                                    handleValueCallback
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.3

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
I believe this requires both the user to be deleted on the backend and the tokens to expire on the frontend. This causes `signOut` to fail since it's trying to refresh tokens before it clears them. 

I opened a PR to handle this case specially: https://github.com/aws-amplify/amplify-flutter/pull/3162
