### ISSUE TITLE
There is no exception thrown or warning when use accessLevel: StorageAccessLevel.protected without specifying the targetIdentityId 

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-flutter#3161]
### Updated Description

The APIs for storage do no enforce that an identityId is provided when the Access level is set to protected, nor is an exception thrown. Instead, the current user's identity ID is used by default.

This is inconsistent with the behavior on other platforms where the API either enforces the value is provided or an exception is thrown.

### Original Description

<details>

```dart
  Future<void> listFiles() async {
    try {
      // (1)
      final result = await Amplify.Storage.list(
        options: const StorageListOptions(
          accessLevel: StorageAccessLevel.protected,
        ),
      ).result;
      safePrint('Listed items: ${result.items}');
    } on StorageException catch (e) {
      safePrint(e.message);
    }
  }
```

In this example the storage plugin expects developers to specify a target identity id

```dart
  Future<void> listFiles() async {
    try {
      // (1)
      final result = await Amplify.Storage.list(
        options: const StorageListOptions(
          accessLevel: StorageAccessLevel.protected,
          pluginOptions: S3ListPluginOptions.forIdentity('target-identity-id'),
        ),
      ).result;
      safePrint('Listed items: ${result.items}');
    } on StorageException catch (e) {
      safePrint(e.message);
    }
  }
```

Without this information, the API call doesn't work as expected. A validation exception should be thrown here to prevent this from happening.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.0

### Deployment Method

Amplify CLI

</details>

**Comment by Jordan-Nelson** [comment]
Closing this issue as this is no longer relevant with the updated storage APIs in Amplify Flutter v2.
