### ISSUE TITLE
AWSService: Support new Services like OpenSearch Serverless

### ISSUE THREAD

**Issue by blattr** [aws-amplify/amplify-flutter#3171]
### Description

I am trying to call my Serverless OpenSearch Cluster. With Postman, it works, because I am able to fill in the service name (in this case "aoss") manually. In my flutter application, I have to pass an enum (AWSService/aws_common) to the V4Signer to get this working but unfortunately, the OpenSearch Serverless Service is not part of this enum. My hopes are, that this small fix could be released really soon so I do not get stuck in my development :-)

PS: Maybe other (new) services are affected as well, but obviously my only issue is OpenSearch Serverless atm.

```json
{
    "status": 403,
    "request-id": "3e0c5ebe-5682-9517-a48a-003ac72f5e22",
    "error": {
        "reason": "Credential should be scoped to correct service: 'aoss', not 'es'.",
        "type": "AccessDenied"
    }
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.7.11

### Amplify Flutter Version

1.0.0

### Deployment Method

Custom Pipeline

**Comment by dnys1** [comment]
I've merged https://github.com/aws-amplify/amplify-flutter/pull/3234 to resolve this. It should be released shortly.

**Comment by dnys1** [comment]
The fix for this has been released. An entry for OpenSearch Serverless has been added and the enum was changed to a class so arbitrary service names can be used.
