### ISSUE TITLE
[amplify_auth_cognito] Reactive way of keeping track of the signed in user and his session

### ISSUE THREAD

**Issue by peer-f** [aws-amplify/amplify-flutter#3182]
I would like to keep track of my signed in user and his session ideally using a stream. I often use `Amplify.Auth.fetchAuthSession()` and the `isSignedIn` attribute of the session to determine if my user is signed in or not. 

In my application I do this by using a `Riverpod FutureProvider` to check if the user is signed in and to display widgets accordingly. I think having one or more streams for auth related data such as the user and the current session would be really beneficial considering reactive navigation flows and handling authentication in general. 

This is my current way of checking if a user is signed in:
```
final isSignedInProvider = FutureProvider<bool>((ref) async {
  if (!Amplify.isConfigured) {
    return false;
  }

  final AuthSession session = await Amplify.Auth.fetchAuthSession();

  return session.isSignedIn;
});
```

Firebase Auth for example offers a lot of different streams to handle scenarios like this by directly exposing streams in methods such as `FirebaseAuth.instance.authStateChanges()`, `FirebaseAuth.instance.idTokenChanges()` or `FirebaseAuth.instance.userChanges()`.  Having direct access to streams that offer this kind of data enables easy integration into state management tools such as a `Riverpod StreamProvider`.

This could be solved by directly exposing streams of `Amplify.Hub` instead of  returning a`StreamSubscription` to improve integration into state management. Right now I feel like the events returned by HubChannel.Auth could have a bit more depth.

**Comment by dnys1** [comment]
Hi @peer-f, this seems similar to https://github.com/aws-amplify/amplify-flutter/issues/2654. Would you mind if I closed this in favor of that issue?

We are investigating ways to make the Hub easier to work with. At the moment, the `authStateChanges` Stream can be mimicked as follows:

```dart
final Stream<AuthUser?> authStateChanges = Amplify.Hub.availableStreams[HubChannel.Auth]!
        .cast<AuthHubEvent>()
        .map((event) => event.payload);
```

**Comment by dnys1** [comment]
Closing in favor of #2654.
