### ISSUE TITLE
S3 protected url created with owners identityId expires

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-flutter#3240]
### Description

**Description**
Similar to a social media app, when user uploads an image with his post, the image is uploaded in protected folder. Which only the owner can delete/write and can be accessed by other with a pre-signed url.

On uploading, I save the pre-signed url in a model. The users' followers can access the model and view the image.

I had this issue before https://github.com/aws-amplify/amplify-flutter/issues/2703 and solved it using` targetIdentityId: object.identityId` as suggested. 

Now with updated SDK, not sure how do the same for protected files:

`Future<String> getDownloadUrl({
  required String key,
  required StorageAccessLevel accessLevel,
}) async {
  try {
    final result = await Amplify.Storage.getUrl(
      key: key,
      options: const StorageGetUrlOptions(
        accessLevel: accessLevel,
        pluginOptions: S3GetUrlPluginOptions(
          validateObjectExistence: true,
          expiresIn: Duration(days: 1),
        ),
      ),
    ).result;
    return result.url.toString();
  } on StorageException catch (e) {
    safePrint('Could not get a downloadable URL: ${e.message}');
    rethrow;
  }
}`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
@itechevo are you asking how to make the same call to v1 `getUrl()` now that API has changed? If so, I think it will look like this:

```dart
final operation = Amplify.Storage.getUrl(
  key: targetKey,
  options: StorageGetUrlOptions(
    accessLevel: StorageAccessLevel.protected,
    pluginOptions: S3GetUrlPluginOptions.forIdentity(
      targetIdentityId,
      validateObjectExistence: true,
    ),
  ),
);
final result = await operation.result;
print(result.url.toString()); // => URL
```

Let me know if this is helpful or if I have misunderstood your question.

**Comment by itechevo** [comment]
@ragingsquirrel3 thanks for the reply, yes that is what I was looking for, couldn't find it from documentation.
