### ISSUE TITLE
Releated to function

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#3243]
### Description

Hey guys, I have a doubt. Is it possible to call a third-party API using a Lambda function after data gets synced to the DataStore?

In my application, I'm using AWS Amplify DataStore to handle data synchronization. Once the data is synchronized with the DataStore, I would like to trigger a Lambda function that calls a third-party API to perform additional actions or update external systems.

I'm wondering if anyone has experience with this scenario and could provide some insights or guidance on how to achieve this. Specifically, I'm looking for information on how to set up the Lambda function to be triggered after data synchronization and how to make the API call within the Lambda function.

Any help or suggestions would be greatly appreciated. Thank you!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
Hello, good question! This feature isn't available by default in Amplify with Datastore, but with some custom changes to AWS resources I think there are some ways you could go about this.

One way would be to use the dynamo DB streams to trigger the lambda. There is some info about that on https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.html. Again noting this isn't Amplify-specific but taking advantage of the fact that Amplify Datastore (and underlying AppSync endpoints) use dynamo db as the underlying data source and there are lots of AWS features available to integrate with them, such as a stream to a lambda trigger.

With GraphQL API, you can make the mutation with a lambda resolver which then gives you lots of options as noted on https://docs.amplify.aws/cli/graphql/custom-business-logic/#structure-of-the-function-event but you will not be able to use this mutation with datastore (see https://github.com/aws-amplify/amplify-category-api/issues/303).
