### ISSUE TITLE
StorageListOptions `pageSize` not working?

### ISSUE THREAD

**Issue by jonRreeves** [aws-amplify/amplify-flutter#3275]
### Description

Hi,

I'm using the following code to list items in an S3 bucket.

```dart
 final result = await Amplify.Storage.list(
        options: StorageListOptions(
          pageSize: 5,
          nextToken: nextToken,
        ),
      ).result;
 ```
 Any provided page size seems to have no effect on the result. In my test environment I have 23 items in my S3 bucket.
 
 The output of 
 
 ```dart
safePrint("items len ${result.items.length}");

...

items len 23
 ```
 
Am i misunderstanding how this works, or is the `pageSize` parameter broken? 
 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
Thanks @jonRreeves. Your understanding of the API is correct and I think this is a bug as I was able to reproduce it. We will work on getting a fix out.

**Comment by ragingsquirrel3** [comment]
This was published with latest version of amplify_storage_s3 (1.2.1) so I will close this. Reopen if you still have any issue and thanks again for filing it.
