### ISSUE TITLE
How to continue with Authorization code

### ISSUE THREAD

**Issue by itlicious** [aws-amplify/amplify-flutter#3297]
### Description

We are only using Flutter web for a project. We have managed to sign in via a federated IDP through the Amplify SDK
`
await Amplify.Auth.signInWithWebUI(
      provider: const AuthProvider.saml('samlprovider'),
    );
`
Once signed in the application is correctly redirected to the specified url with an authorization code and state property. 
How can I apply the code and state to the Amplify SDK? AFAIK there is no method to do this.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @itlicious the Amplify Flutter library is configured to automatically intercept these parameters and complete the sign  upon redirect to the sign-in redirect URI.

Can you share your Amplify configuration (with sensitive values redacted) and an example of the final redirect with code&state which is not triggering a sign in?

**Comment by itlicious** [comment]
Hi @dnys1, below you can find my config. 

I did verify with `Amplify.Auth.getCurrentUser()` after login, but I get a `SignedOutException`. So it looks like it didn't pick up the values correctly.

`{
	"UserAgent": "aws-amplify-cli/2.0",
	"Version": "1.0",
	"auth": {
		"plugins": {
			"awsCognitoAuthPlugin": {
				"UserAgent": "aws-amplify-cli/0.1.0",
				"Version": "0.1.0",
				"IdentityManager": {
					"Default": {}
				},
				"CredentialsProvider": {
					"CognitoIdentity": {
						"Default": {
							"PoolId": "myPoolId",
							"Region": "eu-central-1"
						}
					}
				},
				"CognitoUserPool": {
					"Default": {
						"PoolId": "eu-central-1_q2bereOSF",
						"AppClientId": "myAppClient",
						"Region": "eu-central-1"
					}
				},
				"Auth": {
					"Default": {
						"OAuth": {
							"WebDomain": "https://myDomain.auth.eu-central-1.amazoncognito.com",
							"AppClientId": "myAppClient",
							"SignInRedirectURI": "http://localhost:3000/login",
							"SignOutRedirectURI": "http://localhost:3000/login",
							"Scopes": [
								"email"
							]
						},
						"authenticationFlowType": "USER_SRP_AUTH",
						"mfaConfiguration": "OFF",
						"mfaTypes": [
							"SMS"
						],
						"passwordProtectionSettings": {
							"passwordPolicyMinLength": 8,
							"passwordPolicyCharacters": []
						},
						"signupAttributes": [
							"EMAIL"
						],
						"socialProviders": [],
						"usernameAttributes": [
							"EMAIL"
						],
						"verificationMechanisms": [
							"EMAIL"
						]
					}
				}
			}
		}
	}
}`

**Comment by dnys1** [comment]
Can you try making the signin/signout redirect URI point to the base URL? `http://localhost:3000`

**Comment by itlicious** [comment]
I found out what the problem was.
It was caused by a FutureBuilder on top of my MaterialApp, which was causing the problem that the router was yet unknow at startup time and redirecting to the root, instead of consuming the query parameters.

Thanks for the help.
