### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by BeamTrakLLC** [aws-amplify/amplify-flutter#3301]
### Description

Where

*Pub\Cache\hosted\pub.dev\amplify_analytics_pinpoint-1.2.0\android\build.gradle' line: 27

 What went wrong:
A problem occurred evaluating project ':amplify_analytics_pinpoint'.
> No signature of method: build_3hzsdz38ol0ouu1g29j1zj56o.android() is applicable for argument types: (build_3hzsdz38ol0ouu1g29j1zj56o$_run_closure2) values: [build_3hzsdz38ol0ouu1g29j1zj56o$_run_closure2@22e08282]

Flutter doctor
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Run flutter pub add amplify_auth_cognito and flutter pub add amplify_flutter.
It provides the two versions below.
 -amplify_auth_cognito: ^1.2.0
 -amplify_flutter: ^1.2.0
2. Run flutter app in debug mode

### Screenshots

![Screenshot 2023-06-22 154202](https://github.com/aws-amplify/amplify-flutter/assets/102749940/4a44041c-69b7-4b5d-8608-18b1d05d6d9a)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

**Comment by BeamTrakLLC** [comment]
Here are the contents of that file.
We have an amplify configuration file ready and have pulled the amplify changes to the project. I hoped to provide more detail on steps to reproduce but this happened almost immediately after setting up the amplify project, pulling it into the flutter project, and installing those two packages. As soon as I remove amplify_flutter and amplify_auth_cognito, the app works completely fine again. Thank you for the help!

Here are some of our other settings as well if useful.
 minSdkVersion 24
 targetSdkVersion 32

android/build.gradle
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by BeamTrakLLC** [comment]
AppData\Local\Pub\Cache\hosted\pub.dev\amplify_analytics_pinpoint-1.2.0\android\build.gradle' line: 27
This might be the more specific android/build.gradle file you were looking for as well. this is the one the error points at but I gave my project android/build.gradle file previously.

group 'com.amazonaws.amplify.amplify_analytics_pinpoint'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 24
    }

    namespace 'com.amazonaws.amplify.amplify_analytics_pinpoint'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Comment by Jordan-Nelson** [comment]
@BeamTrakLLC - It looks like the project is using versions of kotlin and gradle that are not supported by Amplify Flutter. Can you update them based on the [docs here](https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/#android) and see if this issue persists?

**Comment by BeamTrakLLC** [comment]
Thank you so much for the help! The app builds successfully and previous issues are now gone.

**Comment by Jordan-Nelson** [comment]
I am glad to hear that. I will close this issue out then.
