### ISSUE TITLE
Amplify.DataStore.observeQuery with QueryPredicate not working

### ISSUE THREAD

**Issue by MattCrist** [aws-amplify/amplify-flutter#3305]
### Description

I have a query which works fine when I observe for all changes but as soon as I add a QueryPredicate I no longer get any updates.  

This query works fine every time:
`void observeQuery() {
    _stream = Amplify.DataStore.observeQuery(Animal.classType)
        .listen((QuerySnapshot<Animal> snapshot) {
      setState(() {
        _animals = snapshot.items;
      });
    });
  }`

With this change the query only works the first time the widget loads, no updates are ever shown:
`void observeQuery() {
    _stream = Amplify.DataStore.observeQuery(Animal.classType,
            where: Animal.FARM.eq(widget.farm.id))
        .listen((QuerySnapshot<Animal> snapshot) {
      setState(() {
        _animals = snapshot.items;
      });
    });
  }`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.4

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Farm @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  animals: [Animal] @hasMany
}

type Animal @model @auth(rules: [{ allow: private }]) {
  id: ID!
  tag: String!
  farm: Farm @belongsTo
}
```

**Comment by Jordan-Nelson** [comment]
Hi @MattCrist - I believe this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/3020 which has been resolved in the latest version of amplify flutter. Are you able to upgrade to the latest available version, including the latest version of DataStore?

**Comment by MattCrist** [comment]
@Jordan-Nelson I upgraded to v1.2.0 and it seem to resolve the issue.  Thanks for your help.
