### ISSUE TITLE
GraphQL update returns success but does not update DynamoDB object

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-flutter#3308]
### Description

Following the [documentation](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter/) on how to update a model via GraphQL, the model in the DB that was supposed to be updated via the mutation call does not update, the update mutation call just returns the model that was in the DB before the update, not the updated model.

No error is reported, the operation returns the updated object but it is not updated, nor is it updated in the DB.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Follow the [documentation](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter/) to make a simple update mutation call on some model. Just change one of the instantiated model object's fields and call update in the same manner as described in the docs, i.e, do something like: 
```dart
Future<void> updateTodo(Todo originalTodo) async {
  final todoWithNewName = originalTodo.copyWith(name: 'new name');

  final request = ModelMutations.update(todoWithNewName);
  final response = await Amplify.API.mutate(request: request).response;
  safePrint('Response: $response');
}
```
And you'll see that what you get back in `response` is `originalTodo`, not `todoWithNewName`.

I have added the code for the update - even though it's pretty generic boilerplate - below, with the schema code.

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
Here is the `Project` model I was trying to update that was not updating at all:


type Project
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownerId" }
      { allow: groups, groups: ["everyone"], operations: [read] }
      { allow: groups, groupsField: "groups", operations: [read, update] }
    ]
  ) {
  id: ID!
  ownerId: ID! @index(name: "byUser", sortKeyFields: ["updatedAt"])
  title: String!
  groups: [String]!
  visibility: ProjectVisibility!
  license: ProjectLicense!
  owner: User @belongsTo(fields: ["ownerId"])
  description: String
  titleArtistUrl: String
  imageUrl: String
  nPlays: Int
  tracks: [Track] @hasMany(indexName: "byProject", fields: ["id"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}


and this is the code that updated it which always returns success and never updates anything (just keeps returning the original un-updated object from the DB):
```dart
  Future<void> updateProject(Project project) async {
    try {
      final request = ModelMutations.update(project);
      final response = await Amplify.API.mutate(request: request).response;
      safePrint('updateProject to title: $project');
      log('-------------------------------------------------------------------');
      safePrint('updateProject response: $response');
    } on Exception catch (e) {
      log('updateProject mutation failed with: $e');
    }
  }
```
```

**Comment by dorontal** [comment]
Related to https://github.com/aws-amplify/amplify-flutter/issues/2026 - which was never fully resolved.

**Comment by dorontal** [comment]
FYI, I was concerned that the groups field in my model my cause some permissions side effects or issues, so I've just tried removing all groups from the model, and used this simpler model instead. The issue of no updates continues, the same exact issue remains with this simpler model:
```graphql
type Project
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownerId" }
    ]
  ) {
  id: ID!
  ownerId: ID! @index(name: "byUser", sortKeyFields: ["updatedAt"])
  title: String!
  visibility: ProjectVisibility!
  license: ProjectLicense!
  owner: User @belongsTo(fields: ["ownerId"])
  description: String
  titleArtistUrl: String
  imageUrl: String
  nPlays: Int
  tracks: [Track] @hasMany(indexName: "byProject", fields: ["id"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

**Comment by ragingsquirrel3** [comment]
Sorry you are having this issue. I was not able to reproduce with a version of your schema that I simplified a but more by removing related fields.

```graphql
type Project @model @auth(rules: [{ allow: owner, ownerField: "ownerId" }]) {
  id: ID!
  ownerId: ID! @index(name: "byUser", sortKeyFields: ["updatedAt"])
  title: String!
  # visibility: ProjectVisibility!
  # license: ProjectLicense!
  # owner: User @belongsTo(fields: ["ownerId"])
  description: String
  titleArtistUrl: String
  imageUrl: String
  nPlays: Int
  # tracks: [Track] @hasMany(indexName: "byProject", fields: ["id"])
  updatedAt: AWSDateTime!
}
``` 

though I don't know if the related models might be related, especially `User` in this use case.

I'm wondering if your error might be in `ModelMutations` code, plugin code, or some case with AppSync. Could you provide a bit more info to help me diagnose/repro?

1. the request variables for your update request that result from `ModelMutations.update`. From your code example where 
`request` is the result of mutations helper, just print `request.variables['input']` as this will help determine if the request generation is not working as expected.
2. assuming 1 has the expected, updated title in the request, are you able to perform this mutation successfully in the AppSync console? If so, could you include the request document/variables that make this work?

**Comment by dorontal** [comment]
Thank you @ragingsquirrel3 for your attention to this.  

>     1. the request variables for your update request that result from `ModelMutations.update`. From your code example where
>        `request` is the result of mutations helper, just print `request.variables['input']` as this will help determine if the request generation is not working as expected.

I added the following print statements to this code that generated the output (below it):
```dart
  Future<void> updateProject(Project project) async {
    try {
      final request = ModelMutations.update(project);
      safePrint(request.variables);
      safePrint('------------------------------------------------------------');
      final response = await Amplify.API.mutate(request: request).response;
      safePrint('updateProject to title: $project');
      safePrint('------------------------------------------------------------');
      safePrint('updateProject response: $response');
    } on Exception catch (e) {
      log('updateProject mutation failed with: $e');
    }
  }
```

and this is the output of those print statements in the code above: 
```
{input: {id: fbb658d9-5940-440a-b2c7-8c880ae367df, title: a7, visibility: private, license: by, description: , titleArtistUrl: null, imageUrl: null, nPlays: 0, createdAt: 2023-06-23T15:31:58.540000000Z, updatedAt: 2023-06-23T18:06:24.032000000Z, ownerId: d641f3a3-39a5-40b5-956e-df6363bac121}, condition: null}
------------------------------------------------------------
updateProject to title: Project {id=fbb658d9-5940-440a-b2c7-8c880ae367df, title=a7, visibility=private, license=by, owner=User {id=d641f3a3-39a5-40b5-956e-df6363bac121, displayName=, colorIndex=7, pictureType=image, initials=, about=, place=, nPlays=0, nProjects=0, nArrangements=0, nPlaylists=0, nFollowing=0, nFollowers=0, bytesQuota=2000000000, bytesUsed=0, email=funkjimi@gmail.com, nUpdatesLeft=9, nUploadsLeft=1000, totalEarned=0, lastUploadedAt=2023-06-20T20:29:27.005000000Z, createdAt=2023-06-20T20:29:27.005000000Z, updatedAt=2023-06-23T16:35:23.281000000Z}, description=, titleArtistUrl=null, imageUrl=null, nPlays=0, createdAt=2023-06-23T15:31:58.540000000Z, updatedAt=2023-06-23T18:06:24.032000000Z}
------------------------------------------------------------
updateProject response: GraphQLResponse<Project$> success: {
  "id": "fbb658d9-5940-440a-b2c7-8c880ae367df",
  "title": "a",
  "visibility": "private",
  "license": "by",
```

> 
>     2. assuming 1 has the expected, updated title in the request, are you able to perform this mutation successfully in the AppSync console? If so, could you include the request document/variables that make this work?
> 

Working on this one. I don't even know the proper GraphQL syntax of an update mutation (Amplify and its codegen have helped me with not needing to know it) .

>     3. the `User` portion of your schema so I can add this to my attempt to repro as it might be relevant

Here is the `User` portion of the schema:

```graphql

type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  displayName: String!
  colorIndex: Int!
  pictureType: PictureType!
  initials: String!
  about: String!
  place: String!
  nPlays: Int!
  nProjects: Int!
  nArrangements: Int!
  nPlaylists: Int!
  nFollowing: Int!
  nFollowers: Int!
  bytesQuota: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  bytesUsed: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  email: String! @auth(rules: [{ allow: owner, operations: [read] }])
  nUpdatesLeft: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  nUploadsLeft: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  totalEarned: Float! @auth(rules: [{ allow: owner, operations: [read] }])
  lastUploadedAt: AWSDateTime! @auth(rules: [{ allow: owner, operations: [read] }])
  projects: [Project] @hasMany(indexName: "byUser", fields: ["id"]) @auth(rules: [{ allow: owner }])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

**Comment by ragingsquirrel3** [comment]
Thanks for the info, I will use this for further investigation and update here if I find anything.

**Comment by dorontal** [comment]
Hi @ragingsquirrel3  I figured out the answer to answer your question #2:
> 
>     2. assuming 1 has the expected, updated title in the request, are you able to perform this mutation successfully in the AppSync console? If so, could you include the request document/variables that make this work?
> 
At the Appsync console GraphQL query section, I logged in via the user pool that was set up for this app with the username of the user that owns the project instance with title "a" - then executed a query, as that user, to change the title to "a9" - here too, the update mutation succeeds without error as you can see in the screenshot, but the DB value still has title as "a" - the title did not change in the DB. I believe the screenshot confirms that the operation has succeeded. 
![mutation-run](https://github.com/aws-amplify/amplify-flutter/assets/5935957/eb5f657f-c97b-4097-b231-e79adb3612ed)

**Comment by ragingsquirrel3** [comment]
Looking at your screenshot, I see the issue might be that you have conflict resolution enabled for this backend (has _version and other fields like _deleted). Are you also using DataStore in this app? In AppSync console, you can try to include _version in your input and set it to the same number as the existing entry (you will have to query it first with that field included in the selection set or look in dynamo DB to see what it is). Let me know if you are able to update in AppSync console this way.

It's kinda complicated, but conflict resolution prevents updates from older versions of the model and it uses _version to keep track of that. When you use DataStore, this is managed automatically as DataStore will keep local versions in sync with the server, which sets the _version. Using GraphQL in the same app as DataStore tends to be difficult because your app will then have to keep track of _version. Further, the _version is not reflected in codegen models so you would have to use manual request document strings. There is some more info from [an older issue](https://github.com/aws-amplify/amplify-cli/issues/3237).

**Comment by ragingsquirrel3** [comment]
I also suspect the reason the request has no error but older data is the result of automerge resolution strategy: "Conflict on a scalar field: GraphQL scalar or any field that is not a collection (i.e. List, Set, Map). Reject the incoming value for the scalar field and select the value existing in the server." https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html#conflict-detection-and-resolution

**Comment by dorontal** [comment]
@ragingsquirrel3 I am still trying to understand this but in the meantime, FYI, the API used here in this issue has been set up with conflict resolution strategy turned "on" and set to "Auto Merge". This was done to prepare for possible use of Datastore. Since we are not using Datastore yet, I can turn that off and check if the updates happen correctly in that case.
