### ISSUE TITLE
Amplify Flutter's UploadFile operation doesn't return versionId

### ISSUE THREAD

**Issue by jcblancomartinez** [aws-amplify/amplify-flutter#331]
Hi,

I've enabled versioning in my S3 bucket. Every time I upload a file, I want to get versionId to be able to store a URL (including versionId) to the S3 object.

However, [UploadFileResult](https://github.com/aws-amplify/amplify-flutter/blob/master/packages/amplify_storage_plugin_interface/lib/src/UploadFile/UploadFileResult.dart#L19) only contains S3 object key.

Could you please add versionId to UploadFileResult?

This is currently blocking us so we are using aws_s3_api plugin instead. One of the cons of using aws_s3_api is that it doesn't handle multipart for large files out-of-the-box and we need to implement the flow by ourselves.

Thanks.

**Comment by fjnoyp** [comment]
Hi @jcblancomartinez thanks for posting this issue.  We won't be able to support this feature at the moment as the underlying Amplify native SDKs which we build upon don't have this functionality.  

Their reasoning is that getUrl is a separate http call and it doesn’t make sense for to make that extra http call for every upload request.

**Comment by jcblancomartinez** [comment]
@fjnoyp,

I think you should consider as starting point S3's API and not Amplify native SDKs.

S3's PutObject API returns versionId as part of its [response](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_ResponseSyntax).

I won't get into why versionId is not returned from Amplify native SDK but it seems like a gap. Please, let me know if I should create a feature request to Amplify native SDK.

Thanks.

**Comment by HuiSF** [comment]
Hi @jcblancomartinez we've release Amplify Flutter [v1.0.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), now the upload and download operations returns a result containing the object `versionId` (if you have enabled bucket versioning)

Example

```dart
// Use `getPlugin` can expose S3 service specific fields in the result object
final s3Plugin = Amplify.Storage.getPlugin(AmplifyStorageS3.pluginKey);

final uploadFileOperation = s3Plugin.uploadFile(
  localFile: AWSFile.fromPath('path/to/local_file.png'),
  key: 'example-key,
  options: StorageUploadFileOptions(
    pluginOptions: S3UploadFilePluginOptions(
      getProperties: true, // specify to return object metadata along with the upload result
    ),
  ),
);
final result = await uploadFileOperation.result;
print('Object versionId: ${result.uploadedItem.versionId}');
```

Please learn about the enhanced upload API [here](https://docs.amplify.aws/lib/storage/upload/q/platform/flutter/), and refer to [the API reference of `S3UploadFilePluginOptions`](https://pub.dev/documentation/amplify_storage_s3_dart/latest/amplify_storage_s3_dart/S3UploadFilePluginOptions-class.html).
