### ISSUE TITLE
Standalone Authenticator Component

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [aws-amplify/amplify-flutter#3324]
### On which framework/platform would you like to see this feature implemented?

Flutter

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Currently, the Authenticator component is designed to be used by wrapping the entire Material App, which can be limiting in certain scenarios. I would like to propose making the Authenticator component usable as a standalone component, allowing it to be placed within custom pages or screens.

The current behaviour of the Authenticator component, where it expands to take up all vertical space and has a set background colour, makes it difficult to integrate it into a custom page. By making the Authenticator component standalone, developers would have the flexibility to incorporate it into their custom UI designs more effectively.

In addition, can custom TextFields and error messages be used?

### Please describe a solution you'd like.

I would like to be able to use the Authenticator component as a standalone component.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by Jordan-Nelson** [comment]
@Petri-Oosthuizen - Currently the best option to achieve this is probably the UI customization that @hbuchel linked above. You can build your own UI for one or more screens. You can use many of the prebuilt components from the authenticator. There is a simple example of how you could use this to add a logo to each screen at the linked docs. Would this fit your use case?

**Comment by Petri-Oosthuizen** [comment]
I apologize for the delayed response. 

I encountered some challenges while attempting to integrate the prebuilt components into my app. These components automatically resize to occupy all vertical space, making it difficult to position them within a scrollable widget. Additionally, when using the prebuilt components separately from the Authenticator widget, the responsibility of implementing the page flow falls on the developer. Ideally, I would like to utilize the complete Authenticator widget to leverage its implementation benefits. However, the main issue I'm currently facing is that the Authenticator widget cannot be used in a scrollable widget without specifying a fixed height, which is not an ideal solution.

Regarding customization, I was more thinking along the lines of customizing the inputs and buttons.

**Comment by Jordan-Nelson** [comment]
@Petri-Oosthuizen - Please take a look at the comment above and let me know if the current options do not work for your use case. Thanks.

**Comment by Petri-Oosthuizen** [comment]
Thank you for your suggestions! Unfortunately, we were unable to get the Authenticator component to work as a standalone component on a page or modal, as we had done in a Vue.js application. As we wanted to use our own custom form components (inputs & buttons) anyway, we opted to build the component ourselves.
