### ISSUE TITLE
Return file url after Amplify.Storage.uploadFile

### ISSUE THREAD

**Issue by NimaSoroush** [aws-amplify/amplify-flutter#333]
**Describe the bug**
Returning the file url after Amplify.Storage.uploadFile will help avoiding Amplify.Storage.getUrl call after file successfully uploaded.

**Expected behavior**
Amplify.Storage.uploadFile returning file's url to avoid Amplify.Storage.getUrl call

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by fjnoyp** [comment]
Hi @NimaSoroush we have investigated adding support for returning url when calling Amplify.Storage.uploadFile

After speaking with other teams, supporting this feature would require making another http request for file url.  As a separate method Amplify.Storage.getUrl already exists it doesn't make sense to make uploadFile automatically call getUrl and incur another http request if it's not needed.

**Comment by fjnoyp** [comment]
Consequently, for now we don't have any plans to add this feature-request.  I'll mark this as pending close.  If you disagree with this decision please let us know the reason and we can consider reopening and reprioritizing.

**Comment by NimaSoroush** [comment]
Thanks Kyle (@fjnoyp), my point was more around not making the second http call and relying on the fact that uploadFile should already know the destination of the uploaded file and can just return the constructed url. If that is not the case and it is more complicated then that, we can close this ticket and rely on the consumer to make two http calls

**Comment by RodPaDev** [comment]
I second @NimaSoroush reason for returning the URL after uploading.
