### ISSUE TITLE
Support switching authentication flows at runtime

### ISSUE THREAD

**Issue by jcowley** [aws-amplify/amplify-flutter#334]
**Describe the bug**
It's not possible to change authenticationFlowType after configuring Amplify (which only supports a single authentidatioonFlowType at one time). This means that it is not possible to use more than one authenticationFlowType in an app.

The use case for this would be switching to CUSTOM_AUTH (from USER_SRP_AUTH or USER_PASSWORD_AUTH) in order to trigger a custom authentication flow for a user to enable a custom challenge. 

The ability to switch authentication flows is supported in amplify-js: 
https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js

**To Reproduce**
1. Call with your default configuration, e.g. `Amplify.configure(amplifyconfig)`
2. Add the plugin `Amplify.addPlugin(AmplifyAuthCognito())`;
3. Attempt to reconfigure Amplify with a new configuration, e.g. `Amplify.configure(customconfig)`

**Expected behavior**
Amplify is reconfigured using the new configuration.

**Actional behavior**
Error thrown: `StateError (Bad state: Amplify has already been configured and re-configuration is not supported.)`

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by Amplifiyer** [comment]
@jcowley Thanks for raising this issue. I'm marking this as a feature request as by architecture, Amplify for iOS and Android does not support reconfiguration.

**Comment by dnys1** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-flutter/issues/410. Updates on support for the custom auth flow will be posted there.

**Comment by jcowley** [comment]
@dnys1 This is not at all the same as #410. They are completely different.

This ticket refers to the ability to *switch* authentication flows after amplify is configured (i.e. at runtime) like you can in the js client.

**Comment by dnys1** [comment]
My apologies, @jcowley. I've re-opened the ticket. I believe this is a general request for re-configuring Amplify at runtime, is that correct?

**Comment by twink1e** [comment]
This feature will be really helpful for supporting both CUSTOM_AUTH and USER_SRP_AUTH at run time, and JS SDK already supports it. Really appreciate it if can be included in a new release 🙏

**Comment by abdallahshaban557** [comment]
We have released this feature! The documentation is available here https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/#switching-authentication-flow-at-runtime
