### ISSUE TITLE
Flutter Datastore Error Serializing Error on Sync

### ISSUE THREAD

**Issue by rlefflerElite** [aws-amplify/amplify-flutter#3358]
### Description

I am running my flutter app and during the datastore sync process I am getting this error:

Caused by: ApiException{message=Amplify encountered an error while deserializing an object., cause=com.google.gson.JsonParseException: Got JSON from an API call which was supposed to go with a List but is in the form of an object rather than an array. It also is not in the standard format of having an items property with the actual array of data so we do not know how to deserialize it., recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

After much debugging, my appsync subscription quota is set to 200, but my models are pushing it to 201.  When it throws the error on sync, Datastore is trying to serialize the error message into one of my models.

This is only occurring in Flutter.  On web the error is handled appropriately.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Inlcude 1 model over what your subscription quota is (1 model = 3 subscriptions, so at the base 100 subscriptions you should be able to replicate at 34 models)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.11.0-6.0.pre.115

### Amplify Flutter Version

^1.1.1

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @rlefflerElite thanks for sharing this issue.  

Can you share the code you're using to trigger this issue?  From what you've said I'm assuming you're running the method Amplify.DataStore.observe on 33+ models and that one of the last method calls is failing?  Where is this code block called in relation to your app startup logic?

**Comment by rlefflerElite** [comment]
@fjnoyp This is happening on sync, at the start of the Flutter app after login.  In my main I am calling await Amplify.addPlugins([
  AmplifyAuthCognito(),
      AmplifyStorageS3(),
      AmplifyAPI(modelProvider: ModelProvider.instance),
      AmplifyDataStore(
        errorHandler: (error) {
          print(error);
        },
        modelProvider: ModelProvider.instance,
        syncExpressions: [
 DataStoreSyncExpression(Job.classType, () {
              Job.REGIONID.eq(regionId);
          }),
          DataStoreSyncExpression(Note.classType, () => Note.REGIONID.eq(regionId)),
          DataStoreSyncExpression(NoteThread.classType, () => NoteThread.REGIONID.eq(regionId)),
......

and then    await Amplify.configure(amplifyconfig);


The issue is coming from the sync.  Datastore expects 3 subscriptions for each model in your schema.  My current Appsync Connection limit is 200.  I have 67 models * 3 subscriptions = 201 which puts me over the limit.  This is when I see the error above occur.  

It seems like with the error message coming back, there is an attempt to serialize the error message into one of the models which fails.  If I remove a model from my schema and stay at 198 subscriptions, everything works fine.

**Comment by fjnoyp** [comment]
@rlefflerElite thank you for the information.  We'll work to reproduce on our side and get back to you here.

**Comment by fjnoyp** [comment]
Hi @rlefflerElite have you saved models for each of the 30+ different model types?  

In my reproduction with syncExpressions with 35 different models, no crash or error occurs.  

Can you share your modelSchema and the code you use to help us reproduce?

**Comment by fjnoyp** [comment]
Hi @rlefflerElite closing for now since we haven't heard back.  Feel free to open again or contact us with any other issues you might have.

**Comment by HusseinReda97pro** [comment]
This error still happens with me, 
what I observed is this error come after my tables count be more than 34 table, if I drop any one it works fine
