### ISSUE TITLE
Hub Event Sequence Not Compatible with Prior Version

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-flutter#3367]
### Description

Previously, I used the Hub.listen method to determine if the Datastore was ready (see below). The code now throws the error **and will not build**

```The argument type 'List<HubChannel<DataStoreHubEventPayload, DataStoreHubEvent>>' can't be assigned to the parameter type 'HubChannel<dynamic, HubEvent<dynamic>>'.```

```
  Future<void> _startAmplify() async {
    try {
      if (Amplify.isConfigured) {
        await Amplify.DataStore.clear();
        await Amplify.DataStore.start();
        hubSubscription =
            Amplify.Hub.listen([HubChannel.DataStore], (dynamic event) async {
          print('Event: ${event.eventName}');
          setState(() {
            completed += (0.98 / 12.0);
          });
          if (event.eventName == 'ready') {
            List<Account> result =
                await Amplify.DataStore.query(Account.classType);
            if (result.length > 0) {
              if (result[0].subscriptionId == '') {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content:
                        const Text('Complete your subscription'),
                    action: SnackBarAction(
                      label: 'OK',
                      onPressed: () {},
                    ),
                  ),
                );
                Navigator.pushReplacementNamed(context, '/');
              }
              if ((result[0].customerStatus == 'SUSPENDED') ||
                  (result[0].customerStatus == 'TRANSITIONED')) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                      content: const Text('Account has been suspended'),
                      action: SnackBarAction(
                        label: 'OK',
                        onPressed: () {},
                      )),
                );
                Navigator.pushReplacementNamed(context, '/');
              }
              if ((result[0].customerStatus == 'INITIAL') ||
                  (result[0].customerStatus == 'NORMAL')) {
                if (widget.destination == 'main') {
                  Navigator.pushReplacementNamed(context, '/main',
                      arguments: 'contact');
                } else {
                  Navigator.pushReplacementNamed(context, '/panic');
                }
              }
              if (result[0].customerStatus == 'BASIC') {
                Navigator.pushReplacementNamed(context, '/panic');
              }
            } else {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content:
                      const Text('Complete your subscription'),
                  action: SnackBarAction(
                    label: 'OK',
                    onPressed: () {},
                  ),
                ),
              );
              Navigator.pushReplacementNamed(context, '/');
            }
          }
        });
      }
    } catch (exception, stackTrace) {
      await Sentry.captureException(
        exception,
        stackTrace: stackTrace,
      );
    }
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

No steps required...application (which previously ran correctly) does not build now.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @ianfmc sorry to hear you're having this issue.  Have you upgraded your pubspec version of Amplify or ran flutter pub get recently?

**Comment by ianfmc** [comment]
Hi @fjnoyp: I am concerned that update my Amplify version will lead to a whole new flurry of dependency problems. Are there fixes for this issue in later versions of the amplify libraries? I'm using the code from the [latest documentation](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/). Thanks.

**Comment by fjnoyp** [comment]
Hi @ianfmc it shouldn't be possible for 3rd party code like Amplify to suddenly stop compiling unless the version was upgraded somehow.  I think unintentionally you might have already upgraded your Amplify version - you can provide your pubspec.yaml for us to double check. 

Otherwise, the fix here is very simple, please remove the [] surrounding HubChannel.Datastore, a single value instead of a list is expected in the API now.

We will update the docs to remove the [] that don't compile anymore. 

Change: 
`Amplify.Hub.listen([HubChannel.DataStore] 
`
To: 
`Amplify.Hub.listen(HubChannel.DataStore
`

**Comment by fjnoyp** [comment]
Updated docs here: 

https://github.com/aws-amplify/docs/pull/5629

**Comment by ianfmc** [comment]
@fjnoyp thanks so much. I did neglect to mention that it worked with 0.6.* and did upgrade to 1.0.0. I'll give that whirl.

**Comment by ianfmc** [comment]
Hi again, @fjnoyp: 

the new error is (after removing the square brackets) is: 

```Couldn't infer type parameter 'E'.  Tried to infer 'HubEvent<dynamic>' for 'E' which doesn't work: Type parameter 'E' is declared to extend 'HubEvent<HubEventPayload>' producing 'HubEvent<DataStoreHubEventPayload>'. The type 'HubEvent<dynamic>' was inferred from: Return type declared as 'StreamSubscription<E>' used where 'StreamSubscription<HubEvent<dynamic>>?' is required.  Consider passing explicit type argument(s) to the generic.```

Please note I have declared the StreamSubscription both ways below:
```
StreamSubscription<HubEvent>? hubSubscription;
StreamSubscription<HubEvent<dynamic>>? hubSubscription;
```

Please advise! Thanks...

**Comment by fjnoyp** [comment]
Hi please update to: 

  late StreamSubscription<DataStoreHubEvent> hubSubscription;

**Comment by ianfmc** [comment]
Thanks so much @fjnoyp. Unfortunately, I'm still getting type errors but during build now, at least (:

I changed the declaration of hubSubscription to match your suggestion. 

The call to listen looks like this:

```
        hubSubscription =
            Amplify.Hub.listen(HubChannel.DataStore, (event) async {
          print('Event: ${event.eventName}');
```

**The error is:** 

```
lib/login/loading.dart:43:25: Error: Inferred type argument 'HubEvent<Object?>' doesn't conform to the bound 'HubEvent<HubEventPayload>' of the type variable 'E' on 'AmplifyHub.listen'.
 - 'HubEvent' is from 'package:amplify_core/src/hub/hub_event.dart' ('../../.pub-cache/hosted/pub.dev/amplify_core-1.0.1/lib/src/hub/hub_event.dart').
 - 'Object' is from 'dart:core'.
 - 'AmplifyHub' is from 'package:amplify_core/src/hub/amplify_hub.dart' ('../../.pub-cache/hosted/pub.dev/amplify_core-1.0.1/lib/src/hub/amplify_hub.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
            Amplify.Hub.listen(HubChannel.DataStore, (event) async {
```

_Do I need to case the event parameter of the anonymous function somehow?_

**Comment by fjnoyp** [comment]
Hi @ianfmc can you try switching the `hubSubscription` to:

`late StreamSubscription<DataStoreHubEvent> hubSubscription;`

**Comment by fjnoyp** [comment]
Thanks again sharing your issues here.  It looks like our docs are not accurate so we have a docs PR with accurate/up-to-date API usage information:

https://github.com/aws-amplify/docs/pull/5629

**Comment by cwomack** [comment]
Closing this issue now that docs PR [#5629](https://github.com/aws-amplify/docs/pull/5629) has been merged in.
