### ISSUE TITLE
DataStore Exception

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#3369]
### Description

unforunately getting this issue today 

- Even i have deployed the model and did pull the changes 
- Uninstalled the app and tried to run
- did amplify datastore.clear

Query API failed. Error = DataStoreError: The operation couldn’t be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn’t be completed. (SQLite.Result error 0.)
Caused by:
no such table: AmpList (code: 1)
2023-07-07 11:11:26.475527+0530 Assist[7719:847336] flutter: DataStoreException(message: The operation couldn’t be completed. (SQLite.Result error 0.), recoverySuggestion: The operation couldn’t be completed. (SQLite.Result error 0.), underlyingException: The operation couldn’t be completed. (SQLite.Result error 0.))

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @Aruljebaraj sorry to hear you're having some problems using Datastore.  Can you provide more details on how you pushed your models?  In your project did you run amplify codegen models and then amplify push?

**Comment by fjnoyp** [comment]
Hi @Aruljebaraj since we haven't heard back from you in 2 weeks we're going to close this issue for now.  Please reopen and comment with answers to our questions or feel free to open a new issue as you wish.  Thanks for your understanding!
