### ISSUE TITLE
Cannot Build App

### ISSUE THREAD

**Issue by ryanmdd** [aws-amplify/amplify-flutter#337]
**Describe the bug**
Getting an error while doing: flutter build ios 

**To Reproduce**
1. rm -rf iod/Podfile
2. flutter build ios

**Expected behavior**
Ann application that will run in the simulator.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**

**Additional context**
this is error log from the flutter build:
~/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_flutter-0.0.2-dev.1/ios/Classes/SwiftAmplify.swift:56:42: error: type 'AmplifyAWSServiceConfiguration' has no member 'addUserAgentPlatform'
              AmplifyAWSServiceConfiguration.addUserAgentPlatform(.flutter, version: version)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~

~/development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_flutter-0.0.2-dev.1/ios/Classes/SwiftAmplify.swift:56:64: error: cannot infer contextual base in reference to member 'flutter'
              AmplifyAWSServiceConfiguration.addUserAgentPlatform(.flutter, version: version)
                                                                  ~^~~~~~~

**Comment by Amplifiyer** [comment]
What is the version of `AWSPluginsCore` in your Podfile.lock file? Can you try deleting your lock file and running `flutter build ios` again?

**Comment by ryanmdd** [comment]
I have tried deleting the Podfile.lock and I will try again.

Looks like my lock file is using:
AWSPluginsCore (= 1.0.4)
Here is the checksum (I don’t know if that helps):
AWSPluginsCore: 646f8c2d831a52f2293da0dfd59a31eee61f6ad5

Thanks

**Comment by Amplifiyer** [comment]
@ryanmdd, it's a very old version, it should be 1.5.0 or newer in your Podspec.lock file. Let us know if deleting the lock file (and `flutter clean`) helps to get the latest package versions.

**Comment by Amplifiyer** [comment]
We are not able to reproduce this issue. In our next release we will be pinning the iOS library version as well to avoid this in the future.
