### ISSUE TITLE
Unhandled DataStoreHubEvent: SUCCEEDED

### ISSUE THREAD

**Issue by dgagnon** [aws-amplify/amplify-flutter#3389]
### Description

Datastore will initialize on 1.2.1 but not start automatically:
[  +47 ms] I/amplify:aws-datastore(24399): DataStore plugin initialized.
[   +1 ms] I/amplify:flutter:datastore(24399): Unhandled DataStoreHubEvent: SUCCEEDED
[        ] I/amplify:flutter:datastore(24399): com.amplifyframework.core.category.CategoryInitializationResult@3ae0d3

full logs: [fulllogs.txt](https://github.com/aws-amplify/amplify-flutter/files/11992375/fulllogs.txt)  

Indeed, I am unable to find a way to listen to the suceeded event from the documentation, even after incorporating the changes in https://github.com/aws-amplify/docs/pull/5629.  See https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#ready  

The other types are in this folder: \amplify_core-1.2.1\lib\src\types\datastore\hub  
I was unable to find any reference to the ready event anywhere.

Being able to listen to this event is very useful to initialize the application.

**Datastore will start if you issue a query however.**

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. create a project using the getting started guide
2. Add default authentication without social and iam as secondary auth
3. add datastore and any model
4. try starting the app

### Screenshots

```dart
// Amplify Flutter Packages
import 'dart:async';

import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';
import 'models/ModelProvider.dart';
import 'src/app.dart';
import 'src/settings/settings_controller.dart';
import 'src/settings/settings_service.dart';

/// ProjectPipeline's documentation project.
/// {@category Architecture}
void main() async {
  // Future<void> createTask(String id) async {
  //   try {
  //     await Amplify.DataStore.save(Task(title: 'title'));
  // await Amplify.DataStore.save(Task(title: 'title', createdAt: TemporalDateTime.now()));
  // } on DataStoreException catch (e) {
  //   safePrint('Something went wrong updating model: ${e.message}');
  // }
  // }
  bool isAmplifyConfigured = false;
  late StreamSubscription<DataStoreHubEvent> hubSubscription;

  // Initialize a boolean indicating if the network is up
  bool datastoreIsUp = false;

  Future<void> configureAmplify() async {
    // Add any Amplify plugins you want to use
    final authPlugin = AmplifyAuthCognito();

    // Add the following lines to your app initialization to add the DataStore plugin
    final datastorePlugin = AmplifyDataStore(
      modelProvider: ModelProvider.instance,
      // Be sure to add the authModeStrategy
      authModeStrategy: AuthModeStrategy.multiAuth,
      // https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan
      syncExpressions: [
        DataStoreSyncExpression(
          User.classType,
          () => User.STATUS.eq(UserStatus.ACTIVE),
        ),
        DataStoreSyncExpression(
          Project.classType,
          () => Project.STATUS.eq(Status.ACTIVE),
        ),
        DataStoreSyncExpression(
          Task.classType,
          () => Project.STATUS.eq(Status.ACTIVE),
        )
      ],
    );

    final api = AmplifyAPI();

    // You can use addPlugins if you are going to be adding multiple plugins
    await Amplify.addPlugins([authPlugin, api, datastorePlugin]);
    // await Amplify.addPlugins([authPlugin]);

    // Once Plugins are added, configure Amplify
    // Note: Amplify can only be configured once.
    try {
      hubSubscription = Amplify.Hub.listen(HubChannel.DataStore, (hubEvent) {
        if (hubEvent is NetworkStatusEvent) {
          final status = hubEvent.payload as NetworkStatusEvent?;
          datastoreIsUp = status?.active ?? false;
        }
        safePrint(hubEvent.eventName.toString());
      });

      await Amplify.configure(amplifyconfig);
      // when starting the app and not logged in, datastore will generate some errors, but they can be ignored.
      // close and restart the app to have the tokens available and successfully start the datastore.
      isAmplifyConfigured = true;
    } on AmplifyAlreadyConfiguredException {
      safePrint("Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
  }

  WidgetsFlutterBinding.ensureInitialized();
  await configureAmplify();

  // Set up the SettingsController, which will glue user settings to multiple
  // Flutter Widgets.
  final settingsController = SettingsController(SettingsService());

  // Load the user's preferred theme while the splash screen is displayed.
  // This prevents a sudden theme change when the app is first displayed.
  await settingsController.loadSettings();

  // Run the app and pass in the SettingsController. The app listens to the
  // SettingsController for changes, then passes it further down to the
  // SettingsView.
  runApp(MyApp(settingsController: settingsController));

  final result = await Amplify.Auth.fetchAuthSession();
  safePrint('User is signed in: ${result.isSignedIn}');
  // await createTask('1234123123');
}
```

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.0-supports-only-mobile+1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
# TODO: look into making a UserInterface and a PPInterface: https://graphql.org/learn/schema/#interfaces
enum Status {
    ACTIVE
    COMPLETED
    DELETED
}

enum UserStatus {
    ACTIVE
    SUSPENDED
    DELETED
}

type User @model @auth(rules: [{ allow: owner}, {allow: private, provider: iam}]) {
    id: ID! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}])
    username: String! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}])
    data: String @auth(rules: [{ allow: owner }, {allow: private, provider: iam}])
    # TODO: https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan
    status: UserStatus @default(value: "ACTIVE" ) @index(name: "byStatus", sortKeyFields: ["createdAt"]) @auth(rules: [{ allow: owner }, {allow: private, provider: iam}])
    owner: String @auth(rules: [{ allow: owner, operations: [read, create, delete] }, { allow: private, provider: iam }])
    createdAt: AWSDateTime! @auth(rules: [{ allow: owner }, { allow: private, provider: iam }])
}
type Project @model @auth(rules: [{ allow: owner}, {allow: private, operations: [read]}, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }]) {
    id: ID! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    title: String! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    description: String @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    data: String @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    status: Status @default(value: "ACTIVE" ) @index(name: "byStatus", sortKeyFields: ["createdAt"]) @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    dueAt: AWSDateTime! @auth(rules: [{ allow: owner}, { allow: private, provider: iam }, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    createdAt: AWSDateTime! @auth(rules: [{ allow: owner }, {allow: private, operations: [read]}, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    owner: String @auth(rules: [{ allow: owner, operations: [read, create, delete] }, { allow: private, provider: iam }, {allow: private, operations: [read]},{ allow: groups, groups: ["admin"] }])
    tasks: [Task] @hasMany(indexName: "byProject", fields: ["id"]) #https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
}
type Task @model @auth(rules: [{ allow: owner}, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }]) {
    id: ID! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    title: String! @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    description: String @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    data: String @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    status: Status @default(value: "ACTIVE" ) @index(name: "byStatus", sortKeyFields: ["createdAt"]) @auth(rules: [{ allow: owner }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    dueAt: AWSDateTime! @auth(rules: [{ allow: owner }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    # https://docs.amplify.aws/cli/graphql/authorization-rules/#multi-user-data-access
    #    owners: [String]
    # BUG: https://github.com/aws-amplify/amplify-flutter/issues/1566
    owner: String @auth(rules: [{ allow: owner, operations: [read, create, delete] }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    projectID: ID! @index(name: "byProject", sortKeyFields: ["createdAt"]) #https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
    project: Project @belongsTo(fields: ["projectID"])
    createdAt: AWSDateTime! @auth(rules: [{ allow: owner }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
}
```

**Comment by dgagnon** [comment]
@fjnoyp yes this works.   
I figured I'd report on the "Unhandled DataStoreHubEvent" in case it creates other issues down the road.  

I was under the impression that datastore was starting automatically before (which I did not like, since it would throw errors before sign in), but it appears it may have been something else triggering it before sign in.  

I am happy with the current behavior of not starting on configure().

**Comment by dgagnon** [comment]
Here is a use case for the succeeded event.  My understanding is that it gets triggered when Datastore is not "ready", but is available.  If there is already data in it, you can query it at this point.

This would help with doing two stage loading of Datastore when it contains lots of object and loading time becomes an issue.

**Comment by Jordan-Nelson** [comment]
Hi @dgagnon - If you want to receive data during sync, observeQuery might meet your use case. See: https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time

From the docs:
> While data is syncing from the cloud, snapshots will contain all of the items synced so far and an isSynced status of false. When the sync process is complete, a snapshot will be emitted with all the records in the local store and an isSynced status of true.

`isSynced` will be true as soon as _**that specific model**_ has completed syncing, which could be long before the `ready` event is emitted since `ready` is not emitted until _ALL_ models have finished syncing.

**Comment by dgagnon** [comment]
Thanks for getting back to me so fast @Jordan-Nelson.

The problem we are trying to address is slow load time.  I am going at it through many different path, this is one of the ideas I had.

Here is a concrete use case: online store supporting an offline catalogue.  2 models, User (owner ACL) and Product (private).  User contains the user's settings and profile info and Product contains 20 000 product entries we want to be able to search on the device.

The normal sequence to load the app would wait for the ready event to navigate the user to the home screen.  As many have pointed out, this makes the initial sync run in the minutes (worst on Android).  Subsequent loads are much faster until the next base full load is done again.  Moreover, with a lots of Model, setting up all the sync takes up quite a bit of time too.

> When the app launches, you would like to determine if there is data on the device from a previous sync. You would like to do this prior to the sync process staring (prior to DataStore.start being called) Is that correct?

Yes, that would be great.  It would allow loading the User model instance to get the user's profile, load the app and let the store show a loading animation while the datastore syncs.  Obviously, this would not help on initial loading.

For initial loading, being able to specify model load order would be needed, although in my limited tests, my User model always loads first (is first in the schema file and is first syncExpressions).  

As a side note, I notice most user's of amplify seem to have some form of User model or another and I was wondering if maybe it shouldnt be built-in and integrated with the Auth.

**Comment by Jordan-Nelson** [comment]
I see. So it sounds like you also would like to adjust the sync expression based on whether or not a prior sync has taken place. Is that also correct?

I don't think there is currently a way to determine if there was previously a sync without performing some operation that starts DataStore (and then starts a sync). There might be some ways to work around it though.

You could query a model that you know will always be synced (the current user's profile for example). If there is data, there must have been a sync. Running that query will start DS if it was not already started, which would then start a sync. Assuming you want to adjust the sync query based on prior sync status, you would have to stop/start DS.

Another option might be to store a flag in device storage (using something like [shared_preferences](https://pub.dev/packages/shared_preferences)).

I don't think the SUCCESS event indicates if there was previously a sync. It is possible it is only logged when there was a previous sync, but I am not sure that is the intention. However, we could track this as a feature request for the ability to determine sync status prior to start. A hub event would be one possible solution for that.

**Comment by dgagnon** [comment]
> I see. So it sounds like you also would like to adjust the sync expression based on whether or not a prior sync has taken place. Is that also correct?

Correct.  More details on this here:  https://github.com/aws-amplify/amplify-flutter/issues/1479#issuecomment-1664382706

> You could query a model that you know will always be synced (the current user's profile for example). If there is data, there must have been a sync. Running that query will start DS if it was not already started, which would then start a sync. Assuming you want to adjust the sync query based on prior sync status, you would have to stop/start DS.

As this starts it, it is non ideal, but seems one of the few viable options.


> Another option might be to store a flag in device storage (using something like [shared_preferences](https://pub.dev/packages/shared_preferences)).

Not a bad idea!  thanks.

> I don't think the SUCCESS event indicates if there was previously a sync. It is possible it is only logged when there was a previous sync, but I am not sure that is the intention. However, we could track this as a feature request for the ability to determine sync status prior to start. A hub event would be one possible solution for that.

I am not 100% sure this really is the right approach.   If others express their interest, sure!

**Comment by Jordan-Nelson** [comment]
@dgagnon - Were you able to use something like shared_preferences to meet your use case?

Let me know if you would like to convert this into a feature request, otherwise I will close it out. Thanks.

**Comment by dgagnon** [comment]
@Jordan-Nelson I am still hitting an issue preventing me from moving forward with this:  https://github.com/aws-amplify/amplify-flutter/issues/1479#issuecomment-1664382706

I see other people seem to have success in updating syncExpression, so I tend to think the issue on our side, but I really can't figure out why it's not working.  I can open this is a standalone issue and remove my comment from the original issue I added it too.

**Comment by Jordan-Nelson** [comment]
If you can open a separate issue with the info in the issue template and any errors and/or stack traces, that would be great.

**Comment by Jordan-Nelson** [comment]
@dgagnon - I am going to close this issue since I believe the original issue was discussed/resolved. The summarize - You can safely ignore the unhandled event. If you are looking for a way to check when there was a previous sync, we could open a feature request for that, but currently you could achieve that through a workaround as mentioned [here](https://github.com/aws-amplify/amplify-flutter/issues/3389#issuecomment-1665905907).

If you are seeing an issue with the sync expression, please open a separate issue with the details from the issue template and we can look into it.
