### ISSUE TITLE
Amplify developer menu in debug mode

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#342]
Hi guys. 

Is there any way to disable the developer menu in debug mode? It disturbs me when I am debugging my app in a physical device. I think the developer menu should be a customizable option in the Amplify Flutter SDK.

**Comment by haverchuck** [comment]
@brunovsiqueira We have a fix to temporarily silence this entirely until we can make it properly customizable.

**Comment by brunovsiqueira** [comment]
Nice! When do you guys are planning to release it?

**Comment by Amplifiyer** [comment]
This is released today in version 0.0.2-dev.2. Let us know if you are still facing any issues. Closing this.
