### ISSUE TITLE
Amplify Auth allow users login  after deleting users from database

### ISSUE THREAD

**Issue by lebe24** [aws-amplify/amplify-flutter#3423]
### Description

The user could log in to the application after deleting the user from the app using amplify studio.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

No response

### Screenshots

No response

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.0.0

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
No response
```

**Comment by Equartey** [comment]
Hey @lebe24,

Sorry you are experiencing this issue. 

Could you please provide more detailed reproduction steps?

The more detailed the better, please include atleast the following:

1. Are you signing out after the user has been deleted and able to sign back in as the same user?
2. Where and how you are deleting the user (eg. from app, studio ui, etc)? 
3. What platform are you trying to sign in on? Does this problem exist on multiple platforms?
4. Are you using the [Amplify Flutter Authenticator UI](https://ui.docs.amplify.aws/flutter/connected-components/authenticator) project?

**Comment by lebe24** [comment]
Hi @Equartey 

The issue is i deleted a demo user from the amplify studio user management, and the said user was able to access the app so if the user never logout, said user can still access the app.

This might be in the amplify auth package in flutter which handle the authentication interface that automatic sign in user even when the device is not connected to the internet.

**Comment by lebe24** [comment]
issue has been resolved
