### ISSUE TITLE
Bad State: No Instance found for AuthConfiguration

### ISSUE THREAD

**Issue by wyc-wyll** [aws-amplify/amplify-flutter#3453]
### Description

I was trying to implement the isUserSignedIn() and getCurrentUser() method from the getting started guide on auth section. However, when I try to call the function it says 

> Bad State: No Instance found for AuthConfiguration

I then checked the amplify configuration function and see if anything is wrong but everything looks fine. I have the awaits added to plugins and configure functions. I am not sure what is wrong here and would need some guidance on how to solve this. Much Appreciated :)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

```
Future<void> _configureAmplify() async {
  try {
    // Initialize Plugins
    final auth = AmplifyAuthCognito();
    final api = AmplifyAPI();
    final datastore = AmplifyDataStore(modelProvider: ModelProvider.instance);

    await Amplify.addPlugins([
      // Plugin list
      auth,
      api,
      datastore,
    ]);

    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException catch (e) {
    safePrint("Amplify Configuration Error: ${e.message}");
  }
}
```

<img width="962" alt="Screenshot 2023-07-21 at 11 00 25 AM" src="https://github.com/aws-amplify/amplify-flutter/assets/113057252/bab9a7a9-dc83-42d4-9936-1baaede99697">

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@wyc-wyll - Is it possible that `isUserSignIn()` is called prior to `_configureAmplify()` completes?

**Comment by wyc-wyll** [comment]
with some inspiration from you I use await when I call the _configureAmplify() function and now it works. That was a minor mistake I made but thank you so much for the direction :)
