### ISSUE TITLE
Weird behaviour using API GraphQL - AppSync

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3458]
### Description

I noticed a really weird behavior while using Amplify API GraphQL when specifying a limit to a query.
I have a table with 30 items in it. Whenever I filter items based on some conditions with a limit, sometimes I get an empty response even though the items are there in my database.
For example:
```dart
      final request = ModelQueries.list(
        Place.classType,
        where: Place.MAXCAPACITY.gt(200),
        limit: 3,
      );

      final response = await Amplify.API.query(request: request).response;
```
If I remove the limit, I get all items that satisfies the condition.

After further investigation, I realized that the limit is applied on the items before any filtering and only then the filters are applied.

Is that normal? And if yes, does this behavior have any good reason to be there?

Thank you for any clarifications.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Populate the database with 2 or 3 items.
2. Run a query with a filter(eq: lastItemName) on the last item in the database and a limit of 1 or 2 (depending on the number of items in a table)
3. The response will have no items in it

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.2.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Item @model @auth(rules: [{allow: private}]) {
  id: ID!
  itemName: String
}
```

**Comment by Equartey** [comment]
Hey @jamilsaadeh97 

Yes, what you see is expected behavior. I've provided a more response on to this question over [here](https://github.com/aws-amplify/amplify-flutter/issues/2006#issuecomment-1210728199). 

Let me know if you still have questions. I'm going to mark this as a duplicate and close.
