### ISSUE TITLE
Exception: No builder registered for SecureStorageInterface

### ISSUE THREAD

**Issue by markjoseultra** [aws-amplify/amplify-flutter#3460]
### Description

1. My app has been working for 2 months now, I didn't change any code then suddenly this error shows up when  
await Amplify.Auth.fetchAuthSession(); is called, I also tried  await Amplify.Auth.getCurrentUser(); same error.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a flutter app and integrate Amplify
2. Execute  await Amplify.Auth.fetchAuthSession(); or  await Amplify.Auth.getCurrentUser();

### Screenshots

![image](https://github.com/aws-amplify/amplify-flutter/assets/49055288/9e1a85b3-9083-4863-8844-dc38887dc701)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.1

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Thanks for confirming @markjoseultra. Can you also confirm that `init` is awaited before `isSignedIn` is called? My suspicion is that somehow `isSignedIn` is being called before `init` is complete which would lead to the error you're seeing.

**Comment by markjoseultra** [comment]
Hi dnys1

It is awaited 
![image](https://github.com/aws-amplify/amplify-flutter/assets/49055288/26e541ad-89ed-4c28-b962-1cda4994b7a8)

**Comment by markjoseultra** [comment]
Hi Team

Any updates about this issue?

**Comment by dnys1** [comment]
Hi @markjoseultra, sorry for the delayed response. In order to better assist you, can you please provide a more complete listing of your application's code? From the snippets you've provided, the problem is still not clear to me.

**Comment by markjoseultra** [comment]
Hi Team, It's working again now, thanks.
