### ISSUE TITLE
Getting a 401 error when using the latest code for the tokens(v.1.2.1)

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#3466]
Hi,
I have migrated my amplify versions  from 
```
  amplify_flutter: ^0.6.1
  amplify_auth_cognito: ^0.6.1
```
to

```
  amplify_flutter: ^1.2.1
  amplify_auth_cognito: ^1.2.1
```
Old code
----------
```
  Future<Map<String, String>> fetchSessionToken(context) async {
    Map<String, String> tokens = {};
    String idToken = '';
    try {
      AuthSession res = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
      if (res.isSignedIn) {
        idToken = (res as CognitoAuthSession).userPoolTokens!.idToken.toString();
        tokens = {
          'idToken': (res).userPoolTokens!.idToken.toString(),
          'accessToken': (res).userPoolTokens!.accessToken.toString()
        };
      } else {
        try {
          signOut(context);
        } on AuthException catch (e) {}
      }
    } on AuthException catch (e) {
    }
    return tokens;
  }
```

Latest code
-----------

```
  Future<Map<String, String>> fetchSessionToken(context) async {
    Map<String, String> tokens = {};
    try {
      final cognitoPlugin = Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
      final res = await cognitoPlugin.fetchAuthSession();
      if (res.isSignedIn) {
        print('accessToken===0${res.userPoolTokensResult.toJson()}');
        print('accessToken===1${res.userPoolTokensResult.value.accessToken.encode()}');
        print('accessToken===2${res.userPoolTokensResult.value.accessToken.encode().toString()}');
        print('accessToken===3${res.userPoolTokensResult.value.accessToken.toString()}');
        tokens = {
          'idToken': res.userPoolTokensResult.value.idToken.encode().toString(),
          'accessToken': res.userPoolTokensResult.value.accessToken.encode().toString()
        };
      } else {
        try {
          signOut(context);
        } on AuthException catch (e) {}
      }
    } on AuthException catch (e) {
    }
    return tokens;
  }
```

But when I'm using the latest code token, I always get a 401 error from our backend APIs. Any idea why it is happening like that? Is it because of encoding or something?

**Comment by Jordan-Nelson** [comment]
Hi @Sunsiha - Just to clarify, the network calls that result from `fetchAuthSession()` are returning 401?

**Comment by Sunsiha** [comment]
> Hi @Sunsiha - Just to clarify, the network calls that result from `fetchAuthSession()` are returning 401?

NO! I am able to see the token in the console. However, when I try to use that ID token and access token, I am getting a 401 error.

**Comment by dnys1** [comment]
Can you share the fully error + stack trace you receive while debugging?

**Comment by Sunsiha** [comment]
> Can you share the fully error + stack trace you receive while debugging?

When I try the same tokens in Postman, the response is only showing AUTHENTICATION_ERROR. I believe it's not something related to a code issue. If it were a code issue, it should work in Postman as well.

**Comment by dnys1** [comment]
To be clear, the code you've posted above for _retrieving_ the access and ID tokens does not fail, but it is when you _use_ the tokens in the `Authorization` header of an API call that you get a 401. Is that correct?

If so, can you be very specific about how you are using the tokens in your API call? Are you using the access or ID? What is the format of the `Authorization` header you're using? Which API are you trying to access with the tokens?

**Comment by Sunsiha** [comment]
> To be clear, the code you've posted above for _retrieving_ the access and ID tokens does not fail, but it is when you _use_ the tokens in the `Authorization` header of an API call that you get a 401. Is that correct?
> Yes!
> If so, can you be very specific about how you are using the tokens in your API call? Are you using the access or ID? What is the format of the `Authorization` header you're using? Which API are you trying to access with the tokens?
Both tokens are using. For the key Authorization sending as IDtoken, and x-access-token as access token. 

The API's are our micro service api's. Not cognito one.

**Comment by Sunsiha** [comment]
@dnys1  Hey it has problem with encoding.

When I tried like the following it worked proper. 
```
 tokens = {
          'idToken': res.userPoolTokensResult.value.idToken.toJson().toString(),
          'accessToken': res.userPoolTokensResult.value.accessToken.toJson().toString()
        };
```

**Comment by dnys1** [comment]
Understood, thanks for clarifying. I would recommend using `idToken.raw` and `accessToken.raw` for accessing the encoded JWT string.

Is your issue resolved now?
