### ISSUE TITLE
iOS to Flutter App Migration User Login

### ISSUE THREAD

**Issue by iamumit** [aws-amplify/amplify-flutter#3468]
### Description

I am migrating an native iOS application to Flutter. The main application is developed as native on iOS side. I'm installing the native application to device. Login to app with using AWS Amplify.

Then installing the Flutter app to device and same app is updating. We are using same user pools so I'm expecting app should start from home page as logged in but `getCurrentUser` and `fetchAuthSession` returns null. So app sending us to login flow again. 

So we are using same user pool and user already logged in. Is there any way to stay user logged in? I couldn't refresh token and reach to current user.

`getCurrentUser` returns => "_No user is currently signed in_"
`fetchAuthSession` returns => "_No identity pool registered for this account_"

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Install the native app on an iOS device.
2. Sign in to the app using the native AWS sign-in flow.
3. Close the app.
4. Install the flutter app on an iOS device.
5. When app opened, user will be logged out and sends to login page.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.4

### Amplify Flutter Version

1.1.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Does the native app use the Amplify iOS or Amplify Swift libraries? If so, what version of those libraries are used?

**Comment by iamumit** [comment]
> Does the native app use the Amplify iOS or Amplify Swift libraries? If so, what version of those libraries are used?

using these libraries on native iOS side :

```
  pod 'AWSMobileClient'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSAppSync', '~> 3.1.13'
```

**Comment by Jordan-Nelson** [comment]
What version of `AWSMobileClient` and `AWSCognitoIdentityProvider` are you using?

We don't officially support automatically migrating credentials when migrating from a native iOS app to a flutter app. However, I would expect this to work if you were previously using `AWSMobileClient`.

Version 0.x of Amplify Flutter depends on `AWSMobileClient` for managing credentials, whereas version 1.x of Amplify Flutter manages them without any dependencies on Amplify iOS/Swift. We support automatically migrating credentials when upgrading from v0 of Amplify Flutter to v1 of Amplify Flutter, which involves migrating credentials from the location that `AWSMobileClient` stores them to the location that they are stored in for v1.

This migration is one time only though. If you are switching back and forth between the native version and the flutter version, it would only perform the migration one time. If you have been switching back and forth, try uninstalling the app completely, and then follow the repro steps.

**Comment by Jordan-Nelson** [comment]
@iamumit - I am going to close this out since there is an open request for migrating to amplify_flutter with tokens.

**Comment by iamumit** [comment]
> @iamumit - I am going to close this out since there is an open request for migrating to amplify_flutter with tokens.

So I decided to logout users for switch environment to Flutter one. Thank you for your support! We can close the ticket
