### ISSUE TITLE
Trigger GraphQL Subscription outside client mutations

### ISSUE THREAD

**Issue by Daeon97** [aws-amplify/amplify-flutter#3474]
**Prelude**
I have defined `Subscription` with the following fields in my client amplify Flutter app
```
type Subscription {
    onGetTrackerModule(id: Int!): TrackerModule
    onListTrackerModules: [TrackerModule]
}
```
For reference purposes I also defined `Mutation` like so
```
type Mutation {
    updateTrackerModuleName(input: UpdateTrackerModuleNameInput): String!
}

input UpdateTrackerModuleNameInput {
    id: Int!
    name: String!
}
```
then I updated my `Subscription` definition thus:
```
type Subscription {
    onGetTrackerModule(id: Int!): TrackerModule @aws_subscribe(mutations: ["updateTrackerModuleName"])
    onListTrackerModules: [TrackerModule] @aws_subscribe(mutations: ["updateTrackerModuleName"])
}
```

However, [I have a lambda function](https://github.com/Daeon97/iot-core-to-dynamo-db-function) that copies data from AWS IoT Core to AWS Dynamo DB

**My struggles**
I want the `Subscription` as defined in my client amplify Flutter app to be triggered whenever [my lambda function](https://github.com/Daeon97/iot-core-to-dynamo-db-function) copies data to DynamoDB. As can be observed above from my prelude the only way the client can get new events on subscription is when the `updateTrackerModuleName Mutation` is triggered by the client itself however, DynamoDB can also get new data added to it anytime [from my lambda function](https://github.com/Daeon97/iot-core-to-dynamo-db-function). I have literally combed through several AWS official docs and Stackoverflow questions, yet to no avail on how to achieve this

**Comment by dnys1** [comment]
Hi @Daeon97, that's an interesting use case! 

As mentioned in the [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) for subscriptions:

> Subscriptions in AWS AppSync are invoked as a response to a mutation.

This differs from, for example, an API Gateway [WebSocket API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview.html) which can achieve the same subscription capability but has the ability to invoke a subscription event at-will from the server.

For your use case, instead of copying directly into DynamoDB, could you instead save that to DynamoDB via a GraphQL mutation? If not, I may recommend exploring an API Gateway WebSocket API for your use case which would ultimately provide more flexibility. However, it is not something we support [out-of-the-box](https://github.com/aws-amplify/amplify-flutter/issues/2523) yet.

**Comment by dnys1** [comment]
I would also encourage checking out the [AppSync feedback repo](https://github.com/aws/aws-appsync-community/) and see if there is an issue which matches your request or if you can create one to alert their team.

**Comment by Daeon97** [comment]
> Hi @Daeon97, that's an interesting use case!
> 
> As mentioned in the [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) for subscriptions:
> 
> > Subscriptions in AWS AppSync are invoked as a response to a mutation.
> 
> This differs from, for example, an API Gateway [WebSocket API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview.html) which can achieve the same subscription capability but has the ability to invoke a subscription event at-will from the server.
> 
> For your use case, instead of copying directly into DynamoDB, could you instead save that to DynamoDB via a GraphQL mutation? If not, I may recommend exploring an API Gateway WebSocket API for your use case which would ultimately provide more flexibility. However, it is not something we support [out-of-the-box](https://github.com/aws-amplify/amplify-flutter/issues/2523) yet.



> I would also encourage checking out the [AppSync feedback repo](https://github.com/aws/aws-appsync-community/) and see if there is an issue which matches your request or if you can create one to alert their team.

Alright thanks alot for the quick response. I will explore the options you have outlined above and drop some feedback

**Comment by dnys1** [comment]
Closing this for now as I feel like AppSync or WebSocket API can be used for your use case. Please thumbs up the issue I mentioned if you'd prefer to use a WebSocket API over AppSync. And please let us know if you run into any more issues.
