### ISSUE TITLE
GraphQL Lambda authorizer not working

### ISSUE THREAD

**Issue by HidekiHiguchi** [aws-amplify/amplify-flutter#3480]
### Description

It seems as If it doesn't even get called, I had it working on another project on a much older version of amplify, If I recall correctly It had to be added manually back then.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. amplify update api
2. GraphQL
3. Authorization modes
4. Amazon Cognito User Pool
5. Configure additional auth types? y
6.  Select API Key and Lambda
7. Enter a description for the API key: · Graphql API Key
8. After how many days from now the API key should expire (1-365): · 365
9. Choose a Lambda authorization function Use a Lambda function already added in the current Amplify project (or create new)
10. ? Choose one of the Lambda functions graphQlLambdaAuthorizer6a425ddf
? How long should the authorization response be cached in seconds? 0
✅ GraphQL schema compiled successfully.

This is the generated lambda:
```
// This is sample code. Please update this to suite your schema

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  const {
    authorizationToken,
    requestContext: { apiId, accountId },
  } = event;
  const response = {
    isAuthorized: authorizationToken === 'custom-authorized',
    resolverContext: {
      // eslint-disable-next-line spellcheck/spell-checker
      userid: 'user-id',
      info: 'contextual information A',
      more_info: 'contextual information B',
    },
    deniedFields: [
      `arn:aws:appsync:${process.env.AWS_REGION}:${accountId}:apis/${apiId}/types/Event/fields/comments`,
      `Mutation.createEvent`,
    ],
    ttlOverride: 300,
  };
  console.log(`response >`, JSON.stringify(response, null, 2));
  return response;
};
```

main configuration:
```
  Future<void> _configureAmplify() async {
    try {
      final auth = AmplifyAuthCognito(
        secureStorageFactory: AmplifySecureStorage.factoryFrom(
          macOSOptions:
          // ignore: invalid_use_of_visible_for_testing_member
          MacOSSecureStorageOptions(useDataProtection: false),
        ),
      );
      final api = AmplifyAPI(
        authProviders: const [
          CustomFunctionProvider(),
        ],
        modelProvider: ModelProvider.instance,
      );
      await Amplify.addPlugins([api, auth]);
      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      safePrint('An error occurred configuring Amplify: $e');
    }
  }
```

When called I get: Not Authorized to access listCoreUserCoreBranches on type Query

### Screenshots

It doesn't even show up on cloudwatch, I suppose It doesn't even get called in the first place.

![image](https://github.com/aws-amplify/amplify-flutter/assets/11017830/267069c0-00c3-467b-acf8-c78317cf2443)

On AWS AppSync Console  it shows up

![image](https://github.com/aws-amplify/amplify-flutter/assets/11017830/52fc64a7-d07c-4bb1-8515-32bed0b5e092)

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.3

### Amplify Flutter Version

1.3.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type CoreUserCoreBranches @model @auth(rules: [

    { allow: public, provider: apiKey,  operations: [create, update, delete, read] }

    { allow: custom, provider: function, operations: [create, update, delete, read] }

]) {
    id: ID!
    coreUser: CoreUser! @belongsTo
    coreBranch: CoreBranch! @belongsTo
    tenant: [String]!
}
```

**Comment by dnys1** [comment]
Hi @HidekiHiguchi, can you please also provide the code snippet for where you're calling the API method?

**Comment by HidekiHiguchi** [comment]
Sure

```
  Future<List<CoreUserCoreBranches?>?> queryUserBranchesByUserId({required String userId}) async {
    final queryPredicate = CoreUserCoreBranches.COREUSER.eq(userId);
    GraphQLRequest request = ModelQueries.list<CoreUserCoreBranches>(CoreUserCoreBranches.classType,
        where: queryPredicate, authorizationMode:  APIAuthorizationType.function);
    
    final response = await Amplify.API.query(request: request).response;
    PaginatedResult<CoreUserCoreBranches> paginatedResult = response.data;
    
    return paginatedResult.items;
  }
```

**Comment by dnys1** [comment]
Can you provide the implementation of `CustomFunctionProvider`? The message "Not Authorized to access listCoreUserCoreBranches on type Query" implies that an authorization decision is being made.

Can you open the Dart DevTools: Network page and see if the Authorization header is being set correctly on the request?

**Comment by HidekiHiguchi** [comment]
> Can you provide the implementation of `CustomFunctionProvider`? The message "Not Authorized to access listCoreUserCoreBranches on type Query" implies that an authorization decision is being made.
> 
> Can you open the Dart DevTools: Network page and see if the Authorization header is being set correctly on the request?

@dnys1 


```
class CustomFunctionProvider extends FunctionAuthProvider {
  const CustomFunctionProvider();
  @override
  Future<String?> getLatestAuthToken() async  {
    String? token = (await Amplify.Auth.fetchAuthSession() as CognitoAuthSession)
        .userPoolTokensResult.value.accessToken.toJson();
    safePrint(token);
    return token;
  }
}
```
<img width="964" alt="Screenshot 2023-07-31 at 20 30 57" src="https://github.com/aws-amplify/amplify-flutter/assets/11017830/09ec3212-4e66-4850-9026-44f854e18287">

```
GraphQLResponse<dynamic> error: [
  {
    "message": "Not Authorized to access listCoreUserCoreBranches on type Query",
    "locations": [
      {
        "line": 1,
        "column": 114
      }
    ],
    "path": [
      "listCoreUserCoreBranches"
    ],
    "errorType": "Unauthorized"
  }
]
```

**Comment by dnys1** [comment]
Thank you, @HidekiHiguchi. Your Lambda specifies `isAuthorized: authorizationToken === 'custom-authorized'`. When you pass the Cognito access token as your authorization token, I would expect `isAuthorized: false` to be returned from the Lambda, which would lead to the **Not authorized** message you're seeing.

As for the Lambda logs, if you go to the Lambda console and search your function's name, you can click on its `Monitor` tab, then `View CloudWatch logs` to see the logs for the function.

**Comment by HidekiHiguchi** [comment]
> Thank you, @HidekiHiguchi. Your Lambda specifies `isAuthorized: authorizationToken === 'custom-authorized'`. When you pass the Cognito access token as your authorization token, I would expect `isAuthorized: false` to be returned from the Lambda, which would lead to the **Not authorized** message you're seeing.
> 
> As for the Lambda logs, if you go to the Lambda console and search your function's name, you can click on its `Monitor` tab, then `View CloudWatch logs` to see the logs for the function.

@dnys1  I wish that was it

<img width="939" alt="Screenshot 2023-07-31 at 20 46 18" src="https://github.com/aws-amplify/amplify-flutter/assets/11017830/26a7271f-a806-494c-9995-866acbb91a33">
<img width="1065" alt="Screenshot 2023-07-31 at 20 47 00" src="https://github.com/aws-amplify/amplify-flutter/assets/11017830/d83a62f8-afa0-42a1-b08d-dfabb9db3702">

**Comment by dnys1** [comment]
Can you try returning the string `custom-authorized` from your `CustomFunctionProvider` class and let me know if that works?

**Comment by HidekiHiguchi** [comment]
That worked!

I expected it to fail during the lambda call, but with an error log, thank you for your help @dnys1 !

<img width="766" alt="Screenshot 2023-07-31 at 21 00 42" src="https://github.com/aws-amplify/amplify-flutter/assets/11017830/e5732862-fd81-49f9-a6c8-51f462664a9d">

**Comment by dnys1** [comment]
My pleasure. I'm glad to hear that worked! 🥳 

I'm not sure why the Lambda did not print a log when it failed, but feel free to open an issue in the [AppSync community repo](https://github.com/aws/aws-appsync-community/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) if the issue continues.

**Comment by ilijanovic** [comment]
So whats the solution now?

If i send my accessToken like this:

  if (authMode === 'AWS_LAMBDA') {
    authToken = (await Auth.currentSession()).getAccessToken().getJwtToken()
  }
  return API.graphql<GraphQLQuery<R>>({
    ...graphqlOperation(operation, variables),
    authMode,
    authToken:authToken
  })

This does not work i get unauthorzied and my lambda authorizer does not even get invoked.

However, if i do:

  if (authMode === 'AWS_LAMBDA') {
    authToken = "teststring"
  }
  return API.graphql<GraphQLQuery<R>>({
    ...graphqlOperation(operation, variables),
    authMode,
    authToken:authToken
  })

It works, my lambda authorizers gets invoked, why is this?
