### ISSUE TITLE
Unauthenticated Routes documentation with GoRouter

### ISSUE THREAD

**Issue by pixnbit** [aws-amplify/amplify-flutter#3493]
### Description

I had to add `routeInformationProvider: appRouter.routeInformationProvider,` to make it work. The documentation might be outdated that doesn't have `routeInformationProvider` specified here: https://ui.docs.amplify.aws/flutter/connected-components/authenticator/customization

```
        return Authenticator(
          child: MaterialApp.router(
            title: '',
            debugShowCheckedModeBanner: false,
            theme: lightThemeData,
            darkTheme: darkThemeData,
            themeMode: ThemeMode.system,
            // routerConfig: appRouter,
            routeInformationProvider: appRouter.routeInformationProvider, // <= this line is missing in doc
            routeInformationParser: appRouter.routeInformationParser,
            routerDelegate: appRouter.routerDelegate,
            // builder: Authenticator.builder(),
          ),
        );
```

Another thing is I feel it might be a bit cumbersent to specify all screens that has to be wrapped with Authenticated view, can the framework do the other way, let the default behavior be the authenticated, and only explicitly specify the public ones? I have a Navigation root screen so I only need to specify AuthenciatedView for one widget:

```
  routes: [
    GoRoute(
      path: '/invite',
      builder: (context, state) => WelcomeInvitee(inviteCode: state.uri.queryParameters['code']!),
    ),
    ShellRoute(
      builder: (BuildContext context, GoRouterState state, Widget child) {
        return AuthenticatedView(child: MainNavigationScreen(child: child));
      },
```

but I can imagine someone has to wrap a bunch of screens to get that one screen not authenticated. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.3

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @pixnbit - The updated docs have been released. As far as better integration with Go Router, we will track this via https://github.com/aws-amplify/amplify-flutter/issues/2040.
