### ISSUE TITLE
UploadFile, downloadFile to s3 bucket with . in the name

### ISSUE THREAD

**Issue by Christopher-Cinefly** [aws-amplify/amplify-flutter#3494]
There has been a previously solved issue #3147 to get the Amplify.Storage.getUrl method that would detect if the bucket name included a . and would use the older path style URL.

It would be useful to also work for the 'uploadFile', 'downloadFile' and 'downloadData' methods. Trying to use these methods demonstrated they were not changed with the previous issue.  I need to use the uploadFile and downloadFile methods in the application I am currently working on, so I was hoping these could be given the same functionality as the other mentioned method to detect if there's a . and build the older path style URL.

**Comment by dnys1** [comment]
Hi @Christopher-Cinefly sorry you are facing this issue. Can you share an example of the code you're calling and the exception you receive?

Can you also provide a bucket name which we could use for testing purposes? Currently we have tests in place for a bucket name with the shape of a URL. If you could share the pattern used by your bucket, that would help tremendously.

**Comment by Christopher-Cinefly** [comment]
The uploadFile method, would attempt to use the virtualised style url to work to upload files. In this situation, I am trying to upload 4 seperate files one after the other, before proceeding to save a record to the database that will reference them. 

Here's whats being called:
```
Future<void> uploadFile(
    String uploadFileKey, File file, Function onProgress) async {
  try {
    final result = Amplify.Storage.uploadFile(
        key: uploadFileKey,
        localFile: AWSFile.fromPath(file.path),
        options: const StorageUploadFileOptions(
            accessLevel: StorageAccessLevel.private));
    onProgress(100, 100);
  } catch (e) {
    print('UploadFile Err: $e');
  }
}
```

Here's the response, the process calls this asynchronously multiple times as multiple files are uploaded. Showing the multiple responses, as there is a new message in the end.

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: NetworkException {
  "message": "The request failed due to a network error.",
  "recoverySuggestion": "Ensure that you have an active network connection",
  "underlyingException": "PUT https://bucket.name.including.identifier.s3.ap-southeast-2.amazonaws.com/private/ap-southeast-2%3A51ddddea-e5f5-4a99-a8e2-c4d1f14ef883/private/5d7720f3-985c-4b9f-9a23-87d34d2008ec/2023/8/4/69026b35-ad24-4b8d-98c0-f38cc10ffc11.mp4?x-id=PutObject failed: HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))"
}


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: NetworkException {
  "message": "The request failed due to a network error.",
  "recoverySuggestion": "Ensure that you have an active network connection",
  "underlyingException": "PUT https://bucket.name.including.identifier.s3.ap-southeast-2.amazonaws.com/private/ap-southeast-2%3A51ddddea-e5f5-4a99-a8e2-c4d1f14ef883/private/5d7720f3-985c-4b9f-9a23-87d34d2008ec/2023/8/4/d0497417-7520-4409-8627-1b6c4a00147b.mp4?x-id=PutObject failed: HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))"
}


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: NetworkException {
  "message": "The request failed due to a network error.",
  "recoverySuggestion": "Ensure that you have an active network connection",
  "underlyingException": "PUT https://bucket.name.including.identifier.s3.ap-southeast-2.amazonaws.com/private/ap-southeast-2%3A51ddddea-e5f5-4a99-a8e2-c4d1f14ef883/private/5d7720f3-985c-4b9f-9a23-87d34d2008ec/2023/8/4/dee5e855-7c65-4fa6-b274-60e61cf1ce65.mp4?x-id=PutObject failed: HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))"
}


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: ApiException {
  "message": "{\"messages\":[{\"level\":\"Error\",\"message\":\"Something went wrong\"}]}",
  "underlyingException": "HTTP Status code: 400"
}


#0      AmplifyAuthorizationRestClient.transformResponse
amplify_authorization_rest_client.dart:65

<asynchronous suspension>


#1      CancelableCompleter.complete.<anonymous closure>
cancelable_operation.dart:425

<asynchronous suspension>


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: UnknownException {
  "message": "Multipart upload has been terminated due to an error.",
  "recoverySuggestion": "An unknown exception has happened.           Please take a look at \n        https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that \n        match your scenario, and file an issue with the details of the bug if there isn't.\n  ",
  "underlyingException": "NetworkException {\n  \"message\": \"The request failed due to a network error.\",\n  \"recoverySuggestion\": \"Ensure that you have an active network connection\",\n  \"underlyingException\": \"PUT https://bucket.name.including.identifier.s3.ap-southeast-2.amazonaws.com/private/ap-southeast-2%3A51ddddea-e5f5-4a99-a8e2-c4d1f14ef883/private/5d7720f3-985c-4b9f-9a23-87d34d2008ec/2023/8/4/c7831e20-85c1-4485-b7b6-b94e0ba7dab4.mp4?x-id=UploadPart&partNumber=2&uploadId=NHyD0dkgDXhpX44p_FzEwNKH13rjF07uYKUwJB3o4ZAWQL_hzo1vQ_9e9QN0nlwJFYOLBuLKby60HwNzv4H128Bi3m5h1ABnxtR3STDpisolv2VPKJ_LzB.WOOqL9n81s3zFr3uLFjTGWEc2kJTcXPKQJpGQUvOVW3.q8SVoevU- failed: HandshakeException: Handshake error in client (OS Error: \\n\\tCERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))\"\n}"
}
```

**Comment by Christopher-Cinefly** [comment]
Just in reference to the not reproducible tag. Would this not be the same case every time this method is called and the bucket it is called upon includes one or more periods in the name? It appears to be the same thing that was happening with the previous issue https://github.com/aws-amplify/amplify-flutter/issues/3147 before that method was updated to check for the condition

**Comment by dnys1** [comment]
Hi @Christopher-Cinefly sorry for the delay on this issue. Can you please provide a bit more info?

1. The version of the Amplify Flutter libraries you're using.
2. The code you're using to construct the Storage plugin and add it using `Amplify.addPlugin`.

Issue #3147 included logic for all public methods, not just `getUrl` and I haven't been able to reproduce this yet since the S3 client is [initialized](https://github.com/aws-amplify/amplify-flutter/blob/de1ce2d769780ebc3b0e8fb8e9e979dfe40eccbd/packages/storage/amplify_storage_s3_dart/lib/src/storage_s3_service/service/storage_s3_service_impl.dart#L42) to use path style URLs when there's a dot in the bucket name.

**Comment by dnys1** [comment]
Hi @Christopher-Cinefly are you still facing this issue?

**Comment by Christopher-Cinefly** [comment]
> Hi @Christopher-Cinefly are you still facing this issue?

Hi @dnys1 After performing another update on the relevant packages, the error has gone. The version in use was a pre-release connection to the branch that was PR'd for the previous issue. Found it strange the version connected included the one method but not the others when they were done together. d

Problem is no longer valid though. Thanks for looking into this.
