### ISSUE TITLE
Updated result is not returning from Graphql query, returning previous cache .

### ISSUE THREAD

**Issue by ilyasarafathemvigo** [aws-amplify/amplify-flutter#3512]
### Description

Using amplify plugin :   amplify_api: ^1.1.0 
   using query function I queried a result.Then I updated the same result using mutation and it got updated successfully in the database. Then again I called the previous query immediately, but am getting old data(without updated content). 
I think previous data taken from the cache and I can't see a option to restrict the cache mechanism. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1.  using "query" function fetch some data .
2. Update the queried result using "mutation".
3. Immediately call the same query with "query" function

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.1.0

### Deployment Method

Custom Pipeline

**Comment by Jordan-Nelson** [comment]
@ilyasarafathemvigo - can you provide a minimal code sample where this issue is reproducible?

The API category does not cache data. Do you have any caching mechanism set up?

**Comment by ilyasarafathemvigo** [comment]
I have no  caching mechanism.
<img width="1140" alt="Screenshot 2023-08-03 at 7 40 36 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/121234451/919a43ba-666b-4bea-8b9a-a2651224206d">
For reproducing this issue 
 fetch some data(query)  then update same queried data(mutation) then call same query again (immediately after mutation is done)

**Comment by Jordan-Nelson** [comment]
I believe [graphql_flutter](https://pub.dev/packages/graphql_flutter) uses hive as a client side cache. The API category has no client side cache unless you are using DataStore. Each request should hit the network.

Is conflict resolution enabled for your backend, and/or was this backend previously use with DataStore?

**Comment by Jordan-Nelson** [comment]
@ilyasarafathemvigo - If you are still facing this issue please let me know the answers to the questions above. Thanks.

**Comment by Jordan-Nelson** [comment]
@ilyasarafathemvigo - I am going to close this out. If you are still having an issue, please let me know and we can reopen the issue.
