### ISSUE TITLE
Android FCM: Ignore intents that don't contain push notification payload

### ISSUE THREAD

**Issue by zilaiyedaren** [aws-amplify/amplify-flutter#3516]
### Description

Ignore intents that don't contain push notification payload

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1.aws sns send android push message
2.when app in background can receive and show a push message in system window, but show warning: 'Ignore intents that don't contain push notification payload'
3. when app in foreground can't show a push message in system window, and show warning: 'Ignore intents that don't contain push notification payload'

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by zilaiyedaren** [comment]
override fun handleIntent(intent: Intent) {
        // If the intent is for a new token, just forward intent to Firebase SDK
        if (intent.action == PushNotificationPluginConstants.ACTION_NEW_TOKEN) {
            super.handleIntent(intent)
            return
        }
        val extras = intent.extras ?: Bundle()
        extras.getNotificationPayload()?.let {
            // message contains push notification payload, show notification
            // passing both intent and payload to refrain from doing the same conversions downstream
            handleMessageReceived(intent, it)
        } ?: run {
            Log.d(TAG, "Ignore intents that don't contain push notification payload")
            super.handleIntent(intent)
        }
    }

**Comment by zilaiyedaren** [comment]
```
override fun handleIntent(intent: Intent) {
        // If the intent is for a new token, just forward intent to Firebase SDK
        if (intent.action == PushNotificationPluginConstants.ACTION_NEW_TOKEN) {
            super.handleIntent(intent)
            return
        }
        val extras = intent.extras ?: Bundle()
        extras.getNotificationPayload()?.let {
            // message contains push notification payload, show notification
            // passing both intent and payload to refrain from doing the same conversions downstream
            handleMessageReceived(intent, it)
        } ?: run {
            Log.d(TAG, "Ignore intents that don't contain push notification payload")
            super.handleIntent(intent)
        }
    }
```

**Comment by NikaHsn** [comment]
@zilaiyedaren I'm not sure if I completely understood the issue you are facing here.
- Are you sending notifications with no payload? 
- If sending notifications with payload can you share the payload? 

Meanwhile the expected behavior of Notifications with no payload or an unexpected payload is:
When handling notifications with no payload (or an unexpected payload), a debug message is logged (just a precaution, and doesn't do anything)
If the app is in  foreground notifications are not displayed. 
If the app is in background notifications are send to system try and hence you see the notification.
Do you see similar behavior? and if so does it cause an issue in you app?

**Comment by NikaHsn** [comment]
@zilaiyedaren let me know if you are experiencing any issue or having question. I will be closing this issue in 7 days if do not hear back from you.

**Comment by diegogangl** [comment]
Can we reopen this? I'm facing this same issue.

Here's my code (root widget):

```dart
  @override
  initState() {
    super.initState();
    _configureAmplify();
  }

  void myNotificationReceivedHandler(PushNotificationMessage notification) {
    print('FG notification: $notification');
  }

  void myTokenReceivedHandler(String token) {
    print('Token: $token');
  }

  Future<void> _configureAmplify() async {
    try {
      final authPlugin = AmplifyAuthCognito();
      final pushPlugin = AmplifyPushNotificationsPinpoint();
      await Amplify.addPlugins([authPlugin, pushPlugin]);

      await Amplify.configure(amplifyconfig);

      handlePushPermissions();

      Amplify.Notifications.Push.onTokenReceived.listen(myTokenReceivedHandler);

      subscription = Amplify
          .Notifications.Push.onNotificationReceivedInForeground
          .listen(myNotificationReceivedHandler);

    } on AmplifyAlreadyConfiguredException {
      safePrint(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
  }


```

When I try to publish a message through SNS I get this message:

`D/PushNotificationFirebaseMessagingService(27792): Ignore intents that don't contain push notification payload`

I've tried every variation I could think of these two payloads:

```
{
"GCM": "{ \"data\": { \"message\": \"Test message from SNS console.\", \"title\": \"FCMSampleApp\" } }"
}
```

```
{
"GCM": "{ \"notification\": { \"title\": \"test title\", \"body\": \"test body\" } }"
}

```
I'm kind of new to Flutter, Dart, aws and amplify so I'm not sure how to debug this

**Comment by Jordan-Nelson** [comment]
Hi @diegogangl - I have re-opened the issue. It sounds like you are unsure what format the message payload should be in. Is that correct?

**Comment by Jordan-Nelson** [comment]
Have you followed the [steps here](https://docs.aws.amazon.com/pinpoint/latest/userguide/campaigns-begin.html) to create a campaign from the pinpoint console?

**Comment by diegogangl** [comment]
@Jordan-Nelson Following those steps did actually work!

```
I/flutter (13575):   "imageUrl": null,
I/flutter (13575):   "deeplinkUrl": null,
I/flutter (13575):   "goToUrl": null,
I/flutter (13575):   "fcmOptions": {
I/flutter (13575):     "channelId": "PINPOINT.NOTIFICATION",
I/flutter (13575):     "messageId": null
I/flutter (13575):   },
I/flutter (13575):   "apnsOptions": null,
I/flutter (13575):   "data": {
I/flutter (13575):     "pinpoint.openApp": "true",
I/flutter (13575):     "pinpoint.notification.title": "Test ",
I/flutter (13575):     "pinpoint.notification.body": "This is a test",
I/flutter (13575):     "pinpoint.campaign.campaign_id": "_DIRECT",
I/flutter (13575):     "pinpoint.notification.silentPush": "0"
I/flutter (13575):   }
I/flutter (13575): }
```

So we should use the pinpoint application and not sns?

**Comment by abdallahshaban557** [comment]
Hello @diegogangl - yes, we support Pinpoint with Amplify Flutter!
