### ISSUE TITLE
[Storage] protected access type behaves as if private access type

### ISSUE THREAD

**Issue by salihgueler** [aws-amplify/amplify-flutter#3517]
### Description

As per the [documentation](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/)

- Guest Accessible by all users of your application
- Protected Readable by all users, but only writable by the creating user
- Private Readable and writable only by the creating user

However, if a user uploads a file to the **protected** section, the others can not reach it. 

Code to reproduce:

**Upload File Snippet**
```dart
Future<void> uploadFile(String filePath) async {
  try {
    final result = await Amplify.Storage.uploadFile(
      localFile: AWSFile.fromPath(
       filePath,
      ),
      key: file.name,
      options: const StorageUploadFileOptions(
        accessLevel: StorageAccessLevel.protected,
      ),
      onProgress: (progress) { },
    ).result;
    safePrint('Uploaded data to location: ${result.uploadedItem.key}');
  } on StorageException catch (e) {
    safePrint(e.message);
    rethrow;
  }
}
```

**List Files Snippet**
```dart
Future<String> getCurrentUserIdentityId() async {
  try {
    final cognitoPlugin =
        Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
    final result = await cognitoPlugin.fetchAuthSession();
    final identityId = result.identityIdResult.value;
    return identityId;
  } on AuthException catch (e) {
    safePrint('Error retrieving auth session: ${e.message}');
    rethrow;
  }
}

Future<List<StorageItem>> listFiles() async {
  try {
    final targetIdentityId = await getCurrentUserIdentityId();
    final result = await Amplify.Storage.list(
      options: StorageListOptions(
        accessLevel: StorageAccessLevel.protected,
        pluginOptions: S3ListPluginOptions.listAllForIdentity(
          targetIdentityId,
        ),
      ),
    ).result;
    safePrint('Listed items: ${result.items}');
    return result.items;
  } on StorageException catch (e) {
    safePrint(e);
    rethrow;
  }
}
```

**Generate URL Snippet**
```dart
Future<String> getCurrentUserIdentityId() async {
  try {
    final cognitoPlugin =
        Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
    final result = await cognitoPlugin.fetchAuthSession();
    final identityId = result.identityIdResult.value;
    return identityId;
  } on AuthException catch (e) {
    safePrint('Error retrieving auth session: ${e.message}');
    rethrow;
  }
}

Future<String> _generateFileUrl() async {
  try {
    final targetIdentityId = await getCurrentUserIdentityId();

    final result = await Amplify.Storage.getUrl(
      key: fileKey,
      options: StorageGetUrlOptions(
        accessLevel: StorageAccessLevel.protected,
        pluginOptions: S3GetUrlPluginOptions.forIdentity(
          targetIdentityId,
        ),
      ),
    ).result;

    return result.url.toString();
  } on StorageException catch (e) {
    safePrint(e.message);
    rethrow;
  }
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

- Create a new Flutter Amplify project with AWS Amplify and Authentication initialized
- Create two users with the defined user pool
- Use the _Code to reproduce_ below to create base scenarios
- Upload a file with user number 1
- Upload a file with user number 2
- **EXPECTED**
- Both files are visible to both users
- **CURRENT**
- Each user can only see their respective files.

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [X] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
Thanks @salihgueler for reporting this. aws-amplify/docs#5742 fixes the doc for protected access level. 
I reference this issue from the aws-amplify/docs#4608 to follow the progress on storage doc improvement and hence closing this one.
