### ISSUE TITLE
"UPLOAD_FILE_FAILED" error flutter amplify after use Amplify.Storage.uploadFile( key: key, local: path, options: options);

### ISSUE THREAD

**Issue by eroamba** [aws-amplify/amplify-flutter#352]

**Comment by offlineprogrammer** [comment]
Hey @eroamba 

Please check our example app ([here](https://github.com/aws-amplify/amplify-flutter/tree/master/example)) for a working file upload function

Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by offlineprogrammer** [comment]
Hey @eroamba

I am closing this issue for now as I didn't hear from 
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
