### ISSUE TITLE
Confusion between Notifications and Analytics

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3523]
I've been looking into the difference between using:
```dart
Amplify.Notifications.Push.identifyUser()
```
and
```dart
Amplify.Analytics.identifyUser()
```
I didn't find anything in the docs except that I can add a map of UserAttributes using Notifications. Then I opened the network inspector to see if the request is the same and I found that there is a number of differences between the two requests. Notably the channel type, address and the OptOut. 

If my application have push notifications, should I identify the user using only Notifications? Can I change the value of OptOut?
If I only use the identifyUser function of Analytics, will it affect anything related to notifications?

Thank you for any clarifications!

**Comment by NikaHsn** [comment]
@jamilsaadeh97 thanks for asking the question and sorry that you couldn't find the answer in the docs.

> If my application have push notifications, should I identify the user using only Notifications?


yes, use `Amplify.Notifications.Push.identifyUser()` to identify the user for push notifications.

> If I only use the identifyUser function of Analytics, will it affect anything related to notifications?

no, `Amplify.Analytics.identifyUser()` is to identify the user for analytics and does not impact push notification.

> Can I change the value of OptOut?

the value is set to `NONE` for push notification to receive all push notifications and can not be changed. can you share more on your use case for changing the OptOut value?

**Comment by jamilsaadeh97** [comment]
Hi @NikaHsn thank you for your answers!

If both the Notifications and Analytics plugin use Pinpoint service, wouldn't it be a bit redundant to call both identifyUser() each time a user opens the app or logs in and would the data be saved twice in Pinpoint?
I'm sorry if I don't have a clearer picture on what are the differences between the two plugins when it comes to identifying a user. Any extra info would be greatly appreciated.

As for my use cases for the OptOut, I had a toggle in my app to let the users opt in or out to receive notifications. I know they can go to their phone settings and switch the notifications on/off but it would be a better user experience to control it directly from the app in my opinion.

Thank you!

**Comment by NikaHsn** [comment]
@jamilsaadeh97 Notifications and Analytics categories have/use their own Pinpoint endpoint. Calling `identifyUser()` on Notifications category will associate the user to the Notification category's Pinpoint endpoint only. Therefore Notification and Analytics category each have an `identifyUser()` API to associate the user to their own Pinpoint endpoint. I hope this helps resolving the confusion.
re OptOut use case: Notifications category does not have an API to support this. there is a workaround to call the `Notifications.Push.identifyUser()` passing an empty string for the userID to disassociate the endpoint from that user.
#3179 is about the OptOut feature and you can follow the progress on that.

**Comment by abdallahshaban557** [comment]
Hi @jamilsaadeh97  - We agree with you it is indeed confusing that we have the same API that works the same but separately on both categories. We are working with the Pinpoint team to simplify this experience further in the future.

**Comment by jamilsaadeh97** [comment]
Hi @NikaHsn thank you so much for the clarifications!

@abdallahshaban557 Yes I feel that at least it should be clarified in the docs with some general use cases.

**Comment by NikaHsn** [comment]
@jamilsaadeh97 I created an issue for docs, please feel free to comment on the issue and follow the progress there. I will be closing this in favor of the docs issue.
