### ISSUE TITLE
App crashing when opening launch notification

### ISSUE THREAD

**Issue by JoakimMellonn** [aws-amplify/amplify-flutter#3530]
### Description

On iOS (haven't tested Android yet) when closing the app and sending a test notification, when I then tap the notification to open it, the app Crashes immediately.
The app doesn't even get to fill the whole screen before closing again. And after that when trying to open the app, it happens repeatedly.

I'm handling the launch notifications just as described in the documentation, and as seen in the code below:
```dart
final launchNotification = notificationsPlugin.launchNotification;

if (launchNotification != null) {
  onLaunchNotificationOpened(launchNotification);
}
```
The above code is executed before running Amplify.addPlugins() with the enabled plugins.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Setup Flutter app with Notifications enabled.
2. Debug and close the app.
3. Send notification to device.
4. Tap the notification to open the app.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@JoakimMellonn sorry that you are facing this issue. would you share the messsage payload that causing the app to crash.

**Comment by JoakimMellonn** [comment]
> @JoakimMellonn sorry that you are facing this issue. would you share the messsage payload that causing the app to crash.

I actually don't do anything special with the payload, because I'm just using the Test Messaging functionality in Pinpoint with the "Action" set to "Open your app".

With that said I don't exactly know what the payload of these messages are, I would just assume they are as simple as possible and would work without any hassle.

**Comment by NikaHsn** [comment]
@JoakimMellonn can you share the console log when the app crashes on opening?
and also implementation of `onLaunchNotificationOpened`.

**Comment by HuiSF** [comment]
@JoakimMellonn Wondering if you are testing on a device, are you using the debug scheme to build your app bundle? The debug scheme only works with connected to Xcode, if you quitted the app, and attempted to reopen it on the device it would close right away (seems like an immediate crash). Testing on a device without Xcode required profile or release scheme to build the app bundle.

**Comment by JoakimMellonn** [comment]
> @JoakimMellonn Wondering if you are testing on a device, are you using the debug scheme to build your app bundle? The debug scheme only works with connected to Xcode, if you quitted the app, and attempted to reopen it on the device it would close right away (seems like an immediate crash). Testing on a device without Xcode required profile or release scheme to build the app bundle.

Yes exactly, was actually doing some testing and figured this being the case! Do you know if it's something new, because I've done the same thing earlier without the same behaviour?

**Comment by HuiSF** [comment]
> > @JoakimMellonn Wondering if you are testing on a device, are you using the debug scheme to build your app bundle? The debug scheme only works with connected to Xcode, if you quitted the app, and attempted to reopen it on the device it would close right away (seems like an immediate crash). Testing on a device without Xcode required profile or release scheme to build the app bundle.
> 
> 
> 
> Yes exactly, was actually doing some testing and figured this being the case! Do you know if it's something new, because I've done the same thing earlier without the same behaviour?

I believe that's always been the case, as an Apple's requirement.

Please note if you minimize the app after ran from Xcode in debug mode without quitting the app (swipe up in the app switcher screen), it can still open. But once you quit the app, you have to rerun it from Xcode.

For testing the push notifications, please build the app with either profile or release scheme.

**Comment by JoakimMellonn** [comment]
> I believe that's always been the case, as an Apple's requirement.
> 
> Please note if you minimize the app after ran from Xcode in debug mode without quitting the app (swipe up in the app switcher screen), it can still open. But once you quit the app, you have to rerun it from Xcode.
> 
> For testing the push notifications, please build the app with either profile or release scheme.

That's totally right! I think I got confused being more used to developing for Android. But thank you for the heads up and clarification!
This problem has been resolved now, thank you for the help!

**Comment by abdallahshaban557** [comment]
Closing this issue now. Thank you for confirming your issue was resolved, @JoakimMellonn !
