### ISSUE TITLE
The argument type 'void Function(AuthHubEvent)' can't be assigned to the parameter type 'void Function(HubEvent<Object?>)'

### ISSUE THREAD

**Issue by roscadalexandru** [aws-amplify/amplify-flutter#3531]
### Description

Amplify.Hub.listen() seems to be bugged. I am pretty confused. I am not sure if this is a bug or I am really doing something wrong even tho I doubt that.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

<img width="1466" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/22360500/4591b939-e8b3-4035-ac3d-886d02f052e4">

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.1

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@roscadalexandru the issue you are facing is due to dart-lang/sdk#53166. in the meantime, using `StreamSubscription<AuthHubEvent>` instead of  `StreamSubscription` should fix your issue.

**Comment by roscadalexandru** [comment]
Oh God. I didn't notice I haven't added the type. Will give it a try tomorrow morning. Thank you

**Comment by dnys1** [comment]
Please let us know if you continue to face this issue. Closing for now as we believe this is a bug in Dart with a known set of workarounds.
