### ISSUE TITLE
Amplify.Storage.list() infinite loop

### ISSUE THREAD

**Issue by charlieforward9** [aws-amplify/amplify-flutter#3538]
### Description

When I copy & paste the EXACT **list file** method from [these docs](https://docs.amplify.aws/lib/storage/list/q/platform/flutter/), I get an infinite loop, where the `hasNextPage` property continues to return true and the `nextToken` value is unique every time. 

Here is my specific implementation:

``` dart
  Future<List<String>> listRawData() async {
    try {
      List<String> fileKeys = [];
      String? nextToken;
      bool hasNextPage;
      do {
        final result = await Amplify.Storage.list(
          path: 'raw/',
          options: StorageListOptions(
            pageSize: 1000,
            nextToken: nextToken,
            pluginOptions: const S3ListPluginOptions(
              excludeSubPaths: true,
            ),
          ),
        ).result;
        fileKeys.addAll(result.items.map((e) => e.key));
        nextToken = result.nextToken;
        hasNextPage = result.hasNextPage;
        print(fileKeys.length);
        print(hasNextPage);
      } while (hasNextPage);
      return fileKeys;
    } on StorageException catch (e) {
      safePrint('Error listing files: ${e.message}');
      rethrow;
    }
  }
```

and this is what is logged in the console:

> flutter: 1000
flutter: true
flutter: 2000
flutter: true
flutter: 3000
flutter: true
flutter: 4000
flutter: true
...

This is the folder I am trying to access viewed through Amplify Studio:
<img width="251" alt="Screen Shot 2023-08-09 at 5 13 27 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/62311337/01d3b2d1-f676-416f-a71f-5c518eaedd82">

It may have to do with there being over 1000 files, when I delete enough to be less than 1000, the function does not continue to loop over and over.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@charlieforward9 sorry that you are facing this issue. It is fixed in [v1.2.1](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.2.1) so upgrading to this version or higher should help resolving the issue.

**Comment by charlieforward9** [comment]
I am sorry for the delay, I spent the week at a tradeshow and will get to this soon.

**Comment by NikaHsn** [comment]
@charlieforward9 I'm closing this issue as I didn't hear back from you. Hopefully upgrading to [v1.2.1](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.2.1) has fixed the issue on your end. if you are still experiencing this issue please let us know and we can consider re-opening it.
