### ISSUE TITLE
Custom auth flow fails to send SMS with code

### ISSUE THREAD

**Issue by itechevo** [aws-amplify/amplify-flutter#3546]
### Description

I have setup custom sign in flow following this: https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/flutter/

After few trial and error I hardcoded a 6 digit code and completed the sign in flow successfully.  Only part not working is the SMS sending of the code to the specified number. I see no error in the console too. 

My region is **ap-south-1** and my SMS is sandbox mode and I am only using the verified number to test this.

Sign up using phone number and get SMS code to confirm sign up. Works fine.
Once signed up, custom sign in with following lambda fails to send code using SNS, but I can complete the sign in flow if just confirm using the hardcoded code. 

**CreateAuthChallenge**

```
/**
 * @type {import('@types/aws-lambda').CreateAuthChallengeTriggerHandler}
 */
//crypto-secure-random-digit is used here to get random challenge code - https://github.com/ottokruse/crypto-secure-random-digit
const digitGenerator = require('crypto-secure-random-digit');
const { SNSClient, PublishCommand } = require("@aws-sdk/client-sns");

const client = new SNSClient({});

async function sendChallengeCode(phoneNumber, secretCode) {

    const input  =  new PublishCommand({
        Message: "[Testing] Your secret code: " + secretCode,
        // One of PhoneNumber, TopicArn, or TargetArn must be specified.
        PhoneNumber: phoneNumber,
      }); 
    const response = await client.send(input);
}

 function createAuthChallenge(event) {
  
  console.log('Event: ', JSON.stringify(event, null, 2));
  
  if (event.request.challengeName === 'CUSTOM_CHALLENGE') {
    // Generate a random code for the custom challenge
    const challengeCode = 123456;//digitGenerator.randomDigits(6).join('');
    
    // Send the custom challenge to the user
   run(event.request.userAttributes.phone_number, challengeCode);

    event.response.privateChallengeParameters = {};
    event.response.privateChallengeParameters.answer = challengeCode;
    event.response.publicChallengeParameters = {
      hint: 'Enter the secret code'
    };
  }
}

exports.handler = async (event) => {
  createAuthChallenge(event);
};
```

**DefineAuthChallenge**

```
/**
 * @type {import('@types/aws-lambda').DefineAuthChallengeTriggerHandler}
 */
 exports.handler = async function(event) {

  console.log('Event: ', JSON.stringify(event, null, 2));

  if(event.request.session.length == 0) {
      event.response.issueTokens = false;
      event.response.failAuthentication = false;
      event.response.challengeName = 'CUSTOM_CHALLENGE';
  } else if (event.request.session.length == 1 && event.request.session[0].challengeName == 'CUSTOM_CHALLENGE' && event.request.session[0].challengeResult == true) {
      event.response.issueTokens = true;
      event.response.failAuthentication = false;
      event.response.challengeName = 'CUSTOM_CHALLENGE';
  } else {
      event.response.issueTokens = false;
      event.response.failAuthentication = true;
  }
  
   return event;
};
```

**VerifyAuthChallengeResponse**

```
/**
 * @type {import('@types/aws-lambda').VerifyAuthChallengeResponseTriggerHandler}
 */
function verifyAuthChallengeResponse(event) {
  if (
    event.request.privateChallengeParameters.answer ===
    event.request.challengeAnswer
  ) {
    event.response.answerCorrect = true;
  } else {
    event.response.answerCorrect = false;
  }
}

exports.handler = async (event) => {
  verifyAuthChallengeResponse(event);
};
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by itechevo** [comment]
> Can you also confirm that the `phone_number` attribute is the number you're expecting? And can you verify that sending an SMS from the SNS console to your phone number works as expected?

I can confirm the number is correct and I am able to send SMS via console.

**Comment by dnys1** [comment]
Thanks, @itechevo. Were you able capture the response from SNS as well?

**Comment by itechevo** [comment]
> capture the response from SNS

I don't see any logs from SNS. I setup cloudwatch like this: https://repost.aws/knowledge-center/monitor-sns-texts-cloudwatch 

After adding the logs:

```
async function sendChallengeCode(phoneNumber, secretCode) {

  console.log('Entering sendChallengeCode');
  
  const input  =  new PublishCommand({
        Message: "[Testing] Your secret code: " + secretCode,
        // One of PhoneNumber, TopicArn, or TargetArn must be specified.
        PhoneNumber: phoneNumber,
      });
      
  console.log('Calling await client.send...');

  const response = await client.send(input);

  console.log(`SNS Response: ${JSON.stringify(response)}`); 
}
```

I never see **SNS Response** printed. I only see the first 2 logs.

**Comment by itechevo** [comment]
[dnys1](https://github.com/dnys1) Any update on this issue?

**Comment by dnys1** [comment]
Hi @itechevo, sorry for the delayed response.

Can you share once again your full Lambda? I'm not seeing in your original post how `sendChallengeCode` is being called. Is it possible it's not being awaited?

Can you make sure `createAuthChallenge` is marked as `async` and that it's being awaited? Can you further make sure that you're returning the response?

```js
exports.handler = async (event) => {
  return createAuthChallenge(event);
};
```

**Comment by itechevo** [comment]
@dnys1 Thank you. After adding await and return on the call as you suggested, I got a meaningful error message:

`CreateAuthChallenge-staging is not authorized to perform: SNS:Publish on resource: +XXXXXXXXXX because no identity-based policy allows the SNS:Publish action`

After I added AmazonSNSFullAccess to CreateAuthChallenge-staging function, I got the SMS message send through successfully.

I created this Lambda functions via Amplify CLI, I thought the permission will be automatically set, guess not. Now, is it safe to set `AmazonSNSFullAccess` to this function, is there a better way to do this?

**Comment by dnys1** [comment]
Glad to hear it! 

For permissions, best practice is to scope down the IAM policy to the minimum necessary permissions. The `AmazonSNSFullAccess` policy looks like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sns:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

This means, by granting the Lambda full access, it can do any SNS operation (`sns:*`) on any resource (`"Resource": "*"`) which is more than the Lambda requires. To scope it down, you just need to give the Lambda access to a single SNS operation (`sns:Publish`) on a single resource (your SNS topic). That policy would look like this:

```json5
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sns:Publish"
            ],
            "Effect": "Allow",
            "Resource": "+XXXXXXXXXX"
        }
    ]
}
```

where `+XXXXXXXXXX` is the resource ARN from the error message you sent. It should look something like: `arn:aws:sns:us-east-2:123456789012:MyTopic`

Hope this helps!

**Comment by itechevo** [comment]
+XXXXXXXXXX is actually the the phone number it was trying to send the SMS to. So, in this case, I can't restrict the **Resource**, since it is a phone number, but I can restrict the action, right?

**Comment by dnys1** [comment]
Apologies for the confusion. The resource must be the ARN of your topic which should look like this: `arn:aws:sns:us-east-2:123456789012:MyTopic`. You should be able to find this in the Pinpoint console.

**Comment by itechevo** [comment]
@dnys1 Thanks for the info, I will check it out. Regarding this issue, thank you for your support to get it resolved.
