### ISSUE TITLE
How can one debug or query the local datastore in flutter

### ISSUE THREAD

**Issue by payls** [aws-amplify/amplify-flutter#3567]
### Description

I am using aws-amplify and aws-datastore plugins in my Flutter ios app with AWS as backend.

I would like to see the values of the Models in the local datastore. I don't want to query the datastore in code. I actually want to see the value in the DB engine.

Below is the browser implementation which I am trying to get at.
![image](https://github.com/aws-amplify/amplify-flutter/assets/5010060/be0627b0-a994-4285-97a0-71bbc532d720)

When I do step debugging I can't see the values from the DB engine which makes sense. Below is a screenshot. How does one see the local DB values in Flutter?
![image](https://github.com/aws-amplify/amplify-flutter/assets/5010060/8fbb6a45-2d56-4e5c-8091-d7c6ac204481)

I also tried to get some inspiration from the [Flutter docs on SQLlite](https://docs.flutter.dev/cookbook/persistence/sqlite) but they have no information on DB management. Please share some insights on this.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a Flutter app and setup Amplify Flutter package
2. Configure Amplify DataStore
3. In the app set a debugger to see values in the local datastore.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @payls the local datastore is stored as a .db file that can be read using a SQL reader like: [https://sqlitebrowser.org/](https://sqlitebrowser.org/)

Finding it can be a bit tricky.  [These instructions](https://stackoverflow.com/questions/1108076/where-does-the-iphone-simulator-store-its-data#:~:text=open%20a%20Finder%20windor%20(%20smiley,version%20of%20the%20different%20Simulators) tell you where you ios simulator files are located.

On my computer it's stored at: 

`/Users/[USER]/Library/Developer/CoreSimulator/Devices/[DEVICE_ID]/data/Containers/Data/Application/[APPLICATION_ID]/Documents/[APPNAME.db]`

To make things easier on Mac, you can save an item to Datastore and then follow the path of most recently modified folders.  

Or you can go to the devices folder and search [APPNAME.db].

**Comment by payls** [comment]
@fjnoyp Thank you I am now able to access the db and debug.
