### ISSUE TITLE
Datastore Observe Query Fails to Return All Items Upon Changes

### ISSUE THREAD

**Issue by soheb12** [aws-amplify/amplify-flutter#3588]
### Description
I have implemented a straightforward observe query using Amplify's DataStore to monitor changes in a "messages" table. The objective is to update the _messages list whenever there's a modification in the messages table. The query monitors messages sent by a specific sender, ordered by their time of sending.

**Code:**
```dart
_stream = Amplify.DataStore.observeQuery(
      Message.classType,
      where: Message.SENDERID.eq('7ca4c5ec-b3af-49f8-afce-b5194a781a7d'),
      sortBy: [Message.TIMESENT.ascending()],
    ).listen((QuerySnapshot<Message> snapshot) {
      setState(() {
        print("*************Got a new message in observe query listen");
        _messages = snapshot.items;
      });
    });

```

**Message Data Model:**

```graphql
type Message @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey(sortKeyFields: ["timeSent"])
  senderId: String
  receiverId: String
  message: String!
  type: MessageTypeEnum!
  timeSent: String!
  isSeen: String
  repliedMessage: String
  repliedTo: String
  repliedMessageType: MessageTypeEnum
}
```

### Issue:
The problem arises when using the observe query – the returned snapshot of items consistently excludes the first item from the previously returned list. This irregularity is exemplified by the following scenarios:

**Initial List:**
```
1
2
3
```

**After adding a new message "4":**
```
2
3
4
```

This pattern keeps continuing on adding another message say 5, the returned list is `3,4,5`

Furthermore, an additional issue arises where the stream doesn't yield any updates on the recipient's side for the new message until the recipient manually refreshes the entire screen.

### Dependencies:

- amplify_datastore: ^1.1.0-supports-only-mobile
- amplify_flutter: ^1.0.1
- Also attempted with ^1.2.0-supports-only-mobile

It's worth noting that despite employing both `1.1.0` and `1.2.0` versions of the library, the issue persists. This behavior prevents the application from reliably reflecting real-time changes in the message list and leads to an unsatisfactory user experience. Any guidance or insight into resolving this issue would be greatly appreciated.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a message data model with below schema
````graphql
type Message @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey(sortKeyFields: ["timeSent"])
  senderId: String
  receiverId: String
  message: String!
  type: MessageTypeEnum!
  timeSent: String!
  isSeen: String
  repliedMessage: String
  repliedTo: String
  repliedMessageType: MessageTypeEnum
}
````
2. Use the below observe query to print the updates:

````dart
_stream = Amplify.DataStore.observeQuery(
      Message.classType,
      where: Message.SENDERID.eq('7ca4c5ec-b3af-49f8-afce-b5194a781a7d'),
      sortBy: [Message.TIMESENT.ascending()],
    ).listen((QuerySnapshot<Message> snapshot) {
      setState(() {
        print("*************Got a new message in observe query listen");
        _messages = snapshot.items;
      });
    });

````

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.10.5

### Amplify Flutter Version

^1.0.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Message @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey(sortKeyFields: ["timeSent"])
  senderId: String
  receiverId: String
  message: String!
  type: MessageTypeEnum!
  timeSent: String!
  isSeen: String
  repliedMessage: String
  repliedTo: String
  repliedMessageType: MessageTypeEnum
}
```

**Comment by soheb12** [comment]
On further i found the issue is with having a sort key enabled on the table. On removing it things work fine. Can we look into this bug, because i need the sort key on the table.

**Comment by Jordan-Nelson** [comment]
@soheb12 - Can you share the code you are using to add new messages?

**Comment by soheb12** [comment]
Here's the code for saving messages:

```
 var senderToReceiverMessage = Message(
      id: convId,
      message: text,
      type: type,
      receiverId: receiverId,
      senderId: senderId,
      timeSent: timeSent,
      isSeen: isSeen,
      repliedMessage: repliedMessage,
      repliedTo: repliedTo,
      repliedMessageType: repliedMessageType,
    );
    
 Amplify.DataStore.save(senderToReceiverMessage)
```

**Comment by Jordan-Nelson** [comment]
@soheb12 where is the value for convId coming from?

**Comment by soheb12** [comment]
This is UUID generated on the fly using `UUID.getUUID()` function

**Comment by Jordan-Nelson** [comment]
@soheb12 I am not able to reproduce this issue on iOS or Android. I am using a slightly simplified version of the schema you are using. Below is the app I am using to attempt to reproduce this.

If you are still facing this issue can you:
- Remove `convId` - If you want a generated ID, omitting the value will result in a generated ID
- Provide a minimal reproduction of the problem (similar to the app that I have shared).
- Confirm if you have cloud sync enabled (are you adding AmplifyAPI?)
- Confirm the platform you are seeing this on (iOS or Android)

```dart
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';
import 'models/ModelProvider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _messages = <Message>[];

  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  void _configureAmplify() async {
    try {
      await Amplify.addPlugin(AmplifyAPI());
      await Amplify.addPlugin(
        AmplifyDataStore(modelProvider: ModelProvider.instance),
      );
      await Amplify.configure(amplifyconfig);
      Amplify.DataStore.observeQuery(
        Message.classType,
        where: Message.SENDERID.eq('7ca4c5ec-b3af-49f8-afce-b5194a781a7d'),
        sortBy: [Message.TIMESENT.ascending()],
      ).listen((QuerySnapshot<Message> snapshot) {
        setState(() {
          safePrint("*************Got a new message in observe query listen");
          safePrint("Number of items: ${snapshot.items.length}");
          _messages = snapshot.items;
        });
      });
      safePrint('Successfully configured');
    } on Exception catch (e) {
      safePrint('Error configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: FilledButton(
            onPressed: () async {
              var senderToReceiverMessage = Message(
                message: 'message 1',
                receiverId: uuid(),
                senderId: '7ca4c5ec-b3af-49f8-afce-b5194a781a7d',
                timeSent: uuid(),
              );

              await Amplify.DataStore.save(senderToReceiverMessage);
            },
            child: const Text('Add Message'),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Jordan-Nelson** [comment]
@soheb12 - I am going to close this since we have not heard back. If you are still facing this issue, please provide the info requested in https://github.com/aws-amplify/amplify-flutter/issues/3588#issuecomment-1696224578.
