### ISSUE TITLE
Field 's3pluginConfig' has not been initialized." - Storage Dart - Late Error

### ISSUE THREAD

**Issue by Stivenmore** [aws-amplify/amplify-flutter#3592]
### Description

When trying to download a document I receive an error based on the configuration of the plugin used to give it that it has not been initialized.
I decided to read the internal code a little more and I see that it is correct but it must take the configuration and go from not being initialized (late), after taking this configuration, but I think this is not happening, could you give me a hand with this?

By the way, thank you very much.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Screenshots

![Captura de pantalla 2023-08-22 a la(s) 2 15 13 p m](https://github.com/aws-amplify/amplify-flutter/assets/62867486/03f52821-6efd-4823-957e-a44d8b076d7e)
![Captura de pantalla 2023-08-22 a la(s) 2 14 46 p m](https://github.com/aws-amplify/amplify-flutter/assets/62867486/4322e23b-394a-4ef6-bd47-53d9a2dab7fe)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.3

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hey @Stivenmore, sorry you encountered this exception. 

Can you please ensure you are calling `Amplify.configure(...)` with the storage plugin? [See docs](https://docs.amplify.aws/lib/storage/getting-started/q/platform/flutter/#initialize-amplify-storage)

If so, can you please provide this code snippet?

**Comment by Stivenmore** [comment]
@Equartey Do not worry, I appreciate the help with this incident, I will attach two screenshots.

1. My amplify configuration (I use other services like auth, api, analitycs).

2. My Storage Settings

![Captura de pantalla 2023-08-22 a la(s) 3 23 13 p m](https://github.com/aws-amplify/amplify-flutter/assets/62867486/108bf522-ab5a-4888-b891-15bb3dd8701c)
![Captura de pantalla 2023-08-22 a la(s) 3 23 22 p m](https://github.com/aws-amplify/amplify-flutter/assets/62867486/9f0f5fa3-e90b-4c4e-b29d-fd4b3a8ca323)

**Comment by Equartey** [comment]
@Stivenmore thanks for providing that context.

You need to call `await Amplify.addPlugins([...]);` before you call `await Amplify.configure(amplifyconfig);`. 

Try this:
```dart
...
final auth = AmplifyAuthCognito();
final api = AmplifyAPI();
final storage = AmplifyStorageS3();
final analytics = AmplifyAnalyticsPinpoint();


await Amplify.addPlugins([auth, api, storage, analytics]);
final amplifyconfig = json.encode(awsGlobalConfig);
await Amplify.configure(amplifyconfig);
...
```

Be sure to customize your plugin definitions as needed. 

Please let me know if you have additional questions.

**Comment by Equartey** [comment]
Hey @Stivenmore, sorry for the delay. Are you still facing this issue?

**Comment by Jordan-Nelson** [comment]
@Stivenmore - I am going to close this out since we have not heard back. If you are still facing this issue, please let us know and we can re-open the issue.
