### ISSUE TITLE
Sending/Receiving Push Notifications by Segment

### ISSUE THREAD

**Issue by zoenberger** [aws-amplify/amplify-flutter#360]
*NOTE: We are _not_ using Cognito for user management. All Pinpoint behavior will go through "guest" access. (Which, it is not clear if this works or if we _must_ use Cognito to authenticate uses for Pinpoint)

Currently, we've integrated the firebase_messaging package. This generates a token, and I can send a test message from the Pinpoint console using this token. However, I have to use a raw message and use this template for it to actually create a notification on an Android device and be handled by the Flutter app when the notification is clicked.

```
{
  "GCMMessage": {
    "notification": {
      "title": "Test Title",
      "body": "Test Notification Text"
    },
    "data": {
      "destinationKey": "Alert",
      "click_action": "FLUTTER_NOTIFICATION_CLICK"
    }
  }
}
```

I've also generated a button I can press to add details to the user:

```
  void _identifyUser() async {
    AnalyticsUserProfile analyticsUserProfile = new AnalyticsUserProfile();
    analyticsUserProfile.plan = "Premium";

    Amplify.Analytics.identifyUser(
        userId: "userid1", userProfile: analyticsUserProfile);
  }
```

Then, when I generate an event, this additional parameter ("plan") will show up in Pinpoint console. For example, Demographics will have a custom attribute of "plan" that will show breakdown of "Premium" users.

Next, I can then go to segments and attempt to create a segment of mobile users with a "Premium" plan:
![image](https://user-images.githubusercontent.com/13423987/107135790-87fe7600-68b2-11eb-8a7a-9ab012df0071.png)

I can not get a push notification campaign target at this segment to produce a push notification to the device. (Again, I can send a test message by device token.)

Can the Amplify Flutter SDK currently meet this use case? I think what I'm trying to do is register the device as being part of a segment so I can target it with campaigns.

**Comment by fjnoyp** [comment]
Hi @zoenberger 

So to clarify, you're able to get push notifications if you target by device token, but do not get push notifications if you target a segment?

**Comment by zoenberger** [comment]
Hi @fjnoyp 

Yes, that is correct. I can send a "test" message to any device using a token. In this case, I only made one device use the "premium" plan. 

The events I created were used with anonymous authentication (which the Amplify CLI scaffolded into Cognito). I think the issue is that since we're not using Cognito there is no way for the user metadata to be saved and associated with that device (token). So when a segment is created _(all mobile devices with 'premium' plan)_ there is no way identify the end users/devices.

**Comment by fjnoyp** [comment]
Hi @zoenberger 

Did adding in Cognito fix the issue you were encountering here?

**Comment by zoenberger** [comment]
@fjnoyp This "issue" is not a problem related to Cognito. I'm trying to better understand what use cases are currently supported with Amplify Flutter.

**Comment by fjnoyp** [comment]
Hi @zoenberger 

Looked more into this issue and found that targeting devices by segment will not work.  The Amplify Flutter library is built on Amplify iOS and Android native libraries which currently have no official support for push notifications.  

Pinpoint can send push notiications with either an endpoint ID or a device token.  You got device token to work, but segment targeting will not work because we do not setup any endpoint ID.  

We are considering adding push notification support in the future and can keep you updated.  We will use the below issue to keep track of adding proper push notification support in Flutter:  

[https://github.com/aws-amplify/amplify-flutter/issues/319](url)

**Comment by fjnoyp** [comment]
Feel free to upvote that issue to give it more visibility to our team as well. 

If you don't mind, I will close this issue soon so that we can keep track of push notification support in a single issue (319).

**Comment by zoenberger** [comment]
This is exactly the information I was looking for. Thank you for looking into it.
