### ISSUE TITLE
Traling slash added at the end of endpoint

### ISSUE THREAD

**Issue by dagovalsusa** [aws-amplify/amplify-flutter#3625]
### Description

Hello, 

A slash is added to the end of the url endpoint which then causes a bad response (404) from the endpoint itself.
Our setup is as follows

` "api": {
      "plugins": {
        "awsAPIPlugin": {
          "APPGQL": {
            "endpointType": "GraphQL",
            "endpoint": "https://xxxx.xxx.xx/graphql",
            "region": "us-east-1",
            "authorizationType": "AMAZON_COGNITO_USER_POOLS"
          }
        }
      }
    }`

but the http call url has an extra "/" at the end as seen from the picture

<img width="1439" alt="Screenshot 2023-08-28 alle 16 52 22" src="https://github.com/aws-amplify/amplify-flutter/assets/11755587/e52135dc-4eeb-4136-9f64-c995b5a701ce">

we debugged and we noticed that in the amplify-flutter/packages/api/amplify_api_dart/lib/src/util/amplify_api_config.dart file in the getUri method the path '' adds one slash too many

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Configure amplify
2. run a query 

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.1

### Amplify Flutter Version

1.3.3 (latest)

### Deployment Method

Custom Pipeline

**Comment by dagovalsusa** [comment]
Hello, the pull request memtioned up doesn't works
Anyone have a suggestions or know who o where the "/" is added?

**Comment by dagovalsusa** [comment]
I tried the pull request mentioned up as @dnys1 suggested.
It works and sounds great, anyone can merge and release it? Or in alternative, how I can use the forked branch?
Thanks

**Comment by Jordan-Nelson** [comment]
@dagovalsusa @alegos27 - I do see that the trailing `/` is added, but I don't see that this results in an issue. Are you using a custom domain?

**Comment by dagovalsusa** [comment]
Hi @Jordan-Nelson, yes we use a custom domain, and in this specific case we use Apollo as supergraph, but the issue is that the path /graphql is considered different from /graphql/ (ex. also Google suggest to rewrite the url without / through .htaccess rules to optimize SEO)
In our case, the error is a 404 {"message": "Not Found"} on /graphql/ https POST, as you can see in the attached image on first message
Thanks

**Comment by dnys1** [comment]
The fix for this has been released. Please run `flutter pub upgrade` to get the fix.

Apologies for the delay! Let us know if you face any similar issues.
