### ISSUE TITLE
DataStore - iOS - GraphQL list of any type fails to save

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#363]
DataStore on iOS does not save fields where the data type is a list.\

**To Reproduce**
1. Create a GraphQL schema with any list type:
   ```graphql
   type TestModel @model {
      id: ID!
      intList: [Int]
      floatList: [Float]
      stringList: [String]
      boolList: [Boolean]
   }
1. Generate the models
   ```bash
   amplify codegen models
   ```
1. Push the backend
   ```bash
   amplify push --yes
   ```
1. In the code populate the TestModel and save it
   ```dart
   final testModel = TestModel(...);
   await Amplify.DataStore.save(testModel);
   ```
1. Note that the fields in DynamoDB are missing.
 
**Expected behavior**
Data gets saved to backend.

**Platform**
Amplify Flutter on iOS - 0.0.2-dev.1

**Additional context**
Models saved to the backend from Android are discarded during initial sync on iOS.
Demo project [can be found here](https://github.com/kjones/datastore_test) 

Seems like there may be a disconnect between how the Flutter SDK is defining a list and how iOS expects the definition to look. Flutter codegen creates the definition with a type of `ModelFieldTypeEnum.collection` ([example](https://github.com/kjones/datastore_test/blob/4cc41f5459032a98a976a908422ef2a16044c4d4/lib/models/TestModel.dart#L332)). The Amplify iOS SDK uses the term [embeddedCollection](https://github.com/aws-amplify/amplify-ios/blob/30c5fa521c87029ae6d5431eb5fac34bd56e9d74/Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema%2BDefinition.swift#L25) for lists whereas [collection](https://github.com/aws-amplify/amplify-ios/blob/30c5fa521c87029ae6d5431eb5fac34bd56e9d74/Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema%2BDefinition.swift#L27) is used when referring to other models.

**Comment by kjones** [comment]
Slightly related to: #289

**Comment by Amplifiyer** [comment]
New version is released with this fix! Please test and close when you can.

**Comment by kjones** [comment]
Every list type I listed above seems to be working. Can't save or sync a model with an enumList now on iOS which I think was working in 0.0.2-dev.1.

Test project here: https://github.com/kjones/datastore_test

**Comment by Amplifiyer** [comment]
It seems enum lists need to be of `.embeddedCollection` type as well. If that's the case I can't imagine it being working before 0.0.2-dev.2. Will verify and launch it in next release.

**Comment by kjones** [comment]
> If that's the case I can't imagine it being working before 0.0.2-dev.2.

That could certainly be the case. I hadn't played with this test app since early Jan at the time of the 0.0.1-dev.6 release so memory is a little vague.

> Will verify and launch it in next release.

Thx
