### ISSUE TITLE
DataStore - Android - Integer list fails serialization

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#365]
DataStore on Android crashes when serializing a list of integers synchronized from the backend.

**To Reproduce**
1. Create a GraphQL schema with an integer list type:
   ```graphql
   type TestModel @model {
      id: ID!
      intList: [Int]
   }
1. Generate the models
   ```bash
   amplify codegen models
   ```
1. Push the backend
   ```bash
   amplify push --yes
   ```
1. In the code populate the TestModel and save it
   ```dart
   final testModel = TestModel(intList: [1, 2, 3]);
   await Amplify.DataStore.save(testModel);
   ```
1. Clear local DataStore and query so that the saved model gets retrieved from the backend.
   ```dart
   await Amplify.DataStore.clear();
   final queryResult = await Amplify.DataStore.query(TestModel.classType);
   ```
1. Failure doesn't actually occur during serialization but when you attempt to use `intList`.
   ```dart
   final testModel = queryResult[0];
   final someOtherList = testModel.intList.map((i) => i + 1).toList();   // Crashes here
   ```
 
**Expected behavior**
DataStore models with integer lists  are correctly deserialized.

**Platform**
Amplify Flutter on Andriod - 0.0.2-dev.1
Also tested with local Flutter 0.0.2-dev.1 build that uses Android SDK build 1.16.11

**Additional context**
Appears to work locally but fails converting double to int on models synchronized from the  backend. Data models coming from the Android SDK are a list of double when they get to the Dart codegen deserialization ([example](https://github.com/kjones/datastore_test/blob/4cc41f5459032a98a976a908422ef2a16044c4d4/lib/models/TestModel.dart#L228)). Using `.cast<int>()` fails during enumeration of the list when underlying  is a List<double>.
Demo project [can be found here](https://github.com/kjones/datastore_test)

**Comment by Amplifiyer** [comment]
I noticed that in my testing as well. Can you try by replacing deserialization code in `fromJson` method of your model by the following
```dart
        intList = (json['intList'] as List)
            .map((e) => e is double ? e.toInt() : e as int)
            .toList(),
```

**Comment by kjones** [comment]
@Amplifiyer That does work.

Still hoping to see the generated code pass pedantic analysis with implicit casts/dynamic disabled at some point so slightly modified version:
```dart
intList = (json['intList'] as List<dynamic>)
  .map((dynamic e) => e is double ? e.toInt() : e as int)
  .toList(),
```

**Comment by Amplifiyer** [comment]
@kjones we have launched this in our new release (please ensure to install latest amplify cli and amplify-flutter packages)

For generated code to pass pedantic analysis, we will be investigating after critical features and bugs are out!

**Comment by kjones** [comment]
Looks good. Thanks.
