### ISSUE TITLE
Add timeout configuration for REST request (Amplify.API)

### ISSUE THREAD

**Issue by fvisticot** [aws-amplify/amplify-flutter#3650]
### Description

I need to configure a timeout to call the REST API backend.
It seems not possible to configure the timeout in the post method or in the Amplify.API ?

Is there a solution ? using a custom AWSCustomHttpClient ?

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.3.2

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@fvisticot Here is one option:

```dart
final operation = Amplify.API.post(...);
final response = await operation.response.timeout(
  const Duration(seconds: 5),
  onTimeout: () async {
    await operation.cancel();
    throw TimeoutException('The request timed out.');
  },
);
```

If you found yourself using this on multiple requests, you could write a utility or extension for it. For example:
```dart
// ext
extension RestOperationTimeout on RestOperation {
  RestOperation withTimeout({Duration duration = const Duration(seconds: 5)}) {
    return this
      ..response.timeout(
        duration,
        onTimeout: () async {
          await operation.cancel();
          throw TimeoutException('The request timed out.');
        },
      );
  }
}
```

```dart
// use
final operation = Amplify.API.post(...).withTimeout();
```

Let me know if that meets your use case.

**Comment by Jordan-Nelson** [comment]
Hello @fvisticot - Let me know if this doesn't solve your use case

**Comment by fvisticot** [comment]
Hello Jordan, 
Sorry for my late answer.
It's working perfectly with your detailed example !
Tx a lot

**Comment by fvisticot** [comment]
Closed
