### ISSUE TITLE
Documentation all APIs and exceptions

### ISSUE THREAD

**Issue by parikh20** [aws-amplify/amplify-flutter#367]
Is there a place where all of the exception names and details are cleanly laid out for in app handling? Having to manually check for each possible type just to get the name of the exception is getting quite exhausting.

**Comment by Amplifiyer** [comment]
@parikh20, we are completely rewriting the error handling such that the errors received from the APIs will be consistent and easy to inspect. We will update our documentation after the release.

**Comment by Jordan-Nelson** [comment]
Hi @parikh20 - The documentation on pub has a section for Exceptions. For example, you can reference the "Exceptions / Errors" section [here](https://pub.dev/documentation/amplify_flutter/latest/amplify_flutter/amplify_flutter-library.html) for amplify_flutter or [here](https://pub.dev/documentation/amplify_auth_cognito/latest/amplify_auth_cognito/amplify_auth_cognito-library.html) for amplify_auth_cognito.

I know this request is quite old and those Exceptions may not have been documented when you opened the issue. If there is something more you are looking for, please let me know.

**Comment by Jordan-Nelson** [comment]
Closing this issue out as completed. Please let us know if the links shared above are not what you are looking for.
