### ISSUE TITLE
Wanted 1 metadata for item with id

### ISSUE THREAD

**Issue by tiyberius** [aws-amplify/amplify-flutter#3672]
### Description

Some mutations succeed, while others fail with this cryptic error message. I'm sure you guys will need some more information, but for now I'm just following orders, as it does say please report to AWS :)

I/amplify:aws-datastore(26556): Starting attempt #9
W/amplify:aws-datastore(26556): Attempt #9 failed.
W/amplify:aws-datastore(26556): DataStoreException{message=Wanted 1 metadata for item with id = 5cecfdb5-02df-40cc-b6f0-d8990fdf1cb4, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
W/amplify:aws-datastore(26556): 	at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:91)
W/amplify:aws-datastore(26556): 	at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$findModelVersion$0$com-amplifyframework-datastore-syncengine-VersionRepository(VersionRepository.java:64)
W/amplify:aws-datastore(26556): 	at com.amplifyframework.datastore.syncengine.VersionRepository$$ExternalSyntheticLambda0.accept(Unknown Source:8)
W/amplify:aws-datastore(26556): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:407)
W/amplify:aws-datastore(26556): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda6.run(Unknown Source:10)
W/amplify:aws-datastore(26556): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/amplify:aws-datastore(26556): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore(26556): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore(26556): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore(26556): 	at java.lang.Thread.run(Thread.java:920)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

This is only happening on Android. If you take a look at the schema, I can update the "skill_level" String but not the "email_notifications_enabled" boolean or any other bool in the "NotificationSettings" type.

I'm sure you'll need more info, but I'm using the latest version of amplify-flutter

  amplify_flutter: ^1.4.0
  amplify_api: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_authenticator: ^1.4.0
  amplify_datastore: ^1.4.0

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type User @model @auth(rules: [
    { allow: private, provider: iam }
    { allow: owner, operations: [read, update, create] }
    ]) {
    user_name: String! @primaryKey
    notification_settings: NotificationSettings
}

type NotificationSettings {
    email_notifications_enabled: Boolean
    sms_notifications_enabled: Boolean
    app_notifications_enabled: Boolean
    email_address: String
}
```

**Comment by Jordan-Nelson** [comment]
Hello @tiyberius - Is this occurring during the initial sync? If it is occurring after saving data, please share the code you are using the save the data. Thanks.

**Comment by Jordan-Nelson** [comment]
Can you are the model (as it exists in AppSync/Dynamo) with that model ID? You can remove/mask any data. I am really just looking to see if it is missing any fields.

**Comment by tiyberius** [comment]
Hey @Jordan-Nelson thanks for the prompt response. I came into work after leaving it for a weekend and everything is working now, I can't seem reproduce the error. If it pops up again I'll re-open this issue! Cheers

**Comment by stevegaunt** [comment]
@Jordan-Nelson 
I have this

W/amplify:aws-datastore( 7836): Attempt #8 failed.
W/amplify:aws-datastore( 7836): DataStoreException{message=Wanted 1 metadata for item with id = e4d7cdfa-6b61-4c2b-8345-5a2e45defaae, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}


I think I managed to create this whilst doing quite a lot of mutations and the closing the app

Is it possible this can be reopened?

**Comment by Jordan-Nelson** [comment]
@stevegaunt - Apologies for missing this. Can you open a new issue with reproduction steps? Thanks
