### ISSUE TITLE
AWS Amplify Flutter Demo - "No Pinpoint plugin config available."

### ISSUE THREAD

**Issue by ryan-weil** [aws-amplify/amplify-flutter#3677]
### Description

I have downloaded and configured the AWS Amplify Flutter example located here: https://github.com/aws-samples/aws-amplify-flutter-example and ran the following commands as demonstrated in the setup instructions for AWS Amplify:
```
$ amplify pull --appId <app_id>--envName staging
$ amplify update auth
```

Upon building and attempting to run the project, it crashed with this error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ConfigurationError {
  "message": "No Pinpoint plugin config available."
}
#0      AmplifyAnalyticsPinpointDart.configure
analytics_plugin_impl.dart:88
#1      AmplifyClassImpl.configurePlatform.<anonymous closure>
amplify_class_impl.dart:75
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      Future.wait (dart:async/future.dart:523:26)
#5      AmplifyClassImpl.configurePlatform
amplify_class_impl.dart:67
#6      AmplifyClass.configure
amplify_class.dart:113
#7      AppState._configureAmplify
main.dart:81
<asynchronous suspension>
```

I tried following the instructions [here](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/flutter/#prerequisites) as it seemed the cause of the problem was that the aforementioned flutter example was using analytics (for whatever reason), but this did not seem to have any effect on remediating the error. I get the same issue even after following those instructions.

Hopefully someone here can help

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
The error indicates that your amplifyconfiguration.dart file doesn't have a section for analytics. Can you share your amplifyconfiguration.dart file (with any sensitive info removed)?

**Comment by ryan-weil** [comment]
> The error indicates that your amplifyconfiguration.dart file doesn't have a section for analytics. Can you share your amplifyconfiguration.dart file (with any sensitive info removed)?

Thank you for your reply. Sure, here is the config file:

```
const amplifyconfig = '''{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxx",
                        "AppClientId": "xxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL",
                            "GIVEN_NAME",
                            "FAMILY_NAME"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS",
                                "REQUIRES_UPPERCASE"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Comment by Jordan-Nelson** [comment]
Thanks.

As expected, there is no section for Analytics. I see you started by running `amplify pull --appId <app_id>--envName staging`. Where did those set up steps come from?

**Comment by ryan-weil** [comment]
> Thanks.
> 
> As expected, there is no section for Analytics.

That makes sense. How can I generate/create that section?

> I see you started by running `amplify pull --appId <app_id>--envName staging`. Where did those set up steps come from?

Those were from AWS in the Authentication tab. Are those instructions incorrect to install Amplify into the Flutter project?

**Comment by ryan-weil** [comment]
Commenting out the PinPoint Analytics line like so:

```
Future<void> _configureAmplify() async {
    try {
      await Amplify.addPlugins([
        AmplifyAPI(modelProvider: ModelProvider.instance),
        AmplifyAuthCognito(),
        AmplifyStorageS3(),
        //AmplifyAnalyticsPinpoint(),
      ]);
      await Amplify.configure(amplifyconfig);

      safePrint('Successfully configured Amplify.');
    } on Exception catch (e) {
      safePrint('Could not configure Amplify. error: $e');
    }
  }
}
```
Changes the error to 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ConfigurationError {
  "message": "No AWS API config found",
  "recoverySuggestion": "Add API from the Amplify CLI. See https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#configure-api"
}
```

**Comment by Jordan-Nelson** [comment]
That sample project makes use of GraphQL API, Auth, Storage, and Analytics. You would need to set up all of those categories to use that sample. I am not familiar with that specific example app. It might require other setup steps. You can open an issue in that repo if there are no setup steps, or if the setup steps are unclear.

**Comment by ryan-weil** [comment]
> That sample project makes use of GraphQL API, Auth, Storage, and Analytics. You would need to set up all of those categories to use that sample. I am not familiar with that specific example app. It might require other setup steps. You can open an issue in that repo if there are no setup steps, or if the setup steps are unclear.

Understood. Do you happen to know if there exists an example repository that is more barebones and simply demonstrates amplify auth using Flutter? As opposed to throwing in all these over complicated things like GraphQL.
