### ISSUE TITLE
Push Notifications to two different applications

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3679]
Hello everyone.

I've been researching on how to send a push notification to two different applications but I didn't find any clear answer or way to do this.

Context:
I have two applications that share the same amplify backend. I successfully implemented push notifications in the first app but it's crucial for me to also send notifications to my second app - think, for example, of Uber (or Booking) and how the application of the user and the one for the driver are linked together and based on some event a notification is sent to either one.

I don't know if the way to do this is to have two Pinpoint projects linked together somehow, or if it's possible to register two app IDs in the same one or there is another, better, way to achieve this.

I'm on a really tight deadline so any basic guidance or help would be greatly appreciated.

Thank you!

**Comment by jamilsaadeh97** [comment]
Hi @dnys1 , kind reminder 🙏

**Comment by jamilsaadeh97** [comment]
I am currently using the same Amplify project in both apps yes.

**Comment by jamilsaadeh97** [comment]
Hi @dnys1, I did more digging and I found [this](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns)
It's stated that: "You can use one token to distribute notifications for all of your company’s apps."

Basically if I use a key (.p8 file) instead of a certificate (.p12 file) when I register an APNS channel with `amplify add notifications` I can maybe send a notification to either one of my applications. 

However, in the docs, it's not mentioned how to use a key instead of a certificate when the CLI prompts me with:
```
Select the authentication method for the APNS channel . Key
```

It's also mentioned that I need to send a JWT to the APNS server along with the push notification. Is that possible to do in my lambda function with the Pinpoint SendMessage command or is it done automatically by Pinpoint?

Thank you for your help and time!

**Comment by dnys1** [comment]
Thanks for doing some more digging and investigation. it does appear that only a single bundle ID can be used per Pinpoint project, unfortunately.

To work around this, I think you would either need two separate Amplify projects or to manage the two Pinpoint projects outside of Amplify.

**Comment by jamilsaadeh97** [comment]
Hi @dnys1 thanks for your reply.

I don't know if two Amplify projects is doable in my case. The two applications rely on real time and they share most of the data from AppSync.

By doing two Amplify projects can the data be linked together? Like in my example of Uber (a ride is shared between the user and the driver). Could you provide me with more info if this is something possible? (Or to make the two Amplify projects have the same Api GraphQL)

Regarding your second suggestion, how can this be done? If I want to register the endpoints and analytics for example.

**Comment by dnys1** [comment]
It's not currently possible to have two Amplify apps share data changes. That would require a lot of manual work to coordinate between the apps.

For the second suggestion, you would need to create the Pinpoint projects using the AWS console or an IaC tool like CloudFormation/CDK and make sure that the IAM permissions were appropriately mapped back to your Amplify project. You could then use the `AmplifyConfig` class in Dart to append the Pinpoint project information to your Amplify CLI configuration.

**Comment by jamilsaadeh97** [comment]
Thank you for your quick reply.

I don't have any experience using the CDK.
I'm going to try implementing that and let you know if I'm stuck somewhere if you don't mind.

Thank you so much!

**Comment by jamilsaadeh97** [comment]
But generally speaking, that would mean each time I do an amplify pull, I need to re-edit the amplifyconfig file for the pinpoint projects right?

**Comment by dnys1** [comment]
Sounds good. Let me know if you get stuck.

I would recommend keeping your `amplifyconfiguration.dart` file untouched and doing the following in your configure method.

```dart
// Start by parsing your CLI config
var config = AmplifyConfig.fromJson(
  jsonDecode(e2eTest.config) as Map<String, dynamic>,
);
// Then add push notifications depending on the app
config = config.copyWith(
  notifications: const NotificationsConfig(
    plugins: {
      NotificationsPinpointPluginConfig.pluginKey:
          NotificationsPinpointPluginConfig(
        // Different depending on the app
        appId: '<APP_ID>',
        region: '<REGION>',
      ),
    },
  ),
);
await Amplify.configure(jsonEncode(config));
```

**Comment by jamilsaadeh97** [comment]
Oh that's very helpful thank you!

Will let you know if anything.
If you don't mind keeping this open for a few days.

**Comment by dnys1** [comment]
Not at all 🙂

**Comment by jamilsaadeh97** [comment]
Hi @dnys1 

Everything is working now. Push notifications are delivered to the two applications!

I created another Pinpoint project from the console and added the `mobiletargeting:GetUserEndpoints` and `mobiletargeting:SendMessages` policies that reference the new Pinpoint project to the auth and unAuth role of my amplify project.

Since this is my first time creating resources outside of Amplify and linking back to Amplify, is there any additional steps that I need to take care of or something to keep in mind? Or if CDK was a better approach?

Thank you so much for your guidance and your time!

**Comment by dnys1** [comment]
I'm glad to hear it! There's nothing special you need to do. If you have more resources than the Pinpoint projects, I would recommend looking into CloudFormation or CDK as it will make it easier to manage multiple resources. But otherwise, you should be good to go 👍 

Please let us know if you face any other issues.

**Comment by jamilsaadeh97** [comment]
Sounds great!
