### ISSUE TITLE
Failed send analytics to console

### ISSUE THREAD

**Issue by bostaginting** [aws-amplify/amplify-flutter#368]
Hi, I'm currently trying analytics for flutter. after pushing the events there is something weird happen, the event name is succeeded but the Event Attributes and Metrics is empty:

![Screen Shot 2021-02-09 at 13 32 45](https://user-images.githubusercontent.com/40355270/107325090-bd39dc80-6adb-11eb-9e53-297bd0aa82ce.png)

here is my configuration 

<img width="591" alt="Screen Shot 2021-02-09 at 13 27 53" src="https://user-images.githubusercontent.com/40355270/107325139-d6428d80-6adb-11eb-81af-acac314cae6f.png">

and function to set new events 

<img width="523" alt="Screen Shot 2021-02-09 at 13 35 13" src="https://user-images.githubusercontent.com/40355270/107325176-e6f30380-6adb-11eb-8994-33375250ba55.png">

is there something wrong with the code?

**Comment by fjnoyp** [comment]
Hi @bostaginting are you testing on iOS or Android?

**Comment by fjnoyp** [comment]
@bostaginting we were able to reproduce this issue on iOS.  We have a fix that will be merged and included in our next release: 
https://github.com/aws-amplify/amplify-flutter/pull/383

**Comment by bostaginting** [comment]
ok thank you, already testing it, and it works now thank you.
