### ISSUE TITLE
signInWithWebUI reports a crash even if exception is handled using try catch statement.

### ISSUE THREAD

**Issue by sourabhguptazeil** [aws-amplify/amplify-flutter#3682]
### Description

signInWithWebUI reports a crash even if exception is handled using try catch statement.

The code is like this

```
Future<SignInResult?> signInWithGoogle() async {
    try {
      final result = await Amplify.Auth.signInWithWebUI(
          options: const SignInWithWebUIOptions(
            pluginOptions: CognitoSignInWithWebUIPluginOptions(
              isPreferPrivateSession: true,
            ),
          ),
          provider: AuthProvider.google);
      return result;
    } on UserCancelledException catch (e) {
      return null;
    } on AmplifyException catch (e) {
      return null;
    }
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Start social authentication
2. Cancel the authentication

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.4.0

### Deployment Method

Custom Pipeline

**Comment by dnys1** [comment]
Hi @sourabhguptazeil, sorry you are facing this issue.

Can you let me know what you mean by a crash? Can you provide any error messages or exceptions/stack traces which are thrown?

**Comment by sourabhguptazeil** [comment]
@dnys1 I have integrated crashlytics in our app. The crash is recorded there if user cancels the social authentication.

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: UserCancelledException {
  "message": "The user cancelled the sign-in flow"
}
flutter: 
package:amplify_auth_cognito/src/flows/hosted_ui/hosted_ui_platform_flutter.dart 96:11   HostedUiPlatformImpl.signIn
===== asynchronous gap ===========================
package:amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 131:5  HostedUiStateMachine.onSignIn
===== asynchronous gap ===========================
package:amplify_auth_cognito_dart/src/state/machines/hosted_ui_state_machine.dart 57:9   HostedUiStateMachine.resolve
===== asynchronous gap ===========================
package:amplify_core/src/state_machine/state_machine.dart 262:11                         StateMachine._listenForEvents.<fn>
===== asynchronous gap ===========================
package:amplify_core/src/state_machine/state_machine.dart 251:7                          StateMachine._listenForEvents
===== asynchronous gap ===========================
package:amplify_core/src/state_machine/event.dart 43:47                                  new EventCompleter
package:amplify_core/src/state_machine/<…>
flutter: ----------------------------------------------------
```

**Comment by dnys1** [comment]
Thank you for the information. This is unfortunately a bug, which I've raised a PR for [here](https://github.com/aws-amplify/amplify-flutter/pull/3686).

I apologize for the inconvenience and will get this released early this week.

**Comment by dnys1** [comment]
The fix for this has been released. Please run `flutter pub upgrade` to get the fix.

Apologies for the delay! Let us know if you face any similar issues.

**Comment by IsuruCTS** [comment]
I am getting this same error when trying to login through 'Microsoft AD' federated login on an iOS device (iOS 16.7.2). 
After logging in with Microsoft AD (two factor authenticate using the Authenticator app), this issue occurs. 
However, I am able to log in successfully in the simulator. Please let me know any solution about this issue.

Flutter Version
3.16.3

Amplify Flutter Version:

amplify_flutter: ^1.6.1
amplify_auth_cognito: ^1.6.1


catch this error: 
`UserCancelledException {
  "message": "The user cancelled the sign-in flow"
}`
And this error in Debug console:
`[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:9624 (
	0   AXRuntime                           0x00000001e616d960 _AXGetPortFromCache + 940
	1   AXRuntime                           0x00000001e616fe84 AXUIElementPerformFencedActionWithValue + 848
	2   UIKit                               0x00000002400301ec BAA2EF76-5F22-34FE-960D-04C473D0D29A + 737772
	3   libdispatch.dylib                   0x00000001c4b7c7a8 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 407464
	4   libdispatch.dylib                   0x00000001c4b7d780 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 411520
	5   libdispatch.dylib                   0x00000001c4b586fc 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 259836
	6   libdispatch.dylib                   0x00000001c4b591b0 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 262576
	7   libdispatch.dylib                   0x00000001c4b62f14 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 302868

	8   libsystem_pthread.dylib             0x0000000207e29bd0 _pthread_wqthread + 284
	9   libsystem_pthread.dylib             0x0000000207e29720 start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:9624 (
	0   AXRuntime                           0x00000001e616d960 _AXGetPortFromCache + 940
	1   AXRuntime                           0x00000001e616fe84 AXUIElementPerformFencedActionWithValue + 848
	2   UIKit                               0x00000002400301ec BAA2EF76-5F22-34FE-960D-04C473D0D29A + 737772
	3   libdispatch.dylib                   0x00000001c4b7c7a8 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 407464
	4   libdispatch.dylib                   0x00000001c4b7d780 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 411520
	5   libdispatch.dylib                   0x00000001c4b586fc 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 259836
	6   libdispatch.dylib                   0x00000001c4b591b0 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 262576
	7   libdispatch.dylib                   0x00000001c4b62f14 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 302868
	8   libsystem_pthread.dylib             0x0000000207e29bd0 _pthread_wqthread + 284
	9   libsystem_pthread.dylib             0x0000000207e29720 start_wqthread + 8
)
[AXRuntimeCommon] AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:9624 (
	0   AXRuntime                           0x00000001e616d960 _AXGetPortFromCache + 940
	1   AXRuntime                           0x00000001e616fe84 AXUIElementPerformFencedActionWithValue + 848
	2   UIKit                               0x00000002400301ec BAA2EF76-5F22-34FE-960D-04C473D0D29A + 737772
	3   libdispatch.dylib                   0x00000001c4b7c7a8 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 407464
	4   libdispatch.dylib                   0x00000001c4b7d780 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 411520
	5   libdispatch.dylib                   0x00000001c4b586fc 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 259836
	6   libdispatch.dylib                   0x00000001c4b591b0 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 262576
	7   libdispatch.dylib                   0x00000001c4b62f14 30AB7A30-04BC-3C9C-AE24-8DE17D9D2AF2 + 302868
	8   libsystem_pthread.dylib             0x0000000207e29bd0 _pthread_wqthread + 284
	9   libsystem_pthread.dylib             0x0000000207e29720 start_wqthread + 8
)`
