### ISSUE TITLE
iOS social sign out makes the app stuck in signed in state.

### ISSUE THREAD

**Issue by AungMoe** [aws-amplify/amplify-flutter#3683]
### Description

I tried to implement social sign in/out and it works fine on android devices. But for iOS it didn't, so I tried the workaround that I found here https://github.com/aws-amplify/amplify-swift/issues/634#issuecomment-774164469 which is to add the option parameter of private session. But it works if we sign in and sign out. But after sign in, if we close the app, we cannot sign in again. It says there is a user already signed in. Cannot sign out also, it goes back to that #634 problem. Tried re installing the app. Doesn't work. I cannot reset the devices as it is a real personal device as suggested here https://github.com/aws-amplify/amplify-flutter/issues/2645. What would be the solution to fix this issue?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Social sign
Close the app
Open the app

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

^0.6.12

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @AungMoe, sorry you are facing this issue.
> But after sign in, if we close the app, we cannot sign in again.

Can you help me understand what you are wanting to achieve? If a user is already signed in, why would you want to sign them in again?

> Cannot sign out also, it goes back to that https://github.com/aws-amplify/amplify-flutter/issues/634 problem.

Can you clarify what you mean here as well? Which issue do you face when trying to sign out? Is there an exception thrown or some other error message printed?

Would you be willing to provide the Flutter code you're calling to sign in the user?

**Comment by AungMoe** [comment]
So after closing and reopening the app, I was able to skip login screen again by fetching current session as token is still there. But when I would like to log out, it pops up a dialog ["My App Name" wants to use "amazoncognito.com" to Sign In] w/ cancel and continue button and cannot log out. 
![img_6583_720](https://github.com/aws-amplify/amplify-flutter/assets/5498755/18e9ab6f-3a1a-4bff-b62e-61bb913dde83)
![img_6585_720](https://github.com/aws-amplify/amplify-flutter/assets/5498755/32008838-6855-422a-a64b-ab8511e034b0)

**Comment by dnys1** [comment]
Thank you for the additional information. Have you added your custom scheme to the `Info.plist` file as described [here](https://docs.amplify.aws/lib-v1/auth/social/q/platform/flutter/#platform-setup)?

I noticed you're using v0 of the Amplify Flutter libraries. May I ask if there's anything in particular keeping you from upgrading to v1? We've fixed a lot of issues including this one in v1 and it's a lot easier for us to troubleshoot now.

**Comment by AungMoe** [comment]
Yes I did add the scheme into Info.plist and the reason for using v0 version is that our app is running on flutter 3.7 so previous devs used v0 to be compatible with the dart SDK version of that flutter. I am just adding this social sign in feature to our app and if I would like to update the auth, I will have to update all flutter, the other codes and plugins. So if you say it is fixed in v1, I think we will try transitioning into newer version and try again. Thanks for responding.

**Comment by dnys1** [comment]
Thanks @AungMoe, yes I believe this is resolved in v1. Let me know if you have any issues in the migration. We have a [migration guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/) available to help make the transition easier.

**Comment by AungMoe** [comment]
Thanks. As for now we are putting this task aside so I will check it out when we try again. I think you can close this issue now.

**Comment by dnys1** [comment]
Sounds good. Please feel free to re-open or create a new issue if you continue to experience this.
