### ISSUE TITLE
The output for "amplify init" has changed

### ISSUE THREAD

**Issue by Mike-and-Happy** [aws-amplify/amplify-flutter#3688]
### Description

In the Readme the output is shown below:

Project information
| Name: <project-name>
| Environment: dev
| Default editor: Visual Studio Code
| App type: flutter
| Configuration file location: ./lib/

In the console the output is the following:

? Enter a name for the project flutterapplication
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
android
ios
javascript
Please tell us about your project
? What javascript framework are you using 

How do I choose Flutter?
Where do I specify the Configuration file location?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Run "amplify init"

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.1

### Amplify Flutter Version

4.29.2

### Deployment Method

Amplify CLI

**Comment by DonMiller9294** [comment]
Hello what is your issue?

**Comment by Mike-and-Happy** [comment]
In the Readme the output includes
App type: flutter and Configuration file location: ./lib/

This is the output I see in the terminal
? Enter a name for the project flutterapplication
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building
android
ios
javascript

How do I specify that I am building a Flutter application and the location of the Configuration file?

**Comment by dnys1** [comment]
Hi @Mike-and-Happy, can you make sure you're on the latest version of `amplify` by running `npm install -g @aws-amplify/cli`. Afterwards, the output of calling `amplify --version` should `12.4.0`. Can you confirm that's the case?

**Comment by Mike-and-Happy** [comment]
Hello @dnys1 I was not running the latest version of amplify.  Thank you.

**Comment by Mike-and-Happy** [comment]
Hi @dnys1, any advice on what actions to take if `sudo npm install -g @aws-amplify/cli` does not update the Amplify version?
