### ISSUE TITLE
Error while configuring AmplifyPushNotificationsPinpoint plugin

### ISSUE THREAD

**Issue by szymondobrzanski** [aws-amplify/amplify-flutter#3690]
### Description

Hello, 
I'm experiencing error while adding _AmplifyPushNotificationsPinpoint_ plugin to configure Amplify in my app:
`flutter: An error occurred while configuring Amplify: PushNotificationException {
  "message": "Error occurred awaiting for device token to register device with Pinpoint",
  "recoverySuggestion": "Please review the underlying exception",
  "underlyingException": "UnknownException {\n  \"message\": \"The AWS credentials could not be retrieved\",\n  \"recoverySuggestion\": \"Invoke Amplify.Auth.signIn to re-authenticate the user\",\n  \"underlyingException\": \"NotAuthorizedException {\\n  message=Unauthenticated access is not supported for this identity pool.,\\n}\"\n}"
}`
Message is the same both on Android and iOS physical devices.

When I delete _AmplifyPushNotificationsPinpoint_ from list of plugins, configuration is successful. Error message indicates that I should login user beforehand plugin configuration but it's not possible as Auth won't be configured yet (and configuring push plugin shouldn't be based on auth state). I followed push notification documentation to configure everything: https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/flutter/. 

Here is my Amplify configuration code:
```
Future<void> main() async {
  await configureApp();
  runMain();
}

void runMain() {
  runApp(RestartApp(MyApp()));
}

Future<void> configureApp() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  const environment =
      String.fromEnvironment('ENVIRONMENT_F', defaultValue: Environment.prod);
  if (kDebugMode) {
    await firebaseCrashlyticsInstance.setCrashlyticsCollectionEnabled(false);
  }
  FlutterError.onError = (errorDetails) {
    firebaseCrashlyticsInstance.recordFlutterFatalError(errorDetails);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    firebaseCrashlyticsInstance.recordError(error, stack, fatal: true);
    return true;
  };
  await configureInjection(environment);
  try {
    if (Amplify.isConfigured) {
      safePrint('Amplify is already configured. Skipping configuration.');
    } else {
      final auth = AmplifyAuthCognito();
      final dataStorePlugin =
          AmplifyDataStore(modelProvider: ModelProvider.instance);
      final api = AmplifyAPI(modelProvider: ModelProvider.instance);
      final pushPlugin = AmplifyPushNotificationsPinpoint();
      await Amplify.addPlugins([dataStorePlugin, api, auth, pushPlugin]);
      await Amplify.configure(amplifyconfig);
    }
  } catch (e) {
    safePrint('An error occurred while configuring Amplify: $e');
    reportError(
        exception: 'Aws Amplify framework could not be initialised',
        reason: 'An error occurred while configuring Amplify: $e');
  }
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [x] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Setup Android and iOS push notifications as stated in https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/flutter/ and https://docs.amplify.aws/lib/push-notifications/setup-push-service/q/platform/flutter/
2. Run the app

### Screenshots

![Zrzut ekranu 2023-09-5 o 12 12 54](https://github.com/aws-amplify/amplify-flutter/assets/119587310/dfdd5060-8079-4717-acc1-266ff669516d)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.3.3

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @szymondobrzanski, sorry you are facing this issue. The error message `Unauthenticated access is not supported for this identity pool.` is saying that your identity pool does not allow retrieving credentials unless you're signed in. However, the push notifications plugin requires that this setting (unauthenticated access) be enabled in your backend.

In order to enable this, you'll need to run `amplify update auth`, then select `Walkthrough all the auth configurations`, followed by `User Sign-Up and Sign-In`, then make sure that unauthenticated access is enabled. The rest can remain unchanged from before. Then call `amplify push` to re-deploy your backend with the changes before running your Flutter app again. You should see this error message go away afterwards.
