### ISSUE TITLE
[URGENT] [CRITICAL] SessionExpiredException on iOS

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#370]
My iOS users cannot use my app due to SessionExpiredException. Some time after signIn sessions expires and users are getting SessionExpiredException when I try to get my AWS Credentials through 
`CognitoAuthSession cognitoAuthSession = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));`

Error:
SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)

Session should be refreshed and they should be able to retrieve their token using cognitoAuthSession.userPoolTokens.accessToken but is not being possible.

The fetchAuthSession method returns that user is signedIn when I call:
`CognitoAuthSession cognitoAuthSession = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: false));`

In this case, getAwsCredential is set to false.

Guys, this is a CRITICAL issue and I need a workaround for this asap.

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] iOS

I am using the latest release (0.0.2-dev.2).

**Comment by haverchuck** [comment]
@brunovsiqueira Did this only start happening with version upgrade?

**Comment by brunovsiqueira** [comment]
This is happening only in iOS (as soon as I know) and it was happening in the two last versions (the ones I tested). Both are not refreshing the session.

**Comment by haverchuck** [comment]
@brunovsiqueira Does the session refresh when you attempt to make any other Amplify API call?  Or are you using Auth only?

**Comment by haverchuck** [comment]
@brunovsiqueira Also - have you checked that the refresh tokens are not actually expired? In that scenario, prompting the user to sign in again would be the correct step.

**Comment by brunovsiqueira** [comment]
I am using Auth only.

How can I check this? I thought Amplify would handle refresh token for me and provide Credentials (JWT) always when I fetch session. This is not the expected behavior?

Signing out user and signing in again every time session expires (and it seems to expires very early) is not good in therms of experience.

**Comment by haverchuck** [comment]
Eventually, the refresh token will expire and Amplify will no longer be able to refresh the tokens, and the user will need to sign in again.  This depends on the configuration of your Cognito User Pool.  Access and ID tokens can be between 5 minutes and 1 day, while refresh tokens can be valid for 1 hour to approx. 10 years.  By looking at your Cognito User Pool App Client, can you tell whether perhaps the refresh tokens themselves have simply expired?

**Comment by haverchuck** [comment]
@brunovsiqueira You can find a good explanation w/ test steps [here](https://github.com/aws-amplify/amplify-ios/issues/1028#issuecomment-776121181).

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. Thanks for your explanation.
My refresh token expiration is set to 30 days. If the session is expired, why am I getting that user is signedIn when I try to fetch session without asking for credentials? In my opinion the behavior should be the same in both cases.

**Comment by haverchuck** [comment]
@brunovsiqueira That behavioral difference is awkward, you're correct.  That aside - are you able to resolve this issue by re-logging in the user?  Did you confirm that the refresh tokens were simply expiring?

**Comment by brunovsiqueira** [comment]
I am pretty sure that was the reason and I am logging out the user when session expires. If this problem happen again I let you guys know.

**Comment by haverchuck** [comment]
@brunovsiqueira I am closing this issue, but if you have continued problems please reach out.

**Comment by lentzou** [comment]
Hello guys,

What's up with this issue I still get 

Exception has occurred.
PlatformException (PlatformException(SessionExpiredException, Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: Please sign in and reattempt the operation., message: Your session has expired.}, null))

when I Amplify.Auth.fetchAuthSession after signOut or when I start the app.
