### ISSUE TITLE
Appstore reject because OAuth shows HostedUI

### ISSUE THREAD

**Issue by denxorz** [aws-amplify/amplify-flutter#3702]
### Description

I have followed the steps on https://docs.amplify.aws/lib/auth/social/q/platform/flutter/ to implement "Sign in with Apple" OAuth support for our Flutter app.

Apple just reviewed the app and rejected the Appstore publication. It seems this is because the "Sign in with Apple" shows some steps in the browser. See message below. 

Is it possible to merge the webbrowser steps into the app somehow?

```
Hello,

Thank you for providing this information.
Upon further review, we found that your submission does not comply with the following guidelines:

Guideline 4.0 - Design
We noticed that the user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.

Next Steps
To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.

You may also choose to implement the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

Resources
- For additional information on the Safari View Controller API, please review the [What’s New in Safari](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Introduction/Introduction.html) webpage.
- Note that apps that support account creation must also offer account deletion, per [App Store Review Guideline 5.1.1(v)](https://developer.apple.com/app-store/review/guidelines/#data-collection-and-storage). Learn more about [offering account deletion in your app](https://developer.apple.com/support/offering-account-deletion-in-your-app).

Best regards,
App Store Review
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Follow steps on https://docs.amplify.aws/lib/auth/social/q/platform/flutter/
2. Submit app for Appstore review 

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.1

### Amplify Flutter Version

1.4.0

### Deployment Method

Custom Pipeline

**Comment by dnys1** [comment]
Hi @denxorz, sorry you are facing this issue.

The Hosted UI implementation of Amplify Flutter uses Apple's recommended `ASWebAuthenticationSession` for displaying an in-app modal for login. I'm not sure why they are classifying this as a browser. Can you provide some more information to better understand the issue?

1. Are you only using Sign In With Apple or do you have other identity providers enabled?
2. Can you provide a screen recording or screenshots showing the sign-in process?

Apologies again and thanks for bringing this to our attention.

**Comment by DennisNurtio** [comment]
Hello @dnys1 , I will try to get more info from Apple and will update the issue. 
Dennis

**Comment by denxorz** [comment]
Hello @dnys1 , I will try to get more info from Apple and will update the issue.
Dennis

**Comment by denxorz** [comment]
Hello @dnys1, after investigation it seems that an old version was somehow submitted into Apple review. So this rejection is not based on the current version of the Amplify plugin. I am closing the issue.

Apologies for the inconvenience.
