### ISSUE TITLE
Amplify is down

### ISSUE THREAD

**Issue by codesculpture** [aws-amplify/amplify-flutter#3704]
Hey suddenly, one backend environment(prod) is down and every network calls from client throwing 401 error. Other dev environment is working fine... And amplify studio is also accessible for prod environment. The client is here is mobile app which built using flutter. Please anyone can help

**Comment by dgagnon** [comment]
@codesculpture We have had something similar happen, did you update your environment recently? Check the settings on your cognito pool and compare it with the dev env.  Somehow, our app configs were gone.  Re-adding them manually fixed it for us.

**Comment by codesculpture** [comment]
> @codesculpture We have had something similar happen, did you update your environment recently? Check the settings on your cognito pool and compare it with the dev env.  Somehow, our app configs were gone.  Re-adding them manually fixed it for us.

The prod env were not touched since long time. But we did some change in dev env recently, does that can be a problem?

**Comment by dgagnon** [comment]
@codesculpture you can check the drift status of your cloudformation stacks as well in order to see if any changes happened.

**Comment by codesculpture** [comment]
@dgagnon actually, no changes. And also the prod env not deployed since last month. And app was built with same configs and had some updates frequently (every week). We releazed an update last week. But it worked fine for till yesterday. Suddenly it stopped working

**Comment by codesculpture** [comment]
Btw, we had a payment overdue and paid yesterday. We actually thought aws suspeneded our whole service since we dint paid. But after clearing all due, we had a call with aws supoort team and they actually said that we dont have any suspension before..

**Comment by codesculpture** [comment]
Hey man, just now i forced to make deploy and app working fine even in the release build (which was build from the previous deployment).

**Comment by codesculpture** [comment]
I totally dont understand why this happened and how its solved when i redeployed forcefully.. and the release apk version of my app which was builded using the previous deployment is kinda working.. somehow... Can anyone tell why this happened ... This is a serious issue

**Comment by codesculpture** [comment]
Btw, thanks for helping me man. I dont really understand how this happened.

**Comment by dnys1** [comment]
Hi @codesculpture, sorry you faced this issue. Can you confirm it is resolved for you?

**Comment by codesculpture** [comment]
Yeah it was solved now, but i dont really like to expect this behavior in future

**Comment by dnys1** [comment]
It sounds like there may have been a billing issue. Unfortunately, I don't have any more knowledge I can provide on this issue. 

Closing for now, but please feel free to create a new issue if you experience this again going forward.
