### ISSUE TITLE
codeDeliveryDetails is null when email based user registration

### ISSUE THREAD

**Issue by salihgueler** [aws-amplify/amplify-flutter#3707]
### Description

When users manually configure the authentication settings, if they disable the email based user registration, the code delivery details return null. 

Also, the CLI does not allow me to select TOTP or SMS for the account verification. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Initialize Amplify project
2. Add authentication with CLI
3. Select Manual Configuration
4. Disable the email registration/forgot password
5. Register a user
6. Try to verify it

Actual:
User does not receive a code to verify to user, code delivery result is null

Expected:
User receives a code and resource is defined

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.13.3

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Can you share the input/output from the CLI when creating a backend to reproduce this?

**Comment by Jordan-Nelson** [comment]
Discussed with @salihgueler offline. We will close this out and re-open when we have more info / repro steps. If anyone else is experiencing this issue, please let us know and we can investigate.
