### ISSUE TITLE
GraphQLResponse lost response headers 

### ISSUE THREAD

**Issue by ainomegumi-desu** [aws-amplify/amplify-flutter#3709]
### Description

After i send graphql request

```
    final opeartion = Amplify.API.query(request: request);
    final response = await opeartion.response;
```
it seems nowhere i can get the response header, cuase the header are lost durating construct GraphQLOperation in the source code

```
  return GraphQLOperation(
    graphQLOperation.operation.then(
      (response) async {
        final responseJson = await response.decodeBody();
        // safePrint(response.headers);
        final responseBody = json.decode(responseJson);

        if (responseBody is! Map<String, dynamic>) {
          throw UnknownException(
            'unable to parse GraphQLResponse from server response which was '
            'not a JSON object: $responseJson',
          );
        }

        return GraphQLResponseDecoder.instance.decode<T>(
          request: request,
          response: responseBody,
        );
      },
      onError: (errr, stackTrace) {
        Error.throwWithStackTrace(
          UnknownException(
            'unable to send GraphQLRequest to client.',
            underlyingException: error,
          ),
          stackTrace,
        );
      },
    ),
  );
}
```

Am i missing something here ? Thanks In Advance

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.3.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @ainomegumi-desu, which headers are you looking to retrieve?

**Comment by ainomegumi-desu** [comment]
> Hi @ainomegumi-desu, which headers are you looking to retrieve? You're correct that we do not currently provide a way to access them.

Tks for investigating, just some custom headers for debug purpose : ) Feel free to close the issue if you need

**Comment by dnys1** [comment]
Thanks, @ainomegumi-desu. For debugging, check out the Network Inspector in DevTools which will show you the full HTTP requests and responses including headers: https://docs.flutter.dev/tools/devtools/network
