### ISSUE TITLE
[Feature Request] amplify_auth_cognito supporting Android API 23 (Android 6) in 1.x.x

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#3739]
We are using Amplify Auth in our App that supports API 23 (minSdkVersion 23). We do need to support this API, because we have ~800 MAU using Android 6 (API 23) devices. We wish to migrate to the 1.x.x version that is being supported and being evolved, but we can't due to this incompatibility (amplify_auth requires minSdkVersion 24). We also have some important bugs (e.g.: https://github.com/aws-amplify/amplify-flutter/issues/1271) with earlier versions (<1.x.x).

Our App is importing this amplify deps: 
```
amplify_auth_cognito
amplify_core
amplify_flutter
```

Is there any reason for not supporting API 23? Would be possible to downgrade minSdkVersion to 23 for the Auth category?

Additionally, the need to support Amplify versions earlier than 1.0.0 has become a significant challenge due to its dependency on aws_common, which relies on http version 0.13.4. Consequently, we are unable to update any dependencies that have moved to http version 1.x.x. (dio for example).

**Comment by brunovsiqueira** [comment]
Here is the error I get When trying to run new versions of amplify auth within our project:

uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [:amplify_auth_cognito] /Users/vianabr/AndroidStudioProjects/BTGMaisBusiness/build/amplify_auth_cognito/intermediates/merged_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 23 Suggestion: use a compatible library with a minSdk of at most 23, or increase this project's minSdk version to at least 24, or use tools:overrideLibrary="com.amazonaws.amplify.amplify_auth_cognito" to force usage (may lead to runtime failures)

The PR would be only downgrading minSdkVersion of amplify_auth_cognito? If so, I can help you guys by opening it.

**Comment by Jordan-Nelson** [comment]
Hi @brunovsiqueira - You should have access to create a PR from a fork.

Along with the API level change, we will want to update our test suite to run against the new min API level (currently the suite runs against API levels 24 and 33), and then resolve and issue in API level 23 (if any surface). The updates to the test suite aren't super straight forward since our entire test suite currently uses the same min/max API levels. We will have to change this to allow for different API levels per package.

**Comment by brunovsiqueira** [comment]
Hi @Jordan-Nelson . I have just opened the PR: https://github.com/aws-amplify/amplify-flutter/pull/3743. Do you have any timeline for the test suite update?

**Comment by Jordan-Nelson** [comment]
@brunovsiqueira - Apologies for the delay on this. Is this still something you are interested in?

**Comment by Jordan-Nelson** [comment]
If anyone is still looking for support for Android 23 in Amplify Flutter v1, please let us know. Thank you.

**Comment by brunovsiqueira** [comment]
Hi @Jordan-Nelson. Sorry for the late reply. I left my previous company that used Amplify. Thank you.

**Comment by Jordan-Nelson** [comment]
Thanks for the update @brunovsiqueira.

If anyone else is still looking for support for API level 23 please let us know. Otherwise we will close out this request.

**Comment by Jordan-Nelson** [comment]
Closing this out since there does not seem to be interest in this request.
