### ISSUE TITLE
Amplify.Storage.getUrl doesn't allow for protected access level

### ISSUE THREAD

**Issue by 94Sip** [aws-amplify/amplify-flutter#3765]
**Describe the bug**
The S3GetUrlPluginOptions as a part of the getUrl function doesn't allow for the identityid of the user who uploaded the file, hence you cannot get a presigned url of a protected file.

**To Reproduce**
try to use the getUrl function to get a presigned url for a protected access file.

**Expected behavior**
The ability to provide the identityId of the user who uploaded the file.

**Additional context**
I'm using the latest version of Amplify libraries for Flutter.

**Comment by reesscot** [comment]
Transferring to Flutter team, as this is a library feature request

**Comment by fjnoyp** [comment]
Hi @94Sip thanks for sharing your issue. 

`S3GetUrlPluginOptions` allows you to pass in an identity id via:

```
S3GetUrlPluginOptions.forIdentity("targetIdentityId"); 
```

This is consistent with other S3 PluginOptions as described in the documentation here: 

https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/#protected-access

Does that address your question?  Or are you having issues getting the proper identityId for accessing another users's protected data?

**Comment by fjnoyp** [comment]
@94Sip if this resolves your issue please let us know, we'll mark it as pending close now.  Thank!

**Comment by Jordan-Nelson** [comment]
@94Sip - I am going to close this issue out since we have not heard back. Please let us know if you are still facing this issue.
