### ISSUE TITLE
Default bucket empty in amplifyconfig file append . in url

### ISSUE THREAD

**Issue by Nikhil-wrench** [aws-amplify/amplify-flutter#3783]
### Description

    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "",
                "region": ""
            }
        }
    }

in  amplifyconfiguration.dart file id bucket is empty, it will create url like "https://.s3..amazonaws.com/...".
there is extra "." before s3

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Screenshots

<img width="880" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/123051037/95b7bf48-f8d3-463a-b30e-1cdf2e5c7e4a">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @Nikhil-wrench you will need to set the bucket in your `amplifyconfiguration.dart` file.  If you have a pre-existing S3 bucket you can use that or you can follow the instructions here on having amplify cli create the S3 backend for you: https://docs.amplify.aws/lib/storage/getting-started/q/platform/flutter/

It is currently not possible to use the Amplify Storage without a S3 bucket being set in the `amplifyconfiguration.dart` file.  We are considering possible future support for having multiple S3 bucket.  

Hope that helped clarify for you!
