### ISSUE TITLE
Unable to configure FCM Push Notifications with server key

### ISSUE THREAD

**Issue by 94Sip** [aws-amplify/amplify-flutter#3789]
### Description

I am trying to enable FCM for Android push notifications. I already have a PinPoint project ("existing resources") with APNs already enabled.

I have followed the instructions in the docs (https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/flutter/) for Android and am trying to enable FCM via the Pinpoint portal. So I have already gone to the Firebase portal and enabled the "legacy" mode and it has given me a Server Key, which I have copied to the clipboard.

Now when I go to the Pinpoint portal and try to enable FCM and paste in the Server Key, when I click the "Save button", it shows "Validating" with a progress indicator, and then stops without saving anything.

I'm going to the portal as I assume I should NOT use the CLI since I already have a Pinpoint project in place. If this is incorrect, please advise otherwise.

So is this a bug with Pinpoint? Or will it not work because of the deprecated nature of the FCM messaging format that the Amplify documents specify? I don't get any error message anywhere on the screen, or in CloudWatch, etc.

Not quite sure where to raise this issue, so if I need to direct this elsewhere, please say so.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.5

### Amplify Flutter Version

1.4.x

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @94Sip thanks for sharing this issue.  To confirm, is this the screen that is screening at validating when adding the FCM key?

![image](https://github.com/aws-amplify/amplify-flutter/assets/11478656/9f172bd7-6ae7-40b8-a7b3-22c95710dc92)

**Comment by 94Sip** [comment]
yes, but I don't get any red banner at the top. When I click on the Save button, the button becomes disabled, and the button text shows "Validating" with a progress indicator, and then goes back to Save (and is enabled again). So it's clearly not Saving, but not giving me any error.

**Comment by fjnoyp** [comment]
Hmm that's strange.  I'm unable to replicate.  

I get the server key specified here: 

![image](https://github.com/aws-amplify/amplify-flutter/assets/11478656/93fe9de2-2232-4dba-af04-bba8b5f982dd)

And then add it to Pinpoint as a Key Credential and save with no problems. 

As a test can you try creating a new Firebase project and adding its server key to your pinpoint project?  We'll reach out to Pinpoint team to see if they can clarify as well.

**Comment by 94Sip** [comment]
Nope, same thing. Could it be because I have already enabled APNs and am using that currently for Apple devices?

**Comment by fjnoyp** [comment]
@94Sip unsure, what region are you using?

**Comment by 94Sip** [comment]
> @94Sip unsure, what region are you using?

Pinpoint in Virginia

**Comment by 94Sip** [comment]
Hi @fjnoyp - any update here?

**Comment by fjnoyp** [comment]
Hi @94Sip no updates sorry still investigating and waiting on Pinpoint team response.  Have you tried configuring FCM anytime since then?

**Comment by 94Sip** [comment]
Yes I have tried multiple times, with a brand a new app (in Firebase) and still the same thing.

**Comment by 94Sip** [comment]
@fjnoyp as an fyi, I created a FCM Token file (JSON file) and tried to upload that to Pinpoint to configure FCM (in the pinpoint console) and it did the same thing - the label on the button disabled for a second or two and showed "Validating" and then it reverted back to enabled behavior. 

So it appears to be a problem with Pinpoint console, regardless of whether I choose SErver Key or Token file.

Have you been able to ascertain anything from the Pinpoint team?

Should I revert to using FCM directly, instead of using Pinpoint? The key driver for me is that I have a lambda function that sends push notifications each night and its very easy to use Pinpoint to get endpoints and associate with users, which then allows me to not worry with APNs or FCM individually.

**Comment by Jordan-Nelson** [comment]
Hello @94Sip - Sorry for the delay in a response. I have reached out to the pinpoint team to see if they have any suggestions. In the meantime, do you see any errors in your browsers dev tools if you open up the network tab? There should be requests made when you tap save. Are those returning any errors?

**Comment by 94Sip** [comment]
Hi Jordan, fwiw, I tried again about a month ago and it worked. So I guess
whatever was a problem, got fixed. It worked exactly like the instructions
said.

**Comment by Jordan-Nelson** [comment]
Okay thanks. I am going to close out this issue then. If this reoccurs the next step would be to open a support ticket so that the Pinpoint team can look into it.
