### ISSUE TITLE
Remove ios social sign in pop up

### ISSUE THREAD

**Issue by rmargolinross** [aws-amplify/amplify-flutter#379]
**Describe the bug**
Currently if you set up social sign in through amplify on flutter, on ios devices you get the pop up requesting to give amazoncognito.com permission. This happens on sign in and sign out. This should be fixed. 

**To Reproduce**
1. Set up social sign in
2. Run it on an ios device

**Expected behavior**
Sign in works without any extra pop ups and sign out should not require any browser

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[*] iOS

**Additional context**
It seems this issue was solved in Amplify-ios with https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0
The issue on that side is located here: https://github.com/aws-amplify/amplify-ios/issues/745

**Comment by rmargolinross** [comment]
Any word on this? I feel like this is a big blocker as right now it is causing the user to see a pop up that is asking amazoncognito for permissions, which I imagine most users will ignore

**Comment by bwhiteTP** [comment]
@haverchuck any update on this?

**Comment by dnys1** [comment]
This functionality is available on iOS as of version 0.2.5 using the [`isPreferPrivateSession`](https://pub.dev/documentation/amplify_auth_cognito/latest/amplify_auth_cognito/CognitoSignInWithWebUIOptions/isPreferPrivateSession.html) option on `CognitoSignInWithWebUIOptions`. Note that this comes at the expense of using a private browsing session, which means credentials available in the user's browser will not be available to your application.
