### ISSUE TITLE
Unhandled Exception: AmplifyAlreadyConfiguredException(message: Amplify has already been configured., recoverySuggestion: Remove the duplicate call to `Amplify.configure()`, underlyingException: null)

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#380]
Using the latest version and getting AmplifyAlreadyConfiguredException. I am calling Amplify.configure and trying to handle the exception by catching it, but it seems not to work.

Amplify.addPlugin(AmplifyAuthCognito());
  try {
    Amplify.configure(amplifyConfig);
  } on AmplifyAlreadyConfiguredException catch(e) {
    print(e);
  }

Should I do something different?

**Comment by Amplifiyer** [comment]
@brunovsiqueira, can you put await on the `Amplify.configure(amplifyConfig);` and see if that helps?

**Comment by brunovsiqueira** [comment]
@Amplifiyer It seems to solve the issue. Thanks for your quick response.

**Comment by 12ajayvishwa** [comment]
Using the latest version and getting AmplifyAlreadyConfiguredException. I am calling Amplify.configure and trying to handle the exception by catching it, but it seems not to work.

void _amplifyConfigure() async {
    AmplifyAuthCognito auth = AmplifyAuthCognito();
  
    Amplify.addPlugins([auth]);
    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      print(
          "Amplify was already configured. Looks like app restarted on android.");
    }

    setState(() {
      _isAmplifyConfigured = true;
    });
  }

**Comment by brunovsiqueira** [comment]
@12ajayvishwa is correct. At least in iOS, AmplifyAlreadyConfiguredException is coming as generic AmplifyException. I think it should be reopened because it has not been properly fixed @Amplifiyer. 

In my opinion we should have a amplifyAlreadyConfigured flag to be checked before calling configure method.

**Comment by 12ajayvishwa** [comment]
yup

**Comment by Amplifiyer** [comment]
@brunovsiqueira we will track the issue for flag here https://github.com/aws-amplify/amplify-flutter/issues/412
