### ISSUE TITLE
Trim Username/Email fields before validation

### ISSUE THREAD

**Issue by denxorz** [aws-amplify/amplify-flutter#3805]
### Description

When our users fill the email and username field (automatically) they might leave a space at the end of a field. This now leads to the error "Invalid email format" or "Username must only contain alphanumeric characters and symbols". This confuses our users.

It would be nice to trim the fields before running the validation.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Enter "username " in a username field
2. Try to login

or

1. Enter "email@test.com " in an email field
2. Try to sign up

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.13.1

### Amplify Flutter Version

1.4.0

### Deployment Method

Custom Pipeline

**Comment by khatruong2009** [comment]
The fix for this was included in v1.6.0. Please let us know if you face any other issues.
