### ISSUE TITLE
Amplify datastore not dispatching ready

### ISSUE THREAD

**Issue by stephenjen** [aws-amplify/amplify-flutter#3812]
### Description

I’m unable to get DataStore to dispatch ready.  After synching all models from the cloud, it stops after dispatching syncQueriesReady and never gets to dispatching ready.

This happened once before when I had corrupted data in the cloud which prevented sync reaching ready, but this time I’ve already deleted all data in all models in the cloud through Amplify Studio.

After deleting all data, I manually added one record in one model to see if anything is downloading to app, and it is downloading this one record.  But if Amplify.Hub.listen does not detect a dispatched ready, then no local changes are synched to the cloud. 

I’ve recently updated Amplify from version 0.6 to 1.4, and Flutter to 3.13.5 stable, not sure if these updates caused this issue or not.  

My Flutter Doctor info:

    [✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
        • Flutter version 3.13.5 on channel stable at /Users/stephen/developer/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
        • Engine revision bd986c5ed2
        • Dart version 3.1.2
        • DevTools version 2.25.0
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
        • Android SDK at /Users/stephen/Library/Android/sdk
        • Platform android-33, build-tools 32.0.0
        • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
        • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 15.0)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Build 15A240d
        • CocoaPods version 1.13.0
    
    [✓] Android Studio (version 2021.2)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    
    [✓] VS Code (version 1.74.0)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension can be installed from:
          🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    
    [✓] Connected device (2 available)
        • iPhone 15 Pro Max (mobile)
        • 3742B3F5-F361-412A-937A-CE78A2F18878
        • ios • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
        • macOS (desktop)            
        • macos                                
        • darwin-arm64 • macOS 13.5.2 22G91 darwin-arm64
    
    [✓] Network resources
        • All expected network resources are available.

Relavent pubspect.yaml info:

      amplify_flutter: ^1.0.0
      amplify_datastore: ^1.0.0
      amplify_auth_cognito: ^1.0.0
      amplify_authenticator: ^1.0.0
      amplify_api: ^1.0.0
      amplify_storage_s3: ^1.0.0
      uuid: ^3.0.7

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.5

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Tag @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String! @index(name: "byName")
  scheduledBlocks: [ScheduledBlock] @manyToMany(relationName: "ScheduledBlockTag")
  trayBlocks: [TrayBlock] @manyToMany(relationName: "TrayBlockTag")
  seriess: [Series] @manyToMany(relationName: "SeriesTag")
  metrics: [Metric] @manyToMany(relationName: "MetricTag")
  userStatsPerformanceModeMetricsAdherence: [UserStatsPerformanceModeMetricsAdherence] @hasMany(indexName: "byTag", fields: ["id"])
}

type ScheduledBlock @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  title: String!
  startTime: AWSDateTime!
  endTime: AWSDateTime!
  duration: Float
  tags: [Tag] @manyToMany(relationName: "ScheduledBlockTag")
  activities: [Activity] @hasMany(indexName: "byScheduledBlock", fields: ["id"])
  trayBlockID: ID! @index(name: "byTrayBlock", sortKeyFields: ["title"])
  trayBlock: TrayBlock! @belongsTo(fields: ["trayBlockID"])
  pOwner: String
}

type Metric @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String!
  duration: Int!
  priority: Int!
  operationModeID: ID! @index(name: "byOperationMode", sortKeyFields: ["title"])
  operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
  tags: [Tag] @manyToMany(relationName: "MetricTag")
}

type UserOperationMode @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  date: AWSDateTime!
  operationModeID: ID! @index(name: "byOperationModeUserOperationMode", sortKeyFields: ["date"])
  operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
  pOwner: String!
  test: String
}

type Settings @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  name: String!
  value: String!
  pOwner: String!
}

type OperationMode @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String!
  shortDescription: String
  description: String!
  longDescription: String
  featured: Boolean!
  featuredPriority: Int!
  category: String!
  categoryPriority: Int!
  metric: [Metric] @hasMany(indexName: "byOperationMode", fields: ["id"])
  userOperationMode: [UserOperationMode] @hasMany(indexName: "byOperationModeUserOperationMode", fields: ["id"])
  series: [Series] @hasMany(indexName: "bySeries", fields: ["id"])
  trayBlocks: [TrayBlock] @manyToMany(relationName: "OperationModeTrayBlock")
  profileImage: String
  authorID: ID @index(name: "byAuthor", sortKeyFields: ["title"])
  author: Author @belongsTo(fields: ["authorID"])
  activities: [Activity] @hasMany(indexName: "byOperationMode", fields: ["id"])
  stats: [UserStatsOperationMode] @hasMany(indexName: "byOperationMode", fields: ["id"])
}

type Author @model @auth(rules: [{allow: private}]) {
  id: ID!
  fname: String!
  lname: String!
  mname: String
  description: String
  profileImage: String
  operationModes: [OperationMode] @hasMany(indexName: "byAuthor", fields: ["id"])
  testtest: String
}

type Series @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String!
  description: String!
  tags: [Tag] @manyToMany(relationName: "SeriesTag")
  operationModeID: ID! @index(name: "bySeries", sortKeyFields: ["title"])
  operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
  trayBlocks: [SeriesTrayBlock] @hasMany(indexName: "bySeriesSeriesTrayBlockA", fields: ["id"])
  activities: [Activity] @hasMany(indexName: "bySeriesActivity", fields: ["id"])
}

type TrayBlock @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String!
  description: String!
  longDescription: String
  duration: Int!
  tags: [Tag] @manyToMany(relationName: "TrayBlockTag")
  seriess: [SeriesTrayBlock] @hasMany(indexName: "byTrayBlockSeriesA", fields: ["id"])
  operationModes: [OperationMode] @manyToMany(relationName: "OperationModeTrayBlock")
  scheduledBlocks: [ScheduledBlock] @hasMany(indexName: "byTrayBlock", fields: ["id"])
}

type SeriesTrayBlock @model @auth(rules: [{allow: private}]) {
  id: ID!
  sequence: Int
  seriesID: ID! @index(name: "bySeriesSeriesTrayBlockA", sortKeyFields:["id"])
  trayBlockID: ID! @index(name: "byTrayBlockSeriesA", sortKeyFields:["id"])
  series: Series @belongsTo(fields: ["seriesID"])
  trayBlock: TrayBlock @belongsTo(fields: ["trayBlockID"])
}

type Friend @model @auth(rules: [{ allow: owner, ownerField: "pOwner"  }{ allow: private, operations: [read] }]) {
  id: ID!
  profileID: ID @index(name: "byProfile", sortKeyFields: ["id"]) # had to remove the ! here for activity to work
  profile: Profile @belongsTo(fields: ["profileID"]) # had to remove the ! here for activity to work
  activities: [Activity] @hasMany(indexName: "byFriend", fields: ["id"])
  pOwner: String!
}
enum ActivityAction {
  STARTEDSCHEDULING
  ADDEDFRIEND
  CHANGEDOPERATIONMODE
  COMPLETIONPROGRESS
  USEDSERIES
  ACHIEVEDGOALS
  ALMOSTACHEIVEDGOALS
  UPLOADEDIMAGE
  MODIFIEDSCHEDULE
  MODIFIEDSCHEDULEMAJOR
  LIKEDACTIVITY
  LIKEDSERIES
  LIKEDBLOCK
  LIKEDACHIEVEDGOALS
  LIKEDCOMMENT
  LIKEDUPLOAD
  COMMENTEDACTIVITY
  COMMENTEDSERIES
  COMMENTEDBLOCK
  COMMENTEDACHEIVEDGOALS
  COMMENTEDALMOSTACHEIVEDGOALS
}

type Activity @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
  id: ID!
  date: AWSDateTime!
  action: ActivityAction!
  friendID: ID! @index(name: "byFriend", sortKeyFields: ["date"])
  friend: Friend! @belongsTo(fields: ["friendID"])
  scheduledBlockID: ID @index(name: "byScheduledBlock", sortKeyFields: ["date"])
  scheduledBlock: ScheduledBlock @belongsTo(fields: ["scheduledBlockID"])
  operationModeID: ID @index(name: "byOperationMode", sortKeyFields: ["date"])
  operationMode: OperationMode @belongsTo(fields: ["operationModeID"])
  likes: [Like] @hasMany(indexName: "byActivity", fields: ["id"])
  comments: [Comment] @hasMany(indexName: "byActivity", fields: ["id"])
  seriesID: ID @index(name: "bySeriesActivity", sortKeyFields: ["date"])
  series: Series @belongsTo(fields: ["seriesID"])
  pOwnerProfileID: ID @index(name: "activitiesByProfile", sortKeyFields: ["date"])
  pOwnerProfile: Profile @belongsTo(fields: ["pOwnerProfileID"])
  completionPercentages: AWSJSON
  pOwner: String!
}

type Like @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
  id: ID!
  activityID: ID! @index(name: "byActivity", sortKeyFields: ["id"])
  activity: Activity! @belongsTo(fields: ["activityID"])
  content: String
  pOwner: String!
}

type Comment @model @auth(rules: [{ allow: private, ownerField: "pOwner" }]) {
  id: ID!
  activityID: ID! @index(name: "byActivity", sortKeyFields: ["id"])
  activity: Activity! @belongsTo(fields: ["activityID"])
  content: String!
  pOwner: String!
}
type Profile @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  userName: String
  fname: String
  lname: String
  profileImage: String
  remoteImageURL: String
  bio: String
  pOwner: String!
  friends: [Friend] @hasMany(indexName: "byProfile", fields: ["id"])
  activities: [Activity] @hasMany(indexName: "activitiesByProfile", fields: ["id"])
  onboarded: Boolean
}

type UserStatsPerformanceModeCategoriesUsed @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  pOwner: String!
  lastUpdated: AWSDateTime!
  year: Int!
  category: String!
  m1: Int
  m2: Int
  m3: Int
  m4: Int
  m5: Int
  m6: Int
  m7: Int
  m8: Int
  m9: Int
  m10: Int
  m11: Int
  m12: Int
}

type UserStatsDaysScheduled @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  pOwner: String!
  year: Int!
  lastUpdated: AWSDateTime!
  m1: Int
  m2: Int
  m3: Int
  m4: Int
  m5: Int
  m6: Int
  m7: Int
  m8: Int
  m9: Int
  m10: Int
  m11: Int
  m12: Int
  weeklyStats: String
}

type UserStatsOperationMode @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  pOwner: String!
  operationModeID: ID! @index(name: "byOperationMode", sortKeyFields: ["lastUpdated"])
  operationMode: OperationMode! @belongsTo(fields: ["operationModeID"])
  lastUpdated: AWSDateTime!
  year: Int
  m1: Int
  m2: Int
  m3: Int
  m4: Int
  m5: Int
  m6: Int
  m7: Int
  m8: Int
  m9: Int
  m10: Int
  m11: Int
  m12: Int
}

type UserStatsStreaks @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  pOwner: String!
  year: Int!
  lastScheduledDayOverall: AWSDateTime
  m1CountOverall: Int
  m2CountOverall: Int
  m3CountOverall: Int
  m4CountOverall: Int
  m5CountOverall: Int
  m6CountOverall: Int
  m7CountOverall: Int
  m8CountOverall: Int
  m9CountOverall: Int
  m10CountOverall: Int
  m11CountOverall: Int
  m12CountOverall: Int
  m1LongestStreakOverall: Int
  m2LongestStreakOverall: Int
  m3LongestStreakOverall: Int
  m4LongestStreakOverall: Int
  m5LongestStreakOverall: Int
  m6LongestStreakOverall: Int
  m7LongestStreakOverall: Int
  m8LongestStreakOverall: Int
  m9LongestStreakOverall: Int
  m10LongestStreakOverall: Int
  m11LongestStreakOverall: Int
  m12LongestStreakOverall: Int
}


type UserStatsPerformanceModeMetricsAdherence @model @auth(rules: [{ allow: owner, ownerField: "pOwner" }{ allow: private, operations: [read] }]) {
  id: ID!
  pOwner: String!
  year: Int!
  tagID: ID! @index(name: "byTag", sortKeyFields: ["year"])
  tag: Tag! @belongsTo(fields: ["tagID"])
  m1MetricQuota: Int
  m1MetricScheduled: Int
  m2MetricQuota: Int
  m2MetricScheduled: Int
  m3MetricQuota: Int
  m3MetricScheduled: Int
  m4MetricQuota: Int
  m4MetricScheduled: Int
  m5MetricQuota: Int
  m5MetricScheduled: Int
  m6MetricQuota: Int
  m6MetricScheduled: Int
  m7MetricQuota: Int
  m7MetricScheduled: Int
  m8MetricQuota: Int
  m8MetricScheduled: Int
  m9MetricQuota: Int
  m9MetricScheduled: Int
  m10MetricQuota: Int
  m10MetricScheduled: Int
  m11MetricQuota: Int
  m11MetricScheduled: Int
  m12MetricQuota: Int
  m12MetricScheduled: Int
}
```

**Comment by stephenjen** [comment]
By trial and error I discovered the issue had to do with these two tables: ScheduledBlock and OperationMode, specifically, some of the @hasMany directives on these tables.

Sync completes properly when I commented out trayBlock and trayBlockID from ScheduledBlock, and userOperationMode, trayBlocks and stats from OperationMode.  Then I realized that the I had to remove the required ! from the child of the above fields and everything went through and synced properly.  

What might be the reason for this?

**Comment by stephenjen** [comment]
After 2 weeks of successful syncing, this issue occurred again today where I noticed the app stopped syncing with the cloud after only reaching "sync is done".  I then went through Amplify Studio and deleted all records of models one model at a time, still sync never reached “datastore is ready” status.  Then I went through AWS DynamoDB and deleted all records from all models again, even though all records already had _deleted set to true.  Then tried again, and sync completed to “datastore is ready” status.  

I then ran code to generate data and everything went through and now syncs.

Hope this sheds additional light on this issue.

**Comment by Jordan-Nelson** [comment]
Hi @stephenjen - It sounds like this issue has occurred three times in total. The first time seemed to be the result of corrupted data and you were able to resolve it. The second occurrence was shortly before you opened this issue. The third occurrence was just recently and you were able to resolve it by deleting all the record in Dynamo. Is that correct?

How were you able to resolve the issue during the second occurrence?

Have there been changes to your schema? Are you saving data to Dynamo directly (not through App Sync / Amplify)?

When this occurs can you run the app from Xcode? You will likely see additional logs coming from native iOS code. Can you please share those logs?

**Comment by stephenjen** [comment]
Hi @Jordan-Nelson, the second time, through trial and error, I realized changing some of the relationship fields from required to not required resolved the problem and sync completes properly.  This worked for 2 weeks, and yesterday it stopped working.  There has not been any schema changes.

The next time this occurs I'll  make sure to look at Xcode.  But as far as I recall there are no errors, at least in Android Studio, and the app is able to run, just no data.

**Comment by stephenjen** [comment]
One thing I just remembered - I did create data directly through Amplify Studio a couple times, but after which all created data were immediately utilized in app without issues, but still, not sure if this caused hiccups.  But I will make sure to only create data through the app in the future.

**Comment by khatruong2009** [comment]
Hi @stephenjen, did you end up running into any issues after only creating data through the app? Is the solution where you changed the relationship fields from required to not required still working?

**Comment by stephenjen** [comment]
Hi @khatruong2009 Yes - only creating data through the app and changing relationships from required to optional seems to be holding.  My guess is this is what happened to me:

1. Not all required relationships were created when I used Amplify Studio to create data.  I don't know how this could have been since these manually created data worked properly in the app, but maybe I missed a failed test somewhere.
2. Problematic records do not show in Studio but do show in the older admin portal.  So at a quick glance all might seem to have been properly deleted from Studio, in reality these problematic records might still exist and are only viewable through the older portal.  The existence of problematic records seem to break sync.

**Comment by khatruong2009** [comment]
Hi @stephenjen, I'm going to close this issue since you are no longer experiencing this problem and make a note of those two points, thank you.
