### ISSUE TITLE
PlatformException Translating platform exception failed.

### ISSUE THREAD

**Issue by euriasb** [aws-amplify/amplify-flutter#385]
**Describe the bug**
A PlatformException is thrown because SignedOutException cannot be translated

Message:

PlatformException (PlatformException(SignedOutException, Translating platform exception failed. Please take a look at https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't., {message: There is no user signed in to retreive user sub, recoverySuggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession}, null))

**To Reproduce**
Should happen with any AuthException, but this happen particularly when I tried to fetch a user session when there was no user signed in, I was catching an AuthException for this case to proceed to the login flow.

**Expected behavior**
A SignedOutException should've been thrown.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android - Didn't test
[X] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max Simulator
 - OS: iOS 14.4
 - Version: Amplify v0.0.2-dev.2

**Comment by Amplifiyer** [comment]
@euriasb can you confirm that you are awaiting on the Auth category API calls in your try catch? Can you post your code snippet here.

**Comment by euriasb** [comment]
Yes I am, here is the snippet:

```
    try {
      CognitoAuthSession session = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
      _accessToken = session.userPoolTokens.accessToken;
      AuthState state = AuthState(authFlowStatus: AuthFlowStatus.session);
      authStateController.add(state);
    } on AuthException catch (_) {
      showLogin();
    }
```

**Comment by haverchuck** [comment]
@euriasb What is your cognito configuration? Are you using a userpool + identity pool, and if so, are you allowing unauthenticated access?  Or are you using a userpool only?

**Comment by euriasb** [comment]
UserPool only, no unauthenticated access.

But for some reason the problem seems to have gone away, I was having other issues so I did a flutter clean, restarted VS Code and now it is working as expected.

**Comment by haverchuck** [comment]
@euriasb I am closing this issue since it seems to have resolved on your end.

**Comment by DriftingShadows** [comment]
I am still getting this when adding the
`CognitoSessionOptions(getAWSCredentials: true)` 
option to fetchAuthSession and the user is not signed in.

**Comment by dorontal** [comment]
I'm seeing this issue again - with **all** exceptions, it seems (AuthException, StorageException) - suddenly the mechanism that caught Amplify library exceptions before is no longer catching any of the exceptions because of this PlatformException issue - if anybody else is seeing this issue resurface, please holler.

**Comment by dorontal** [comment]
This happened as soon as I upgraded CLI from version 10.2.1 to  10.2.3 yesterday, by the way.

**Comment by dorontal** [comment]
@haverchuck I believe this issue needs to be resurrected - please check.

**Comment by abdallahshaban557** [comment]
Hi @dorontal - can you please create a new Github issue and provide us with the information on our issue template - our support engineer will get back to you! https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=BUG-REPORT.yaml
