### ISSUE TITLE
[Smithy] `http_operation.dart` fails CFE in `master`

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#3854]
### Description

In Dart `master`, the following CFE error is being produced compiling the `smithy` module:

```
  Failed to load "test/http/http_operation_test.dart":
  lib/src/http/http_operation.dart:271:16: Error: A value of type 'Object?' can't be assigned to a variable of type 'Output?'.
   - 'Object' is from 'dart:core'.
        output = switch (payload) {
```

This seems to be due to a bug in Dart: https://github.com/dart-lang/sdk/issues/53627

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

master

### Amplify Flutter Version

latest

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
I believe this was resolved in https://github.com/aws-amplify/amplify-flutter/pull/3963.
