### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity" on path: DexPathList[[zip file "/data/app/com.maiacare.devapp-lQI-KRfcGxSpvJyYutwxfQ==/base.apk"]

### ISSUE THREAD

**Issue by fejofj** [aws-amplify/amplify-flutter#3913]
### Description

Android app crashes after redirecting social login link to browser and after the verification of social login but auth provider, when redirect back to app it crashes and throws runtime exception

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity" on path: DexPathList[[zip file "/data/app/com.maiacare.devapp-lQI-KRfcGxSpvJyYutwxfQ==/base.apk"

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![image](https://github.com/aws-amplify/amplify-flutter/assets/50331218/4956ea10-8d62-4d09-a3a2-04539d9c2546)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

^1.3.3

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @fejofj - Are you able to provide reproduction steps for the issue?

Can you confirm you have followed the following steps for set up? https://docs.amplify.aws/lib/auth/social/q/platform/flutter/

Was this previously working? If so, we're there any changes prior to this issue?

What social provider are you using?

**Comment by Jordan-Nelson** [comment]
@fejofj - If you are still facing this issue can you please provide the info requested above? Thanks.

**Comment by fejofj** [comment]
@Jordan-Nelson It's Fixed.

Steps I did:
- Updated the amplify_flutter package
- Updated the AndroidManifest.xml like which mentioned on the documentation  https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/
