### ISSUE TITLE
CreateAt Doesn't Auto-Generate for Android, but Works for iOS

### ISSUE THREAD

**Issue by Daniel-HyunHo-Shin** [aws-amplify/amplify-flutter#3927]
### Description

I'm working with both the API and DataStore in AWS Amplify.

I've noticed a discrepancy: the `createdAt` and `updatedAt` fields are auto-populated for iPhone users (as evidenced by the attached picture), but they aren't being generated automatically for Android users. My preference is for Amplify to handle the `createdAt` and `updatedAt` fields, leaving me to manage the `createdOn` and `updatedOn` fields that I created seperately for specialized use.

- Could this be happening because I've deliberately added the `createdAt` and `updatedAt` fields to my `schema.graphql`?
- If I were to remove the `createdAt` and `updatedAt` fields from `schema.graphql` and push the updated schema, would that be a safe procedure?
- Are there potential risks or issues associated with this action that I should be wary of?

Here is the code that I use to create a model in my program
```dart
 Future<void> addBankroll(
    String icon,
    String name,
    String description,
    DateTime createdOn,
   // createdAt and updatedAt is null here
   // When I sync with iphone they are auto-generated
   // but with android they are null

  ) async {
    Bankroll bankroll = Bankroll(
      icon: icon,
      name: name,
      description: description,
      createdOn: TemporalDateTime(createdOn),
      orderIndex: null,
      isVisible: true,
    );
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(
      () async {
        final bankrollRepository = ref.watch(bankrollRepositoryProvider);
        await bankrollRepository.addBankroll(bankroll);
        return _getBankrollList();
      },
    );
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

Some of createdAt is null. I found that happens to Android user

<img width="683" alt="git" src="https://github.com/aws-amplify/amplify-flutter/assets/43032514/63097bb9-6110-4f1f-bb64-87bea679110b">

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.2 

### Amplify Flutter Version

^1.4.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Bankroll @model @auth(rules: [{allow: owner}]) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  name: String
  icon: String
  currency: String
  description: String
  GameSessions: [GameSession] @hasMany(indexName: "byBankroll", fields: ["id"])
  LiveGameSessions: [LiveGameSession] @hasMany(indexName: "byBankroll", fields: ["id"])
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
  orderIndex: Int
  isVisible: Boolean
}

type GameSession @model @auth(rules: [{allow: owner}]) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  gameType: GameType!
  limitType: LimitType!
  buyIn: Float
  cashout: Float
  tableSize: Int
  smallBlind: Float
  bigBlind: Float
  ante: Float
  rank: Int
  currency: String
  startDate: AWSDateTime
  endDate: AWSDateTime
  duration: Int
  note: String
  location: String
  bankrollID: ID! @index(name: "byBankroll")
  bankroll: Bankroll @belongsTo(fields: ["bankrollID"])
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
}

type LiveGameSession @model @auth(rules: [{allow: owner}]) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  gameType: GameType!
  limitType: LimitType!
  buyIn: Float
  cashout: Float
  tableSize: Int
  smallBlind: Float
  bigBlind: Float
  ante: Float
  rank: Int
  currency: String
  startDate: AWSDateTime
  endDate: AWSDateTime
  duration: Int
  note: String
  location: String
  bankrollID: ID! @index(name: "byBankroll")
  bankroll: Bankroll @belongsTo(fields: ["bankrollID"])
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
}

enum GameType {
  cashGame
  onlineGame
  tournament
  pubTournament
  casualGame
}

enum LimitType {
  noLimit
  potLimit
  fixedLimit
  mixedLimit
}
```

**Comment by khatruong2009** [comment]
Hi @Daniel-HyunHo-Shin, I was able to reproduce this issue and we are taking steps to investigate it now, thanks.

**Comment by khatruong2009** [comment]
Hi @Daniel-HyunHo-Shin, if you remove createdAt and updatedAt from your schema and rerun `amplify codegen models`, DynamoDB will automatically generate those fields for you, regardless of platform. 
![Screenshot 2023-12-05 at 1 46 07 PM](https://github.com/aws-amplify/amplify-flutter/assets/64438356/0e65f411-48dc-4db2-895f-ca99158f34bd)
Attached is an example my data that I created without any createdAt or updatedAt in the schema. The data was also saved using an android device.

**Comment by Daniel-HyunHo-Shin** [comment]
**It worked perfectly.** I was concerned that the createdAt and updatedAt fields in my database might become null if I removed them from the schema. However, Amplify auto-generated them after few minutes. 

I am not sure whether all the data was initially set to null and then auto-generated, or if only a few of them were auto-generated. If your database is large, this process could take longer.

Thank you
