### ISSUE TITLE
Support connectivity_plus v5.0

### ISSUE THREAD

**Issue by kouz75** [aws-amplify/amplify-flutter#3929]
### Description

Hi,

connectivity_plus 4.x don't work with Xcode 15 : https://github.com/fluttercommunity/plus_plugins/issues/1955

a fix is know available: https://pub.dev/packages/connectivity_plus

can you update connectivity_plus version to 5.x ?

thanks
 

### Categories

- [ ] Analytics
- [X] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.6

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @kouz75 - Thanks for opening the issue. I have opened a PR to bump the minimum version

**Comment by Jordan-Nelson** [comment]
@kouz75 - The update to the version constraint has been merged and will be included in the next release.

**Comment by PfernFSU** [comment]
Hello - do we have an ETA on this? Lot of people probably experiencing this same issue, but I haven't seen a release yet.

**Comment by khatruong2009** [comment]
The fix for this was included in v1.6.0. Please let us know if you face any other issues.

**Comment by PfernFSU** [comment]
Hi @khatruong2009 - when I do a `flutter pub deps` on my project that depends upon amplify_api, I see that it is still depending upon the bad version of Connectivity Plus and not 5.x despite being 1.6.

<img width="390" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/517019/81f7aa8b-18e0-4cac-8aae-5e45565ccd99">

**Comment by Jordan-Nelson** [comment]
@PfernFSU can you please run 'flutter pub upgrade'? This will pull the latest version of all dependencies.
