### ISSUE TITLE
Amplify.Auth.confirmSignIn unexpected response

### ISSUE THREAD

**Issue by fourman-alex** [aws-amplify/amplify-flutter#3931]
### Description

When calling 
```
final signInResult = await Amplify.Auth.confirmSignIn(
      confirmationValue: newPassword,
);
_handleSignInResult(signInResult);
```
An exception returns with:
`"message": "Invalid attributes given, new password should be given with key NEW_PASSWORD"`

we're calling `Amplify.Auth.confirmSignIn` as a response to `SignInResult.nextStep.signInStep` = `AuthSignInStep.confirmSignInWithNewPassword` with the new password just as described in the [documentation](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/flutter/#confirm-signin-with-new-password)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.6

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by fourman-alex** [comment]
@Jordan-Nelson does not reproduce on 1.4.0

**Comment by Jordan-Nelson** [comment]
Hello @fourman-alex - I will see if I can reproduce this. I want to confirm the version of amplify_flutter you are using. You had listed 1.0.0 in the description. If you are not using 1.4.0 or later, would you be able to see if you still face this issue on a more recent version?

**Comment by fourman-alex** [comment]
on 1.4.0 it works fine
