### ISSUE TITLE
Increase package_info_plus version to ^5.0.0

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [aws-amplify/amplify-flutter#3933]
### Description

I'm currently using amplify_auth_cognito: ^1.4.2 and tried to update package_info_plus to the new version ^5.0.0, but I receive the following error:
```
Because no versions of amplify_auth_cognito match >1.4.2 <2.0.0 and amplify_auth_cognito 1.4.2 depends on amplify_analytics_pinpoint >=1.4.1 <1.5.0, amplify_auth_cognito ^1.4.2 requires amplify_analytics_pinpoint >=1.4.1 <1.5.0.
Because amplify_analytics_pinpoint 1.4.1 depends on package_info_plus ^4.0.1 and no versions of amplify_analytics_pinpoint match >1.4.1 <1.5.0, amplify_analytics_pinpoint >=1.4.1 <1.5.0 requires package_info_plus ^4.0.1.
Thus, amplify_auth_cognito ^1.4.2 requires package_info_plus ^4.0.1.
So, because myapp depends on both amplify_auth_cognito ^1.4.2 and package_info_plus ^5.0.0, version solving failed.

```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a new project
2. Add amplify_auth_cognito: ^1.4.2 to pubspec.yaml
3. Add package_info_plus: ^5.0.0 to pubsec.yaml
4. Run flutter pub get

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.6

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @quoc-huynh-cosee - Thanks for opening the issue. The latest version contains a breaking change. I have opened an issue in fluttercommunity/plus_plugins (https://github.com/fluttercommunity/plus_plugins/issues/2245) to get more context on this breaking change before we make any changes.

In the mean time, I believe you could use a [dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) if desired. Keep in mind that we have not run our test suite against the latest version of this plugin so you will want to ensure the app is working as expected.

**Comment by Jordan-Nelson** [comment]
For the time being, we are going to leave the version constrain as is. Updating the constraint to `^5.0.0` would result in a breaking change, which we try to avoid when possible. Updating the constraint to a range (`">=4.0.0 <6.0.0"`) would lead to a less than ideal experience as those that do not want to upgrade kotlin would be forced to pin the version of package_info_plus.

We are going to investigate how we can allow the use the latest version of this plugin without a breaking change and/or a less than ideal experience. I will comment here when we have an update. In the meantime, please let us know if the dependency override does not work for you.

**Comment by vbuberen** [comment]
Will leave link to a comment here as well https://github.com/aws-amplify/amplify-flutter/issues/3932#issuecomment-1758550300
