### ISSUE TITLE
DataStore - iOS - observe() stops working after clear()

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#395]
Amplify SDK Version: 0.1.0
Test project can be found here: https://github.com/kjones/datastore_test/

iOS Only. `DataStore.observe()` no longer works after calling `DataStore.clear()`. It all works great until a call to `DataStore.clear()` is made. From that point on, model change events cease. It doesn't matter if I cancel the `observe()` subscription before calling `clear()` or not. Current test code waits until the "ready" event before reissuing the `observe()`.

**Expected behavior**
There should be some magical combination of SDK calls that will get the `observe()` events going again after calling `clear()`.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
 - Device: iOS Simulator

**Comment by Amplifiyer** [comment]
I can reproduce this issue in a different app. I could see the remote mutations being synced down but the local observer seems to have shut down and making any DataStore API call restarts it (such as query or save)

@kjones can you confirm that after calling `clear()` if you just make a dummy query() call everything works?

**Comment by kjones** [comment]
@Amplifiyer Yes everything appears to work fine. The only thing broken appears to be that all past or future calls to observe() will never receive any data.

I was debugging in the iOS Swift DataStore plugin code last night and found that the observe() error callback gets called when calling clear() from the Flutter app. That callback appears to tear down all the "necessary parts" for notifying the Flutter code about create/update/deletes from the native DataStore SDK. Calls to observe() after that don't rebuild the necessary notification parts. The iOS plugin doesn't even get called on new observe() calls made in Flutter.

**Comment by kjones** [comment]
> @kjones can you confirm that after calling `clear()` if you just make a dummy query() call everything works?

Think I may have answered this wrong... Additional query() or save() calls do not restart item change notifications. I can see the items getting synced when debugging in the iOS SDK but they never get forwarded to Flutter.

So, when I said "Yes everything appears to work fine", I was referring to the fact that the data is all there in the local DB. query() and save() calls still work. They save data to the local DB and sync to the backend. observe() is the only thing that appears to be fatally broken without restarting the app.

**Comment by kjones** [comment]
@Amplifiyer Any more thoughts on this. The sequence of calls to DataStore I'm using in [the test app](https://github.com/kjones/datastore_test/blob/main/lib/main.dart) basically looks like this:
- Register and configure plugins
- Subscribe to DataStore Hub events
- DataStore.query() - To kickstart DataStore since there is no .start() in DS Flutter
- Wait for "ready" hub event
- DataStore.observe() - save off stream subscription

At this point multiple local and remote DS.save() calls result in calls to the observe callback that updates the UI.

- Cancel stream subscription
- DataStore.clear()
- DataStore.query() - To kickstart DataStore since there is no .start() in DS Flutter
- Wait for "ready" hub event
- DataStore.observe() - save off stream subscription

At this point:
- Remote calls to DS.save() are received by the iOS Amplify SDK and saved in the local DS DB
- Local calls to DS.save() are saved in the local DS DB and synced to the backend.
- The observe callback does not get called

After the first call to DS.clear() I can't find any sequence of calls to DS query/observer or waiting/not-waiting for specific hub events before issuing those calls that keeps observe working.

Tracing through some of the SDK source, it seems like the Flutter side of observe thinks that establishing the event channel with the native plugin code is a once-in-a-lifetime occurrence. The iOS plugin side, however, tears all of that down when DS.clear() is called.

**Comment by Amplifiyer** [comment]
@kjones I think the below is an issue and was assumed to work like android. I'll discuss this with iOS team and report back.
> The iOS plugin side, however, tears all of that down when DS.clear() is called.

**Comment by lawmicha** [comment]
To better understand the behavior on iOS DataStore, I'm running the actions in this [sample app](https://github.com/lawmicha/DatastoreObserve)

**There are no events when observer is not set up**
1. Save - Save is successful to local DB, no events on the subscription

**Events come through when observer is set up**
2. Set up observer - successful
3. Save - Save is successful, mutation events come through

**Clear will complete the publishers**
4. DataStore.clear - completed. the observer is completed successfully with `.finished` event
6. Save - Save is successful, no events

**Set up observer again is successful**
7. Set up observer - successful
8. Save - save is successful, events come through on the observer


Although there is a difference in behavior between Android and iOS, i'd like to first understand why the iOS behavior is causing this issue on Flutter:

> Tracing through some of the SDK source, it seems like the Flutter side of observe() thinks that establishing the event channel with the native plugin code is a once-in-a-lifetime occurrence.

Independent from the action ( in this case `DataStore.clear()`) that caused the iOS observer to sends a successful `.finished` completion event, this completion event is coming through. Is there a workaround in the Flutter code to clean up the references when it receives the completion event?
