### ISSUE TITLE
After Upgrading to Flutter 3.16.0-14.0.pre.24 - smithy fails.

### ISSUE THREAD

**Issue by dsmak** [aws-amplify/amplify-flutter#3972]
### Description

iOS build, that worked on Flutter 3.13.0-6.0.pre.8 fails on Flutter 3.16.0-14.0.pre.24 with one of Cognito dependencies with the following:

~/.pub-cache/hosted/pub.dev/smithy-0.5.2/lib/src/http/http_operation.dart:271:16: Error: A value of type 'Object?' can't be assigned to a variable of type 'Output?'.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

I was peacefully using cognito packages, and all worked, then upgraded to Flutter 3.16.0-14.0.pre.24.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.0-14.0.pre.24

### Amplify Flutter Version

^1.3.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@dsmak we merged a fix for this recently. It should be included in our next release. I will let you know when that happens.

**Comment by Jordan-Nelson** [comment]
Here is the PR that resolved this - https://github.com/aws-amplify/amplify-flutter/pull/3963.

You could attempt to make that one line change in your local cache. Otherwise, you will need to continue to use flutter stable until this is released.

**Comment by dsmak** [comment]
Thanks a lot, Jordan

**Comment by khatruong2009** [comment]
The fix for this was included in v1.6.0. Please let us know if you face any other issues.
