### ISSUE TITLE
Install the App, First Launch App Push Notification initialization failure，The push permission box does not appear

### ISSUE THREAD

**Issue by zilaiyedaren** [aws-amplify/amplify-flutter#3996]
### Description

Install the App, First Launch App Push Notification initialization failure，The push permission box does not appear.
But, exit the App process, restart the second or third time can appear the push permission box.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

try {
    final authPlugin = AmplifyAuthCognito();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    // should add this listener to your app's main function but before runApp and Amplify.configure to avoid missing events.
    pushPlugin.onNotificationReceivedInBackground(
        AmplifyPush.asyncNotificationReceivedHandler);
    if (!Amplify.isConfigured) {
      // call Amplify.configure to use the initialized categories in app
      await Amplify.addPlugins([
        authPlugin,
        pushPlugin,
      ]);
      await Amplify.configure(amplifyconfig);
      AmplifyPush.registerPushListener();
    }
  } on Exception catch (e) {
    debugPrint('An error occurred configuring Amplify: $e');
  }

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by zilaiyedaren** [comment]
`try {
    final authPlugin = AmplifyAuthCognito();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    // should add this listener to your app's main function but before runApp and Amplify.configure to avoid missing events.
    pushPlugin.onNotificationReceivedInBackground(
        AmplifyPush.asyncNotificationReceivedHandler);
    if (!Amplify.isConfigured) {
      // call Amplify.configure to use the initialized categories in app
      await Amplify.addPlugins([
        authPlugin,
        pushPlugin,
      ]);
      await Amplify.configure(amplifyconfig);
      AmplifyPush.registerPushListener();
    }
  } on Exception catch (e) {
    debugPrint('An error occurred configuring Amplify: $e');
  }`

**Comment by zilaiyedaren** [comment]
error message:

flutter: An error occurred configuring Amplify: PushNotificationException {
flutter:   "message": "Error occurred awaiting for device token to register device with Pinpoint",
flutter:   "recoverySuggestion": "Please review the underlying exception",
flutter:   "underlyingException": "UnknownException {\n  \"message\": \"Forbidden from accessing the Pinpoint resource.\",\n  \"recoverySuggestion\": \"Please ensure Analytics is properly configured in your amplifyconfiguration.dart file and that unauthenticated guest access is allowed or an authorized user is signed in.\",\n  \"underlyingException\": \"ForbiddenException {\\n}\"\n}"
flutter: }

**Comment by Equartey** [comment]
I see you also opened https://github.com/aws-amplify/amplify-flutter/issues/3997.

Lets consolidate the discussion on that ticket. I'm going to close this as a duplicate. 

Please respond there with your current issue and we will assist you setting up push notifications :)
