### ISSUE TITLE
An error occurred configuring Amplify: PushNotificationException

### ISSUE THREAD

**Issue by zilaiyedaren** [aws-amplify/amplify-flutter#3997]
### Description

iPhone Device not simulator， error message:

flutter: An error occurred configuring Amplify: PushNotificationException {
flutter:   "message": "Timed out awaiting for device token.",
flutter:   "recoverySuggestion": "This may happen when the native apps have not been correctly configured for push notifications, review push notification configurations of the native iOS and Android apps of your Flutter project.",
flutter:   "underlyingException": "TimeoutException after 0:00:05.000000: Future not completed"
flutter: }

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by zilaiyedaren** [comment]
This problem occurs when the first installation starts

**Comment by Equartey** [comment]
Hi @zilaiyedaren,

Sorry you ran into this issue. 

Can you please confirm you've completed the platform setup for iOS? https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/flutter/ 

If so, can you please provide more context and reproduction steps?

**Comment by zilaiyedaren** [comment]
@Equartey YES, I Do. I have completed the platform setup for ios. Install the app, fitst launch push notification permission box does't appear. but when i exit app, open app again is ok.
`final authPlugin = AmplifyAuthCognito();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    final analyticsPlugin = AmplifyAnalyticsPinpoint();
    // should add this listener to your app's main function but before runApp and Amplify.configure to avoid missing events.
    pushPlugin.onNotificationReceivedInBackground(
        AmplifyPush.asyncNotificationReceivedHandler);
    if (!Amplify.isConfigured) {
      // call Amplify.configure to use the initialized categories in app
      await Amplify.addPlugins([
        analyticsPlugin,
        authPlugin,
        pushPlugin,
      ]);
      debugPrint('Amplify plugins add');
      await Amplify.configure(amplifyconfig);
      AmplifyPush.registerPushListener();`

**Comment by zilaiyedaren** [comment]
`
@Equartey YES, I Do. I have completed the platform setup for ios. Install the app, fitst launch push notification permission box does't appear. but when i exit app, open app again is ok.
`final authPlugin = AmplifyAuthCognito();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    final analyticsPlugin = AmplifyAnalyticsPinpoint();
    // should add this listener to your app's main function but before runApp and Amplify.configure to avoid missing events.
    pushPlugin.onNotificationReceivedInBackground(
        AmplifyPush.asyncNotificationReceivedHandler);
    if (!Amplify.isConfigured) {
      // call Amplify.configure to use the initialized categories in app
      await Amplify.addPlugins([
        analyticsPlugin,
        authPlugin,
        pushPlugin,
      ]);
      debugPrint('Amplify plugins add');
      await Amplify.configure(amplifyconfig);
      AmplifyPush.registerPushListener();`
`

**Comment by zilaiyedaren** [comment]
@Equartey  First Install and open app, the newtork permission box appear, but push notification permission box does't appear. I think cognito auth sdk has not invoke completed, so push notification sdk initital async initital failure.

**Comment by Jordan-Nelson** [comment]
Hello @zilaiyedaren - As of version 1.6.0 this will no longer throw an exception. Instead a warning is logged but the configuration call is still successful. That doesn't fix the underlying issue, but does allow other amplify categories to work in the event that the token cannot be retrieved for some reason.

As far as the underlying issue goes, are you seeing this across all devices and OSs? Are you able to test with other iOS devices and iOS versions to see if this is specific to a certain device or OS?

**Comment by tiyberius** [comment]
I am getting this error on an Android physical device, but strangely enough only when building in release mode

`flutter run --flavor dev --target lib/main_dev.dart -d <DEVICE_ID> --release`

The app works when building in release mode on an iOS, but not on the Android. Here's the stack trace from Sentry:

```
{
LogRecord.error: [Filtered], 
LogRecord.loggerName: Swellify, 
LogRecord.sequenceNumber: 0, 
LogRecord.stackTrace: 
#0      AmplifyPushNotifications._registerDeviceWhenConfigure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:352)
<asynchronous suspension>
#1      AmplifyPushNotifications.configure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:231)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#3      AmplifyClass._configurePlugins (package:amplify_core/src/amplify_class.dart:171)
<asynchronous suspension>
#4      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:128)
<asynchronous suspension>
#5      _configureAmplify (package:swellify/main_dev.dart:91)
<asynchronous suspension>
#6      initializeAwsAmplify (package:swellify/main_dev.dart:59)
<asynchronous suspension>
#7      main.<anonymous closure> (package:swellify/main_dev.dart:41)
<asynchronous suspension>
#8      Sentry._init (package:sentry/src/sentry.dart:149)
<asynchronous suspension>
#9      Sentry.init (package:sentry/src/sentry.dart:70)
<asynchronous suspension>
#10     SentryFlutter.init (package:sentry_flutter/src/sentry_flutter.dart:83)
<asynchronous suspension>
#11     main (package:swellify/main_dev.dart:29)
<asynchronous suspension>
}
```

and the relevant part of my `main_dev.dart` file looks like:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await SentryFlutter.init(
    (options) {
      options.dsn =
          '<REDACTED>';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
      options.addIntegration(LoggingIntegration(minEventLevel: Level.INFO));
      options.beforeSend = beforeSentrySend;
    },
    appRunner: () async {
      configureLogging();
      await initializeAwsAmplify();
      await activateAdapty();
      observeDatastoreEvents();
      observeAuthEvents();
      runApp(
        const ProviderScope(
          child: SwellifyApp(
            flavor: 'Dev',
            showDebugBanner: true,
          ),
        ),
      );
    },
  );
}

Future<void> initializeAwsAmplify() async {
  try {
    await _configureAmplify();
  } on AmplifyAlreadyConfiguredException catch (error, stackTrace) {
    log.warning(
      'Tried to reconfigure Amplify; this can occur when your app restarts on Android.',
      error,
      stackTrace,
    );
  } on PushNotificationException catch (error, stackTrace) {
    log.severe('Error while tring to configure Amplify.', error, stackTrace);
  }
}
```

**Comment by Equartey** [comment]
@tiyberius sorry you ran into this issue as well. 

We will continue to investigate on our side.

Have you tried multiple android devices? Have you seen the error on them as well?

**Comment by tiyberius** [comment]
Thank you @Equartey for your reply. I only have one Android device that I can test this on, unfortunately. It is a Samsung Galaxy A04, model name SM-A045F/DS running Android version 13.

To add some color to this issue, I wound my commit history back and got a little more information about the error:

```
E/flutter (14225): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PushNotificationException {
E/flutter (14225):   "message": "Error occurred awaiting for device token.",
E/flutter (14225):   "recoverySuggestion": "Review the underlying exception.",
E/flutter (14225):   "underlyingException": "PlatformException(TOKEN_RECEIVED, java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR, null, null)"
E/flutter (14225): }
E/flutter (14225): #0      AmplifyPushNotifications._registerDeviceWhenConfigure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:352)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #1      AmplifyPushNotifications.configure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:231)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #2      Future.wait.<anonymous closure> (dart:async/future.dart:525)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #3      AmplifyClass._configurePlugins (package:amplify_core/src/amplify_class.dart:171)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #4      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:128)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #5      _configureAmplify (package:swellify/main_dev.dart:67)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #6      initializeAwsAmplify (package:swellify/main_dev.dart:41)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225): #7      main (package:swellify/main_dev.dart:24)
E/flutter (14225): <asynchronous suspension>
E/flutter (14225):
```

As you can see, there's an FIX_AUTH_ERROR which after Googling, looks as if it could be related to the keychain/SHA-1 for the "release" builds. I'll do some more digging, I'm hopeful that it's something to do with those keys at this point. Will report back when I have more info or when I've figured it out.

**Comment by tiyberius** [comment]
Ugh, okay so this was my bad. For anyone else who ends up here, my problem was solved by adding the right SHA-1 hash to the Google Cloud console under API's & Services -> Credentials -> "Android key (auto created by Firebase)". After clicking on the key, under "Android Restrictions" I had to add the package name and SHA-1 fingerprint I got from running `./gradlew signingReport`. See https://stackoverflow.com/a/67374808 for a bit more context.

Thanks @Equartey for any time spent looking into this issue!

**Comment by NikaHsn** [comment]
@tiyberius thanks for sharing the info @zilaiyedaren are you still facing the issue?

**Comment by Samaritan1011001** [comment]
@zilaiyedaren Thank you for your time and for reporting the issue. Can you provide the following information to help us pin this down? 
1. Which iPhone device, iOS version are you seeing the problem on?
2. Can you provide a sample code that shows how and when you are using the Amplify Push Notification APIs?

Finally, from the error message in the description, it seems like the underlying iOS's APNs setup might not be working properly. To confirm it is setup properly, you may considering logging the device token directly in the native iOS module of the Flutter app. If you can log the device token there, it'll help us pin down the root cause. 

This link might be helpful to know where you can log the device token in the iOS module - https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns

**Comment by zilaiyedaren** [comment]
@Samaritan1011001 thank you for answer this issue.
**1.Which iPhone device, iOS version are you seeing the problem on?**
all deivce and ios version have this problem
**2.Can you provide a sample code that shows how and when you are using the Amplify Push Notification APIs?**
`
final authPlugin = AmplifyAuthCognito();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    // should add this listener to your app's main function but before runApp and Amplify.configure to avoid missing events.
    pushPlugin.onNotificationReceivedInBackground(
        AmplifyPush.asyncNotificationReceivedHandler);
    if (!Amplify.isConfigured) {
      // call Amplify.configure to use the initialized categories in app
      await Amplify.addPlugins([
        authPlugin,
        pushPlugin,
      ]);
      debugPrint('Amplify plugins add');
      await Amplify.configure(amplifyconfig);
`

**Comment by zilaiyedaren** [comment]
@Samaritan1011001
first install app, ios system need network permission, and appear  network permission dialog. then the error message appears. it should be displayed push notification permission dialog after network permission dialog.

**Comment by zilaiyedaren** [comment]
@Jordan-Nelson yes, my devices and os system of devices appear this issue.

**Comment by Jordan-Nelson** [comment]
@zilaiyedaren if you are still facing this issue please take a look at the questions above. Thanks.

**Comment by Jordan-Nelson** [comment]
I will close this issue as we have not heard back.
