### ISSUE TITLE
DataStore - codegen - Exception when schema type is float and underlying is a whole number

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#400]
The generated models don't properly handle the case when the GraphQL schema is specified as `Float` and the underlying stored value is a whole number. An exception gets thrown with the message `Unhandled Exception: type 'int' is not a subtype of type 'double'`.

**To Reproduce**
1. Create a schema with a Float field.
2. Set the field value to a whole number.
3. Save the model.
4. Query for the newly saved model.

Exception will occur when deserializing the model.

**Expected behavior**
Model generation for Float schema types should properly deserialize whole numbers. Something similar to `(json['testFloat'] as num)?.toDouble()` should work.

**Platform**
[x] Android
[x] iOS

**Comment by fjnoyp** [comment]
Hi @kjones thank you for bringing that to our attention!  I'll take a look into this.

**Comment by fjnoyp** [comment]
Hi @kjones I am unable to reproduce your issue on Android or iOS.  I created a test model with a float field and then saved a whole number to it: 

`      await Amplify.DataStore.save(TestFloat(intType: 5, floatType: 5));
`
When I call query, I am able to retrieve this model without issue: 

```
(await Amplify.DataStore.query(TestFloat.classType)).forEach((element) {
        if (element != null) {
          print("the element: " + element.toString());
        }
      });

```
Result: 

> flutter: the element: TestFloat {id=528fdf07-ebf2-4e4a-83ea-a90ffc457e3e, intType=5, floatType=5.0}
> flutter: the element: TestFloat {id=ed10f4e9-029b-47c1-8fea-e29d4c915e4a, intType=5, floatType=5.0}

Could you provide more details on what your model was and how you saved it?  Also, which version of our Amplify Flutter library are you using?

**Comment by kjones** [comment]
OK. I wasn't sure of the exact last step and threw in the `query()` whereas I'm really using `observe()`.

I wonder if this needs to be a roundtrip to the backend so that when received on the client it deserializes as an int. The key was getting the backend to store the value in DDB as type `N` with no decimal place. i.e. `1` instead of `1.0`. I thought round-tripping to the local DB would do it but perhaps not.

I wonder if you could see what is stored in DDB and manually remove the decimal place. Then on the client do a DS.clear().

Anyway, I'll try to get a better example to reproduce it.

Last second thought... Could you try:
```
final someInt = 1;
await Amplify.DataStore.save(TestFloat(intType: 5, floatType: someInt.toDouble()));
```

**Comment by kjones** [comment]
So revisiting [my test app](https://github.com/kjones/datastore_test) shows that I did a pretty crappy job of writing this up. I assumed it was the normal deserialization but it actually was happening when processing Hub events.
```
I/flutter ( 9145): type 'int' is not a subtype of type 'double'
E/flutter ( 9145): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'double'
E/flutter ( 9145): #0      new TestModel.fromJson
package:datastore_test/models/TestModel.dart:286
E/flutter ( 9145): #1      TestModelType.fromJson
package:datastore_test/models/TestModel.dart:506
E/flutter ( 9145): #2      new HubEventElement
package:amplify_datastore/…/DataStoreHubEvents/HubEventElement.dart:25
E/flutter ( 9145): #3      new HubEventElementWithMetadata
package:amplify_datastore/…/DataStoreHubEvents/HubEventElementWithMetadata.dart:24
E/flutter ( 9145): #4      new OutboxMutationEvent
package:amplify_datastore/…/DataStoreHubEvents/OutboxMutationEvent.dart:26
E/flutter ( 9145): #5      _onListen.<anonymous closure>
package:amplify_datastore/amplify_datastore_stream_controller.dart:82
E/flutter ( 9145): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
```
SDK version is 0.1.0
[This commit](https://github.com/kjones/datastore_test/commit/743541739f570dc240ed8bf0ca913fc0ba982dcc) shows the changes I made to get the above exception.

**Comment by kjones** [comment]
Confirmed that using `observe()` will make this happen also and it does appear to be the roundtrip to the backend that causes it. When the underlying is a fractional number, the `observe()` stream listener is called twice for every mutation. I'm guessing once for the local mutation and once with the response from when DataStore syncs the mutation to the backend. When the underlying is a whole number the stream listener only gets called once. The response from the DataStore sync gets the following exception.
```
E/flutter (12257): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'double'
E/flutter (12257): #0      new TestModel.fromJson
package:datastore_test/models/TestModel.dart:286
E/flutter (12257): #1      TestModelType.fromJson
package:datastore_test/models/TestModel.dart:506
E/flutter (12257): #2      new SubscriptionEvent.fromMap
package:amplify_datastore_plugin_interface/…/models/subscription_event.dart:37
E/flutter (12257): #3      AmplifyDataStoreMethodChannel.observe.<anonymous closure>
package:amplify_datastore/method_channel_datastore.dart:129
E/flutter (12257): #4      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
```

**Comment by fjnoyp** [comment]
Nice thank you for the detailed logs and reproduction steps @kjones 

I'll investigate this further.

**Comment by fjnoyp** [comment]
Hi @kjones I've pulled your project but am having issues running it on Android - iOS works fine.  Did you have this issue when developing your project?  

Error on Android: 
```
E/amplify:aws-datastore( 8423): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore( 8423): GraphQLResponseException{message=Subscription error for TestModel: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'onUpdateTestModel' in type 'Subscription' is undefined @ 'onUpdateTestModel'', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'onUpdateTestModel' in type 'Subscription' is undefined @ 'onUpdateTestModel'', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
```

**Comment by kjones** [comment]
No idea what is going on here @fjnoyp. Thought maybe I didn't commit something you may have needed so to verify, I did the following:
1. `git clone https://github.com/kjones/datastore_test.git dstest`
1. `cd dstest`
1. `amplify --version`
   4.44.2
1. `amplify init`
1. `amplify push --yes`
1. Used VS Code to build the app and run in on Pixel 3 API 28 Android emulator.

No errors until the one this issue is about. Let me know if there is anything else you would like me to try.

**Comment by fjnoyp** [comment]
Thanks @kjones.  I re-pulled the project and am able to reproduce the float error you've been having, but only on Android.  

On iOS, when I click mutate, no error occurs. 
On Android, when I click mutate and get the: Unhandled Exception: type 'int' is not a subtype of type 'double' error you encountered before.  However, the model instance is still updated and I see the change in your UI. 

Do you observe similar behavior?  I noticed you marked that both iOS and Android were affected.

**Comment by kjones** [comment]
Perhaps the iOS error was when running both the Android and iOS versions at the same time and hitting mutate back-n-forth between the devices? It's been a few days so can't remember the exact details.

The change does make it to the UI because the observe() stream listener is called twice on the device that makes the mutation. If you mutate on one device, the other device UI will not get updated if I remember correctly.

**Comment by kjones** [comment]
@fjnoyp Have you had any time to take another look at this?

This is one I can work around since I can just edit the generated model code. So if you're trying to optimize impact #260 has no workaround other than modifying the schema.

**Comment by infernal008** [comment]
Hello, I would just like to share that I am experiencing the same issue as well.

I have a DataStore object whose attribute is of type Float wherein I store values from a Dart object whose attribute is of type Double - something like Double->Float.

Here are my observations:

1. In my checking, I can confirm that my values are indeed doubles, with decimal places, prior executing the `Amplify.DataStore.save(object)` code.
2. Double values having a decimal value of zero (0 or .0 in the end) are stored as integers in the DynamoDB table while values with non-zero decimal values are stored properly.
3. The following example is in relation to number 2:

```
LocalDataStore => DynamoDb
1.0 => 1
7.0 => 7
25.5 => 25.5
```

I can also confirm that the idea from @kjones `(json['testFloat'] as num)?.toDouble()` helps. So far, a workaround is enough but I think ideally it would be best not to touch generated code like the DataStore objects.

**Comment by kjones** [comment]
I completely forgot this even existed for two reasons.
1. I have hand modified the generated code with the workaround,
and more importantly
2. #260 has still not been fixed and has no workaround so I'm not currently using the AWS DataStore plugin. I am instead using my own DataStore plugin written back in September which does support nested classes. ([example DataStore plugin](https://github.com/kjones/flutter-datastore-example))

**Comment by infernal008** [comment]
> I completely forgot this even existed for two reasons.
> 
> 1. I have hand modified the generated code with the workaround,
>    and more importantly
> 2. #260 has still not been fixed and has no workaround so I'm not currently using the AWS DataStore plugin. I am instead using my own DataStore plugin written back in September which does support nested classes. ([example DataStore plugin](https://github.com/kjones/flutter-datastore-example))

Lucky for me, the workaround is currently enough for me to proceed with my development. Though I would have to keep an eye into it as a simple codegen would perhaps overwrite it.

I was actually parsing the num values the long way, thanks for the lead on a shorter version. :D

**Comment by Lorenzohidalgo** [comment]
@fjnoyp is there any update on this? Getting a little tired of having to modify the generated models after every pull.

The current workaround is changing all floats to the generated files from:
```dart
        totalValue = json['totalValue'],
```

to:
```dart
        totalValue = json['totalValue'] != null
            ? (json['totalValue'] as num).toDouble()
            : json['totalValue'],
```

**Comment by rmargolinross** [comment]
Is this still being worked on?

**Comment by rmargolinross** [comment]
> @fjnoyp is there any update on this? Getting a little tired of having to modify the generated models after every pull.
> 
> The current workaround is changing all floats from the generated files from:
> 
> ```dart
>         totalValue = json['totalValue'],
> ```
> 
> to:
> 
> ```dart
>         totalValue = json['totalValue'] != null
>             ? (json['totalValue'] as num).toDouble()
>             : json['totalValue'],
> ```

A cleaner way to write this is ```totalValue = (json['totalValue'] as num?)?.toDouble();```

**Comment by jobypthomas** [comment]
@rmargolinross @fjnoyp @Lorenzohidalgo 
I am having the same issue. This started happening since I made my app null safe and upgrading to library 0.2.2 from 0.1.0. Also, it happens only in iOS. Android works just fine. Apparently, the workaround does not work for me. I modified the "Employee.fromJson()" method in the generated Employee.dart file and replaced 
`_salary = json['salary'] `
with 
```
_salary = json['salary'] != null
            ? (json['salary'] as num).toDouble()
            : json['salary'],
```
BUT NO LUCK.

**Comment by jobypthomas** [comment]
Another thing I noticed is that for "Int? type in schema.graphql, dynamodb stores as int (eg: 9). However, the ".fromJson" receives them as float (eg: 9.0) randomly. I had to explicitly handle them to make it to work. 
```
_quantity = json['quantity'] != null
            ? (json['quantity'] as num).toInt()
            : json['quantity'],
```
Please note, I have this issue only in iOS. Android works just fine.

**Comment by HuiSF** [comment]
Thank you for the follow up @jobypthomas 
This PR should be able to fix the issue you mentioned in your latest comment. I will do some testing and update here.
