### ISSUE TITLE
Remove browser redirection after signOut() in app using social sign in

### ISSUE THREAD

**Issue by FirdousNath** [aws-amplify/amplify-flutter#401]
This behaviour is seen under android whenever I call `Amplify.Auth.signOut()` it opens up chrome with redirection link. I also tried removing metadata field inside amplifyconfiguration.dart file.
` "SignInRedirectURI": "",
                            "SignOutRedirectURI": "",`

Can someone know how to remove redirection ?

**Comment by rmargolinross** [comment]
I think I remember reading somewhere that in the iOS package, there is the option to just delete the auth token to sign out. That would be ideal to have for any social sign in on both ios and android if possible.

**Comment by haverchuck** [comment]
Related to this [amplify-android](https://github.com/aws-amplify/amplify-android/issues/1180) issue.

**Comment by haverchuck** [comment]
@FirdousNath Are you using Hosted UI at all? If you are only using the standard APIs such as `Auth.signIn` and `Auth.signOut`, you can remove the entire "OAuth" block from your amplifyconfiguration.dart file.  This would stop the behavior you are seeing.

**Comment by raphire08** [comment]
Hello, I removed the OAuth section from config file.
The redirection behaviour has stopped. The login and logout is working. But, getting an error in console for Android simulator only after that. 

_federatedSignIn: Putting provider and token in store
W/AWSMobileClient(12345): Failed to federate tokens during sign-in
W/AWSMobileClient(12345): java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.

How to get rid of this without changing the actual configuration in aws?

**Comment by FirdousNath** [comment]
Nothing helped so far, I removed everything still the same. What I did to override is I included a deep link to my app which in turns reopen my app

**Comment by dubeboy** [comment]
I was wondering if there is any progress regarding this issue?

**Comment by abhishekak048** [comment]
Any update?

**Comment by twink1e** [comment]
I'm using email sign in without UI, and social sign in with UI at the same time, so I have to include the OAuth and redirect section in amplify config file.
How can I stop the logout redirect web from being popped up when user sign in with email or after logout?

**Comment by artahc** [comment]
any update on this?

**Comment by Jordan-Nelson** [comment]
As of now, the Amplify-Android library, which Amplify-Flutter depends on, does not officially support social sign in and username based sign in within the same app. The [amplify-android](https://github.com/aws-amplify/amplify-android/issues/1180) issue linked above is the feature request for that in Amplify-Android. If this is a feature you are looking for, you can give that issue a 👍  to show your support.

**Comment by ken-ng-esotec** [comment]
To overcome this issue, do global sign out so that the browser redirect is skipped.

      final SignOutResult res = await Amplify.Auth.signOut(
        options: const SignOutOptions(globalSignOut: true),
      );

**Comment by fuzzy28** [comment]
> To overcome this issue, do global sign out so that the browser redirect is skipped.
> 
> ```
>   final SignOutResult res = await Amplify.Auth.signOut(
>     options: const SignOutOptions(globalSignOut: true),
>   );
> ```

This works @ken-ng-esotec ! thanks!

Also, anyone has encountered like when authenticating thru google / Facebook, if there's only one account logged in, it automatically registers that account without asking to choose another account?

**Comment by Jordan-Nelson** [comment]
Hello everyone - We have recently released a new developer preview version of the Auth category ([amplify_flutter v1.0.0-next.0](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.0)). This new version is a full re-write of the auth category in dart, and it supports Mobile, Desktop, and Web. This issue is addressed in this new version. You can read more about the developer preview release in the [blog post](https://aws.amazon.com/blogs/mobile/amplify-flutter-auth-web-and-desktop/) and [docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/). I will update this issue again once this new version is out of developer preview.

Let me know if you have any questions!

**Comment by HappyMakadiyaS** [comment]
Hey, @Jordan-Nelson  
When the version 1.0.0 scheduled for production release? As we have to fix this in a production application.

**Comment by Jordan-Nelson** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. See [the comment above](https://github.com/aws-amplify/amplify-flutter/issues/401#issuecomment-1224270594) for details on what was changed in this version with regards to this issue.

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
