### ISSUE TITLE
flutter analytics demo app crashed when install aab from google play store

### ISSUE THREAD

**Issue by seven8-dev** [aws-amplify/amplify-flutter#4014]
### Description

I use flutter analytics demo app to test. (only configure amplify and do nothing else)
APK works fine.  (IOS works fine too)
But when I build aab file and publish to google play store, the app crashed when launch.

both test on gradle:7.4.2  and gradle:8.1.0

this is the src code.
[pubspec.yaml.txt](https://github.com/aws-amplify/amplify-flutter/files/13172418/pubspec.yaml.txt)
[main.dart.txt](https://github.com/aws-amplify/amplify-flutter/files/13172405/main.dart.txt)

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. build aab and publish to google play store
2. only launch app then crashed

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.8

### Amplify Flutter Version

  amplify_flutter: ^1.4.1   amplify_auth_cognito: ^1.4.2   amplify_analytics_pinpoint: ^1.4.1   amplify_push_notifications_pinpoint: ^1.2.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@seven8-dev - Can you confirm the same APK that was uploaded to the play store works as expected when run NOT through the play store? Can this be reproduced without publishing to the play store?

Are there any logs you are collecting?

**Comment by seven8-dev** [comment]
I build APK directly and works fine. I confirmed this.

I did fully test yesterday.  I also confirmed :
If i remove the pinpoint configure , app will not crash and works fine.

This is test demo src  and the crash log.
[demoapp.zip](https://github.com/aws-amplify/amplify-flutter/files/13194681/demoapp.zip)

[logcat.txt.zip](https://github.com/aws-amplify/amplify-flutter/files/13194661/logcat.txt.zip)
[log.txt.zip](https://github.com/aws-amplify/amplify-flutter/files/13194664/log.txt.zip)

This is the test result. 
<img width="1174" alt="スクリーンショット 2023-10-28 15 27 39" src="https://github.com/aws-amplify/amplify-flutter/assets/130534626/505b9887-b0ef-45c7-95d3-cfa47269f6f5">

Thanks.

**Comment by seven8-dev** [comment]
If need full demo src , i can upload too. 
The test demo is simple and nothing else. (Just configure the pinpoint addon.)

**Comment by seven8-dev** [comment]
I build a new version and it works fine now.
I do not know why it works now???
