### ISSUE TITLE
Flutter Datastore not working on IOS

### ISSUE THREAD

**Issue by DanieduPlessis** [aws-amplify/amplify-flutter#402]
**Describe the bug**
Unable to run app on IOS device after adding amplify_datastore 0.1.0

**To Reproduce**
1. Create a new flutter app
2. Add amplify_core: ^0.1.0 and  amplify_datastore: ^0.1.0 to the pubspec lock file
3. Uncomment the 2nd line in the Podfile, and change it to platform :ios, '11.0'
4. execute Flutter run to run the application on IOS.

**Expected behavior**
When trying to run this application on IOS device, the follow error is show (running this on android does work)

```console
Running pod install...                                              5.3s
Running Xcode build...                                                  
Xcode build done.                                           40.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-02-22 15:46:39.907 xcodebuild[65970:812155]  DTDeviceKit: deviceType from 9fd8fc2d464346c17ae08bb44ac19f7c232cf0ae was NULL
    2021-02-22 15:46:39.997 xcodebuild[65970:812148]  DTDeviceKit: deviceType from 9fd8fc2d464346c17ae08bb44ac19f7c232cf0ae was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:419:83:
    warning: undeclared selector 'startCustomAuthentication_v2' [-Wundeclared-selector]
                if (self.pool.isCustomAuth && [self.pool.delegate respondsToSelector:@selector(startCustomAuthentication_v2)]) {
                                                                                      ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:420:79:
    warning: undeclared selector 'startCustomAuthentication_v2' [-Wundeclared-selector]
                    authenticationDelegate = [self.pool.delegate performSelector:@selector(startCustomAuthentication_v2)];
                                                                                  ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:461:20:
    warning: unused variable 'userAttributes' [-Wunused-variable]
            NSString * userAttributes = lastChallenge.challengeParameters[@"userAttributes"];
                       ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:668:53:
    warning: undeclared selector 'startCustomAuthentication_v2' [-Wundeclared-selector]
                [self.pool.delegate respondsToSelector:@selector(startCustomAuthentication_v2)]) {
                                                        ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:669:118:
    warning: undeclared selector 'startCustomAuthentication_v2' [-Wundeclared-selector]
                id<AWSCognitoIdentityCustomAuthentication> authenticationDelegate = [self.pool.delegate
                performSelector:@selector(startCustomAuthentication_v2)];
                                                                                                                         ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:1199:33:
    warning: 'getMultiFactorAuthenticationCode:mfaCodeCompletionSource:' is deprecated: Use
    `getMultiFactorAuthenticationCode_v2:mfaCodeCompletionSource:` instead [-Wdeprecated-declarations]
            [authenticationDelegate getMultiFactorAuthenticationCode:authenticationInput mfaCodeCompletionSource:mfaCompletionSource];
                                    ^
    In file included from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m:8:
    In file included from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider.h:43:
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.h:422:122:
    note: 'getMultiFactorAuthenticationCode:mfaCodeCompletionSource:' has been explicitly marked deprecated here
                     mfaCodeCompletionSource: (AWSTaskCompletionSource<NSString *> *) mfaCodeCompletionSource __attribute__((deprecated("Use
                     `getMultiFactorAuthenticationCode_v2:mfaCodeCompletionSource:` instead")));
                                                                                                                             ^
    6 warnings generated.
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileResults.swift:302:9: warning:
    switch covers known cases, but 'AWSCognitoIdentityProviderDeliveryMediumType' may have additional unknown values
            switch(deliveryDetails.deliveryMedium) {
            ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileResults.swift:302:9: note:
    handle unknown values using "@unknown default"
            switch(deliveryDetails.deliveryMedium) {
            ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.m:1
    077:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - (void)synchronize
    ^
    In file included from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.m:9
    :
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.h:2
    76:1: note: method 'synchronize' declared here
    - (void)synchronize __attribute__((deprecated("calling this method is no longer required")));
    ^
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.m:1
    082:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - (BOOL)synchronizeWithError:(NSError *__autoreleasing *)error
    ^
    In file included from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.m:9
    :
    /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/Internal/UICKeyChainStore/AWSCognitoAuthUICKeyChainStore.h:2
    77:1: note: method 'synchronizeWithError:' declared here
    - (BOOL)synchronizeWithError:(NSError * __nullable __autoreleasing * __nullable)error __attribute__((deprecated("calling this method is
    no longer required")));
    ^
    2 warnings generated.
    /Volumes/Macintosh HD - Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m:442:72: warning:
    'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
    [-Wdeprecated-declarations]
                    NSURLConnection *connection = [[NSURLConnection alloc] initWithRequest:request delegate:self startImmediately:NO];
                                                                           ^
    In module 'Foundation' imported from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk/System/Library/Frameworks/Foundati
    on.framework/Headers/NSURLConnection.h:114:1: note: 'initWithRequest:delegate:startImmediately:' has been explicitly marked deprecated
    here
    - (nullable instancetype)initWithRequest:(NSURLRequest *)request delegate:(nullable id)delegate startImmediately:(BOOL)startImmediately
    API_DEPRECATED("Use NSURLSession (see NSURLSession.h)", macos(10.5,10.11), ios(2.0,9.0), tvos(9.0,9.0)) API_UNAVAILABLE(watchos);
    ^
    /Volumes/Macintosh HD - Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.m:830:76: warning:
    'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
    [-Wdeprecated-declarations]
                        NSURLConnection *connection = [[NSURLConnection alloc] initWithRequest:request delegate:self startImmediately:NO];
                                                                               ^
    In module 'Foundation' imported from /Volumes/Macintosh HD -
    Data/personal/flutter_datastore_test/ios/Pods/AWSMobileClient/AWSCognitoAuth/AWSCognitoAuth.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk/System/Library/Frameworks/Foundati
    on.framework/Headers/NSURLConnection.h:114:1: note: 'initWithRequest:delegate:startImmediately:' has been explicitly marked deprecated
    here
    - (nullable instancetype)initWithRequest:(NSURLRequest *)request delegate:(nullable id)delegate startImmediately:(BOOL)startImmediately
    API_DEPRECATED("Use NSURLSession (see NSURLSession.h)", macos(10.5,10.11), ios(2.0,9.0), tvos(9.0,9.0)) API_UNAVAILABLE(watchos);
    ^
    2 warnings generated.
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:14: error: consecutive statements on a line must be separated by ';'
                } receiveValue: { (mutationEvent) in
                 ^
                 ;
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:27: error: consecutive statements on a line must be separated by ';'
                } receiveValue: { (mutationEvent) in
                              ^
                              ;
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:27: error: expected expression
                } receiveValue: { (mutationEvent) in
                              ^
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:23
    9:81: error: referencing instance method 'sink(receiveValue:)' on 'Publisher' requires the types 'DataStoreError' and 'Never' be
    equivalent
                observeSubscription = try observeSubscription ?? bridge.onObserve().sink {
                                                                                    ^
    Combine.Publisher:2:11: note: where 'Self.Failure' = 'DataStoreError'
    extension Publisher where Self.Failure == Never {
              ^
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:15: error: use of unresolved identifier 'receiveValue'
                } receiveValue: { (mutationEvent) in
                  ^~~~~~~~~~~~
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:29: error: unable to infer complex closure return type; add explicit type to disambiguate
                } receiveValue: { (mutationEvent) in
                                ^
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:24
    6:29: error: closure expression is unused
                } receiveValue: { (mutationEvent) in
                                ^
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:26
    6:11: warning: 'catch' block is unreachable because no errors are thrown in 'do' block
            } catch {
              ^
    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'amplify_datastore' from
    project 'Pods')
    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'amplify_datastore' from
    project 'Pods')
    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'amplify_datastore' from
    project 'Pods')
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/ios/Classes/FlutterFetchCognitoSessionResult.
    swift:146:44: warning: result of call to 'get()' is unused
          try identityProvider.getIdentityId().get()
                                               ^  ~~
    /Users/danieduplessis/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/ios/Classes/FlutterSignOutResult.swift:42:5:
    warning: will never be executed
        return state
        ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.
```

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.3.1

**Additional context**

**Comment by fjnoyp** [comment]
Hi @DanieduPlessis 

Are you able to deploy your app to an iPhone simulator?  Also, are you able to build your Flutter project before adding Datastore or any of our Amplify Flutter libraries?  

I haven't personally encountered this issue before, but looking online, it appears this website might have a solution: 

https://community.axway.com/s/question/0D52X00007eJIuSSAW/dtdevicekit-devicetype-from-device-id-was-null-error

**Comment by Amplifiyer** [comment]
@DanieduPlessis DataStore on iOS only supports iOS 13 and onwards. Can you change your Podfile to `platform :ios, '13.0'` and let us know if that fixes it for you?

**Comment by capraqua** [comment]
I have the same issue. I changed plaftform :ios, '13.0'. It seems Datastore requiring 13.0 but SQLite is at 11.

Here is what i get

Xcode build done.                                            7.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/lamnguyen/Documents/Desktop backup/projects/chison_flutter_app/ios/Pods/AmplifyPlugins/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift:10:8: error: compiling for iOS 11.0, but
    module 'SQLite' has a minimum deployment target of iOS 13.0: /Users/lamnguyen/Documents/Desktop
    backup/projects/chison_flutter_app/build/ios/Release-iphoneos/SQLite.swift/SQLite.framework/Modules/SQLite.swiftmodule/arm64-apple-ios.swiftmodule
    import SQLite
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by Amplifiyer** [comment]
@capraqua which flutter version are you using?

**Comment by capraqua** [comment]
> @capraqua which flutter version are you using?

Flutter Channel beta, 1.26.0-17.6.pre

**Comment by Amplifiyer** [comment]
> 
> 
> > @capraqua which flutter version are you using?
> 
> Flutter Channel beta, 1.26.0-17.6.pre

There are some issues with Flutter beta version as mentioned here https://github.com/aws-amplify/amplify-flutter/issues/359 Please use stable version of Flutter for now.

**Comment by capraqua** [comment]
> > > @capraqua which flutter version are you using?
> > 
> > 
> > Flutter Channel beta, 1.26.0-17.6.pre
> 
> There are some issues with Flutter beta version as mentioned here #359 Please use stable version of Flutter for now.

Thanks, here what i did to fix the issue

- Change to stable channel
- rm ios folder
- plaftform :ios, '13.0' in pod file
- change s.platform = :ios, '11.0' to s.platform = :ios, '13.0' in amplify_datastore.podspec

**Comment by haverchuck** [comment]
@DanieduPlessis Did the suggestion from @capraqua work for you?

**Comment by tranminhhaifet** [comment]
Got same problem and no way to fix, so disappointed

**Comment by haverchuck** [comment]
@DanieduPlessis I see that you are adding `amplify_core`.  As part of our recent GA release, you can now import `amplify_flutter` instead.

**Comment by haverchuck** [comment]
@tranminhhaifet What is the specific error you are seeing (this thread details a couple)?

**Comment by haverchuck** [comment]
@DanieduPlessis @tranminhhaifet @capraqua Could you try updating your Podfile to include a post_install hook that contains the following:
```
post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
   end
 end
```

**Comment by tranminhhaifet** [comment]
@haverchuck Thank you but still not working, here is my errors
Launching lib/main.dart on iPhone 11 in debug mode...
 lib/main.dart
Xcode build done.                                           12.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:14: error: consecutive statements on a line must be separated by ';'
                } receiveValue: { (mutationEvent) in
                 ^
                 ;
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:27: error: consecutive statements on a line must be separated by ';'
                } receiveValue: { (mutationEvent) in
                              ^
                              ;
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:27: error: expected expression
                } receiveValue: { (mutationEvent) in
                              ^
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:239:81: error: referencing instance method 'sink(receiveValue:)' on 'Publisher' requires the types 'DataStoreError' and 'Never' be equivalent
                observeSubscription = try observeSubscription ?? bridge.onObserve().sink {
                                                                                    ^
    Combine.Publisher:2:11: note: where 'Self.Failure' = 'DataStoreError'
    extension Publisher where Self.Failure == Never {
              ^
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:15: error: use of unresolved identifier 'receiveValue'
                } receiveValue: { (mutationEvent) in
                  ^~~~~~~~~~~~
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:29: error: unable to infer complex closure return type; add explicit type to disambiguate
                } receiveValue: { (mutationEvent) in
                                ^
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:246:29: error: closure expression is unused
                } receiveValue: { (mutationEvent) in
                                ^
    /Users/hai/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_datastore-0.1.0/ios/Classes/SwiftAmplifyDataStorePlugin.swift:266:11: warning: 'catch' block is unreachable because no errors are thrown in 'do' block
            } catch {
              ^
    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'amplify_datastore' from project 'Pods')
    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'amplify_datastore' from project 'Pods')
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 11.
Exited (sigterm)

**Comment by Ashish-Nanda** [comment]
@tranminhhaifet Could you give us some more details:

1) Have you set `plaftform :ios, '13.0'` in your pod file?
2) What version of Xcode are you using? 
3) Are you on an M1 Mac?
4) What version of Flutter are you using?

Please provide any other details about your setup that could be useful.

**Comment by tranminhhaifet** [comment]
@Ashish-Nanda 
1. Yes I did
2. Xcode 11 
3. No, I use Macbook Air 2019
4. Flutter 1.22.6 and Dart 2.10.5

**Comment by Ashish-Nanda** [comment]
@tranminhhaifet I think you mentioned Xcode 11.3 initially correct?

I think that is the issue. Amplify iOS requires Xcode 11.4 at the minimum: https://github.com/aws-amplify/amplify-ios#installation

You will need to upgrade. I have seen a similar issue before, so hopefully this will resolve it for you.

After upgrading I recommend you also do:
```
rm Podfile.lock
rm -rf Pods/
```
And then run the app again.

**Comment by tranminhhaifet** [comment]
Hi @Ashish-Nanda 
1. My Xcode 11.5

**Comment by capraqua** [comment]
> @DanieduPlessis @tranminhhaifet @capraqua Could you try updating your Podfile to include a post_install hook that contains the following:
> 
> ```diff
>  post_install do |installer|
>    installer.pods_project.targets.each do |target|
>      flutter_additional_ios_build_settings(target)
> +    target.build_configurations.each do |config|
> +      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
> +    end
>    end
>  end
> ```

This solution works for me with the newest flutter version Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.7 19H114 darwin-x64)

**Comment by tranminhhaifet** [comment]
@capraqua  thank you
I did try the hook, did not work for me. macOS Catalina 10.15.5, Xcode 11, Flutter 1.22.6 channel stable, dart 2.10.5. I temporarily switch to Android Simulator and working with a Linux machine, works fine.

**Comment by dsanvita** [comment]
I fixed a similar issue with a small code change: https://github.com/aws-amplify/amplify-ios/pull/1137#pullrequestreview-651502617

**Comment by offlineprogrammer** [comment]
Hey @tranminhhaifet 

@dsanvita code change was approved and merged... 
I am closing this issue for now as we didn't hear from you 
Feel free to test using the latest build and let us know if you got any issues
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
