### ISSUE TITLE
Implement better error messages for Sign In with Apple

### ISSUE THREAD

**Issue by rmargolinross** [aws-amplify/amplify-flutter#405]
**Describe the bug**
I am getting this generic error whenever trying to Sign in with Apple. I get all the way through the sign in process and right after I accept the permissions to sign in the error throws as the browser dissapears.

Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't.

**To Reproduce**
Sign in with Apple

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Additional context**
I am at a loss here as I can't seem to get anymore information that what I have posted above. I have no idea what is going on.

**Comment by omchiii** [comment]
I had the same issue, mine seem to get fixed after : 1. removing amplify from the cli, 2. update the cli and 3. initialize amplify from the cli again & add auth through cli again. On Android mine does not seem to work.

**Comment by rmargolinross** [comment]
I was actually able to find out the issue, but I am keeping this open as the error message is not helpful. The issue was that I was missing the required email mapping in my cognito setup. It would be helpful to set up some sort of pointer to this configuration issue.

**Comment by haverchuck** [comment]
@rmargolinross We do [mention this in the documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter#amazon-cognito-user-pool-setup), but perhaps it needs to be more prominent.

**Comment by haverchuck** [comment]
@rmargolinross I am going to mark this issue as a feature request for more helpful Hosted UI error messaging.  This may require the involvement of multiple teams.

**Comment by dnys1** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. The error messages should be improved and there should be consistency between iOS and Android now.

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
