### ISSUE TITLE
Auth.forgetDevice always removes local device details even when forgetting a device that isn't the current device

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#4056]
### Description

`Auth.forgetDevice()` always removes local device details even when forgetting a device that isn't the current device.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Set up app with device tracking
2. Remember device 1
3. Remember device 2
4. From device 1, forget device 2
5. Observe that local device info on device 1 is removed.

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

n/a

### Amplify Flutter Version

1.6.x

### Deployment Method

Amplify CLI

**Comment by dtodt** [comment]
https://github.com/aws-amplify/amplify-flutter/pull/4060

**Comment by haverchuck** [comment]
This is fixed on amplify flutter 1.6.3.
