### ISSUE TITLE
The method 'Amplify' isn't defined for the type '_MyAppState'.

### ISSUE THREAD

**Issue by gauravdangi** [aws-amplify/amplify-flutter#407]
I've just started learning AWS Amplify and followed the step given in https://aws.amazon.com/getting-started/hands-on/build-flutter-app-amplify/module-two/ to initialize Amplify in my flutter project. 

But I'm getting **The method 'Amplify' isn't defined for the type '_MyAppState'** error when I'm trying to integrate Amplify (with statement final _amplify = Amplify();) in my App.

**To Reproduce**
1. Create new flutter project
2. Initialize Amplify (amplify init)
3. Add amplify_core: '<1.0.0' in pubspec.yaml 
4. Integrate Amplify
5. Flutter run
**Output**

```
gauravdangi@Gauravs-MacBook-Air amplify_demo % flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            9.6s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[23877]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1f5000188)
    and ?? (0x1184442b8). One of the two will be used. Which one is undefined.
    objc[23877]: Class AMSupportURLSession is implemented in both ?? (0x1f50001d8) and ??
    (0x118444308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    lib/main.dart:15:20: Error: Method not found: 'Amplify'.
      final _amplify = Amplify();
                       ^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/gauravdangi/Development/work/examples/amplify_demo/ios/Pods/Pods.xcodeproj: warning:
    The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flutter' from
    project 'Pods')
```

**Expected behavior**
I should be able to run my flutter application

**Screenshots**
<img width="968" alt="Screenshot 2021-02-24 at 10 05 44 PM" src="https://user-images.githubusercontent.com/15454927/109034654-dd79b600-76ed-11eb-8112-916381e83440.png">

main.dart code
```
import 'package:flutter/material.dart';
import './amplifyconfiguration.dart';
import 'package:amplify_core/amplify_core.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _amplify = Amplify();

  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }

  void _configureAmplify() async {
    try {
      await _amplify.configure(amplifyconfig);
      print('Successfully configured Amplify 🎉');
    } catch (e) {
      print('Could not configure Amplify ☠️');
    }
  }
}

```

**amplifyconfiguration.dart**
```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0"
}''';
```

**Smartphone (please complete the following information):**
 - Device: [iPhone 12 Pro max
 - OS: iOS14.5

**Additional context**
When I'm running Amplify console, I'm getting **App with id: xxxxxxxxxx not found**

Also I'm using MacOs with new M1 chip

**Comment by Amplifiyer** [comment]
@gauravdangi, the module that you are referring to is currently out of date. Please follow https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter to get started for now and we will work on updating the module you referred.

**Comment by gauravdangi** [comment]
Thanks! Working as expected.
