### ISSUE TITLE
[Amplify Storage] [uploadFile] Slow performance on first usage

### ISSUE THREAD

**Issue by delfme** [aws-amplify/amplify-flutter#4083]
### Description

I opened a similar issue long time ago but it seems it's gone lost in the pile.

The file upload takes much time on first usage.

Upload a file of 1.63 MB:
- Stunning 6 sec at first usage
- Decent 2 sec on second usage if it is used soon after

Issue is not related to variation of internet connectivity and is not reproducible by using `dio` plugin.
We suspect there is some code that get performed on first usage and is taking 3-4sec.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

To reproduce the issue you can use this sample
https://github.com/delfme/sample_demo_amplify/tree/main

Just download a file from web and then upload it multiple time.
First upload is slow.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel master, 3.17.0-1.0.pre.37

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @delfme - I believe https://github.com/aws-amplify/amplify-flutter/issues/3044 was the issue where you had first reported this, but I we can track this as a separate issue since the original comment on #3044 seems to be for a different issue.

Can you use flutter's dev tools to [capture the network traffic](https://docs.flutter.dev/tools/devtools/network) on a initial upload as well as a subsequent upload?

**Comment by delfme** [comment]
Hello @Jordan-Nelson - it is not clear what is happening with the network.
I see `POST` to cognito that takes 700ms !! Then I see Pending `PUT`.
<img width="1146" alt="Screenshot 2023-11-08 at 15 04 36" src="https://github.com/aws-amplify/amplify-flutter/assets/53510751/10ef7826-2f6a-4f20-af72-7ad06bd41b0d">

Can you please guys quick investigate issue by using this sample?
As for our app, we cannot waste 700ms or 1-2 sec for cognito auth.
We are mostly sending 2-3MB files (typical Whatsapp scenario), and users expect the file transfer to be fast.

**Comment by Jordan-Nelson** [comment]
Thank you for sharing the network info. I have a few follow up questions.
1. Can you share the value of the "x-amz-target" request header on each of the Cognito requests? You can find that in the dev tools under Headers -> Request Headers
2. Are reproducing this as an authenticated or unauthenticated user? That is, have you logged in already on this device?
3. I see your region is us-east-1. How close geographically are you to this region?
4. Are you using a vpn?

**Comment by delfme** [comment]
Thx @Jordan-Nelson 
1. x-amz-target: [AWSCognitoIdentityService.GetCredentialsForIdentity]
2. authenticated
3. very close, net. delay could be around 50ms
4. nope. Upload is slow only with the AWS Storage plugin.

Have you had the chance to try the sample?

**Comment by delfme** [comment]
Also, it is my code wrong or await doesn't work as expected in this code?
```
var startTime = DateTime.timestamp();
    try {
    final resultUrl = await Amplify.Storage.uploadFile(
      key: 'test_amplify/${basename(file.path)})',
      localFile: AWSFile.fromPath(file.path),
      onProgress: (progress) {
        final sent = progress.fractionCompleted * len;
        debugPrint('File upload progress %${progress
            .fractionCompleted} sent $sent of total $len');
      });
      } on StorageException catch (e) {
      safePrint('Error uploading file: $e');
      } finally {
      safePrint('Successfully uploaded file: ${resultUrl}');
      debugPrint('Time elapsed to upload '
          '${DateTime.timestamp().difference(startTime).inMilliseconds}ms');
      }
```

Log is
```
flutter: Successfully uploaded file: null
flutter: Time elapsed to upload 3ms
flutter: File upload progress %0.030526955167261033 sent 65536.0 of total 2146824
flutter: File upload progress %0.061053910334522066 sent 131072.0 of total 2146824
flutter: File upload progress %0.0915808655017831 sent 196608.0 of total 2146824
flutter: File upload progress %0.12210782066904413 sent 262144.0 of total 2146824
flutter: File upload progress %0.15263477583630516 sent 327680.0 of total 2146824
flutter: File upload progress %0.1831617310035662 sent 393216.0 of total 2146824
flutter: File upload progress %0.21368868617082723 sent 458752.0 of total 2146824
flutter: File upload progress %0.24421564133808826 sent 524288.0 of total 2146824
flutter: File upload progress %0.2747425965053493 sent 589824.0 of total 2146824
flutter: File upload progress %0.30526955167261033 sent 655360.0 of total 2146824
flutter: File upload progress %0.3357965068398714 sent 720896.0 of total 2146824
flutter: File upload progress %0.3663234620071324 sent 786432.0 of total 2146824
flutter: File upload progress %0.39685041717439345 sent 851968.0 of total 2146824
flutter: File upload progress %0.42737737234165446 sent 917504.0 of total 2146824
flutter: File upload progress %0.4579043275089155 sent 983040.0 of total 2146824
flutter: File upload progress %0.4884312826761765 sent 1048576.0 of total 2146824
flutter: File upload progress %0.5189582378434375 sent 1114112.0 of total 2146824
flutter: File upload progress %0.5494851930106986 sent 1179648.0 of total 2146824
flutter: File upload progress %0.5800121481779597 sent 1245184.0 of total 2146824
flutter: File upload progress %0.6105391033452207 sent 1310720.0 of total 2146824
flutter: File upload progress %0.6410660585124817 sent 1376256.0 of total 2146824
flutter: File upload progress %0.6715930136797428 sent 1441792.0 of total 2146824
flutter: File upload progress %0.7021199688470038 sent 1507328.0 of total 2146824
flutter: File upload progress %0.7326469240142648 sent 1572864.0 of total 2146824
flutter: File upload progress %0.7631738791815258 sent 1638400.0 of total 2146824
flutter: File upload progress %0.7937008343487869 sent 1703936.0 of total 2146824
flutter: File upload progress %0.8242277895160479 sent 1769472.0 of total 2146824
flutter: File upload progress %0.8547547446833089 sent 1835008.0 of total 2146824
flutter: File upload progress %0.8852816998505699 sent 1900544.0 of total 2146824
flutter: File upload progress %0.915808655017831 sent 1966080.0 of total 2146824
flutter: File upload progress %0.946335610185092 sent 2031616.0 of total 2146824
flutter: File upload progress %0.976862565352353 sent 2097152.0 of total 2146824
flutter: File upload progress %1.0 sent 2146824.0 of total 2146824
flutter: File upload progress %1.0 sent 2146824.0 of total 2146824

```

**Comment by Jordan-Nelson** [comment]
I was unable to reproduce this with the provided example app. I see one request to Cognito when credentials are expired (see screenshot below). This would be expected since new credentials will need to be fetched prior to uploading the file.

Can you confirm that `AWSCognitoIdentityService.GetCredentialsForIdentity` is the value on both of the requests?

Can you also share the version of `amplify_auth_cognito` and `amplify_auth_cognito_dart` from your pubspec.lock file?


<img width="873" alt="Screenshot 2023-11-08 at 12 50 51 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/20613561/2bc105c9-d307-498f-ae63-dff57eec7af4">

**Comment by delfme** [comment]
Thx @Jordan-Nelson 
```
var startTime = DateTime.timestamp();
    try {
    final resultUrl = await Amplify.Storage.uploadFile(
      key: 'test_amplify/${basename(file.path)})',
      localFile: AWSFile.fromPath(file.path),
      onProgress: (progress) {
        final sent = progress.fractionCompleted * len;
        debugPrint('File upload progress %${progress
            .fractionCompleted} sent $sent of total $len');
      });
      } on StorageException catch (e) {
      safePrint('Error uploading file: $e');
      } finally {
      safePrint('Successfully uploaded file: ${resultUrl}');
      debugPrint('Time elapsed to upload '
          '${DateTime.timestamp().difference(startTime).inMilliseconds}ms');
```
Above lines are still not in the sample code, can you please use them instead of lines 80-96?
https://github.com/delfme/sample_demo_amplify/blob/4ffdd1f798987ebb7d7abd0bbee81d0fdfe5c97d/lib/main.dart#L80-L96
Coz I noticed that progress was not working properly, so I changed the code this other way, which is also what you guys suggest here https://docs.amplify.aws/lib-v1/storage/upload/q/platform/flutter/#upload-a-local-file
But by using above code, I get that wrong logs.


As for cognito auth, I still get the 700ms cognito auth call, it seems I don't get it anymore after forcing await inside main(). It is weird though. Here is where we initialize stuff, I just added await to main.
https://github.com/delfme/sample_demo_amplify/blob/4ffdd1f798987ebb7d7abd0bbee81d0fdfe5c97d/lib/aws/amplify.dart#L10-L19

As for the slowness and upload progress issues, I confirm below points:
1) `progress` and `time elapsed` printed "after" the file is downloaded
2) slow upload for bigger file (check sample with the 10Mb file)
3) only a few progress values given for bigger file (check sample with the 10Mb file)

**Comment by delfme** [comment]
As for point 3) here is the logs when uploading the 2MB file and the 10MB file.

Progress for the 2MB file, looks correct.
```
flutter: File upload progress %0.030526955167261033 sent 65536.0 of total 2146824
flutter: File upload progress %0.061053910334522066 sent 131072.0 of total 2146824
flutter: File upload progress %0.0915808655017831 sent 196608.0 of total 2146824
flutter: File upload progress %0.12210782066904413 sent 262144.0 of total 2146824
flutter: File upload progress %0.15263477583630516 sent 327680.0 of total 2146824
flutter: File upload progress %0.1831617310035662 sent 393216.0 of total 2146824
flutter: File upload progress %0.21368868617082723 sent 458752.0 of total 2146824
flutter: File upload progress %0.24421564133808826 sent 524288.0 of total 2146824
flutter: File upload progress %0.2747425965053493 sent 589824.0 of total 2146824
flutter: File upload progress %0.30526955167261033 sent 655360.0 of total 2146824
flutter: File upload progress %0.3357965068398714 sent 720896.0 of total 2146824
flutter: File upload progress %0.3663234620071324 sent 786432.0 of total 2146824
flutter: File upload progress %0.39685041717439345 sent 851968.0 of total 2146824
flutter: File upload progress %0.42737737234165446 sent 917504.0 of total 2146824
flutter: File upload progress %0.4579043275089155 sent 983040.0 of total 2146824
flutter: File upload progress %0.4884312826761765 sent 1048576.0 of total 2146824
flutter: File upload progress %0.5189582378434375 sent 1114112.0 of total 2146824
flutter: File upload progress %0.5494851930106986 sent 1179648.0 of total 2146824
flutter: File upload progress %0.5800121481779597 sent 1245184.0 of total 2146824
flutter: File upload progress %0.6105391033452207 sent 1310720.0 of total 2146824
flutter: File upload progress %0.6410660585124817 sent 1376256.0 of total 2146824
flutter: File upload progress %0.6715930136797428 sent 1441792.0 of total 2146824
flutter: File upload progress %0.7021199688470038 sent 1507328.0 of total 2146824
flutter: File upload progress %0.7326469240142648 sent 1572864.0 of total 2146824
flutter: File upload progress %0.7631738791815258 sent 1638400.0 of total 2146824
flutter: File upload progress %0.7937008343487869 sent 1703936.0 of total 2146824
flutter: File upload progress %0.8242277895160479 sent 1769472.0 of total 2146824
flutter: File upload progress %0.8547547446833089 sent 1835008.0 of total 2146824
flutter: File upload progress %0.8852816998505699 sent 1900544.0 of total 2146824
flutter: File upload progress %0.915808655017831 sent 1966080.0 of total 2146824
flutter: File upload progress %0.946335610185092 sent 2031616.0 of total 2146824
flutter: File upload progress %0.976862565352353 sent 2097152.0 of total 2146824
flutter: File upload progress %1.0 sent 2146824.0 of total 2146824
```

Progress for the 10MB file, just 3-4 values, and from time to time, long upload time.
```
flutter: File upload progress %0.0 sent 0.0 of total 10504179
flutter: File upload progress %0.001753492586141192 sent 18419.0 of total 10504179
flutter: File upload progress %0.5008767462930706 sent 5261298.999999999 of total 10504179
flutter: File upload progress %1.0 sent 10504179.0 of total 10504179
flutter: File upload progress %1.0 sent 10504179.0 of total 10504179
```

**Comment by delfme** [comment]
One point about the 600-700ms cognito call. It would be nice if you guys could investigate more on that delay. Coz it cannot be network delay (I'm close to region but even if I were in Asia it would be like 250ms). So it should be something that sometimes impact on that api response time. This is why I initially thought that cognito auth was on lamba function. It looked like a cold start.

**Comment by Jordan-Nelson** [comment]
@delfme - I believe you have a second issue open for the issues you are facing around progress upload (https://github.com/aws-amplify/amplify-flutter/issues/4074). Let's use that issue to track those issues and keep this issue focused on the initial issue you were observing which is that fetching credentials is adding a significant amount of time to the initial request.

It sounds like you are no longer getting a duplicate request. As for the 600-700ms request time, I am unable to reproduce that. As you can see in the screenshot that I shared, I am observing this request take ~150ms. What device are you producing that from? What type of connection are you on?

Can you also share the version of amplify_auth_cognito and amplify_auth_cognito_dart from your pubspec.lock file?

**Comment by delfme** [comment]
You right @Jordan-Nelson 
It seems Im no longer getting cognito duplicate calls and we close this issue.
<img width="1065" alt="Screenshot 2023-11-09 at 09 48 05" src="https://github.com/aws-amplify/amplify-flutter/assets/53510751/8ab843d4-67c6-434f-8e8c-3d7dcc34d4d6">

However, there are still those other issues, so I decided to edit my sample repo so that we use official code lines as much as possible and expose the issues separately but with a single sample. Going to add them soon.

**Comment by delfme** [comment]
@Jordan-Nelson I just filed issues as mentioned above. They are 4 and can be tested by using the same sample. I closed the old pending ones.
