### ISSUE TITLE
[Amplify Storage] [uploadFile] progress not working well with medium/large file

### ISSUE THREAD

**Issue by delfme** [aws-amplify/amplify-flutter#4096]
### Description

It seems that progress is not working well when files are not small ones.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

Use sample https://github.com/delfme/sample_demo_amplify

**Configure code before run:**
Add your bucket here
https://github.com/delfme/sample_demo_amplify/blob/076064605de3fbb88f7ba798b372af202537f4ce/lib/main.dart#L53

Configure your amplify settings here
https://github.com/delfme/sample_demo_amplify/blob/main/lib/aws/amplify_configuration.dart

**How to reproduce issue**
1) tap button 1 to download a 2MB image and 10MB video from web
2) tap button 3 to upload video.I can be noticed that only a few progress values are returned
```
flutter: File upload progress %0.0 sent 0.0 of total 10504179
flutter: File upload progress %0.001753492586141192 sent 18419.0 of total 10504179
flutter: File upload progress %0.5008767462930706 sent 5261298.999999999 of total 10504179
flutter: File upload progress %1.0 sent 10504179.0 of total 10504179
flutter: File upload progress %1.0 sent 10504179.0 of total 10504179
```

On the contrary, progress works well with small file and typical logs would be like that:
```
flutter: File upload progress %0.030526955167261033 sent 65536.0 of total 2146824
flutter: File upload progress %0.061053910334522066 sent 131072.0 of total 2146824
flutter: File upload progress %0.0915808655017831 sent 196608.0 of total 2146824
flutter: File upload progress %0.12210782066904413 sent 262144.0 of total 2146824
flutter: File upload progress %0.15263477583630516 sent 327680.0 of total 2146824
flutter: File upload progress %0.1831617310035662 sent 393216.0 of total 2146824
flutter: File upload progress %0.21368868617082723 sent 458752.0 of total 2146824
flutter: File upload progress %0.24421564133808826 sent 524288.0 of total 2146824
flutter: File upload progress %0.2747425965053493 sent 589824.0 of total 2146824
flutter: File upload progress %0.30526955167261033 sent 655360.0 of total 2146824
flutter: File upload progress %0.3357965068398714 sent 720896.0 of total 2146824
flutter: File upload progress %0.3663234620071324 sent 786432.0 of total 2146824
flutter: File upload progress %0.39685041717439345 sent 851968.0 of total 2146824
flutter: File upload progress %0.42737737234165446 sent 917504.0 of total 2146824
flutter: File upload progress %0.4579043275089155 sent 983040.0 of total 2146824
flutter: File upload progress %0.4884312826761765 sent 1048576.0 of total 2146824
flutter: File upload progress %0.5189582378434375 sent 1114112.0 of total 2146824
flutter: File upload progress %0.5494851930106986 sent 1179648.0 of total 2146824
flutter: File upload progress %0.5800121481779597 sent 1245184.0 of total 2146824
flutter: File upload progress %0.6105391033452207 sent 1310720.0 of total 2146824
flutter: File upload progress %0.6410660585124817 sent 1376256.0 of total 2146824
flutter: File upload progress %0.6715930136797428 sent 1441792.0 of total 2146824
flutter: File upload progress %0.7021199688470038 sent 1507328.0 of total 2146824
flutter: File upload progress %0.7326469240142648 sent 1572864.0 of total 2146824
flutter: File upload progress %0.7631738791815258 sent 1638400.0 of total 2146824
flutter: File upload progress %0.7937008343487869 sent 1703936.0 of total 2146824
flutter: File upload progress %0.8242277895160479 sent 1769472.0 of total 2146824
flutter: File upload progress %0.8547547446833089 sent 1835008.0 of total 2146824
flutter: File upload progress %0.8852816998505699 sent 1900544.0 of total 2146824
flutter: File upload progress %0.915808655017831 sent 1966080.0 of total 2146824
flutter: File upload progress %0.946335610185092 sent 2031616.0 of total 2146824
flutter: File upload progress %0.976862565352353 sent 2097152.0 of total 2146824
flutter: File upload progress %1.0 sent 2146824.0 of total 2146824
flutter: File upload progress %1.0 sent 2146824.0 of total 2146824
```
To see it, just upload image (which is a 2MB file) and see that progress will work well in that case.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel master, 3.17.0-1.0.pre.37

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @delfme - The reason that you see less progress updates on the larger file is because a multipart upload is used for files larger than 5mb. This is noted in the docs here: https://docs.amplify.aws/lib/storage/upload/q/platform/flutter/#multipart-upload

For a multipart upload, the file is split into chunks and each chunk is uploaded in parallel. The progress will update after each part uploads. The file you are using happens to be broken into 3 chunks - two of ~5mb and one very small chunk with the rest of the data. The smallest chunk will typically complete first, which is why the first progress report is very small and then the next two jumps are ~50%.

**Comment by Jordan-Nelson** [comment]
Let me know if you have any other questions.

**Comment by delfme** [comment]
Makes sense. Closing this one. Thx
