### ISSUE TITLE
[Amplify Storage] [downloadFile] cannot download file

### ISSUE THREAD

**Issue by delfme** [aws-amplify/amplify-flutter#4098]
### Description

Idk if this is a bug or a mistake with my code, however I cannot download a file after having uploaded it successfully.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [x] Storage

### Steps to Reproduce

Use sample https://github.com/delfme/sample_demo_amplify

**Configure code before run:**
Add your bucket here
https://github.com/delfme/sample_demo_amplify/blob/076064605de3fbb88f7ba798b372af202537f4ce/lib/main.dart#L53

Configure your amplify settings here
https://github.com/delfme/sample_demo_amplify/blob/main/lib/aws/amplify_configuration.dart

**How to reproduce issue**
1) tap button 1 to download a 2MB image and 10MB video from web
2) tap button 2 to upload image
3) tap button 4 to download the image. Error is thrown, see log below.

```
flutter: Download File https://YOUR_BUCKET_NAME.s3.amazonaws.com/public/test_amplify/image.jpg
flutter: File download progress %-0.0
flutter: Error downloading file: StorageKeyNotFoundException {
flutter:   "message": "Cannot find the item specified by the key and access level.",
flutter:   "recoverySuggestion": "Ensure that correct object key is provided, and/or correct `StorageAccessLevel` and `targetIdentityId` are included in the options.",
flutter:   "underlyingException": "NoSuchKey {\n}"
flutter: }
```

NOTE:
1) File is uploaded correctly and it can be opened inside browser if we click the url printed by log. Hence `key` should be correct.
2) I'm using same policy/settings to upload file, hence `AccessLevel` should be correct. 

Is there anything wrong with my code?

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel master, 3.17.0-1.0.pre.37

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @delfme - It looks like the key you are trying to use is `https://$bucket.s3.amazonaws.com/public/test_amplify/video.mp4`. However the file was uploaded with the key `test_amplify/video.mp4`. I was able to get the example to work by updating the key.

I am going to close this issue. Please let us know if you face other issues.

**Comment by delfme** [comment]
That is because I tried different keys, but I still cannot download the file with storage. But I can download it with `dio`, same url. Might it be an issue with my Cognito settings?

**Comment by delfme** [comment]
This is result with Storage
```
flutter: Download File https://mybucket.s3.amazonaws.com/public/test_amplify/image.jpg
flutter: File download progress %-0.0
flutter: Error downloading file: StorageKeyNotFoundException {
flutter:   "message": "Cannot find the item specified by the key and access level.",
flutter:   "recoverySuggestion": "Ensure that correct object key is provided, and/or correct `StorageAccessLevel` and `targetIdentityId` are included in the options.",
flutter:   "underlyingException": "NoSuchKey {\n}"
flutter: }
```

This is result with dio
```
flutter: Download File https://mybucket.s3.amazonaws.com/public/test_amplify/image.jpg
flutter: Progress: 0.0%
flutter: Progress: 2.5957880105681697%
flutter: Progress: 5.841512858063819%
flutter: Progress: 28.03280567014343%
flutter: Progress: 98.87643328004532%
flutter: Progress: 100.0%
flutter: Status: TaskStatus.complete
flutter: Time elapsed to download 3957ms
flutter: File exists?: true
```

I use same url. GET is publicly allowed, this is why I can download with any http request.

**Comment by Jordan-Nelson** [comment]
What key are you using when you get the StorageKeyNotFoundException?

**Comment by delfme** [comment]
This is the key that is printed by log Download:
https://mybucket.s3.amazonaws.com/public/test_amplify/image.jpg

I pass same url to both storage.downloadFile and dio. Dio downloads the file successfully.
It might be issue with accessLevel, not the key.
Im using unauthenticated cognito user. But I can upload files with same config.

**Comment by Jordan-Nelson** [comment]
@delfme - `https://mybucket.s3.amazonaws.com/public/test_amplify/image.jpg` is the url. `test_amplify/image.jpg` is the key. The url and "public" prefix will be added automatically when using Amplify to download the file.

**Comment by delfme** [comment]
@Jordan-Nelson 🤦‍♂️ It was that, I was ofc passing the key, not the url, but I was passing key "public/test_amplify/image.jpg". Thx much for this!
