### ISSUE TITLE
[Amplify Storage] file is uploaded to "public" folder even if bucket's public access is disabled

### ISSUE THREAD

**Issue by delfme** [aws-amplify/amplify-flutter#4101]
### Description

I know this is just configuration issue, but cannot find a solution for it.

<img width="607" alt="Screenshot 2023-11-09 at 16 12 04" src="https://github.com/aws-amplify/amplify-flutter/assets/53510751/5d0d12cd-daf8-41d6-a538-990c1799c590">

If upload with public access enabled, file will be saved inside a default "public" folder.
So if my file path for the key is "test_amplify/image.jpg"
the image will be uploaded to path "public/test_amplify/image.jpg"

If I disable the Public access, files will still be saved to this "public" folder.
How can I prevent Amplify from adding this "public" folder to the path?

As for download, I cannot download files with both Public bucket, issue reported here https://github.com/aws-amplify/amplify-flutter/issues/4098, and private bucket. Error from log is the same.

Inside IAM I have a role for Amplify: `amplify-myId-dev-163006-authRole`
with correct policy for protected, private, public and uploads.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "kms:Decrypt",
                "kms:GenerateDataKey"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/*",
                "arn:aws:s3:::my-bucket163006-dev/protected/${cognito-identity.amazonaws.com:sub}/*",
                "*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

And my bucket policy is 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my-bucket"
        },
        {
            "Sid": "AllObjectActions",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*Object*",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}
```

Can you please help me understand what's the issue?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel master, 3.17.0-1.0.pre.37

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @delfme - Amplify Storage has a concept of access levels (private, protected, and guest) that is distinct from an S3 buckets public access. You can read about Amplify Storage access levels here: https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/

By default the prefix used in S3 is based on the Amplify Storage access level. However, you can customize the prefix. You can read more about that here: https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/#customization

Let me know if you have any other questions.

**Comment by delfme** [comment]
Got it. Will let you know but for now we can close this one. Thx.
