### ISSUE TITLE
classType cannot be found in Amplify generated models for flutter

### ISSUE THREAD

**Issue by mtalhastar** [aws-amplify/amplify-flutter#4104]
I have generated models from amplify cli for flutter app but i want to now get user by id using GraphQL API but when i import the generated model, no classType is found. Please let me know how to fix this and what further i can add to resolve this issue.

![image](https://github.com/aws-amplify/amplify-flutter/assets/75212035/d0e02fe5-11cb-44bb-8f26-27424a65a78e)

**Comment by Jordan-Nelson** [comment]
Hello @mtalhastar - can you share the following:
- The UserType model that is being generated
- Your schema file
- The version of the Amplify CLI you are using

**Comment by mtalhastar** [comment]
I am using Amplify CLI v 2.0
Below are the files as demands:
[files.zip](https://github.com/aws-amplify/amplify-flutter/files/13312626/files.zip)

**Comment by Jordan-Nelson** [comment]
Hello @mtalhastar - Amplify CLI v2 would be quite old (published ~4 years ago). Amplify Flutter is likely not supported in that version. If that is indeed the version you are using could you upgrade to the latest version?

**Comment by mtalhastar** [comment]
Sorry its amplify CLI version 12.7.1

**Comment by Jordan-Nelson** [comment]
It looks like the issue is that UserType is not annotated with `@model`. This will be required for using code gen. See: https://docs.amplify.aws/cli/graphql/data-modeling/

**Comment by Jordan-Nelson** [comment]
Let me know you have any other questions.

**Comment by mtalhastar** [comment]
hey brother should i need to use @model annotation on every type?

**Comment by mtalhastar** [comment]
Thankyou the issue is resolved after adding @model annotation.
