### ISSUE TITLE
Feature Request: Query Predicate Operation: attributeExists

### ISSUE THREAD

**Issue by MarlonJD** [aws-amplify/amplify-flutter#4130]
### Description

Hello, on amplify-flutter there is no attributeExists on where parameters while ModelQueries.list.

I needed this when eq(null) was not enough, If there is no key in dynamodb it gives false result, so we need this attributeExists in these cases.

```
ModelQueries.list(Employee.classType,
            where: Employee.COGNITOID.attributeExists(false));
```

I'm planning to add this, what do you about it?

## Detailed Example Use Case, why we need this?

```
Post(title: "Lorem ipsum", blog: null, ...)
```

we want to list posts with no blogs assigned, if belongsTo model was null, in dynamoDB there wouldn't be any attribute. So if we try to list this:

```
final req = ModelQueries.list(
  Post.classType,
  where: Post.BLOG.eq(null),
  limit: _limit,
);
```

it won't give us right results. it should've customized document and variables for this.

This feature allow us to do this.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by MarlonJD** [comment]
I just add #4134 for this issue

**Comment by Equartey** [comment]
@MarlonJD Awesome, thanks for opening a pull request! 

We need to review this internally before we can take your changes. Will provide updates as I have them.

**Comment by MarlonJD** [comment]
@Equartey I can clone and try to pass tests, I was did some online GitHub checks quickly then tests not working for now

**Comment by Equartey** [comment]
@MarlonJD No need, tests are not the issue. We need to review the implementation to ensure it doesn't collide with DataStore category.

**Comment by MarlonJD** [comment]
@Equartey yes, that's true, I didn't test datastore side, okay than I'll wait your response about it, thanks.

**Comment by Equartey** [comment]
@MarlonJD apologies for the delay. Your feature work has been merged 🎉  

We will let you know when its released and available. Thanks again for your contribution, it's highly appreciated!

**Comment by MarlonJD** [comment]
@Equartey Thanks for your corrections on the PR, you did great work for datastore and tests, I'm happy that it's merged. 🎉

**Comment by Jordan-Nelson** [comment]
This was added in Amplify Flutter v2 which was released a couple weeks ago. There were some breaking changes in this version. Please see [the upgrade guide](https://docs.amplify.aws/gen1/flutter/start/project-setup/upgrade-guide/) for more info.

@MarlonJD Thanks for opening the issue and your contributions!
