### ISSUE TITLE
OIDC support by amplify_flutter - Question

### ISSUE THREAD

**Issue by xenowits** [aws-amplify/amplify-flutter#414]
Does amplify_flutter support OIDC(OpenId connect) now? If yes, how do we use it?
Any help is very much appreciated!
Thanks in advance.

**Comment by haverchuck** [comment]
@xenowits I am marking this as a feature request.  Are you hoping to use OIDC with Cognito Hosted UI or with Cognito Identity Pools, or a different use case?

**Comment by xenowits** [comment]
@haverchuck thanks for replying. Actually, I am hoping to use firebase as the IdProvider. I wish to add firebaseToken as the default authorization method in AWS Appsync. We are heavily using the amplify_flutter library and were wondering if there's a way to send firebaseToken with each GraphQL request.

**Comment by haverchuck** [comment]
We don't currently support this, but we are actively investigating  adding support.  We will keep this issue open, so please check back.

**Comment by xenowits** [comment]
Sure thanks @haverchuck

**Comment by xenowits** [comment]
Any updates on this?

**Comment by jamesmoore255** [comment]
Any updates on this?

**Comment by abdallahshaban557** [comment]
OIDC is now supported! Thank you for opening this feature request!
