### ISSUE TITLE
SWIFT TASK CONTINUATION MISUSE on signInWithWebUI IOS

### ISSUE THREAD

**Issue by koebelt** [aws-amplify/amplify-flutter#4141]
### Description

Im Using `amplify_auth_cognito: ^1.6.0`  on a IOS/Android project. My code using signInWithWebUI with google was working fine a few days ago. but now I get the error : `SWIFT TASK CONTINUATION MISUSE: launchUrl(_:callbackURLScheme:preferPrivateSession:) leaked its continuation!` on my IOS17 iPhone 15 emulator.
When `isPreferPrivateSession: true`, it stills opens the modal but after entering my informations, the page loads indefinitely, or, when it is set on `false` it only briefly shows the popup before disappearing. without throwing an error

Note: Its still works on my IOS TestFlight beta build which has `amplify_auth_cognito: ^1.4.2`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.4

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @koebelt, sorry to hear you've ran into this issue. 

We will investigate and try to reproduce on our end. 

Have you tried reproducing the error on previous versions of xcode or ios?

**Comment by koebelt** [comment]
No, but this error appeared independently from a new Xcode or IOS version

**Comment by cmj0121** [comment]
Have the same issue on my iPhone SE (17.1.1)

**Comment by NikaHsn** [comment]
@koebelt @cmj0121 can you please confirm that your Xcode project has its minimum deployment version set to 13.0.
![image](https://github.com/aws-amplify/amplify-flutter/assets/6644919/4ea48f63-c690-4eb6-92ae-8d6b2d128335)
![image](https://github.com/aws-amplify/amplify-flutter/assets/6644919/18167172-f6b2-4963-aca1-13c9f2bf2471)

**Comment by koebelt** [comment]
Yes, The minimum ios version is IOS 13.0

**Comment by cmj0121** [comment]
@NikaHsn Unexpectedly the issue is gone without modifying my code. I guess the iPhone's auto-upgrade solves this issue in my case.

**Comment by NikaHsn** [comment]
@cmj0121 thanks for the update and glad to hear the issue is fixed for you. 
@koebelt can you confirm the Podfile is correctly set to 13.0? we've seen this issue being related to ios version, have you tried to reproduce the issue on other ios versions? can you please provide stack trace/logs?

**Comment by koebelt** [comment]
For me the problem fixed itself 5 days ago, no changes in IOS related files. Also Podfile is set to 13.0

**Comment by NikaHsn** [comment]
@koebelt glad to hear the problem is fixed for you, do you think it was fixed because of ios or xcode version upgrade/downgrade?
@bagusherdi can you share the output of `flutter doctor -v`? also please check that the Xcode project has its minimum deployment version set to 13.0 and same for Podfiles.
there are some issue related to running flutter apps on ios after upgrading to xcode 15: flutter/flutter#130819,
flutter/flutter#136060 in case you find them relevant.

**Comment by pauloeduardoferreira** [comment]
TWO DAYS STRUGGLING WITH IT! Thanks @NikaHsn!

**Comment by airon-tark** [comment]
ONE DAY STRUGGLING WITH IT! Thanks @NikaHsn!
