### ISSUE TITLE
The specified item could not be found in the keychain code -25300

### ISSUE THREAD

**Issue by EllisMatusica** [aws-amplify/amplify-flutter#4146]
### Description

After a recent mac update to macOS 14.1.1, i began receiving the following exception as soon as i run the app on any physical device:

`ItemNotFoundException (SecureStorageException(message: Them item was not found in the keychain., recoverySuggestion: An unknown exception occurred. 
Please take a look at https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't., underlyingException: SecurityFrameworkError: {code: -25300, message: The specified item could not be found in the keychain.}))`

This is occurring before my Sign in page loads on app start. The sign in page uses the amplify prebuilt `Authenticator` Sign in page. 
Any guidance is greatly appreciated.

Amplify package versions:
`amplify_auth_cognito: ^1.0.0`
`amplify_flutter: ^1.0.0`
`amplify_datastore: ^1.0.0-supports-only-mobile`
`amplify_api: ^1.0.0`
`amplify_storage_s3: ^1.0.0`
`amplify_authenticator: ^1.0.0`

Flutter version:
3.10.5

 Devices tested on:
 iPhone 12 running iOS 17.1.1, 
 iPhone 7 running iOS 14.5.1, 
 iPhone X running iOS 15.7.

edit: After some more testing I've found that the app crashes in debug mode as soon as the `Authenticator` widget is built in android and iOS. However on Android i get the error: `Unauthenticated access is not supported for this identity pool` immediately before sign in page appears. What does work is using `flutter run` in terminal and running it that way, still not sure what the cause of these errors are.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by delwinbest** [comment]
Hi don't think this is related to OSX nor a physical phone; I'm able to repro this issue when moving from amplify_authenticator 1.5.1 to anything >1.6.0. Physical and iPhone simulator.

I have not been able to find a work around as any version < 1.6.0 runs into build issues with smithy. Please help!

**Comment by delwinbest** [comment]
I'm getting this on simulator for iOS development as well. I've enabled keychain sharing in xCode.

The issue does **not** occur when building and running from Flutter or xCode **without debug** - it does happen as soon as I run in debug mode. 

ItemNotFoundException (SecureStorageException(message: Them item was not found in the keychain., recoverySuggestion: An unknown exception occurred. 
Please take a look at https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't., underlyingException: SecurityFrameworkError: {code: -25300, message: The specified item could not be found in the keychain.}))

**Comment by delwinbest** [comment]
I spent some time with the folks from AWS (thank you!) but neither of us could recreate the issue on a clean flutter app with boiler plate code. I did notice some extended attributes (com.apple.provenance ) on the new boiler plate folder and updated instructions in getting setup here pertaining to keyChain sharing in xCode: https://pub.dev/packages/amplify_authenticator/example

I do not know what caused this but what ended up working after trying to rebuild the app was:
1. clean check out of my repo 
2. sudo xattr -dr com.apple.provenance REPO_FOLDER
3. cd REPO_FOLDER; amplify pull
4. Follow https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/#enable-keychain to ensure build target is ios 13.0 and keychain sharing is now enabled in xCode. 
5. flutter clean; flutter pub get

This resolved the issues for me - would love to know why.

**Comment by EllisMatusica** [comment]
> I spent some time with the folks from AWS (thank you!) but neither of us could recreate the issue on a clean flutter app with boiler plate code. I did notice some extended attributes (com.apple.provenance ) on the new boiler plate folder and updated instructions in getting setup here pertaining to keyChain sharing in xCode: https://pub.dev/packages/amplify_authenticator/example
> 
> I do not know what caused this but what ended up working after trying to rebuild the app was:
> 
> 1. clean check out of my repo
> 2. sudo xattr -dr com.apple.provenance REPO_FOLDER
> 3. cd REPO_FOLDER; amplify pull
> 4. Follow https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/#enable-keychain to ensure build target is ios 13.0 and keychain sharing is now enabled in xCode.
> 5. flutter clean; flutter pub get
> 
> This resolved the issues for me - would love to know why.

The issue went away once i did a clean repo checkout, still not sure why, thank you for the help !

**Comment by khatruong2009** [comment]
Hi @EllisMatusica, I'm glad that the issue was resolved. To get more information, can you confirm in your `pubspec.lock` file which flutter version you have there?

**Comment by EllisMatusica** [comment]
> Hi @EllisMatusica, I'm glad that the issue was resolved. To get more information, can you confirm in your `pubspec.lock` file which flutter version you have there?

`flutter: ">=3.10.0"`

**Comment by khatruong2009** [comment]
Hi @EllisMatusica and @delwinbest, I'm going to close this issue now. Let us know if any other issues come up.

**Comment by delwinbest** [comment]
Hi Folks - issue reappeared today and I'm no longer able to debug via VSCode. 'flutter run' works. I've completely reinstalled flutter, the git repo, Xcode code and cleared ~/.flutter and ~/.dart caches. Can't seem to get this working.

Why would it only happen during debug?

**Comment by zhoulijun12315** [comment]
i have the same issue in MacOS14.1 、 Xcode 15.2.

**Comment by eliast96** [comment]
I'm encountering this issue too, any solution to this?

**Comment by Jordan-Nelson** [comment]
@delwinbest @zhoulijun12315 @eliast96 - if you are still experiencing this can you open a new issue so we can capture reproduction steps and other information about your environment? Thank you.

**Comment by fernandovargascabrera** [comment]
Hi @delwinbest, were you able to find a solution to this?

**Comment by gornypiotr** [comment]
I'm getting the same error while running on iOS.

amplify_auth_cognito: ^2.5.0
amplify_authenticator: ^2.3.1
amplify_flutter: ^2.5.0

Flutter version: 3.27.0
