### ISSUE TITLE
[Question] How to add caching to Amplify.API.get ?

### ISSUE THREAD

**Issue by fvisticot** [aws-amplify/amplify-flutter#4147]
### Description

How to add caching to Amplify.API.get ?
Is there a documentation available ?

```
final restOperation=Amplify.API.get('users/$id',
          apiName: "users");
final response = await restOperation.response;
```

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.16

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @fvisticot, we currently do not support caching for API.
