### ISSUE TITLE
Feature Request: Support the use of custom storage paths

### ISSUE THREAD

**Issue by exampaqs** [aws-amplify/amplify-flutter#416]
## Updated Description
Feature Request: The ability to specify a custom prefix for S3 storage, instead of using the public/protected/private prefixes. For reference, see feature requests and docs in other Amplify libraries.
- Amplify-iOS feature request: https://github.com/aws-amplify/amplify-ios/issues/916
- Amplify-Android feature request: https://github.com/aws-amplify/amplify-android/issues/910
- Amplify-JS docs: https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js/#customization

## Original Description
Amplify.Storage.list() is showing empty list of items when used with existing buckets

**Comment by haverchuck** [comment]
@exampaqs How have you configured the ACL on the existing bucket?

**Comment by exampaqs** [comment]
First all public access to Bucket is blocked and the Bucket permission reads "Only authorized users of this account"

Second I have added a bucket permission like this
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::{BUCKET-NAME}/*"
        }
    ]
}

and the Auth and UnAuth Roles of the Iam user each have a policy configured like:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::{BUCKET-NAME}"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::{BUCKET-NAME}/*"
        }
    ]
}

but few hours ago, i created a folder in the bucket and named it 'public'. then i could only access objects in this public folder but do not have access to other objects in the bucket.

**Comment by smerchermek** [comment]
I have the same problem when trying to access an existing bucket, Amplify.Storage.list () returns an empty list.
The configuration is good, I can access the list of my objects in my bucket from the command line

**Comment by smerchermek** [comment]
I have the same problem while accessing the objects in my bucket, I can only access objects inside "public" folder.
Amplify is well configured and I have access to my bucket using Command Line

**Comment by Jordan-Nelson** [comment]
Hello @exampaqs - It sounds like what you are looking for is the ability to specify a custom prefix, instead of using the public/protected/private prefixes. This is not something that is currently supported. I will mark this as a feature request to track interest.

For reference, this has been requested for iOS and Android as well.
- iOS request: https://github.com/aws-amplify/amplify-ios/issues/916
- Android request: https://github.com/aws-amplify/amplify-android/issues/910

**Comment by hackrx** [comment]
any updates on this?

**Comment by dospringer** [comment]
@hackrx In iOS the problem has been fixed: https://github.com/aws-amplify/amplify-ios/issues/916

**Comment by Elviron** [comment]
@hackrx This has been fixed in android now: [aws-amplify/amplify-flutter#1257](https://github.com/aws-amplify/amplify-flutter/issues/1257)

**Comment by jack24254029** [comment]
How can I get file without prefix?

**Comment by loganSims** [comment]
Just adding my vote for this feature.

**Comment by gb1849** [comment]
This is basic, super needed, really dont understand how they decided to put the resources in mandatory-predefined folders. It has literally no sense....

**Comment by abdallahshaban557** [comment]
Hi @gb1849  - we are working on enabling this feature in a future iteration of our storage category. Can you please elaborate a bit more on what your use case is? How would you like to control your folders for your app?

**Comment by AthreshK** [comment]
Hi @fjnoyp, Is this feature added? if not by when can we expect this to be rolled out?

**Comment by fjnoyp** [comment]
Hi @AthreshK this feature is merged and will be included in our next release.

**Comment by AthreshK** [comment]
> Hi @AthreshK this feature is merged and will be included in our next release.

That's great! thank you very much for the feature addition! Hoping to see the documentation with it.

**Comment by fjnoyp** [comment]
We have a docs PR on the way as well.  Thanks for the pointer @AthreshK 

https://github.com/aws-amplify/docs/pull/4593

**Comment by ragingsquirrel3** [comment]
This was released with version 0.6.9.

**Comment by ragingsquirrel3** [comment]
I'm going to close this issue but please comment here or open new issue if there are any issues with use after upgrading to latest version.
