### ISSUE TITLE
uuid dependency

### ISSUE THREAD

**Issue by tigrenok00** [aws-amplify/amplify-flutter#4162]
### Description

Hi,
I have other packages which depend on latest versions of uuid, but the constraint for amplify_flutter 1.6.0 is uuid >=3.0.6 <=3.0.7 (current version is 4.2.1).
I need uuid ^4.0.0 specifically. 
Can you update the constraint please?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.16.0

### Amplify Flutter Version

1.6.0

**Comment by pixnbit** [comment]
I was going to fill the same ticket, basically got stuck at UUID v3. Some of other libraries can't update because of this.

**Comment by xonaman** [comment]
+1

**Comment by Berkay-ZERO** [comment]
+1

**Comment by NikaHsn** [comment]
sorry that you are facing this problem, the latest version has breaking changes for us and we are working on it.

**Comment by Berkay-ZERO** [comment]
> sorry that you are facing this problem, the latest version has breaking changes for us and we are working on it.

Can you estimate approximately how long it might take?

**Comment by NikaHsn** [comment]
Closing this issue as the latest version of Amplify Flutter libraries support uuid 4.
