### ISSUE TITLE
Error: No AWSAccessKey was presented

### ISSUE THREAD

**Issue by exampaqs** [aws-amplify/amplify-flutter#417]
I have a code like this in my project:

//fetching object url
final GetUrlResult imageUrl = await Amplify.Storage.getUrl(key: urlKey);

//In a widget
return StreamBuilder(
        // 1
        stream: imageUrl.url,
        builder: (context, snapshot) {
          // 2
          if (snapshot.hasData) {
            // 3
            if (snapshot.data.length != 0) {
              return GridView.builder(
                  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 1),
                  // 4
                  itemCount: snapshot.data.length,
                  itemBuilder: (context, index) {
                   
                    return CachedNetworkImage(
                      imageUrl: snapshot.data,
                      fit: BoxFit.cover,
                      placeholder: (context, url) => Container(
                        alignment: Alignment.center,
                        child: CircularProgressIndicator(),
                      ),
                    );
                  });
            } else {
              // 5
              return Center(child: Text('No images to display.'));
            }
          } else {
            // 6
            return Center(child: CircularProgressIndicator());
          }
        });

but I get this error from CachedNetworkImage HttpException: Invalid statusCode: 404

and when i pasted the returned url in my browser, i got this response:
<Error>
<Code>AccessDenied</Code>
<Message>No AWSAccessKey was presented.</Message>
</Error>

**Comment by haverchuck** [comment]
@exampaqs How have you configured the bucket ACL? Is the object you are trying to reach configured for public access?
