### ISSUE TITLE
iOS "No plugin found for awsS3StoragePlugin" but works in Android

### ISSUE THREAD

**Issue by nathcakes** [aws-amplify/amplify-flutter#4175]
### Description

When running my flutter app on an iOS device (iOS 16) I'm getting the following error during startup: 

``[Amplify] No plugin found for configuration key `awsS3StoragePlugin`. Add a plugin for that key.``

This prevents me from using S3 services in my code. I do not get this error when running on Android devices and I'm able to successfully upload to the S3 bucket using an Android device. I can't reproduce the error in a entirely fresh project so I assume somethings changed in my configuration, any help would be appreciated.

I tried removing the s3 storage, pushing the change, importing the s3 bucket and pushing again and this did not resolve the error. I have previously run my application on the same device with no errors, but it's been about a month since I last tested on an iOS device. 

I setup my configureAmplify as follows: 
```
  Future<void> _configureAmplify() async {
    try {
      final auth = AmplifyAuthCognito();
      final storage = AmplifyStorageS3();
      final datastorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
      final api = AmplifyAPI();
      await Amplify.addPlugins([auth, storage, datastorePlugin, api]);
      await Amplify.configure(amplifyconfig);
    } on Exception catch (e) {
      safePrint("An error occurred configuring Amplify: $e");
    }
  }
```

My amplifyconfiguration.dart contains the following plugin information: 
```
"storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "BUCKET_NAME",
                "region": "ap-southeast-2",
                "defaultAccessLevel": "guest"
            }
        }
    }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@nathcakes I cant see problem with the s3 storage plugin info in the amplifyconfiguration.dart. can you share the stack trace. have you tried deleting the the `amplifyconfiguration.dart` and run `amplify pull`?

**Comment by khatruong2009** [comment]
Hi @nathcakes, since this issue isn't affecting the functionality of your S3 plugin, I'm going to close this issue now. If this issue starts to affect data being uploaded/downloaded to/from S3, please feel free to reopen this issue, thanks.
