### ISSUE TITLE
AWS Datastore sync stops when iPhone is locked

### ISSUE THREAD

**Issue by stephenjen** [aws-amplify/amplify-flutter#4193]
### Description

When run on a physical iPhone, during the initial sync after login, sync stops if the phone becomes locked, and only continues when the phone is unlocked.  In the simulator, during the initial sync after login, sync continues even if the phone becomes locked, and the app can complete the sync while the phone is locked.

Is this something to do with background refresh in iOS?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.0

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @stephenjen, I'm coming up with a similar reproduction of this issue but not exactly as you described. What I'm doing is:

1. Signing in on the flutter app on my physical iPhone. 
2. Locking the phone as soon as the sign in succeeds
3. The initial sync does not happen
4. I unlock the phone and the initial sync still doesn't happen
5. I query or send a mutation and only then will the initial sync begin. 

Have you been encountering this as well or am I missing something in the reproduction?

**Comment by stephenjen** [comment]
It is similar, except when I unlock the phone the sync resumes.  I have a listener for Datastore events.

This bug only occurs on physical device.  Sync doesn't get interrupted on the simulator.

**Comment by khatruong2009** [comment]
Hi @stephenjen, ok it turns out, for me, I forgot to put the `await Amplify.DataStore.start()` call in my `_configureAmplify()` method but now that I have that in there, I'm unable to reproduce the issue now. I used Network Link Conditioner to slow down my network so that the initial sync would happen more slowly. I locked the phone while the sync was in progress and it was still able to complete. Am I missing a step in my reproduction?

**Comment by stephenjen** [comment]
The only difference is when sync starts I set a listener to check on the status of the sync, and when the sync get to 'ready' status, I navigate user to another screen.  Is this similar to how you're able to determine if sync has completed?

Of note is lock screen pauses sync only on a physical device and not in the simulator.  Could this have something to do with background refresh?

**Comment by khatruong2009** [comment]
Hi @stephenjen, I am using this in my listener that gets called after my `_configureAmplify` method:

```dart
Amplify.Hub.listen(HubChannel.DataStore, (hubEvent) {
      print('DataStore event: ${hubEvent.eventName}, ${hubEvent.payload}');
}
```
When testing on my physical device, I see the sync start, lock my phone, and then the sync still seems to complete for me. I have background app refresh turned on in my phone, not sure if that makes a difference or not.

**Comment by stephenjen** [comment]
Ok, I'll give this a try

**Comment by khatruong2009** [comment]
Hi @stephenjen, I wanted to follow up to see if you were still having this issue. I still haven't been able to reproduce this on my end.
