### ISSUE TITLE
Can not generate models without @model directive

### ISSUE THREAD

**Issue by dajojo** [aws-amplify/amplify-flutter#420]
**Describe the bug**
In my schema I want to nest a model into another without using an additional table.
'Amplify codegen models' outputs no errors but does only create empty files for models without @model directive. The generated flutter code for the other models is invalid aswell since some model classes are missing but referenced. 

**To Reproduce**

1. Enter schema:
```
type Parent @model {
	id: ID! 
	children: [Child] 
} 

type Child {
	id: ID! 
	content: String
}
``` 

2. Run 'amplify codegen models'
3. See missing classes

**Expected behavior**
Proper generation for missing classes

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by kjones** [comment]
Putting another vote in here to get this fixed. #260 is where I'm at.

**Comment by fjnoyp** [comment]
Thanks for linking the issues @kjones 

Currently this is not supported @dajojo as we do not generate the dart class for non model classes defined in your schema and have no support for them in our code.  We will investigate fixing this missing feature and provide more details in the above linked issue #260.

**Comment by fjnoyp** [comment]
@dajojo as this issue is the same as #260 do you mind if we close this issue so we can keep the issue consolidated?

**Comment by dajojo** [comment]
@fjnoyp Thanks for the fast reply!
I would appreciate this feature since it is very important for using a NoSQL database correctly.
Closed for duplication
