### ISSUE TITLE
Increase package_info_plus version to 5.0.1 in amplify_analytics_pinpoint

### ISSUE THREAD

**Issue by ngoc-quoc-huynh** [aws-amplify/amplify-flutter#4211]
### Description

I'm currently using amplify_auth_cognito: ^1.6.0 and tried to update package_info_plus to the new version ^5.0.1, but I receive the following error:
```
Because no versions of amplify_auth_cognito match >1.6.0 <2.0.0 and amplify_auth_cognito 1.6.0 depends on amplify_analytics_pinpoint >=1.6.0 <1.7.0, amplify_auth_cognito ^1.6.0 requires amplify_analytics_pinpoint >=1.6.0 <1.7.0.
And because amplify_analytics_pinpoint >=1.1.1 depends on package_info_plus ^4.0.1, amplify_auth_cognito ^1.6.0 requires package_info_plus ^4.0.1.
So, because justlaw depends on both amplify_auth_cognito ^1.6.0 and package_info_plus ^5.0.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on package_info_plus: flutter pub add package_info_plus:^4.2.0
```

There is already a [PR](https://github.com/aws-amplify/amplify-flutter/pull/4164) for this.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a new project
2. Add amplify_auth_cognito: ^1.6.0 to pubspec.yaml
3. Add package_info_plus: ^5.0.1 to pubsec.yaml
4. Run flutter pub get

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.2

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by haverchuck** [comment]
This was resolved in the latest release of amplify flutter.
