### ISSUE TITLE
upgrade to new amplify_storage_s3 1.6.0 upload file  access denied 

### ISSUE THREAD

**Issue by ahmad-moblers** [aws-amplify/amplify-flutter#4213]
### Description

i am using this old code v0 to upload file and pass targetIdentityId
```dart
 await Amplify.Storage.uploadFile(
        local: file,
        key: "uploads/$fileName",
        options: S3UploadFileOptions(
          accessLevel: StorageAccessLevel.private,
          targetIdentityId: customUid,
        ),
      );
```
      
in the new sdk v1 i am using 
```dart
       final awsFile = AWSFile.fromPath(file.path);
      final uploadResult = await Amplify.Storage.uploadFile(
        localFile: awsFile,
        key: "uploads/$fileName",
        options: const StorageUploadFileOptions(
          accessLevel: StorageAccessLevel.private,

        ),
      ).result;
```
i am getting access denided my question how i can pass "targetIdentityId" when upload file in the new sdk?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.10.6

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @ahmad-moblers, are you setting up your backend to have a custom `targetIdentityId` for objects uploaded to your S3? Thank you for providing a solution for other developers that encounter this. If there's no further concern, I'm going to close the issue.
