### ISSUE TITLE
Support request: Datastore for Web

### ISSUE THREAD

**Issue by BrandowBuenos** [aws-amplify/amplify-flutter#4223]
Hello, everyone. I have an app in which Amplify has been working extremely well. However, I need to develop the web version and I just wanted to port the existing app to the web, but the datastore is not supported yet. Is there any way to use it nonetheless? If not, is there a timeline for adding this support to the datastore library?

**Comment by cwomack** [comment]
Hello, @BrandowBuenos 👋.  We appreciate you opening this issue and will point you towards the [open Request for Comments (RFC)](https://github.com/aws-amplify/amplify-flutter/issues/3180) specifically for this feature request! To ensure we're capturing all feedback tied to DataStore support for web, we'll consolidate this issue into the RFC and close this.  Please provide any comments or feedback in the open RFC.
