### ISSUE TITLE
`SignedOutException` on platform Linux when using the Amplify Authenticator UI

### ISSUE THREAD

**Issue by rivertam** [aws-amplify/amplify-flutter#4228]
### Description

I've followed the tutorial at https://docs.amplify.aws/flutter/start/getting-started/, using the `Authenticator` UI component. Signing up and the following log in worked fine in the sense that the account was created, email verification worked, typing the wrong password prompts an "Incorrect username or password" toast, etc. However, once I sign in and can access the application, the console shows a failure:

```
UnknownException {
  "message": "unable to send GraphQLRequest to client.",
  "underlyingException": "SignedOutException {\n  \"message\": \"No user is currently signed in\"\n}"
}
```

and any mutations or queries give the same issue back.

Context: Using `flutter run` prompts the question of whether I'd like to run on "Linux" or "Chrome" (as I don't currently have the mobile workflows set up). I'm running through "Linux". When I run through "Chrome", authentication works and I'm able to add and see `BudgetEntry`s.

I should also add that I am on WSL2 on Windows 11.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Follow the tutorial at https://docs.amplify.aws/flutter/start/getting-started/ on WSL without setting up mobile workflows
2. `flutter run` and select Linux
3. Sign up for an account
4. Restart `flutter run` and select Linux again
5. Sign into the same account

### Screenshots

![image](https://github.com/aws-amplify/amplify-flutter/assets/4165105/2821fdc5-09e1-485c-8ad9-a40b580d8b80)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [X] Linux

### Flutter Version

3.16.2

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type BudgetEntry @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
  description: String
  amount: Float!
}
```

**Comment by Jordan-Nelson** [comment]
Hello @rivertam - Thanks for taking the time to open the issue.

1. Are you using Ubuntu on WSL2?
2. Is libsecret installed (should be able to run `dpkg -l | grep libsecret` to check)?
3. Do auth operations such as fetchUserAttributes() work as expected?

**Comment by rivertam** [comment]
1. Yes
2. Yes, installed through apt
3. No they don't. I believe that's one of the calls that the errors were coming from. I have however abandoned this project and my computer is having a PSU issue, so even if I wanted to replicate I can't for a few weeks unfortunately.

**Comment by Jordan-Nelson** [comment]
Okay. If auth operation are not working as expected my guess would be there is an issue with how credentials are stored. This could be an issue specific to WSL2. I don't have a machine set up to test this on. If you pick this project up again I think the next step would be to see if values are getting stored correctly by libsecret. I believe you should be able to view them in passwords and keys.

I am going to close this since we don't have a way to troubleshoot this further, but if you pick this project up (or another amplify project) we can reopen this and continue troubleshooting.
