### ISSUE TITLE
Flutter Amplify IoT Support

### ISSUE THREAD

**Issue by PRenouf** [aws-amplify/amplify-flutter#425]
Hi,

Could anyone point me in the direction of any guides/documentation for using AWS IoT Core Pub/Sub within flutter.

I believe it is not currently supported as part of Amplify and [aws_iot 0.1.0 ](https://pub.dev/packages/aws_iot) is not compatible  with Amplify pods.

Cheers,

**Comment by fjnoyp** [comment]
Hi @PRenouf 

Thanks for bringing this missing feature to our attention.

We currently do not have any Amplify IoT Support within Flutter.  Providing support is a bit tricky as the underlying Amplify native libraries which Amplify Flutter is built on do not provide this functionality as well. 

Let's keep this issue open as a feature-request so that other community members can comment here.

**Comment by tehokang** [comment]
Hi, @fjnoyp 

Same here wishing support AWS IoT Core functionalities from flutter. 
Currently we've been using mqtt client via pub.dev to connect/publish/subscribe with certificate and private key in mobile application, by the way we've concerning this if this could make security issues and registration issue on app store.

Actually we're going to have to make a decision about above situation whether you keep using certificate and private key in mobile app or find another way. 
According to above reply, I understand that unfortunately there is not any plan to support IoT yet.

Thanks for reading,

**Comment by PRenouf** [comment]
This is my current (WIP) plan for anyone interested:

I've settled with storing data, from the app, in a dynamoDB database using the Amplify AP. I then plan to use lambda functions to update the database with information as it arrives from IoT Core. 

I not handling large quantities of data, and I will need to store it anyway, so I don't think this solution is too bad.  It's then dependant on user by user authentication performed by Cognito.

**Comment by MohammedNoureldin** [comment]
This is sad that I keep checking open issues every week to check if the missing features I need are coming any soon for Flutter. This is of course one of them.

**Comment by MohammedNoureldin** [comment]
@PRenouf have you managed somehow to use IoT in Flutter using Cognito authentication?

**Comment by PRenouf** [comment]
@MohammedNoureldin I'm not sure what your question is. If you're wanting to set up Cognito authentication for an app user please check this tutorial: https://www.youtube.com/watch?v=x8xEkNCd3Vg&t=4s

**Comment by MohammedNoureldin** [comment]
@PRenouf, thank you for your answer. I was not asking how to use Cognito itself, but how to use it to authenticate AWS IOT, but I already found some resources, but it is really a pain procedure, we need to do a lot of manual work to get that working.

**Comment by dnys1** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-flutter/issues/1006, which is more general. Please follow that ticket for the latest updates.

**Comment by amizer12** [comment]
+1 from me as well, using mqttclient with SigV4 urls is way to much just to authenticate. Iot is fueled by mobile and flutter is already gaining a momentum so i think this is a VERY much needed in order to increase Amplify consumption.
