### ISSUE TITLE
[Question] GraphqlAPI decodePath attribute when getting a list of objects

### ISSUE THREAD

**Issue by fvisticot** [aws-amplify/amplify-flutter#4278]
### Description

From the documentation:
https://docs.amplify.aws/flutter/build-a-backend/graphqlapi/advanced-workflows/

In the documentation we get an object by Id and decode the object with the decodePath.

I'm using a graphQLDocument to get a list of objects as an output
How to specify the decodePath ? (.items)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.3

### Amplify Flutter Version

12.8.2

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type PostRating @model @auth(rules: [{allow: public}, {allow: owner}]) {
  id: ID!
  postId: ID!
  post: Post @hasOne(fields: ["postId"])
  rating: Float! 
  votes: Int!
  status: ReviewStatus!
  lastRatingDate: AWSDateTime!
}
```

**Comment by Equartey** [comment]
Hi @fvisticot, here is an example of a custom list operation with decoding. 

```dart
const listTodo = 'listTodo';
const graphQLDocument = '''query ListTodo {
  $listTodo {
    items {
      id
      name
    }
  }
}''';
final getTodoRequest = GraphQLRequest<PaginatedResult<Todo>>(
  document: graphQLDocument,
  modelType: Todo.classType,
  decodePath: listTodo,
);
```

Please reach out if you have additional questions.
