### ISSUE TITLE
Unable to  build app {Execution failed for task ':amplify_analytics_pinpoint:compileReleaseKotlin'.}

### ISSUE THREAD

**Issue by pranavo72bex** [aws-amplify/amplify-flutter#4289]
### Description

` ext.kotlin_version = '1.8.0'`
 
    ```
     classpath 'com.android.tools.build:gradle:7.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.0'
```

`> Configure project :app
WARNING:API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.`

`e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (8, 8): Unresolved reference: io
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (10, 39): Unresolved reference: FlutterPlugin
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (20, 5): 'onAttachedToEngine' overrides nothing
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (20, 46): Unresolved reference: FlutterPlugin
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (22, 43): Cannot access class 'BinaryMessenger'. Check your module classpath for missing or conflicting dependencies
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (25, 5): 'onDetachedFromEngine' overrides nothing
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (25, 48): Unresolved reference: FlutterPlugin
e: /Users/pranav.jha/.pub-cache/hosted/pub.dev/amplify_analytics_pinpoint-1.6.2/android/src/main/kotlin/com/amazonaws/amplify/amplify_analytics_pinpoint/AmplifyAnalyticsPinpointPlugin.kt: (26, 43): Cannot access class 'BinaryMessenger'. Check your module classpath for missing or conflicting dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amplify_analytics_pinpoint:compileDebugKotlin'.
> Compilation error. See log for more details`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![Screenshot 2023-12-28 at 16 29 33](https://github.com/aws-amplify/amplify-flutter/assets/71395812/e4e2e8b8-578a-4c08-9323-305b75fe6d82)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.3

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @pranavo72bex thanks for sharing your issue.  Why are you setting your kotlin version to 1.8.0?  Currently Amplify Flutter is only compatible with kotlin 1.7.10

**Comment by pranavo72bex** [comment]
> Hi @pranavo72bex thanks for sharing your issue. Why are you setting your kotlin version to 1.8.0? Currently Amplify Flutter is only compatible with kotlin 1.7.10

i also tried with kotlin version 1.7.0 and its not working

**Comment by pranavo72bex** [comment]
`_$hubSubscription = Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
      switch (hubEvent.eventName) {
        case "SESSION_EXPIRED":
          ref.read(authProvider.notifier).logOutUser();
          break;
        case "SIGNED_OUT":
          ref.read(authProvider.notifier).signOutCleanup();
          break;
      }
    });`
    
    lib/ui/screens/home/main_screen.dart:225:37: Error: Inferred type argument 'HubEvent<Object?>' doesn't conform to the bound 'HubEvent<HubEventPayload>' of the type variable 'E' on 'AmplifyHub.listen'.
 - 'HubEvent' is from 'package:amplify_core/src/hub/hub_event.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/hub_event.dart').
 - 'Object' is from 'dart:core'.
 - 'AmplifyHub' is from 'package:amplify_core/src/hub/amplify_hub.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/amplify_hub.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
    _$hubSubscription = Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
                                    ^
Target kernel_snapshot failed: Exception

**Comment by pranavo72bex** [comment]
> Hi @pranavo72bex thanks for sharing your issue. Why are you setting your kotlin version to 1.8.0? Currently Amplify Flutter is only compatible with kotlin 1.7.10

I manage to fix this issue 
` ext.kotlin_version = '1.9.10'`
```
`[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources`
```
``` classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version'
        classpath 'com.google.gms:google-services:4.3.0'

**Comment by pranavo72bex** [comment]
> ```
> _$hubSubscription = Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
>       switch (hubEvent.eventName) {
>         case "SESSION_EXPIRED":
>           ref.read(authProvider.notifier).logOutUser();
>           break;
>         case "SIGNED_OUT":
>           ref.read(authProvider.notifier).signOutCleanup();
>           break;
>       }
>     });
> ```
> 
> ```
>   lib/ui/screens/home/main_screen.dart:225:37: Error: Inferred type argument 'HubEvent<Object?>' doesn't conform to the bound 'HubEvent<HubEventPayload>' of the type variable 'E' on 'AmplifyHub.listen'.
> - 'HubEvent' is from 'package:amplify_core/src/hub/hub_event.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/hub_event.dart').
> - 'Object' is from 'dart:core'.
> - 'AmplifyHub' is from 'package:amplify_core/src/hub/amplify_hub.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/amplify_hub.dart').
> Try specifying type arguments explicitly so that they conform to the bounds.
>    _$hubSubscription = Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
>                                    ^
> Target kernel_snapshot failed: Exception
> ```
It fix my issue
```  handleHub() {
    _$hubSubscription =
        Amplify.Hub.listen<AuthHubEvent, HubEvent<AuthHubEvent>>(
            HubChannel.Auth as HubChannel<AuthHubEvent, HubEvent<AuthHubEvent>>,
            (hubEvent) {
      switch (hubEvent.eventName) {
        case "SESSION_EXPIRED":
          ref.read(authProvider.notifier).logOutUser();
          break;
        case "SIGNED_OUT":
          ref.read(authProvider.notifier).signOutCleanup();
          break;
      }
    });
  }`

**Comment by fjnoyp** [comment]
Alright good to hear, I'll close for now then @pranavo72bex.  Feel free to reopen or create another issue should you have another problem.
