### ISSUE TITLE
Build issue in Android | Inferred type argument 'HubEvent<Object?>' doesn't conform to the bound 'HubEvent<HubEventPayload>' of the type variable 'E' on 'AmplifyHub.listen'.

### ISSUE THREAD

**Issue by pranavo72bex** [aws-amplify/amplify-flutter#4291]
### Description

lib/ui/screens/home/main_screen.dart:224:37: Error: Inferred type argument 'HubEvent<Object?>' doesn't conform to the bound 'HubEvent<HubEventPayload>' of the type variable 'E' on 'AmplifyHub.listen'.
 - 'HubEvent' is from 'package:amplify_core/src/hub/hub_event.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/hub_event.dart').
 - 'Object' is from 'dart:core'.
 - 'AmplifyHub' is from 'package:amplify_core/src/hub/amplify_hub.dart' ('../.pub-cache/hosted/pub.dev/amplify_core-1.6.2/lib/src/hub/amplify_hub.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
    _$hubSubscription = Amplify.Hub.listen(HubChannel.Auth, (hubEvent) {
    
    
    ` amplify_auth_cognito: ^1.6.1
  amplify_core: ^1.6.2
  amplify_flutter: ^1.6.1'

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![Screenshot 2024-01-01 at 10 16 42](https://github.com/aws-amplify/amplify-flutter/assets/71395812/5e2dda10-3d84-4a72-99c5-3ce91ab809a1)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.3

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @pranavo72bex, sorry you've ran into this error. 

Can you please provide the code that the stack trace points to?

**Comment by Jordan-Nelson** [comment]
@pranavo72bex if you are still facing this issue please provide the code from lib/ui/screens/home/main_screen.dart:224:37. Thanks.

**Comment by pranavo72bex** [comment]
> @pranavo72bex if you are still facing this issue please provide the code from lib/ui/screens/home/main_screen.dart:224:37. Thanks.

Yes, I am still getting the error in my project 
`I am using flutter 3.16.3 and kotlin version 1.9.10`
![Screenshot 2024-01-09 at 10 06 56](https://github.com/aws-amplify/amplify-flutter/assets/71395812/87234d44-633d-4202-874d-bef781975a26)
![Screenshot 2024-01-09 at 10 08 00](https://github.com/aws-amplify/amplify-flutter/assets/71395812/1e548219-8f71-46e2-a6fb-4b44e9318c17)

**Comment by pranavo72bex** [comment]
@Jordan-Nelson  @Equartey , am i missing something here ?
![Screenshot 2024-01-09 at 15 34 17](https://github.com/aws-amplify/amplify-flutter/assets/71395812/3ad6727e-1386-4540-814b-5099b6e8a14f)
![Screenshot 2024-01-09 at 15 34 35](https://github.com/aws-amplify/amplify-flutter/assets/71395812/f152fe5a-e528-4c2e-840c-0a6ea0b9ad92)

**Comment by Jordan-Nelson** [comment]
@pranavo72bex can you share the code where `_$hubSubscription` is defined so that I can see the type?

Also, if you could copy/past the code snippet rather than take a screenshot that would be appreciated. That way I can copy/paste it into my IDE.

**Comment by Jordan-Nelson** [comment]
Based on the error message, I believe `_$hubSubscription` is of type `StreamSubscription<HubEvent>`. If you change it to `StreamSubscription<AuthHubEvent>` that should result your issue.

**Comment by pranavo72bex** [comment]
> `StreamSubscription<AuthHubEvent>`

Thank you sir, it fix the issue 🙏
