### ISSUE TITLE
PinPoint Push Notification Endpoint Address issue with iOS 13.0

### ISSUE THREAD

**Issue by mvn-thanhnguyen8-hn** [aws-amplify/amplify-flutter#4301]
### Description

I had the same problem https://github.com/aws-amplify/aws-sdk-ios/issues/1926, so is the problem resolved? Thank you very much

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.3

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @mvn-thanhnguyen8-hn, thank you for taking the time to submit this issue. We will investigate it and get back to you, thanks.

**Comment by mvn-thanhnguyen8-hn** [comment]
@khatruong2009 Hope to receive your reply soon, many thanks 🙇🏻‍♂️

**Comment by mvn-thanhnguyen8-hn** [comment]
@khatruong2009 Sorry, I wonder if you have investigated and encountered problems with the current version 🙇🏻‍♂️
