### ISSUE TITLE
S3 without authentication

### ISSUE THREAD

**Issue by nt4f04uNd** [aws-amplify/amplify-flutter#437]
is it possible to use AmplifyStorageS3 without AmplifyAuthCognito? i don't need to authenticate users in my app, only use a public bucket, or via iam credentials

**Comment by fjnoyp** [comment]
Hi @nt4f04uNd you currently need to include the AmplifyAuthCognito plugin when using AmplifyStorageS3.  

However, when following the setup instructions we have [here](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter#prerequisites) you just need to include Auth but don't need to spend time configuring it as you can allow guess (unauthenticated) access to your Storage items.

**Comment by nt4f04uNd** [comment]
i find it strange that even if you don't need to used you have to include it, what's the reason of that? i don't think it's a big blocker, but for my particular use case (i only use s3 storage) i moved over to using https://pub.dev/packages/flutter_aws_s3_client, which i found being very lightweight and easy to configure and it was exactly what i needed

**Comment by Abacaxi-Nelson** [comment]
Same here. And i dont need cognito..
So not easy way to just send files to S3 ?

**Comment by offlineprogrammer** [comment]
Hi @Abacaxi-Nelson @nt4f04uNd 

As per @fjnoyp the Auth is required by the native libraries and to generate the required identity pools for the users

You can read more about S3 and its policy [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html)

Regards
Mo

**Comment by offlineprogrammer** [comment]
Hi All

I am closing this issue for now due to inactivity

Regards
Mo
