### ISSUE TITLE
 AWS lambda function error 

### ISSUE THREAD

**Issue by itamimkhan** [aws-amplify/amplify-flutter#4408]
### Description

getting the error ="The API with ID vh2wyexl67 doesn’t include a resource with path /* having an integration arn:aws:lambda:us-east-1:641366283611:function:CertHiveQueueEmailDeliveryRequest-dev on the ANY method.
" 
<img width="1057" alt="Screenshot 2024-01-30 at 12 46 06 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/143828679/945d1eca-fc90-4c52-beac-e243e79fe6c5"
<img width="1001" alt="Screenshot 2024-01-30 at 12 46 50 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/143828679/993b21c9-eff0-47fa-a0b7-837af209fc1a">

in configuration-->>triggers

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

<img width="1001" alt="Screenshot 2024-01-30 at 12 46 50 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/143828679/d78b3da7-10ff-4dc2-b36f-5b7c35359e7a">

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16

### Amplify Flutter Version

v1

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @itamimkhan, thank you for taking the time to submit this issue. Do you have any code you could share with us to help us reproduce the issue?

**Comment by Jordan-Nelson** [comment]
@itamimkhan if you are still facing this issue please take a look at the question above. Thanks.

**Comment by khatruong2009** [comment]
Hi @itamimkhan, I'm closing this issue now. Please feel free to reopen the issue if you experience this issue again and have reproduction steps for us to follow. Thanks.
