### ISSUE TITLE
No auth provider found for auth mode function

### ISSUE THREAD

**Issue by dustin-auby** [aws-amplify/amplify-flutter#4411]
### Description

Hi all, i am trying to use a Lambda function for Lambda authorization mode in amplify and i get the following error.

`underlyingException": "ConfigurationError {\n  \"message\": \"No auth provider found for auth mode function.\",\n  \"recoverySuggestion\": \"Ensure API plugin correctly configured.\"\n}`

I have created the function, set the authentication mode to Lambda but when querying i get that error. if i run the query from appsync it works fine.

bellow is the model i am using

`type Attendants @model @auth(rules: [{ allow: custom, provider: function }]) {
  id: ID!
  event_uuid: ID! @primaryKey(sortKeyFields: ["id"])
  name: String
  surname: String
  json: AWSJSON
  json_string: String
}`

If anyone can assist with this i would be very greatfull

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.3

### Amplify Flutter Version

^1.6.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Attendants @model @auth(rules: [{ allow: custom, provider: function }]) {
  id: ID!
  event_uuid: ID! @primaryKey(sortKeyFields: ["id"])
  name: String
  surname: String
  json: AWSJSON
  json_string: String
}
```

**Comment by dustin-auby** [comment]
I have manage to resolve this, turns out you cannot have 2 AmplifyAPI Objects, i was using one for api and one for the Lambda function. i merged the two and now it works fine.

I am now however getting very slow response times even when not using the Lambda function.between 400 and 1500 ms is this normal ?

**Comment by khatruong2009** [comment]
Hi @dustin-auby, how are you measuring the response times from the Lambda function? Is the 400-1500ms for the full network affect or is it from the API?

**Comment by khatruong2009** [comment]
Since this happens even when you don't use a lambda function, are you using the GraphQL API on a model that doesn't have authorization?

**Comment by dustin-auby** [comment]
Hi,

Both models are authenticated . One uses cognito pool with owner permissions and the other uses custom with the lambda function as I need more fine grain control.



Sent from my Galaxy


-------- Original message --------
From: Kha Truong ***@***.***>
Date: 2024/02/01 23:40 (GMT+02:00)
To: aws-amplify/amplify-flutter ***@***.***>
Cc: Dustin | Epicdev ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-amplify/amplify-flutter] No auth provider found for auth mode function (Issue #4411)


Since this happens even when you don't use a lambda function, are you using the GraphQL API on a model that doesn't have authorization?

**Comment by khatruong2009** [comment]
Hi @dustin-auby, could the longer latency events be happening when credentials are expired and need to be refreshed? Could you capture the network traffic and share it with us so we can better diagnose the issue?

Something like this:

![image](https://github.com/aws-amplify/amplify-flutter/assets/64438356/46813784-eb1a-4ad5-8d18-fc8733b7cbf1)

**Comment by dustin-auby** [comment]
Hi, yes i was still having the issues. i have since moved away from amplify as i found it to limiting in many areas.
