### ISSUE TITLE
Support user migration lambda function trigger & USER_PASSWORD authentication type

### ISSUE THREAD

**Issue by pairwinter** [aws-amplify/amplify-flutter#442]
**Describe the bug**
Amplify.Auth.signIn can not trigger user migration lambda function. But Amplify.Auth.resetPassword() and signInWithWebUI() works fine, both of them can trigger user migration lambda function.
I have set the authenticationFlowType to USER_PASSWORD_AUTH in amplifyconfiguration.dart, and enabled the USER_PASSWORD_AUTH for the app in User Pool settings.
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
           ...
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
               ,
                "Auth": {
                    "Default": {
                        "OAuth": {
                            ...
                        },
                        "authenticationFlowType": "USER_PASSWORD_AUTH"
                    }
                }
            }
        }
    }
}
```

**To Reproduce**
1. set a lambda function triggerMigrateUser, mock the user: {username: "testusername", password: "testpassword"}
2. config the lambda for User Migration in User Pool Trigger Settings, 
3. In User Pool -> General settings -> App clients : Check "Enable username password based authentication (ALLOW_USER_PASSWORD_AUTH)"
4. Set up "authenticationFlowType": "USER_PASSWORD_AUTH" in amplifyconfiguration.dart
5. Enable the config in the code, Amplify.configure(amplifyconfig)
6. Execute this code: Amplify.Auth.signIn(username: "testusername", password: "testpassword")

**Expected behavior**
Lambda function triggerMigrateUser should be triggered when executing Amplify.Auth.signIn(). 

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/damon.liu/Documents/workspace/code/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/damon.liu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/damon.liu/Library/Android/sdk
    • Java binary at: /Users/damon.liu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Users/damon.liu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Users/damon.liu/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

 
[✓] Connected device (1 available)            
    • iPhone 12 Pro Max (mobile) • 8D15FEF9-BB73-4D7D-8259-91D3FC043BB3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro Max
 - OS: iOS14.4

**Comment by pairwinter** [comment]
Hi, any idea for this question?

**Comment by pairwinter** [comment]
Hi @Ashish-Nanda , any update on this question?

**Comment by offlineprogrammer** [comment]
Hi @pairwinter 

Are you still facing this issue with the latest release ?

Thanks
Mo

**Comment by pairwinter** [comment]
> Hi @pairwinter
> 
> Are you still facing this issue with the latest release ?
> 
> Thanks Mo

Hi @offlineprogrammer , I have not try the latest release. Have the aws-amplify team reproduced this issue and fixed it?

**Comment by Jordan-Nelson** [comment]
Hello @pairwinter - I am going to mark this as a feature request to track interest in this. Although it seems that this may partially work, this is not officially supported by Amplify-Flutter.

Amplify-Flutter depends on [Amplify-iOS](https://github.com/aws-amplify/amplify-ios) or [Amplify-Android](https://github.com/aws-amplify/amplify-android), depending on the target platform. This is not currently supported by Amplify-iOS. It looks like this might be possible in Android currently, but believe would require using [aws-sdk-android](https://github.com/aws-amplify/aws-sdk-android), which is a lower level SDK that Amplify-Android depends on.

This is supported by amplify-js. [Here are the docs](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js/#migrate-users-with-amazon-cognito) for it.

For reference, here is a link to [an issue that was resolved in aws-sdk-android](https://github.com/aws-amplify/aws-sdk-android/issues/1778) to support this.

**Comment by pairwinter** [comment]
Hi, @Jordan-Nelson , thank you for the explanation. Despite can make a workaround by using the amplify-js, if we can add the complete support for that on Amplify-flutter, it would be great news to encourage teams to move to the amplify-platform from the existing system. Hope we can get this support soon, thank you.

**Comment by Jordan-Nelson** [comment]
Support for this has been added in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
