### ISSUE TITLE
[Bug] LoadingScreen should have CircularProgressIndicator.adaptive()

### ISSUE THREAD

**Issue by marcotrumpet** [aws-amplify/amplify-flutter#4438]
### Description

LoadingScreen in amplify_authenticator should use CircularProgressIndicator.adaptive() to better fit the platform being used on.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.8

### Amplify Flutter Version

1.5.3

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @marcotrumpet - Thanks for opening the issue.

I think the platform adaptive loading indicator could look out of place given that none of the other widgets in the authenticator are platform adaptive.

However, the authenticator is intended to be themed and customized as desired. If you prefer a different styled loading indicator you can use the following code to achieve that.

Let me know if you have any other questions.

```dart
  @override
  Widget build(BuildContext context) {
    return Authenticator(
      // authenticatorBuilder allows you to fully customize one or more states.
      // the code below swaps out the "loading" step with a custom widget.
      authenticatorBuilder: (context, state) {
        if (state.currentStep == AuthenticatorStep.loading) {
          return const Center(
            child: CircularProgressIndicator.adaptive(),
          );
        }
      },
      child: MaterialApp(
        builder: Authenticator.builder(),
        home: Scaffold(
          appBar: AppBar(),
          body: const Center(
            child: Column(
              children: [
                Text('You are logged in!'),
                SizedBox(height: 16),
                SignOutButton()
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by marcotrumpet** [comment]
hey @Jordan-Nelson many thanks, that was it, I'll close this
