### ISSUE TITLE
[Documentation] Flutter example in amplify gen 2 documentation missing binding init

### ISSUE THREAD

**Issue by malaquf** [aws-amplify/amplify-flutter#4447]
### Description

Hi,
I was just getting started with Flutter + amplify libs and I noticed the example in the Flutter section [here](https://docs.amplify.aws/gen2/start/mobile-support/) is missing the `WidgetsFlutterBinding.ensureInitialized();` before `await _configureAmplify();` otherwise, it fails during startup because the binding has not yet been initialized.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

<img width="1043" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/3417108/0e276464-c844-4544-8bf8-c3fd1c6867fc">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.9

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @malaquf, `WidgetsFlutterBinding.ensureInitialized();` is only needed when calling `_configure` before calling `runApp`. This is because calling `configureAmplify()` before `runApp` creates a race condition. If you put `_configureAmplify()` in the `initState()` or after the `runApp` and it should work. This issue isn't Gen 2 specific. Let me know if that fixes your problem, thanks.

**Comment by malaquf** [comment]
Hey hey @khatruong2009, I know it. I just opened it because in the documentation itself it tries to configure it before calling runApp, so I thought you'd like to review the doc.

<img width="1439" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/3417108/d6185897-52b0-4e16-a247-60a1869c1a27">

**Comment by khatruong2009** [comment]
Oh ok I see. Thank you for bringing this to our attention, I'll get working on updating the docs now.

**Comment by khatruong2009** [comment]
Hi @malaquf, I just merged the change on the amplify-docs repo and it will be included in the next release. Thank you for pointing out this issue to us.

**Comment by malaquf** [comment]
Great, thanks for taking care and also pointing out the right repo, so next time I could maybe submit a PR on my own :)

**Comment by khatruong2009** [comment]
@malaquf The change should be out in 25-30 minutes. I'm going to close this issue now but feel free to let us know if you have any other issues in the future.
