### ISSUE TITLE
How much does DataStore cost?

### ISSUE THREAD

**Issue by lukaszciastko** [aws-amplify/amplify-flutter#445]
I know it's not a technical issue, but, I've been browsing the AWS pages and cannot find any information on how much Amplify DataStore costs? The AWS Amplify Pricing only includes static hosting but no information about other services.

**Comment by haverchuck** [comment]
@lukaszciastko It is my understanding that there is no additional charge for using DataStore - you pay for the underlying services with which DataStore interacts (i.e. [AppSync](https://aws.amazon.com/appsync/pricing/)).  You can also check the pricing pages for Amazon Cognito, AWS DynamoDB or other services you are using.

**Comment by lukaszciastko** [comment]
> @lukaszciastko It is my understanding that there is no additional charge for using DataStore - you pay for the underlying services with which DataStore interacts (i.e. [AppSync](https://aws.amazon.com/appsync/pricing/)). You can also check the pricing pages for Amazon Cognito, AWS DynamoDB or other services you are using.

Thanks. This wasn't clear to me at first, but it makes sense. I didn't see the link between Data Store and AppSync.
