### ISSUE TITLE
User being deleted after the app is being deleted from the phone

### ISSUE THREAD

**Issue by true-glassy** [aws-amplify/amplify-flutter#4523]
### Description

I have a problem with Auth this issue happened twice and although I did the same steps before it was okay and the user was not deleted, it randomly happens.
The user got deleted from the Cognito pool after the app was deleted, the user ID is no longer available in the pool and the users have decreased by one so I am 100% sure that it was deleted.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Register with Amplify Auth
2. Delete the App
3. User is delete

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.4

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @true-glassy - Thank you for taking the time to open the issue.

I have attempted to reproduce this given the steps you have provided and do not see that the user is deleted. It sounds like you are also unable to consistently reproduce this issue. Unfortunately without reproduction steps we won't be able to triage this issue. Please let us know if you are able to come up with a reproduction.

**Comment by true-glassy** [comment]
Yes, I tried it several times and couldn't reproduce the issue but it happened twice in the last month and I am sure the account was deleted each time.
Do you have a suggestion or ideas for the cause? and can I send a confirmation code to delete the user account?

**Comment by Jordan-Nelson** [comment]
> can I send a confirmation code to delete the user account?

This is not a feature that is supported. You might be able to build a lambda fn that does this, but it is not supported out of the box.

You could use AWS CloudTrails and search for invocations of "DeleteUser" to see where the event originated from and at what time. It might be hard to do this now given some time has passed and there may be other logs for the DeleteUser now.

Without reproduction steps or more info indicating the calls to delete the user are coming from Amplify Flutter, I am going to close this out. We can reopen it if you are able to reproduce it or collect more info.
