### ISSUE TITLE
table update issue

### ISSUE THREAD

**Issue by Aruljebaraj** [aws-amplify/amplify-flutter#4547]
### Description

After creating a table in DataModel and deploying it, I didn't see the model folder when I pulled the changes.
 
### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @Aruljebaraj, after you pulled an Amplify backend, you need to generate the models. 

From your project root run:

If you're using the Amplify CLI: `amplify codgen models`

Or `npx @aws-amplify/cli codegen models --model-schema PATH_TO_SCHEMA --target flutter --output-dir ./lib/models`
