### ISSUE TITLE
'AuthProvider' doesn't conform to the bound 'Enum?' when setting up the Authenticator

### ISSUE THREAD

**Issue by JncHrmn** [aws-amplify/amplify-flutter#4548]
### Description

We are setting up our authentication flow, exactly how it's done in the documentation, but everytime we want to run the application, this error occurs:
On MacOs for iOs: `Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/amplify_authenticator-1.2.0/lib/src/widgets/social/social_button.dart:128:13: Error: Type argument 'AuthProvider' doesn't conform to the bound
'Enum?' of the type variable 'T' on 'EnumProperty'.`

And on Windows for Android: `/C:/Users/Admin/AppData/Local/Pub/Cache/hosted/[pub.dev/amplify_authenticator-1.2.0/lib/src/widgets/social/social_button.dart:128:13](http://pub.dev/amplify_authenticator-1.2.0/lib/src/widgets/social/social_button.dart:128:13): Error: Type argument 'AuthProvider' doesn't conform to the bound 'Enum?' of the type variable 'T' on 'EnumProperty'.`
 - 'AuthProvider' is from 'package:amplify_core/src/types/auth/sign_in/auth_provider.dart' ('/C:/Users/Admin/AppData/Local/Pub/Cache/hosted/[pub.dev/amplify_core-1.1.1/lib/src/types/auth/sign_in/auth_provider.dart'](http://pub.dev/amplify_core-1.1.1/lib/src/types/auth/sign_in/auth_provider.dart%27)).
 - 'Enum' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
      ..add(EnumProperty<AuthProvider>('provider', provider))
            ^
/D:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:2314:20: Context: This is the type variable whose bound isn't conformed to.
class EnumProperty<T extends Enum?> extends DiagnosticsProperty<T> {
                   ^
                   
We tried usual procedure `flutter upgrade`, `amplify upgrade`, but hasn't solved the error.
Manually changing the versions of the authenticator didn't help as well.
What could be cause of this? What could be potential solutions? 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

We just followed the guide from the Authenticator for Flutter.
Did the steps like pulling backend, installing dependencies and adding the authenticator in our main.dart.
When running the app, the error occurs and the build is stopped.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @JannicMeetYu, it looks like your Amplify Flutter version is old, have you tried updating your amplify packages to their latest versions? 

Can you post your `pubspec.yaml`?

**Comment by Jordan-Nelson** [comment]
> `flutter clean + flutter pub get`

If you have a pubspec.lock file this will install the version listed in the lock file. You can run `flutter pub upgrade` to upgrade to the latest version allowed by the constraint in your pubpsec.yaml file. See [the Flutter docs](https://docs.flutter.dev/packages-and-plugins/using-packages#updating-package-dependencies) for more info on installing/upgrading packages from the CLI. Once you have upgraded you can look at your lock file, or run `flutter pub deps --no-dev --style=compact` to verify the packages were upgraded.

If you are still facing issues after upgrading please share the output of `flutter pub deps --no-dev --style=compact`.

**Comment by Equartey** [comment]
@JannicMeetYu glad you could resolve it. Do you know what package & version it was colliding with?
