### ISSUE TITLE
Support for handling analytics in native code

### ISSUE THREAD

**Issue by lukaszciastko-spica** [aws-amplify/amplify-flutter#4557]
We have a Flutter app, and we’re looking to migrate our analytics to AWS Amplify.

The app needs to record native and Dart events, but the AWS Flutter SDK seems to only support Dart events. At the same time, the native iOS SDK is only available via the Swift Package Manager (no Cocoapods), which Flutter doesn’t support - while I think I can add the dependency to the main app, there is no easy way to add the SDK to plugins the app uses (and where the actual events are triggered).

Is there an easy way to use AWS Amplify Analytics in this scenario?

**Comment by Equartey** [comment]
Hi @lukaszciastko-spica, your summary seems correct to me and it sounds like the main issue for adoption is being able to capture native iOS events. Regrettably, we are unable to provide a straightforward solution at the moment. Currently, we do not support this for the reason you mentioned (Cocoapods). 

I'd suggest investigating Flutter's platform channel to see if you can record these events on your own.

**Comment by Jordan-Nelson** [comment]
@lukaszciastko-spica I am going to close this issue since the question was answered. As noted above, the best way to handle this currently would be to send the event from native iOS to Dart using a platform channel and then record it with Amplify Flutter.
