### ISSUE TITLE
when ever i am trying to do flutter run then a error occurs 

### ISSUE THREAD

**Issue by amantiwari-18** [aws-amplify/amplify-flutter#4570]
### Description

/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/amplify_secure_storage.vm.dart:138:27: Error: The method 'getApplicationSupportDirectory' isn't defined for the class 'AmplifySecureStorage'.
 - 'AmplifySecureStorage' is from 'package:amplify_secure_storage/src/amplify_secure_storage.vm.dart' ('/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/amplify_secure_storage.vm.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getApplicationSupportDirectory'.
      final path = (await getApplicationSupportDirectory()).path;
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/path_provider_local.dart:31:11: Error: Method not found: 'MissingPlatformDirectoryException'.
    throw MissingPlatformDirectoryException(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![Uploading Capture.JPG…]()

### Categories

- [ ] Analytics
- [X] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![Capture](https://github.com/aws-amplify/amplify-flutter/assets/102050032/f14a06cc-8d92-465d-9649-3f08bc1983dd)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision ba39319843 (12 days ago) • 2024-03-07 15:22:21 -0600 Engine • revision 2e4ba9c6fb Tools • Dart 3.3.1 • DevTools 2.31.1

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@amantiwari-18 can you provide the output of 'flutter pub deps --no-dev --style=compact' and the code you are using the configure amplify?

**Comment by amantiwari-18** [comment]
> @amantiwari-18 can you provide the output of 'flutter pub deps --no-dev --style=compact' and the code you are using the configure amplify?




Error on line 42, column 18 of pubspec.yaml: Invalid version constraint: Expected version number after "^" in "^2.1 .2", got "2.1 .2".
   ╷
42 │   path_provider: ^2.1 .2
   │                  ^^^^^^^
   
   
   
   it says this when i write  flutter pub deps --no-dev --style=compact
   
   
 import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:eadmin/auth/login.dart';
import 'package:eadmin/directional/dir.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
   await requestStoragePermission(); // Request storage permission
  await configureAmplify();

  
  bool isAuthenticated = await checkAuthentication();

  runApp(MyApp(isAuthenticated: isAuthenticated));
}
Future<void> configureAmplify() async {

  try {
    
 await Amplify.addPlugin(AmplifyDataStore(modelProvider: ModelProvider.instance)); 
    
    final storage = AmplifyStorageS3();
    final api = AmplifyAPI();
    final auth = AmplifyAuthCognito();
    await Amplify.addPlugins([
     api,
    storage,  
    auth,
    ]);
     await Amplify.configure(amplifyconfig);
    DynamoDB(region: 'eu-west-1');
  } 
  catch (e) {
    print("********************$e");
  }
}

Future<bool> checkAuthentication() async {
  try {
    final session = await Amplify.Auth.fetchAuthSession();
    return session.isSignedIn;
  } catch (e) {
    print("Error checking authentication: $e");
    return false;
  }
}



class MyApp extends StatelessWidget {
  final bool isAuthenticated;

  const MyApp({Key? key, required this.isAuthenticated}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(5, 255, 255, 255),
      ),
      home: isAuthenticated ? const dir() : const LoginScreen(),
    );
  }
}

**Comment by Jordan-Nelson** [comment]
It looks like you have a space in the version number '2.1 .2'. Can you remove that and then run it?

**Comment by amantiwari-18** [comment]
> It looks like you have a space in the version number '2.1 .2'. Can you remove that and then run it?



____________________________________________________________________________________________________________________
sorry  my bad i am new to flutter 
 this is what it says
    ╵
PS D:\STUDY\eadmin> flutter pub deps --no-dev --style=compact
Dart SDK 3.3.1
Flutter SDK 3.19.3
eadmin 1.0.0+1

dependencies:
- amplify_api 1.7.0 [amplify_api_dart amplify_core amplify_flutter connectivity_plus flutter meta plugin_platform_interface]
- amplify_auth_cognito 1.7.2 [amplify_analytics_pinpoint amplify_analytics_pinpoint_dart amplify_auth_cognito_dart amplify_core amplify_flutter amplify_secure_storage async flutter meta path plugin_platform_interface]
- amplify_datastore 1.7.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]        
- amplify_flutter 1.7.0 [amplify_core amplify_secure_storage aws_common collection flutter meta]
- amplify_storage_s3 1.7.0 [amplify_core amplify_db_common amplify_storage_s3_dart aws_common flutter meta path_provider]
- aws_dynamodb_api 2.0.0 [shared_aws_api]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- file_picker 6.2.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- font_awesome_flutter 10.7.0 [flutter]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- table_calendar 3.0.9 [flutter intl simple_gesture_detector]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

transitive dependencies:
- amplify_analytics_pinpoint 1.7.0 [amplify_analytics_pinpoint_dart amplify_core amplify_db_common amplify_secure_storage aws_common device_info_plus flutter meta package_info_plus path_provider]
- amplify_analytics_pinpoint_dart 0.3.7 [amplify_core amplify_db_common_dart amplify_secure_storage_dart aws_common aws_signature_v4 built_collection built_value collection drift intl meta path smithy smithy_aws uuid]
- amplify_api_dart 0.4.0 [amplify_core async aws_common collection json_annotation meta plugin_platform_interface stream_transform web_socket_channel]
- amplify_auth_cognito_dart 0.10.12 [amplify_analytics_pinpoint_dart amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value clock collection convert crypto ffi fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid win32 win32_registry worker_bee]
- amplify_core 1.7.0 [async aws_common aws_signature_v4 collection graphs intl json_annotation logging meta retry stack_trace uuid]        
- amplify_datastore_plugin_interface 1.7.0 [amplify_core collection flutter meta]
- amplify_db_common 0.3.5 [amplify_db_common_dart drift flutter path path_provider]
- amplify_db_common_dart 0.3.6 [amplify_core async aws_common drift meta path sqlite3]
- amplify_secure_storage 0.4.2 [amplify_secure_storage_dart async file flutter meta path path_provider path_provider_windows]
- amplify_secure_storage_dart 0.4.3 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- amplify_storage_s3_dart 0.3.10 [amplify_core amplify_db_common_dart async aws_common aws_signature_v4 built_collection built_value drift 
fixnum json_annotation meta path smithy smithy_aws]
- args 2.4.2
- async 2.11.0 [collection meta]
- aws_common 0.6.3 [async built_collection built_value collection http2 js json_annotation logging meta mime os_detect path stream_transform uuid]
- aws_signature_v4 0.5.1 [async aws_common collection convert crypto json_annotation meta path]
- built_collection 5.1.1
- built_value 8.8.1 [built_collection collection fixnum meta]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.3 [typed_data]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- drift 2.14.1 [async convert collection js meta stream_channel sqlite3 path]
- ffi 2.1.2
- file 7.0.0 [meta path]
- fixnum 1.1.0
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- graphs 2.3.1 [collection]
- http 0.13.6 [async http_parser meta]
- http2 2.3.0
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.18.1 [clock meta path]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- logging 1.2.0
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nm 0.5.0 [dbus]
- oauth2 2.0.2 [collection crypto http http_parser]
- os_detect 2.0.1
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.1 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- retry 3.1.2
- shared_aws_api 2.0.1 [crypto http meta xml intl uuid collection]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- simple_gesture_detector 0.2.1 [flutter]
- sky_engine 0.0.99
- smithy 0.6.3 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.6.2 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_span 1.10.0 [collection path term_glyph]
- sqlite3 2.4.0 [collection ffi js meta path]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- web 0.5.1
- web_socket_channel 2.4.4 [async crypto stream_channel web]
- win32 5.3.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- worker_bee 0.2.3 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]     
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
PS D:\STUDY\eadmin>

**Comment by amantiwari-18** [comment]
> It looks like you have a space in the version number '2.1 .2'. Can you remove that and then run it?

@Jordan-Nelson  any updates?

**Comment by khatruong2009** [comment]
Hi @amantiwari-18, have you tried rerunning `flutter run` after making the change to the version number?

**Comment by amantiwari-18** [comment]
@khatruong2009  @Jordan-Nelson 

hey i tires flutter clean and flutter run but the error persists

PS D:\STUDY\eadmin> flutter clean
Deleting build...                                                1,764ms
Deleting .dart_tool...                                              66ms
Deleting Generated.xcconfig...                                       3ms
Deleting flutter_export_environment.sh...                            7ms
Deleting ephemeral...                                               14ms
Deleting ephemeral...                                               42ms
Deleting ephemeral...                                                4ms
Deleting .flutter-plugins-dependencies...                           19ms
Deleting .flutter-plugins...                                        10ms
PS D:\STUDY\eadmin> flutter run
Resolving dependencies... (1.5s)
  built_value 8.8.1 (8.9.1 available)
  drift 2.14.1 (2.16.0 available)
  http 0.13.6 (1.2.1 available)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.4 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.3 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)        
  material_color_utilities 0.8.0 (0.11.1 available)   
  meta 1.11.0 (1.12.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  table_calendar 3.0.9 (3.1.0 available)
  test_api 0.6.1 (0.7.0 available)
  uuid 3.0.7 (4.3.3 available)
  vm_service 13.0.0 (14.1.0 available)
Got dependencies!
15 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on sdk gphone x86 in debug mode...
/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/amplify_secure_storage.vm.dart:138:27: Error: 
The method 'getApplicationSupportDirectory' isn't defined for the class 'AmplifySecureStorage'.
 - 'AmplifySecureStorage' is from 'package:amplify_secure_storage/src/amplify_secure_storage.vm.dart' ('/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/amplify_secure_storage.vm.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getApplicationSupportDirectory'.
      final path = (await getApplicationSupportDirectory()).path;
/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/path_provider_local.dart:31:11: Error: Method 
not found: 'MissingPlatformDirectoryException'.
    throw MissingPlatformDirectoryException(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Running Gradle task 'assembleDebug'...                             97.3s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by amantiwari-18** [comment]
> Hi @amantiwari-18, have you tried rerunning `flutter clean` and `flutter run` after making the change to the version number?

@Jordan-Nelson @khatruong2009 
 Any suggestions guys how can i overcome this error?

**Comment by amantiwari-18** [comment]
> * /C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/path_provider_local.dart


@Jordan-Nelson  @khatruong2009 

this is the path_provider

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// ignore_for_file: implementation_imports

import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:path_provider_windows/src/folders.dart';
import 'package:path_provider_windows/src/path_provider_windows_real.dart';

/// A version of [PathProviderWindows] that uses the
/// [WindowsKnownFolder.LocalAppData] directory in place of the
/// [WindowsKnownFolder.RoamingAppData] directory.
class PathProviderWindowsLocal extends PathProviderWindows {
  @override
  Future<String?> getPath(String folderID) {
    if (folderID == WindowsKnownFolder.RoamingAppData) {
      return super.getPath(WindowsKnownFolder.LocalAppData);
    }
    return super.getPath(folderID);
  }
}

// / Returns version of [getApplicationSupportDirectory] that returns the Local
/// App Data directory on Windows.
Future<Directory> getApplicationLocalSupportDirectory() async {
  if (!Platform.isWindows) throw UnsupportedError('Only supported on Windows');
  final path = await PathProviderWindowsLocal().getApplicationSupportPath();
  if (path == null) {
    throw MissingPlatformDirectoryException(
      'Unable to get application support directory',
    );
  }
  return Directory(path);
}

**Comment by amantiwari-18** [comment]
> Can you share the contents of these two files?
> 
> * /C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/amplify_secure_storage.vm.dart'
> * /C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/amplify_secure_storage-0.4.2/lib/src/path_provider_local.dart
> 
> The error message is saying that the function `getApplicationLocalSupportDirectory()` isn't defined. It should be defined in `path_provider_local.dart`. I would like to see the contents of your local files to see if that function is defined.

@Jordan-Nelson @khatruong2009 
this is the  amplify_secure_storage.vm


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import 'dart:async';
import 'dart:io';

import 'package:amplify_secure_storage/src/amplify_secure_storage.android.dart';
import 'package:amplify_secure_storage/src/path_provider_local.dart';
import 'package:amplify_secure_storage/src/pigeons/ns_user_defaults_pigeon.g.dart';
import 'package:amplify_secure_storage_dart/amplify_secure_storage_dart.dart';
// ignore: implementation_imports
import 'package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart';
import 'package:async/async.dart';
import 'package:meta/meta.dart';
import 'package:path_provider/path_provider.dart';

/// {@template amplify_secure_storage.amplify_secure_storage}
/// The default Secure Storage implementation used in Amplify packages.
/// {@endtemplate}
class AmplifySecureStorage extends AmplifySecureStorageInterface {
  /// {@template amplify_secure_storage.amplify_secure_storage.from_config}
  /// Generates a [AmplifySecureStorage] from a config.
  ///
  /// Should only be used within Amplify packages. See [factoryFrom] for
  /// external use.
  /// {@endtemplate}
  @internal
  AmplifySecureStorage({
    required super.config,
  });

  /// {@template amplify_secure_storage.amplify_secure_storage.factory_from}
  /// Returns a factory for creating [AmplifySecureStorage] instances.
  /// {@endtemplate}
  static AmplifySecureStorage Function(
    AmplifySecureStorageScope amplifyScope,
  ) factoryFrom({
    WebSecureStorageOptions? webOptions,
    WindowsSecureStorageOptions? windowsOptions,
    LinuxSecureStorageOptions? linuxOptions,
    MacOSSecureStorageOptions? macOSOptions,
    IOSSecureStorageOptions? iOSOptions,
  }) {
    return (AmplifySecureStorageScope scope) {
      return AmplifySecureStorage(
        config: AmplifySecureStorageConfig(
          scope: scope.name,
          webOptions: webOptions,
          windowsOptions: windowsOptions,
          linuxOptions: linuxOptions,
          macOSOptions: macOSOptions,
          iOSOptions: iOSOptions,
        ),
      );
    };
  }

  late final AmplifySecureStorageInterface _instance;

  /// A namespace for storing the list of registered scopes.
  ///
  /// Used as the file name on Linux and a prefix for the
  /// key in NSUserDefaults on iOS and MacOS.
  @visibleForTesting
  static const scopeStoragePrefix = 'amplify_secure_storage_scopes';

  final _initMemo = AsyncMemoizer<void>();

  Future<void> _init() async {
    await _initMemo.runOnce(
      () async {
        if (Platform.isAndroid) {
          _instance = AmplifySecureStorageAndroid(config: config);
        } else {
          var config = this.config;
          if (Platform.isWindows) {
            config = config.copyWith(
              windowsOptions: config.windowsOptions.copyWith(
                storagePath: config.windowsOptions.storagePath ??
                    (await getApplicationLocalSupportDirectory()).path,
              ),
            );
          }
          // ignore: invalid_use_of_internal_member
          _instance = AmplifySecureStorageWorker(config: config);
        }
        if (Platform.isIOS || Platform.isMacOS || Platform.isLinux) {
          final accessGroup = Platform.isLinux
              ? config.linuxOptions.accessGroup
              : Platform.isIOS
                  ? config.iOSOptions.accessGroup
                  : config.macOSOptions.accessGroup;
          // if accessGroup is set, do not clear data on initialization
          // since the data can be shared across applications.
          if (accessGroup == null) {
            await _initializeScope();
          }
        }
      },
    );
  }

  @override
  Future<void> delete({required String key}) async {
    await _init();
    return _instance.delete(key: key);
  }

  @override
  Future<String?> read({required String key}) async {
    await _init();
    return _instance.read(key: key);
  }

  @override
  Future<void> write({required String key, required String value}) async {
    await _init();
    return _instance.write(key: key, value: value);
  }

  @override
  Future<void> removeAll() async {
    await _init();
    // ignore: invalid_use_of_internal_member
    return _instance.removeAll();
  }

  /// Clears all keys for the given scope if this scope
  /// has not been initialized previously.
  ///
  /// Checks for an initialization flag in file storage.
  /// If the flag is not present storage will be cleared
  /// and then the flag will be set.
  ///
  /// Intended to clear storage after an app uninstall & re-install.
  Future<void> _initializeScope() async {
    if (Platform.isLinux) {
      final path = (await getApplicationSupportDirectory()).path;
      final fileStore = FileKeyValueStore(
        path: path,
        fileName: '$scopeStoragePrefix.json',
      );
      final isInitialized = await fileStore.containsKey(key: config.scope!);
      if (!isInitialized) {
        // removeAll is marked as internal to prevent use from outside
        // of secure_storage. Use in amplify_secure_storage is acceptable.
        // ignore: invalid_use_of_internal_member
        await _instance.removeAll();
        await fileStore.writeKey(key: config.scope!, value: true);
      }
    }

    if (Platform.isIOS || Platform.isMacOS) {
      final userDefaults = NSUserDefaultsPigeon();
      final key = '$scopeStoragePrefix.${config.scope}.isKeychainConfigured';
      final isInitialized = await userDefaults.boolFor(key);
      if (!isInitialized) {
        // ignore: invalid_use_of_internal_member
        await _instance.removeAll();
        await userDefaults.setBool(key, true);
      }
    }
  }
}

**Comment by Jordan-Nelson** [comment]
Thanks. The function that cannot be found should be coming from the path_provider plugin. Can you share the contents of the following file?
- `/C:/Users/noobg/AppData/Local/Pub/Cache/hosted/pub.dev/path_provider-2.1.2/lib/path_provider.dart`

**Comment by amantiwari-18** [comment]
> * path_provider-2.1.2/lib/path_provider.dart

@Jordan-Nelson  Thanks a lot man 
the path_finder file was empty even after downloading the package multiple times 

i copied the path finder code from github  and pasted now it works
