### ISSUE TITLE
Update aws_common dependencies

### ISSUE THREAD

**Issue by flodaniel** [aws-amplify/amplify-flutter#4618]
### Description

Merge this PR: https://github.com/aws-amplify/amplify-flutter/pull/4464/files so that aws_common stays up-to-date. We can't update some of our libs because aws_common depends on `js ^0.6.4`.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

See description.

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.19.5

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
thanks for opening this issue and sorry that you are facing this issue. we will look into upgrading the dependencies. the js 0.7.0 has breaking changes and so may involve some code changes in our libraries. we also upgrade dependencies across all the packages and hence may not mrge this PR which is only for aws_common package.

**Comment by flutterocks** [comment]
This is preventing me from using amplify as it's incompatible with a core plugin I'm using. 

What external action are you pending? this seems like an issue with amplify not being up to date on dependencies.

**Comment by Jordan-Nelson** [comment]
Hello @flutterocks - There was a dependency of Amplify Flutter that did not yet support version 0.7.0, but it appears that it now does. I will take a look into this.

**Comment by Jordan-Nelson** [comment]
This was resolved in https://github.com/aws-amplify/amplify-flutter/pull/5063 and should be included in the next release.

**Comment by flutterocks** [comment]
Thanks!  Any idea when this will be? currently holding up a release on our end

**Comment by Equartey** [comment]
@flodaniel @flutterocks 
Hi all, this has been addressed in Amplify Flutter 2.3.0. Please let us know if you have any more concerns.
