### ISSUE TITLE
[amplify_auth_cognito] type 'FetchAuthSessionFetching' is not a subtype of type 'FetchAuthSessionSuccess' in type cast

### ISSUE THREAD

**Issue by hayashikun** [aws-amplify/amplify-flutter#4635]
### Description

An error `type 'FetchAuthSessionFetching' is not a subtype of type 'FetchAuthSessionSuccess' in type cast` occurs after calling `Amplify.Auth.fetchAuthSession()`.

This is the stacktrace reported to Sentry.
<img width="554" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/5352478/de41f7e0-9371-4c60-b198-5f865911d628">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

We have not been able to reproduce it, but it is occurring at our distribution environments.

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

1.7.0

### Deployment Method

Custom Pipeline

**Comment by Jordan-Nelson** [comment]
@hayashikun Thanks for taking the time to open the issue.

Amplify Auth uses a state machine internally to fetch/refresh the user's session. From the info provided, it seems that the state machine is expecting the state machine to eventually resolve to a success state (or throw and exception), but that is not happening. It is not immediately clear to me how this could occur. I have a few follow up questions to try narrow down the issue.
- Is the stack trace that you provided the full stack trace? Do you have any additional logs?
- Do you have any info as to what APIs are being called or what the end user is doing when this occurs?
- Do you use the `fetchAuthSession()` API in your application? If so, do you use the `forceRefresh` option?
- Do you use the `federateToIdentityPool()` API?
- I see you specified this is happening on Windows. Can you confirm Windows is the OS running on the end user's device where this is occurring? Do your users use any other platforms? If so, which platforms are they using and is the issue occurring on those platforms?

**Comment by Jordan-Nelson** [comment]
@hayashikun - I am going to close this out since we have not heard back. If you are still facing this issue please take a look at the questions above. Thanks.
