### ISSUE TITLE
S3 access denied when making the API call.

### ISSUE THREAD

**Issue by alpebubekir** [aws-amplify/amplify-flutter#4666]
### Description

I am using amplify flutter and trying to upload photo to s3 bucket and get link of it. I did everything mentioned on the doc. But getting "S3 access denied when making the API call." this error. What am I doing wrong?

This is what I am doing for uploading:
```
final result = await FilePicker.platform.pickFiles(
  type: FileType.any,
  withReadStream: true,
  withData: false,
);

if (result == null) {
  print('No file selected');
  return;
}

final platformFile = result.files.single;

try {
  await Amplify.Storage.uploadFile(
    localFile: AWSFile.fromStream(
      platformFile.readStream!,
      size: platformFile.size,
    ),
    key: platformFile.name,
    onProgress: (p) =>
        print('Uploading: ${p.transferredBytes}/${p.totalBytes}'),
  ).result;
} on StorageException catch (e) {
  print('Error uploading file - ${e.message}');
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

I think there is a problem with permissions on roles or users or somethings else. I am a newbie at Amazon's services

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.17.0-5.0.pre.58 • channel master

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @alpebubekir 

Can you tell me a bit more about your auth setup?
- Are you using Cognito for authentication?
- What authorization rules have you set up for storage? The Amplify CLI allows you to allow/disallow read/write/delete access for unauthenticated (guest) and authenticated users. Can you let me know what rules you enabled?
- Is there a user signed in?
- If not, does your identity pool allow for unauthenticated (guest) users?
- Did you use the Amplify CLI to set up the backend?
- Can you provide the full stack trace of the error?

Thanks.

**Comment by Jordan-Nelson** [comment]
@alpebubekir - If you are still facing this issue can you take a look at the questions above. Thanks.

**Comment by Jordan-Nelson** [comment]
I am going to close this out since we have not heard back

**Comment by pepie** [comment]
@Jordan-Nelson I am getting the same error with version 2.1.0, Amplify Gen 2, and Flutter. 

Error: 
"S3 access denied when making the API call"

// Libraries
  amplify_api: *amplify_version
  amplify_authenticator: ^2.0.1
  amplify_auth_cognito: *amplify_version
  amplify_datastore: *amplify_version
  amplify_flutter: *amplify_version
  amplify_storage_s3: *amplify_version

Tutorial Reference:
https://docs.amplify.aws/flutter/build-a-backend/storage/upload-files/

// backend.ts
const backend = defineBackend({  auth,   data,   storage });

// data/resources.ts
export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'iam',
     apiKeyAuthorizationMode: {  expiresInDays: 7 }
  },
});

// storage/resource.ts
export const storage = defineStorage({
  name: 'mediafiles',
  access: (allow) => ({
      'media/public/{entity_id}/*': [
         allow.guest.to(  ['read]'  ),
         allow.entity( 'identity' ).to( ['read', 'write', 'delete'] ),
         allow.groups( ['Admins'] ).to( [ 'read', 'write', 'delete']  )
      ],
      'media/protected/{entity_id}/*': [
         allow.authenticated.to(['read']),
         allow.entity('identity').to(['read', 'write', 'delete']),
      ],
      'media/private/{entity_id}/*': [
         allow.entity('identity').to(['read', 'write', 'delete']),
     ]
  }),
});

// upload methods


final result = await Amplify.Storage.uploadFile(
            localFile: AWSFile.fromStream( imageFile.openRead(), size: 0 ),
            path: StoragePath.fromString("media/public/test.jpg",
            options: options,
            onProgress: onProgress ?? (progress) {
              safePrint('upload progress ${progress.fractionCompleted}');
            },
).result;



Please review.

**Comment by Jordan-Nelson** [comment]
@pepie - It looks like you have already created a separate issue (https://github.com/aws-amplify/amplify-flutter/issues/5065) so I will respond on that issue. Thanks.

**Comment by pepie** [comment]
Thank you!
