### ISSUE TITLE
[Feature Request] DataStore watch()

### ISSUE THREAD

**Issue by mclark4386** [aws-amplify/amplify-flutter#468]
The current methods for `query`/`observe` are a bit clunky if you want to use a stream builder and expect new items to stream right into it (idiomatic of flutter). So I would like to request/purpose a `watch` command that would work the same as `query` except that it would return a stream that upon a change that would affect the previous results of the the query would sink a new set of results to processed/displayed.

One package that currently does this REALLY well is [Moor](https://pub.dev/packages/moor_flutter). There documentation about that function is [here](https://moor.simonbinder.eu/docs/getting-started/writing_queries/?#select-statements). I'm not asking for their expression system, simply the ability to `watch` to get an auto-updating stream of the query results.

Excited to see where this project goes 'cause it's off to a great start!

**Comment by haverchuck** [comment]
@mclark4386 Thanks for posting this suggestion! 

What would this `watch` command do that cannot be accomplished  with [observe](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter)?

Thanks!

**Comment by Tedsterh** [comment]
I also think this is a great idea as I am currently struggling on how to observe a specific model, is this currently possible?

**Comment by Jordan-Nelson** [comment]
Hello @mclark4386 - Thanks for opening this issue.

The `observeQuery()` API was recently released which supports the use case you are looking for. `observeQuery()` returns a stream of query snapshots. Snapshots are emitted in real-time as updates are made, similar to observe. Unlike observe, the snapshots from `observeQuery()` contain the entire result set for the given query, not just the updated item.

You can see an example in [the amplify-flutter docs for Observe Query](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time).

This also works great with StreamBuilder. Here is an example of what that might look like:

```dart
@override
Widget build(BuildContext context) {
  return StreamBuilder(
    stream: Amplify.DataStore.observeQuery(Post.classType),
    builder: (
      BuildContext context,
      AsyncSnapshot<QuerySnapshot<Post>> snapshot,
    ) {
      if (snapshot.data == null) {
        return Center(child: CircularProgressIndicator());
      }
      QuerySnapshot<Post> querySnapshot = snapshot.data!;
      return ListView.builder(
        itemCount: querySnapshot.items.length,
        itemBuilder: (context, index) {
          Post post = querySnapshot.items[index];
          return ListTile(title: Text(post.title));
        },
      );
    },
  );
}
```

Another nice feature of the observeQuery API is that each snapshot includes a boolean value to indicate if DataStore's sync process has completed. In that example above, if you want to show a progress indicator until cloud sync is complete, you can simply update the stream to the following:

```dart
stream: Amplify.DataStore.observeQuery(Post.classType)
  .skipWhile((snapshot) => !snapshot.isSynced)
```
