### ISSUE TITLE
Stuck in WebUI after authenticating with a certificate in iOS

### ISSUE THREAD

**Issue by LSch96** [aws-amplify/amplify-flutter#4689]
### Description

Our app offers a certificate-based login on managed devices using Cognito. This works perfectly fine on Android devices. But on iPhone, the user is stuck in the WebUI/Safari after successfully selecting their certificate. The website just seems to be loading indefinitely and no redirection to the app with a successful authentication result is triggered. 

The WebUI is initiated with the following parameters:
```
Amplify.Auth.signInWithWebUI(
      options: const SignInWithWebUIOptions(
        pluginOptions: CognitoSignInWithWebUIPluginOptions(
          isPreferPrivateSession: true,
        ),
      ),
    );
```

Thank you very much in advance for your support!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Open app on iOS and navigate to login, resulting in the WebUI to open
3. Select user certificate in WebUI and continue until the user should normally be redirected back to the app with a successful authentication result
4. User is stuck in Safari and no redirection is triggered

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.5

### Amplify Flutter Version

1.7.0

### Deployment Method

Custom Pipeline

**Comment by Equartey** [comment]
Hi @LSch96, thanks for taking the time to raise this issue. While we investigate, could you please provide answers to the following questions:

Do you notice this behavior on physical devices and/or the emulator? 

Do you notice this behavior with a different browser?

**Comment by LSch96** [comment]
Hi @Equartey, thanks for your reply!

I've noticed this behavior on a physical device, an iPhone 14 Pro with iOS 17.4.1 to be precise.

Regarding a different browser - iOS always seems to open the WebUI in Safari, even though Chrome is set as the standard browser. Unfortunately I couldn't figure out how to force the app to open the WebUI in Chrome.

**Comment by Equartey** [comment]
@LSch96 Thanks for the extra context. Can you help me understand how to reproduce this. 

> Our app offers a certificate-based login on managed devices using Cognito.

Can you elaborate on this setup? 

Did you use Amplify CLI to set this up?

**Comment by LSch96** [comment]
Hi @Equartey, sorry for the delayed response.
We use AzureAD as our external OIDC provider in Cognito. The users have user-certificates saved on their devices allowing them to authenticate.

Our configuration for Amplify looks something like this:
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-central-1_xxx",
            "AppClientId": "xyzjkfkjdsfd",
            "Region": "eu-central-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "CUSTOM_AUTH",
            "OAuth": {
              "WebDomain": "anydomain.auth.eu-central-1.amazoncognito.com",
              "AppClientId": "xyzjkfkjdsfd",
              "SignInRedirectURI": "myapp://redirect",
              "SignOutRedirectURI": "myapp://signout",
              "Scopes": [
                "openid"
              ]
            }
          }
        }
      }
    }
  }
}
```

In the meantime, we were wondering if we've missed a configuration similar to the intent-filter in the AndroidManifest.xml, but for iOS (i.e. adding myapp to the associated domains).
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="myapp" />
</intent-filter>
```
Maybe the actual problem is navigating back to the app after successful authentication?

**Comment by sauravkalia** [comment]
Any solution for this? I am having the same issue on the IOS Physical Device. It's working fine on the Emulator?

**Comment by sauravkalia** [comment]
@Equartey have added the same in `info.plist` as well. but still the same issue on IOS Physical Device

**Comment by LSch96** [comment]
Hi @Equartey, unfortunately it doesn't work for us either.

**Comment by lokalathlet** [comment]
Hi @Equartey, Is there an update to this issue?

**Comment by khatruong2009** [comment]
Hi @lokalathlet @sauravkalia, are you folks also using a custom provider like @LSch96 is above? Also, are your reproduction steps similar to what's listed in the Steps to Reproduction up above? If not, could you provide them?

**Comment by khatruong2009** [comment]
Hi @lokalathlet, @sauravkalia, and @LSch96, 

I was able to reproduce this issue on my physical device with a test app. Do you folks know around when this stopped working in your apps? Was this working in your apps previously? I'm currently on the latest version of iOS (17.4.1). Are you also using the latest version of iOS and was it working before any specific updates of amplify-flutter or iOS? I also tested this on previous versions of flutter and am getting the same issue. Thanks.

**Comment by lokalathlet** [comment]
Hi @khatruong2009, our app is still under development. We are new to iOS. The same app on Android works as expected. We use the latest versions of amplify_flutter and iOS. We therefore have no experience with older versions, whether it ever worked before. Thx for investigating in this issue.

**Comment by lokalathlet** [comment]
@khatruong2009, by the way, me and @LSch96 are in the same team.

**Comment by khatruong2009** [comment]
Hi @sauravkalia, @lokalathlet, I tested the solution that @sauravkalia mentioned and the fix worked for me. I had `platform :ios, '13.0'` set in my podfile but in xcode, I had minimum deployment set to 12.0. Once I changed it to 13.0 to match my podfile, the redirect started working as intended. Let me know if that works.

**Comment by LSch96** [comment]
Hello @sauravkalia and @khatruong2009, I've just tested it for the project @lokalathlet and myself are working on. And it works for us, too. Thank you very much, I'm going to close this issue now.
