### ISSUE TITLE
Type comparison with UnderlyingExceptions might not be working as expected.

### ISSUE THREAD

**Issue by jmartins-sh** [aws-amplify/amplify-flutter#4693]
### Description

Hello there! I'm currently testing scenarios where Cognito triggers (Lambdas) might return validation errors. While catching the `LambdaException`, I noticed that the underlying exception has a prefix of "_$".  

For example, I encountered `_$UserLambdaValidationException`, whereas the exception provided by amplify-flutter is simply `UserLambdaValidationException` (without the "_$").  

Is this expected behavior? Did I misunderstand something?

Appreciate the help. :)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a lambda that throws an Error("Not authorized to use the system.");
2. Catch the exception in flutter code
3. Compare the type of underlying exception (supposed to be the _$UserLambdaValidationException) inside the LambdaException with UserLambdaValidationException
4. The comparison returns false.

### Screenshots

![image (1)](https://github.com/aws-amplify/amplify-flutter/assets/16046723/de2d835a-95a7-4c7c-a675-cba73503d50b)

![image](https://github.com/aws-amplify/amplify-flutter/assets/16046723/5f4d5da3-f44f-42a9-bd84-1f8c3ced60c3)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.1

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @joaoantoniomartinsfilho 

_$UserLambdaValidationException extends UserLambdaValidationException. [Here](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito_dart/lib/src/sdk/src/cognito_identity_provider/model/user_lambda_validation_exception.g.dart) is the class definition. 

If you want to check if the exception is a UserLambdaValidationException you can do the following.

```dart
if (e is UserLambdaValidationException) {
  // handle exception 
}
```

Let me know if you have any other questions.

**Comment by joaoantoniomartinsfilho** [comment]
Hey @Jordan-Nelson, how's it going?

Thanks for the reply.

I did exactly what you suggested, the first screenshot shows the comparison using the is operator, but for some reason It is returning false.

**Comment by joaoantoniomartinsfilho** [comment]
Hey @Jordan-Nelson , I followed your suggestion, but even after that, the comparison using the `is` operator with `underlyingException` is returning `false`, as you can check in the screenshot below. 

Did I misunderstand something, or is there something else I need to consider?

![image](https://github.com/aws-amplify/amplify-flutter/assets/16046723/028ea323-0f3a-4f6a-82ed-a6f12c01885c)

**Comment by Jordan-Nelson** [comment]
@joaoantoniomartinsfilho You are not missing anything. That looks like unexpected behavior. We will see if we can reproduce it.

**Comment by Jordan-Nelson** [comment]
Hello @joaoantoniomartinsfilho - This does appear to be a bug. The exception is not getting mapped correctly. `e` should be type `UserLambdaValidationException`, not `LambdaException`.

The reason that you are not able to type check the underlying exception is that there are actually two `UserLambdaValidationException` types. One is public and extends `AmplifyException`. The other is private and is only intended to be used internally. The underlying exception is the private/internal one. However, if `e` was the correct type you would not need to check the type of `e.underlyingException`

Thanks for raising the issue. I will look into a fix and let you know when we have an update.

**Comment by jmartins-sh** [comment]
Hey @Jordan-Nelson, thanks for the reply. 

I just have one more question, the lib amplify-flutter is independent of Amplify Gen 2 right? Or Am I getting this wrong? My project is currently running in Amplify Gen 1 (amplify-cli and cloud). Will we face any issues using the lib 2.0? 

Appreciate it.
