### ISSUE TITLE
Update device_info_plus dependency

### ISSUE THREAD

**Issue by flodaniel** [aws-amplify/amplify-flutter#4698]
### Description

The device_info_plus dependency needs to be updated urgently as the updates contains the (by apple) required ios privacy manifest updates: https://pub.dev/packages/device_info_plus/changelog

This is the dependabot PR: https://github.com/aws-amplify/amplify-flutter/pull/4682

This is the dependency error:
```
Because amplify_auth_cognito 1.7.2 depends on amplify_analytics_pinpoint >=1.7.0 <1.8.0 which depends on device_info_plus ^9.0.0, amplify_auth_cognito 1.7.2 requires device_info_plus ^9.0.0.
So, because app depends on both amplify_auth_cognito 1.7.2 and device_info_plus 10.1.0, version solving failed.

```
### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

n/a

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.5

### Amplify Flutter Version

1.7.2

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @flodaniel, we are aware of this issue and working to resolve this. It's effort is being tracked on this issue https://github.com/aws-amplify/amplify-flutter/issues/4601, I'm closing this as a duplicate.
