### ISSUE TITLE
Storage Exception

### ISSUE THREAD

**Issue by exampaqs** [aws-amplify/amplify-flutter#470]
`  void _configureAmplify(GlobalProvider provider) async {
    
    if (!mounted) return;

    Amplify.addPlugins([AmplifyAuthCognito(), AmplifyStorageS3()]);

    try {

      await Amplify.configure(amplifyconfig);

    } catch (_) {

      configurationState = true;

    }

    configurationState = true;

  }`

then:

`Future<String> getImages({@required String urlKey}) async {

    String url;

    try {

      final GetUrlResult imageUrl = await Amplify.Storage.getUrl(key: urlKey);

      url = imageUrl.url;

    } on StorageException catch (e) {

      print('there was error: $e');

    } catch (e) {
      //I've tried running  await Amplify.configure(amplifyconfig); but got exception that
      //configuration is already done

      print(e)

    }

    return url;
}`

but if i call `getImages('my/s3/image/url')`, I got this exception:
StorageException(message: An unknown exception has happened. Please take a look at
I/flutter (15597): https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
I/flutter (15597): match your scenario, and file an issue with the details of the bug if there isn't., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.)

I tried configuring s3Storage after the Storage Exception but it gives an error that Storage has already been configured

**Comment by haverchuck** [comment]
@exampaqs Do you have any logs you could post?

**Comment by exampaqs** [comment]
> @exampaqs Do you have any logs you could post?

I did that in the post, but this is the full log:

E/amplify:flutter:storage_s3(15597): StorageException
E/amplify:flutter:storage_s3(15597): java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
E/amplify:flutter:storage_s3(15597): 	at com.amplifyframework.core.category.Category.getPluginIfConfiguredOrThrow(Category.java:239)
E/amplify:flutter:storage_s3(15597): 	at com.amplifyframework.core.category.Category.getSelectedPlugin(Category.java:215)
E/amplify:flutter:storage_s3(15597): 	at com.amplifyframework.storage.StorageCategory.getUrl(StorageCategory.java:75)
E/amplify:flutter:storage_s3(15597): 	at com.amazonaws.amplify.amplify_storage_s3.AmplifyStorageOperations$StorageOperations.getUrl(AmplifyStorageOperations.kt:66)
E/amplify:flutter:storage_s3(15597): 	at com.amazonaws.amplify.amplify_storage_s3.AmplifyStorageS3Plugin.onMethodCall(AmplifyStorageS3Plugin.kt:60)
E/amplify:flutter:storage_s3(15597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/amplify:flutter:storage_s3(15597): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/amplify:flutter:storage_s3(15597): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/amplify:flutter:storage_s3(15597): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/amplify:flutter:storage_s3(15597): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/amplify:flutter:storage_s3(15597): 	at android.os.Looper.loop(Looper.java:160)
E/amplify:flutter:storage_s3(15597): 	at android.app.ActivityThread.main(ActivityThread.java:6758)
E/amplify:flutter:storage_s3(15597): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:storage_s3(15597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/amplify:flutter:storage_s3(15597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
I/flutter (15597): there was error: StorageException(message: An unknown exception has happened. Please take a look at
I/flutter (15597): https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
I/flutter (15597): match your scenario, and file an issue with the details of the bug if there isn't., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.)

**Comment by Amplifiyer** [comment]
@exampaqs are there more logs from the first `configure()` call. It seems you are catching an exception but considering it a success in your app. It'll be interesting to see if you have any logs/exceptions thrown from first configure call.

**Comment by offlineprogrammer** [comment]
Hi @exampaqs 

Are you still seeing this issue? Can you please provide the logs as per @Amplifiyer msg above?

Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by offlineprogrammer** [comment]
Hi @exampaqs 

I am closing this issue for now 
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by MobilyteApps** [comment]
same issue
