### ISSUE TITLE
Cognito User pool authorization does not work at iOS

### ISSUE THREAD

**Issue by A-Kurimoto** [aws-amplify/amplify-flutter#471]
**Describe the bug**
https://docs.amplify.aws/lib/restapi/authz/q/platform/flutter#cognito-user-pool-authorization

Cognito User pool authorization does not work at iOS. It returns always 401 unauthorized.

Also, it works fine with Javascript.
https://docs.amplify.aws/lib/restapi/authz/q/platform/js#request-headers

**To Reproduce**
Following is my configuration.

```
{
        "UserAgent": "aws-amplify-cli/2.0",
        "Version": "1.0",
        "api": {
          "plugins": {
            "awsAPIPlugin": {
              "PlayAtPark": {
                "endpointType": "REST",
                "endpoint": "https://XXXXXX.execute-api.us-east-1.amazonaws.com/develop",
                "region": "us-east-1",
                "authorizationType": "AMAZON_COGNITO_USER_POOLS"
              }
            }
          }
        },
        "auth": {
          "plugins": {
            "awsCognitoAuthPlugin": {
              "UserAgent": "aws-amplify-cli/0.1.0",
              "Version": "0.1.0",
              "IdentityManager": {"Default": {}},
              "CredentialsProvider": {
                "CognitoIdentity": {
                  "Default": {
                    "PoolId": "us-east-1:XXXXXXX",
                    "Region": "us-east-1"
                  }
                }
              },
              "CognitoUserPool": {
                "Default": {
                  "PoolId": "us-east-1_XXXXXX",
                  "AppClientId": "XXXXXXXXX",
                  "Region": "us-east-1"
                }
              },
              "Auth": {
                "Default": {
                  "authenticationFlowType": "USER_SRP_AUTH"
                }
              }
            }
          }
        }
      }
```

And following is source code.

```
await Amplify.Auth.signIn(
    username: 'hoge',
    password: 'XXXXXXX',
);

RestResponse response = await Amplify.API.get(
                          restOptions: RestOptions(
                              path: '/v1/hoge', apiName: 'XXXXXX'))
                      .response;
```

**Expected behavior**

I checked the request header.

- Javascript
```
"Authorization": "Bearer eyJraWQiOiJtd01Dc......,
```

- iOS
```
"Authorization": "eyJraWQiOiJsTkl4RHNk......",
```
 
I think this request should contains 'Bearer'.
(It may be the cause of amplify-ios)

https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/UserPoolRequestInterceptor.swift#L41

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [ ] Android
- [x] iOS

I haven't checked at Android.

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS14.4

**Comment by alokjkumar** [comment]
I have the same issue. Works in android if I manually add the Authorization header but not in iOS

**Comment by Verditer** [comment]
@alokjkumar  how were you able to manually add the authorization header. 
The below code is not working, 400 when headers are added and 401 when headers are removed

`CognitoAuthSession res = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));

      final id = res.userPoolTokens.idToken;
      final at = res.userPoolTokens.accessToken;

      //authorization header is not automatically added
      //as mentioned in decoumentation
      RestOptions options = RestOptions(
          path: '/items',
          headers: {'Authorization': '$id', 'testHeader': 'HelloWorld'});

      RestOperation restOperation = Amplify.API.get(restOptions: options);`

**Comment by alokjkumar** [comment]
@Verditer seem to be using very similar code. Not sure how it differs...

``` 
static Future<dynamic> makeAPICall(BuildContext context, DataModel data) async {
    try {
      String inputJson = data.toJson();

      RestOptions options = RestOptions(
        path: '/api-call',
        apiName: 'myAPI',
        headers: {'Authorization': await getIdToken()},
        body: Uint8List.fromList(inputJson.codeUnits),
      );

      RestOperation restOperation = Amplify.API.post(restOptions: options);

      RestResponse response = await restOperation.response;

      String jsonString = String.fromCharCodes(response.data);
      dynamic json = jsonDecode(jsonString);
      return json;
    } on ApiException catch (e) {
      return Future.error(e.message);
    }
  }
```

```
Future<String> getIdToken() async {
    try {
      CognitoAuthSession session = await auth.fetchAuthSession(request: AuthSessionRequest(options: CognitoSessionOptions(getAWSCredentials: true)));
      return session.userPoolTokens.idToken;
    } catch (e) {
      return Future.error(e);
    }
  }
```

Doesn't work for iOS though - only Android. Issue still persists for iOS

**Comment by Verditer** [comment]
@alokjkumar thanks for the response. A new flutter app with auth/api created by amplify seems to be working with cognito pool and social provider. Flutter app with auth imported (with existing cognito user pool with social id provider) and API added manually in amplifyconfiguration with auth set to cognito pool isn't working. seems some configuration is missing.
What was your setup auth/api freshly created by amplify or existing resources are imported.

**Comment by alokjkumar** [comment]
@Verditer - I largely followed the second route. Auth config was generated through Amplify CLI but the API was built using SAM so had to be imported into the config. Here's my amplifyconfiguration file.
```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "<identity_pool_id>",
                            "Region": "<region>"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "<user_pool_id>",
                        "AppClientId": "<app_client_id>",
                        "AppClientSecret": "<app_client_secret>",
                        "Region": "<region>"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "myAPI": {
                    "endpointType": "REST",
                    "endpoint": "<api_endpoint>",
                    "region": "<region>",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }
}''';
```

**Comment by Verditer** [comment]
@alokjkumar thanks.. for the input
 i found the issue..with the code.. the query paramters are not properly escaped and that was reason authentication header and tokens were getting truncated.

**Comment by vishalkhedeker** [comment]
@Verditer can you tell me how exactly the issue was resolved? im stuck in similar situation.

**Comment by Verditer** [comment]
@vishalkhedeker  request parameters are escaped for instance # is replaced with %23

**Comment by alokjkumar** [comment]
@haverchuck any idea of when this might get looked at? Developing without being able to make API calls is a little prohibitive...

**Comment by A-Kurimoto** [comment]
I could avoid this error.

As @alokjkumar says, it's a way to add headers directly, but I was able to get it to work on iOS by customizing the identity source with the Cognito authorizer instead of Authorization.

<img width="414" alt="スクリーンショット 2021-05-09 9 24 19" src="https://user-images.githubusercontent.com/19422621/117556866-65921980-b0a8-11eb-880a-59810bbbf170.png">

```
static Future<dynamic> makeAPICall(BuildContext context, DataModel data) async {
    try {
      String inputJson = data.toJson();

      RestOptions options = RestOptions(
        path: '/api-call',
        apiName: 'myAPI',
        // headers: {'Authorization': await getIdToken()},
        headers: {'x-custom-authorization': await getIdToken()}, // use custom identity source header
        body: Uint8List.fromList(inputJson.codeUnits),
      );

      RestOperation restOperation = Amplify.API.post(restOptions: options);

      RestResponse response = await restOperation.response;

      String jsonString = String.fromCharCodes(response.data);
      dynamic json = jsonDecode(jsonString);
      return json;
    } on ApiException catch (e) {
      return Future.error(e.message);
    }
  }
```

However, requests include both Authorization and x-custom-authorization header and it's a waste of resource.
This is a temporary workaround and we are waiting for a fix.

**Comment by ragingsquirrel3** [comment]
@A-Kurimoto and @alokjkumar sorry you have been facing this issue and thanks for reporting it, as well as detailed descriptions of errors, configurations, and workarounds. I spent some time configuring my own example REST API with cognito user pool auth mode and found a way to address this with the backend configuration after initially reproducing the error and workaround you describe. Because [REST w cognito auth mode is not supported by the CLI](https://github.com/aws-amplify/amplify-cli/issues/3390) this process is unfortunately a little manual and error-prone.

Option 1) Do not manually add any headers to the request from Flutter and setup API gateway to accept the access token that is attached to the request by default. When following the [instructions for configuring API gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html) I found it necessary to follow the instructions for step 7 (skip step 6), specifically setting the Oauth scope to `aws.cognito.signin.user.admin`. In summary, here are the instructions in API gateway (after having added the "Authorization" header as authorizer and following steps 1-5):

* Select Resources on the left, Under Resources, and each individual resource path, select Any. You will see a Test section, Method Request, Method Response, Integration Request, etc
* Click on Method Request, under Settings, Authorization, click on edit. In the drop down, select the User Pool authorizer, then click on the check mark to save it.
* Click on the OAuth Scopes and add aws.cognito.signin.user.admin.
* Click on Actions, deploy API, and select the deployment stage, and click Deploy.

This is needed because by default, the Android and iOS libraries (and thus Flutter) automatically add an access token as the "Authorization" header when using cognito auth mode and API gateway needs some additional configuration to accept it. More info on this scope is described [here](https://stackoverflow.com/questions/53149091/what-does-the-aws-cognito-signin-user-admin-scope-mean-in-amazon-cognito).

Option 2) Follow the workaround @A-Kurimoto described by naming the header something besides "Authorization" (e.g. "x-custom-authorization") and attach an ID token to the header from flutter. The different name is needed because the iOS library adds the access token as the "Authorization" header, overwriting whatever might have been added from flutter. Android does not overwrite, which explains the platform difference.

This confusion gets down to the difference between id/access tokens, which is touched a little more in [JS docs](https://docs.amplify.aws/lib/restapi/authz/q/platform/js#note-related-to-use-access-token-or-id-token). Again, this confusion comes from the automatic assignment of an access token from Android/iOS libraries and additional backend configuration needed.

Let me know if you are still facing this issue after following these configuration instructions.

**Comment by Birxdk** [comment]
Workaround that worked for me on iOS:

Set the authorizationType to `NONE` in the flutter amplifyconfig, and manually set the headers. By setting to `NONE`, the Amplify SDK doesn't overwrite the `Authorization` header and you can now use the Id token instead.

In your Authorizer in the API Gateway Console, set the `Token Source` to `Authorization`, and use the authorizer for the endpoints.

Setting headers in Flutter:
```
...
RestOptions options = RestOptions(
        path: '/api-call',
        apiName: 'myAPI',
        headers: {'Authorization': await getIdToken()},
        body: Uint8List.fromList(inputJson.codeUnits),
      );
RestOperation restOperation = Amplify.API.post(restOptions: options);
...
```

amplifyconfig:
```
...
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "myAPI": {
                    "endpointType": "REST",
                    "endpoint": "<api_endpoint>",
                    "region": "<region>",
                    "authorizationType": "NONE"
                }
            }
        }
    }
```

Hope this helps for others too..

**Comment by dorontal** [comment]
@ragingsquirrel3 and @A-Kurimoto I have tried your workaround and believe I followed your instructions very carefully - skipping step 6 here
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html
and adding the auth scope `aws.cognito.signin.user.admin` - so now I no longer get a 'Missing authorization header' error, which is great, but I do get a 502 error "Internal Server Error" -- if this workaround has stopped working for anybody, I would very much appreciate a holler.

**Comment by dorontal** [comment]
Yup. Just tried this procedure (Option 1, of the @A-Kurimoto solution above) re-did it all from scratch and I still get the "Internal Server Error" when calling
```dart
   await restOperation.response
```
Specifically, the error reported is
```
Exception has occurred.
RestException (RestException{response=RestResponse{statusCode=502, headers={date: Mon, 13 Jun 2022 15:06:13 GMT, x-amz-cf-pop: PHL50-C1, content-length: 36, x-amz-apigw-id: TqnPxFb1IAMFysg=, x-amzn-errortype: InternalServerErrorException, x-amzn-requestid: 5fb8c5b1-45d1-4265-962e-3b5764d8e12e, access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, access-control-allow-methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT, access-control-expose-headers: Date,X-Amzn-ErrorType, via: 1.1 4f7671bb51952e26d4af9f468d98bc84.cloudfront.net (CloudFront), access-control-allow-origin: *, content-type: application/json, x-cache: Error from cloudfront, x-amz-cf-id: QGf9BM6WigIHSYYRVhZMtRAh6UoTSHdupgBG-MWIKTIoPzs5HNOibw==}, body={"message": "Internal server error"}}})
```

**Comment by Arrnav** [comment]
@A-Kurimoto 's workaround worked wonders for me, combined with @Birxdk 's suggestion to set Authorization type as NONE. I feel keeping `Token Source` as the original `Authorization` helps avoiding issues with other services in the future. Using Xcode 14 for Swift, iOS with Amplify Auth and API.
