### ISSUE TITLE
Update connectivity_plus dependency

### ISSUE THREAD

**Issue by yeeahh** [aws-amplify/amplify-flutter#4711]
### Description

The connectivity_plus dependency needs to be updated urgently as the updates contains the (by apple) required ios privacy manifest updates: https://developer.apple.com/support/third-party-SDK-requirements/

This is the dependency error:

![image](https://github.com/aws-amplify/amplify-flutter/assets/19768643/35525b3a-6b4b-43ab-9e47-650891250b1f)

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Just update The connectivity_plus dependency

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.5

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @yeeahh, we are aware of this issue and working to resolve this. It's effort is being tracked on this ticket https://github.com/aws-amplify/amplify-flutter/issues/4601, I'm closing this as a duplicate.
