### ISSUE TITLE
Datastore without Cloud sync - Android build failing

### ISSUE THREAD

**Issue by mjaydeep01** [aws-amplify/amplify-flutter#4712]
### Description

Tryin to setup datastore without syncing to cloud (without cognito). Working fine for IOS, but build failing for Android with following error.

* What went wrong:
Execution failed for task ':amplify_datastore:generateDebugRFile'.
> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
   > /Users/../.gradle/caches/transforms-3/4ca4167c123fdb664319b0d36b43d617/transformed/com.amplifyframework.auth.cognito-r.txt

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (4 weeks ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1

dependencies:
  amplify_api: ^1.7.0
  amplify_datastore: ^1.7.0
  amplify_flutter: ^1.7.0

Followed Android platform setup introduction from "https://docs.amplify.aws/flutter/start/project-setup/platform-setup/#android"

**android/build.gradle**

buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

**Error**
* What went wrong:
Execution failed for task ':amplify_datastore:generateDebugRFile'.
> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
   > /Users/mjaydeep/.gradle/caches/transforms-3/4ca4167c123fdb664319b0d36b43d617/transformed/com.amplifyframework.auth.cognito-r.txt

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.4

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@mjaydeep01 sorry that you are facing this issue and thanks for reporting it. would you share the the Gradle distributionUrl from the android/gradle/wrapper/gradle-wrapper.properties please.

**Comment by NikaHsn** [comment]
@mjaydeep01 The issue you're encountering appears to be related to version incompatibilities in your Android build setup.
With Ampliy Flutter 1.8.0 android dependecies are updated, would it be possible for you to update your project to use below versions?
- amplify flutter 1.8.0
- kotlin version 1.9.10
- java version 17 
- gradle version 8.1.0 
- gradle distribution url 8.1 (distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-all.zip)

**Comment by Jordan-Nelson** [comment]
@mjaydeep01 were you able to @NikaHsn's suggestion above?

**Comment by mjaydeep01** [comment]
@NikaHsn @Jordan-Nelson, Yes, its working fine after using above configuration. Thanks.

**Comment by Jordan-Nelson** [comment]
@mjaydeep01 I'm glad to hear that. I will close this issue then.
