### ISSUE TITLE
Amplify confirm sign in with custom authentication flow timing out

### ISSUE THREAD

**Issue by philyang07** [aws-amplify/amplify-flutter#4719]
### Description

Refer to this https://github.com/aws-amplify/amplify-flutter/issues/4541, I'm just raising this again in case it got lost, feel free to close this one and reopen the one I linked.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

https://github.com/aws-amplify/amplify-flutter/issues/4541

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.9

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@philyang07 sorry that you are still facing this issue, I've reponed the #4541 and am closing this one as duplicate.
