### ISSUE TITLE
Flutter WEB

### ISSUE THREAD

**Issue by bobosette** [aws-amplify/amplify-flutter#473]
Hi. Did you plan to release something for Flutter Web??

Thank you

**Comment by SalahAdDin** [comment]
@bobosette Oh shit, does it not work on web now?

**Comment by bobosette** [comment]
No.... "Could not configure aws amplify" and it throws an error.
I don't know if there is to setup something

**Comment by haverchuck** [comment]
@SalahAdDin @bobosette We are currently investigating adding the web platform to amplify-flutter.

**Comment by bobosette** [comment]
Thank you. Would you know how much time does it take??

**Comment by SalahAdDin** [comment]
> No.... "Could not configure aws amplify" and it throws an error.
> I don't know if there is to setup something

What's about **Flutter Desktop**?

**Comment by roelvandenbranddvc** [comment]
This has been requested before: https://github.com/aws-amplify/amplify-flutter/issues/234 

If we put our votes on the same feature, we might get it further up the backlog ;-)

**Comment by haverchuck** [comment]
@roelvandenbranddvc Thank for noting the previous issue.  I'm going to close this one, in order to consolidate all feedback on  #234.
