### ISSUE TITLE
Flutter - AWS Amplify - Network error in authentication when building apk, no issues in debug/emulation

### ISSUE THREAD

**Issue by salvatoresaporito** [aws-amplify/amplify-flutter#4782]
### Description

I am working a on basic Flutter 3.19.6 app, target android. I can nicely use a Cognito user pool for authentication and attach otehr AWS permissions. I can see the users being created in the Cognito user pool in AWS console.

I can build a debug apk, and run in emulator

`flutter run`

and here the authentication form works well.

However, if I do

`flutter build apk`

The first login/account creation is impossible and a 'Network error message' is displayed.
See screenshots

I have tried also the following, it did not solve

`flutter build apk --no-shrink`

This reproduces across a variety of android phyiscal device, only when using the release apk. Is it something related to storing credentials?

I have followed the documentation getting started tutorials carefully, completed

```
amplify init
amplify configure
amplify add auth
amplify push

```
My pubpsec:

```
dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.8.0
  amplify_auth_cognito: ^1.8.0
  amplify_authenticator: ^1.6.0
  amplify_storage_s3: ^1.8.0

```
My build.gradle:

`   ext.kotlin_version = '1.9.23'`

My app/build.gradle
```

    minSdkVersion 28
    targetSdkVersion  flutter.targetSdkVersion
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

```
class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    configureAmplify();
  }

  @override
  Widget build(BuildContext context) {
    return authenticateApp('TEST', const HomePage(title: 'TEST')); // Check for authentication, then display the home page
  }
}

Widget authenticateApp(String appTitle, Widget appContext) {
  return Authenticator(
    child: MaterialApp(
      title: appTitle,
      initialRoute: '/',
      routes: {
        '/': (context) => appContext,
      },
      builder: Authenticator.builder(),
    ),
  );
}
```

`flutter build apk`
install on android device via apk release file

### Screenshots

![IJOGCgWkt](https://github.com/aws-amplify/amplify-flutter/assets/159818369/43e871dc-e6c5-4665-bdb6-eca4f5b6b42b)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.6

### Amplify Flutter Version

1.8.0

### Deployment Method

Amplify CLI

**Comment by stonedMoose** [comment]
@salvatoresaporito I have the same issue. Did you manage to find a workaround ?

**Comment by salvatoresaporito** [comment]
it was pretty trivial, but not so well document imho

See here and update your manifest accordingly:

https://docs.flutter.dev/deployment/android#build-the-app-for-release
Review the app manifest
[#](https://docs.flutter.dev/deployment/android#review-the-app-manifest)

Review the default [App Manifest](https://developer.android.com/guide/topics/manifest/manifest-intro) file, AndroidManifest.xml. This file is located in [project]/android/app/src/main. Verify the following values:

application
    Edit the android:label in the [application](https://developer.android.com/guide/topics/manifest/application-element) tag to reflect the final name of the app.
uses-permission
    Add the android.permission.INTERNET [permission](https://developer.android.com/guide/topics/manifest/uses-permission-element) if your application code needs Internet access. The standard template doesn't include this tag but allows Internet access during development to enable communication between Flutter tools and a running app.
