### ISSUE TITLE
Listen to Amplify.Hub events within Authenticator?

### ISSUE THREAD

**Issue by ibariens** [aws-amplify/amplify-flutter#4783]
### Description

I'm trying to listen for Authentication events within the Authenticator package.
The use case is to listen for a `AuthHubEventType.signedIn` event, so an API can be called from a BLOC that was created before using the `authBuilder`

I currently tried to add on multiple locations: 
```

Amplify.Hub.listen(
        HubChannel.Auth,
        (msg) {
          safePrint("Incoming $msg");
        },
        onError: (msg) {
          safePrint("Error $msg");
        },
      );
```

but this never gets called. 
 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Add:

```
Amplify.Hub.listen(
        HubChannel.Auth,
        (msg) {
          safePrint("Incoming $msg");
        },
        onError: (msg) {
          safePrint("Error $msg");
        },
      );
```

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.21.0

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@ibariens I am not able to reproduce this. The [Auth sample app](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito/example/lib/main.dart) in this repo has a hub listener and uses the authenticator. I attempted to reproduce this was not able to. Can you share a minimal reproduction that includes how the authenticator and the hub listener are integrated into you app?

**Comment by ibariens** [comment]
@Jordan-Nelson , everything worked as it should. I assumed that AuthHubEventType.signedIn would also be emitted if the user was authenticated through persistence, which unfortunately doesn't.  The internal `StateMachineBloc` does emit an `AuthenticatedState`, but I guess this is the same issue as [#3245](https://github.com/aws-amplify/amplify-flutter/issues/3245) and https://github.com/aws-amplify/amplify-flutter/issues/3228 .

Thanks for the help! I'll close this issue.
