### ISSUE TITLE
How do we update custom attributes of a user in aws cognito user pool using amplify flutter

### ISSUE THREAD

**Issue by pavan613** [aws-amplify/amplify-flutter#487]
**Describe the bug**
How do we update custom attributes of a user in aws cognito user pool using amplify flutter. 
If this feature is not there in flutter at the moment when is it expected to come.
Is there any work around for this?

**Comment by haverchuck** [comment]
@pavan613 You can currently create custom attributes for a new user with the signup api; the APIs to update cognito attributes (both custom and standard) are actively under development.

**Comment by SalahAdDin** [comment]
@haverchuck It is related to the **API** `updateAttributes` function, isn't it?

**Comment by Jordan-Nelson** [comment]
Hi @pavan613 - The APIs to update user attributes are now available in version 0.1.5. The [docs on user attributes](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter#update-user-attribute) have been updated to include the new APIs. I am going to close out this ticket as I believe those APIs are what you are looking for.
