### ISSUE TITLE
Login with email is slow

### ISSUE THREAD

**Issue by harini18** [aws-amplify/amplify-flutter#4882]
### Description

I am using HostedUI for my login purpose. Login via social (Google & Apple) are working fine, but Login with Email is taking almost 5 to 10 seconds.

I am using
dependencies:
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_flutter: ^2.0.0

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Regular Login with Email.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.6

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Can run in debug mode with Flutter dev tools open and capture the network requests?

**Comment by harini18** [comment]
![Screenshot 2024-05-13 at 1 24 42 PM](https://github.com/aws-amplify/amplify-flutter/assets/68139/1b2303e9-ba9c-4de5-8765-f3219bc87cb5)
![Screenshot 2024-05-13 at 1 25 22 PM](https://github.com/aws-amplify/amplify-flutter/assets/68139/ed2328df-1c14-48f0-8b46-b51ffcd98082)
![Screenshot 2024-05-13 at 1 26 26 PM](https://github.com/aws-amplify/amplify-flutter/assets/68139/0d04466d-4c0c-4176-baac-8c1fd7e9cab7)

**Comment by harini18** [comment]
![Screenshot 2024-05-13 at 1 28 38 PM](https://github.com/aws-amplify/amplify-flutter/assets/68139/ee6ebbce-a507-42e8-91bf-c9c2b0d3353f)

sometimes around 10 seconds

**Comment by Jordan-Nelson** [comment]
@harini18 - From the first screenshot it looks like one of the network requests takes significantly longer than the others. This appears to be the InitiateAuth call. Do you have any Cognito Auth triggers enabled for this user pool?

**Comment by harini18** [comment]
No. It is simple setup. It was setup via amplify. 

There are no network triggers.

**Comment by harini18** [comment]
Also Login via Social works fine - look at this screenshot

![Screenshot 2024-05-13 at 1 40 09 PM](https://github.com/aws-amplify/amplify-flutter/assets/68139/f9e1529b-c123-4334-8b28-ab9e31ce5c2a)

**Comment by harini18** [comment]
Any updates?

**Comment by Jordan-Nelson** [comment]
@harini18 - I am not able to reproduce this. Can you share more info about how you set up the backend? Did you using the [Amplify CLI](https://docs.amplify.aws/gen1/flutter/start/getting-started/installation/) or did you use [Amplify Gen 2](https://docs.amplify.aws/flutter/start/quickstart/#create-backend)?

**Comment by Jordan-Nelson** [comment]
Can you walk me through what options you selected when creating the project?

Is US West 2 the geographic location that you are located closest to? I see most of the requests are fairly quick so I don't think latency is the issue here but would like to rule that out.

Do you use a VPN or any proxy tools?

**Comment by harini18** [comment]
We setup Auth - for email, via Google and via Apple.

We do not use any other Amiplfy packages other than Auth.

Not using VPN or proxy tools.

I am not sure why that one call is consistently taking 5 to 10 seconds.

**Comment by harini18** [comment]
Yes it is happening on both iOS and Android. Also in physical device.

**Comment by NikaHsn** [comment]
thanks @harini18 for the info. we will look into this issue and get back to you with any updates.

**Comment by harini18** [comment]
Thanks

**Comment by Equartey** [comment]
Hey @harini18. We could not reproduce this on a existing app. 

We're still working on reproducing this on a fresh app. 

We will provide more updates as we have them.

**Comment by Jordan-Nelson** [comment]
@harini18 I was unable to reproduce this with a new Amplify app following the instructions you provided? If you create a branch new Amplify app following those steps do you see this issue?

**Comment by Jordan-Nelson** [comment]
Hello @harini18 I am going to close this out since we were unable to reproduce and we have not heard back.
