### ISSUE TITLE
AmplifyAPI modelProvider not working moving from v1 to v2

### ISSUE THREAD

**Issue by coldfingersnz** [aws-amplify/amplify-flutter#4889]
### Description

My app has been running well using the amplify_flutter: ^1.0.0 packages. I upgraded to ^2.0.0 and now it shows **modelProvider isn't defined.** 

Switching back to 1 fixes the issue. I am logging this here because I'm sure others will run into this problem as this line of code is directly from the online Amplify flutter documentation. 

The code when defining API is:

`final api = AmplifyAPI(modelProvider: ModelProvider.instance);`

Error: No named parameter with the name 'modelProvider'.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Follow the instructions here: https://docs.amplify.aws/gen1/flutter/build-a-backend/graphqlapi/set-up-graphql-api/
2. Around the initializing you are directed to define API as:

`final api = AmplifyAPI(modelProvider: ModelProvider.instance);`
You will see error in IDE

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type DeleteMe @model @auth(rules: [{allow: private, operations: [read, update]}, {allow: owner}]) {
  id: ID!
  title: String!
  progress: String
  imageUrl: String
  imageKey: String
  notes: String
  email: String
  date: String
  stripeDesc: String
}
```

**Comment by coldfingersnz** [comment]
Thanks, Jordan, nailed it. 
I don't know how you guys keep track of all the changes in so many plugins.

Keep up the good work and I look forward to seeing the flutter documentation catch up :-)

**Comment by bebopinbebop** [comment]
Hey that worked! I was following the Flutter AWS integration tutorial and it resolved the api call:

https://docs.amplify.aws/gen1/flutter/start/getting-started/integrate/

**Comment by Jordan-Nelson** [comment]
For anyone that might still be facing issue migrating from v1 to v2 there is a full migration guide here: https://docs.amplify.aws/gen1/flutter/start/project-setup/upgrade-guide/.

If you are facing a scenario that is not covered there please open a new issue. Thanks.
