### ISSUE TITLE
Get user data as the response of signUp request

### ISSUE THREAD

**Issue by babytiger0929** [aws-amplify/amplify-flutter#490]
I am trying to implement Amplify authentication system in flutter project, and need to get user data as a response in signUp request just like in the web.

In web:
Auth.signUp({some user data}).then(user => {
    ... (Here I can get user data such as userSub)
});

I wanna to get the user data in similar way especially userSub.
Any good solution?
(In my case, username is email.)

**Comment by Amplifiyer** [comment]
You can use the [`fetchAuthSession`](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter) in amplify-flutter to get the userSub. It will return an instance of [`CognitoAuthSession`](https://github.com/aws-amplify/amplify-flutter/blob/c773828dd91ded62e25eece9b8945f07fa551957/packages/amplify_auth_cognito/lib/src/CognitoSession/CognitoAuthSession.dart)

**Comment by babytiger0929** [comment]
I think I can use fetchAuthSession only after I logged in.
Can I use this just after creating a new account?

**Comment by Amplifiyer** [comment]
@babytiger0929 I believe that's accurate. Adding @haverchuck to verify my understanding.

**Comment by sanjidbillah** [comment]
@babytiger0929 did you get solution?

**Comment by babytiger0929** [comment]
not yet :(

**Comment by yucomds** [comment]
Any update on this?
