### ISSUE TITLE
correctClockSkew option

### ISSUE THREAD

**Issue by jtushar53** [aws-amplify/amplify-flutter#4914]
### Description

We recently got live using aws amplify , have a large pool of users onboarded already. and now due to the nature of user's persona who are regularly travelling and have to change time on regularly basis n their phone. we started facing Signature not yet current issue. 

aws js sdk have option to correct time difference between client and server(now enabled by default in aws sdk 3) , amplify-flutter do not have such option. Please help , users cannot correct timezone on their devices, even a workaround from app or backend will work for us now .

### Categories

- [ ] Analytics
- [x] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Setup amplify flutter 
add api gateway and lambda function
change phone's time to be  +5 minute 
call API using amplify-flutter classes from flutter app

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @jtushar53 sorry to hear this is creating friction for your users. I understand this is an important feature and we are investigating solutions. 

We already have an open feature request for this: https://github.com/aws-amplify/amplify-flutter/issues/4174.  As such, I'm closing this as a duplicate. 

Please leave a thumps up or comment over there to better help us track interest.
