### ISSUE TITLE
Customize title of Authentication with  Amplify flutter Authentication UI 

### ISSUE THREAD

**Issue by KumarHalder** [aws-amplify/amplify-flutter#4917]
I am trying to update the text "Log in using", and preferably remove it.  I did not find anything to do that. I am using a mix of prebuilt ui with customization in flutter amplify_authenticator package. 

![image](https://github.com/aws-amplify/amplify-flutter/assets/57747618/62b65ab9-28d7-4db5-b58c-a66aff4f476a)

I have tried all AuthStringResolver as follows.

```AuthStringResolver AuthStringResolver({
  ButtonResolver? buttons,
  DialCodeResolver? dialCodes,
  InputResolver? inputs,
  MessageResolver? messages,
  TitleResolver? titles,
  InstructionsResolver? instructions,
})
```

They work for pretty much all the text in different components. However, I could not change the title of tab. Any help regarding this would much appreciated.

**Comment by Jordan-Nelson** [comment]
Hello @KumarHalder - It looks like you are already customizing some of the content in the authenticator. This content is considered an input label and can be customized with a custom `InputResolver`. There is no way to remove the Text widget (without rebuilding the full screen) but you can return an empty string.

```dart
class CustomInputResolver extends InputResolver {
  const CustomInputResolver();

  @override
  String title(BuildContext context, InputField field) {
    switch (field) {
      case InputField.usernameType:
        return '';
      default:
        return super.title(context, field);
    }
  }
}
```

```dart
return Authenticator(
  stringResolver: AuthStringResolver(
    inputs: CustomInputResolver(),
  ),
  // other props
);
```

**Comment by Jordan-Nelson** [comment]
Let me know if you have any other questions

**Comment by KumarHalder** [comment]
Thank you so much! That worked! I wished there was more documentation about this. I believe a lot can be achieved by customization, and due to proper documentation, we are missing a lot.
