### ISSUE TITLE
How to use SyncExpression with GroupPredicate

### ISSUE THREAD

**Issue by harrynguyen2510** [aws-amplify/amplify-flutter#4919]
### Description

This might not a bug but it doesn't run properly when re-evaluate Sync Expression 
It works when I run basic expression like 

```dart
SyncExpression: [
    DataStoreSyncExpression(MessageItem.classType, () => MessageItem.ID.eq('id')), 
]
```

But in the case that I have a list of ids, how can I apply for multiple expression for same Schema model
For example, this is the code I reckoned but it doesn't work 

```dart
DataStoreSyncExpression(MessageItem.classType, () {
  print('syncListChatroomid: $syncListChatroomid');
  if (syncListChatroomid.isNotEmpty) {
    List<QueryPredicate> predicates = [];
    for (String roomid in syncListChatroomid) {
       predicates.add(MessageItem.ONCHATROOMID.eq(roomid));
    }

    QueryPredicateGroup combinedPredicates = QueryPredicateGroup(QueryPredicateGroupType.or, predicates);
    return combinedPredicates ;
  } else {
    return MessageItem.ID.eq('no-id');
  }
}),
```

Logic code is at the beginning, if list is empty, sync no Message item
Once I got list of chatroomids, I run:

```dart
try {
      await Amplify.DataStore.stop();
    } on Exception catch (error) {
      safePrint('Error clearing DataStore: $error');
    }

    try {
      await Amplify.DataStore.start();
    } on Exception catch (error) {
      safePrint('Error starting DataStore: $error');
    }
```

The sync seem works, it print out values on list, but return no data, no bug detected 
What is the right way to write multiple predicates when we re-evaluate syncExpression?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Run SyncExpression at the begining, fetch no data
Received data of List<String> chatroomids 
Re-evaluate sync 
SyncExpression trigger, print out data of chatroomids , but return no MessageItem

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

12.12.0

### Deployment Method

Amplify CLI

**Comment by harrynguyen2510** [comment]
update:
I have tried instead of stop, I run Datastore.clear when re-evaluate syncepxression, it's working but not good UX because Clearing take times, have to fetch data again

**Comment by Jordan-Nelson** [comment]
@harrynguyen2510 are you seeing the same behavior on Android and iOS?

**Comment by Jordan-Nelson** [comment]
@harrynguyen2510 if you are still facing this issue can you let us know what platform(s) you are seeing this on?

I had a few follow up questions as well:
- Can you share the schema you are using (at leas the portion involving the models used in the sync expression)?
- Are you seeing selective sync work on the initial sync if `syncListChatroomid` is populated?
- Are you seeing the print statement execute after calling stop/start?

**Comment by Jordan-Nelson** [comment]
@harrynguyen2510 I am going to close this out since we have not heard back

**Comment by stephenjen** [comment]
Hi @Jordan-Nelson , I have a model for Friends and then another model for UserStatistics, and I'm trying to use SyncExpression to allow users to sync the user statistics for their friends.  The method described by @harrynguyen2510 , is this an efficient way to go about achieving this?

**Comment by stephenjen** [comment]
@harrynguyen2510 , I was also having the same issue where I needed to run DataStore.clear() in order to use updated syncExpressions, but in 2.4.1 I can use DataStore.close() instead.

**Comment by sampaio96** [comment]
Hi. Can you try replacing:

```
DataStoreSyncExpression(MessageItem.classType, () => MessageItem.ID.eq('id')),
```

with:

```
DataStoreSyncExpression(MessageItem.classType, () => MessageItem.ID.eq(MessageItemIdentifier(id: 'id'))),
```

For `ONCHATROOMID`, there probably are no changes needed.

See the [documentation for Amplify Gen 2](https://docs.amplify.aws/gen1/flutter/start/project-setup/upgrade-guide/#models--query-predicates-graphql-api--datastore) for more details.

I don't know if this would change anything. I do know that the QueryPredicate code does not enforce type restrictions so it's  very hard to detect this issue.
