### ISSUE TITLE
Data not updated by API GraphQL

### ISSUE THREAD

**Issue by mazidahmad** [aws-amplify/amplify-flutter#4939]
### Description

Hi, I am having an issue when trying to update data from a Customer table. After doing API.mutate, there is no errors and it returns the data but not the modified data. The attribute data is not updated in Datastore or DynamoDB.

Another way, is I try to request GraphQL manually by Appsync queries, It works updated but it should contain _version data when sending the mutation. If the _version is not included, it won't update the data. I want to try by adding _version attribute here but in the model, there is no _version attribute here.

![image](https://github.com/aws-amplify/amplify-flutter/assets/45102623/2eae970f-8dc0-420f-ba4c-76cc4e671257)

Thank you

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Get Customer data by Id
2. Customer found
3. Change any attributes
4. Send request update mutation to API GraphQL

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.1

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Customer @model @auth(rules: [{ allow: public }, { allow: private }]) {
  id: ID!
  cognitoSub: String
  customerLat: Float
  customerLng: Float
  customerFirstname: String!
  customerLastname: String!
  customerStatusValue: Int
  customerType: Int!
  customerEmail: String!
  customerPhoneNumber: String!
  pushNotificationToken: String
  deviceType: Int
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

**Comment by Jordan-Nelson** [comment]
Hello @mazidahmad. Thanks for taking the time to open the issue. Can you provide more detail reproduction steps, including code snippets for the queries?

**Comment by mazidahmad** [comment]
Here are steps to reproduce the issue with the code snippets : 

```
Future<void> upsertCustomerAccount({required String customerId}) async {
    Position? position;
    var firstName = await _storage.read(StorageKey.firstName);
    var lastName = await _storage.read(StorageKey.lastName);
    var email = await _storage.read(StorageKey.email);
    var mobileNumber = await _storage.read(StorageKey.mobileNumber);
    var pushNotifToken = await AppUtils().getPushNotificationToken();
    var deviceType = await _statusLocalDatasource
        .getStatusByCode(Platform.isIOS ? 'ios' : 'android');

    await Future.wait([
      // get current position
      LocationService().getCurrentPosition().then((value) => position = value),
    ]);

    var request = ModelQueries.get(
        Customer.classType, CustomerModelIdentifier(id: customerId));
    var response = await Amplify.API.query(request: request).response;
    var customer = response.data;

    if (customer != null) {
      var updatedAt = TemporalDateTime(DateTime.now());
      customer = customer.copyWith(
        customerLat: double.tryParse(position!.latitude.toString()),
        customerLng: double.tryParse(position!.longitude.toString()),
        deviceType: deviceType.statusValue,
        pushNotificationToken: pushNotifToken,
        updatedAt: updatedAt,
      );

      final request = ModelMutations.update(customer);
      await Amplify.API.mutate(request: request).response;
    } else {
      var createdAt = TemporalDateTime(DateTime.now());
      var customer = Customer(
        id: customerId,
        customerLat: double.tryParse(position!.latitude.toString()),
        customerLng: double.tryParse(position!.longitude.toString()),
        customerFirstname: firstName,
        customerLastname: lastName,
        customerType: 0,
        customerEmail: email,
        customerPhoneNumber: mobileNumber,
        deviceType: deviceType.statusValue,
        pushNotificationToken: pushNotifToken,
        createdAt: createdAt,
        updatedAt: createdAt,
      );

      final request = ModelMutations.create(customer);
      await Amplify.API.mutate(request: request).response;
    }
  }
``` 

I already have Customer data and want to update the data here.

Steps : 
1. Get customer by the ID
2. If it exists, will change any attribute there
3. Update Customer by mutate

When I debug it, there is no errors here and it returns Customer value with no updated customer data.

I tried to change it to `Amplify.DataStore.save(customer)`, but the table has not been updated.

**Comment by mazidahmad** [comment]
After taking time to find the root cause, I found it. The issue was, that I didn't check `DataStoreHubEvent` from `Amplify.Hub.listen` and listen to every status event until it is ready. After the ready event is emitted, I can save or update any data from the datastore now.

Thank you
