### ISSUE TITLE
Datastore query returns empty list even when isSynced: true in observeQuery snapshot.

### ISSUE THREAD

**Issue by agent515** [aws-amplify/amplify-flutter#4963]
### Description

Datastore starts syncing when the app is freshly installed or when it is accessed for the first time after `Amplify.DataStore.clear()` when user signs out. This [issue](https://github.com/aws-amplify/amplify-flutter/issues/2904) has already been filed before. As mentioned in [this](https://github.com/aws-amplify/amplify-flutter/issues/2904#issuecomment-1515576933) comment, I am using `observeQuery` to check if the datastore has finished syncing and then only start querying data.

```dart
final QuerySnapshot<User> snapshot = await Amplify.DataStore.observeQuery(
  User.classType,
).firstWhere((snapshot) => snapshot.isSynced);
```

But even when isSynced is true, the `snapshot.items` is empty. But after hot-restarting the app, relaunching the app or a slight delay (debugging using breakpoints) a non-empty list is returned.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Make a fresh new install of the Flutter application or clear DataStore on log out and log back in.
2. Wait for the datastore to get synced using `observeQuery`.

```dart
 await Amplify.DataStore.observeQuery(
  User.classType,
).firstWhere((snapshot) => snapshot.isSynced)
```
3. Check snapshot.items or use Amplify.query  after the snapshot is returned after `snapshot.isSynced` is true.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type User @model {
  id: String!
  name: String!
  email: String!
  phone: String!
  licenseNo: String!
  brokerAgencyName: String!
  profilePic: String
  contracts: [Contract] @hasMany
}

type Contract @model {
  id: ID!
  mlsID: String!
  propertyAddress: String!
  type: ContractType!
  status: ContractStatus!
  broker: User! @belongsTo
  buyers: [Buyer] @hasMany
}

type Buyer @model {
  id: ID!
  name: String!
  email: String!
  phone: String!
  contract: Contract! @belongsTo
  signature: String
  ipAddress: String
  timestamp: AWSDateTime
}

enum Usertype {
  broker
}

enum ContractType {
  showing
}

enum ContractStatus {
  draft
  sent
  signed
}
```

**Comment by Jordan-Nelson** [comment]
@agent515 - Thanks for opening the issue and providing repro steps. Does this only occur after calling Datastore.clear() or Datastore.stop()? If so, I think this may be a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/3113. Can you take a look at that issue and let me know if you do not think this is a duplicate? Thanks

**Comment by agent515** [comment]
@Jordan-Nelson yeah, it is a duplicate.
