### ISSUE TITLE
Pagination with Datastore

### ISSUE THREAD

**Issue by gauravdangi** [aws-amplify/amplify-flutter#500]
**Describe the bug**
As given in the [documentation](https://docs.amplify.aws/lib/datastore/data-access/q/platform/flutter#pagination), the following statement should be used for performing pagination.
```
List<Post> posts = await Amplify.DataStore.query(Post.classType,
    pagination: new QueryPagination(page:0, limit:100));
```

But I'm getting `The name 'QueryPagination' isn't a class. Try correcting the name to match an existing class.` error. I can't find any suggested import too. How can we implement pagination with Datastore?

**Expected behavior**
Should be able to implement pagination.

**Comment by anthonymoretti** [comment]
Adding this line manually solved it for me:
`import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';`

**Comment by offlineprogrammer** [comment]
@gauravdangi Thanks for reporting this. 

As per @anthonymoretti you need to add 

```
import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';

```

We will update the [doc](https://github.com/aws-amplify/docs/pull/3337) for this

**Comment by Jordan-Nelson** [comment]
@offlineprogrammer I think we should consider exporting this from the plugin so that consumers of the package don't have to import from a package that they do not directly depend on. I would consider importing from the interface package a workaround but not a permanent solution.
