### ISSUE TITLE
fix: expired link at document

### ISSUE THREAD

**Issue by magisystem0408** [aws-amplify/amplify-flutter#5013]
### Description

Expired link `CONTRIBUTING.md`

<img width="1120" alt="スクリーンショット 2024-06-12 0 17 55" src="https://github.com/aws-amplify/amplify-flutter/assets/61937077/ae95ae70-e880-4714-8541-8d4d26f2d39c">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Go to `https://github.com/aws-amplify/amplify-flutter/blob/main/CONTRIBUTING.md`
2. click link at `https://github.com/aws-amplify/amplify-flutter/blob/main/CONTRIBUTING.md#packages-inside-amplify-flutter`

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment]
@magisystem0408 thanks for opening this issue and also the PR to fix this issue. the PR is mrged and hence I'm closing this issue.
