### ISSUE TITLE
Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by fryette** [aws-amplify/amplify-flutter#5018]
### Description

Time to time some users report crash with that log:

Unable to instantiate activity ComponentInfo{{**bundleId**}/com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity}: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity" 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

I dont have clear steps as it's a report from crashlytics service

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.0-3.22.0

### Amplify Flutter Version

2.0.0

### Deployment Method

AWS CDK

**Comment by Jordan-Nelson** [comment]
@fryette - Do you know what version of Amplify Flutter is used in the version of the app that these customers are using? The reference to "com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity" indicates it is version 0.6.14 or older. v0.x is in maintenance mode which means it will only receive critical bug fixes. Are you able to get these users to upgrade to a version of the app with a more recent version of Amplify Flutter?

**Comment by fryette** [comment]
Thanks for clarification.
Will check that posibility

**Comment by bhautik-a3s** [comment]
I also got this issue. Anyone have solution than please help

**Comment by Jordan-Nelson** [comment]
@bhautik-a3s if you are still facing this please open a new issue and fill out this issue in the issue template. Thanks.
