### ISSUE TITLE
Inspect your amplifyconfiguration.dart and ensure that the string is proper json

### ISSUE THREAD

**Issue by amankachhal99** [aws-amplify/amplify-flutter#5025]
### Description

After I enable social (google) login in backend.ts I am getting following
"Inspect your amplifyconfiguration.dart and ensure that the string is proper json"

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Add following google auth in auth/reource.ts
```
import { defineAuth, secret } from '@aws-amplify/backend';

export const auth = defineAuth({
  loginWith: {
      email: true,
      externalProviders: {

          google: {
              clientId: secret('google_client_id'),
              clientSecret: secret('google_client_secret'),
              scopes: ['email','profile']
          },
          callbackUrls: ['myapp://'],
          logoutUrls: ['myapp://'],
      }
  }
});
```
2. Commit the code and merge to develop branch. 
3. download the amplifyconfiguration file using below command: 
`npx ampx generate outputs --app-id d2nrtckgworsqw --branch develop --out-dir lib --profile dev --format dart --outputs-version 0`
4. start the flutter project. 
5. Following error is received. 
```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ConfigurationError {
  "message": "The provided configuration is not a valid json. Check underlyingException.",
  "recoverySuggestion": "Inspect your amplifyconfiguration.dart and ensure that the string is proper json"
}
#0      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:121:9)
#1      AppPreInit._configureAmplify (package:aanandamfe/main.dart:120:21)
<asynchronous suspension>
#2      AppPreInit.appPreInit (package:aanandamfe/main.dart:105:5)
<asynchronous suspension>
#3      main (package:aanandamfe/flavors/main_dev.dart:10:3)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ConfigurationError {
  "message": "The provided configuration is not a valid json. Check underlyingException.",
  "recoverySuggestion": "Inspect your amplifyconfiguration.dart and ensure that the string is proper json"
}
#0      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:121:9)
#1      AppPreInit._configureAmplify (package:aanandamfe/main.dart:120:21)
<asynchronous suspension>
#2      AppPreInit.appPreInit (package:aanandamfe/main.dart:105:5)
<asynchronous suspension>
#3      main (package:aanandamfe/flavors/main_dev.dart:10:3)
<asynchronous suspension>
```
6. below is the output of npx ampx info
```
npx ampx info

System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M2
  Memory: 172.61 MB / 8.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.14.0 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 10.7.0 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.5
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```
7. flutter version
```
flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (9 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```
8. 

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.1.0

### Deployment Method

Amplify CLI

**Comment by amankachhal99** [comment]
Thanks @Jordan-Nelson  for the reply. After I fix the workaround in my ampllifyconfiguration I was able to start the flutter project. Now after I authorize the app on Google I am getting the below error
```
LambdaException {
  "message": "'name'"
}
```
is this also associated with the bug. I tried to double verify all the configuration and they look fine to me.

**Comment by Jordan-Nelson** [comment]
@amankachhal99 that does not seem to be related. Do you have any Lambda triggers set up with Cognito?

**Comment by Jordan-Nelson** [comment]
@amankachhal99 I am going to close this issue out as a duplicate since we have another issue tracking the original issue. If you are still facing the second issue please open a new issue. Thanks.

**Comment by amankachhal99** [comment]
Thanks a lot @Jordan-Nelson . The workaround works and yes there was a lambda trigger which was failing. I got it sorted also.. Thanks for the help. Cheers.
