### ISSUE TITLE
Cloud Messaging API (Legacy) will be removed

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#5037]
### Description

I'm using Amplify Push Notifications set up using Cloud Messaging API (Legacy) per the [docs](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-service/).

I just received an email from firebase stating that the API's will stop in a few days:
> We’re writing to remind you that starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued. This change will cause the legacy APIs to return an increased number of error responses.
The discontinued APIs will be completely shut down by July-August 2024.

I didn't find any useful information on when Amplify will update this or how we can update it on our side. The notifications service in my apps is critical for its operations so it will be greatly appreciated if I can have any update on this.

Please note there is an [open issue](https://github.com/aws-amplify/amplify-cli/issues/13688) in the Amplify CLI repo but, so far, it didn't get any response from a team member 

Thank you

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

See above

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by tyllark** [comment]
Hello @jamilsaadeh97 thank you for submitting this issue. We will look into this and get back to you!

**Comment by jamilsaadeh97** [comment]
Hi @tyllark thank you for the quick fix.

Just updated it in prod and everything is working perfectly!
