### ISSUE TITLE
Error occurred awaiting for device token to register device with Pinpoint, Invalid identity pool configuration. Check assigned IAM roles for this pool.

### ISSUE THREAD

**Issue by MishaPadalka** [aws-amplify/amplify-flutter#5039]
### Description

When running app both on Android and iOS I face this issue during the  configureAmplify() method which is inside main():
```
Future<void> main() async {
  final binding = WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  configureDependencies();
  await configureAmplify();
  await _configureFirebase();
  await fetchAuth();
  runApp(....);
}
```

```
 Future<void> configureAmplify() async {
  try {
    final auth = AmplifyAuthCognito();
    final api = AmplifyAPI();
    final pushPlugin = AmplifyPushNotificationsPinpoint();
    

    await Amplify.addPlugin(auth);
    await Amplify.addPlugin(api);
    await Amplify.addPlugin(pushPlugin);

    await Amplify.configure(amplifyconfig);

  } on Exception catch (e) {
    safePrint('An error occurred configuring Amplify: $e');
  }
}
```
When I remove await Amplify.addPlugin(pushPlugin); I don't receive such error. I use existing resources, here is my amplifyconfig 
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
     "api": {
        "plugins": {
            "awsAPIPlugin": {
                "DevCubeAirApi": {
                    "endpointType": "GraphQL",
                    "endpoint": "<graphql-endpoint>",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
       }
      }
     }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:<pool-id>",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "<pool-id>",
                        "AppClientId": "<app-client>",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                            "WebDomain": "<web-domain>",
                            "AppClientId": "<app-client>",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        }
                    }
                }
            }
        }
    },
      "notifications": {
    "plugins": {
      "awsPinpointPushNotificationsPlugin": {
        "appId": "<pinpoint-app-id>",
        "region": "us-east-2"
      }
    }
  }
}
''';
```
Here is AWS cognito identity pool information : 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "cognito-identity.amazonaws.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "cognito-identity.amazonaws.com:aud": "us-east-2:<pool-id>" // same as in the configuration file and cognito identity pool id
                },
                "ForAnyValue:StringLike": {
                    "cognito-identity.amazonaws.com:amr": "authenticated"
                }
            }
        }
    ]
}
```
```

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cognito-identity:GetCredentialsForIdentity",
                "mobiletargeting:*",
                "cognito-sync:*",
                "cognito-identity:*"
            ],
            "Resource": "*"
        }
    ]
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Open the app -> run main() -> run configureAmplify() -> error appears

### Screenshots

<img width="1315" alt="image_2024_06_19T11_26_22_760Z" src="https://github.com/aws-amplify/amplify-flutter/assets/58531288/81f04440-b538-42c3-b31a-d3228d09b335">

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.0

### Amplify Flutter Version

1.8.0

### Deployment Method

Amplify CLI + Custom Pipeline

**Comment by tyllark** [comment]
Hello @MishaPadalka thank you for submitting this issue. We will look into this and get back to you!

**Comment by tyllark** [comment]
Hello @MishaPadalka after review our documentation for [setting up push notification](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-notifications/) we found this excerpt:

> Authorizing the app for analytics events is crucial for unauthenticated users, particularly if you intend to configure Amplify or send push notifications to your users before their authentication. If authorization is declined, please keep in mind that updating the Cognito user pool would become necessary, and any subsequent updates could potentially result in the deletion of the current user data.

Your role trust policy seems to be configured to authorization:
> "cognito-identity.amazonaws.com:amr": "authenticated"

Could you please try updating you trust policy to "unauthenticated" and let us know if that resolves your issue.

**Comment by MishaPadalka** [comment]
Hello @tyllark I tried to update the trust policy to unauthenticated but it didn't help, the same error occurs. Maybe there is another option in which this error can occur? Also I wanted to add that during the first ran I receive this error : 
<img width="1213" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/58531288/8b959821-f1d1-4672-ae8d-ff5e2c17e466">
, but after hot restart I receive this one 
<img width="1303" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/58531288/68de8895-a09f-4efc-ba9b-23c745f1b218">

**Comment by tyllark** [comment]
@MishaPadalka Sorry for the delay. Can you please verify the status of guest access in your identity.

> AWS Console -> Cognito -> Identity pools -> Identity pool name -> User access -> Guest access
![Screenshot 2024-06-25 at 2 49 45 PM](https://github.com/aws-amplify/amplify-flutter/assets/169833923/57a6865e-e560-4134-a9ff-7a9926c7452f)

If guest access is inactive try activating it and verify again that the guest role's trust relationship is unauthenticated.

**Comment by MishaPadalka** [comment]
Hello @tyllark , sorry for the delay. Here is my screenshots, but I still have the same error
![image](https://github.com/aws-amplify/amplify-flutter/assets/58531288/bfdbdc0a-5b95-4a3c-bf98-2b5424a613ea)
![image](https://github.com/aws-amplify/amplify-flutter/assets/58531288/c773eafa-d62b-455b-8f15-24baa62feed1)
![image](https://github.com/aws-amplify/amplify-flutter/assets/58531288/a7f59f49-052c-436c-8cdf-431c6f731e54)
![image](https://github.com/aws-amplify/amplify-flutter/assets/58531288/abe40da6-c34b-494d-acc5-67485338c400)

**Comment by MishaPadalka** [comment]
Hello @tyllark ! Could you please help me with this problem?

**Comment by MishaPadalka** [comment]
Hello @tyllark ! Could you please help me with this problem?

**Comment by tyllark** [comment]
Hello @MishaPadalka sorry for the delay, we are still looking into this issue. Your unauthenticated policy + trust entities look correct and I was unable to reproduce the issue when using them in my app. Could you please provide the following details:

1. Your authenticated policy and trust entities.
2. Are you experiencing this issue while authenticated (from a previous session) and/or while unauthenticated?

**Comment by Jordan-Nelson** [comment]
@MishaPadalka I am going to close this out since we have not heard back
