### ISSUE TITLE
[Gen 2] Feature request: Support secondary index query with sorting

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/amplify-flutter#5048]
### Description

The flutter gen2 doc regarding secondary index query [here](https://docs.amplify.aws/flutter/build-a-backend/data/data-modeling/secondary-index/) uses typescript as example.

so the model is:
```
Message: a
    .model({
      roomId: a.id().required(),
      createdAt: a.datetime(),
    })
    .secondaryIndexes(index => [index('roomId').sortKeys(['createdAt']).queryField('listByDate')])
    .authorization(allow => [
      allow.owner(),
    ]),
```

After run client-code gen `npx ampx generate graphql-client-code --app-id xxxx --branch main --format modelgen 
--model-target dart --out lib/models`, I am not able to see `listByDate` function signature shown in the Message model's dart file, but I can only see the index created like below:
```
    modelSchemaDefinition.indexes = [
      amplify_core.ModelIndex(fields: const ["roomId", "createdAt"], name: "messagesByRoomIdAndCreatedAt")
    ];
```

I am not sure if sorting by secondary index is supported by flutter gen 2 or not, so created this feature request issue. What I want to do is the flutter way of  `  
  await client.models.Message.listByDate({
    roomId: "YOUR_ROOM_ID",
  }, { sortDirection: 'DESC', })`
  
but there is no instrution on the doc what is the function call to execute the index query and with sorting

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

As mentioned above.

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by tyllark** [comment]
Hello @hangoocn thank you for submitting this issue. We will look into this and get back to you!

**Comment by Jordan-Nelson** [comment]
@hangoocn thanks for opening the request. It looks like the linked docs are showing incorrect code samples. Those samples are for Amplify JS. We have made a note of the docs issue and will update it.

We do have a feature request tracking this. See https://github.com/aws-amplify/amplify-flutter/issues/4942. The issue description and comments explain some current workarounds. If you would like to see this feature supported can you please give that issue a 👍 and leave a comment with your use case?

Let me know if you believe this request if different or have other questions.

**Comment by hangoocn** [comment]
Hi @Jordan-Nelson Yes, it is same request and I have put 👍. I will close this one as duplicate. Thnx!

**Comment by fudedevelopments** [comment]
it still dont have the clear docs for query using secondary index in flutter
