### ISSUE TITLE
How to use SignInOptions?

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#506]
Hi there.

I am struggling trying to set SignInOptins to the Amplify.Auth.signIn method. I am trying to set it just as a simples Map<String, String> but I get "The argument type 'Map<String, String>' can't be assigned to the parameter type 'SignInOptions'.".

How should I set a Map in signIn(options: )?

**Comment by brunovsiqueira** [comment]
@Amplifiyer could you please help me with this question?

**Comment by brunovsiqueira** [comment]
Can someone help me with this?

**Comment by Ashish-Nanda** [comment]
`SignInOptions` and [`CognitoSignInOptions`](https://github.com/aws-amplify/amplify-flutter/blob/master/packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoSignInOptions.dart) which I think you should use here, are types that are part of the `amplify_auth_cognito` package. You need to pass an instance of these to the `signIn` API as it expects that type.

**Comment by brunovsiqueira** [comment]
Thank you very much @Ashish-Nanda!

**Comment by brunovsiqueira** [comment]
@Ashish-Nanda the Amplify.Auth.signIn expects a SignInOptions and not a CognitoSignInOptions. When I try to send a CognitoSignInOptions in this method it throws an error "Invalid argument: Instance of 'CognitoSignInOptions'", even CognitoSignInOptions inherting from SignInOptions. Besided that, I cannot instantiate SignInOptions cause it is not allowed.

What should I do? Is it expected  to not be able to use CognitoSignInOptions as a "option" parameter for the signIn method?

**Comment by Amplifiyer** [comment]
@brunovsiqueira can you share your code snippet or a reproducible app?


Ideally you should be able to pass a subclass object to a function that expects a superclass. e.g. the below code compile on dartpad successfully

```dart
class SignInOptions {
  const SignInOptions();
  void serializeAsMap() {
    print("SignInOptions:SerializeAsMap");
  }
}

class CognitoSignInOptions extends SignInOptions {
  CognitoSignInOptions(this.option): super();
  int option;
  void serializeAsMap() {
    print("CognitoSignInOptions:SerializeAsMap:option:" + option.toString());
  }
}

void signIn(SignInOptions a) {
  a.serializeAsMap();
}
void main() {
    signIn(CognitoSignInOptions(1));
}
```

**Comment by haverchuck** [comment]
@brunovsiqueira Are you trying to do something like this?
```dart
 Amplify.Auth.signIn(
          username: usernameController.text.trim(),
          password: passwordController.text.trim(),
          options: CognitoSignInOptions(clientMetadata: {'key':'value'})
      );
```

**Comment by brunovsiqueira** [comment]
@haverYes, I am doing exactly what you said and I get the same error mentioned here: https://github.com/aws-amplify/amplify-flutter/issues/512. 

Seems that signIn is not accepting CognitoSignInOptions as options argument.

**Comment by brunovsiqueira** [comment]
Hi there. Any updates on this? 

Passing options to cognito will be a must in my company starting next week. So I need help with this asap.

@haverchuck @Ashish-Nanda @Amplifiyer

**Comment by tcaravanabtg** [comment]
I guess the error has something to do with the SignInRequest passing the options parameters as an instance of CognitoSignInOptions instead of a Map.

The message_codec class that will consume it only deal with primitive types (boolean, integer, double, string, list, map), throwing the invalid argument exception.

**Comment by caravanat** [comment]
Also the SignUp function on AuthCognito.kt use de options parameter while the SignIn don't.

`  private fun onSignUp (@NonNull flutterResult: Result, @NonNull request: HashMap<String, *>) {
    var errorSent: Boolean = false
    try {
      FlutterSignUpRequest.validate(request)
      var req = FlutterSignUpRequest(request);

      Amplify.Auth.signUp(
              req.username,
              req.password,
              req.options,
              { result -> prepareSignUpResult(flutterResult, result)},
              { error ->
                if (!errorSent) {
                  errorSent = true
                  errorHandler.handleAuthError(flutterResult, error)
                }
                LOG.error("AuthException", error)
              }
      );
    } catch (e: Exception) {
      errorHandler.prepareGenericException(flutterResult, e)
    }
  }`

`private fun onSignIn (@NonNull flutterResult: Result, @NonNull request: HashMap<String, *>) {
    try {
      FlutterSignInRequest.checkUser()
      FlutterSignInRequest.validate(request)
      var req = FlutterSignInRequest(request)
      Amplify.Auth.signIn(
              req.username,
              req.password,
              { result -> prepareSignInResult(flutterResult, result) },
              { error -> errorHandler.handleAuthError(flutterResult, error)}
      );
    } catch (e: Exception) {
      errorHandler.prepareGenericException(flutterResult, e)
    }
  }`

**Comment by brunovsiqueira** [comment]
Adding code in _SignInRequest.dart_ solves the type problem but metadata keep not being sent do cognito (I can see it in my pre auth lambda logs).
As stated by @caravanat, the reason why it is happening is that _onSignIn_ method in _AuthCognito.kt_ doesn't have the options parameter so it is impossible to be sent.

@haverchuck @Ashish-Nanda @Amplifiyer could someone please help us with it? Solving this is urgent for our team.

**Comment by caravanat** [comment]
I made a PR that fix this behavior. While it works without any change in amplify-android, some changes are needed in amplify-ios because it passes nil in validationData to the awsclient.

**Comment by caravanat** [comment]
Here is the needed changes in ampify-ios: https://github.com/aws-amplify/amplify-ios/pull/1169

**Comment by haverchuck** [comment]
@brunovsiqueira Are you trying to pass validationData or clientMetadata?

**Comment by haverchuck** [comment]
@brunovsiqueira We are reviewing the PR made by @caravanat... I was actually like halfway down the road of making these same changes before I noticed the PR.

**Comment by haverchuck** [comment]
@caravanat Thanks so much!

**Comment by haverchuck** [comment]
@brunovsiqueira We are working with @caravanat on their PR.  We are giving this high priority and will attempt to merge/release as early next week as possible. 

Please note that this clientMetadata will appear in the validationData object within the lambda trigger.

**Comment by brunovsiqueira** [comment]
@haverchuck thanks so much! Looking forward for this fix :)

**Comment by haverchuck** [comment]
@brunovsiqueira @caravanat Just made a PR into @caravanat 's branch. I tested this on both platforms, both with options and without.  Please note that the client metadata will appear in the `validationData` block in lambda, and on the iOS platform there will be some other data in `validationData` by default

**Comment by caravanat** [comment]
@haverchuck and it is supposed to work on iOS without any change in amplify-ios? I'm going to test it asap, thank you so much for your help!

**Comment by haverchuck** [comment]
@caravanat This should work without iOS changes.  Please update this thread if it does not work when you test.

**Comment by haverchuck** [comment]
@caravanat @brunovsiqueira I added another PR to @caravanat's branch to refine the iOS side a bit and add unit tests.  I'm working to get this ready for action next week.

**Comment by caravanat** [comment]
@haverchuck in iOS the server is not receiving the correct values.

The app is sending:

```
SignInResult res = await Amplify.Auth.signIn(
        username: username.trim(),
        password: password.trim(),
        options: CognitoSignInOptions(clientMetadata: {
      "sessionId": sessionID,
      "ofdbLoadError": "true",
      "ofdbChannel":"business",
      "mobileId": mobileID,
      "alias": username,
    });
```

But the server is receiving:

```
request: {
    userAttributes: {
      'custom:uuid': 'f2805f1c-f4d7-42a0-8c68-96b73c88508c',
      sub: '7c1d0796-0bad-4b6f-a14b-16b0f69edd0b',
      'cognito:email_alias': 'xxx@btgpactual.com',
      'cognito:user_status': 'CONFIRMED',
      email_verified: 'true',
      'custom:isHubDomain': 'true',
      'custom:origin': 'quickfin',
      phone_number_verified: 'false',
      'cognito:mfa_enabled': 'false',
      email: 'xxx@btgpactual.com'
    },
    validationData: {
      'cognito:iOSVersion': '14.5',
      'cognito:bundleShortV': 'xxx',
      'cognito:bundleVersion': 'xxx,
      'cognito:idForVendor': 'xxx',
      'cognito:systemName': 'iOS',
      'cognito:bundleId': 'com.btg.business',
      'cognito:deviceName': 'iPhone',
      'cognito:model': 'iPhone'
    },
    userNotFound: false
  },
```

**Comment by caravanat** [comment]
@haverchuck I tested with the last PR and the only thing I noticed is that the Android send:

```
validationData: {
      ofdbChannel: 'business',
      mobileId: 'xxx',
      alias: 'xxx',
      sessionId: 'xxx',
      ofdbLoadError: 'true'
    },
```

and iOS send:

```
validationData: {
      'cognito:bundleVersion': '2.2.11',
      'cognito:systemName': 'iOS',
      'cognito:bundleId': 'com.btg.business',
      sessionId: 'xxx',
      ofdbLoadError: 'true',
      'cognito:deviceName': 'iPhone',
      'cognito:iOSVersion': '14.5',
      'cognito:bundleShortV': '2.2.01',
      ofdbChannel: 'business',
      'cognito:idForVendor': 'xxx',
      mobileId: 'xxx',
      alias: 'xxx',
      'cognito:model': 'iPhone'
    },
```

I don't know if that is the expected behavior but there is some extra info in iOS that maybe should be somewhere else. Anyway the signinoptions is working for us now and I'm looking forward for you guys merging these changes.

Thank you!

**Comment by brunovsiqueira** [comment]
Hello @haverchuck. When do you guys are planning to release this fix?

**Comment by haverchuck** [comment]
@caravanat Yes that is expected behavior right now.
@brunovsiqueira We are hoping to release by Wednesday afternoon (if not earlier), but that will depend on some additional testing on the SignInOption pull request.

**Comment by brunovsiqueira** [comment]
Ok @haverchuck. Releasing it this week works for our team. Thank vou very much!

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. Is it going to be released today?

**Comment by Ashish-Nanda** [comment]
Hi @brunovsiqueira we just did the release for version `0.1.3` that includes the fix. Please give it a try and let us know if your issue is resolved.

**Comment by brunovsiqueira** [comment]
It is working as expected! Thanks so much guys!
