### ISSUE TITLE
[Gen2] storage plugin causes 'Lost connection to device.' on debugging session

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/amplify-flutter#5066]
### Description

Whenever storage is added, debugging session in windows will exit in 1~2 minutes.
I am on flutter and storage version 2.1.0.

When storage is removed from the plugins, the issue is gone.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

The issue happens when debugging on windows platform.

1. add `storage` to plugins like this:
```
    final storage = AmplifyStorageS3();
    await Amplify.addPlugins(
      [
        auth,
        api,
        storage
      ],
    );
```
2. Start a bugging session in vscode (press F5 in 'windows - desktop' platform).
3. Wait for around 1~2 minutes
4. Check for DEBUG CONSOLE: 'Lost connection to device.' 'Exited.'

Notice now the app is still running, but the debugging session ended, so I am not able to change the code and hot reload the app. The only way is to close the app, and restart the debug session again which is super annoying.

### Screenshots

![image](https://github.com/aws-amplify/amplify-flutter/assets/14363128/c7f5e9f5-a4ec-4d71-81c3-8298adf6f51d)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.19.3

### Amplify Flutter Version

2.1.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@hangoocn - Thanks for opening the issue. I want to confirm that both the host OS and the target OS are windows when this occurs (opposed to running an Android emulator on a Windows PC for example). Is that the case?

**Comment by Jordan-Nelson** [comment]
Thanks @hangoocn - We will attempt to reproduce this.

**Comment by hangoocn** [comment]
Hi @Jordan-Nelson , I just tried to add storage to a fresh new amplify project and is not able to reproduce the issue. It might caused by some other reasons which not just because of adding storage. (Although removing storage can fix it....)

I will close this issue to avoid your team put more effort on this.
