### ISSUE TITLE
AmplifyPlugins.AWSCognitoAuthError error 7, Invalid parameter exception

### ISSUE THREAD

**Issue by henry8th** [aws-amplify/amplify-flutter#509]
**Describe the bug**
I have set up AWS user model and added several custom attributes
When registering and passing in userAttributes i receive the error

flutter: InvalidParameterException(message: Attributes did not conform to the schema: custom:firstName: Attribute does not exist in the schema.
custom:dateOfBirth: Attribute does not exist in the schema.
custom:lastName: Attribute does not exist in the schema.
, recoverySuggestion: Make sure that the parameters passed are valid, underlyingException: The operation couldn’t be completed. (AmplifyPlugins.AWSCognitoAuthError error 7.))

**To Reproduce**
1. Create AWS amplify User model, add custom attributes and deploy
2. Set up a registration BLoC pipeline on the flutter frontend 
3. Call   SignUpResult result = await Amplify.Auth.signUp(
          username: email.trim(),
          password: password.trim(),
          options: CognitoSignUpOptions(userAttributes: {
            'firstName': firstName.trim(),
            'lastName': lastName.trim(),
            'dateOfBirth': dateOfBirth.trim()
          }));

SideNote: I have also tried using the keys that don't have quotes this also generates an error

**Expected behavior**
For a user model to be created 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[] iOS

**Smartphone (please complete the following information):**
 - Device: Iphone 11 simulator
 - OS: 14.4

Thank you

**Comment by haverchuck** [comment]
@henry8th The custom attributes in your userpool look like this, with the custom prefix?
![image](https://user-images.githubusercontent.com/10621276/116278325-3e982700-a73b-11eb-88df-910160c48fd0.png)
