### ISSUE TITLE
Configure auth to handle SAML flow.

### ISSUE THREAD

**Issue by mattRiddoch** [aws-amplify/amplify-flutter#510]
**Describe the bug**
We are currently using the flutter_web_auth plugin to present a ping fed webview.  The url looks like so:
```
'https://XXXXXXXXXX.amazoncognito.com/oauth2/authorize?identity_provider=PingFedNonProd&redirect_uri=XXXXXX://auth/callback&response_type=TOKEN&client_id=XXXXXXXXXXXXXXX',
urlScheme: 'XXXXXXXXX',
```

We would love to have this configured in the "Auth" section of the amplifyconfiguration.dart file but am coming up short finding examples?
This example looks close:
[Issue 431](https://github.com/aws-amplify/amplify-flutter/issues/431)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[X] iOS

**Comment by drkhannah** [comment]
We need the Flutter Amplify package to support our custom SAML login

**Comment by drkhannah** [comment]
(Bump) any response to this would be extremely helpful

**Comment by drkhannah** [comment]
(Bump) any response to this would be extremely helpful

**Comment by drkhannah** [comment]
@haverchuck does the `feature-request` mean this isn't currently supported?

**Comment by srisaiswaroop** [comment]
Any update on SAML support for flutter SDK?

**Comment by Jordan-Nelson** [comment]
I don't have an update on this issue, but if it is a feature you would like to see implemented, please give the issue a 👍 . It helps us to quickly gauge how much interest a feature request has.

**Comment by dnys1** [comment]
This feature has been added in v1.0.0 of Amplify Flutter, which is now stable. To enable a SAML provider, follow the instructions in the Cognito docs for enabling [Hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html) and [adding a SAML provider](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html), then call `signInWithWebUI` using the name given during set up.

```dart
Future<void> _signInSaml() async {
  final result = await Amplify.Auth.signInWithWebUI(
    provider: const AuthProvider.saml('Keycloak-SAML'),
  );
  safePrint(result);
}
```

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
