### ISSUE TITLE
AuthException instead of specific exception

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#513]
Hi there.

When cognito throws an LimitExceededException, for example when you call the resetPassword method, the result comes as a AuthException instance and not a LimitExceededException instance. I can see it is a LimitExceededException only in the "code" part of "underlyingException" attribute. It makes hard for us to catch the different exceptions properly.

Shouldn't Amplify be throwing a LimitExceededException in this case?

**Comment by brunovsiqueira** [comment]
Using amplify 0.1.0.

**Comment by haverchuck** [comment]
@brunovsiqueira This should be fixed in 0.1.3.

**Comment by brunovsiqueira** [comment]
Thanks so much guys! I am going to test it and let you guys know.

**Comment by brunovsiqueira** [comment]
It is working as expected now! Thank you all again!
