### ISSUE TITLE
"You are currently signed out" right after sign up on Android

### ISSUE THREAD

**Issue by agordeev** [aws-amplify/amplify-flutter#515]
**Describe the bug**

Here's my code:

```dart
      final result = await Amplify.Auth.signUp(
          username: email,
          password: password,
          options: CognitoSignUpOptions(userAttributes: userAttributes));

      debugPrint('Signed up');
      final usr = await Amplify.Auth.getCurrentUser();
```

The last line throws the following error:

```
Exception has occurred.
PlatformException (PlatformException(SignedOutException, Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: Please sign in and reattempt the operation., message: You are currently signed out.}, null))
```

Dependencies:

```yaml
  # AWS Amplify 
  amplify_flutter: ^0.1.0
  amplify_auth_cognito: ^0.1.0
```

The user is created fine. Happens only on Android.

Might be related to https://github.com/aws-amplify/amplify-ios/issues/1162

**Comment by Jordan-Nelson** [comment]
Hi @agordeev - Thanks for taking the time to open the issue. I was able to reproduce this behavior on both iOS and Android. `SignedOutException` will be thrown on both platforms when calling `Amplify.Auth.getCurrentUser()` if the user is not signed in. This is is expected behavior. You cannot access the current user if there is no user that is signed in.

Is there a use case in which you need to access information about the user before they are signed in? If so, do you mind explaining what your use case is?

**Comment by agordeev** [comment]
So signing up doesn't automatically signing in?

**Comment by Jordan-Nelson** [comment]
> So signing up doesn't automatically signing in?

That is correct. After calling `Amplify.Auth.signUp()`, the user will be sent a code that can be used to confirm their account by calling `Amplify.Auth.confirmSignUp()`. Once the user's account has been confirmed, they can be signed in with `Amplify.Auth.signIn()`. The [documentation on authentication](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter) has more detail on the authentication flow. Let me know if that clears things up.

**Comment by Emadeddin-eibo** [comment]
That's very upsetting UX to work with, I have MFA and a user has to enter two verification codes?

Signup -> Confirm signup (not logged in!) -> login -> confirm login. Any solution to this scenario?

**Comment by gabsn** [comment]
Up getting similar issue when using a passworless custom auth flow
