### ISSUE TITLE
InstructionsResolver is not a Class

### ISSUE THREAD

**Issue by GyulaSipos** [aws-amplify/amplify-flutter#5163]
### Description

As per the [I18n](https://ui.docs.amplify.aws/flutter/connected-components/authenticator/customization#internationalization-i18n) documentation i tried to create my own XYInstructionsResolver extends InstructionsResolver to localize the auth widget, but the IstructioinsResolver triggers "Classes can only extend other classes. Try specifying a different superclass, or removing the extends clause" error in the linter. The other Resolvers (InputResolver, MessageResolver, etc...) are recognisd and work as they should.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Try to extend InstructionsResolver in your main.dart to create localized messages. The class is not recognized.

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.2.0, but its the same in 1.6.1

### Deployment Method

Custom Pipeline

**Comment by Equartey** [comment]
Hi @GyulaSipos @dJani97. 

Thanks for reporting this issue. I've opened https://github.com/aws-amplify/amplify-flutter/pull/5169 to add the missing export. 

All the other resolvers are already being [exported](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/authenticator/amplify_authenticator/lib/src/l10n/auth_strings_resolver.dart#L8-L12). Please let us know if you are having issues importing other resolvers.

As of now, this is the recommend way to localize your app. https://ui.docs.amplify.aws/flutter/connected-components/authenticator/customization#internationalization-i18n

**Comment by Equartey** [comment]
The fix has been merged and will be included in the next release. We will announce here when it's available.

**Comment by NikaHsn** [comment]
I'm going to close this issue as the fix has been released in [2.4.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v2.4.0) version. If you see otherwise or have additional questions, please open a new issue.
