### ISSUE TITLE
completeNewPassword method missing

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#518]
When my user is in FORCE_CHANGE_PASSWORD status on Cognito (for example when he has got a temporary password) and I try to signIn it gives me:
`CognitoSignInResult.nextStep.signInStep: "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD"`

Ok, it should be possible for the user to confirm sign in with a new password and then complete the sign in flow. The problem is that Amplify Flutter is missing this method. For instance, in Amplify JS this method is called _completeNewPassword_ (ref: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#forgot-password) but in Flutter it doesn't even exists.

Is there any plans and/or schedule to release this feature? It is vital for our signIn process.

@Amplifiyer @haverchuck @Ashish-Nanda

**Comment by haverchuck** [comment]
@brunovsiqueira Have you tried using the confirmSignIn API to respond, with the new password as the `confirmationValue`?

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. I tried to test it and I think what you said is working, the user went to CONFIRMED status. However, in this method I need to send metadata int the options parameter and when I try to send a CognitoConfirmSignInOptions an exception is raised saying that the argument CognitoConfirmSignInOptions is invalid as option parameter.

**Comment by brunovsiqueira** [comment]
Probably it is related to the same error that was happening with CognitoSinInOptions.

**Comment by caravanat** [comment]
The ConfirmSignInRequest is missing the same serializeAsMap() in options that the SignInRequest missed before 0.1.3.

**Comment by brunovsiqueira** [comment]
I am going to open a new issue for this problem.

**Comment by mmazurovsky** [comment]
> @brunovsiqueira Have you tried using the confirmSignIn API to respond, with the new password as the `confirmationValue`?

Thank you very much. I can finally change user's temporary password to a permanent one with this method. The naming of this method is not very clear and the docs lack info on this subject
