### ISSUE TITLE
Support latest version of json_annotation

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#5196]
Amplify Flutter's version constraints do not allow for v4.9 of json_annotation.

Originally from https://github.com/aws-amplify/amplify-flutter/issues/5111#issuecomment-2227387658

**Comment by aktumut** [comment]
We are suffering here. :)

**Comment by AndreyGuitar** [comment]
@Jordan-Nelson , any news on a release date with the fix?

**Comment by Jordan-Nelson** [comment]
Hello @AndyGUI - Apologies for the delay. We will look to get a release out either later this week or early next week. I'll update this issue when it is available.

**Comment by AndyGUI** [comment]
@Jordan-Nelson, great news, thanks a lot!
Also, I belive the package_info_plus will updated as well in the same hot fix version?
_dependency_overrides_ are evil 😆

**Comment by AndyGUI** [comment]
@Jordan-Nelson , I'm really really really sorry to ping you here, 
but we need to know, at least approximately, what is the next planed release date (including updated package dependencies)?

**Comment by NikaHsn** [comment]
I'm going to close this issue as the fix has been released in [2.4.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v2.4.0) version.
