### ISSUE TITLE
Implement AWS Signer

### ISSUE THREAD

**Issue by MohammedNoureldin** [aws-amplify/amplify-flutter#523]
Apparently, in Amplify-JS it is possible to use the following code to sign a URL to be able to connect to a WebSocket endpoint secured by IAM:

```
.
.
  const credentials = await Auth.currentCredentials()

  const accessInfo = {
    access_key: credentials.accessKeyId,
    secret_key: credentials.secretAccessKey,
    session_token: credentials.sessionToken,
  }

  const wssUrl = "wss://YOUR-API-ID.execute-api.REGION.amazonaws.com/dev"

  const signedUrl = Signer.signUrl(wssUrl, accessInfo)

  wsClient = new W3CWebSocket(signedUrl)
.
.
```

However, this `Signer` class is not available in Flutter/Dart? This is a big issue, because by this I am not able anymore to continue coding to connect my application to my secured WebSocket endpoint.

Will this class be available any soon? Or do we have any alternative with code example please for the time being?

**Comment by hackrx** [comment]
Hey! @MohammedNoureldin, did you figure out a fix for this issue?

**Comment by MohammedNoureldin** [comment]
Hey @hackrx!

I had to implement it by myself. You can use this library I created:

https://github.com/MohammedNoureldin/aws_url_signer

**Comment by hackrx** [comment]
Thanks, @MohammedNoureldin, if possible, can you please update the readme, for the how-to call guide? I can see it requires 
```
{String apiId,
    String region,
    String stage,
    String accessKey,
    String secretKey,
    String sessionToken}
```
 parameters in. signing function, 
Don't you think it is a bad practice to hardcode access_key & secret_key in the frontend application?

**Comment by MohammedNoureldin** [comment]
@hackrx please check this https://github.com/MohammedNoureldin/aws_url_signer/issues/1#issuecomment-844970264, there is actually not too much to be said.

The keys are not stored in the app, they are being fetched using **Cognito** (shown in the link above), so the user is logged in using username and password, then **Cognito** returns temporary keys.

**Comment by dnys1** [comment]
This has been released as the [`aws_signature_v4`](https://pub.dev/packages/aws_signature_v4) package with support for Web and VM platforms!
