### ISSUE TITLE
Amplify.Notifications.Push.launchNotification always return null;

### ISSUE THREAD

**Issue by ClemPalf** [aws-amplify/amplify-flutter#5233]
### Description

Hi, 
I am having trouble manipulating push notifications when received from a terminated state.
The command `Amplify.Notifications.Push.launchNotification` always return null.

All the other commands to manipulate the notifications are working as expected (`onNotificationOpened`, `onNotificationReceivedInBackground`, `onNotificationReceivedInBackground`, `onNotificationReceivedInForeground`) 

Regards

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

On IOS (didn't try Android)
1) I have the following code before runApp: 
```
 final authPlugin = AmplifyAuthCognito();
    final storagePlugin = AmplifyStorageS3();
    final analyticsPlugin = AmplifyAnalyticsPinpoint();
    final apiPlugin = AmplifyAPI();
    final pushPlugin = AmplifyPushNotificationsPinpoint();

    pushPlugin
        .onNotificationReceivedInBackground(myAsyncNotificationReceivedHandler);

    await Amplify.addPlugins(
      [
        authPlugin,
        storagePlugin,
        analyticsPlugin,
        apiPlugin,
        pushPlugin,
      ],
    );

    await Amplify.configure(amplifyconfig);

    // When opened from terminated state.
    pushNotif = Amplify.Notifications.Push.launchNotification;
```
2) Terminate the app.
3) Send a pushNotification via a campaign.
4) The notification appear on the locked screen
5) Tap the notification
6) Amplify.Notifications.Push.launchNotification is always null

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.2.0

### Deployment Method

AWS CDK

**Comment by Equartey** [comment]
Hi @ClemPalf, thanks for taking the time to submit this issue. We will investigate the observed behavior and update you as we can.

**Comment by tyllark** [comment]
Hi @ClemPalf I'm receiving the launch notification on both iOS and Android. Are you calling `Amplify.Notifications.Push.launchNotification` multiple times? After the first call we set this value to null so subsequent calls will always return a value of null.

**Comment by ClemPalf** [comment]
Hi @tyllark,
No I am calling `Amplify.Notifications.Push.launchNotification` only once.
In case this is useful, here is a bit more context: 
- I am sending my push notification via APN prod, I build my app as an ipa, and dropped it on my physical device (just like @Equartey described it in another [post](https://github.com/aws-amplify/amplify-flutter/issues/4875#issuecomment-2123338214))
- This is how I configured my notification in my campaign: 
![image](https://github.com/user-attachments/assets/b131a419-ee1e-4bc1-b2a6-9532eb836e58)

Also, do you have a simple demo app I could try ? If I can make it work, it should help me figure out what I did wrong.

Regards,

**Comment by ClemPalf** [comment]
I just tested on Android: everything works fine. So I don't think there is a problem with my flutter code.

**Comment by tyllark** [comment]
hi @ClemPalf I'm still seeing the launchNotification even when using APN prod (by dropping an ipa on my physical device). I stripped my test application down to 2 files, could you please try running them from within your project and let me know if you are still getting null launchNotifications.

[lib.zip](https://github.com/user-attachments/files/16567426/lib.zip)

pubspec.yaml dependencies
```
dependencies:
  amplify_flutter: ^2.2.0
  amplify_auth_cognito: ^2.2.0
  amplify_push_notifications_pinpoint: ^2.2.0
```

**Comment by ClemPalf** [comment]
Hi, 

So I tried with your files (to which I just added two buttons: One that logged me in with Cognito and the other identified me with pinpoint). 

It still doesn't work, and the results are a bit strange.
This is what I get when opening the notification from a terminated state:
![IMG_1943 2](https://github.com/user-attachments/assets/19c86497-c000-41b5-815a-a0377f62cc88)
The `Amplify.Notifications.Push.onNotificationOpened.listen(_onPushNotificationOpened);` I thought it was only for foreground/background state.

 And this is what I get when opening the notification from a background state:
![IMG_1944](https://github.com/user-attachments/assets/4c2bbef0-21eb-4ef6-a305-8cf69aa36b85)



I tried commenting out `Amplify.Notifications.Push.onNotificationOpened.listen(_onPushNotificationOpened);` thinking it might "consume" the `Amplify.Notifications.Push.launchNotification`, but no, even without it the result is null.

Please ask if there is any extra info/logs you would like to have.

Regards,

**Comment by ClemPalf** [comment]
Also, is the app you sent me supposed to work on Android?
Because I get this error: 
```
PushNotificationException {
  "message": "Callback is not a global or static function",
  "recoverySuggestion": "Make the callback function given to the API a top-level or a static function."
} 
```
And then when I modified the code so that  _onBackgroundNotification(PushNotificationMessage message) is a global function : it works fine in debug mode. But in release mode, I get this weird Flutter error every time I receive a notification when the app is in background mode: 
```
E/flutter ( 7988): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Dart_LookupLibrary: library 'package:myapp/push_notification_page.dart' not found.
E/flutter ( 7988): [ERROR:flutter/shell/common/shell.cc(117)] Dart Error: Dart_LookupLibrary: library 'package:myapp/push_notification_page.dart' not found.
```

I really have trouble understanding what is going on...

**Comment by tyllark** [comment]
Hello @ClemPalf sorry for the delay, but I believe I have an answer to your question now. On iOS when [Background Modes - Remote notifications](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-notifications/#set-entitlements) is enabled then receiving a notification launches your app in the background so tapping on the notification launched the app from a background state. Despite this it's possible for the app to still launch from a terminated state so [per our documentation](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/interact-with-notifications/#respond-to-a-notification-being-opened) you will need to support both `onNotificationOpened` (for background launches) and `getLaunchNotification` (for terminated launches).

From your screenshot your phone seems to be constantly launching the app from a background state which is why you are receiving the Open Message event rather than `launchNotification`. From my side my phone was launching the app from a terminated state consistently which populated `launchNotification`, but after doing this 10-50 times my phone started to consistently launch from a background state and I was getting the Open Message event instead.

I did not test this sample project on Android, but you can remove the `onNotificationReceivedInBackground` and `_onBackgroundNotification` logic if you want to run this sample project on Android. I believe your actual project was working correctly on Android.

**Comment by ClemPalf** [comment]
Hi @tyllark, thanks for your answer!
For some reasons, my app sometimes doesn't trigger nor `onNotificationOpened` nor `Amplify.Notifications.Push.launchNotification` while your test app does. I will figure out why and get back to you (hopefully to close the issue).

Regards,

**Comment by ClemPalf** [comment]
So for some reason which are still not quite clear to me, my app could, from a terminated state, received the notification from onNotificationOpened, or onNotificationReceivedInBackground, or launchNotification (and only one of them at the same time). I adapted my code, and now everything works !
