### ISSUE TITLE
How to use Amplify Hub events?

### ISSUE THREAD

**Issue by gelintonx** [aws-amplify/amplify-flutter#524]
Hi there.

I am struggling trying to listen to the Amplify Hub I am trying to listen to this event to check if user is signed in. Then if user isn't logged in send it to the login page 
How should I listen to this events? I'm using the following code: `StreamSubscription hubSubscription = Amplify.Hub.listen([HubChannel.Auth], (hubEvent) {
  switch(hubEvent.eventName) {
    case "SIGNED_IN": {
      print("USER IS SIGNED IN");
    }
    break;
    case "SIGNED_OUT": {
      print("USER IS SIGNED OUT");
    }
    break;
    case "SESSION_EXPIRED": {
      print("USER IS SIGNED IN");
    }
    break;
  }
});`

**Comment by haverchuck** [comment]
@gelintonx Hub can be used to passively listen for and handle these events as they occur in realtime.  In order to check at a specific moment whether a user is signed in, you can use `fetchAuthSession`:
```dart
 CognitoAuthSession res = await Amplify.Auth.fetchAuthSession();    
```

**Comment by gelintonx** [comment]
Ok thanks @haverchuck  I'll be using this function to solve my issue
