### ISSUE TITLE
userPoolTokens. null

### ISSUE THREAD

**Issue by salvolf** [aws-amplify/amplify-flutter#526]
I'm unable to get the access token from a CognitoAuthSession

**To Reproduce**
    CognitoAuthSession session = await Amplify.Auth.fetchAuthSession();
 if (session.isSignedIn) {
    print("session.userPoolTokens.accessToken");
    print(session.userPoolTokens.accessToken);
}
**Expected behavior**
i would expect an access token i get: 
E/flutter (12615): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'accessToken' was called on null.
E/flutter (12615): Receiver: null
E/flutter (12615): Tried calling: accessToken

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Comment by haverchuck** [comment]
@salvolf Have you tried calling like this?
```dart
CognitoAuthSession res = await Amplify.Auth.fetchAuthSession(
     options: CognitoSessionOptions(getAWSCredentials: true)
 ); 
```

**Comment by salvolf** [comment]
Yes it worked, thanks!
