### ISSUE TITLE
 error: could not find module 'amplify_auth_cognito' for target 'arm64-apple-macos'; found: x86_64-apple-macos,

### ISSUE THREAD

**Issue by richard457** [aws-amplify/amplify-flutter#5275]
### Description

Launching lib/main.dart on macOS in debug mode...
/Users/richard/Documents/GitHub/flipper/apps/flipper/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: could not find module 'amplify_auth_cognito' for target 'arm64-apple-macos'; found: x86_64-apple-macos, at: /Users/richard/Documents/GitHub/flipper/apps/flipper/build/macos/Build/Products/Debug/amplify_auth_cognito/amplify_auth_cognito.framework/Modules/amplify_auth_cognito.swiftmodule
import amplify_auth_cognito
       ^
#import "Headers/amplify_auth_cognito-Swift.h"
        ^
** BUILD FAILED **

Error: Build process failed

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Add amplify_auth_cognito to flutter app and run debug mode on macos

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.0

### Amplify Flutter Version

2.3.0

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @richard457, thank you for submitting this issue. We will take a look at it and get back to you with any updates or questions.

**Comment by khatruong2009** [comment]
Hi @richard457, are you using the gen2 backend to create your app?

**Comment by NikaHsn** [comment]
@richard457 do you see this issue when running a sample flutter app (without adding amplify_auth_cognito)? I suspect that you may have installed a Flutter SDK for x64 architecture on a macOS with arm64 architecture.
you may run `flutter doctor -v` to check the version of Flutter installed and if it matches your mscOS system architecture

**Comment by richard457** [comment]
I have flutter version 3.24.0

**Comment by richard457** [comment]
> Hi @richard457, are you using the gen2 backend to create your app?

I think so, I started using amplify recently, and I did a bunch of things that I do not know which led to what.

**Comment by richard457** [comment]
but I think in general error might be related to the recent change in flutter to adopt new package manager for swift etc....

**Comment by NikaHsn** [comment]
@richard457 I'm not sure if the issue you are facing is related to flutter's swift package manager support.
when you get a chance would you please responde to these questions:
- do you see this issue when running a sample flutter app (without adding amplify_auth_cognito)? I suspect that you may have installed a Flutter SDK for x64 architecture on a macOS with arm64 architecture.
- what is the output of ruunning `flutter doctor -v` (you may check the version of Flutter installed and if it matches your mscOS system architecture)
- Have you followed the macOS Platform setup [here](https://docs.amplify.aws/flutter/start/platform-setup/#macos)?

**Comment by NikaHsn** [comment]
I'm closing this issue as we did not hear back. Please feel free to open a new issue if you face any problem.
