### ISSUE TITLE
Deployment issue in monorepo with amplify gen 2 & Next js

### ISSUE THREAD

**Issue by spring-bconnect** [aws-amplify/amplify-flutter#5287]
### Monorepo app deployment failure issue

PFA screenshots

<img width="1606" alt="Screenshot 2024-08-13 at 6 07 47 PM" src="https://github.com/user-attachments/assets/1a5fc42b-958e-4e98-a373-3e09b5ede85c">
<img width="1606" alt="Screenshot 2024-08-13 at 6 08 01 PM" src="https://github.com/user-attachments/assets/6fd80712-efd7-4369-9c3a-f63d1271be43">

**yarn workspaces> pacakge.json**
{
  "name": "----",
  "version": "1.0.0",
  "description": "-------",
  "main": "index.js",
  "author": "-------",
  "license": "MIT",
  "private": true
}

**Monorepo Folder structure**

<img width="266" alt="Screenshot 2024-08-13 at 6 12 31 PM" src="https://github.com/user-attachments/assets/893eca30-7331-4c0c-85f7-73c598761054">

**Complete folder structure**

<img width="261" alt="Screenshot 2024-08-13 at 6 35 22 PM" src="https://github.com/user-attachments/assets/cf6c4fcf-113d-4ccb-bdb6-99a4cb22a5d8">

**Forntend app > Nextjs > Package.json**

<img width="503" alt="Screenshot 2024-08-13 at 6 15 54 PM" src="https://github.com/user-attachments/assets/1eae1073-d919-414d-81c0-2e4c8020dab7">

**Nextjs> tsconfig.json**

<img width="840" alt="Screenshot 2024-08-13 at 6 18 55 PM" src="https://github.com/user-attachments/assets/26e51bcf-08a0-4836-bbf1-4a9f72f01fa1">

**Amplify> ts.config.json**

<img width="840" alt="Screenshot 2024-08-13 at 6 20 01 PM" src="https://github.com/user-attachments/assets/c1d3c6b7-0da8-4360-8330-9091ccb4bdcf">

**Comment by khatruong2009** [comment]
Hi @spring-bconnect, I believe this is a continuation of the current conversation on [this issue](https://github.com/aws-amplify/amplify-flutter/issues/5272) can we continue on that issue instead?

**Comment by khatruong2009** [comment]
I'm going to close this issue now as we're continuing the conversation in the [this thread](https://github.com/aws-amplify/amplify-flutter/issues/5272).
