### ISSUE TITLE
Error : amplify upload file function not throwing an exception 

### ISSUE THREAD

**Issue by lavishmanghnani2** [aws-amplify/amplify-flutter#5306]
### Description

I'm encountering an issue while using the amplify_storage_s3 package in a Flutter application. The issue occurs under the following circumstances:

When we upload larger files on S3 and suddenly the internet goes down or OFF 

Expected Behavior:

The upload file function throw any exception 

my code :

```dart
  Future<void> uploadIOFile(
      {required File file,
      required int index,
      required String name,
      required S3UploadFileOperation? uploadOperation,
      required BuildContext? context,
      required Function(StorageTransferProgress progress)
          returnProgress}) async {
    try {
      final storagePlugin = Amplify.Storage.getPlugin(
        AmplifyStorageS3.pluginKey,
      );
      final awsFile = AWSFilePlatform.fromFile(file);

      uploadOperation = storagePlugin.uploadFile(
          localFile: awsFile,
          options: const StorageUploadFileOptions(
            pluginOptions: S3UploadFilePluginOptions(
              useAccelerateEndpoint: true,
            ),
          ),
          key: name,
          onProgress: (StorageTransferProgress progress) {
            uploaderLastTime = DateTime.now();
            //  print("MeeeWorkkingforat>>>>>>>>>>$index");
            manageOperationWithState(uploadOperation: uploadOperation);
            returnProgress(progress);
          });
      await uploadOperation.result.catchError((e) {
        throw Exception(e);
      });
    } on StorageException catch (e) {
      //   safePrint('Error uploading file: ${e.message}');
      throw Exception(e);
    } catch (e) {
      throw Exception(e);
    }
  }
  ```
  When the internet goes off in the middle of uploading the response I'm getting :
  
  
  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DELETE https://dental-drive122415-dev.s3.us-east-1.amazonaws.com/public/65e160509d8ba938a5368b88/9B77E407-F085-4A35-BE1B-A09F1494F7BE/1723805881801/C%3A/New%20folder%20%283%29/android-studio-2024.1.1.12-windows%20-%20Copy.exe?x-id=AbortMultipartUpload&uploadId=3nopqwZnhVwAhf2JnCM09BJxbzwG3xVizYXocZNUs0NRHQbGNNf9VZGflRGMesaDUeB80883u02S1AurOtUSa02le9Ljsp736Zne2UcUy6xUWUc7R2.0d6o5ug8E.qO4mZhMkQUENJDJb_AOzUJP6cIoA7bxmDUinaE7ybgmPFA- failed: SocketException: Failed host lookup: 'dental-drive122415-dev.s3.us-east-1.amazonaws.com' (OS Error: No such host is known.

, errno = 11001)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

1.  Set up a Flutter application using these packages    amplify_storage_s3: ^1.8.0
  amplify_flutter: ^1.8.0
  amplify_auth_cognito: ^1.8.0
  aws_common: ^0.6.5,  packages.
  
  2. Upload larger files  more then 500 MB
  
  3. Turn off the pc internet from settings 

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

">=3.3.0 <4.0.0"

### Amplify Flutter Version

  amplify_storage_s3: ^1.8.0   amplify_flutter: ^1.8.0   amplify_auth_cognito: ^1.8.0   aws_common: ^0.6.5

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment]
Hi @lavishmanghnani2, thank you for taking the time to submit this issue. We will take a look and reach out to you with any questions or updates.

**Comment by khatruong2009** [comment]
Hi @lavishmanghnani2, are you also having this issue on other platforms as well like iOS, Android, or Mac? Or is this only specific to windows?

**Comment by lavishmanghnani2** [comment]
> Hi @lavishmanghnani2, are you also having this issue on other platforms as well like iOS, Android, or Mac? Or is this only specific to windows?

@khatruong2009 No, I'm using this only in windows and getting this issue only in larger files

**Comment by NikaHsn** [comment]
@lavishmanghnani2  thank you for the reply. we will look into this issue and get back to you with any updates.

**Comment by Jordan-Nelson** [comment]
@lavishmanghnani2 what version of flutter are you using? I see your provided a range of 3.3.0-4.0.0. That is quite a large range. Can you run `flutter doctor` and share the output?

Are you able to reproduce this issue with the latest version of Amplify Flutter libraries?

**Comment by TaraCybertouch** [comment]
@Jordan-Nelsonhee thanks for your response, here is my flutter doctor output :

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4780], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[!] Android Studio (version 2023.1)
    X Unable to determine bundled Java version.
[!] Android Studio (version 2023.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.


and I didn't update the  latest version of Amplify Flutter libraries because my project is running Amplify Gen 1 and The updated Dependency required Gen 2

**Comment by Jordan-Nelson** [comment]
@TaraCybertouch Amplify Flutter 2.x is compatible with both Gen 1 and Gen 2 applications. You can see the migration guide here: https://docs.amplify.aws/gen1/flutter/start/project-setup/upgrade-guide/.

We will attempt to reproduce this, but I would recommend upgrading to the latest version as v1.x will only receive critical fixes.

**Comment by lavishmanghnani2** [comment]
@Jordan-Nelson okay i will try to  upgrading to the latest version and then let you know

**Comment by tyllark** [comment]
Hi @lavishmanghnani2, do you have any updates for the latest version?

**Comment by lavishmanghnani2** [comment]
hello @tyllark , yes my issue is resolved.
