### ISSUE TITLE
CognitoConfirmSignInOptions not working

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#532]
When I use the auth confirmSignIn method with ConfirmSignInOptions as options attribute an exception is raised saying that the argument CognitoConfirmSignInOptions is invalid as option parameter. I believe this could be solved in a similar way you guys solved the  CongitoSignInOptions issue (https://github.com/aws-amplify/amplify-flutter/issues/506).

Sending client metadata as options parameter will be mandatory for us early next week.

@haverchuck @Amplifiyer

**Comment by haverchuck** [comment]
@brunovsiqueira Which Cognito Trigger are you expecting to pass this to?

**Comment by brunovsiqueira** [comment]
@haverchuck  this is going to be passed to the Pre Authentication trigger.

**Comment by haverchuck** [comment]
@brunovsiqueira Are there other Auth APIs you are expecting to use for this... or just signIn and confirmSignIn?

**Comment by brunovsiqueira** [comment]
No, just the two you mentioned. Makes sense confirm signin not triggering pre auth. But I am using same metadata in the post auth trigger.

**Comment by haverchuck** [comment]
@brunovsiqueira PR #538 has a fix for this issue. It will only work with iOS until we merge another PR into amplify-android and update the gradle files in this PR.  If you have time, do you want to grab the code changes from this PR and test so that we can confirm it is working for you before we release - and also to make sure that there aren't any other issues.

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. Thank you so much! I will test it as soon as possible and let you know. 

When are you guys planning to release it with the iOS part working?

**Comment by haverchuck** [comment]
We are hoping to get this change, as well as the change for android, merged and released early next week.

**Comment by brunovsiqueira** [comment]
Ok, that works for us! Thank you again.

**Comment by haverchuck** [comment]
@brunovsiqueira There was a small bug in the #538, which I've just fixed. If you've already pulled the code before this comment, you may need to pull again.

**Comment by haverchuck** [comment]
@brunovsiqueira When you test the iOS functionality, can you please make sure that there is nothing else needed? We generally try to avoid more than one release per week.

**Comment by haverchuck** [comment]
@brunovsiqueira Any update on this?

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. Should I only use your commit and it should work both on Android and iOS? As soon as I have time to test I will do it.

**Comment by haverchuck** [comment]
@brunovsiqueira I just pushed the requisite changes to #538 which will enable this for both platforms.  For this trigger, you will see the values you pass in under a clientMetadata key in the trigger's request object:

```
request: {
    userAttributes: {
      sub: 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx',
      'cognito:user_status': 'CONFIRMED',
      email_verified: 'true',
      'cognito:mfa_enabled': 'true',
      phone_number_verified: 'true',
      phone_number: '+xxxxxxxxxx',
      email: 'xx.xx@xx.com'
    },
    newDeviceUsed: false,
    clientMetadata: { myKey: 'myValue' }
```

**Comment by haverchuck** [comment]
@brunovsiqueira We plan on releasing this tomorrow morning (PST).

**Comment by brunovsiqueira** [comment]
Hi @haverchuck. Sorry fot the late reply.

I tested in iOS and Android and both are working as expected. Thank you so much again!
