### ISSUE TITLE
ANDROID: Error when receiving background notifications in release mode

### ISSUE THREAD

**Issue by ClemPalf** [aws-amplify/amplify-flutter#5321]
### Description

On Android, in release mode, the function `pushPlugin.onNotificationReceivedInBackground(onNotifReceivedCallback);` can't seem to find the onNotifReceivedCallback when receiving the notification.

In debug mode, everything works fine, but in release mode, when receiving the notification and the app is in background state, I get the following error : 

```
E/flutter (31451): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception:
E/flutter (31451): NoSuchMethodError: No top-level getter 'onNotifReceivedCallback' declared.
E/flutter (31451): Receiver: top-level
E/flutter (31451): Tried calling: onNotifReceivedCallback
E/flutter (31451): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:163)
E/flutter (31451): #1      __getCallbackFromHandle$Method$FfiNative (dart:ui/natives.dart)
E/flutter (31451): #2      _getCallbackFromHandle (dart:ui/natives.dart:95)
E/flutter (31451): #3      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:74)
E/flutter (31451): #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543)
E/flutter (31451): #5      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:73)
E/flutter (31451): #6      AmplifyPushNotificationsFlutterApi._dispatchToExternalHandle (package:amplify_push_notifications/src/push_notifications_flutter_api.dart:96)
E/flutter (31451): <asynchronous suspension>
```

It works fine on IOS.
 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Here is a simple test app
[lib.zip](https://github.com/user-attachments/files/16673696/lib.zip)
1) I plugged a OnePlus8 to my computer.
2) Launched the app in release mode.
3) Logged in with Google, identified as a user on Pinpoint, and authorized pushNotifications.
4) Put the app in the background.
5) Launched a notification on the pinpoint console.
The error appeared in the debug console as soon as the device received the notification.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.0

### Amplify Flutter Version

2.3.0

### Deployment Method

AWS CDK

**Comment by NikaHsn** [comment]
@ClemPalf Sorry that you are facing this issue and thanks for reporting it. We will look into this and get back to you when we have updates.

**Comment by NikaHsn** [comment]
@ClemPalf as this issue only happens on release mode and based on the error message I suspect this may be caused by the dart pre-compiler tree shaking. Would you please try adding @pragma("vm:entry-point") to the onNotifReceivedCallback function, I wonder if that would fix the problem.
more info on Dart pre-compiler optimization and use of @pragma("vm:entry-point") can be found [here](https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md#procedures)

**Comment by ClemPalf** [comment]
Hello @NikaHsn, 
Your solution worked! 
Thanks for the quick answer and the associated documentation.
