### ISSUE TITLE
Intermittent Issue - Cannot read properties of undefined (reading 'permission_types')

### ISSUE THREAD

**Issue by markjoseultra** [aws-amplify/amplify-flutter#5342]
### Description

Hi Team,

We keep getting this error but it resolves itself, earlier today all our users experience at the same time and there is a downtime of an hour then it got resolved again and none of us created a fix so it remains a mystery.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

1. Try doing a stress test on amplify query and mutate since it doesn't happen all the time.
2. Use an error monitoring system like sentry.

### Screenshots

![image](https://github.com/user-attachments/assets/b4b6080f-29a3-4e1a-9753-0d93ae2d9062)
![image](https://github.com/user-attachments/assets/a53210b6-3a8a-4323-99d8-bb183cbb9305)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.1.0

### Deployment Method

AWS CDK

**Comment by NikaHsn** [comment]
Sorry that you are facing this issue and thanks for reporting it. We will look into this and get back to you when we have updates. meanwhile do you have more detailed error messages to share with us.

**Comment by Jordan-Nelson** [comment]
@markjoseultra Without more info we are not going to be able to triage this issue. `aws_amplify_impl.dart` and `AWSAmplifyImpl` are not part of our code base. If those are files in your app, please share them so we can see the code causing the issue.

**Comment by markjoseultra** [comment]
Hi Team here is the code that triggers the error previously, now it works but please continue the investigation 

`  ///Amplify query function
  @override
  Future<Map<String, dynamic>> query(
    String query,
    Map<String, dynamic> variables,
  ) async {
    try {
      var operation = Amplify.API.query(
        request: GraphQLRequest<String>(
          document: query,
          variables: variables,
          apiName: "ticklr-lambda",
          headers: {
            "Authorization": await LambdaToken.generate(),
          },
        ),
      );

      var response = await operation.response.timeout(
          Duration(minutes: AppConfig.REMOTE_REQUEST_TIMELIMIT), onTimeout: () {
        throw Exception('Weak internet connection, please try again');
      });

      if (response.hasErrors) {
        throw Exception(response.errors[0].message);
      }

      if (response.data == null && response.data!.isEmpty) {
        throw Exception('Unable to fetch data from server, please try again.');
      }

      String? data = response.data;

      return jsonDecode('$data');
    } on GraphQLResponseError catch (e) {
      throw Exception(e.message.toString());
    } on ApiException catch (e) {
      throw Exception(e.message.toString());
    } on LambdaException catch (e) {
      throw Exception(e.message.toString());
    } catch (e) {
      rethrow;
    }
  }`
