### ISSUE TITLE
Sign in provider was not registered due to missing optional dependency. showSignIn() API may not work as expected.

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#535]
The following warning is being printed in console (latest release):
`D/AWSMobileClient(29781): Using the SignInProviderConfig from `awsconfiguration.json`.
W/AWSMobileClient(29781): Sign in provider was not registered due to missing optional dependency. showSignIn() API may not work as expected.
W/AWSMobileClient(29781): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobile/auth/userpools/CognitoUserPoolsSignInProvider;
W/AWSMobileClient(29781): 	at com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders(AWSMobileClient.java:3536)
W/AWSMobileClient(29781): 	at com.amazonaws.mobile.client.AWSMobileClient.access$100(AWSMobileClient.java:163)
W/AWSMobileClient(29781): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:490)
W/AWSMobileClient(29781): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(29781): 	at java.lang.Thread.run(Thread.java:923)`

Should I just ignore this warning? Am I missing any configuration?

**Comment by haverchuck** [comment]
@brunovsiqueira This can be safely ignored if you aren't using Hosted UI (and should be silenced on a future release).

**Comment by brunovsiqueira** [comment]
Ok! Thanks @haverchuck.
