### ISSUE TITLE
Expose progressListener from Amplify.Storage.uploadFile and Amplify.Storage.downloadFile

### ISSUE THREAD

**Issue by albemala** [aws-amplify/amplify-flutter#541]
**Describe the bug**

In the native SDKs, there is a `progressListener` parameter for the `Amplify.Storage.uploadFile` and `Amplify.Storage.downloadFile` APIs. This parameter is not exposed in the Flutter SDK.

**Expected behavior**

Could you please add the `progressListener` parameter in Flutter as well? Many thanks!

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by dnys1** [comment]
This has been released in version 0.2.6
