### ISSUE TITLE
Changing "maxRecordsToSync" is not having any effect

### ISSUE THREAD

**Issue by anthonymoretti** [aws-amplify/amplify-flutter#543]
**Describe the bug**
DataStore is only syncing 10,000 items even when I change `maxRecordsToSync` to something higher like 50,000. It also continues to sync 10,000 items if I change `maxRecordsToSync` to something lower like 5,000. I've tried doing it by code and also changing `amplifyconfiguration.dart`.

**To Reproduce**
1. Add the following code after `await Amplify.configure(amplifyconfig);`:
```
const dataStoreConfig = '''{
  "maxRecordsToSync": 50000
}''';
await Amplify.DataStore.configure(dataStoreConfig);
```

_or_ add the following to `amplifyconfiguration.dart`:
```
"DataStore": {
  "maxRecordsToSync": 50000
}
```
2. Verify in the Amplify console that the table has more than 10,000 items that aren't deleted.
3. Run the app, calling `await Amplify.DataStore.clear();` at the beginning.
3. Wait a couple of minutes for items to sync from the cloud.
4. Query the table with a pagination limit above 10,000, e.g. 1,000,000.
5. Check the length of the returned list and see it only equals 10,000.

**Expected behavior**
The length of the list should match the live item count in the console.

**Platform**
This issue is reproducible in:
[ ] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/anthonymoretti/Development/flutter
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 22D9A5A3-6D98-4CFE-BB37-8FC3047614AE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      90.0.4430.85

! Doctor found issues in 2 categories.
```

</details>

**Smartphone:**
 - Device: Simulator
 - OS: iOS14.4

**Additional context**
 - Amplify: 4.49.0

**Comment by haverchuck** [comment]
@anthonymoretti This is not a feature we support yet, so I'm marking this as a feature request and getting it into our backlog.

**Comment by anthonymoretti** [comment]
@haverchuck Ok, thanks for letting me know! You wouldn't be able to give a very rough ballpark figure of when you think it might work would you?

**Comment by HuiSF** [comment]
Hi all, amplify-flutter 0.16.0 just released, which includes support of datastore custom configuration. 
Configurable fields include:

* `syncInterval`
* `syncMaxRecords`
* `syncPageSize`

Please try it out, and feel free to follow up if you experience any issues. Thanks!

**Comment by anthonymoretti** [comment]
Thank you! I'll try it out

**Comment by anthonymoretti** [comment]
It works with the following code. Thank you!!

```
await Amplify.addPlugin(
  AmplifyDataStore(
    modelProvider: ModelProvider.instance,
    syncMaxRecords: 50000,
  ),
);
```
