### ISSUE TITLE
API (GraphQL) - Support multiple auth modes

### ISSUE THREAD

**Issue by jodafm** [aws-amplify/amplify-flutter#547]
**Describe the bug**
amplify-flutter is not supporting multiple auth modes because the **amplify_api package** is not receiving neither propagating a parameter called "apiName".

**apiName** is used by the amplify-ios/amplify-flutter to infer which api to use.

If we configure multiple auth modes in **amplifyconfiguration.dart**, all the api operations failed returning this error:

**More than one graphQL API configured. Could not infer which API to call, recoverySuggestion: Use the apiName to specify which API to call** 

**To Reproduce**
1. Configure multiple auth modes. (https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter)
2. Send an operation (query, mutation, subscription)

**Expected behavior**
We expect that GraphQLRequest receive the apiName in order to be able to configure the multi auth mode.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by matthewfx** [comment]
Hi! Any ETA on that issue? It would be highly appreciated if you could fix it.

**Comment by ragingsquirrel3** [comment]
This was added with PR https://github.com/aws-amplify/amplify-flutter/pull/553 which is merged, but I want to keep this issue open until next release is shipped to pub dev with this change. We should also update docs to reflect this addition.

**Comment by ragingsquirrel3** [comment]
This was released with 0.2.2 and we added some documentation for this at the bottom of https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter . Thanks again @jodafm ! I'm going to close this issue now.
