### ISSUE TITLE
Amplify.Notifications.Push.onNotificationOpened.listen wont trigger on Android

### ISSUE THREAD

**Issue by gigamike** [aws-amplify/amplify-flutter#5474]
### Description

I'm using Amplify for push notifications. In IOS, when I clicked the push message, it works fine. I can get the push payload i.e.

`flutter: 🚀 onNotificationOpened PushNotificationMessage {
  "title": "Test title",
  "body": "Test body please ignore",
  "imageUrl": null,
  "deeplinkUrl": null,
  "goToUrl": null,
  "fcmOptions": null,
  "apnsOptions": {
    "subTitle": null
  },
  "data": {
    "type": "friend_request",
    "data1": "data21"
  }
}`

But when using Android it seems the Amplify.Notifications.Push.onNotificationOpened.listen won't trigger. I just received a message like this

D/AmplifyAuthCognitoPlugin(11095): [onNewIntent] Got intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x14400000 pkg=au.movinghub.homehub cmp=au.movinghub.homehub/com.example.homehub.MainActivity (has extras) }
D/AmplifyAuthCognitoPlugin(11095): [onNewIntent] Not handling intent

Here is a sample code
```
Future<void> _configureAmplify() async {
    try {
      final authPlugin = AmplifyAuthCognito();
      final pushPlugin = AmplifyPushNotificationsPinpoint();

      pushPlugin.onNotificationReceivedInBackground(myCallback);

      if (!Amplify.isConfigured) {
        await Amplify.addPlugins([authPlugin, pushPlugin]);
        await Amplify.configure(amplifyconfig);

        Amplify.Notifications.Push.onTokenReceived.listen((event) {
          print('🚀 onTokenReceived $event');
          SessionManager().setString("device_id", event.toString());
        });

        // Required to call this after Amplify.configure.
        Amplify.Notifications.Push.onNotificationReceivedInForeground
            .listen((event) {
          print('🚀 onNotificationReceivedInForeground $event');
        });

        // Required to call this after Amplify.configure.
        // wont trigger in Android
        Amplify.Notifications.Push.onNotificationOpened.listen((event) {
          print('🚀 onNotificationOpened $event');
          print(event.data);
        });
      }
      setState(() {
        _amplifyConfigured = true;
      });

      /*
      final subscription = Amplify.Notifications.Push.onNotificationOpened
          .listen(myNotificationOpenedHandler);
      print(subscription);
      */
    } on Exception catch (e) {
      print(e.toString());
    }

    AmplifyLogger().logLevel = LogLevel.info;
  }
```

Im using https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-pinpoint-2016-12-01.html#sendmessages to trigger a push which works fine on both IOS and Android.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Setup Amplify push notification using Amazon Pinpoint. 

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.1

### Amplify Flutter Version

2.2.0

### Deployment Method

Amplify Gen 2

**Comment by Equartey** [comment]
Hi @gigamike, sorry to hear you've ran into this issue. 

We'll investigate it and provide an update here when we can, thanks.

**Comment by gigamike** [comment]
Hi @tyllark ,

Thanks for reply. Your sample code is almost the same as mine. When sending push message via Pinpoint i.e. Pinpoint -> All projects -> [Project name] -> Test messaging?, I'm receiving this

I/FA      ( 3621): Application backgrounded at: timestamp_millis: 1726613957096
I/flutter ( 3621): 🚀 Background Message PushNotificationMessage {
I/flutter ( 3621):   "title": "test",
I/flutter ( 3621):   "body": "test",
I/flutter ( 3621):   "imageUrl": null,
I/flutter ( 3621):   "deeplinkUrl": null,
I/flutter ( 3621):   "goToUrl": null,
I/flutter ( 3621):   "fcmOptions": {
I/flutter ( 3621):     "channelId": "PINPOINT.NOTIFICATION",
I/flutter ( 3621):     "messageId": null
I/flutter ( 3621):   },
I/flutter ( 3621):   "apnsOptions": null,
I/flutter ( 3621):   "data": {
I/flutter ( 3621):     "pinpoint.openApp": "true",
I/flutter ( 3621):     "pinpoint.notification.title": "test",
I/flutter ( 3621):     "pinpoint.notification.body": "test",
I/flutter ( 3621):     "pinpoint.campaign.campaign_id": "_DIRECT",
I/flutter ( 3621):     "pinpoint.notification.silentPush": "0"
I/flutter ( 3621):   }
I/flutter ( 3621): }


BUT when I clicked the push message

D/AmplifyAuthCognitoPlugin( 3621): [onNewIntent] Got intent: Intent { flg=0x10400000 cmp=au.movinghub.homehub/com.example.homehub.MainActivity (has extras) }
D/AmplifyAuthCognitoPlugin( 3621): [onNewIntent] Not handling intent
E/OpenGLRenderer( 3621): Unable to match the desired swap behavior.

Is that really the behavior of Android? Because in IOS, when I clicked the push notification 

flutter: 🚀 Open Message PushNotificationMessage {
  "title": "test",
  "body": "test",
  "imageUrl": null,
  "deeplinkUrl": null,
  "goToUrl": null,
  "fcmOptions": null,
  "apnsOptions": {
    "subTitle": null
  },
  "data": {}
}

So in Android the Open Message PushNotificationMessage is not triggered/listen. 

Thanks,
Mik

**Comment by tyllark** [comment]
Hi @gigamike,

For permissions `<uses-permission android:name="android.permission.INTERNET"/>` is the only permission I have in my AndroidManifest.xml. I do request push notification permissions at runtime via:
```
Amplify.Notifications.Push.requestPermissions(
      alert: true,
      badge: true,
      sound: true,
);
```

To clarify the intended functionality for both Android and iOS:

- if the app is opened in foreground it will trigger `onNotificationReceivedInForeground` and no notification will be displayed, thus `onNotificationOpened` will not trigger.

- If the app is in the background it will trigger `onNotificationReceivedInBackground` and display a notification to the user that will trigger `onNotificationOpened` when opened.

- If the app is terminated it it will trigger `onNotificationReceivedInBackground` and display a notification to the user that will either trigger `onNotificationOpened` or set `launchNotification` when opened. You should handle both possibilities here since the OS may leave the app in background mode for after receiving a push notification.

Can you please:
1. Confirm if launchNotification is being set incase you are launch the app from a terminated state.
2. Confirm that you are not getting push notifications to click when receiving a foreground notification.

**Comment by gigamike** [comment]
Hi @tyllark ,
Thanks for reply.

This one is not working on my end.
"If the app is in the background it will trigger onNotificationReceivedInBackground and display a notification to the user that will trigger onNotificationOpened when opened."

Yes it triggers onNotificationReceivedInBackground but when I click the push message it doesn't trigger the onNotificationOpened for Android only. For IOS it works. My goal is when users click the push message they will be redirected to a specific screen in my app depending on the push payload i.e. data

Confirm if launchNotification is being set incase you are launch the app from a terminated state.
-Yes
Confirm that you are not getting push notifications to click when receiving a foreground notification.
- Im getting the push notification and I can see logs for onNotificationReceivedInBackground. But when I click or open the push it doesn't return the payload.

One thing, I tried adding firebase_messaging and I can trigger onopen for Android i.e.

// doesn't trigger when Android but ok with IOS (Pinpoint Test Message)
Amplify.Notifications.Push.onNotificationOpened
        .listen(_onPushNotificationOpened);
        
if(Platform.operatingSystem == 'android'){
    FirebaseMessaging.instance.getInitialMessage().then(
          (value) => setState(
            () {
              _resolved = true;
              initialMessage = value?.data.toString();
            },
          ),
        );

    FirebaseMessaging.onMessage.listen(showFlutterNotification);
    
// it triggers for Android coming from Pinpoint (Pinpoint Test Message)
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('A new onMessageOpenedApp event was published!');
    });
}

Any ideas?

Thanks,
Mik

**Comment by gigamike** [comment]
Hi @tyllark ,

Ok, I figure it out. The problem was I'm using newer version of i.e.

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.23" apply false
    id("com.google.gms.google-services") version "4.3.2" apply false
}

because currently as of writing, Firebase messaging "Add Firebase to your Android app"
<img width="906" alt="Screenshot 2024-09-19 at 8 23 29 AM" src="https://github.com/user-attachments/assets/84bdd34c-f40c-4bad-8ed3-0ac7cc92222f">

So I downgraded to 4.3.14

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    // id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id "org.jetbrains.kotlin.android" version "1.9.23" apply false
    id("com.google.gms.google-services") version "4.3.14" apply false
}

I/FA      (18734): Application backgrounded at: timestamp_millis: 1726704920445
I/flutter (18734): 🚀 Background Message PushNotificationMessage {
I/flutter (18734):   "title": "Mik Test title",
I/flutter (18734):   "body": "Mik Test body please ignore",
I/flutter (18734):   "imageUrl": null,
I/flutter (18734):   "deeplinkUrl": null,
I/flutter (18734):   "goToUrl": null,
I/flutter (18734):   "fcmOptions": {
I/flutter (18734):     "channelId": "PINPOINT.NOTIFICATION",
I/flutter (18734):     "messageId": null
I/flutter (18734):   },
I/flutter (18734):   "apnsOptions": null,
I/flutter (18734):   "data": {
I/flutter (18734):     "pinpoint.openApp": "true",
I/flutter (18734):     "pinpoint.notification.title": "Mik Test title",
I/flutter (18734):     "pinpoint.notification.body": "Mik Test body please ignore",
I/flutter (18734):     "type": "friend_request",
I/flutter (18734):     "pinpoint.campaign.campaign_id": "_DIRECT",
I/flutter (18734):     "pinpoint.notification.silentPush": "0"
I/flutter (18734):   }
I/flutter (18734): }
D/AmplifyAuthCognitoPlugin(18734): [onNewIntent] Got intent: Intent { flg=0x10400000 cmp=au.movinghub.homehub/com.example.homehub.MainActivity (has extras) }
D/AmplifyAuthCognitoPlugin(18734): [onNewIntent] Not handling intent
I/flutter (18734): 🚀 Open Message PushNotificationMessage {
I/flutter (18734):   "title": "Mik Test title",
I/flutter (18734):   "body": "Mik Test body please ignore",
I/flutter (18734):   "imageUrl": null,
I/flutter (18734):   "deeplinkUrl": null,
I/flutter (18734):   "goToUrl": null,
I/flutter (18734):   "fcmOptions": {
I/flutter (18734):     "channelId": "PINPOINT.NOTIFICATION",
I/flutter (18734):     "messageId": null
I/flutter (18734):   },
I/flutter (18734):   "apnsOptions": null,
I/flutter (18734):   "data": {
I/flutter (18734):     "pinpoint.openApp": "true",
I/flutter (18734):     "pinpoint.notification.title": "Mik Test title",
I/flutter (18734):     "pinpoint.notification.body": "Mik Test body please ignore",
I/flutter (18734):     "type": "friend_request",
I/flutter (18734):     "pinpoint.campaign.campaign_id": "_DIRECT",
I/flutter (18734):     "pinpoint.notification.silentPush": "0"
I/flutter (18734):   }
I/flutter (18734): }

I can trigger now both  Background Message and Open Message.

Thank you so much
