### ISSUE TITLE
fetchAuthSession throws when no logged in user?

### ISSUE THREAD

**Issue by chris** [aws-amplify/amplify-flutter#550]
**Describe the bug**
When my app launches, I call `fetchAuthSession` to get any auth session. This may not be the right approach (so please let me know if there's a better way). My desire is that, if there's a logged in user, I'd get an auth session and the `isSignedIn` field would be true. My thought was if there is no logged in user, then `isSignedIn` would be false. But, instead it seems to throw a SignedOutException. This is ok, and I can handle via exception handling, but it makes me wonder if there's a different way to check if there is a signed in user or not, and/or what the recommended approach is for detecting if we have a logged in user or not? I am using a Cognito user pool.

**To Reproduce**
1. call `Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true))`

With a logged in user, this works fine.
With a logged out user, I get an exception.

**Expected behavior**
Expect documentation/explanation of the possible states, and/or doc around how to get user (if there is one) when launching app. My presumption is:

- non-null session and `isSingedIn` = true, means we have a current signed in user
- non-null session and `isSingedIn` = false, means we had a logged in user, but their session is expired (not sure if this means their id/access tokens are expired; and I also thought that calling the session would refresh their tokens?).
- null session, means we don't know of any user/no logged in user

**Platform**
Amplify Flutter currently supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

I haven't tested this on Android.

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/chris/Code/flutter
    • Framework revision 1d9032c7e1 (3 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 744F6841-284B-40D4-97B5-9F1C4F26A831 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.93
    ! Error: CRB iPhone XS max is not connected. Xcode will continue when CRB iPhone XS max is connected. (code -13)

• No issues found!```

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro simulator
 - OS: iOS 14.5

**Comment by riyan-datalyca** [comment]
I use `Amplify.Auth.getCurrentUser()` function. If there is a Current User Signed In it will return the user-id and user-name, else Signed Out error.

**Comment by offlineprogrammer** [comment]
Hi @chris 

I don't get an error on `Amplify.Auth.fetchAuthSession()`

Instead, I get the following: 

```
CognitoAuthSession
credentials:null
identityId:null
isSignedIn:false
userPoolTokens:null
userSub:null
hashCode:2690726810

```

Feel free to test using the latest build and let us know if you get errors

Thanks
Mo

**Comment by haverchuck** [comment]
related: https://github.com/aws-amplify/amplify-android/issues/1247

**Comment by offlineprogrammer** [comment]
Hi All

I am closing this issue for now due to inactivity
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
