### ISSUE TITLE
Platform Exception when trying to signup a user

### ISSUE THREAD

**Issue by kkeshav93** [aws-amplify/amplify-flutter#551]
I am trying to sign up a user using a simple code where I have hardcoded the email and password as well. the code looks as following:

`Future<String> _onSignup(BuildContext context) async {
    try {
      await Amplify.Auth.signUp(
          username: 'username@gmail.com',
          password: '1234567890',
          options: CognitoSignUpOptions(
              userAttributes: {'email': 'username@gmail.com'}));
    } catch (e) {
      return e.toString();
    }
  }`

But when i click the button the following error is throw:

PlatformException (PlatformException(AuthException, Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: See attached exception for more details., underlyingException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference, message: Sign up failed}, null))

**Comment by haverchuck** [comment]
@kkeshav93 Which version of amplify-flutter are you using?

**Comment by kkeshav93** [comment]
Flutter 2.0

**Comment by haverchuck** [comment]
@kkeshav93 Specifically, I meant to ask which version of the `amplify_auth_cognito plugin` and `amplify_flutter` packages?

**Comment by kkeshav93** [comment]
amplify_flutter: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'

I added the above once to pubsec.yaml. So they always try to get the latest.

**Comment by kkeshav93** [comment]
>amplify --version  
4.50.2
