### ISSUE TITLE
Is it possible to alter the path prefix and download whatever I want from S3?

### ISSUE THREAD

**Issue by blattr** [aws-amplify/amplify-flutter#552]
**Describe the bug**
I am using a lambda backend to generate (and track) new file ids and upload the objects to S3 via a presigned url. The S3 key looks something like "users/{identityId}/images/{fileId}". This works perfectly finde with using plain http.

```dart
http.Response response = await http.put(
      Uri.parse(presignedUrl),
      headers: {
        HttpHeaders.contentTypeHeader: ContentType.binary.mimeType,
      },
      body: data,
    );
```

When I try to download this object, the Amplify Storage plugin adds a path prefix which causes my key to look like "**public**/users/{identityId}/images/{fileId}". Obviously, I am not able to download this object (because it doesn't exist).

```text
StorageException(message: The key 'public/users/***/images/***' could not be found with message: Received HTTP Response status code 404 NotFound., recoverySuggestion: Make sure the key exists before trying to download it.
The object for key in the public access level should exist under the public folder as public/<key>.
When looking for the key in protected or private access level, it will be under its respective folder
such as 'protected/<targetIdentityId>/<key>' or 'private/<targetIdentityId>/<key>'., underlyingException: null)
```

Is there any possibility to change this behavior? I cannot believe I ran into this kind of limitation. I mean, people totally new to AWS may find this mechanism useful but for the concept of "using existing resources" this is a show stopper. As a side note  - of course, It is not possible to download a specific versionId, too.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Comment by Jordan-Nelson** [comment]
Hello @blattr - Thanks for taking the time to open the issue. The ability to specify a custom prefix is not currently supported. There have been a few separate issues for this. #416 is going to be used to track interest in this feature.

I'm going to mark this as a duplicate and close this issue out. Please provide any additional comments/questions on the other thread.
