### ISSUE TITLE
Social Sign In not working on iOS devices

### ISSUE THREAD

**Issue by kavienanj** [aws-amplify/amplify-flutter#5523]
### Description

The SSO authentication is working perfectly on Android Devices and even iOS Simulator. But not in physical iOS devices. We couldn't find what could be the issue. We used Firebase and Onesignal services too. But even after stripping out the dependencies and making the app this simple the issue still persists.

When the sso button is clicked the prompt appears, but before we press continue its is getting dismissed immediately. After the first time repeated presses doesn't trigger anything.

The code is very simple,

```flutter
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  void _configureAmplify() async {
    try {
      await Amplify.addPlugin(AmplifyAuthCognito());
      await Amplify.configure(amplifyconfig);
      safePrint('Successfully configured');
    } on Exception catch (e) {
      safePrint('Error configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Authenticator(
      child: MaterialApp(
        builder: Authenticator.builder(),
        home: const Scaffold(
          body: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('You are logged in!'),
              SizedBox(height: 20),
              Center(child: SignOutButton()),
            ],
          ),
        ),
      ),
    );
  }
}
```

The pubspec.yaml

```yaml
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  amplify_flutter: ^2.4.1
  amplify_auth_cognito: ^2.4.1
  amplify_authenticator: ^2.1.3
```

Behavior on a Physical iOS 18 iPhone,

https://github.com/user-attachments/assets/a26d1503-b8db-4cad-9e51-03b3f19820ed

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Run the above code

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.0

### Amplify Flutter Version

2.4.1

### Deployment Method

Amplify Gen 2

**Comment by Equartey** [comment]
Hi @kavienanj, I'm unsure what the collision was between the packages, but one cause of the obersved behavior is from not setting the iOS minimum deployment target. We have this process outlined in our docs here: [https://docs.amplify.aws/gen1/flutter/start/project-setup/platform-setup](https://docs.amplify.aws/gen1/flutter/start/project-setup/platform-setup/#ios). Can you confirm these properties were set when you saw the issue?

**Comment by kavienanj** [comment]
@Equartey YESS, You are right. We tried that and it worked. Since we referred to this docs page we have missed that setup https://docs.amplify.aws/flutter/build-a-backend/auth/sign-in-with-web-ui/. In this page, it doesn't mention any platform setup for iOS. Now our app is working as expected. Thank you for your support. I am closing the issue.

**Comment by seildancer** [comment]
I had the exact same issue with the symptoms described in the screen recording (the dialog disappearing right after popping up), and following the platform-setup docs it is resolved. Thank you so much!
