### ISSUE TITLE
Auth signOut after signInWithWebUI does not clear browser session

### ISSUE THREAD

**Issue by devsideal** [aws-amplify/amplify-flutter#5538]
### Description

**Describe the bug**
Amplify.Auth.signOut() does not clear the SFAuthentication session. This will not allow the user to signIn again with another users.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. signIn using Amplify.Auth.signInWithWebUI
2. After successful signIn, signout the user by Amplify.Auth.signOut
3. Now try to signIn again using Amplify.Auth.signInWithWebUI.
4. The user is not presented a signIn screen, Amplify automatically signin the user to the previous users account.

Expected behavior
After signOut Amplify.Auth.signInWithWebUI should work as a fresh start.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.4.1

### Deployment Method

Amplify CLI (Gen 1)

**Comment by tyllark** [comment]
Hello @devsideal thank you for submitting this issue. There is a [feature request ](https://github.com/aws-amplify/amplify-flutter/issues/1528) for this already open, but it has unfortunately been blocked by Cognito for quite some time. Please give the feature request a thumbs up and follow it for any updates. I will close this issue as a duplicate if you have no additional question.

Our [docs](https://docs.amplify.aws/gen1/flutter/build-a-backend/auth/sign-in-with-web-ui/#prefer-private-session-during-signin-on-ios) include a section for private sessions on iOS. This will not cover Android and private sessions might not be suitable for your use case.
```
await Amplify.Auth.signInWithWebUI(
    options: const SignInWithWebUIOptions(
      pluginOptions: CognitoSignInWithWebUIPluginOptions(
        isPreferPrivateSession: true,
      ),
    ),
  );
```
