### ISSUE TITLE
How to update user attributes for Auth Cognito

### ISSUE THREAD

**Issue by fdarsot** [aws-amplify/amplify-flutter#554]
I have some custom attributes set up for a user when a user signs up, how do i update those custom attributes when i want?

i dont see a function for this.

**Comment by Ashish-Nanda** [comment]
Hi @fdarsot the `updateUserAttribute()` API that you are looking for, along with other user attribute related APIs have been implemented as part of PR https://github.com/aws-amplify/amplify-flutter/pull/533. The PR is currently under review and should be available soon in the next release.

**Comment by fdarsot** [comment]
thats perfect! thank you guys!

**Comment by haverchuck** [comment]
@fdarsot [These APIs](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter#fetch-the-current-users-attributes) have been updated in amplify-flutter v0.1.5.
