### ISSUE TITLE
Support for S3 Cross Region Replication

### ISSUE THREAD

**Issue by masterlonghorn** [aws-amplify/amplify-flutter#555]
Are we able to use S3 Cross Region Replication with flutter amplify projects?

Let's say my primary bucket is in US and I want full replicas in EU and maybe one in Asia. Even if the buckets have same name (I am assuming this is possible, comment if otherwise) how can we target the closest bucket region based on user location?

Would be if the files are only uploaded to the bucket closest to user and accessed directly. Based on access patterns if some file is being requested often globally, it could be replicated to other regions by lambda. Is something like this a possibility?

**Comment by fjnoyp** [comment]
Hi @masterlonghorn, yes you are able to use S3 Cross Region Replication as it can be configured using the Amazon S3 console.  https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-example-walkthroughs.html

It seems you can configure replication use filters and rules to achieve that effect based on the above example.

**Comment by masterlonghorn** [comment]
Thanks fo the reply @fjnoyp. If I have buckets in multiple regions, how do I read from the closest bucket to the user in my flutter app?

**Comment by offlineprogrammer** [comment]
Hi @masterlonghorn 

Check the S3 Multi-Region Access Points feature. you need to implement a logic in you App to determine the closest region 

https://aws.amazon.com/blogs/aws/s3-multi-region-access-points-accelerate-performance-availability/

Regards
Mo
