### ISSUE TITLE
Face/Image Detection+Analysis

### ISSUE THREAD

**Issue by donpaul120** [aws-amplify/amplify-flutter#556]
With the current version please how possible is it to integrate aws-rekognition? is it possible using the REST, if so can you please point me towards the right direction.

**Comment by fjnoyp** [comment]
Hi @donpaul120 you can follow the integration instructions here: https://docs.aws.amazon.com/rekognition/latest/dg/getting-started.html.  I'm not so familiar with the documentation but it appears to give a general overview of what can be done and how to do it.  

This documentation here seems more recent: 
https://docs.aws.amazon.com/rekognition/latest/dg/rekognition-dg.pdf

If you look at the Table of Contents in the document you'll see a section "Using the AWS SDK or HTTP to call Amazon Rekognition API operations ....... 7".  That could be a good place to start looking as well!

**Comment by offlineprogrammer** [comment]
Hi @donpaul120 

I am closing this issue as @fjnoyp provided the links for the documentation 

Regards
Mo
