### ISSUE TITLE
Custom prefix instead of folders namespaced by AccessLevel

### ISSUE THREAD

**Issue by LostJ3ster** [aws-amplify/amplify-flutter#557]
**Describe the bug**
When trying to upload Content to our Bucket, we are only able to upload to a folder named "public".
For our usecase (because we're switching packages in order to achive Null-Safety in the near future), we need to upload to another - custom named folder.

**To Reproduce**

    S3UploadFileOptions options = S3UploadFileOptions(
      accessLevel: StorageAccessLevel.guest,
      metadata: meta,
    );
    
    UploadFileResult result;
    try {
      result = await Amplify.Storage.uploadFile(
        key: keyPath,
        local: temp,
        options: options,
      );
    } on StorageException catch (e) {
      print(e.message);
    }

**Expected behavior**
We expected to be able to set a custom prefix, or set the folder via the key or something like that.
But because of the folders namespaced by AccessLevel, we would have to move all our data to another folder, which is a no-go for us.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel unknown, 1.22.6, on Microsoft Windows [Version 10.0.19041.928], locale de-DE)
    • Flutter version 1.22.6 at C:\dev\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Robin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Robin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 90.0.818.51```

</details>

**Comment by smerchermek** [comment]
I've the same problem, did you find any solution please ? Thanks

**Comment by dospringer** [comment]
@smerchermek The only way I see in the moment is to create a script with AWS Lambda, to transfer the uploaded files in the correct location.  I don't like this "solution", but I think it is the best solutions in the moment, without making breaking changes in a live system.

**Comment by Jordan-Nelson** [comment]
Hello @LostJ3ster - Thanks for taking the time to open the issue. The ability to specify a custom prefix is not currently supported. There have been a few separate issues for this. #416 is going to be used to track interest in this feature.

I'm going to mark this as a duplicate and close this issue out. Please provide any additional comments/questions on the other thread.
