### ISSUE TITLE
Unhandled Exception: SignedOutException(message: There is no user signed in to retreive user sub, recoverySuggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession, underlyingException: null)

### ISSUE THREAD

**Issue by shajedulislam** [aws-amplify/amplify-flutter#562]
```
CognitoAuthSession cognitoAuthSession =
          await Amplify.Auth.fetchAuthSession(
              options: CognitoSessionOptions(
        getAWSCredentials: true,
      ));
```

The above code works fine in emulators but giving this error in real device.
Note: All packages are updated

**Comment by fjnoyp** [comment]
Hi @shajedulislam could you provide more context on what you have done?  

What platform emulator was it working on?  What code and user workflow did you do?  What physical device are you testing on?

**Comment by shajedulislam** [comment]
@fjnoyp 

I am using this function to check if the user logged in or not

after trying different ways I found that, I get this error when running in debugging mode what ever the device is. Running in release mode is ok.

**Comment by shajedulislam** [comment]
Problem is solved. 
To get AWSCredentials using the function  Amplify.Auth.fetchAuthSession() We have to first do:

`CognitoAuthSession cognitoAuthSession = await Amplify.Auth.fetchAuthSession();`

After that we have to do:

```
CognitoAuthSession cognitoAuthSession =
          await Amplify.Auth.fetchAuthSession(
              options: CognitoSessionOptions(
        getAWSCredentials: true,
      ));
```

So on first call we can not get AWSCredentials in fetchAuthSession() function. It gives error. But works well calling fetchAuthSession function again 2nd time with AWSCredentials.

So I am closing this issue.
