### ISSUE TITLE
Flutter(doc): How to access Amplify Gen 2 (AWS Parameter Store) Secrets?

### ISSUE THREAD

**Issue by pavel-penev-hms** [aws-amplify/amplify-flutter#5627]
## Steps to Reproduce

* Go to [Secrets and environment vars, §[Access secrets](https://docs.amplify.aws/flutter/deploy-and-host/fullstack-branching/secrets-and-vars/#access-secrets)](https://docs.amplify.aws/flutter/deploy-and-host/fullstack-branching/secrets-and-vars/#access-secrets) (for Amplify Gen. 2)
* Switch 'Choose your framework/language' in the left-hand menu to 'Flutter'.

## Expected Behavior

* See Dart code for accessing a secret as created in the previous section of the page.

## Observed Behavior

* The 'Access secrets' section shows TypeScript code.

## Notes

* As a separate issue, reading secrets is nice, but so is writing them. A code sample for storing a secret would be useful to have, as well. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

* Go to [Secrets and environment vars, §[Access secrets](https://docs.amplify.aws/flutter/deploy-and-host/fullstack-branching/secrets-and-vars/#access-secrets)](https://docs.amplify.aws/flutter/deploy-and-host/fullstack-branching/secrets-and-vars/#access-secrets) (for Amplify Gen. 2)
* Switch 'Choose your framework/language' in the left-hand menu to 'Flutter'.

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.4

### Amplify Flutter Version

2.4.1

### Deployment Method

Amplify Gen 2

**Comment by ekjotmultani** [comment]
Hi @pavel-penev-hms, thank you for taking the time to submit this issue. Our backend definitions are done in typescript and then converted to outputs for dart to consume. This is why typescript code is shown on the docs page, because the secrets are defined in the resource.ts file where you define Auth. This file should be under amplify/auth/resource.ts, please see [the documentation](https://docs.amplify.aws/flutter/start/quickstart/#create-backend-1) for further reference on where to find that.

**Comment by pavel-penev-hms** [comment]
@ekjotmultani, thanks for the reply. I understand that model, and authentication definitions are in TypeScript, and that the example shows using a secret for the Auth definition. However, I'd like to read a secret from Flutter. Let me give you scenario, which would, hopefully, clarify what I'm asking.

* I have a data model, and Auth definition in TypeScript.
* The Auth is used in production where authentication secrets are entered by a user on the Amplify Gen. 2 built-in login page.
* In an integration testing environment, I want to run 'large tests' against the same application, but by reading secrets from a secrets store.

**Comment by tyllark** [comment]
Hello @pavel-penev-hms in general we do not support writing secrets at runtime. Our API does not expose this information at runtime either, but [this section of the docs ](https://docs.amplify.aws/flutter/deploy-and-host/fullstack-branching/secrets-and-vars/#branch-environment-2) explains how to extract the secrets into a file a build time which you could incorporate into your testing. Just make sure you don't embed this file within the release of your application.

**Comment by pavel-penev-hms** [comment]
@tyllark, thanks for clarifying! I was hoping there may be a Dart interface to the AWS Parameter Store. It seemed like they would be accessible from TypeScript using the `@aws-sdk/client-ssm`, or `@aws-amplify/backend-secret` although I haven't tried.

I think your suggestion may be a good option for now.

**Comment by Equartey** [comment]
@pavel-penev-hms sounds like your root issue is resolved. I'm going to close this issue for now. If you have additional context you want to add later on for future readers, please add that here.
