### ISSUE TITLE
Hub auth events not emit

### ISSUE THREAD

**Issue by flutteresbolivia** [aws-amplify/amplify-flutter#563]
**Describe the bug**
When the loggin or logout, the amplify_auth_cognito events not emit o don't work.

use versions:
amplify_flutter: '0.1.4'
amplify_auth_cognito: '0.1.4'
amplify_storage_s3: '0.1.4'

flutter 2.0.3

**Comment by Jordan-Nelson** [comment]
Hi @flutteresbolivia - Thanks for opening the issue. Can you please fill out the remaining portions of the issue template so that I can try to reproduce this issue? The steps to reproduce, platform (iOS or Android), and output of `flutter doctor -v` would be helpful. Thank you.

**Comment by offlineprogrammer** [comment]
Hi @flutteresbolivia 

I couldn't reproduce this issue using our sample app on iOS & Android. 

My setup details 

```yaml


dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.8.0+1
  amplify_flutter: 0.1.4
  amplify_auth_cognito: 0.1.4
  amplify_analytics_pinpoint: 0.1.4
  amplify_storage_s3: 0.1.4

```

I subscribed to the hub events as below

```dart

void _initAmplifyFlutter() async {
    AmplifyAuthCognito auth = AmplifyAuthCognito();
    AmplifyStorageS3 storage = AmplifyStorageS3();
    AmplifyAnalyticsPinpoint analytics = AmplifyAnalyticsPinpoint();

    Amplify.addPlugins([auth, storage, analytics]);

    // Initialize AmplifyFlutter
    try {
      await Amplify.configure(amplifyconfig);
      StreamSubscription hubSubscription =
          Amplify.Hub.listen([HubChannel.Auth], (hubEvent) {
        switch (hubEvent.eventName) {
          case "SIGNED_IN":
            {
              print("USER IS SIGNED IN");
            }
            break;
          case "SIGNED_OUT":
            {
              print("USER IS SIGNED OUT");
            }
            break;
          case "SESSION_EXPIRED":
            {
              print("USER IS SIGNED IN");
            }
            break;
        }
      });
    } on AmplifyAlreadyConfiguredException {
      print(
          "Amplify was already configured. Looks like app restarted on android.");
    }

    setState(() {
      _isAmplifyConfigured = true;
    });
  }

```

And I can see the events on the logs

````

Xcode build done.                                           32.7s
Connecting to VM Service at ws://127.0.0.1:64394/V5-_liqlPn4=/ws
flutter: USER IS SIGNED OUT
flutter: USER IS SIGNED IN


````

Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by flutteresbolivia** [comment]
> Hola @flutteresbolivia
> 
> No pude reproducir este problema con nuestra aplicación de muestra en iOS y Android.
> 
> Mis detalles de configuración
> 
> ```yaml
> dependencias :
>    flutter :
>      sdk : flutter 
>   file_picker : ^ 1.8.0 + 1 
>   amplify_flutter : 0.1.4 
>   amplify_auth_cognito : 0.1.4 
>   amplify_analytics_pinpoint : 0.1.4 
>   amplify_storage_s3 : 0.1.4
> ```
> 
> Me suscribí a los eventos del centro de la siguiente manera
> 
> ```dart
> void  _initAmplifyFlutter () async {
>      AmplifyAuthCognito auth =  AmplifyAuthCognito ();
>     Almacenamiento AmplifyStorageS3 =  AmplifyStorageS3 ();
>     Análisis de AmplifyAnalyticsPinpoint =  AmplifyAnalyticsPinpoint ();
> 
>     Amplificar . addPlugins ([autenticación, almacenamiento, análisis]);
> 
>     // Inicializar AmplifyFlutter 
>     try {
>        esperan ser  Amplify . configurar (amplifyconfig);
>       StreamSubscription hubSubscription = 
>           Amplificar . Hub . listen ([ HubChannel . Auth ], (hubEvent) {
>          switch (hubEvent.eventName) {
>            case  "SIGNED_IN" :
>             {
>               print ( "USUARIO HA INICIADO SESIÓN" );
>             }
>             romper ;
>           caso  "SIGNED_OUT" :
>             {
>               print ( "EL USUARIO ESTÁ CERRADO" );
>             }
>             romper ;
>           caso  "SESSION_EXPIRED" :
>             {
>               print ( "USUARIO HA INICIADO SESIÓN" );
>             }
>             romper ;
>         }
>       });
>     } en  AmplifyAlreadyConfiguredException {
>        print (
>            "Amplify ya estaba configurado. Parece que la aplicación se reinició en Android." );
>     }
> 
>     setState (() {
>       _isAmplifyConfigured =  true ;
>     });
>   }
> ```
> 
> Y puedo ver los eventos en los registros
> 
> ```
> 
> Xcode build done.                                           32.7s
> Connecting to VM Service at ws://127.0.0.1:64394/V5-_liqlPn4=/ws
> flutter: USER IS SIGNED OUT
> flutter: USER IS SIGNED IN
> ```
> 
> No dude en probar con la última versión y avísenos si tiene algún problema.
> 
> Gracias
> Mo

I am using flutter_bloc, and in the super () method I started the events and it seems that they were not created correctly.

It only worked when I executed an event in the BLOC And there I created it and it worked.

I am going to test this configuration that you just passed me and I will comment again.

**Comment by offlineprogrammer** [comment]
Hey @flutteresbolivia 

I am closing this issue for now as I didn't hear from because of inactivity 
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by T-moz** [comment]
I have the same issue:
```yaml
  amplify_auth_cognito: ^0.2.6
  amplify_core: ^0.2.6
  amplify_flutter: ^0.2.6
```

The `Amplify.hub` do not emit auth events. But I'm 100% sure that I'm listening to event, I placed breakpoints in the Amplify sdk.

This is my code:
```dart
    _hubSubscription = Amplify.Hub.listen([HubChannel.Auth], (hubEvent) async {
      Logger.root.fine('Auth event from hub ${hubEvent.eventName} : $hubEvent');
      switch (hubEvent.eventName) {
        case "SESSION_EXPIRED":
          final session = await _getAuthSession();
          _sessionUpdated.add(session);
          break;
      }
    });
```

---

So I came up with a custom solution, using a `Timer` and the token expiration date.

```dart
  /// Return a [CognitoAuthSession]
  ///
  /// Side effect:
  /// * call [_scheduleRefreshAuthSession] if an idToken is found
  Future<CognitoAuthSession> _getAuthSession() async {
    final session = await Amplify.Auth.fetchAuthSession(
      options: CognitoSessionOptions(getAWSCredentials: true),
    ) as CognitoAuthSession;
    final _idToken = session.userPoolTokens?.idToken;
    if (_idToken != null) {
      _scheduleRefreshAuthSession(_idToken);
    }
    return session;
  }

  /// [Amplify.Hub.listen] seems to never be called.
  /// https://github.com/aws-amplify/amplify-flutter/issues/563
  ///
  /// So we schedule a new [_getAuthSession] after session has expired.
  void _scheduleRefreshAuthSession(String idToken) {
    _timer?.cancel();
    final decodedToken = JwtDecoder.decode(idToken);
    final exp = decodedToken['exp'];
    if (exp is int) {
      // [exp] is express in secondes.
      final expirationDate = DateTime.fromMillisecondsSinceEpoch(exp * 1000);
      final duration = expirationDate.difference(
        const Clock().now(),
      );
      _timer = Timer(duration, () async {
        final nextSession = await _getAuthSession();
        _sessionUpdated.add(nextSession);
      });
    }
  }
```

**Comment by MSKoWa** [comment]
Hi,

I had similar issues. I logged in, logged out, or whatever and my code did not run in the specified callback function where I set a lot of breakpoints. What I had was the following:
```
_authEventStream = amplify.Hub.listen(
      [HubChannel.DataStore],
      (HubEvent hubEvent) async {
        final event = hubEvent.eventName;
        ...

}
```

I removed the `async` keyword and it worked again....
