### ISSUE TITLE
ConfirmForgotPassword pauses hubSubscription indefinitely if an exception occurs

### ISSUE THREAD

**Issue by IsaacSnapDsk** [aws-amplify/amplify-flutter#5655]
### Description

When the `_confirmResetPassword()` method inside of `auth_bloc.dart` experiences an exception (like when entering an invalid confirmation code), the hub subscription does not resume. This results in subsequent events not being handled by the auth bloc, which in turn causes the ConfirmForgotPassword form to get stuck in an infinite loading state if the "Submit" button is pressed again.

I replicated the package locally and it looks like adding a `yield* const Stream.empty()` at the end of the method resolves this issue, a pattern that looks like it's being used in the other event handler methods.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [x] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Navigate to the ConfirmForgotPassword step in the Authenticator
2. Fill out the form but enter an incorrect confirmation code and submit the form
3. A banner should pop informing you that it's invalid
4. Put the correct confirmation code in the form and submit the form
5. Notice that the submit button gets put into a loading state indefinitely

### Screenshots

https://github.com/user-attachments/assets/95cf3bad-0983-43a6-b1a5-9f1c36d96432

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.0

### Amplify Flutter Version

2.4.0

### Deployment Method

Custom Pipeline

**Comment by tyllark** [comment]
Hi @IsaacSnapDsk thanks for taking the time to open up this issue. We will investigate and get back to you when we have an update.

**Comment by Equartey** [comment]
Hi @IsaacSnapDsk, thank you for the excellent write up. Your analysis was 100% correct and I have opened a PR with a fix. We will update you when its available.

**Comment by ekjotmultani** [comment]
Hello @IsaacSnapDsk, a fix for this has been released in Authenticator 2.5.1. Thanks again for reporting this issue and your work in documenting it so well for us. Let us know if you have any more questions.
