### ISSUE TITLE
S3 upload throws Concurrent read operations are not allowed! when uploading 32mb file

### ISSUE THREAD

**Issue by tmageebtr** [aws-amplify/amplify-flutter#5670]
### Description

Using code similar to the S3 upload example, chunked_stream_reader.dart throws 'Concurrent read operations are not allowed!'

This is caused by 2 processes trying to read from the file stream at the same time.

Potential issue identified tracing through s3_upload_task.dart:

_startNextUploadPartsBatch starts up to 4 chunk readers sequentially.  Each of these starts a synchronous process to send the chunk to S3.  As the uploads finish they trigger another call to  _startNextUploadPartsBatch  which waits for the first batch to finish.  If more than 1 upload process finishes before the first batch finishes we can end up with 2 new _startNextUploadPartsBatch both waiting for the first batch to finish.  When that first batch does finish, the 2 new _startNextUploadPartsBatch both start trying to read the file stream resulting in concurrent read attempts.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

Using example S3 upload code, upload file greater than 20Mb  (4 chunks * 5Mb max chunk)

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.4

### Amplify Flutter Version

2.5.0

### Deployment Method

Amplify Gen 2

**Comment by Equartey** [comment]
Hi @tmageebtr, thanks for taking the time to open this issue. We will investigate this issue and provide an update when we can.

**Comment by ekjotmultani** [comment]
Hi @tmageebtr, a fix for this has been released in Storage 2.5.1! Thanks again for reporting this issue. Let us know if you have any more questions.
