### ISSUE TITLE
AWS meta.llama3 access: UnknownOperationException With Status Code 200

### ISSUE THREAD

**Issue by dkliss** [aws-amplify/amplify-flutter#5675]
### Description

Hi, 

When i send a request to AWS Bedrock, specifically to Llama model below.

```
static const String metaLlamaID = 'us.meta.llama3-2-1b-instruct-v1:0';

static const String metaLlamaARN =
      'arn:aws:bedrock:us-east-1:*************:inference-profile/us.meta.llama3-2-1b-instruct-v1:0';


```

 I receive status code 200 but "Output: key have error as below. I can see in AWS console that I have permission to this model. 

`
flutter: AWS Bedrock Response for Success is us.meta.llama3-2-1b-instruct-v1:0: {Output: {__type: com.amazon.coral.service#UnknownOperationException}, Version: 1.0}`

To reproduce:

Step 1: Sign in using AWS Cognit as per approach in https://github.com/aws-amplify/amplify-flutter/issues/5236

Step 2: Send an Invoke request to the modelARN instead of mode ID. This has something to do with interference profile used for llama (as per docs).  

``i.e.` change this  final path = 'model/$modelId/invoke';  --> to this  final path = 'model/$modelARN/invoke';`

Step 3: Issue Send Command. I also added below to security policy:
```

 "Sid": "AllowBedrockInferenceProfiles",
            "Effect": "Allow",
            "Action": [
                "bedrock:GetInferenceProfile",
                "bedrock:CreateInferenceProfile",
                "bedrock:ListInferenceProfiles"
            ],
```

I was wondering if there is anything special I need to configure here. Any guidance will be appreciated.

Thanks

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Provided above. 

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.4

### Amplify Flutter Version

2.5.0

### Deployment Method

Amplify Gen 2

**Comment by Equartey** [comment]
Hi @dkliss, we will need to investigate the requirements of the `llama3` model in order to fully address your inquiry. As noted in the previous discussion, the support for different bedrock models is very limited at the moment. We will update you here when we have more information.
