### ISSUE TITLE
Local data store not syncing with cloud

### ISSUE THREAD

**Issue by gnsslrrcs** [aws-amplify/amplify-flutter#573]
Flutter datastore not updating data to cloud even after adding Amplify_API plugin. 

**Expected behavior**
After adding Amplify_API plugin, the data from local datastore will sync with cloud.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[-] Android
[-] iOS

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help others that might land on this page
https://github.com/aws-amplify/amplify-flutter/issues/822
