### ISSUE TITLE
Support for TOTP(Time-based One-time Password)

### ISSUE THREAD

**Issue by rhinozD** [aws-amplify/amplify-flutter#574]
Hi,
In the future, we want to implement an app with a "Sign-in with custom auth challenges" feature.
Like this: https://docs.amplify.aws/lib/auth/mfa/q/platform/js#sign-in-with-custom-auth-challenges

But now we just want to use setup TOTP.
Like JavaScript Library: https://docs.amplify.aws/lib/auth/mfa/q/platform/js#setup-totp

does amplify-flutter support Setup TOTP?
if it does, please show me how to do that.

Thank you so much.
Best Regard!

**Comment by abdallahshaban557** [comment]
Hi @rhinozD - This feature is now available in the latest version of Amplify 0.5.0. You can try it out using this [link](https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/flutter/)

**Comment by dnys1** [comment]
Re-opening. Custom auth support has been released in 0.5.0, but TOTP support is still unsupported. We will continue to track that feature in this ticket.

**Comment by dsambuk** [comment]
Hey! Are there any news on this? TOTP MFA is a vital part of one of my projects. Would be know about the plans on this. 
Thank you!

**Comment by abdallahshaban557** [comment]
Hi @dsambuk - we are currently discussing the design internally, and we will provide an update on this issue when we have a path forward!

**Comment by mikolaj1982** [comment]
any ETA when this will be released?

**Comment by tonyGlobow** [comment]
+1, also expecting this feature!

**Comment by abdallahshaban557** [comment]
We are almost there! We are finalizing our security reviews at this point and testing it thoroughly. We will provide an update on this when we have our date locked in!

**Comment by dnys1** [comment]
I'm very pleased to announce this feature has been released in v1.4.0 🚀

Please see [the docs](https://docs.amplify.aws/lib/auth/mfa/q/platform/flutter/) to learn about how to enable TOTP in your backend and the new [login](https://docs.amplify.aws/lib/auth/mfa/q/platform/flutter/#setting-up-totp-for-a-user) and [setup](https://docs.amplify.aws/lib/auth/mfa/q/platform/flutter/#enabling-totp-after-a-user-is-signed-in) flows which are available.

We have updated the [Authenticator](https://pub.dev/packages/amplify_authenticator) as well. If you're already using it, you shouldn't need to make any changes to take advantage of TOTP!
