### ISSUE TITLE
Can not pass data in ConfirmSignUpOptions()

### ISSUE THREAD

**Issue by shajedulislam** [aws-amplify/amplify-flutter#575]
```
SignUpResult signUpResult = await Amplify.Auth.confirmSignUp(
          username: widget.email,
          confirmationCode: _pinController.text,
          options: ConfirmSignUpOptions(),
        );
```

I need to pass clientMetada here but can not pass data in confirm signup option. Like,

```
{
  'clientMetada': {
    'IsDoctor': false,
    
  }}
```

 It says,
### Abstract classes can't be instantiated. Try creating an instance of a concrete subtype

Any solution?

**Comment by HuiSF** [comment]
Hi @shajedulislam `ConfirmSignUpOptions` is an abstract class, initiating an abstract class causes the error you encountered.

The auth plugin provides a concrete subtype [`CognitoConfirmSignInOptions`](https://github.com/aws-amplify/amplify-flutter/blob/master/packages/amplify_auth_cognito/lib/src/CognitoSignIn/CognitoConfirmSignInOptions.dart#L18) of `ConfirmSignUpOptions`, we can use this class to initiate the options. (Please note that `CognitoConfirmSignUpOptions` currently accept only named parameter `validationData`.)

e.g.

```dart
SignUpResult res = await Amplify.Auth.confirmSignUp(
          username: usernameController.text.trim(),
          confirmationCode: confirmationCodeController.text.trim(),
          options: CognitoConfirmSignUpOptions(
              validationData: {'testField': 'doctor'}));
```

Is this sufficient for your use case please?

**Comment by HuiSF** [comment]
In addition, there might be a feature gap here that `confirmSignUp` doesn't properly work with `clientMetadata`, will continue investigating.

**Comment by shajedulislam** [comment]
@HuiSF Thanks fro your response. Our web version already developed using client meta data and yes currently it only accepts validation data for flutter. We will try to manage using validation data but it would be better to bring it with client meta data also.

**Comment by HuiSF** [comment]
Hello @shajedulislam amplify-flutter 0.16.0 just released, which includes the support of passing `clientMetadata` as `confirmSignUp` options, please try it out, and feel free to follow if you are experiencing any issues. Thanks!
