### ISSUE TITLE
Need exactly the same completeNewPassword  function as the JavaScript Library

### ISSUE THREAD

**Issue by rhinozD** [aws-amplify/amplify-flutter#576]
Hi,
Our case is similar to the one below: 

https://github.com/aws-amplify/amplify-flutter/issues/560#issuecomment-834057529

but our attribute is `phone_number`.  Furthermore, we use `SMS_MFA_CODE` so the `phone_number` attribute must be set before login.
As your comment in the issue above, you are adding the `updateUserAtributes` function. Does it have to be done after login or not? If that's the case then it doesn't match our case.
Also is there any alternative solution?
Our customer wants an answer as soon as possible so please reply as soon as possible to us.
Thanks in advance for your help.

@Amplifiyer @haverchuck

**Comment by rhinozD** [comment]
Is there any update? 
Will it be resolved in the near future?

**Comment by haverchuck** [comment]
@rhinozD What exactly is the use case that is not satisfied?  Are you unable to login as a user who is in the 'FORCE_CHANGE_PASSWORD' state?  If so, you can use the confirmSignIn API to pass in the new password.  If this is not the problem you are having, can you lay out the specific API that is not working?

**Comment by rhinozD** [comment]
@haverchuck 
Thanks for the reply.

> Are you unable to login as a user who is in the 'FORCE_CHANGE_PASSWORD' state? If so, you can use the confirmSignIn API to pass in the new password. 

I tried confirmSignIn method. It works fine except that I want to add the `phone_number` attribute too.
Like this:
```
Map<String, String> userAttributes = { 'phone_number': phoneNumber, };
var options = CognitoConfirmSignInOptions(clientMetadata: userAttributes);
Amplify.Auth.confirmSignIn( confirmationValue: newPassword, options: options);
```
As I said above,
since I set SMS MFA as required the flow will be like this: 
`confirmSignIn → receive SMS text with OTP code → go to SMS OTP input screen → home Page`
so I need to set the `phone_number` attribute when doing confirmSignIn - What the javascript Library can do using the `completeNewPassword` function:
```
       Auth.completeNewPassword(
            user,               // the Cognito User Object
            newPassword,       // the new password
            // OPTIONAL, the required attributes
            {
              phone_number: '1234567890'
            }
```
Note that my application does not have the SignUp flow. Admin will run the batch and import users into the Cognito User Pool.
Is the [updateAttribute APIs](https://github.com/aws-amplify/amplify-flutter/pull/533) you mentioned be used to update the attributes before calling `confirmSignIn` API? It is still in the `FORCE_CHANGE_PASSWORD` state.

Thank you!

**Comment by haverchuck** [comment]
Related to this [amplify-android issue](https://github.com/aws-amplify/amplify-android/issues/683).

**Comment by haverchuck** [comment]
@rhinozD We are working on this.

**Comment by rhinozD** [comment]
@haverchuck Thank you for your reply.
When will this bug be fixed? We need to implement this in our app as soon as possible.

**Comment by haverchuck** [comment]
@rhinozD This will require some changes to additional libraries outside of amplify-flutter. Those changes are being worked on right now.

**Comment by haverchuck** [comment]
@rhinozD  We have merged a fix for this and it will be included in our next release.

**Comment by rhinozD** [comment]
@haverchuck Thank you so much!!!

**Comment by subhendukundu** [comment]
I have a question on a similar line. I am trying to add passwordless login with phone number.
In javascript API I would do something like this
1. Signup
```
try {
  await Auth.signUp({
    username: phoneNumber,
    password: Date.now().toString()
  });
} catch {
  // Handle sign up error
}
```
Which I am using
```
final phone = phoneNumberController.text.trim();
    final password = generateRandomString(10);
    print(password);
    try {
      Map<String, String> userAttributes = {
        'phone_number': '+91$phone',
      };
      SignUpResult res = await Amplify.Auth.signUp(
        username: '+91$phone',
        password: password,
        options: CognitoSignUpOptions(userAttributes: userAttributes),
      );
      print(res);
      signin();
    } on AuthException catch (e) {
      print(e.message);
    }
```
This is adding my user, correctly.
2. Signin
```
try {
  const cognitoUser = await Auth.signIn(phoneNumber);
} catch {
  // Handle sign in errors
}
```
This is where the issue I am facing.
```
try {
      SignInResult res = await Amplify.Auth.signIn(
        username: '+91$phone',
        password: '',  // This is required?
      );
      print(res);
    } on AuthException catch (e) {
      print(e.message);
    } finally {
      // TODO: setloader to true
    }
```
This is where I am stuck. What can we do here?

3. Custom Challenge
```
try {
  const cognitoUser = await Auth.sendCustomChallengeAnswer(user, OTP);
} catch {
  // Handle 3 error thrown for 3 incorrect attempts. 
}
```
What will be here?

```
try {
  SignInResult res = await Amplify.Auth.confirmSignIn(
    confirmationValue: '123456' // not required to pass user?
  );
  setState(() {
    isSignedIn = res.isSignedIn;
  });
} on AuthException catch (e) {
  print(e.message);
}
```

Any suggestions would be really helpful as stuck for a while now 🙏
