### ISSUE TITLE
Error with codegen and models preventing API sync

### ISSUE THREAD

**Issue by BesavedTech** [aws-amplify/amplify-flutter#578]
When I use your example for many to many relationships in datastore with this schema
[](https://docs.amplify.aws/lib/datastore/relational/q/platform/flutter#many-to-many)

`type Post @model @auth(rules: [{allow: public}]) {
  id: ID!
  title: String!
  rating: Int
  status: PostStatus
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

type PostEditor @model(queries: null) @key(name: "byPost", fields: ["postID", "editorID"]) @key(name: "byEditor", fields: ["editorID", "postID"]) @auth(rules: [{allow: public}]) 
  {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: AmpUser! @connection(fields: ["editorID"])
}`

API Sync fails and when I checked on the AWS Amplify data section, the table PostsEditor does not get created. and it shows it missing under post. 

I am not sure what i am doing wrong.

<img width="466" alt="Screenshot 2021-05-14 at 09 03 11" src="https://user-images.githubusercontent.com/78008731/118247375-a2885280-b492-11eb-812e-92581f405ecd.png">

**Comment by Merglobe** [comment]
@HuiSF yes it did and no I mean syncing in the app it self.

**Comment by HuiSF** [comment]
After making local changes to the GraphQL schema and data models, you would need to push the latest changes to AWS by running `amplify push`, as you mentioned "PostsEditor does not get created", it sounds like it's out of sync between AWS AppSync and your local changes.

You can check if you have local changes are pending to be pushed by running [amplify CLI](https://docs.amplify.aws/cli/start/workflows#common-cli-commands).

**Comment by offlineprogrammer** [comment]
Hi @Merglobe 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide more details

Regards
Mo

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help others that might land on this page
https://github.com/aws-amplify/amplify-flutter/issues/822
