### ISSUE TITLE
How to use accessKey and secretKey to upload files through amplify_storage_s3

### ISSUE THREAD

**Issue by ZTMIDGO** [aws-amplify/amplify-flutter#5783]
I don't see a case in the amplify_storage_s3 about using accessKey and secretKey, can you help me

**Comment by tyllark** [comment]
Hello @ZTMIDGO thank you for taking the time to create this issue. Just to clarify are you attempting to use an existing S3 bucket within your Amplify Application?

**Comment by ZTMIDGO** [comment]
> Hello @ZTMIDGO thank you for taking the time to create this issue. Just to clarify are you attempting to use an existing S3 bucket within your Amplify Application?

Yes, by using the accessKey and secretKey of the IMA user, something like this https://github.com/aws-amplify/amplify-flutter/issues/1416

**Comment by ekjotmultani** [comment]
Hi @ZTMIDGO , another clarifying question, do you essentially want to authenticate a given user using their access key to access their own s3 bucket?

**Comment by tyllark** [comment]
> Yes, by using the accessKey and secretKey of the IAM user, something like this https://github.com/aws-amplify/amplify-flutter/issues/1416

Hello @ZTMIDGO, It looks like this feature request was closed was closed by the customer and it was never implemented on the Flutter side. I will mark this issue a future request the parity the JS implementation, but unfortunately we do not have any workarounds in the meantime.

**Comment by ZTMIDGO** [comment]
@tyllark @ekjotmultani Thanks for the reply and look forward to future releases
