### ISSUE TITLE
DataStore makes my app crashing at run on IOS

### ISSUE THREAD

**Issue by fafriat** [aws-amplify/amplify-flutter#585]
When adding the DataStore plugin, the application is crashing at runtime (in IOS Simulator):  

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           12,8s
Debug service listening on ws://127.0.0.1:65508/HVt_gCraq6Q=/ws
Syncing files to device iPhone 12 Pro Max...
Lost connection to device.
I changed version (Pod) to 13.0... and did all version related changes..

Running with Xcode , I am getting nw_protocol_get_quic_image_block_invoke dlopen libquic failed
then execution is stopping in thee debugger with 

Thread1: EXC_BAD_ACCESS (code=2...)

in code:  public static func modelSchema(from name: ModelName) -> ModelSchema? {
        concurrencyQueue.sync {
            modelSchemaMapping[name]
        }
    }

any idea ?

**Comment by haverchuck** [comment]
@fafriat Thanks for posting this issue.  Could you please clarify:
* Which version of amplify-flutter are you currently using?
* What do you mean by 'all version related changes'?

**Comment by fafriat** [comment]
amplify -v
4.51.1

flutter --version
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (5 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

I changed the Podfile:
platform :ios, '13.0'
...
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
  end
end

I changed in Xcode IOS  deployment target to 13.0

**Comment by fafriat** [comment]
The problem disappear for me after I added :

`await Amplify.DataStore.clear();`

after the  Amplify.configure() call...

So it is certainly related to old/bad format data  from the  Appsync...

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822

**Comment by HuiSF** [comment]
Thank you @fafriat for reporting this issue and providing your solution! It looks like you have resolved this issue. I'll close this issue for now. Please feel free reopen or follow up if you have other issues.
