### ISSUE TITLE
Make a null-safety branch beta branch

### ISSUE THREAD

**Issue by sgehrman** [aws-amplify/amplify-flutter#591]
Waiting for null-safety.  Is there a beta branch?  It shouldn't take more than an hour to convert.

**Comment by haverchuck** [comment]
@sgehrman There are some additional considerations we are working through - but we are planning on doing a tagged release of null safety as soon as we can.  Currently working on it.

**Comment by carlomigueldy** [comment]
Good to know @haverchuck 

Looking forward to that release

**Comment by sgehrman** [comment]
Any estimation on time?  I don't care if it's buggy, I'm just using s3.

**Comment by carlomigueldy** [comment]
Awesome! Thanks for sharing @sgehrman

**Comment by sgehrman** [comment]
Didn't work:

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:amplify_storage_plugin_interface
- package:amplify_core
- package:amplify_auth_plugin_interface
- package:amplify_analytics_plugin_interface
- package:amplify_datastore_plugin_interface
- package:amplify_api_plugin_interface
- package:date_time_format

**Comment by chillbrodev** [comment]
@haverchuck Any update on the branch? Amplify is blocking me from being sound null safe. Thanks in advance and appreciate all the hard work that goes into Amplify.

**Comment by Ashish-Nanda** [comment]
@chillbrodev We are currently testing the Auth, Storage, Analytics and API packages which have been migrated. We'll do a pre-release sometime soon for those categories and update this thread as soon as its availble.

**Comment by Ashish-Nanda** [comment]
Hi everyone the [pre-release version of null safety for Auth, Storage, API, and Analytics is now available](https://pub.dev/publishers/aws-amplify.com/packages).  To use it please update your pubspec.yaml to use `0.2.0-nullsafety.0`. Do let us know your feedback or if you encounter any issues.

We are currently working on upgrading Datastore to Null Safety and will share updates once that is ready.

**Comment by Ashish-Nanda** [comment]
**Amplify Flutter `0.2.0` with support for null safety is now released!**

The example apps have all been migrated to null safety as well. You can refer to this [branch](https://github.com/aws-amplify/amplify-flutter/tree/null-safety-master)

Please take a look at the docs for [instructions on how to migrate your app](https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter)

Do let us know if you have any questions or feedback.
