### ISSUE TITLE
SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)

### ISSUE THREAD

**Issue by shajedulislam** [aws-amplify/amplify-flutter#594]
`CognitoAuthSession cognitoAuthSession = await Amplify.Auth.fetchAuthSession();`

I am using it to check if user signed in or not with the  help of `cognitoAuthSession.isSignedIn`

Previously I got this error mentioned in title on every devices but after new plugin update and also pod update, app is running well in ios emulators and also real ios devices. Release build also working fine for ios devices but I am facing this error now when app is building from Microsoft app centre which is a release build. Any help with that?

**Comment by shajedulislam** [comment]
We deployed the app on apple test flight. Getting same error but working fine on emulators and also release build on real device.

**Comment by offlineprogrammer** [comment]
Hi @shajedulislam 

I couldn't reporduce this issue. I am using the following on Apple store and it is working fine

``` Dart  
Future<bool> isSignedIn() async {
    AuthSession authSessions = await Amplify.Auth.fetchAuthSession();
    return authSessions.isSignedIn;
  }
```

Feel free to test using the latest build and let us know if you got any issues

Regards
Mo

**Comment by offlineprogrammer** [comment]
Hey @shajedulislam 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
