### ISSUE TITLE
No documentation available to configure the Phone OTP based sign up process.

### ISSUE THREAD

**Issue by latheeshvmv** [aws-amplify/amplify-flutter#606]
**Describe the bug**
How to add phone and confirm sign up via phone OTP and not with email OTP.

There is currently no documentation provided for it. Documentation only covers the email

Please assist.

**To Reproduce**
1. Go to 'https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter'

**Expected behavior**
Documentation for the process?

**Comment by offlineprogrammer** [comment]
Hi @latheeshvmv

We updated the docs for this here https://docs.amplify.aws/lib/auth/sms_flows/q/platform/flutter#sign-up

Regards
Mo

**Comment by latheeshvmv** [comment]
Thank you
