### ISSUE TITLE
Unrecognized DataStoreHubEvent: outboxMutationFailed

### ISSUE THREAD

**Issue by Lorenzohidalgo** [aws-amplify/amplify-flutter#611]
**Describe the bug**
There are some Events for DataStoreHubEvent that are not recognized and therefore cant be handled with a hubSubscription.

For some reason DataStore won't update a specific model and since the event is not recognized the only error log that I'm receiving is:
`E/amplify:flutter:datastore(27989): Unrecognized DataStoreHubEvent: outboxMutationFailed`

**To Reproduce**
1. Create a Flutter Project with DataStore
2. Make some CRUD operations
3. See error - some events are not recognized

**Expected behavior**
The event should be recognized or a detailed error description should be prompted to be able to debug the error.

**Platform**
Amplify Flutter currently supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [VersiÃ³n 10.0.19042.985], locale es-ES)
    • Flutter version 2.2.0 at C:\DEVELOPMENT\SRC\flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\Lorenzo HG\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
 - Device: Emulated Pixel 4
 - OS: Android 11
 - Version API30

**Comment by HuiSF** [comment]
`OutboxMutationFailedEvent` would be published when processing a mutation in the outbox went wrong. Currently the flutter library doesn't have a specific handling of this exception, therefore it logs it as "not recognized" error. 

To be noted, `OutboxMutationFailedEvent` can have many different causes, it's unnecessarily an amplify-flutter library issue. But the library should forward this exception properly, to provide more meaningful exception information to consumer.

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822

**Comment by HuiSF** [comment]
With the latest release of amplify-flutter, it log will provide full details unhandled event instead of printing an error log.
