### ISSUE TITLE
[Flutter] Sync is not happening

### ISSUE THREAD

**Issue by sganeshkanna** [aws-amplify/amplify-flutter#615]
**Describe the bug**
Unable to see the data in Admin dashboard content menu after save from Flutter application

**To Reproduce**
Enabled API Key Authorization mode
Able to query data from data store
Amplify.DataStore.save(item) saved item into local db and I can see the data in subsequent query.
But its not reflected in admin UI content.
Similarly after uninstalling data is gone
So the issue is Amplify.DataStore.save(item) only save the data in local and not syncing to backend.
I am running this in Android

**Expected behavior**

*
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M21
 - OS: 10.0

**Additional context**

**Comment by Lorenzohidalgo** [comment]
Are you initializing the Amplify API plugin in your application?

**Comment by fjnoyp** [comment]
It seems that only local storage of Datastore is working.  The remote syncing appears to be disabled for some reason. 

Did you configure Amplify API And Datastore via the amplify cli?  Amplify cli will generate a amplifyconfiguration.dart file that Amplify Flutter uses to communicate and store/query data from your backend.

**Comment by sganeshkanna** [comment]
@Lorenzohidalgo @fjnoyp 
Below is my amplifyconfiguration.dart. 


const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "RentalService": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://<Something>.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "<Something>"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://<Something>.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "<Something>",
                        "ClientDatabasePrefix": "RentalService_API_KEY"
                    },
                    "RentalService_AWS_IAM": {
                        "ApiUrl": "https://<Something>.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "<Something>_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:<Something>",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_<Something>",
                        "AppClientId": "<Something>",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "<Something>",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "<Something>",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';

**Comment by Lorenzohidalgo** [comment]
@sganeshkanna it seems that API is configured, are you initializing the plugin?

Here is an example of how I'm initializing auth, analytics, DataStore, API and S3:

```dart
Future<void> _configureAmplify() async {
    final auth = AmplifyAuthCognito();
    final analytics = AmplifyAnalyticsPinpoint();
    final data = AmplifyDataStore(modelProvider: ModelProvider.instance);
    final api = AmplifyAPI();
    final s3 = AmplifyStorageS3();
    if (!Amplify.isConfigured) {
      try {
        Amplify.addPlugins([auth, analytics, data, api, s3]);

        await Amplify.configure(amplifyconfig);
      } on AmplifyAlreadyConfiguredException {
        // do something
      } catch (e) {
        print(e);
      }
    } else {
     // do something else
    }
  }
```

**Comment by sganeshkanna** [comment]
On launch I have configured amplify,


    try {
      // add Amplify plugins
      await Amplify.addPlugins([_dataStorePlugin, _apiPlugin, _authPlugin]);

      // configure Amplify
      //
      // note that Amplify cannot be configured more than once!
      await Amplify.configure(amplifyconfig);
      print("Amplify Congigured");
    } catch (e) {
      // error handling can be improved for sure!
      // but this will be sufficient for the purposes of this tutorial
      print('An error occurred while configuring Amplify: $e');
    }

Where plugin variables are declared as fields inside the class
final AmplifyAPI _apiPlugin = AmplifyAPI();
final AmplifyAuthCognito _authPlugin = AmplifyAuthCognito();
final AmplifyDataStore _dataStorePlugin =
AmplifyDataStore(modelProvider: ModelProvider.instance);

**Comment by Lorenzohidalgo** [comment]
Are you getting any type of error on the output logs? what kind of DataStore Events are you seeing?

**Comment by HuiSF** [comment]
Could you also watch the logs in debug console, see if you can find something like

```
I/amplify:aws-datastore(23474): Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore(23474): Setting currentState to SYNC_VIA_API
```
`Setting currentState to SYNC_VIA_API` is the flag if the datastore can sync remotely.

**Comment by sganeshkanna** [comment]
yes, @HuiSF  I am getting like what you mentioned.


E/amplify:aws-datastore(26636): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore(26636): DataStoreException{message=Timed out waiting for subscription processor to start., cause=null, recoverySuggestion=Retry}
E/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.startSubscriptions(SubscriptionProcessor.java:154)
E/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:309)
E/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/amplify:aws-datastore(26636): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:aws-datastore(26636): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/amplify:aws-datastore(26636): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:aws-datastore(26636): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:aws-datastore(26636): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore(26636): API sync failed - transitioning to LOCAL_ONLY.
W/amplify:aws-datastore(26636): DataStoreException{message=Timed out waiting for subscription processor to start., cause=null, recoverySuggestion=Retry}
W/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.startSubscriptions(SubscriptionProcessor.java:154)
W/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:309)
W/amplify:aws-datastore(26636): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
W/amplify:aws-datastore(26636): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
W/amplify:aws-datastore(26636): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore(26636): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/amplify:aws-datastore(26636): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore(26636): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore(26636): 	at java.lang.Thread.run(Thread.java:923)
I/amplify:aws-datastore(26636): Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
I/amplify:aws-datastore(26636): Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore(26636): Stopping subscription processor.
W/oc.assetservic(26636): Long monitor contention with owner pool-29-thread-24 (466) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:165) waiters=2 in void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String) for 1.012s

**Comment by HuiSF** [comment]
Thanks for providing the logs @sganeshkanna 

>Timed out waiting for subscription processor to start.

The logs showed that GraphQL subscription timed out. GraphQL subscription default timeout period is 10 seconds when subscribe 5 or less models. When there are more than 5 models to subscribe, it adds 2 seconds for each additional model to the timeout period, this is decent. 

How many models do you have in your App?

Here are some suggestions for next step:

1. Check connectivity of your testing device (any network throttling or anything could disturb WebSocket connection?)
2. Double check if the network on your testing device can reach AWS AppSync services (you can find service endpoint information from AWS console)
3. Test with only 1 model see if the subscription can complete

**Comment by brownAddict** [comment]
> Thanks for providing the logs @sganeshkanna
> 
> > Timed out waiting for subscription processor to start.

Thank you very much, you saved me.

I have been having this same error for the past 8 days. Initially, I had 19 models and it always failed ("Timed out waiting for subscription processor to start"). After reading your post, I reduced my models to 4 and it synced successfully.

So, how do I increase the timeout period since the default is not enough? or am I supposed to have less than 5 models?

**Comment by HuiSF** [comment]
Glad to help @brownAddict 

Have you tested with Android platform? I have just noticed that this mechanism is not working properly with amplify-flutter
>When there are more than 5 models to subscribe, it adds 2 seconds for each additional model to the timeout period

So the timeout period is always 10 seconds regardless number of models to be subscribed...
I will soon open a PR to fix this issue.

**Comment by brownAddict** [comment]
Yes, I have tested it on Android (Physical device). It syncs seamlessly both ways (Device to Admin UI and Admin UI to device).

**Comment by HuiSF** [comment]
Fix to the `amplify-android` dependency has been merged, waiting for it gets release and integrate to `amplify-flutter`.

**Comment by richardmcclellan** [comment]
> I have been having this same error for the past 8 days. Initially, I had 19 models and it always failed ("Timed out waiting for subscription processor to start"). After reading your post, I reduced my models to 4 and it synced successfully.

FYI, AppSync has a limit of 50 subscriptions per web socket.  DataStore is currently only designed to open one web socket.   DataStore initiates 3 subscriptions (onCreate, onUpdate, onDelete) for each type, so effectively there is a limit of floor(50/3) = 16 types, currently.  

In the future, we may update DataStore to automatically open multiple web sockets when the number of total models exceeds 16.

**Comment by sganeshkanna** [comment]
Thanks for the inputs. Will check the same case in Android code and update here.

**Comment by brownAddict** [comment]
> FYI, AppSync has a limit of 50 subscriptions per web socket. DataStore is currently only designed to open one web socket. DataStore initiates 3 subscriptions (onCreate, onUpdate, onDelete) for each type, so effectively there is a limit of floor(50/3) = 16 types, currently.
> 
> In the future, we may update DataStore to automatically open multiple web sockets when the number of total models exceeds 16.

Noted. Thank you very much. This means I will have to wait for the update, because I am in the process of migrating an existing app and it needs at least 19 types.

**Comment by richardmcclellan** [comment]
I just did a little more digging and realized the limit has actually been [raised to 100 subscriptions per websocket](https://github.com/aws-amplify/amplify-js/issues/5050#issuecomment-632210401), so you can actually use DataStore with up to 33 types now.

**Comment by HuiSF** [comment]
Thanks for the info @richardmcclellan ! I'm wondering do we have developer documentation that describes the maximum number of models can be subscribed? I think that would be a helpful piece of information to share broadly.

**Comment by brownAddict** [comment]
Thanks for the info @richardmcclellan

**Comment by alecellis1985** [comment]
> yes, @HuiSF I am getting like what you mentioned.
> 
> E/amplify:aws-datastore(26636): Failure encountered while attempting to start API sync.
> E/amplify:aws-datastore(26636): DataStoreException{message=Timed out waiting for subscription processor to start., cause=null, recoverySuggestion=Retry}
> E/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.startSubscriptions(SubscriptionProcessor.java:154)
> E/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:309)
> E/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
> E/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
> E/amplify:aws-datastore(26636): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/amplify:aws-datastore(26636): at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> E/amplify:aws-datastore(26636): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/amplify:aws-datastore(26636): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/amplify:aws-datastore(26636): at java.lang.Thread.run(Thread.java:923)
> W/amplify:aws-datastore(26636): API sync failed - transitioning to LOCAL_ONLY.
> W/amplify:aws-datastore(26636): DataStoreException{message=Timed out waiting for subscription processor to start., cause=null, recoverySuggestion=Retry}
> W/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.startSubscriptions(SubscriptionProcessor.java:154)
> W/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:309)
> W/amplify:aws-datastore(26636): at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
> W/amplify:aws-datastore(26636): at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
> W/amplify:aws-datastore(26636): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> W/amplify:aws-datastore(26636): at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> W/amplify:aws-datastore(26636): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> W/amplify:aws-datastore(26636): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> W/amplify:aws-datastore(26636): at java.lang.Thread.run(Thread.java:923)
> I/amplify:aws-datastore(26636): Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
> I/amplify:aws-datastore(26636): Setting currentState to LOCAL_ONLY
> I/amplify:aws-datastore(26636): Stopping subscription processor.
> W/oc.assetservic(26636): Long monitor contention with owner pool-29-thread-24 (466) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:165) waiters=2 in void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String) for 1.012s

Im having this same issue, @HuiSF any ETA on the fix for the 10 sec upgrade? can you test with 20models so we really can use this in real life? I am really behind in development time with a client because this sync issues and the current logs that do not say what's the issue. Could we try to add more try catches to the current solution and in cause expose something else than null?

**Comment by HuiSF** [comment]
Hi all, amplify-flutter `0.16.0` just released, which includes the the integration of amplify-android 1.19.0.
The fore-mentioned subscription timeout issue happened in Android when subscribing more than 5 models should be mitigated. Please feel free to follow up if you are still experiencing issues around subscription.

**Comment by offlineprogrammer** [comment]
Hi All

I am closing this issue for now 
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help others that might land on this page
https://github.com/aws-amplify/amplify-flutter/issues/822
