### ISSUE TITLE
Setting up a Flutter project

### ISSUE THREAD

**Issue by justinfargnoli** [aws-amplify/amplify-flutter#62]
**Which Category is your question related to?**
CLI (`amplify init`)

**Amplify CLI Version** 
4.27.2

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**
![Screen Shot 2020-08-19 at 11 21 22 AM](https://user-images.githubusercontent.com/34139864/90654174-17817100-e20e-11ea-9a36-49d0dba3fc35.png) 
(There are no other options below javascript in the drop down menu at the bottom of the screenshot.)

I'm trying to setup my flutter app repo to use the developer preview of amplify-flutter. However, when I run `amplify init` there is no option to select a flutter app like there is in the [tutorial](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter#n3-provision-the-backend-with-amplify-cli). Am I not using the CLI correctly, am I not using the correct version of the CLI, is this a bug in the CLI, or is this not yet supported in the CLI? If the last case is true, then how should I set up a Flutter project to work with the developer preview of amplify-flutter?

**Comment by haverchuck** [comment]
@justinfargnoli The README in our Github repo pointed users to the instructions for the stable install of the CLI, instead of the Flutter preview.  We have corrected the issue.  As noted above, you need to run `npm install -g @aws-amplify/cli@flutter-preview`.
