### ISSUE TITLE
Generic AuthException being thrown 

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#623]
Hi there.

When user is already signed in, an AuthException is thrown instead of a FlutterInvalidStateException. I can only see that it is a FlutterInvalidStateException if I open the "underlyingException" attribute inside the AuthException.

Shouldn't it throw a FlutterInvalidStateException so I could handle it easier?

Furthermore, it would be nice if every exception thrown by Amplify  were specific and not a generic AuthException.

**Comment by Jordan-Nelson** [comment]
Hi @brunovsiqueira - Thanks for opening this issue. Would you mind filling out the issue from the issue template? I am particularly looking for steps to reproduce (are you simply calling signIn when a user is already signed in?), platform (iOS, Android, or both) and the version of amplify flutter you are using. Thanks.

**Comment by brunovsiqueira** [comment]
Sure @Jordan-Nelson.

Yes, I am simply calling signIn when a user is already signed in. I tested on Andorid, but I guess it also happens on iOS. We are using Amplify 0.1.5 now.

**Comment by Jordan-Nelson** [comment]
@brunovsiqueira - this has been resolved as of version 0.2.1. You should now see an InvalidStateException on both platforms when calling signIn with a user already authenticated.
