### ISSUE TITLE
dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-flutter#628]
The https://github.com/aws-amplify/amplify-flutter/blob/master/CONTRIBUTING.md#architecture-of-the-codebase link is dead, so that link in the top part of the file should be removed or a section added for it.

**Comment by ragingsquirrel3** [comment]
I think https://github.com/aws-amplify/amplify-flutter/blob/master/CONTRIBUTING.md#debugging also dead.

**Comment by offlineprogrammer** [comment]
PR [630](https://github.com/aws-amplify/amplify-flutter/pull/630) merged
