### ISSUE TITLE
Organize packages according to Dart package layout conventions

### ISSUE THREAD

**Issue by mrhota** [aws-amplify/amplify-flutter#633]
**Describe the chore**

Many of the amplify-flutter packages do not have `lib/src` directories, which seems to lead to API leakage in docs.

It isn't always clear what code is public API and what code is implementation for a package.

In an effort to clarify and tidy things up, I'd like to ensure all amplify-flutter packages follow the conventions laid out in the [Dart package layout page](https://dart.dev/tools/pub/package-layout).

**Expected behavior**

Once done, dartdocs should be tidier and clearer, and it should be easier to navigate the code, both as a client of this package, and a contributor.

**Additional context**

Once this chore is done, my near-term goal is also to begin refactoring packages according to the [Flutter Federated Plugins guidelines](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin).

Beyond that, these tasks are in service to my medium-term goal of implementing web support.

**Comment by dnys1** [comment]
Resolved as part of 0.3.0 release. Thanks again for raising this issue!
