### ISSUE TITLE
auth events see to not emit

### ISSUE THREAD

**Issue by rmargolinross** [aws-amplify/amplify-flutter#641]
**Describe the bug**
I am subscribing to auth events using the recommended `Amplify.Hub.availableStreams[HubChannel.Auth]!.map(_toAuthEvent);` and while debugging I am not seeing any of these get fired.

**To Reproduce**
Subscribe to the auth events and then trigger events that should fire them.

**Expected behavior**
The events should be triggered.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-US)
    • Flutter version 2.2.0 at /Users/rmargolinross/dev/flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rmargolinross/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • AD9976D1-BE17-47E6-A37B-CB3E3A9F3FBD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 91.0.4472.101

• No issues found!```

</details>

**Smartphone (please complete the following information):**
- Tested on ios and android emulators

**Comment by dnys1** [comment]
Hi @rmargolinross - thank you for creating a ticket for this issue. Can you please post a link to where that method was described? In the meantime, could you try using the method described [here](https://docs.amplify.aws/lib/auth/auth-events/q/platform/flutter)?

**Comment by rmargolinross** [comment]
Oh, it seems the documentation has been updated. I was doing it the old way as I have pointed out up above. I will try to change my code to use the format you linked to, but if the way I pointed out no longer works, it really should be removed from the api or deprecated somehow.

**Comment by dnys1** [comment]
Thanks for letting me know, @rmargolinross. By adding a listener to the stream in your example (e.g. with `.listen((event) => print(event))`, it should work. However, without a listener, the stream will not fire. Hope this helps and apologies for the incorrect documentation.
