### ISSUE TITLE
How to define pipeline resolvers?

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-flutter#645]
I want to use pipeline resolvers in my amplify projects.
Is Amplify support pipeline resolvers?

**Comment by dnys1** [comment]
Hi @yukitaka13-1110 - yes! Amplify is fully capable of integrating pipeline resolvers. Here are some resources to get you started:
- [Amplify Docs](https://docs.amplify.aws/cli/graphql-transformer/resolvers#custom-resolvers)
- [Tutorial](https://dev.to/dagasatvik10/add-pipeline-resolvers-in-aws-amplify-43ae)
- [Example Project](https://github.com/dnys1/habitr/tree/master/amplify/backend/api/habitr)

Hope this helps! Let me know if get stuck along the way.

**Comment by yukitaka13-1110** [comment]
@dnys1 Thank you for your reply.
I'll check it. Thank you so much!!
