### ISSUE TITLE
Logging has already been configured., recoverySuggestion: Remove the duplicate call to `Amplify.configure()

### ISSUE THREAD

**Issue by IMDSK** [aws-amplify/amplify-flutter#646]
i have seen the issue of AWS what's wrong in my code? ;-;

**Describe the bug**

flutter: AmplifyException(message: An unknown exception has happened.           Please take a look at 
        https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that 
        match your scenario, and file an issue with the details of the bug if there isn't.
  , recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: PlatformException(AmplifyAlreadyConfigured, Translating platform exception failed. Please take a look at https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't., {message: Logging has already been configured., recoverySuggestion: Remove the duplicate call to `Amplify.configure()`, underlyingException: nil}, null))

```
 Future<void> _configureAmplify() async {
    try {
      await Amplify.addPlugins([
        AmplifyAuthCognito(),
        AmplifyDataStore(modelProvider: ModelProvider.instance),
        AmplifyAPI(),
      ]);

      await Amplify.configure(amplifyconfig);
    } catch (e) {
      print(e);
    }
  }
}

```
![image](https://user-images.githubusercontent.com/35393027/122177117-828fe880-ceaf-11eb-9813-43d8e142fb24.png)
![image](https://user-images.githubusercontent.com/35393027/122077227-c211f280-ce25-11eb-98ab-809fadcb04db.png)
![image](https://user-images.githubusercontent.com/35393027/122077585-1026f600-ce26-11eb-9d96-2bce73538787.png)

**Comment by haverchuck** [comment]
@IMDSK Which version of amplify-flutter are you currently using in your app?

**Comment by offlineprogrammer** [comment]
Hey @IMDSK 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
