### ISSUE TITLE
Authenticate via social media

### ISSUE THREAD

**Issue by PiotrWpl** [aws-amplify/amplify-flutter#67]
Hi,

is there any way to use this package for authentication via Facebook/Google/Apple?

BTW: I'm really glad that we will finally have an official amplify-flutter package! Fingers crossed

**Comment by haverchuck** [comment]
@PiotrWpl Social sign-in is not currently available, but it is on the roadmap!

**Comment by PiotrWpl** [comment]
It would be great to have this working out of the box. Because currently, it's the most painful task for us in integration with Cognito from our Flutter app.

Can't wait for that!

**Comment by haverchuck** [comment]
@PiotrWpl Moving this issue over to 'discussions'.
