### ISSUE TITLE
Update documentation for sign in with web UI in android

### ISSUE THREAD

**Issue by fanwgwg** [aws-amplify/amplify-flutter#677]
**Describe the bug**
At https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android#update-androidmanifestxml, it's asking to use `HostedUIRedirectActivity` for versions of `amplify_android` 1.17.8+, given that the version of `amplify_android` used by amplify_flutter is 1.19.0, per #650, should the documentation at https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter#android-platform-setup be updated to using `HostedUIRedirectActivity` as well?

**Comment by hackrx** [comment]
I am seeing this warning in the console too,@cshfang can you please tell me which amplify_auth_cognito version does include this fix.
The version of amplify auth, which I am using:
```
amplify_auth_cognito: ^0.2.0
``` 
Warning:
`D/AuthClient(22687): Authorization flow completed successfully
W/amplify:flutter:auth_cognito:utils(22687): HostedUIRedirectActivity is not declared in AndroidManifest.`

**Comment by dnys1** [comment]
Thank you for reporting this bug. The docs have been updated now.
