### ISSUE TITLE
No HTTP response data when Amplify.API request is erroneous

### ISSUE THREAD

**Issue by ioantsaf** [aws-amplify/amplify-flutter#688]
**Describe the bug**
When an API status code > 299 is returned, an `ApiException` is thrown. The exception now contains the `int httpStatusCode`, as implemented [here](https://github.com/aws-amplify/amplify-flutter/pull/590), but it does not contain the response data (if available).

It would be a good improvement to include the HTTP response data, if available, like it is implemented in the [js SDK, where one can access the (erroneous) response data in the `error.response` object](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js).

**To Reproduce**
1. Perform an `Amplify.API.get()` request (or `.put()`, `.post()` etc.).
2. If the HTTP status code returned is > 299, an `ApiException` is thrown.
3. The exception does not contain the error response data, nor is it accessible as part of the exception message.

**Expected behavior**
The error response data is available as part of the `ApiException` object.

**Platform**
This issue is reproducible in:
[X] Android
[X] iOS

**Comment by ragingsquirrel3** [comment]
@ioantsaf thanks for bringing this request to our attention. I can see how the raw response might be useful. Offhand, I'm not sure how much effort might be required to add that to the exception in the Flutter library in a similar manner to JS code you mentioned. We will put this in our backlog for further consideration/investigation.

**Comment by ragingsquirrel3** [comment]
@ioantsaf the request was implemented in PR #721 and should go out with the next release.

**Comment by dnys1** [comment]
This is now available in amplify_api `0.2.1`: https://pub.dev/packages/amplify_api/changelog
