### ISSUE TITLE
Can't send a json object as input with amplify appsync

### ISSUE THREAD

**Issue by MathiasHaudgaard** [aws-amplify/amplify-flutter#699]
**Describe the bug**
I'm trying to create the mutation below
```json
mutation Mutation {
           createMatches(input: {
            id: "someEntryId",
            encodedJson: "{\"someId1\":3,\"someId2\":3,\"someId3\":2,\"someId4\":2}"
           }) {
             id
           }
         }
```
However, I'm getting the error: Invalid JSON payload in POST request from Amplify.API.mutate, but if I use the mutation above directly in Appsync, the mutation is valid. I'm not really sure if it's a bug in amplify or I'm just missing something. I Hope someone can help me out here 😄 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [x] Android
- [ ] iOS

**Comment by kyleVoodoo** [comment]
Hey @MathiasHaudgaard thanks for reaching out.  Can you provide the mutation string you are providing to Amplify.API.mutate?  Were you able to make sure that the syntax matched out examples, ie: 

```
String graphQLDocument =
        '''mutation CreateTodo(\$name: String!, \$description: String) {
              createTodo(input: {name: \$name, description: \$description}) {
                id
                name
                description
              }
        }''';
    var variables = {
      "name": "my first todo",
      "description": "todo description",
    };
```

**Comment by fjnoyp** [comment]
Hi @MathiasHaudgaard were you able to resolve this issue in the end?

**Comment by MathiasHaudgaard** [comment]
```json
mutation Mutation {
           createMatches(input: {
                         id: "someId1",
                         timestamp: "1625989630221",
                         eloDifference: 4.555293323375431,
                         cupsForEachPlayer: "{\"somePlayerId1\":\"2\",\"somePlayerId2\":\"2\",\"somePlayerId3\":\"3\",\"somePlayerId4\":\"3\"}",
                         winners: ["somePlayerId1","somePlayerId2"],
                         lossers: ["somePlayerId3","somePlayerId4"],
                         lastCup: "somePlayerId1"}) {
                          id
                          }
```

Your example does not match what I'm trying to do. I want to send some stringified JSON which can be seen in the above example. However, I went with another design so I'm not facing the problem anymore. We can close this issue for now. I'll reopen it if the problem occurs again. Thanks for the response 😄
