### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.util.List com.amplifyframework.devmenu.PersistentLogStoragePlugin.getLogs()' on a null object reference

### ISSUE THREAD

**Issue by FirdousNath** [aws-amplify/amplify-flutter#704]
**Describe the bug**
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.util.List com.amplifyframework.devmenu.PersistentLogStoragePlugin.getLogs()' on a null object reference

**Expected behavior**
This error shouldn't appear in Crashlytics

**Amplify versions**
```
`amplify_flutter: ^0.2.0-nullsafety.1
  amplify_auth_cognito: ^0.2.0-nullsafety.1
  amplify_storage_s3: ^0.2.0-nullsafety.1`
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[-] Android

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-IN) [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2) [✓] Xcode - develop for iOS and macOS [✓] Chrome - develop for the web [!] Android Studio ✗ Unable to find bundled Java version. [✓] Android Studio (version 4.1) [✓] Connected device (1 available)```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. Nexus5x]

**Comment by cshfang** [comment]
Hi @FirdousNath, would it be possible for you to provide some reproduction steps to help us understand how/when you are encountering this exception? Per [this comment](https://github.com/aws-amplify/amplify-android/issues/800#issuecomment-813515292), the dev menu should be disabled by default.

**Comment by offlineprogrammer** [comment]
Hi @FirdousNath 

Following up on this. If you are still experiencing an issue, please provide the info requested above.

Regards
Mo

**Comment by FirdousNath** [comment]
I am not able to reproduce. Actually I am not sure why this error is being raised. Maybe when I submit app to google play store, Google is automate testing it. Not sure but my crashlytics console show this error every time I push new update to my app.

**Comment by offlineprogrammer** [comment]
Thanks @FirdousNath for the update. 

Closing this issue based on your feedback

Regards
Mo
