### ISSUE TITLE
[off-topic] monorepo tooling

### ISSUE THREAD

**Issue by Salakar** [aws-amplify/amplify-flutter#71]
Off topic a bit but wondering if you've considered using some tooling to help manage this monorepo and all the packages?

We built Melos for this purpose; https://github.com/invertase/melos - and might be useful :) we built this to help manage over 40 packages on the FlutterFire repo; https://github.com/FirebaseExtended/flutterfire/blob/master/melos.yaml - definitely helps to have all the packages interlinked and playing nice together locally, especially if you're doing a federated plugin setup.

**Comment by haverchuck** [comment]
@Salakar Thanks for your post - we will definitely take a look at this.
