### ISSUE TITLE
Using GCM for notification with Amplify in flutter

### ISSUE THREAD

**Issue by Monik09** [aws-amplify/amplify-flutter#715]
I want to know how to work with push notifications using amplify in flutter. I have added analytics and notifications using amplify add and wondering whether we can push notifications in flutter and configured FCM in it. 
I am unable to find something useful on google about push notifications in flutter with the help of amplify pinpoint.
Can anyone tell me whether it's in line or we have to work with something else?

**Comment by Monik09** [comment]
oh kk, i was able to do that.

**Comment by guoguoguilai** [comment]
Did you find the way to push notification in Flutter?

**Comment by Monik09** [comment]
Yes, @guoguoguilai. You have to set up google cloud messaging first and then you can send notifications through it. If you want to use amplify pinpoint with it, you will need a google token from the flutter app and then this token will be used on the pinpoint service web page to send the notification.

**Comment by Monik09** [comment]
I hope it helps @guoguoguilai

**Comment by Monik09** [comment]
If anyone is having difficulty with it, you can also go through this blog: 
[AWS Pinpoint With Flutter](https://monik.hashnode.dev/push-notification-using-amazon-pinpoint-in-flutter)

**Comment by vyendn3** [comment]
How about for iOS setup?
