### ISSUE TITLE
social login in iOs doesnt get token 

### ISSUE THREAD

**Issue by toshiossada** [aws-amplify/amplify-flutter#731]
I'm trying social  login at iOs but when I done login with google and then callback to my application the additionalInfo is null without token, this work fina at Android.
![image](https://user-images.githubusercontent.com/2637049/126362303-79800e9f-83b0-41a8-8cb4-0a63698cdf5c.png)

```
dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^0.2.0
  amplify_auth_cognito: ^0.2.0
```

```
$ flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```
```

                  try {
                    var res = await Amplify.Auth.signInWithWebUI(
                        provider: AuthProvider.google);

                    print(res);
                    print(
                        'TOKEN: ${res.nextStep?.additionalInfo['token'] ?? ''}');
                  } on AmplifyException catch (e) {
                    print(e.message);
                  } catch (e) {
                    print(e);
                  }
```

at Android thats works great

![image](https://user-images.githubusercontent.com/2637049/126340249-b9f9c8a9-95d3-4220-94d3-05606f49fce5.png)

**Comment by ragingsquirrel3** [comment]
Thanks for bringing this issue to our attention, will investigate as soon as possible.

**Comment by toshiossada** [comment]
My solution was put
```
final  session = await Amplify.Auth.fetchAuthSession(
            options: CognitoSessionOptions(getAWSCredentials: true));
```

![image](https://user-images.githubusercontent.com/2637049/126552595-616fa4d4-c8ba-46db-a653-aa3f48a7f7e1.png)


Is this correct?

**Comment by dnys1** [comment]
Sorry for the discrepancy you are seeing between iOS and Android's `additionalData` field. Your solution is the correct way to query the current user's auth tokens.

Closing this for now. Please reopen if you experience any issues with this solution.
