### ISSUE TITLE
Amplify support for Flutter desktop web (Chrome and Edge)

### ISSUE THREAD

**Issue by asad7452** [aws-amplify/amplify-flutter#732]
I checked on pub.dev and all the Amplify packages for Flutter do not have Web (Chrome and Edge) support.  When I try to debug in Android Studio for Chrome or Edge as target, I get an error saying that Amplify plugins cannot be loaded.  When are we planning to have support for desktop web?

**Comment by ragingsquirrel3** [comment]
Sorry but amplify-flutter does not yet support web. More discussion on this topic can be found on https://github.com/aws-amplify/amplify-flutter/issues/234 so I will close this issue as duplicate.
