### ISSUE TITLE
App crashes at startup (for release build) when using Datastore(GraphQL api)

### ISSUE THREAD

**Issue by Perniciosius** [aws-amplify/amplify-flutter#737]
**Describe the bug**
App crashes at startup when using Datastore(GraphQL api). It occurs only for release build. In debug and profile build, app functions normally.

**To Reproduce**
1. Setup Datastore GraphQL api with cloud sync.
2. Build a release build (```flutter build --release```)
3. Start app.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[✔️] Android
[] iOS: Haven't checked for iOS.

<summary>Logs</summary>
  
  ```
E/AndroidRuntime(10251):        at f.b.a.e.g.n.run(Unknown Source:21)
E/AndroidRuntime(10251):        at f.b.a.e.g.n.call(Unknown Source:0)
E/AndroidRuntime(10251):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10251):        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(10251):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10251):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10251):        at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(10251): Caused by: java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'f.b.a.e.e.e.i' (declaration of 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' appears in /data/app/~~g2cpLgC60oOqc7U9JpFk8Q==/com.perniciosius.feedback-h-s0MnWu_0xP0G5oN_AXHA==/base.apk)
E/AndroidRuntime(10251):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.l(Unknown Source:41)
E/AndroidRuntime(10251):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.m(Unknown Source:0)
E/AndroidRuntime(10251):        at com.amplifyframework.datastore.syncengine.S0.a(Unknown Source:11)
E/AndroidRuntime(10251):        at f.b.a.e.e.e.j.q(Unknown Source:10)
E/AndroidRuntime(10251):        at f.b.a.a.k.f(Unknown Source:5)
E/AndroidRuntime(10251):        at f.b.a.e.e.e.l.q(Unknown Source:17)
E/AndroidRuntime(10251):        at f.b.a.a.k.f(Unknown Source:5)E/AndroidRuntime(10251):        at f.b.a.e.e.e.J.run(Unknown Source:6)
E/AndroidRuntime(10251):        at f.b.a.a.p.run(Unknown Source:9)
E/AndroidRuntime(10251):        ... 7 more

```

**Comment by Jordan-Nelson** [comment]
This could be a similar issue to https://github.com/aws-amplify/amplify-flutter/issues/675, which only surfaced in apps created with a very recent version of flutter. 

@Perniciosius do you know what version of flutter you used to create the app? If you haven't upgraded flutter since you created the app, you can get the current version you are using with `flutter --version`.

**Comment by Aditya-goldsetu** [comment]
Hey! I am using the latest versions of flutter packages but still I am getting the same error.  Not just for datastore but also for the amplify api

**Comment by Aditya-goldsetu** [comment]
My environment and dependencies in pubspec.yaml


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^0.2.0
  amplify_api: ^0.2.0
  amplify_auth_cognito: ^0.2.0
  amplify_core: ^0.2.0
  amplify_datastore: ^0.2.0

**Comment by Aditya-goldsetu** [comment]
I think this is only occurring when the data model has  relationships. I created another environment where there is only one store table and there the same code works.

**Comment by Perniciosius** [comment]
@Aditya-goldsetu 
My data has only one table and this error is only coming in release build.

**Comment by Perniciosius** [comment]
@Jordan-Nelson Downgrading gradle plugin from v4.0.0 seems to have fixed the issue.

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822
