### ISSUE TITLE
Getting an Error on iPhone 12 & 12 pro

### ISSUE THREAD

**Issue by androidshivam** [aws-amplify/amplify-flutter#747]
**Description of bugs:** Unhandled Exception: SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)

**To Reproduce:** While installing the app in iOS 12 & 12Pro

**Expected Behavior:** Initialise the AWS plugins and fetch the current session of user null if User is not signin else gives null

**Stack Trace:**

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)
#0      AmplifyAuthCognitoMethodChannel.fetchAuthSession (package:amplify_auth_cognito/method_channel_auth_cognito.dart:239:7)
<asynchronous suspension>
#1      AmplifyAuthCognito.fetchAuthSession (package:amplify_auth_cognito/amplify_auth_cognito.dart:113:17)
<asynchronous suspension>
#2      CognitoService.isSignedIn (package:total_vision/services/cognito_service.dart:470:21)
<asynchronous suspension>
#3      CognitoService.configureAmplify (package:total_vision/services/cognito_service.dart:151:20)
<asynchronous suspension>

**Code Snippet:**

Future<bool> isSignedIn() async {
    final session = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true));
    if(session.isSignedIn){
      await getUserData();
      await fetchSession();
      unawaited(Future.delayed(Duration.zero, locator<AppSyncService>().queryAll));
    }
    return session.isSignedIn;
  }

**Environment(please complete the following information):**

SDK Version: 2.2.3
Dependency Manager: CocoaPods version 1.10.1
Xcode Version: Xcode 12.5.1, Build version 12E507

**Device: iPhone 12 & iPhone 12 Pro**
iOS Version: 14.6
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-26 at 11 31 25](https://user-images.githubusercontent.com/45711013/126941003-8301cbe3-8eb6-4fab-92c1-0ef183ccbbf5.png)

**Comment by yashaeologic** [comment]
Hey Shivam,

Are you using dependency in pub spec or using the whole package as custom dependancy.

**Comment by androidshivam** [comment]
name: total_vision
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
    # TODO: https://pub.dev/packages/rx_ble#ios
    # rx_ble: ^1.0.0
  rx_ble:
    git:
      url: git://github.com/IoTReady/plugin-flutter-rx-ble.git
      ref: master
  get_it: ^6.0.0
  # TODO: https://pub.dev/packages/flutter_cognito_plugin#ios
  pin_input_text_field:
    path: ./local_plugins/flutter_pin_text_field
  shared_preferences: ^2.0.6
  package_info: ">=0.4.0+17 <2.0.0"
  lottie: ^1.0.1
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.21.0+1
  country_pickers: ^2.0.0
  flutter_datetime_picker: ^1.3.8
  date_format: ^2.0.2
  progressive_image: ^1.0.1
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.1
  image_picker: ^0.7.4
  image_cropper: ^1.2.3
  flutter_image_compress: ^0.7.0
  path_provider: ^2.0.1
  amplify_flutter: ^0.2.0
  amplify_auth_cognito: ^0.2.0
  amplify_api: ^0.2.0
  url_launcher: ^6.0.3
  permission_handler: ^7.1.0
  app_settings: ^4.1.0
  share: ^2.0.1
  calendarro:
    path: ./local_plugins/flutter_calendarro
  # TODO: https://pub.dev/packages/flutter_local_notifications#ios-integration


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/ios_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          weight: 300
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500

**Comment by androidshivam** [comment]
> Hey Shivam,
> 
> Are you using dependency in pub spec or using the whole package as custom dependancy.

name: total_vision
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
    # TODO: https://pub.dev/packages/rx_ble#ios
    # rx_ble: ^1.0.0
  rx_ble:
    git:
      url: git://github.com/IoTReady/plugin-flutter-rx-ble.git
      ref: master
  get_it: ^6.0.0
  # TODO: https://pub.dev/packages/flutter_cognito_plugin#ios
  pin_input_text_field:
    path: ./local_plugins/flutter_pin_text_field
  shared_preferences: ^2.0.6
  package_info: ">=0.4.0+17 <2.0.0"
  lottie: ^1.0.1
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.21.0+1
  country_pickers: ^2.0.0
  flutter_datetime_picker: ^1.3.8
  date_format: ^2.0.2
  progressive_image: ^1.0.1
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.1
  image_picker: ^0.7.4
  image_cropper: ^1.2.3
  flutter_image_compress: ^0.7.0
  path_provider: ^2.0.1
  amplify_flutter: ^0.2.0
  amplify_auth_cognito: ^0.2.0
  amplify_api: ^0.2.0
  url_launcher: ^6.0.3
  permission_handler: ^7.1.0
  app_settings: ^4.1.0
  share: ^2.0.1
  calendarro:
    path: ./local_plugins/flutter_calendarro
  # TODO: https://pub.dev/packages/flutter_local_notifications#ios-integration


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/ios_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          weight: 300
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500

**Comment by haverchuck** [comment]
@androidshivam  Was there a previously authenticated user on this device, and the refresh token expired?

**Comment by androidshivam** [comment]
> @androidshivam Was there a previously authenticated user on this device, and the refresh token expired?

I've tested on multiple devices.I'm facing this issue on first install as well

**Comment by abdallahshaban557** [comment]
@androidshivam  are you still facing this issue?

**Comment by dnys1** [comment]
@androidshivam - is the confusion that `fetchAuthSession` is throwing an exception instead of returning a value of `isSignedIn = false`? Can you add a try/catch block and handle a `SessionExpiredException` the same way you'd handle a value of `false` for `isSignedIn`?

**Comment by abdallahshaban557** [comment]
@androidshivam  - did you try the workaround provided by @dnys1 ?

**Comment by Jordan-Nelson** [comment]
@androidshivam - If you are still facing this issue after trying the solution above, please let us know. Otherwise we will close it out. Thanks.
