### ISSUE TITLE
ApiException OkHttp client request java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by ken-ng-esotec** [aws-amplify/amplify-flutter#749]
When making queries / mutations that take long we receive and no known way to override

```
ApiException(message:` OkHttp client request failed., recoverySuggestion: See attached exception for more details., underlyingException: java.net.SocketTimeoutException: timeout)
```

Is it possible to allow the library to set timeouts per query in `Amplify.API.query` or `Amplify.API.mutate`

**Comment by dnys1** [comment]
Created a feature ticket to track this: https://github.com/aws-amplify/amplify-flutter/issues/798

**Comment by akshatbhuhagal** [comment]
Duplicate, Check issue #1612
