### ISSUE TITLE
signIn method should alow single argument?

### ISSUE THREAD

**Issue by subhendukundu** [aws-amplify/amplify-flutter#755]
In javascript API I would do something like this
1. Signup
```
// From my web app usin JS API
try {
  await Auth.signUp({
    username: phoneNumber,
    password: Date.now().toString()
  });
} catch {
  // Handle sign up error
}
```
Which I am using
```
// Flutter API
final phone = phoneNumberController.text.trim();
    final password = generateRandomString(10);
    print(password);
    try {
      Map<String, String> userAttributes = {
        'phone_number': '+91$phone',
      };
      SignUpResult res = await Amplify.Auth.signUp(
        username: '+91$phone',
        password: password,
        options: CognitoSignUpOptions(userAttributes: userAttributes),
      );
      print(res);
      signin();
    } on AuthException catch (e) {
      print(e.message);
    }
```
This is adding my user, correctly.
2. Signin
```
// From my web app usin JS API
try {
  const cognitoUser = await Auth.signIn(phoneNumber);
} catch {
  // Handle sign in errors
}
```
This is where the issue I am facing.
```
// Flutter API
try {
      SignInResult res = await Amplify.Auth.signIn(
        username: '+91$phone',
        password: '',  // This is required? Shouldn’t be optional?
      );
      print(res);
    } on AuthException catch (e) {
      print(e.message);
    } finally {
      // TODO: setloader to true
    }
```
This is where I am stuck. What can we do here?

3. Custom Challenge
```
// From my web app usin JS API
try {
  const cognitoUser = await Auth.sendCustomChallengeAnswer(user, OTP);
} catch {
  // Handle 3 error thrown for 3 incorrect attempts. 
}
```
What will be here for flutter?

```
// Flutter API
try {
  SignInResult res = await Amplify.Auth.confirmSignIn(
    confirmationValue: '123456' // not required to pass user?
  );
  setState(() {
    isSignedIn = res.isSignedIn;
  });
} on AuthException catch (e) {
  print(e.message);
}
```

Any suggestions would be really helpful as stuck for a while now 🙏

**Comment by dnys1** [comment]
Hi @subhendukundu, from what I can tell, you are using the [custom auth](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js#custom_auth-flow) flow. Unfortunately, this flow is unsupported in the Flutter SDK. I've marked this ticket as a feature request so that we can look to include it in one of our future releases.

In the meantime, please see the [docs](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter) for the current auth flows available in Flutter.

**Comment by orestesgaolin** [comment]
When using custom auth flow, is there any (hacky) way to achieve that in with Flutter SDK?

**Comment by dnys1** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-flutter/issues/410. Updates on support for the custom auth flow will be posted there.
