### ISSUE TITLE
Null safe generated data models are still producing a build error

### ISSUE THREAD

**Issue by davidjaldred** [aws-amplify/amplify-flutter#759]
Following the guide here: https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter

With the enableDartNullSafety feature flag set to “true”, and a default data model (named 'Dummy') without any changes made to it, I am still getting a build error in the generated model file (well 3 to be precise, but all on the same line: ` const Dummy._internal({required this.id}): ;`). Removing the colon fixes the problem.

**To Reproduce**
1. Add a model in the Admin UI and don't make any changes
2. Make sure project is using null safety
3. Run `amplify pull` and see build errors in generated model

**Expected behavior**
No build errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/33041809/127263941-84693452-4033-4939-b38f-835384b0ac2e.png)

![image](https://user-images.githubusercontent.com/33041809/127263831-852f5555-1743-41e2-ac6c-2569e1aa9b0d.png)

**Comment by HuiSF** [comment]
It looks like the [model gen](https://github.com/aws-amplify/amplify-codegen/blob/master/packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts#L302) always expects a model has other fields than `id` in the model.

I will forward this issue to amplif-codegen.

In addition, what's your use case of model which has only `id` field? Or is the example for only testing and reproduce this issue please?

**Comment by davidjaldred** [comment]
Ahh apologies, wasn't aware of the amplify-codegen repo. Thanks for forwarding.

Yes, mostly for testing purposes. However, I'm not using any data models yet and when I delete the model in the Admin UI, the save and deploy button is disabled, so I've had to keep it as a placeholder/dummy model for now.

**Comment by HuiSF** [comment]
Thanks for confirming and no worries!

Before the root cause gets resolved, I recommend you to add extra fields in a model, which can unblock you. The library creates tables in local db following the schema. If you need to remove any field from a model that you don't need, you can either invoke `Amplify.DataStore.clear()` API or delete testing App from device and reinstall to recreate local db.

**Comment by davidjaldred** [comment]
Great, will do, and thanks for taking the time to help!

**Comment by HuiSF** [comment]
The amplify-codegen fix [has been released](https://github.com/aws-amplify/amplify-codegen/releases/tag/v2.26.3).
