### ISSUE TITLE
Autogenerated GraphQL queries, mutations and subscriptions

### ISSUE THREAD

**Issue by NicolasCF96** [aws-amplify/amplify-flutter#769]
Hi guys, 

Coming from using Amplify with React and now with Flutter, I'm missing the auto generated code for schema.graphql queries, mutations and subscriptions. I was wondering if the command amplify codegen models would  generate the equivalent of src/queries.js, src/mutations.js, etc., as it is with React or otherwise if this has to be written by the developer, could you provide acesss to documentation or else that could be useful? I'm building an app which has a rather complicated schema.graphql with many models, one-to-many and many-to-many relationships, etc., therefore it would be very useful to have autogenerated code as in with Amplify React. Thanks!!

**Comment by Jordan-Nelson** [comment]
Hello @NicolasCF96 - This is not something that is currently supported by amplify-flutter. The feature request is being tracked at https://github.com/aws-amplify/amplify-flutter/issues/308. The second item in the feature request is for "GraphQL Request Helpers that automatically generate GraphQL requests". Please feel free to upvote that issue to express your interest. 

I am going to close this issue out as a duplicate.
