### ISSUE TITLE
Update MFA settings for specific user in Cognito

### ISSUE THREAD

**Issue by Emadeddin-eibo** [aws-amplify/amplify-flutter#770]
Is there any way to update the value of MFA (enable/disable) after Auth.signIn() or Auth.signUp() ?

<img width="648" alt="Screenshot 2021-08-02 at 7 42 38 PM" src="https://user-images.githubusercontent.com/47105622/127895988-937e8c2e-8592-42b1-88a5-ca7f0b1ad0bc.png">

**Comment by Jordan-Nelson** [comment]
Hello @Emadeddin-eibo - Thanks for taking the time to open the issue.

I want to confirm that you are looking for a way to do this programmatically using amplify-flutter, similar to what [amplify-js supports](https://docs.amplify.aws/lib/auth/mfa/q/platform/js#setup-mfa-type). If this is the case, this is not a feature that is supported by amplify-flutter, but I can mark this as feature request to track interest.

It looks like this is only supported by amplify-js currently. There is an open feature request in amplify-ios (https://github.com/aws-amplify/amplify-ios/issues/938) and a related feature request in amplify-android (https://github.com/aws-amplify/amplify-android/issues/671).

**Comment by chillbrodev** [comment]
Checking in to see if there has been any updates on this, seems like an important feature to have. If we can't do this via Flutter, what is the recommended approach? Please advise.

**Comment by dnys1** [comment]
This should be resolved when #3146 is released. Unfortunately, I don't have a timeframe for when that will happen, although it is a top priority of ours at the moment.

A recommended workaround would be to call [AdminSetUserMfaPreference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserMFAPreference.html) in your backend.

**Comment by dnys1** [comment]
I'm very pleased to announce this feature has been released alongside TOTP support in v1.4.0 🚀

Please see [the docs](https://docs.amplify.aws/lib/auth/mfa/q/platform/flutter/#setting-a-users-preferred-mfa-option) to learn about the new `fetchMfaPreference` and `updateMfaPreference` APIs.
