### ISSUE TITLE
Multiple environment

### ISSUE THREAD

**Issue by flutteresbolivia** [aws-amplify/amplify-flutter#772]
I have amazon as a provider of APIs, each one with its different cognito, development and production.

I want you to help me with how I can import or generate a production or development environment in my flutter application? Has anyone developed or any documentation on that?

**Comment by HuiSF** [comment]
In general amplify-flutter relies on amplify-cli to manage Amplify configuration and environments. [This amplify-cli documentation](https://docs.amplify.aws/cli/teams/multi-frontend) may help you to learn more about it.

In Flutter, `amplifyconfiguration.dart` contains the Amplify configuration details which is the equivalent to the `amplifyconfiguration.json` mentioned in the above documentation. Please feel free to follow up if you have further questions.

**Comment by flutteresbolivia** [comment]
> En general, amplify-flutter se basa en amplify-cli para administrar la configuración y los entornos de Amplify. [Esta documentación de amplify-cli](https://docs.amplify.aws/cli/teams/multi-frontend) puede ayudarlo a obtener más información al respecto.
> 
> En Flutter, `amplifyconfiguration.dart`contiene los detalles de configuración de Amplify que es el equivalente a lo `amplifyconfiguration.json`mencionado en la documentación anterior. No dude en hacer un seguimiento si tiene más preguntas.

So it means that, if I want to change from development to production environment, only with the commands it would be super simple, right?

And my files would be changed without having to modify it manually.

**Comment by HuiSF** [comment]
From my personal experience, `amplify pull` merges new configuration into existing `amplifyconfiguration.dart` if any.

I believe developers are still responsible to validate the effectiveness of the configuration ultimately by testing the App. 

In addition, I think multiple `amplifyconfiguration.dart` configuration files could be set, for different development environments, stages, release channels.

**Comment by flutteresbolivia** [comment]
> From my personal experience, `amplify pull` merges new configuration into existing `amplifyconfiguration.dart` if any.
> 
> I believe developers are still responsible to validate the effectiveness of the configuration ultimately by testing the App.
> 
> In addition, I think multiple `amplifyconfiguration.dart` configuration files could be set, for different development environments, stages, release channels.

thanks!

**Comment by andrespd99** [comment]
What about the `amplify` folder? There are some variables there that change between environments as in `team-provider-info.json`. Will this be an issue or can I work with multiple environments by only swapping the `amplifyconfiguration.dart`?
