### ISSUE TITLE
Need Clarification for new update 0.2.2

### ISSUE THREAD

**Issue by fdarsot** [aws-amplify/amplify-flutter#784]
With the addition of new feature feat: Auth Devices API (#735) in the new update 0.2.2 i was wondering if we can now call the different functions
Amplify.Auth.rememberDevice
Amplify.Auth.forgetDevice
Amplify.Auth.fetchDevices

can someone provide an example use case please. 

thank you

**Comment by dnys1** [comment]
Hi @fdarsot - great question and yes, these functions are now fully available. Please have a look at the [iOS](https://docs.amplify.aws/lib/auth/device_features/q/platform/ios) and [Android](https://docs.amplify.aws/lib/auth/device_features/q/platform/android) docs for use cases while we prepare Flutter-specific docs.

**Comment by dnys1** [comment]
Hi @fdarsot - The new docs are live here: https://docs.amplify.aws/lib/auth/device_features/q/platform/flutter
