### ISSUE TITLE
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#797]
**Describe the bug**
I am have been stuck with this issue for 2 days, this occurs when I try to update social(google) auth redirect url locally and via amplify admin UI.

**To Reproduce**
1.  Initialise new social auth via admin UI.
2. Paste the web client ID and secret and paste the redirect URL to GCP.
3. Insert redirect URL I want to add `<appName>://` but it does not allow me to do so I inserted myapp://
4. save and deploy
4. Now I changed the redirect URL from `myapp://` to `<appName>://` in `amplify/backend/auth/appName/parameters.json`
5. Now save and `amplify push`

Also, I was facing this same issue with the previous amplify project, which I deleted and created a new one. In that project I was replacing the `schema.graphql` with other `schema.graphql` file from another amplify project.

It gives the following error:
![image](https://user-images.githubusercontent.com/54453778/129028109-531204cf-88a4-40a4-b528-dcc95f8a6a9f.png)

I read somewhere that I need to go to CloundFormation and manually hit the continue `continue update rollback` but this option is disabled for me.
![image](https://user-images.githubusercontent.com/54453778/129031425-740d949a-7253-4386-8bd5-60ac2d0fde74.png)

amplify-cli version
`5.3.0`
dependencies
```
 amplify_api: ^0.2.0
  amplify_flutter: ^0.2.1
  amplify_auth_cognito: ^0.2.0
```

**Comment by dnys1** [comment]
@hackrx - was your issue resolved? This usually happens when trying to push while a previous push is still ongoing.

**Comment by hackrx** [comment]
I am no more facing this issue. Will open this issue again in future if needed.
Thanks :) for the follow up.
