### ISSUE TITLE
Custom HTTP Interceptors

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#798]
**Describe the bug**
Support for custom HTTP interceptors, as is available in both [iOS](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios#adding-headers-to-outgoing-requests) and [Android](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android#adding-headers-to-outgoing-requests)

- #671 
- #749

**Comment by martinzuccotti** [comment]
+1

**Comment by Nut41tank** [comment]
+1

**Comment by simranjeet09** [comment]
+1 this is required feature

**Comment by uppuluriaditya** [comment]
+1 this will be very useful

**Comment by Jordan-Nelson** [comment]
Hello everyone - If this is a feature you would like to see implemented, please give the original issue description a 👍 . We use this to quickly get an idea of how much interest there is in a feature. The "+1" comments can easily be missed whereas the 👍 count on the original issue description is easily viewable. Thanks.

**Comment by simranjeet09** [comment]
@Jordan-Nelson  we have a product developed based on amplify-flutter.   Both of the features mentioned in ticket #798 are required features for the product. Somehow we have figured out a workaround but it has made our code a mess as we need to make a lot of changes just to support multiple tokens and other auth stuff. 

Android and iOS both have  support for these features I am wondering why we are waiting for more votes / likes /comments on this feature request. It would make sense if amplify did not had this feature available on other platforms.

**Comment by Simon-PumpAndUp** [comment]
Hello @Jordan-Nelson, I'm using Rekognition via a rest API call to a lambda. The thing is, processing the images can take more than 10s and I get a timeout. My only solution is to call from the lambda another lambda and directly respond to the request. So increasing the timeout would ease a lot my environment.

**Comment by ragingsquirrel3** [comment]
Hello - We have recently released a new developer preview version of the API category ([amplify_flutter v1.0.0-next.1](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.1)). This new version is a full re-write of the API category in dart, and it supports Mobile, Desktop, and Web. The new version supports custom headers in a `GraphQLRequest` and request interceptors. You can see more info/examples [in the docs](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#adding-headers-to-outgoing-requests). I will update this issue again once this new version is out of developer preview.

Let me know if you have any questions!

**Comment by Jordan-Nelson** [comment]
Support for this was added in v1.0.0 of Amplify Flutter, which is now stable. You can see the docs on customizing http requests [here](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#adding-headers-to-outgoing-requests).

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
