### ISSUE TITLE
No implementation found for method configure on channel com.amazonaws.amplify/core

### ISSUE THREAD

**Issue by magicmass** [aws-amplify/amplify-flutter#80]
**Describe the bug**
When running the example app and viewing the loading page to the it will show a Missing plugin exception.

**To Reproduce**
1. Go to the example app
2. Run the example app
3. See error

**Expected behavior**
No exceptions thrown
**Screenshots**
Exception which i receive:

[ERROR:flutter/lib/ui/ui_dart_state.cc(167)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/core)
E/flutter ( 9324): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 9324): <asynchronous suspension>
E/flutter ( 9324): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 9324): #2      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
E/flutter ( 9324): #3      Amplify.configure (package:amplify_core/amplify_core.dart:66:35)
E/flutter ( 9324): #4      _MyAppState._initAmplifyFlutter (package:example/main.dart:34:19)
E/flutter ( 9324): #5      _MyAppState.initState (package:example/main.dart:23:5)
E/flutter ( 9324): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4697:58)
E/flutter ( 9324): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4533:5)
E/flutter ( 9324): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3503:14)
E/flutter ( 9324): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3262:18)
E/flutter ( 9324): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1217:16)
E/flutter ( 9324): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1188:5)
E/flutter ( 9324): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1130:17)
E/flutter ( 9324): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2622:19)
E/flutter ( 9324): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1129:13)
E/flutter ( 9324): #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
E/flutter ( 9324): #16     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
E/flutter ( 9324): #17     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 9324): #18     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9324): #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9324): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9324): #21     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9324): #22     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9324): #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter ( 9324): #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 9324): #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter ( 9324): #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter ( 9324): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 9324): 

**Platform**
Android flutter 

**Smartphone (please complete the following information):**
Android emulator running Android 10.0, API 29

**Comment by haverchuck** [comment]
@magicmass Which flutter sdk version are you using?

**Comment by kjones** [comment]
I am seeing something similar.
1. On Android, run the example app
1. When the LandingPage is shown with the "Sign In" and "Sign Up" buttons, hit the back button until the Android home screen is displayed.
1. Hit the Android app switcher button (rightmost) and return to the example app. App stays on the LoadingPage.

**Comment by fjnoyp** [comment]
Thanks @kjones for that very helpful snippet.  We are now able to reproduce the issue and are looking into it now.

**Comment by fjnoyp** [comment]
@kjones thanks for the additional context.  I believe this is a separate error that needs additional investigation, please see issue: https://github.com/aws-amplify/amplify-flutter/issues/99

@magicmass  if you are getting the issue you mentioned when the app is first starting up and no interaction has occurred with the app, then the likely problem has to do with flutter.  At this point, we recommend you to close your android emulator, run flutter clean, and restart the emulator.

**Comment by fjnoyp** [comment]
Closing issue as no further details have been provided.  

@magicmass if you are still facing this problem please feel free to provide more information and reopen the issue.
