### ISSUE TITLE
Datastore - iOS Nested Model int field crash 

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#800]
**Describe the bug**

In iOS, if you have a nested model with a field type of int, any queries will fail.  This is because iOS returns a `NSNumber` type which is treated as a double in Flutter.  As a result the following exception will be thrown: 

`
DataStoreException(message: An unrecognized exception has happened while Serialization/de-serialization. Please see underlyingException for more details., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: type 'double' is not a subtype of type 'int?')
`

**Comment by HuiSF** [comment]
Issue has been fixed.
