### ISSUE TITLE
No Way to Monitor S3 Progress

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-flutter#805]
**Describe the bug**
There is no way to add a listener to track download or upload progress for S3. This exists in iOS and android, however.

**Expected behavior**
Need a way to track download progress because my users are downloading large files. 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by julien-tamade** [comment]
Any word on if this is going to be worked on and approximate timeline?

**Comment by fjnoyp** [comment]
Hi @julien-tamade thanks for your patience here.  We've merged in a [PR](https://github.com/aws-amplify/amplify-flutter/pull/928) to add this missing feature.  It will be included in the next Amplify Flutter release we make.

**Comment by dnys1** [comment]
This was released in version 0.2.6
