### ISSUE TITLE
Example App - CLI Getting Started - Android - AMPLIFY_SIGNUP_FAILED - NullPointerException, CognitoUserPool

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#81]
I've run into a similar issue. I can also confirm that used `flutter pub get` to pull the packages in, and used amplify cli to initialise auth and analytics.
One thing to note tho that the analytics seem to work fine, and it's only the Auth that fails.

Error: 

`E/amplify:flutter:auth_cognito(11377): AMPLIFY_SIGNUP_FAILED
E/amplify:flutter:auth_cognito(11377): AmplifyException {message=Sign up failed, cause=java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference, recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito(11377): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:1)
E/amplify:flutter:auth_cognito(11377): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(11377): 	at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
E/amplify:flutter:auth_cognito(11377): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
E/amplify:flutter:auth_cognito(11377): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:auth_cognito(11377): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference
E/amplify:flutter:auth_cognito(11377): 	at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:1894)
E/amplify:flutter:auth_cognito(11377): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(11377): 	... 1 more
I/flutter (11377): Instance of 'AuthError'`

_Originally posted by @lamorltd in https://github.com/aws-amplify/amplify-flutter/issues/80#issuecomment-678463088_

**Comment by fransiskapw** [comment]
Hello, I'm encountering the same error right now and can't seem to find a workaround

I use the code sample from getting started doc:
```
try {
      Map<String, dynamic> userAttributes = {
        "email": email,
        "phone_number": phone,
        "name": name
        // additional attributes as needed
      };
      SignUpResult res = await Amplify.Auth.signUp(
        username: email,
        password: password,
        options: CognitoSignUpOptions(
          userAttributes: userAttributes
        )
      );
        print("isSignUpComplete ${res.isSignUpComplete}");
    } on AuthError catch (e) {
      print(e);
    }
```

The error is below (no additional detail, not sure how to find more info):
```
/amplify:flutter:auth_cognito(10669): AMPLIFY_SIGNUP_FAILED
I/flutter (10669): Instance of 'AuthError'
```

I already made sure that:
- Command `amplify add auth` is run,
- The Cognito User Pool is created in AWS Console

I even tried to run `amplify remove auth` and then added it again

My amplify version: 4.26.1-flutter-preview.0
My flutter version: 
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (2 weeks ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

**Comment by vhicks** [comment]
@fransiskapw were you able to figure this out? I followed the same steps and still get the error.
