### ISSUE TITLE
DataStore throws Exception when querying models with nullable lists if the list is null

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#813]
**Describe the bug**
DataStore throws an Exception when querying models with nullable lists if the list is null. This applies to List of type int, TemporalDate, TemporalDateTime, TemporalTime, TemporalTimestamp.

**To Reproduce**
1. Create a model with a field of type List<int>? (note: This is also reproducible with TemporalDate, TemporalDateTime, TemporalTime, TemporalTimestamp)

example schema.graphql

```graphql
type IntListTypeModel @model {
  id: ID!
  value: [Int]
}
```
2. Save an object with the list as null
```dart
  IntListTypeModel testModel = IntListTypeModel();
  await Amplify.DataStore.save(testModel);
```
3. Try to query that model
```dart
  var models = await Amplify.DataStore.query(IntListTypeModel.classType);
```
4. An exception in thrown
```
Message: "An unrecognized exception has happened while Serialization/de-serialization. Please see underlyingException for more details."
Underlying Exception: "type 'Null' is not a subtype of type 'List<dynamic>' in type cast"
```

**Cause:** The fromJson method on the model expects a List<dynamic> (not a List<dynamic>?) and throws an exception

**Expected behavior**
The model should return with a null value. 

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**NOTE**
Prior to this issue being marked as resolved, the DataStore integration tests that are skipped due to this issue should be updated. 

See: https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/integration_test/model_type_test.dart

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822

**Comment by HuiSF** [comment]
This issue should've been fixed by this change: https://github.com/aws-amplify/amplify-codegen/pull/227
The integration tests are no longer failing for the use cases described in the post.
