### ISSUE TITLE
[Feature Request] Support Cascading Save & Delete

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#818]
There are a few scenarios that produce unexpected behavior due to the lack of support for Cascading Save and Cascading Delete.

### Issue 1: NullPointerException when deleting hasOne nested model 

**Describe the bug**
A NullPointerException is thrown when trying to delete models with certain hasOne schemas.

**To Reproduce**
1. create a schema such as the one below
```graphql
type HasOneModel @model {
  id: ID!
  name: String!
  childID: ID!
  child: ChildModel @connection(fields: ["childID"])
}

type ChildModel @model {
  id: ID!
  name: String!
}
```
2. Save a model like so
```dart
var child = ChildModel(name: 'child');
var parent = HasOneModel(name: 'HasOne', child: child, childID: child.id);
await Amplify.DataStore.save(child);
await Amplify.DataStore.save(parent);
```
3. Attempt to delete the model
```dart
await Amplify.DataStore.delete(parent);
```

**Expected behavior**
The model should be deleted. There should not be an exception thrown.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

### Issue 2: DataStore does not return nested data for belongsTo relationship if parent model is created/saved after children

**Describe the bug**
Functionality was recently added to return nested data for belongsTo relationships. Example: In the Blog/Post/Comment example, when a Comment is queried, the associated Post should be returned.

This behavior does not work as expected if the parent model created after the child models.

```dart
// if the child is created first, and then the parent is created
// with the children passed into the constructor
// the parent will NOT be returned when querying the child
savePostFail() async {
  var comment = Comment(content: 'comment');
  await Amplify.DataStore.save(comment);
  var post = Post(title: 'post', rating: 1, comments: [comment]);
  await Amplify.DataStore.save(post);
  var queriedComments = await Amplify.DataStore.query(Comment.classType);
  var firstQueriedComment = queriedComments.first;
  expect(firstQueriedComment.post, isNotNull); // this will fail
}
```

The behavior does work if the parent model is created/saved BEFORE the children, like so:

```dart
// if the parent is created first, and then child is created
// with the parent passed into the constructor
// the parent will be returned when querying the child
savePostPass() async {
  var post = Post(title: 'post', rating: 1);
  await Amplify.DataStore.save(post);
  var comment = Comment(content: 'comment', post: post);
  await Amplify.DataStore.save(comment);
  var queriedComments = await Amplify.DataStore.query(Comment.classType);
  var firstQueriedComment = queriedComments.first;
  expect(firstQueriedComment.post, isNotNull); // this will pass
}
```

**To Reproduce**
1. create a schema like the one below:
```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
}

type Post @model @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  rating: Int!
  created: AWSDateTime
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  post: Post @connection(fields: ["postID"])
  content: String!
}
```
2. Attempt to execute the code in the sample above an observe that the first example does not return nested data, whereas the second will return nested data.

**Expected behavior**
Nested data should return regardless of how the parent/child models are constructed and saved, OR the docs the clearly state the expected behavior.

**Comment by cshfang** [comment]
I think this may be an issue with hasMany relationships as well:
https://github.com/aws-amplify/amplify-flutter/issues/767

**Comment by HuiSF** [comment]
Thanks for reporting this issue!

It seems the platform libraries currently are not supporting cascading save, e.g.

`Comment` belongs to `Post`, if a `Comment` saved (created) before its parent `Post`, the `belongsTo` relationship won't be created as `Comment` is missing `postId` field.

I think the new feature of cascading save and delete will be planned in the near future, will follow up and update the progress here.

**Comment by Jordan-Nelson** [comment]
**Note:** Prior to this issue being marked as resolved, the DataStore integration tests that are skipped due to this issue should be updated.

See: https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/integration_test/relationship_type_test.dart

**Comment by ianfmc** [comment]
Hi: is there a workaround to this issue? How can I delete from an Android or iOS application (with a hasOne relationship)?

**Comment by HuiSF** [comment]
Update:

The issue one in the description:
>A NullPointerException is thrown when trying to delete models with certain hasOne schemas.

This issue should has been fixed by this PR https://github.com/aws-amplify/amplify-android/pull/1614 amplify-flutter will integrate the fix once the fix is released in amplify-android, and amplify-flutter release can proceed.

NOTE: cascade delete (deleting hasOne parent cascade deletes hasOne child) will still not be supported by current implementation.
