### ISSUE TITLE
Cannot sync with the cloud

### ISSUE THREAD

**Issue by otabek1** [aws-amplify/amplify-flutter#821]
**Describe the bug**
I am using Amplify DataStore and API to save to on the cloud. But I am getting "Failed to load class "org.slf4j.impl.StaticLoggerBinder" error when I try to save an object. I followed the same tutorials from the documentation and Youtube.
**To Reproduce**
1. Create data model and deploy.
2.  Try to save it on the cloud with API

**Expected behavior**

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>
My code:
  ```
@override
  void initState() {
    super.initState();
    firstNameController = TextEditingController();
    lastNameController = TextEditingController();

    _configureAmplify();
  }

  void _configureAmplify() async {
    AmplifyDataStore datastorePlugin =
        AmplifyDataStore(modelProvider: ModelProvider.instance);

    final AmplifyAPI _apiPlugin = AmplifyAPI();

    await Amplify.addPlugins(
        [datastorePlugin, _apiPlugin, AmplifyAuthCognito()]);

    // Once Plugins are added, configure Amplify
    // Note: Amplify can only be configured once.
    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      print(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
    print("configured");
  }

  void addAdult() async {
    if (formKey.currentState!.validate()) {
      print("validated");
      try {
        final item = Adult(
            firstName: "Lorem ipsum dolor sit amet",
            lastName: "Lorem ipsum dolor sit amet",
            hasChildren: true,
            totalEarned: 123.45,
            totalTipped: 123.45,
            phoneNumber: "(555) 123-6789");
        await Amplify.DataStore.save(item).then((value) => print("done"));
      } catch (e) {
        print("Someting went wrong $e");
      }
    }
  }


```
</details>

**Comment by HuiSF** [comment]
Hello @otabek1 , thanks for opening this issue.
To my knowledge, `org.slf4j.impl.StaticLoggerBinder` warning was thrown from System Logger not amplify libraries. And it doesn't block amplify cloud syncing.

Here are some tips to help you resolve the issue:
* Check the content of `lib/amplifyconfiguration.dart` if it has correct configuration
* Check App running log, do you see something similar to below item?

```
I/amplify:aws-datastore(11946): Orchestrator transitioning from LOCAL_ONLY to SYNC_VIA_API
I/amplify:aws-datastore(11946): Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore(11946): Starting API synchronization mode.
```

* Check if you see any error message around ` Setting currentState to SYNC_VIA_API`.
* Do you see any errors/exceptions after executing `save` operation?

**Comment by otabek1** [comment]
Hey @HuiSF Thanks for the quick reply. 

Here are my logs and there does not seem to be any issue:
I/amplify:aws-datastore(12408): Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='a6506aa0-a1b6-42f8-a30c-73ceeffe91b0', serializedData={firstName=Lorem ipsum dolor sit amet, lastName=Lorem ipsum dolor sit amet, totalEarned=123.45, phoneNumber=(555) 123-6789, hasChildren=true, totalTipped=123.45, id=a6506aa0-a1b6-42f8-a30c-73ceeffe91b0}, modelName=Adult}, mutationType=CREATE, mutationId=4756adb3-015a-11ec-a6a4-73a67a16df0d, predicate=MatchAllQueryPredicate}
I/amplify:aws-datastore(12408): Successfully removed from mutations outboxPendingMutation{mutatedItem=SerializedModel{id='a6506aa0-a1b6-42f8-a30c-73ceeffe91b0', serializedData={firstName=Lorem ipsum dolor sit amet, lastName=Lorem ipsum dolor sit amet, totalEarned=123.45, phoneNumber=(555) 123-6789, hasChildren=true, totalTipped=123.45, id=a6506aa0-a1b6-42f8-a30c-73ceeffe91b0}, modelName=Adult}, mutationType=CREATE, mutationId=4756adb3-015a-11ec-a6a4-73a67a16df0d, predicate=MatchAllQueryPredicate}

 But it is still not showing up in Admin  UI

**Comment by HuiSF** [comment]
```
Successfully removed from mutations outboxPendingMutation
```
This message usually means the locally saved data has been synced to cloud successfully. Could you also check from the DynamoDB console, see if the data has been written into the tables?

**Comment by otabek1** [comment]
I checked it is empty.

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822

**Comment by HuiSF** [comment]
@otabek1 could you please paste the schema of the model that cannot be synced to cloud? (you can find the schema in `amplify/backend/api/<your api name>/schema.graphql`).

**Comment by offlineprogrammer** [comment]
Hey @otabek1 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by atomicalsoftwares** [comment]
I'm having this EXACT same issue and I cannot find when or how it stopped working.


type Configuration @model @auth(rules: [{allow: private}, {allow: private, provider: iam}]) {
  id: ID!
  var1: String
  var2: String!
  var3: String
  var4: String
  var5: String
  var6: String
  var7: String
} 

15509-15646 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.CompletionStageConsumer>
15509-15643 I/amplify:aws-datastore: Orchestrator lock acquired.
15509-15653 I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
15509-15653 I/amplify:aws-datastore: Starting to observe local storage changes.
15509-15655 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.FlowableStageSubscriber>
15509-15655 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.FlowableStageSubscriber>
15509-15655 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.FlowableFirstStageSubscriber>
15509-15655 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.FlowableFirstStageSubscriber>
15509-15655 I/art: Rejecting re-init on previously-failed class java.lang.Class<io.reactivex.rxjava3.internal.jdk8.FlowableFirstStageSubscriber>
15509-15655 I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
15509-15655 I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
15509-15653 I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
15509-15652 I/amplify:aws-datastore: Starting API synchronization mode.
15509-15653 I/amplify:aws-datastore: Orchestrator lock released.

I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation
15509-15657 I/APP: Configutation: Configuration {<------redacted------> , createdAt=null, updatedAt=null}
15509-15652 I/amplify:aws-datastore: Starting processing subscription events.
15509-15652 I/amplify:aws-datastore: Started subscription processor for models: [Configuration] of types [ON_CREATE, ON_UPDATE, ON_DELETE].

**Comment by atomicalsoftwares** [comment]
@otabek1 are you using a specific version of okhttp in your android library?

If yes, update to the latest will resolve the issue.
