### ISSUE TITLE
bucket url with amz token and credentials expires early than 7 days

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#824]
**Describe the bug**
I created a post on `1629324269125` i.e ` Thursday, August 19, 2021, 3:34:29.125 AM GMT+05:30` (2 days ago), and I stored the image URL in the dynamodb table. According to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html), this URL with appropriate credentials should be valid for 7 days. But it just expires in 2 days.
I think it is only valid for 24hrs or less, I am not sure. Right now when I am trying to access this URL from Browser I am getting this: 
![image](https://user-images.githubusercontent.com/54453778/130298160-5224d0ff-fec8-4fec-b0b2-93b6fe79104c.png)
When I parsed the URL, I got all the credentials: (only showing the query parameters)
![image](https://user-images.githubusercontent.com/54453778/130298495-06dc499f-eb43-4524-87ee-befab6637228.png)

**To Reproduce**
1. First upload an image to s3 bucket using this code, 
```
 try {
      final uploadOptions = S3UploadFileOptions(
          accessLevel: StorageAccessLevel.guest,
          contentType: "Image",
          metadata: {"imageType": "userImageURL"});

      print(
          "key before upload : ${key + "_" + userObj.id.toString() + "_" + userImageURL.toString().split('/').last}");
      UploadFileResult uploadresult = await Amplify.Storage.uploadFile(
          // options: uploadOptions,
          key: key + "_" + userObj.id.toString() + "_" + "userProfileImage",
          local: File(userImageURL.toString()));
      setState(() {
        operationMessage = "Image Uploaded to bucket";
        uploadFileResult = uploadresult;
      });
      await getUrl();
    } catch (e) {
      context.loaderOverlay.hide();
      print("Error occured while uploading image to s3");
      print(e);
    }
```
2. Then call getURL() to get the tokenized URl, 
```
 String key = uploadFileResult.key;
      print("key we have is $key");

      S3GetUrlOptions options = S3GetUrlOptions(
        accessLevel: StorageAccessLevel.guest,
        expires: 604799 // by default it's value is this only
      );
      GetUrlResult result =
          await Amplify.Storage.getUrl(key: key, options: options);
      print(result.url);
      setState(() {
        userImageURL = result.url;
      });
      return result.url;
    } catch (e) {
      context.loaderOverlay.hide();
      print('GetUrl Err: ' + e.toString());
    }
```
3. One more thing when I print it, this URL doesn't have any `x-amz-expiry` or any signature, but when I make a mutate operation using below code, then it just adds all the required parameters like `X-Amz-Algorithm`, `X-Amz-Security-Token`, `X-Amz-Date`, `X-Amz-Expires` etc.
```
 var passVariable = {
      'id': userObj.id,
      "userImageURL": userImageURL.toString(),
    };

    try {
      var requestUserUpdate = GraphQLRequest<String>(
          document: graphQLDocument, variables: passVariable);
      var operationUpdate = Amplify.API.mutate(request: requestUserUpdate);
      var res = await operationUpdate.response;
```
4. Now if you will open visit the Dynamodb and open the URL stored in the doc, it will be accessible for few hours (I am not sure for exactly how many hours)
5. The very next day you will see `Expired-Token` error, or on the flutter side, if you are rendering this image, you will get: 

![image](https://user-images.githubusercontent.com/54453778/130298816-b07e71a8-ee20-4ef6-82e2-91b85cc03bd7.png)

**Expected behavior**
The tokenized URL should be valid for at least 6 days.

**Comment by dnys1** [comment]
Hi @hackrx - so, the issue here is that there are two expirations at play:
1. The expiration of the user credentials (the security token). Every user, even unauthenticated users, have implicit access credentials which expire.
2. The expiration of the URL given valid access credentials.

The expiration of the token is thus the minimum of the two expiration times.

**Comment by dnys1** [comment]
A possible solution might be to save the key instead of the URL and have each user needing access generate a URL for themselves.

Closing this issue for now but please feel free to re-open if this solution does not work for you.
