### ISSUE TITLE
Support for Web, Desktop

### ISSUE THREAD

**Issue by Ch4rl3B** [aws-amplify/amplify-flutter#825]
It'll be awesome if you add support for Web, Desktop... can this be possible? An approach or alternative to this for flutter??

**Comment by Jordan-Nelson** [comment]
Hi @Ch4rl3B - Thanks for opening this request. There are existing feature requests for web support (https://github.com/aws-amplify/amplify-flutter/issues/234)  and desktop support (https://github.com/aws-amplify/amplify-flutter/issues/133). We will continue to use those issues to track support for web/desktop. Feel free to 👍  those issues to express your support.

I am going to close this issue as a duplicate to avoid confusion with the other issues.
