### ISSUE TITLE
Selective sync on owner field returns no records

### ISSUE THREAD

**Issue by rajd90** [aws-amplify/amplify-flutter#827]
**Describe the bug**
Before selective sync was introduced, my flutter app worked fine, although inefficient. After adding in the new sync expressions with query predicates on the owner field, the datastore sync seems to return no records at all. Remove the sync expressions seems to put things back to normal.

When I query the graphql API directly, in the same app, am do get results back when including the userId in the filter.

```
await Amplify.addPlugins([
      AmplifyAuthCognito(),
      AmplifyAPI(),
      AmplifyDataStore(modelProvider: ModelProvider.instance, syncExpressions: [
        DataStoreSyncExpression(Place.classType, () => Place.OWNER.eq(_userId)),
        DataStoreSyncExpression(
            Profile.classType, () => Profile.OWNER.eq(_userId))
      ]),
      AmplifyStorageS3()
]);
try {
    await Amplify.configure(amplifyconfig);
}
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[√] Android
[?] iOS - not tested on iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (3 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\-----\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\-----\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```

</details>

**Additional context**
I'd expect some easy way to selectively sync based on the owner of the record, as in a larger application, there's little reason to store data belonging to other users on the local device. This gets more tricky when it's the first setup on a device - the current approach of setting the sync expression has to be done when configuring amplify, which is started before the user signs in, so we don't know their username/userId yet.

Another question that pops up is, when using selective sync, will it take advantage of the GSI that I set up on the table, or does it just do a table scan? It would be better if it can take advantage of the GSI, given that it seems to be in line with the DynamoDB best practices.

Am I doing something wrong? Is there a better way to selectively sync only the user's own records?

**Comment by HuiSF** [comment]
Hi @rajd90 thanks for reporting this issue. I will look into the selective sync.

In the meantime, regarding your point
> selectively sync based on the owner of the record, as in a larger application, there's little reason to store data belonging to other users on the local device

I'd like to provide a different thought to achieve this.

Based on your description, the App needs only sync only the data belongs to the current user, and other users's data should not be synced . This can be achieved by leveraging DataStore model authorization. I personally think that's a better solution for the use case you described, and more secure.

Please take a look at https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter/

**Comment by kjones** [comment]
> Based on your description, the App needs only sync only the data belongs to the current user, and other users's data should not be synced . This can be achieved by leveraging DataStore model authorization. I personally think that's a better solution for the use case you described, and more secure.

While using owner auth does prevent other user's data from being synched, the AppSync VTL template will still perform an expensive DynamoDB table scan to find all of the owner's data in a table. I haven't looked at this in several months so this may no longer be the case... If that is still the case, how do you recommend getting the backend VTL to optimize use of owner auth and a "query by owner" DDB operation?

**Comment by EricRenForCode** [comment]
> Based on your description, the App needs only sync only the data belongs to the current user, and other users's data should not be synced . This can be achieved by leveraging DataStore model authorization. I personally think that's a better solution for the use case you described, and more secure.

@HuiSF  my app needs  only sync the data belongs to the current users too and I used the DataStore model authorization by adding @auth(rules: [{allow: owner}]) for each of my models. But after doing so, all the data are saved in local successfully but I am not able to find it by looking at DynamoDB tables. if i disabled model authorization, the data can sync to the cloud. 
Also, another questions. if one user upload the model data to the cloud with the app that doesn't implement model authorization, after enabling model authorization, can user still be able to fetch his pre-saved model data after logged in?

**Comment by HuiSF** [comment]
Hi @EricRenForCode thanks for following up on this thread. Regarding the issue you encountered could you please answer below question to help us triaging the issue?

1. Did you add `amplify_auth_cognito` to your project?
2. Were you able to configure the auth category by running `amplify add auth`?
3. After configuration, did you run `amplify push` to sync the configuration to cloud?
4. While testing, did you implement user sign in to ensure there is a valid user session?
5. Did you see any abnormal logs in App console after local saving?

To your question - According to the [documentation of "owner authorization"](https://docs.amplify.aws/cli/graphql-transformer/auth/#owner-authorization), when this auth rule is enabled on a model, a new field will be inserted into the model under the hood to store owner information for authentication on operations. From this, I think the data saved prior to enable the auth rule will be inaccessible with the auth role as the data doesn't have the ownership information.

**Comment by EricRenForCode** [comment]
> Hi @EricRenForCode thanks for following up on this thread. Regarding the issue you encountered could you please answer below question to help us triaging the issue?
> 
> 1. Did you add `amplify_auth_cognito` to your project?
> 2. Were you able to configure the auth category by running `amplify add auth`?
> 3. After configuration, did you run `amplify push` to sync the configuration to cloud?
> 4. While testing, did you implement user sign in to ensure there is a valid user session?
> 5. Did you see any abnormal logs in App console after local saving?
> 
> To your question - According to the [documentation of "owner authorization"](https://docs.amplify.aws/cli/graphql-transformer/auth/#owner-authorization), when this auth rule is enabled on a model, a new field will be inserted into the model under the hood to store owner information for authentication on operations. From this, I think the data saved prior to enable the auth rule will be inaccessible with the auth role as the data doesn't have the ownership information.

1. I added amplify_auth_cognito: ^0.2.4 into my project
2. yes. I configured amplify add auth. the app are able to sign in successfully.
3. yes. successfully push and No changes detected.
4. by calling Amplify.Auth.fetchAuthSession(), it is verified that user has signed in.
5. after local saving, the subscribed HubChannel received outboxMutationEnqueued and outboxStatus events. no other logs showed up. checking with Dynamo DB, nothing show up. if the app logout and cleared the DataStore and login again with the same user, the datastore cannot fetch the data.

**Comment by HuiSF** [comment]
Thanks for the info @EricRenForCode .. hum I suspect that something could go wrong with the underlying AppSync GraphQL request. By any chance... have you enabled logging for your AppSync API? If so when you go to "monitoring" section, you may discover some 400 errors, if you have any could you inspect the logs?

If not... we may need to inspect the network traffic of your device or simulator to intercept possible GraphQL error. (amplify-flutter currently doesn't have the custom `errorHandler` setup to catch underlying GraphQL errors :( )

**Comment by EricRenForCode** [comment]
Hi @HuiSF 

I just checked out the documentation: [https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter/#configure-custom-authorization-logic-with-aws-lambda](url). The owner based authorization with third party OIDC provider is not ready yet. My app use third party provider to login, I guess that could be the reason that users can not saved data into the cloud. right?

**Comment by dnys1** [comment]
Hi @EricRenForCode - apologies for the delayed response. OIDC is supported in DataStore as of version `0.2.4` as long as it is the primary authorization mode. Having additional authorization modes -- so-called "multi-auth" -- is not yet supported.

The docs were unfortunately out-of-date so I've updated them to reflect the latest info. Thank you for your patience and apologies again!

**Comment by EricRenForCode** [comment]
> Hi @EricRenForCode - apologies for the delayed response. OIDC is supported in DataStore as of version `0.2.4` as long as it is the primary authorization mode. Having additional authorization modes -- so-called "multi-auth" -- is not yet supported.
> 
> The docs were unfortunately out-of-date so I've updated them to reflect the latest info. Thank you for your patience and apologies again!

Hi @dnys1 - thanks for replying me and updating the docs. I am facing an issue when I set up auth rules with OIDC provider in my models. After I configured it in my schema.graphql and generated the models, I got errors like this:

`InvalidDirectiveError: @auth directive with 'oidc' provider found, but the project has no OPENID_CONNECT authentication provider configured.`

it looks like my OIDC provider its not configured, but my app is able to login successfully using OIDC providers.

**Comment by dnys1** [comment]
Closing due to @EricRenForCode's update. Please re-open or start a new thread if the issue continues.
