### ISSUE TITLE
Most QueryPredicates do not work with type double/float on Android

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#830]
**Describe the bug**
The majority of the QueryPredicates do not work with type double/float. When using lt, le, gt, ge, or between, the QueryPredicate has no impact on the query.

**To Reproduce**
Here is a schema and in integration test that can be used to reproduce this:

```graphql
type DoubleTypeModel @model {
  id: ID!
  value: Float
}
```

```dart
testWidgets('simple test', (WidgetTester tester) async {
  var models = [
    DoubleTypeModel(value: -10.0),
    DoubleTypeModel(value: -1.0),
    DoubleTypeModel(value: 0.0),
    DoubleTypeModel(value: 0.1),
    DoubleTypeModel(value: 2.1),
    DoubleTypeModel(value: 1000.0),
  ];

  for (var model in models) {
    await Amplify.DataStore.save(model);
  }
  var allModels = await Amplify.DataStore.query(DoubleTypeModel.classType);
  expect(allModels.length, 6);

  var someModels = await Amplify.DataStore.query(DoubleTypeModel.classType,
      where: DoubleTypeModel.VALUE.le(2.1));
  // this test will fail because all models will be returned
  expect(allModels.length, 5);
});
```

**Expected behavior**
QueryPredicates should work for type Double

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Comment by Jordan-Nelson** [comment]
**Note:** Prior to this issue being marked as resolved, the DataStore integration tests that are skipped due to this issue should be updated.

See: https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/example/integration_test/query_test/query_predicate_test/double_query_predicate_test.dart

**Comment by HuiSF** [comment]
Above described root cause should've been fixed. Will verify and enable corresponding integration tests.

**Comment by HuiSF** [comment]
Integration tests now runs query predicate with float/double values.
