### ISSUE TITLE
React to Flutter

### ISSUE THREAD

**Issue by EduardoGascaAP** [aws-amplify/amplify-flutter#832]
I contacted support because I wanted to pull my existing amplify project (React Js) to Flutter. They told me that it is not possible to do "amplify pull --appId XXXXXXXX". Moreover, they told me to set up my amplifycononfiguration.dart manually. We generated the file and it was checked by AWS amplify support team. We were not able to do "amplify codegen models" or "amplify codegen --apiId XXXXXXX". Right now Im trying to use the same Appsync and tables I use in React Js since it is my database.

**Expected behavior**
The behavior is that when appsync endpoint is specified in my config file it should generate graphql files and models.

**Comment by HuiSF** [comment]
Hi @EduardoGascaAP thanks for opening this issue.

I think `amplify pull` works with ampliffy-flutter, that's how I pull in my previously configured Amplify APIs etc.

Here's the basic flow I personally use:

1. Setup flutter project
2. `amplify pull` at the root of the flutter project
3. It prompts which authentication method you are going to use
4. It prompts which profile (previously configured for your React project) you want to use
5. Select the profile you are going to use
6. It prompts if you are going to modify the back-end
7. choose yes (if will pull down the API backend files including schema.graphql)

This process should automatically invoke `amplify codegen models` to generate Dart models according to your schema.graphql.
