### ISSUE TITLE
[doubt] Remember Device

### ISSUE THREAD

**Issue by flutteresbolivia** [aws-amplify/amplify-flutter#836]
I want to add a functionality in my mobile application.

I register my users through their phone number with SMS verification.

So when a user uninstalls the application from their phone and wants to log in again, they no longer have to check again to satisfy the user experience.

> with these new amplify flutter features, is this possible?

> Would it work by uninstalling the application doing the remember?

**Comment by nazarcybulskij** [comment]
> 

I have this issue :( Do you found solutions ??
