### ISSUE TITLE
DataStore query throws Exception with empty QueryPagination on Android

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#842]
**Describe the bug**
QueryPagination() has no required arguments. `page` is optional and `limit` defaults to 100. However, the query will fail on Android if no value page is supplied. `page` should either be required or default to 0. On iOS, the first page is returned if no page is supplied.

**To Reproduce**
Below is an integration test which will throw an exception on Android.

```dart
group('pagination', () {
  var models = List.generate(1000, (i) => Blog(name: 'blog $i'));
  setUp(() async {
    await configureDataStore();
    // clear data before each test
    await clearDataStore();
    for (var model in models) {
      await Amplify.DataStore.save(model);
    }
  });
  testWidgets('should return the models for the given page and limit',
      (WidgetTester tester) async {
    var blogs = await Amplify.DataStore.query(Blog.classType,
        pagination: QueryPagination());
  });
});
```

**Expected behavior**
`page` should either be required or default to 0. If `page` is not required, the query should not throw an exception without a supplied value.

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Comment by cshfang** [comment]
Should be fixed by #1533
