### ISSUE TITLE
Appsync unauthenticated read access examples?

### ISSUE THREAD

**Issue by kcsarith** [aws-amplify/amplify-flutter#846]
I just want to know how I can use Appsync to allow owners to create, read, update, delete from DynamoDB and everyone else to read only access.

Following the Amplify Documentation for Cognito owner CRUD and other read access is easy. When I created API I had the default authentication as Cognito and additional auth with IAM, then for my models auth rules I put. I saw this in a JavaScript video tutorial, not sure if it works with Flutter.
```
@auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
      { allow: public, provider: iam, operations: [read] }
    ]
  )
```
as well as { allow: private, operations: [read] } for testing just in case but I never seen anyone use this rule.

I also test this method on the documentation to fetchSession when the user is not logged in as well as not using it.
```
void _fetchSession() async {
  try {
    AuthSession res = await Amplify.Auth.fetchAuthSession(
      options: CognitoSessionOptions(getAWSCredentials: true),
    );
    String identityId = (res as CognitoAuthSession).identityId!;
    print('identityId: $identityId');
  } on AuthException catch (e) {
    print(e.message);
  }
} 
```

I'm not looking for debugging, I just want to know how I can use the Amplify CLI, GraphQL Schema, maybe IAM permissions, to allow owner based CRUD and guest users to read only.

**Comment by HuiSF** [comment]
Hi @kcsarith have you taken a look at Amplify documents about auth rules with the GraphQL API? It provides example of typical use cases.

And this [specific example](https://docs.amplify.aws/cli/graphql/authorization-rules/#configure-multiple-authorization-rules) is what you were looking for? It uses the same rule as the example you mentioned to achieve public access for everyone.
