### ISSUE TITLE
I could subscribe by Amplify.API.subscribe, but no data received.

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-flutter#849]
**Describe the bug**
I can subscribe successfully by executing `Amplify.API.subscribe()`.
But I couldn't receive mutation data.

**To Reproduce**
```graphql
type Mutation {
  sendChatMessage(groupId: String!, message: String!): ChatMessage
}

type Subscription {
  onSendChatMessage(groupId: String!): ChatMessage @aws_subscribe(mutations : ["sendChatMessage"])
}


```
<img width="956" alt="スクリーンショット 2021-09-02 1 55 36" src="https://user-images.githubusercontent.com/22259776/131712315-675361b9-5c43-455f-8b0e-eb2742f28b89.png">

```
I/FLTFireBGExecutor( 6723): Creating background FlutterEngine instance, with args: [--enable-dart-profiling]
D/eglCodecCommon( 6723): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6723): eglCreateContext: 0xdc9d1f80: maj 3 min 0 rcv 3
D/eglCodecCommon( 6723): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6723): eglCreateContext: 0xdc9d1fe0: maj 3 min 0 rcv 3
D/HostConnection( 6723): HostConnection::get() New Host Connection established 0xc8691fd0, tid 7082
I/flutter ( 6723): ChatMessageController: OnSendChatMessage Subscribed
```

```dart
final groupId = 'group-001';
final variables = GOnSendChatMessageVarsBuilder()..groupId = groupId;
_onSendChatMessage = Amplify.API.subscribe<String?>(
        request: GraphQLRequest(
          document: gql.printNode(on_send_chat_message_ast.document),
          variables: variables.build().toJson(),
        ),
        onData: (response) {
          _logger(response.data);
          _logger(response.errors.toString());
        onEstablished: () {
          _logger('OnSendChatMessage Subscribed');
        },
        onError: (dynamic error) {
          _logger('OnSendChatMessage error -> $error');
        },
        onDone: () {
          _logger('OnSendChatMessage disposed');
        },
      );
    } on Exception catch (error) {
      _logger('fail to subscribe');
      _logger(error);
    }
```
**Expected behavior**
Receive data from subscription.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.5.1 20G80 darwin-x64, locale ***)
    • Flutter version 2.2.0 at /Users/***/fvm/versions/2.2.0
    • Framework revision b22742018b (4 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/**/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yukitaka13-1110** [comment]
I figured out mutation result must contains subscription arguments.
Is this a specification of AppSync?

**Comment by HuiSF** [comment]
Per my understanding, amplify-flutter uses AppSync API as the dependency of the API and DataStore categories, so yes everything will need to follow AppSync specifications.
