### ISSUE TITLE
Amplify Auth Cognito Sign In/Sign Up Issue

### ISSUE THREAD

**Issue by ManoVikram** [aws-amplify/amplify-flutter#859]
**Returning 'UserNotFoundException' instead of 'UserNotConfirmedException'**
Step 1: User creates an account
Step 2: Closes the app before confirming the account(closed the app before entering the confirmation code sent to EMail)
Step 3: Tries to log in later with Email and Password
Expected Error: UserNotConfirmedException
Actual Error: UserNotFoundException

Note: This error is not occurring when the user tries to log in(Step 3) with Username and Password

**To Reproduce**
I followed all the steps mentioned here: https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/#configure-auth-category
But for 'How do you want users to be able to sign in?', I chose Email.
And all other Flutter code is the same as here: https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/

**Platform**
I work with Andoird. So, I haven't tried this for iOS devices.

**Comment by Jordan-Nelson** [comment]
Hello @ManoVikram - Thanks for taking the time to open the issue.

I was unable to reproduce this with the steps above. Can you expand on your note about using username and password versus email and password? Did you use the CLI to switch to a username based sign in method to test this out with username/password? If you chose Email as the sign in method, the email effectively is the username for the purposes of sign in, so unless you switched to Username temporarily to try this out, I am unsure what this means.

Could you also add what version of amplify-flutter you are using?

**Comment by haverchuck** [comment]
@ManoVikram Can you please also post which version of the amplify CLI you are using (`$ amplify --version`)

**Comment by ManoVikram** [comment]
Ok. Let me brief it.

Step 1: Created a Flutter project

Step 2: Went to the terminal and ran 'amplify init'

Step 3: Added necessary packages to the Flutter app:
  amplify_auth_cognito: ^0.2.2
  amplify_flutter: ^0.2.2

Step 4: Then ran 'amplify add auth'

Step 5: I followed all the steps given here: https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/#prerequisites

Except that in documentation, they selected 'Username' for the question 'How do you want users to be able to sign in?' but I chose 'Email'. Basically, I want the users to sign in using 'Email' & 'Password' instead of 'Username' & 'Password'

? Do you want to use the default authentication and security configuration?
    `Default configuration`
? How do you want users to be able to sign in?
    `Email`
? Do you want to configure advanced settings?
    `No, I am done.`

Step 6: Followed all the steps to set up the Flutter code as per the documentation

Step 7: Created a new account using Email and Password

Step 8: AWS Amplify sent a confirmation code to that Email

Step 9: Without entering the code, I closed the app

Step 10: Tried to log in using the same account that I have created

From the above steps, it is expected to get an exception as I haven't confirmed the account by entering the confirmation code sent to that Email(as I mentioned in Step 9, I closed the app without entering the confirmation code).

So usually, the exception should be 'UserNotConfirmedException', but, I'm getting 'UserNotFoundException'. And to be specific, this happens only when I try to log in with Email and Password and not when Username and Password.

When I use Username and Password to log in, it is correctly showing UserNotConfirmedException. But, when I use Email and Password to log in, instead of showing UserNotConfirmedException, it is showing UserNotFoundException.

Note: I initialized amplify with Email. But, I am able to log in using both Email and Username.

Amplify Version: 5.4.0

**Comment by haverchuck** [comment]
@ManoVikram This is occurring because an '[alias](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-1)' (i.e. an email/phone_number/preferred_username) cannot be used in place of a username until the alias attribute been verified. An alternative would be use an [email/phone_number _instead_ ](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-1)of a username . I believe that in this case, you would get the `UserNotConfirmed` exception as expected.

**Comment by ManoVikram** [comment]
Now, I have to delete the user pool and create it again with the above-mentioned configurations, right?

**Comment by haverchuck** [comment]
@ManoVikram I believe so - Cognito has many immutable properties. If you downgrade Amplify CLI, you can use the CLI I believe.

**Comment by ManoVikram** [comment]
Awesome!! I tried the method you have mentioned above and it is working perfectly right now. Thanks!!
