### ISSUE TITLE
how to login by social account like google

### ISSUE THREAD

**Issue by jsw-davidhuang** [aws-amplify/amplify-flutter#863]
i had read the doc that it can be done by Social sign in with web UI, but i am looking for a way to just jump to a google page then input account&password, then turn back instead of using the aws cognito page. can anyone help?

**Comment by haverchuck** [comment]
@jsw-davidhuang Have you tried this?

```dart
    try {
       await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);
    } on AmplifyException catch (e) {
      /// handle error
    }
```

**Comment by jsw-davidhuang** [comment]
also i found an other issue which is that the signInWithWebUI and only be open by googe chrome in android phone. if chrome not exist it will crash.

**Comment by jsw-davidhuang** [comment]
> also i found an other issue which is that the signInWithWebUI and only be open by googe chrome in android phone. if chrome not exist it will crash.

how can i fix it, if my phone don't got chorme?

**Comment by dnys1** [comment]
@haverchuck It looks like this should be possible via the Android plugin (see discussion [here](https://github.com/aws-amplify/amplify-android/issues/678)). We should be able to add an option to `SignInWithWebUIRequest` to specify the browser package.

**Comment by jsw-davidhuang** [comment]
> @haverchuck It looks like this should be possible via the Android plugin (see discussion [here](https://github.com/aws-amplify/amplify-android/issues/678)). We should be able to add an option to `SignInWithWebUIRequest` to specify the browser package.

this issue reply an answer like this:
```
Amplify.Auth.signInWithWebUI(this,
        AWSCognitoAuthWebUISignInOptions.builder()
            .browserPackage("org.mozilla.firefox")
            .build(),
    { LOG.info("Sign in succeeded: ${it}") },
    { LOG.error("Sign in failed: ${it.message}", it) }
)

Amplify.Auth.signOut(
     AWSCognitoAuthSignOutOptions.builder()
         .browserPackage("org.mozilla.firefox")
         .build(),
    { LOG.info("Sign out succeeded.") },
    { LOG.error("Sign in failed: ${it.message}", it) }
)
```
but i think there are 2 question @dnys1 
1. is this future support in the flutter version.
2. what most develop want is that they can auto jump to the default browser the phone got(use intent： intent.setAction(Intent.ACTION_VIEW);
        intent.setData(Uri.parse(url));) instead of naming the browser. thanks for your reply.

**Comment by dnys1** [comment]
Hi @jsw-davidhuang, thank you for your insight. I believe this was main discussion point of the Android thread I posted, and for better or worse, I believe the given solution is where they landed. See [this comment](https://github.com/aws-amplify/amplify-android/issues/678#issuecomment-861032813) for a way to list the installed browsers.

Flutter does not currently support this feature, but if it did, it would be exactly as Android has it since we are built off the Android and iOS SDKs.

**Comment by jsw-davidhuang** [comment]
> Hi @jsw-davidhuang, thank you for your insight. I believe this was main discussion point of the Android thread I posted, and for better or worse, I believe the given solution is where they landed. See [this comment](https://github.com/aws-amplify/amplify-android/issues/678#issuecomment-861032813) for a way to list the installed browsers.
> 
> Flutter does not currently support this feature, but if it did, it would be exactly as Android has it since we are built off the Android and iOS SDKs.

ok, thanks for your reply
