### ISSUE TITLE
TemporalTimestamp problem with flutter Android (IOS works as expected)

### ISSUE THREAD

**Issue by mahanshiran** [aws-amplify/amplify-flutter#864]
Here is my schema.
```graphql
enum MessageType {
  TEXT
  IMAGE
  VIDEO
  STICKER
  GIFSTICKER
  LINK
  CUSTOM
}

type Message @model @auth(rules: [{allow: public}]) {
  id: ID!
  deviceName: String!
  senderId: String!
  colorIndex: Int
  recieverId: String
  gender: String!
  chatroom: String!
  senderName: String!
  body: String!
  battery: Int!
  creationDate: AWSTimestamp!
  messageType: MessageType!
}
 ```

in IOS everything works as expected but in android, i get this log. then everything only works locally and won't be synced to the cloud

<details>
I/amplify:aws-datastore( 7826): Orchestrator lock acquired.
I/amplify:aws-datastore( 7826): Orchestrator transitioning from LOCAL_ONLY to SYNC_VIA_API
I/amplify:aws-datastore( 7826): Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore( 7826): Starting API synchronization mode.
I/amplify:aws-datastore( 7826): Starting processing subscription events.
I/amplify:aws-datastore( 7826): Orchestrator lock released.
I/amplify:aws-datastore( 7826): Started subscription processor for models: [Message] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
W/amplify:aws-datastore( 7826): Failed to sync remote model into local storage: ModelWithMetadata{model=SerializedModel{id='964a9116-fcf7-45e5-b856-a6c2cb4618c7', serializedData={_deleted=null, gender=male, _lastChangedAt=1.631074108958E12, chatroom=English, colorIndex=4, battery=69, body=fdfsf, creationDate=1.631074107979E12, recieverId=-1, deviceName=sada, senderId=C4568BD1-E6DC-4D5E-BE32-B7AD1D9ABC6E, senderName=sada, messageType=TEXT, id=964a9116-fcf7-45e5-b856-a6c2cb4618c7, _version=1}, modelName=Message}, syncMetadata=ModelMetadata{id='964a9116-fcf7-45e5-b856-a6c2cb4618c7', _deleted=null, _version=1, _lastChangedAt=Temporal.Timestamp{timestamp=1631074108958}}}
W/amplify:aws-datastore( 7826): DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:362)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 7826): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore( 7826): Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:119)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:241)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.extractFieldValues(SQLiteCommandFactory.java:404)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.insertFor(SQLiteCommandFactory.java:318)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:738)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:345)
W/amplify:aws-datastore( 7826): 	... 6 more
W/amplify:aws-datastore( 7826): Initial cloud sync failed.
W/amplify:aws-datastore( 7826): DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:362)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 7826): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore( 7826): Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:119)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:241)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.extractFieldValues(SQLiteCommandFactory.java:404)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.insertFor(SQLiteCommandFactory.java:318)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:738)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:345)
W/amplify:aws-datastore( 7826): 	... 6 more
E/amplify:aws-datastore( 7826): Error encountered in the DataStore.
E/amplify:aws-datastore( 7826): DataStoreException{message=Initial cloud sync failed., cause=DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}, recoverySuggestion=Check your internet connection.}
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$createHydrationTask$7$SyncProcessor(SyncProcessor.java:163)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$SyncProcessor$CVdiyILaX0hVxQyCyWP-obOGU5A.accept(Unknown Source:4)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.innerError(FlowableConcatMapCompletable.java:166)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver$ConcatMapInnerObserver.onError(FlowableConcatMapCompletable.java:260)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableOnErrorComplete$OnError.onError(CompletableOnErrorComplete.java:66)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onError(MaybeFlatMapCompletable.java:97)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:91)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$wibDnzZq5mJOXI5qd8Wh_zsWeGQ.accept(Unknown Source:4)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:366)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:aws-datastore( 7826): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:aws-datastore( 7826): Caused by: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:362)
E/amplify:aws-datastore( 7826): 	... 6 more
E/amplify:aws-datastore( 7826): Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:119)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:241)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.extractFieldValues(SQLiteCommandFactory.java:404)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.insertFor(SQLiteCommandFactory.java:318)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:738)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:345)
E/amplify:aws-datastore( 7826): 	... 6 more
E/amplify:aws-datastore( 7826): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore( 7826): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
E/amplify:aws-datastore( 7826): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
E/amplify:aws-datastore( 7826): match your scenario, and file an issue with the details of the bug if there isn't.}
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:323)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$PVk58tU0K8ndPJYnH_tRmf4RGwE.subscribe(Unknown Source:2)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:aws-datastore( 7826): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:aws-datastore( 7826): Caused by: java.lang.RuntimeException: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
E/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:316)
E/amplify:aws-datastore( 7826): 	... 18 more
E/amplify:aws-datastore( 7826): Caused by: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:362)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:aws-datastore( 7826): 	... 3 more
E/amplify:aws-datastore( 7826): Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:119)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:241)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.extractFieldValues(SQLiteCommandFactory.java:404)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.insertFor(SQLiteCommandFactory.java:318)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:738)
E/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:345)
E/amplify:aws-datastore( 7826): 	... 6 more
W/amplify:aws-datastore( 7826): API sync failed - transitioning to LOCAL_ONLY.
W/amplify:aws-datastore( 7826): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
W/amplify:aws-datastore( 7826): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
W/amplify:aws-datastore( 7826): match your scenario, and file an issue with the details of the bug if there isn't.}
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:323)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$PVk58tU0K8ndPJYnH_tRmf4RGwE.subscribe(Unknown Source:2)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 7826): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore( 7826): Caused by: java.lang.RuntimeException: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
W/amplify:aws-datastore( 7826): 	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:316)
W/amplify:aws-datastore( 7826): 	... 18 more
W/amplify:aws-datastore( 7826): Caused by: DataStoreException{message=Error in saving the model: Message[id=964a9116-fcf7-45e5-b856-a6c2cb4618c7], cause=java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:362)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/amplify:aws-datastore( 7826): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore( 7826): 	... 3 more
W/amplify:aws-datastore( 7826): Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:119)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:241)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.extractFieldValues(SQLiteCommandFactory.java:404)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.insertFor(SQLiteCommandFactory.java:318)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:738)
W/amplify:aws-datastore( 7826): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:345)
W/amplify:aws-datastore( 7826): 	... 6 more
I/amplify:aws-datastore( 7826): Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
I/amplify:aws-datastore( 7826): Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore( 7826): Stopping subscription processor.
I/amplify:aws-datastore( 7826): Stopped subscription processor.

</details>

**Comment by HuiSF** [comment]
Hello @mahanshiran thanks for reporting this issue.

From the logs you provided, I noticed the value of the `creationDate` may be incorrect:

```
creationDate=1.631074107979E12
```

The value of a `TemporalTimestamp` field should be stored as an integer. In the issue you encounter, it seems the value is stored as a double/float number. Could you please check how's the data stored in your DynamoDB from the DynamoDB console?

**Comment by mahanshiran** [comment]
oh, you are right thank you very much
