### ISSUE TITLE
Wait for Sync before query.

### ISSUE THREAD

**Issue by tr-asimpson** [aws-amplify/amplify-flutter#865]
Hi ,

I have a request similar to https://github.com/aws-amplify/amplify-js/issues/5077 which was resolved with PR https://github.com/aws-amplify/amplify-js/pull/5942

I need to know when a sync has taken place as an initial query returns empty and then a sync occurs and the data is received as it should be.

The use case is i always want to clear local data on start and sync to cloud as the cloud data can be changed by other means and local storage is often out of date.

Thanks!

**Comment by Afunyah** [comment]
Hello,

I just came across a similar problem and wanted to share how I went about it.

```
  static void pullCloudAndExecute(Function toExec) async {
    await Amplify.DataStore.query(GenericUser.classType).then((value) {
      print("Performed Dummy Query");
    });

    StreamSubscription dsHub =
        Amplify.Hub.listen([HubChannel.DataStore], (hubEvent) {
      print("HubEvent is ${hubEvent.eventName}");
    });

    dsHub.onData((data) async {
      print(data.eventName);
      if (data.eventName == 'ready') {
        print("DataStore READY (custom)");
        toExec();
        await dsHub.cancel();
      }
    });
  }
```
I placed this in my 'global' singleton class, I can now pull from the cloud if I need to.

The ready event occurs when data from the cloud has been pulled and is ready. 
[https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#ready]

A given function can be executed when the data sync is completed.

Similar issue:
Sync to cloud not working #279 

I'm just a beginner testing some code so this solution is probably not professional.
It could probably be improved, and there is probably a better way somewhere out there.

Let me know if it helps, thanks.

**Comment by HuiSF** [comment]
Currently amplify-flutter emits a hub event once syncing is completed. Here's [an example](https://github.com/aws-amplify/amplify-flutter/blob/32822f071e5df2604c762fa83db5f73cb46c65f1/packages/amplify_datastore/example/lib/main.dart#L153-L158) of how to use the event.

For online/offline detection you may need some other 3rd-party packages, e.g. [connectivity_plus](https://pub.dev/packages/connectivity_plus). 

In addition, the new DataStore APIs [`start`](https://github.com/aws-amplify/amplify-flutter/blob/32822f071e5df2604c762fa83db5f73cb46c65f1/packages/amplify_flutter/lib/categories/amplify_datastore_category.dart#L119) and [`stop`](https://github.com/aws-amplify/amplify-flutter/blob/32822f071e5df2604c762fa83db5f73cb46c65f1/packages/amplify_flutter/lib/categories/amplify_datastore_category.dart#L128) will be released soon, which you can leverage to start or stop API syncing according to connectivity conditions.
