### ISSUE TITLE
Cocoapod dependencies error 0.2.3

### ISSUE THREAD

**Issue by odemkovych** [aws-amplify/amplify-flutter#873]
With 0.2.3 version ios build is broken. The amplify_api cocoapod file contains next line:

> load '../../../build-support/dependencies.rb'

which causes error:

> Analyzing dependencies
> [!] Failed to load 'amplify_api' podspec: 
> [!] Invalid `amplify_api.podspec` file: cannot load such file -- ../../../build-support/dependencies.rb.

https://github.com/aws-amplify/amplify-flutter/blob/2384f9f60c19cb93cf102c4eaa32b3d462f5e1fc/packages/amplify_api/ios/amplify_api.podspec#L1

**Comment by haverchuck** [comment]
@odemkovych Was this a release build?

**Comment by haverchuck** [comment]
We are working on a fix for this now.

**Comment by haverchuck** [comment]
@odemkovych This should be resolved with version 0.2.4.

**Comment by eyeled-mh** [comment]
I've got the same problem.

**Comment by offlineprogrammer** [comment]
@eyeled-mh are you using the version 0.2.4?

**Comment by eyeled-mh** [comment]
@offlineprogrammer Not yet. I went back to 0.2.2 ; that worked for me. I'll try the new version soon

**Comment by dnys1** [comment]
Closing for now, but feel free to reopen if the issue persists.
