### ISSUE TITLE
Is there any way to create variable import in custom resolvers? 

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#877]
**Describe the question**
We can write custom resolvers inside `amplify/backend/api/<project>/resolvers/`, but inside custom resolvers, suppose we need a table(model) name then we need to hardcode that value in the template. 
So I want to know is there any way to write an export file inside `/resolvers` dir, and write all the variables in it similar to `.env` file and import these variables in the custom vtl template files. 

For eg. in a custom resolver (BatchPutItem), I need table names, and I am hardcoding all the table name 
```
{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
        "User-axgsatgg-staging": $utils.toJson($usersdata),
        "Quote-axgsatgg-staging": $utils.toJson($quoteData),
        "Universe-axgsatgg-staging": $utils.toJson($universeData),
    }
}
```
and in response template: 
```

#if ($ctx.error)
    $util.toJson($ctx.error)
#end

$util.toJson($ctx.result.data.User-axgsatgg-staging)

```
And in other resolvers too, I am hardcoding the same values, so I want to know is there any way to create a file like `.env`: 

**.env file**
```
USER_TABLE: User-axgsatgg-staging
QUOTE_TABLE: Quote-axgsatgg-staging
UNIVERSE_TABLE: Universe-axgsatgg-staging
```

and use it like this: 

**req template**
```
{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
        "User_TABLE": $utils.toJson($usersdata),
        "QUOTE_TABLE": $utils.toJson($quoteData),
        "UNIVERSE_TABLE": $utils.toJson($universeData),
    }
}
```

**res template**

```

#if ($ctx.error)
    $util.toJson($ctx.error)
#end

$util.toJson($ctx.result.data.User_TABLE)

```

Thanks.

**Comment by dnys1** [comment]
Hi @hackrx, please see the discussion [here](https://github.com/aws-amplify/amplify-cli/issues/1774). Currently, there is no out-of-the-box support for this functionality.
