### ISSUE TITLE
Missing type for hubEvent

### ISSUE THREAD

**Issue by omartinma** [aws-amplify/amplify-flutter#879]
**Describe the bug**
Currently, while listening to changes to Amplify.hub one of the parameters is dynamic, causing issues with the analyzer.

![image](https://user-images.githubusercontent.com/11978998/133130504-d577070b-a221-4a59-ab46-8706454c29fe.png)

![image](https://user-images.githubusercontent.com/11978998/133130716-a8e56689-e048-470d-8a33-6e9c688b4b7f.png)

This can be a workaround just ignore the lint rule by adding // ignore: avoid_dynamic_calls but it would be nice to avoid doing so. Also will give more clarity while using the hubEvent object.

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1323 darwin-x64, locale es-ES)
    • Flutter version 2.5.0 at /Users/oscarmartin/SDKS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/oscarmartin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
</details>

**Comment by HuiSF** [comment]
Currently the hub event listener [expects a dynamic parameter](https://github.com/aws-amplify/amplify-flutter/blob/4c8d7bea2a60c456f93b768eb7d01671811cc701/packages/amplify_flutter/lib/amplify_hub.dart#L22). 

In lieu of using warning suppression, you may try to cast the type of `hubEvent`, e.g.
```dart
final hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) {
  if (msg is DataStoreHubEvent) {
    // here the eventName type will be inferred as `DataStoreHubEvent.eventName`
    if (msg.eventName == 'ready') { 
      // do things
    }
  }
  print(msg);
});
```
Possible event types are defined [here](https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore/lib/types/DataStoreHubEvents).

**Comment by omartinma** [comment]
> Currently the hub event listener [expects a dynamic parameter](https://github.com/aws-amplify/amplify-flutter/blob/4c8d7bea2a60c456f93b768eb7d01671811cc701/packages/amplify_flutter/lib/amplify_hub.dart#L22).
> 
> In lieu of using warning suppression, you may try to cast the type of `hubEvent`, e.g.
> 
> ```dart
> final hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) {
>   if (msg is DataStoreHubEvent) {
>     // here the eventName type will be inferred as `DataStoreHubEvent.eventName`
>     if (msg.eventName == 'ready') { 
>       // do things
>     }
>   }
>   print(msg);
> });
> ```
> 
> Possible event types are defined [here](https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore/lib/types/DataStoreHubEvents).

Thanks for answering that. Maybe that could be added as documentation on listen method? Maybe you have it somewhere in the docs, but I think would be much easier for devs to document that in the code. What do you think?
Right now just seeing the listen method i dont have a quick way to know all the different events
![image](https://user-images.githubusercontent.com/11978998/133304936-71599b60-035b-47e9-bcf9-d0cb01fe4556.png)

But even adding this to docs, why is not possible to change the listener definition?

**Comment by HuiSF** [comment]
Agreed, this could use some improvements.

**Comment by HuiSF** [comment]
Thanks for the feedback and suggestions @omartinma ! PRs are always welcome, if you'd like to contribute 😊

**Comment by omartinma** [comment]
> Thanks for the feedback and suggestions @omartinma ! PRs are always welcome, if you'd like to contribute 😊

Happy to help here. I'm doing some experiments these couple of weeks with Amplify, i will gather my feedback and create a PR to discuss about that. Should we keep this issue open and whenever I create the PR I will link both?

**Comment by HuiSF** [comment]
Sure thing @omartinma  thanks for your help!

**Comment by anhNEON** [comment]
I came across this issue as well but the type AuthHubEvent is not available. 
I think an export is missing on this file packages/amplify_auth_cognito/lib/src/types.dart

<img width="644" alt="Bildschirmfoto 2021-11-15 um 12 14 13" src="https://user-images.githubusercontent.com/93521009/141774079-fce29374-b52e-46cd-9de0-d2e61ee2f271.png">

**Comment by HuiSF** [comment]
> I came across this issue as well but the type AuthHubEvent is not available. I think an export is missing on this file packages/amplify_auth_cognito/lib/src/types.dart
> 
> <img alt="Bildschirmfoto 2021-11-15 um 12 14 13" width="644" src="https://user-images.githubusercontent.com/93521009/141774079-fce29374-b52e-46cd-9de0-d2e61ee2f271.png">

I think there is a work around, is that you can check `event.eventName`. Here's an example:

https://github.com/aws-amplify/amplify-flutter/blob/3642cf0f267922b4c2da38813c56a6da47d73377/packages/amplify_auth_cognito/example/lib/main.dart#L89-L116

**Comment by two4zero** [comment]
@anhNEON +1

**Comment by Jordan-Nelson** [comment]
Hi everyone - It looks like a type `HubEvent` was added a while back. `DataStoreHubEvent` and `AuthHubEvent` extend `HubEvent`. If you simply want to check the event name, you should not need to check that the event is `DataStoreHubEvent`/`AuthHubEvent` anymore. See below for two example of how to use these types.


```dart
Amplify.Hub.listen([HubChannel.Auth], (event) {
  if (event.eventName == 'SIGNED_IN') {
    // do something
  }
});

Amplify.Hub.listen([HubChannel.Auth, HubChannel.DataStore], (event) {
  if (event is DataStoreHubEvent) {
    // do something
  } else if (event is AuthHubEvent) {
    // do something
  }
});
```

I think this resolves the original request. Please let me know if anything is unclear or if you believe this doesn't satisfy the original feature request. Otherwise I will close this out.
