### ISSUE TITLE
Module 'amplify_auth_cognito' not found

### ISSUE THREAD

**Issue by Surya-thangavel** [aws-amplify/amplify-flutter#881]
### **Error  : "Parse Issue Module 'amplify_auth_cognito' not found"**

**Flutter doctor Output**

`[✓] Flutter (Channel stable, 2.0.6, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/srinivashvk/flutter
    • Framework revision 1d9032c7e1 (5 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/srinivashvk/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • A490CC7A-78F1-4A2F-9325-4E1047F49EB0 • ios  • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!`

![Screenshot 2021-09-14 at 9 44 14 PM](https://user-images.githubusercontent.com/85167156/133295684-80378ea4-03bc-4bd6-89f3-520f8d4b1930.png)

**Flutter build ios full log** 
[log (1).txt](https://github.com/aws-amplify/amplify-flutter/files/7163578/log.1.txt)

**Comment by dnys1** [comment]
Hi @Surya-thangavel can you please verify the deployment target of your app? This is a known issue when targeting older versions of iOS. Amplify requires this value to be iOS 11.0 or later (13.0 or later when using DataStore).

<img width="932" alt="Screen Shot 2021-09-14 at 9 54 58 AM" src="https://user-images.githubusercontent.com/24740863/133300998-70716877-5ff0-41d3-9eb6-b9b0ef0de98a.png">

**Comment by Surya-thangavel** [comment]
@dnys1  The targeting version is iOS 11.0 as I am not using DataStore.

**Comment by fjnoyp** [comment]
Hi @Surya-thangavel can you provide the logs file again as I cannot open it.

**Comment by jsw-davidhuang** [comment]
i think not only the main target version need to over ios11, but all other target in the xcodewordspace need to over ios11

**Comment by benedict1986** [comment]
Hi @jsw-davidhuang , can you please elaborate a bit more? I am also having the same problem and all of my Deployment Targets are 13.0. Thank you.

**Comment by Surya-thangavel** [comment]
@fjnoyp  Here's the log file
[flutter build ios log.txt](https://github.com/aws-amplify/amplify-flutter/files/7178661/flutter.build.ios.log.txt)

**Comment by Surya-thangavel** [comment]
@benedict1986 The app running on simulator and build succeed with amplify but only when archiving the app this error occurs, Is yours the same issue ?

**Comment by jsw-davidhuang** [comment]
> Hi @jsw-davidhuang , can you please elaborate a bit more? I am also having the same problem and all of my Deployment Targets are 13.0. Thank you.

i think is something like this, this pod all need to be over ios 11
![微信截图_20210917102228](https://user-images.githubusercontent.com/88757436/133714117-341594ea-c116-4407-85c4-d425126c9611.png)

**Comment by fjnoyp** [comment]
Hi @Surya-thangavel are you sure you are targeting 13.0?  In the logs file provided I see the following messages at the end: 

`warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'FMDB' from project 'Pods')`

**Comment by fjnoyp** [comment]
Thanks @jsw-davidhuang  for your help clarifying how to set the main target version. 

@Surya-thangavel @benedict1986 does following his advice help resolve your problem?

**Comment by fjnoyp** [comment]
Hi @Surya-thangavel I've been trying to reproduce your error but I am able to archive the amplify_auth_cognito example app no problem.  Here is my setup: 

Xcode 12.2

My Runner and Pods -> General tab -> Deployment Info are all set to iOS 11.0 as shown in the picture attached. 

In the logs you sent me, it appears you are still set to 8.0.  I'm not able to target that version.  What version of Xcode are you using?

<img width="662" alt="Untitled" src="https://user-images.githubusercontent.com/11478656/133848701-595b91b7-bb5b-442f-bcd1-d584b835e4a9.png">

**Comment by jsw-davidhuang** [comment]
by the way, if still can not set to ios11, you should directly edit the .spec file in the pods folder, it is something like .symxxxx/packagename.podspec

**Comment by benedict1986** [comment]
> @benedict1986 The app running on simulator and build succeed with amplify but only when archiving the app this error occurs, Is yours the same issue ?

Hi @Surya-thangavel , yes, I can run my app in simulator but when I run it with my iPhone, I got this error.

**Comment by benedict1986** [comment]
> > Hi @jsw-davidhuang , can you please elaborate a bit more? I am also having the same problem and all of my Deployment Targets are 13.0. Thank you.
> 
> i think is something like this, this pod all need to be over ios 11
> ![微信截图_20210917102228](https://user-images.githubusercontent.com/88757436/133714117-341594ea-c116-4407-85c4-d425126c9611.png)

Hi @jsw-davidhuang , I think I don't have this Pods project
<img width="389" alt="Screen Shot 2021-09-18 at 11 10 35 pm" src="https://user-images.githubusercontent.com/7417859/133890022-cf4dc8c7-35c3-43d1-861e-a601893a0fe5.png">

**Comment by fjnoyp** [comment]
@benedict1986 did you open the Runner.xcworkspace project?  Your error message mentions that you should open that project.  I think you might have opened the Runner.xcodeproj on accident instead.

**Comment by benedict1986** [comment]
> @benedict1986 did you open the Runner.xcworkspace project? Your error message mentions that you should open that project. I think you might have opened the Runner.xcodeproj on accident instead.

Hi @fjnoyp , after investigating a bit, I found the issue when I run `flutter run` is that I did not build in release mode. I added --release to the command and eventually got the following error, which was the same as what I got from Xcode.

<img width="991" alt="Screen Shot 2021-09-21 at 12 02 58 am" src="https://user-images.githubusercontent.com/7417859/134015971-68032d9c-cc6d-49b1-9c16-09e4956178db.png">

**Comment by benedict1986** [comment]
Hi @fjnoyp , I finally get my log as well but could not find any message similar as the one you pointed out for @Surya-thangavel.

[Build target Runner_2021-09-21T00-48-54.txt](https://github.com/aws-amplify/amplify-flutter/files/7196567/Build.target.Runner_2021-09-21T00-48-54.txt)

This is something about IPHONEOS_DEPLOYMENT_TARGET

<img width="581" alt="Screen Shot 2021-09-21 at 12 57 14 am" src="https://user-images.githubusercontent.com/7417859/134024490-9ce6ddba-99be-45df-ab1b-4b08ffc797f2.png">

**Comment by dnys1** [comment]
The following steps allow me to create a release archive. If someone can create a minimum set of steps to reproduce this issue, I will reopen. Otherwise, I believe this is resolved.

1. Create a Flutter project and initialize Amplify with Auth category.
2. Add `amplify_flutter` and `amplify_auth_cognito` as dependencies.
3. Update `Podfile` to have `platform :ios, '11.0'`.
4. Run `pod install` inside `ios` directory to generate `Runner.xcworkspace`.
4. Open `ios/Runner.xcworkspace` and change deployment target to iOS 11.
3. Run `flutter build ios` to create a release build.
4. Open `ios/Runner.xcworkspace` and run `Product > Archive`.

**Comment by benedict1986** [comment]
Hi @dnys1 , thank you for your step. My case is slightly different from what yours. I already have Cognito setup in AWS and do not want to initialise Amplify with Auth category. Here is the minimum steps I am using to recreate the issue. Can you please let me know if there is any step is missing or anything wrong with it. I am happy to share myapp4 if you need it. Thank you.

1. flutter create myapp4
<img width="720" alt="Screen Shot 2021-09-22 at 1 04 51 am" src="https://user-images.githubusercontent.com/7417859/134196436-c77514d4-dfc2-4679-a0e3-f698cbf9cd19.png">

2. add amplify_auth_cognito: ^0.2.4 to pubspec.yaml
<img width="518" alt="Screen Shot 2021-09-22 at 1 06 17 am" src="https://user-images.githubusercontent.com/7417859/134196647-215c42f2-33dd-4362-925c-fdb4c5054988.png">

3. run flutter pub get
<img width="526" alt="Screen Shot 2021-09-22 at 1 07 39 am" src="https://user-images.githubusercontent.com/7417859/134196881-7f836ef1-880d-4da5-9412-9c0559e4b775.png">

4. double click Runner.xcworkspace in ios folder and open the project in Xcode
<img width="1399" alt="Screen Shot 2021-09-22 at 1 08 29 am" src="https://user-images.githubusercontent.com/7417859/134196969-5f9f8009-59a1-4366-941f-fe5415300c69.png">

5. update iOS Deployment Target to 11.0

<img width="1137" alt="Screen Shot 2021-09-22 at 1 09 26 am" src="https://user-images.githubusercontent.com/7417859/134197250-b09a2f15-8865-4ccc-a435-989abc080cd2.png">

6. Hook up IPHONE
7. use personal team to sign the app, I changed the bundle identifier to com.example.myapp4-1024
<img width="1137" alt="Screen Shot 2021-09-22 at 1 11 04 am" src="https://user-images.githubusercontent.com/7417859/134197585-f5e70c1e-2c17-4aab-8f89-78ee3fe6d7d5.png">

8. make sure Runner > iPhone is selected
<img width="1135" alt="Screen Shot 2021-09-22 at 1 12 19 am" src="https://user-images.githubusercontent.com/7417859/134197741-e807df6f-bc1b-4167-94b8-1c8f52ad9cae.png">

8. click the arrow to run the app

<img width="1139" alt="Screen Shot 2021-09-22 at 1 13 42 am" src="https://user-images.githubusercontent.com/7417859/134198045-ca2e0396-67ad-48ac-94ad-b1a73e2b9622.png">

9. run flutter build iOS

<img width="800" alt="Screen Shot 2021-09-22 at 1 16 39 am" src="https://user-images.githubusercontent.com/7417859/134198676-e93e78dc-022a-47cb-8823-a602df38d5d1.png">

10. Open Xcode -> Product. -> Archive
<img width="1136" alt="Screen Shot 2021-09-22 at 1 18 52 am" src="https://user-images.githubusercontent.com/7417859/134198853-be26a2c0-6b24-44d0-a3c2-d8eff29d71de.png">

**Comment by dnys1** [comment]
Hi @benedict1986, you are missing a couple steps. Please follow steps 3-4 from my post and try again.

**Comment by jsw-davidhuang** [comment]
Hi @benedict1986 i think when you build you got to better do like this: 
```
1. flutter clean 
2. flutter build ios 
3. 3.open the xworkspace in the ios folder then build . 
4. but all this require the 0 step which is : you need to amplify init the project and input the keys you apply on aws cognito.
```

**Comment by benedict1986** [comment]
Hi @dnys1 and @jsw-davidhuang , thank you for you advice.

According to @dnys1 , I ran pod init, update Podfile and pod install as follow
<img width="1437" alt="Screen Shot 2021-09-24 at 2 06 38 am" src="https://user-images.githubusercontent.com/7417859/134544037-751bba96-c7b7-414f-a9bd-2de7126e52e4.png">
<img width="476" alt="Screen Shot 2021-09-24 at 2 10 32 am" src="https://user-images.githubusercontent.com/7417859/134544160-7812f232-176b-49ef-a3c6-9eacdd7732bb.png">

Unfortunately, the error is still there. I trust your approach works. It means the only thing I did not try was to run amplify init with Auth category.

The reason I reluctant to run `amplify init` is because it provisions the backend in aws. It creates a new IAM user and something else. I don't know what exactly it's created so I want to use the existing aws profile (client id and client secret) instead of using amplify init to create another one.

Not sure if @Surya-thangavel  has solved the problem or not. 

Thanks for all of your help. Let me try to understand more about the library.

**Comment by dnys1** [comment]
@benedict1986 Can you verify you are opening `Runner.xcworkspace` and not `Runner.xcodeproj`. The image above showed the latter. 

Running `amplify init` is not technically required for building a release archive, so I don't believe that's the problem.

**Comment by benedict1986** [comment]
Hi @dnys1, thank you for your advice. in the previous post with lots of images. I did not init and install pod. As a result there is no Pods project when I open `Runner.xcworkspace`. Now I init and install pod, I can see the Pods project when I open `Runner.xcworkspace` as follow

<img width="800" alt="Screen Shot 2021-09-24 at 5 47 51 pm" src="https://user-images.githubusercontent.com/7417859/134638016-31bcc61e-d86f-4c79-955a-ca296b929573.png">

In order to make sure I did not open a wrong file. I renamed the original `Runner.xcworkspace` to `Runner2.xcworkspace` and another `Runner.xcworkspace` is generated when I run `pod install`. And I pretty sure I opened the newly generated `Runner.xcworkspace` and then I see the Xcode as the image above.

<img width="786" alt="Screen Shot 2021-09-24 at 5 49 45 pm" src="https://user-images.githubusercontent.com/7417859/134638277-b381d229-1dec-4a1d-b410-af6ffd4c3725.png">

Unfortunately, even doing that, I still get the same error about amplify_auth_cognito module not found.

**Comment by benedict1986** [comment]
Ok, finally, it's working...I summary the steps as follow:

1. Run `flutter create myapp`
2. Open `pubspec.yaml` and add `amplify_auth_cognito: ^0.2.4`
3. Run `flutter pub get`. This step is what I am missing. After running this step, I saw the Podfile. Previously I did not run this step and create the Podfile with `pod init`, which is not right
4. Update `Podfile` and uncomment `platform :ios, '9.0'` and update it to `platform :ios, '11.0'`
5. Run `pod install`
6. Open the newly generated `Runner.xcworkspace`
7. Update the iOS Deployment target to 11.0. Refer to https://github.com/aws-amplify/amplify-flutter/issues/881#issuecomment-922274561
8. Run `flutter build ios` to create a release build. I have a automatic signing issue in this step but I think it should be easy to resolve.
9. I end up with running the app in Xcode and it can be build and successfully.


Massive thank to @fjnoyp and @dnys1

**Comment by dnys1** [comment]
Thank you for the update @benedict1986. I'm glad you were able to get it resolved 👍

**Comment by richard457** [comment]
This is happening to me on macos flutter 3.24 and latest amplify_auth_cognito

**Comment by Crusade1337** [comment]
Im facing the same issue with flutter 3.2.24 and the following versions:
`  amplify_flutter: ^2.4.1
  amplify_auth_cognito: ^2.4.1
  amplify_authenticator: ^2.1.3`
Parse Issue (Xcode): Module 'amplify_auth_cognito' not found

When i run it via xCode it seems to work, but via the CLI or VsCode the package is not found.

`flutter doctor                  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!`

**Comment by richanshah** [comment]
> macos

same here, any update on this?

**Comment by richanshah** [comment]
> This is happening to me on macos flutter 3.24 and latest amplify_auth_cognito

any update?
