### ISSUE TITLE
amplify-flutter upload to s3 fails on both iOS and android

### ISSUE THREAD

**Issue by shravyamachanna** [aws-amplify/amplify-flutter#90]
I used the below s3 upload code to try uploading the file to our **public** bucket but I get an exception on iOS and android.

```
try {
      print('In upload');
      // Uploading the file with options
      File local = await FilePicker.getFile(type: FileType.image);
      final key = new DateTime.now().toString();
      Map<String, String> metadata = <String, String>{};
      metadata['name'] = 'filename';
      metadata['desc'] = 'A test file';
      S3UploadFileOptions options = S3UploadFileOptions(
          accessLevel: StorageAccessLevel.private, metadata: metadata);
      UploadFileResult result = await Amplify.Storage.uploadFile(
          key: key, local: local, options: options);
      setState(() {
        _uploadFileResult = result.key;
      });
    } catch (e) {
      print('UploadFile Err: ' + e.toString());
    }
```
Exception on Android :

```
I/flutter (17626): UploadFile Err: PlatformException(AmplifyException, UPLOAD_FILE_OPERATION_FAILED, {PLATFORM_EXCEPTIONS: {platform: Android, localizedErrorMessage: Something went wrong with your AWS S3 Storage upload file operation, recoverySuggestion: See attached exception for more information and suggestions}})
E/amplify:flutter:storage_s3(17626): UPLOAD_FILE_OPERATION_FAILED
E/amplify:flutter:storage_s3(17626): AmplifyException {message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
E/amplify:flutter:storage_s3(17626): 	at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onStateChanged(AWSS3StorageUploadFileOperation.java:182)
E/amplify:flutter:storage_s3(17626): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
E/amplify:flutter:storage_s3(17626): 	at android.os.Handler.handleCallback(Handler.java:883)
E/amplify:flutter:storage_s3(17626): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/amplify:flutter:storage_s3(17626): 	at android.os.Looper.loop(Looper.java:214)
E/amplify:flutter:storage_s3(17626): 	at android.app.ActivityThread.main(ActivityThread.java:7116)
E/amplify:flutter:storage_s3(17626): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:storage_s3(17626): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/amplify:flutter:storage_s3(17626): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```
Exception on iOS : 
```
flutter: In upload
flutter: UploadFile Err: PlatformException(AmplifyException, UPLOAD_FILE_OPERATION_FAILED, {PLATFORM_EXCEPTIONS: {recoverySuggestion: TODO some status code to recovery message mapper.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes, platform: iOS, localalizedError: The HTTP response status code is [403].}})
```
I also get the below error sometimes
```
UploadFile Err: PlatformException(AmplifyException, UPLOAD_FILE_OPERATION_FAILED, {PLATFORM_EXCEPTIONS: {localalizedError: Access denied!, platform: iOS, recoverySuggestion: }})
```
 This issue is reproducible in :
 Android
 iOS

**Comment by Ashish-Nanda** [comment]
@shravyamachanna 

Did you set up your backend with the CLI? Have you enabled access for guest users?
If not you may need to log in before uploading.

**Comment by shravyamachanna** [comment]
@Ashish-Nanda 

I used existing AWS resources. I haven't used CLI to set it up.  

Our use case is to make authenticated users upload to a bucket with their identityId.. as it isn't working either. I have tried the Cognito auth user who is logged In to upload image to the public bucket. 

amplifyconfiguration.dart :
```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "********",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "*******",
                        "AppClientId": "******",
                        "AppClientSecret": "*****",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "****",
                        "Region": "us-west-2"
                    }
                }
            }
        }
    },
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "******",
                    "region": "us-east-1"
                },
                "pinpointTargeting": {
                    "region": "us-east-1"
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "******",
                "region": "us-west-2"
            }
        }
    }
}''';
```

**Comment by Ashish-Nanda** [comment]
@shravyamachanna, the terminology `public` can be confusing sometimes. I suspect you have a `public` folder in the bucket but the bucket is not truly `public` allowing anyone to upload/read from it as that would not be a good practice from a security standpoint, and we recommend you scope down the permissions.

Since you have set up your Cognito resources manually and not using the CLI, looking at the authorization related errors, I think it could be that you are missing the IAM roles and permissions necessary for users to Put/Get/List/Delete objects in the bucket.

I suggest you take a look at our docs [here](https://docs.amplify.aws/lib/storage/getting-started/q/platform/js#manual-setup-import-storage-bucket) to get an idea about the roles and policies you would need to create. 

Hopefully this will address your issue!

**Comment by shravyamachanna** [comment]
@Ashish-Nanda 

Previously I used to upload using the same credentials on iOS and Android and it used to work fine(IAM roles are exactly the same now). I used to use flutter platform channel to call AWS SDK for iOS and Android. Now I'm migrating to flutter Amplify. 

Bucket properties haven't changed as it is still working fine when I upload it using iOS or Android AWS SDK.

As far as the public goes ...I created a temporary bucket to test ...We won't use that bucket as its not a best practice.

Please help me resolve the issue.

**Comment by fjnoyp** [comment]
Hi @shravyamachanna thanks for providing those extra details.  

Strange how native iOS and Android was working for you before.  Can you provide the Android storage upload code you used?  Also, can you provide the amplifyConfiguration file for Android native, perhaps we can compare the differences between that and the one used in your flutter project.

**Comment by shravyamachanna** [comment]
Hi @fjnoyp,

Thank you for looking into the issue. Below are the awsconfiguration.json and android code which we are using with flutter platform channels.  

awsconfiguration.json
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "******",
                "Region": "us-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "********",
            "AppClientId": "********",
            "AppClientSecret": "********",
            "Region": "us-west-2"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Region": "us-west-2"
        }
    }
} 
```
Android storage upload code 

```
                  filePath = call.argument("filePath");
                  key = call.argument("key");

                  String idId = AWSMobileClient.getInstance().getIdentityId() + "/" +key;

                  File file = new File(filePath);

                  new AwsHelper(MainActivity.this, new AwsHelper.OnUploadCompleteListener() {
                    @Override
                    public void onUploadComplete() {
                      runOnUiThread(() -> {
                        Map<String, Object> hMap = new HashMap<>();
                        hMap.put(STATUS, true);
                        hMap.put(TAG, "Upload Successful");
                        hMap.put(MESSAGE, idId);
                        result.success(hMap);
                      });
                    }

                    @Override
                    public void onFailed() {
                      runOnUiThread(() -> {
                        result.error("Upload Error", "Failed to upload", null);
                      });
                    }
                  }, idId).uploadImage(file);

```

**Comment by fjnoyp** [comment]
Hi @shravyamachanna 

I thought you were using Amplify Android Storage (https://docs.amplify.aws/lib/storage/upload/q/platform/android) via the method channel before.  I'm not too sure what AWSHelper is.

I've been looking through your dart code and it looks correct - it appears you are using the code in the sample app which should be working either way.  

Based on the information you've provided it's looking like your backend resources are not configured correctly as your dart code seems correct.  In this case I would recommend following the advice that Ashish provided before: https://docs.amplify.aws/lib/storage/getting-started/q/platform/js#manual-setup-import-storage-bucket

Using the Amplify CLI is the best way to automatically get this all set up without having to worry about configuring these things manually.

**Comment by shravyamachanna** [comment]
Thanks, @Ashish-Nanda, and @fjnoyp. I figured it out our bucket policy doesn't have a prefix(public/protected/private) previously. I added them and it worked.

**Comment by Ashish-Nanda** [comment]
Thats great @shravyamachanna!

The error messages implied there was something missing in the policies configured manually as compared to how the Amplify CLI sets them up. Glad that you were able to figure it out!

Will go ahead and close out the issue now that it's resolved.

**Comment by horgag** [comment]
@shravyamachanna could you expand a bit more on your solution. I have the same problem... Is it something I have to do with the configuration file?

**Comment by shravyamachanna** [comment]
@horgag ... Our issue was with the bucket policy, previously our bucket policy didn't allow uploads to the buckets with the prefix(public/protected/private). After allowing the object to be uploaded with prefix in bucket policy, it worked.

**Comment by rubana28** [comment]
@shravyamachanna  how did you allow the object to be uploaded with prefix in bucket policy ? it will be very helpful if you share the solution more briefly as I am facing almost the same problem

**Comment by rubana28** [comment]
@shravyamachanna  this is my problem right now

`D/FilePickerDelegate(16243): Selected type */*
W/utter_analytic(16243): Verification of androidx.arch.core.internal.SafeIterableMap$Entry androidx.arch.core.internal.SafeIterableMap$ListIterator.backward(androidx.arch.core.internal.SafeIterableMap$Entry) took 464.219ms
I/utter_analytic(16243): Background concurrent copying GC freed 1530(191KB) AllocSpace objects, 1(20KB) LOS objects, 54% free, 1302KB/2838KB, paused 462us total 515.923ms
D/EGL_emulation(16243): eglMakeCurrent: 0xdd6d9800: ver 2 0 (tinfo 0xdd709400)
I/FilePickerDelegate(16243): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fflowerone.jpg
I/FilePickerUtils(16243): Caching file from remote/external URI
D/EGL_emulation(16243): eglMakeCurrent: 0xe887fa00: ver 2 0 (tinfo 0xd2201d50)
D/EGL_emulation(16243): eglMakeCurrent: 0xdd6d9800: ver 2 0 (tinfo 0xdd709400)
I/FilePickerUtils(16243): File loaded and cached at:/data/user/0/com.example.flutter_analytics/cache/file_picker/flowerone.jpg
I/FilePickerDelegate(16243): Absolute file path:/data/user/0/com.example.flutter_analytics/cache/file_picker/flowerone.jpg
D/EGL_emulation(16243): eglMakeCurrent: 0xe887fa00: ver 2 0 (tinfo 0xd2201d50)
D/eglCodecCommon(16243): setVertexArrayObject: set vao to 0 (0) 7 0
I/flutter (16243): PlatformException(AmplifyException, UPLOAD_FILE_OPERATION_FAILED, {PLATFORM_EXCEPTIONS: {platform: Android, localizedErrorMessage: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, recoverySuggestion: }}, null)`
