### ISSUE TITLE
how to bond WebRTC SDK with cognito function

### ISSUE THREAD

**Issue by jsw-davidhuang** [aws-amplify/amplify-flutter#904]
my company is now using cognito and AWS Kinesis Video Streams to make liveview of the camera, but now, i can only set to use cognito by this amplify-flutter sdk, my question is how to set kvs with the cognito? i believe there are some Access Key ID and Secret Access Key in kvs, i just don't know how to get those key from cognito accounts.

i can found some doc like this ：
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-android.html

but there are no flutter version.

**Comment by dnys1** [comment]
Hi @jsw-davidhuang, currently we do not support integration with the WebRTC SDK. However, the Cognito resources that Amplify generates should function just as well as any other Cognito resource for integration with KVS. You can find the name of your Cognito resource by running `amplify status` and can visit its console page by running `amplify console auth`. Hope this helps.

If you'd like to see a WebRTC SDK for Flutter, I encourage you to leave a comment on [this thread](https://github.com/aws-amplify/amplify-cli/issues/6896) with your intended use case. This will help us prioritize development of an integrated solution.
