### ISSUE TITLE
[Amplify Datastore] Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first

### ISSUE THREAD

**Issue by trey-rosius** [aws-amplify/amplify-flutter#912]
**Describe the bug**
Datastore plugin denies to configure. I have AuthCognito, API, and Storage which all Configure properly, but Datastore doesn't configure. I also noticed that, when I comment out the other 3 plugins(Auth,API,Storage), datastore configures properly. Strange

```
  final AmplifyDataStore _amplifyDataStore =  AmplifyDataStore(modelProvider: ModelProvider.instance,);
  bool _amplifyConfigured = false;
  Future<void> _configureAmplify() async {

   try{


    await Amplify.addPlugins([
     _amplifyDataStore,
      AmplifyAuthCognito(),
      AmplifyAPI(),
      AmplifyStorageS3()
    ]);

      // Once Plugins are added, configure Amplify
      await Amplify.configure(amplifyconfig);
      setState(() {
        _amplifyConfigured = true;

        print("Amplify has been configured");
      });

    } catch(e) {
      print(
          'An error occured :$e');

   
    }


  }


```

**To Reproduce**
1. Run the example in the [docs](https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter/)
2. Add auth, api and storage plugins alongside the datastore plugin.
3. Attempt saving data to datastore.

**Expected behavior**

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en-CM)
    • Flutter version 2.5.1 at /Users/imac/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/imac/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • wstoiz5ps4d6r8em • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 2 categories.
```

</details>

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 8 Pro]
 - OS: [Android 9]
 - Browser [Chrome]
 - Version [93.0]

**Additional context**
I also have my complete code here https://github.com/trey-rosius/friends

**Comment by dnys1** [comment]
Thanks @trey-rosius for your detailed write up. Will investigate this morning and get you an update sometime today.

**Comment by dnys1** [comment]
Hi @trey-rosius - I'm still working on this issue. I appreciate you sharing your code and unforunately, I'm still struggling to reproduce the problem. Would you be able to share the logs you get when you encounter the issue? That would help tremendously as well. Thanks!

**Comment by dnys1** [comment]
One thing I noticed was that you're adding the `AmplifyStorageS3` plugin, but your `amplify` folder in your Github repo does not contain a storage category resource. Can you confirm this is not the source of your problem?

**Comment by trey-rosius** [comment]
Thank you @dnys1 . Indeed datastore couldn't configure because I had the storage plugin added but had not added the storage category to my Amplify application yet.
I wish it actually made storage fail, instead of Datastore. 
Thanks a lot.🙏🏾
I'll close this issue now.

**Comment by dnys1** [comment]
Glad that worked! Thanks for your patience resolving the issue.
