### ISSUE TITLE
Amplify Datastore 1:n Relationship Issue

### ISSUE THREAD

**Issue by ManoVikram** [aws-amplify/amplify-flutter#914]
**Describe the bug**
I have created 2 Amplify Datastore models - Creator and Post. So, basically, the relationship between Creator and Post is 1:n. A creator can post as many Posts as he/she wants. But, a Post will belong to only one Creator. I created the relationship between the models in Amplify Admin and pulled it to my local code. All the coding part was done. The issue comes here. Initially, the Post relationship(1:n) in Creator will be null as there are no posts yet. When I upload the first Post, It is not getting stored in the array(List<Post> is what it will be in code, right?). When I try to upload the 2nd post, the 1st post has vanished and the List<Post> relation in Creator is null again.

What should I do? Is there any workaround?

**Comment by dnys1** [comment]
Hi @ManoVikram, sorry you are experiencing this issue. Would you be able to share your schema here and the code you're running. I'd love to try and reproduce the issue and see if we can find a fix for you.

**Comment by ManoVikram** [comment]
![image](https://user-images.githubusercontent.com/42974191/134705434-e506459a-1166-41fb-8f0d-48fb4cbd4fd7.png)

         `AuthUser userRes = await Amplify.Auth.getCurrentUser();
          List<User> usersList = await Amplify.DataStore.query(
            User.classType,
            where: User.EMAIL.eq(userRes.username),
          );

          User user = usersList.first;

          Audio audio = Audio(
            uploadedOn: TemporalDateTime(DateTime.now().toLocal()),
            title: event.title,
            category: event.category,
            audioKey: audioResult.key,
            thumbnailKey: thumbnailResult.key,
            listenings: 0,
            creatorID: user.creator!.id,
            description: event.description,
          );

            if (user.creator?.id != null) {
            Creator creatorOld = (await Amplify.DataStore.query(
                Creator.classType,
                where: Creator.ID.eq(user.creator?.id)))[0];

            print("Old Creator:");
            print(oldCreator.audioUploads);
            List<Audio> newList = [];
            if (oldCreator.audioUploads == null) {
              print("1");
              newList.add(audio);
            } else {
              print("2");
              newList = oldCreator.audioUploads!;
              newList.add(audio);
            }
            print("NewList: $newList");

            Creator newCreator =
                oldCreator.copyWith(id: oldCreator.id, audioUploads: newList);
            print("New Creator");
            print(newCreator.audioUploads);

            try {
              await Amplify.DataStore.save(audio);
            } catch (error) {
              print(error);
            }

            try {
              await Amplify.DataStore.save(creatorNew);
            } catch (error) {
              print(error);
            }

            yield const UploadAudioSuccess();
          } else {
            yield const UploadAudioFailure();
          }`

I have attached the screenshot and the code above. Let me know if you need more info.

**Comment by HuiSF** [comment]
The nested models with `1:n` or `hasMany` relationship currently requires a separate query to retrieve, in the meantime, all `hasMany` field in the root model remain `null`.
e.g.
```dart
Creator creator = (await Amplify.DataStore.query(
            Creator.classType,
            where: Creator.ID.eq(user.creator?.id)))[0];

// get all audios uploaded by this creator
List<Audio> creatorsAudios =
  await Amplify.DataStore.query(Audio.classType, where: Audio.CREATOR.eq(creator.id))
```

**Comment by ManoVikram** [comment]
Could you please brief it? 

The issue is when the user uploads new audio, it is not even getting stored in the relationship. The relationship is always null.

**Comment by ManoVikram** [comment]
For the first time, the Audio relationship in Creator should be null. That's fine. When I upload the audio and store its data in the datastore, it should get updated and the Audio data should be present in the relationship in Creator. So, when I upload another Audio, there should be 1 already present in the relationship. But, the issue is the relationship is becoming null.

**Comment by HuiSF** [comment]
Hi @ManoVikram thanks for the follow up. Relationship is not a data structure, it just describes how models are related. It doesn't hold any actual data until required query is executed.

After saving the second `Audio` object. Could you please try to run below query, check if it returns 2 audio object in a list (the first audio and the one just saved)

```
// You many need to adjust this example according to your implementation
List<Audio> creatorsUploadedAudios =
  await Amplify.DataStore.query(Audio.classType, where: Audio.CREATOR.eq(creator.id))
```

**Comment by ManoVikram** [comment]
Yes, I am getting a list of 2 Audio objects. Now, I am getting it.
```
Creator creator = (await Amplify.DataStore.query(Creator.classType,where: Creator.ID.eq(user.creator?.id)))[0];
print(creator.audioUploads);
```
The above code will always return '`null`' because audioUploads is just a relation and doesn't contain the actual data. The actual data should be fetched by querying the Audio model. Am I right?

**Comment by HuiSF** [comment]
Yes, that's correct @ManoVikram . At this moment:

* `belongsTo` field is pre-populated when querying root model
* `hasOne` field is not pre-populated
* `hasMany` field is not pre-populated

`hasOne` and `hasMany` require separate queries to retrieve data from database. Some changes are on the way to improve this experience, please stay tuned!

**Comment by Chuckh008** [comment]
Hello, I'm new here and not sure if my post will get read after the issue has been closed or not. I am experiencing the same problem as ManoVikram. I created a simple schema using Admin UI. I too, was surprised that  @hasMany field returns null. I did read the entire thread but I still have a couple of questions. 

Here is the simple schema:

![Screen Shot 2021-12-01 at 5 49 56 PM](https://user-images.githubusercontent.com/45703080/144342816-70c27cd2-c84f-4ad4-bdff-a18c7784a76a.png)

//schema.graphql

type Items @model @auth(rules: [{allow: public}]) {
  id: ID!
  productName: String
  quantity: String
  orderID: ID @index(name: "byOrder")
}

type Order @model @auth(rules: [{allow: public}]) {
  id: ID!
  Customer: String
  OrderItems: [Items] @hasMany(indexName: "byOrder", fields: ["id"])
}

Amplify generated the corresponding models in my project. For brevity, I will only include the getters and Order.fromJson generated for the Order object. 

  @override
  String getId() {
    return id;
  }
  
  String? get Customer {
    return _Customer;
  }
 
**List<Items>? get OrderItems {
    return _OrderItems;
  }**


I'm new to all this but it appears that ['OrderItems'] should be populate in Order.fromJson.

  Order.fromJson(Map<String, dynamic> json)  
    : id = json['id'],
      _Customer = json['Customer'],
      _OrderItems = json['OrderItems'] is List
        ? (json['OrderItems'] as List)
          .where((e) => e?['serializedData'] != null)
          .map((e) => Items.fromJson(new Map<String, dynamic>.from(e['serializedData'])))
          .toList()
        : null;

Why is this code generated?
Given that the dart model classes are overwritten when the schema is change in the UI, how could a second query be implemented with Amplify generated models?
If I somehow injected the OrderItems into the Orders constructor, how could i make OrderItems an observable stream?  

Sorry, I lied. I will include the rest of the model that appears to support CRUD operations on both Order and Item.

  Map<String, dynamic> toJson() => {
    'id': id, 'Customer': _Customer, 'OrderItems': _OrderItems?.map((Items? e) => e?.toJson()).toList()
  };

  static final QueryField ID = QueryField(fieldName: "order.id");
  static final QueryField CUSTOMER = QueryField(fieldName: "Customer");
  static final QueryField ORDERITEMS = QueryField(
    fieldName: "OrderItems",
    fieldType: ModelFieldType(ModelFieldTypeEnum.model, ofModelName: (Items).toString()));
  static var schema = Model.defineSchema(define: (ModelSchemaDefinition modelSchemaDefinition) {
    modelSchemaDefinition.name = "Order";
    modelSchemaDefinition.pluralName = "Orders";
    
    modelSchemaDefinition.authRules = [
      AuthRule(
        authStrategy: AuthStrategy.PUBLIC,
        operations: [
          ModelOperation.CREATE,
          ModelOperation.UPDATE,
          ModelOperation.DELETE,
          ModelOperation.READ
        ])
    ];
    
    modelSchemaDefinition.addField(ModelFieldDefinition.id());
    
    modelSchemaDefinition.addField(ModelFieldDefinition.field(
      key: Order.CUSTOMER,
      isRequired: false,
      ofType: ModelFieldType(ModelFieldTypeEnum.string)
    ));
    
    modelSchemaDefinition.addField(ModelFieldDefinition.hasMany(
      key: Order.ORDERITEMS,
      isRequired: false,
      ofModelName: (Items).toString(),
      associatedKey: Items.ORDERID
    ));
  });
}

class _OrderModelType extends ModelType<Order> {
  const _OrderModelType();
  
  @override
  Order fromJson(Map<String, dynamic> jsonData) {
    return Order.fromJson(jsonData);
  }
}

It appears that all the plumbing is in place but the water is turned off. Like I stated, I'm new at this so...
Would I be asking to much for a simple flutter example app that demonstrates how to address the null @hasMany obstacle? 

One last thing...

ModelProvider.dart throw this compile time error.

Missing concrete implementations of 'getter ModelProviderInterface.customTypeSchemas' and 'setter ModelProviderInterface.customTypeSchemas'.
Try implementing the missing methods, or make the class abstract 

Whenever ModelProvider.dart is regenerated I have to add the following line of code.
  @override
  List<ModelSchema> customTypeSchemas =[];


Thanks in advance

**Comment by HuiSF** [comment]
Hi @Chuckh008 so sorry for missing your comment here.

**Re: list field in generated models**

Currently DataStore doesn't support lazing loading on list field of a model, or populate the list item eagerly. Lazing loading of list field will be supported in the near future, please stay tuned.

> Why is this code generated?

The fromJson is generated generically by codegen on each schema field. You could use `fromJson` to create an instance of the model from a json data by yourself.

>Missing concrete implementations of 'getter ModelProviderInterface.customTypeSchemas' and 'setter ModelProviderInterface.customTypeSchemas'.

This is a new change introduced with amplify-flutter 0.3.0, please refer to this [release note](https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.3.0) to learn about migration process.

**Comment by Chuckh008** [comment]
Hello HuiSF,

Thanks for the response. Could you give me an example of how I could populate the OrderItems in an Order?

**Comment by amitvrm036** [comment]
@HuiSF I checked that other amplify-swift and amplify-js are now supporting lazy loading models but amplify-flutter still lacks this support , please let me know whats the current status for this ?

**Comment by abdallahshaban557** [comment]
Hi @amitvrm036  - we are tracking this work for the Flutter libraries on this ticket https://github.com/aws-amplify/amplify-flutter/issues/1449

We do not have an ETA yet, but our team is working on enabling this work for the GraphQL API category.
