### ISSUE TITLE
[Question] Web Support?

### ISSUE THREAD

**Issue by rgb1380** [aws-amplify/amplify-flutter#916]
What is the timeframe and plan to support Flutter Web?

**Comment by offlineprogrammer** [comment]
Hi @rgb1380  - Thanks for opening this request. There are existing feature requests for web support (#[234](https://github.com/aws-amplify/amplify-flutter/issues/234)). We will continue to use tit to track support for web. Feel free to 👍  it to express your support.

I am going to close this issue as a duplicate to avoid confusion with the other issues.

Regards
Mo
