### ISSUE TITLE
signInWithWebUI does not exit browser, and stay in the navigator after social login

### ISSUE THREAD

**Issue by Ibessas** [aws-amplify/amplify-flutter#923]
I am trying to implement the signInWithWebUI but after the user log in with Facebook or Google, the navigator is redirected to the website on the redirect SignInRedirectURI and does not back to the APP.

1. Init and configure the amplify on your project
2. On the amplifyconfiguration.dart  set into SignInRedirectURI an url that is an actual page on the internet, and set url is in the cognito
3. Use the SignInRedirectURI with Google or Facebook
4. Run the app and login via social
5. After login via Google or Facebook you'll be redirect to the url, and will not back to the app

I was expecting the navigator to close and the tokens to be saved in the app 

flutter doctor -v:
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19042.1237], locale pt-BR)
    • Flutter version 2.2.3 at **[REDACTED]**
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at **[REDACTED]**
    • Platform android-30, build-tools 30.0.2
    • Java binary at: **[REDACTED]**       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at **[REDACTED]**
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.2)
    • VS Code at **[REDACTED]**
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Redmi 4X (mobile) • 639d58d67cf4 • android-arm64  • Android 7.1.2 (API 25)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!

**Comment by Ibessas** [comment]
I'm using the  0.2.0 version, and calling the function this way: `await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);`

**Comment by Jordan-Nelson** [comment]
Hi @Ibessas - Can you share what you specified for `SignInRedirectURI`? Is it something like `<APP_NAME>://`?

**Comment by Ibessas** [comment]
Hello, thanks for the reply!
I'm using: `"SignInRedirectURI": "https://[REDACTED]/visao-geral/"`

**Comment by Jordan-Nelson** [comment]
Typically the `SignInRedirectURI` would be `<APP_NAME>://` and in AndroidManifest there would be a data element with `android:scheme="<APP_NAME>"`.

You might have a unique use case that I am not understanding. Are you trying to redirect the user to a web page after sign in?

**Comment by Ibessas** [comment]
Thanks for the reply!

I made a modification on the `android:scheme` i was using, it was wrong before, now the login is redirecting back to the app, thanks for your help!!!
