### ISSUE TITLE
Returned value from Storage.downloadFile function do not resolve when is called with a expired session

### ISSUE THREAD

**Issue by capida** [aws-amplify/amplify-flutter#926]
**Describe the bug**
After the session expires, any of the functions from the Storage package that use an access token and return a Future, that Future value never is resolved or is rejected. The program waits indefinitely.

**To Reproduce**
1. Configure the authentication client with the following values: 
Auth flows: ALLOW_REFRESH_TOKEN_AUTH, ALLOW_USER_SRP_AUTH
Refresh token expiration: 30 days
Access token expiration: 7 minutes
Id token expiration: 7 minutes
2. Login with a user who has the SMS MFA option enabled
3. Wait until the session expires
4. Then call multiple times Sotorage.downloadFile or some function that requires the access token  (Two or three times is enough).
5. The Future returned by the function never ends. It is neither resolved nor rejected.

**Expected behavior**
After the session expires, no matter how many times they are called, these functions should throw a SessionExpiredException.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Paste your output of "flutter doctor -v" here```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1237], locale en-US)
    • Flutter version 2.2.3 at ****
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ****
    • Platform android-31, build-tools 31.0.0
    • Java binary at: ****
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.60.2)
    • Flutter extension version 3.26.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!

</details>

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android 7.0
 - Google Play Services 21.33.14

**Additional context**
minSdkVersion 21
targetSdkVersion 30
compileSdkVersion 30

**Comment by Jordan-Nelson** [comment]
Hello @capida - Thank you for taking the time to open this issue. I was able to reproduce this with the steps you provided.

This appears to be an issue in Amplify-Android, which Amplify-Flutter depends on when targeting Android. I was able to reproduce this issue in a native Android app using Amplify-Android as well. I have opened an issue (https://github.com/aws-amplify/amplify-android/issues/1516) in Amplify-Android for this. Once it is resolved, it can be pulled into Amplify-Flutter.

**Comment by jack24254029** [comment]
any updates?

**Comment by dnys1** [comment]
Hi @jack24254029 - we have no updates at this time. A workaround to this could be to call `fetchAuthSession` as outlined [here](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/) before calling `downloadFile` so that the tokens are refreshed before the Storage call is made.

**Comment by jack24254029** [comment]
Hi @dnys1 
When do `awsAccessKey`, `awsSecretKey` and `sessionToken` expire?
I don't see this on official document.
Did `downloadFile` return a Amplify Exception when used expired session?

**Comment by dnys1** [comment]
@jack24254029 - AWS credentials are good for one hour (this duration cannot be changed). It appears the current issue is that no exception is being thrown from the `downloadFile` call when credentials have expired.

**Comment by jack24254029** [comment]
Do you plan to improve this issue?

**Comment by jack24254029** [comment]
How about this issue on iOS?

**Comment by jack24254029** [comment]
> The Android team is currently investigating it. You can track their progress here: [aws-amplify/amplify-android#1516](https://github.com/aws-amplify/amplify-android/issues/1516)

Is mean that this issue only occur on Android?

**Comment by jack24254029** [comment]
> > The Android team is currently investigating it. You can track their progress here: [aws-amplify/amplify-android#1516](https://github.com/aws-amplify/amplify-android/issues/1516)
> 
> Is mean that this issue only occur on Android?

I test this on iOS, it works fine.
Thank you very much.

**Comment by Jordan-Nelson** [comment]
This issue should be resolved in the developer-preview version of Amplify Flutter (v1.0.0)

**Comment by Jordan-Nelson** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
