### ISSUE TITLE
Cognito error but sign-in/API sync still works

### ISSUE THREAD

**Issue by raywhiteside** [aws-amplify/amplify-flutter#927]
**Describe the bug**
When logging in, I see this in the log.

```
I/flutter (18553): ┌───────────────────────────────────────────────────────────────────────────────
I/flutter (18553): │ 💡 Logging in from login page
I/flutter (18553): └───────────────────────────────────────────────────────────────────────────────
**W/CognitoUserSession(18553): CognitoUserSession is not valid because idToken is null.**
D/AWSMobileClient(18553): Sending password.
D/AWSMobileClient(18553): Using USER_SRP_AUTH for flow type.
E/UserContextDataProvider(18553): Exception in creating JSON from context data
E/UserContextDataProvider(18553): Exception in creating JSON from context data
D/AWSMobileClient(18553): _federatedSignIn: Putting provider and token in store
D/AWSMobileClient(18553): Inspecting user state details
**D/AWSMobileClient(18553): hasFederatedToken: false** provider: cognito-idp.us-east-2.amazonaws.com/us-east-2_QMtTO7BGQ
I/flutter (18553): ┌───────────────────────────────────────────────────────────────────────────────
I/flutter (18553): │ 💡 Authentication Event SIGNED_IN
I/flutter (18553): └───────────────────────────────────────────────────────────────────────────────
```

**To Reproduce**
Sign in with this Amplify configuration:
```
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "[redacted]",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "[redacted]",
                        "AppClientId": "[redacted]",
                        "AppClientSecret": "[redacted]",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "loginMechanisms": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "[redacted]",
                        "Region": "us-east-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "[redacted]"
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "bbptodo": {
                    "endpointType": "GraphQL",
                    "endpoint": "[redacted]",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }
}''';
```

**Expected behavior**
The functionality is what I expect, but I don't expect/understand the errors (perhaps not errors?) in the log.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Additional context**

**Comment by Jordan-Nelson** [comment]
Hello @raywhiteside - I'm happy to help you understand the logs.

For some context, Amplify-flutter is built on top of [Amplify-Android](https://github.com/aws-amplify/amplify-android) and [aws-sdk-android](https://github.com/aws-amplify/aws-sdk-android). Most of the logs you are seeing are generated from these libraries.

Which log(s) in particular are you looking for info on?

The log `CognitoUserSession is not valid because idToken is null` is expected.

This is logged from [aws-adk-android](https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession.java#L136) when a check to see if a valid session exists fails (i.e. when there is no valid session). When signIn is invoked in amplify-flutter, there is a similar signIn method in aws-sdk-android that is invoked. Prior to signing the user in, this method first checks to see if a valid session already exists.

I am not sure off-hand where `Exception in creating JSON from context data` is coming from. I don't actually see that in a sample app using amplify-flutter.

Let me know if that helps, or if there is a specific log you are looking for info on.

**Comment by raywhiteside** [comment]
Okay, that explains it. Thanks.

**Comment by ptdungivs** [comment]
I am having a similar situation. Can you tell me how you solved it?

**Comment by ptdungivs** [comment]
I am having a similar situation. Can you tell me how you solved it?

**Comment by ptdungivs** [comment]
I am having a similar situation. Can you tell me how you solved it? Thanks.

**Comment by raywhiteside** [comment]
Basically there is no error, Amplify checks if there is a valid session and the error is generated if there isn't. It's just not an indicator something is actually wrong.

**Comment by taouichaimaa** [comment]
This mainly happens to me when I sign in (successfully) but the auth.currentuser is null. can @Jordan-Nelson  you explain why that happens ? It solves itself after trying to login a few times but it makes no sense .

**Comment by chancechou** [comment]
This problem still exists. The code I debugged yesterday, without any changes today, suddenly got this error.

**Comment by chancechou** [comment]
> This problem still exists. The code I debugged yesterday, without any changes today, suddenly got this error.

And only an error message appears, and no error is thrown, so I can't catch the exception and handle it accordingly.

**Comment by chancechou** [comment]
And only the error message is displayed, and no error is thrown, so I can't catch the exception and handle it accordingly.

**Comment by YawarOsman** [comment]
> Basically there is no error, Amplify checks if there is a valid session and the error is generated if there isn't. It's just not an indicator something is actually wrong.

i tried to login in different device(android emulator) it shows this error: `CognitoUserSession is not valid because idToken is null.`

**Comment by Jordan-Nelson** [comment]
Hey folks - it sounds like the issues being reported since this issue was closed are different than the original issue. If you are experiencing an issue, can you please open a new issue?

**Comment by saculNiot** [comment]
Hi, I am facing this issue. It stops me from signing in on Android device. Any solution for this?
