### ISSUE TITLE
Signing in without calling signing out does not work in ios but works in android

### ISSUE THREAD

**Issue by danielvtan** [aws-amplify/amplify-flutter#93]
**Describe the bug**
Should work or should not work for both android and ios to maintain uniformity

**To Reproduce**
1. run example in android and ios
2. remove `Amplify.Auth.signOut` code before `Amplify.Auth.signIn`. run (will work in android. will fail in ios)
3. See error

**Expected behavior**
Should work/not work in both android and ios

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[] Android
[X] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.6

**Additional context**

```
void _signIn() async {
    // Sign out before in case a user is already signed in
    // If a user is already signed in - Amplify.Auth.signIn will throw an exception

    // Removing this code. Amplify.Auth.signIn will throw error in iOS but not in Android
    try {
      await Amplify.Auth.signOut();
    } on AuthError catch (e) {
      print(e);
    }
    // Removing this code. Amplify.Auth.signIn will throw error in iOS but not in Android

    try {
      SignInResult res = await Amplify.Auth.signIn(
          username: usernameController.text.trim(),
          password: passwordController.text.trim());
      Navigator.pop(context, true);
    } on AuthError catch (e) {
      setState(() {
        _signUpError = e.cause;
        _signUpExceptions.clear();
        e.exceptionList.forEach((el) {
          _signUpExceptions.add(el.exception);
        });
      });
    }
  }
```
error thrown
```
flutter: Instance of 'AuthError'
flutter: AMPLIFY_SIGNIN_FAILED
flutter: PLATFORM_EXCEPTIONS
flutter: INVALID_STATE
```

**Comment by Ashish-Nanda** [comment]
@danielvtan We are aware about this issue and are looking into it.
@haverchuck Do you have some additional context?

**Comment by habupagas** [comment]
flutter: Instance of 'AuthError'
flutter: AMPLIFY_SIGNIN_FAILED
flutter: PLATFORM_EXCEPTIONS
flutter: INVALID_STATE

**Comment by haverchuck** [comment]
@danielvtan On the Android platform, you will now receive an exception similar to the iOS platform (if using version 0.1.0).  Some might see this as less than ideal - but it was the safest way to enforce uniformity between platforms.  There is still a divergence in the event that a user has signed in but a session has expired - it is discussed in our [documentation](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter#sign-in-a-user).

**Comment by DaviRolim** [comment]
I'm having the same issue, I'm trying to use the signInWithWebUI, but I deleted the user manually from the pool, and now every time I try to signIn again I get this error and I can't find a way to stop this from happening. I already tried to SignOut before signIn but the same error occurs.
