### ISSUE TITLE
Datastore and Automerge identifying erroneous conflicts after Datastore 0.2.4 update

### ISSUE THREAD

**Issue by djsjr** [aws-amplify/amplify-flutter#930]
**Describe the bug**
After upgrading to Datastore 0.2.4, `Amplify.Datastore.save(model)` does not work properly. I have a model that stores a List of integers as well as several strings. Updating model (by saving a new model with the same id) with a new list, results in concatenating the new list with the old in the cloud. Updating model (by saving a new model with same id) with a different string results in the old list being concatenated onto the old list (as in it doubles) and no string changing in the cloud. Remotely, all the changes are correctly made.

In the Datastore dynamoDB table, new versions of the model instance are being stored upon each save, but again, with the old string and/or a concatenated list. 

When I downgrade to 0.2.2, the list updates successfully, without retaining old values by concatenating new ones.

**To Reproduce**
1. Save a new instance of a model using `Amplify.Datastore.save(model)`. Let's say this model has a name 'Old Name' and a List of ints [0, 1, 2].
  2. create a new instance... `newModel = model.copyWith(id: model.id, name: 'Updated Name')`.
3. Save the new model, replacing the old with `Amplify.Datastore.save(newModel)`.
4. Check amplify admin panel and/or dynamoDB to find model is saved with name still as 'Old Name' and list now reads [0, 1, 2, 0, 1, 2].

**Expected behavior**
Datastore should replace the old list, since there is no conflict. It should also replace the old string if provided a new one. It does neither.

**Screenshots**
none

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.5.0 at /Users/daniel/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 3A9EF015-C91B-4C41-A6F2-B9B61DD0C554 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 14.7.1
 - Browser n/a
 - Version

**Additional context**

[This doc](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html) explains that auto merge concatenates lists when it detects a conflict: 'Concatenate the incoming list with the existing list in the server.' But I do not see why a conflict is being detected, if it is. I am only updating the model instance on one device.

**Comment by HuiSF** [comment]
It looks like amplify-ios now doesn't support generating update mutation GraphQL document with only updated fields, instead , it sends entire model which may cause the issue:

```
[0, 1, 2] => [0, 1, 2, 0, 1, 2]
```

**Comment by djsjr** [comment]
@HuiSF just realized you're one of the people trying to fix this and not just an app dev with a similar problem. Thank you for taking a look into this!

**Comment by HuiSF** [comment]
Hi @djsjr oops you caught me :D and sorry somehow I missed your last comment.

I can't think of a workaround within the current codebase. Though AppSync allows different conflict resolution strategy, e.g. Custom Lambda, with this feature extra work is required, but you can probably gain a complete control of how it should merge conflict data. So it may be worth to look into while waiting on the library fix.

**Comment by djsjr** [comment]
@HuiSF I haven't had a problem since 0.2.5 came out. 0.2.6 causes no issue so far either. Will close!
