### ISSUE TITLE
Really need release notes

### ISSUE THREAD

**Issue by rmargolinross** [aws-amplify/amplify-flutter#932]
**Describe the bug**
This project has no release notes and it is difficult to find what changed and what I should be looking out for

**To Reproduce**
look for release notes

**Expected behavior**
They exist 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by HuiSF** [comment]
Hi @rmargolinross thanks for opening this issue and your suggestion.
Would this [releases](https://github.com/aws-amplify/amplify-flutter/releases) page help with what you need?

**Comment by Jordan-Nelson** [comment]
Hello @rmargolinross - As @HuiSF noted, the releases page is a good way to see the changes in a release across all packages. If you would prefer to see notes for a specific package, each package has a change log located at https://github.com/aws-amplify/amplify-flutter/blob/main/packages/<PACKAGE_NAME>/CHANGELOG.md. For example, here is [the change log for amplify_auth_cognito](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_auth_cognito/CHANGELOG.md).

Those change logs are used to generate the change logs on pub.dev. See example for [amplify_auth_cognito](https://pub.dev/packages/amplify_auth_cognito/changelog).

**Comment by rmargolinross** [comment]
@HuiSF thanks for the link. I for some reason, couldn't find the releases page for amplify-flutter. That is exactly what I was looking for.
