### ISSUE TITLE
"Hot restart" is causing a subsequent call to `Amplify.configure`

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#94]
**Describe the bug**
PlatformException (PlatformException(AmplifyException, The client issued a subsequent call to `Amplify.configure` after the first had already succeeded., {cause: null, recoverySuggestion: Be sure to only call Amplify.configure once}))

**To Reproduce**
```
  Amplify amplify = Amplify();
  bool _isAmplifyConfigured = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _initAmplifyFlutter();
  }

  void _initAmplifyFlutter() async {
    print("init amplify");
    AmplifyAuthCognito auth = AmplifyAuthCognito();

    amplify.addPlugin(
      authPlugins: [auth],
    );
    // Initialize AmplifyFlutter
    await amplify.configure(amplifyconfig);

    setState(() {
      _isAmplifyConfigured = true;
    });
  }
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[x] Android
[] iOS (cant test)

**Additional context**
This Error happens in VSCode when hot restarting.

**Comment by fjnoyp** [comment]
Hi @Rayv1 thanks for bringing this issue to our attention.  

Our Amplify Flutter framework currently supports hot reloading but not hot restarting.  

For now, we recommend hot reloading or stopping and starting the the app in VSCode.  Please let us know if that would be a major problem for you and your workflow. 

We will look into how we might fix this issue in the future.

**Comment by Rayv1** [comment]
Hi @fjnoyp its okay for now. i just comment it out, when using hot restart.

**Comment by lukaselmer** [comment]
> Hi @Rayv1 thanks for bringing this issue to our attention.
> 
> Our Amplify Flutter framework currently supports hot reloading but not hot restarting.
> 
> For now, we recommend hot reloading or stopping and starting the the app in VSCode. Please let us know if that would be a major problem for you and your workflow.
> 
> We will look into how we might fix this issue in the future.

Hi @fjnoyp,

This is a major problem for my workflow - not having the option to hot restart slows me down substantially.

What is the behavior if the app is already configured (in Kotlin / Android), and then the Dart VM is restarted? Do I have to configure it again, or will it work with the previous configuration? Would it be possible to add a separate method [here](https://github.com/aws-amplify/amplify-flutter/blob/master/packages/amplify_core/android/src/main/kotlin/com/amazonaws/amplify/amplify_core/Core.kt#L39) to check if the configuration is initialized already?

**Comment by bwhiteTP** [comment]
@Rayv1 Not sure why this was closed, this is a major problem for us, please reopen.

**Comment by Rayv1** [comment]
I put it in a try catch Block, so iam still calling it, but when an error appears, iam doing nothing. The authentication Plugin ist ein still working with this work around.
