### ISSUE TITLE
Unable to sign-in user. MFAMethodNotFoundException was raised. 

### ISSUE THREAD

**Issue by hsiehro** [aws-amplify/amplify-flutter#95]
**Describe the bug**
Able to sign-up user, but unable to sign-in.  MFAMethodNotFoundException was raised after submission, but no MFA message received. Check user pool, user account status is 'Confirmed' and 'Enabled' with email verified set 'true', and SMS MFA Status - 'Disabled'

**To Reproduce**
1. Sign-up user with basic info (name, email, password)
2. User email inbox received MFA verification code 
3. Enter 6 digit verification code and submit
4. Return sign-up complete successfully
5. Go to Sign-in page
6. Enter user email + password and submit
7. Returns the MFAMethodNotFoundException message

**Expected behavior**
Either sign-in succeed or received new MFA verification code in user inbox for multi-factor authentication

**Screenshots**
W/CognitoUserSession(28635): CognitoUserSession is not valid because idToken is null.
D/AWSMobileClient(28635): Sending password.
E/amplify:flutter:auth_cognito(28635): AMPLIFY_SIGNIN_FAILED
E/amplify:flutter:auth_cognito(28635): AmplifyException {message=Sign in failed, cause=com.amazonaws.services.cognitoidentityprovider.model.MFAMethodNotFoundException: No MFA mechanism registerd in the account. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: MFAMethodNotFoundException; Request ID: 9a418ff2-7333-4138-be5b-eac965efaad8), recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito(28635): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$5.onError(AWSCognitoAuthPlugin.java:357)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onFailure(AWSMobileClient.java:1258)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onFailure(CognitoUser.java:1155)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$23.run(CognitoUser.java:2915)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2965)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1222)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1176)
E/amplify:flutter:auth_cognito(28635): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(28635): 	at java.lang.Thread.run(Thread.java:818)
E/amplify:flutter:auth_cognito(28635): Caused by: com.amazonaws.services.cognitoidentityprovider.model.MFAMethodNotFoundException: No MFA mechanism registerd in the account. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: MFAMethodNotFoundException; Request ID: 9a418ff2-7333-4138-be5b-eac965efaad8)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[x] Android
[N/A] iOS

**Additional context**
Maybe this is not related to the Amplify flutter itself. I suspect the reason cause is due to I enable the SMS text message for MFA second factors during the initial setup, which I never use it during my authentication process (phone number is not required). The only reason I enable it is simply to keep it as an option in case I need it in the future.

**Comment by fjnoyp** [comment]
Hi @hsiehro thanks for sharing this issue with us.  Have you tried setting up your Amplify Flutter project again to use phone numbers during user sign up?  I think the insight that you provided in "additional context" is probably correct.  Cognito is failing with MFAMethodNotFoundException because MFA with phone number can't be enabled if the user isn't providing any phone numbers to begin with :)

**Comment by hsiehro** [comment]
Hi @fjnoyp Kyle,

Thanks for the prompt reply. I haven't tried the phone number scenario during sign-up. Will give it a try later or consider reset the project without the SMS authentication during initial setup for now.  Since the exception root cause is confirmed, I will close this issue.

Again, thanks for your great support.

BR/Roger
