### ISSUE TITLE
How to write integration test for social login

### ISSUE THREAD

**Issue by thphuc** [aws-amplify/amplify-flutter#950]
Hi team.

Sorry I don't follow the template in this question because this is not a bug.

I am learning how to write integration test for social login. I can "mock" the social login and pass my login screen. But then the problem is I need real authorized user to call other apis. 

Do we support what I am trying to do?

Thanks!

**Comment by Jordan-Nelson** [comment]
Hi @thphuc - How are you mocking social sign in and which other APIs are you trying to call in your test? Would mocking the other APIs via the same method you are mocking social sign in with meet your use case?

**Comment by dnys1** [comment]
Closing since this is a larger request to Flutter and not something we can support at the moment.
