### ISSUE TITLE
Datastore Sync not working - unable to store data in aws datastore

### ISSUE THREAD

**Issue by LetsHandOutOurMastery** [aws-amplify/amplify-flutter#957]
**Whenever Im trying to save data in aws amplify datastore, im receiving this exception. Im using AWS cognito for authentication. Once user authenticated, I will perform save operation in datastore which was working previously.

DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=javax.net.ssl.SSLHandshakeException: Chain validation failed, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
W/amplify:aws-datastore(31591): at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:359)
W/amplify:aws-datastore(31591): at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4)
W/amplify:aws-datastore(31591): at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:157)
W/amplify:aws-datastore(31591): at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
W/amplify:aws-datastore(31591): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore(31591): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore(31591): at java.lang.Thread.run(Thread.java:920)
W/amplify:aws-datastore(31591): Caused by: ApiException{message=OkHttp client request failed., cause=javax.net.ssl.SSLHandshakeException: Chain validation failed, recoverySuggestion=See attached exception for more details.}
W/amplify:aws-datastore(31591): ... 5 more
W/amplify:aws-datastore(31591): Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed**

**Comment by HuiSF** [comment]
Hi @LetsHandOutOurMastery looking at this exception

```
javax.net.ssl.SSLHandshakeException: Chain validation failed
```

It looks a network layer issue happening in your testing device. I think this is nothing to do with the library itself...

Here are some tips I can think of to help you resolve this issue:

- Are you using proxy on your Android device/emulator?
- Is the date and time accurate on your Android device/emulator?
- Could you try to run the App on a iOS simulator see if it happens?

**Comment by LetsHandOutOurMastery** [comment]
Hi @HuiSF. Please check below.

    1. Are you using proxy on your Android device/emulator? -  No.
    2. Is the date and time accurate on your Android device/emulator? - Yes. The Aws amplify server we using is us-east1 - US East-N Virginia and I am using the app from UAE(Gulf standard time). Could this be a problem. It was working earlier with the same config in admin UI and flutter code.
    3. Could you try to run the App on a iOS simulator see if it happens? - I have tried the same in ios Simulator also. I dont find the error but the data not saved in Amplify Datastore. 

**ios Log:** 
flutter: [ItemMaster {id=d739b4ee-af1d-41a9-b759-14b733076363, ItemID=IT_000001, ItemName=adfsfsdf, Category=Sweets, ThumbnailImagePath=https://quikshopimages.s3.amazonaws.com/buttermilk_kulambu_masala-214x300.jpg, Description=adfsdf, Status=10, LongDesc=dad, Weight=10, Units=KG, ItemBrand=sdfsd, FullsizeImagePAth=https://quikshopimages.s3.amazonaws.com/buttermilk_kulambu_masala-214x300.jpg, LastDate=121222}, ItemMaster {id=9c9a0e99-ad1e-4dad-ac64-f3dfd8620c24, ItemID=IT888888, ItemName=sadfsf sweetysd, Category=Sweets, ThumbnailImagePath=https://quikshopimages.s3.amazonaws.com/buttermilk_kulambu_masala-214x300.jpg, Description=adfsdf, Status=10, LongDesc=dad, Weight=10, Units=KG, ItemBrand=sdfsd, FullsizeImagePAth=https://quikshopimages.s3.amazonaws.com/buttermilk_kulambu_masala-214x300.jpg, LastDate=121222}, ItemMaster {id=335b30e3-29fb-4b8c-be68-b2d3418fbe4d, ItemID=IT7777777, ItemName=sadfsfsweetys345, Category=Sweets, ThumbnailImagePath=https://quikshopimages.s3.amazonaws.com/buttermilk_ku<…>




Below is the GraphQL schema for the table and we are trying to save data to this table. 

type ItemMaster @model
@key(fields: ["Status", "ItemName"])
@key(name: "byItemCat", fields: ["Status", "Category"], queryField: "byItemCat")
@key(name: "byItemBrand", fields: ["Status", "ItemBrand"], queryField: "byItemBrand")
@key(name: "byItemID", fields: ["ItemID", "Status"], queryField: "byItemID")
@auth(rules: [{allow: public}]) {
id:ID!
ItemID: String!
ItemName: String!
Category: String!
ThumbnailImagePath: AWSURL!
Description: String!
Status: Int!
LongDesc: String!
Weight: Int!
Units: String!
ItemBrand: String!
FullsizeImagePAth: AWSURL!
LastDate: AWSTimestamp
}

**Comment by LetsHandOutOurMastery** [comment]
I just queried immediately after saving the data and receive the response model only from my local, not the cloud data. It looks the data saves only in local not in the cloud. How can we do it? Am I missing something?


I/amplify:aws-datastore( 3438): Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='f123398e-c7c7-4552-b41a-e36fda93f8d3', serializedData={LongDesc=FruitsBanana Robustas3\IT_000002.jpg, Status=0, Category=Fruits, Description=FruitsBanana Robusta, ThumbnailImagePath=s3\IT_000002.jpg, ItemBrand=None, ItemID=IT_000002, Units=gm, Weight=90, LastDate=12312321312323, FullsizeImagePAth=test1235, ItemName=Banana Robusta, id=f123398e-c7c7-4552-b41a-e36fda93f8d3}, modelName=ItemMaster}, mutationType=CREATE, mutationId=114ab13e-2ace-11ec-b1cc-ef694f0d6d58, predicate=MatchAllQueryPredicate}

I/amplify:aws-datastore( 3438): Successfully removed from mutations outboxPendingMutation{mutatedItem=SerializedModel{id='f123398e-c7c7-4552-b41a-e36fda93f8d3', serializedData={LongDesc=FruitsBanana Robustas3\IT_000002.jpg, Status=0, Category=Fruits, Description=FruitsBanana Robusta, ThumbnailImagePath=s3\IT_000002.jpg, ItemBrand=None, ItemID=IT_000002, Units=gm, Weight=90, LastDate=12312321312323, FullsizeImagePAth=test1235, ItemName=Banana Robusta, id=f123398e-c7c7-4552-b41a-e36fda93f8d3}, modelName=ItemMaster}, mutationType=CREATE, mutationId=114ab13e-2ace-11ec-b1cc-ef694f0d6d58, predicate=MatchAllQueryPredicate}

Though I receive the log, but the same data not found in cloud.

**Comment by HuiSF** [comment]
For Admin UI questions/issues, you may want to check out https://github.com/aws-amplify/amplify-adminui/issues
