### ISSUE TITLE
resendSignUpCode throws Error but sends Code

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#97]
**Describe the bug**
I used the resendSignUpCode function from Amplify.Auth, then it throws an Error, but i receive an E-Mail with a new Verification Link.
Exception:
```

cause:"ERROR_FORMATTING_PLATFORM_CHANNEL_RESPONSE"
exceptionList:List (1 item)
[0]:AuthException
detail:"codeDeliveryDetails malformed"
exception:"resendSignUpCode failed"
hashCode:255155121
runtimeType:Type (AuthException)
hashCode:519294247
runtimeType:Type (AuthError)
```

MyCode:
```
  Future<bool> resendSignUpMessage(String email) async {
    try {
      ResendSignUpCodeResult res =
          await Amplify.Auth.resendSignUpCode(username: email);
      return true;
    } catch (e, s) {
      printErrorStack(e.exceptionList, s);
      return false;
    }
  }
```

**Expected behavior**
Not throwing an Error, if there is none

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[x] Android
[] iOS

**Comment by fjnoyp** [comment]
Hi @rayv1 thanks for sharing this issue with us.  We'll look into reproducing this problem on our side and get back to you with what we find.

**Comment by fjnoyp** [comment]
Hi @Rayv1 we're able to reproduce the error on our side.  An error is being thrown yet the code is being sent still.  Thank you very much for bringing this to our attention.  We'll look into fixing the issue.

**Comment by haverchuck** [comment]
@Rayv1 Thanks for submitting this issue; I've created a [PR to fix it.](https://github.com/aws-amplify/amplify-flutter/pull/101)
