### ISSUE TITLE
Data is not persistent when releasing to iOS  - Apple - TestFlight 

### ISSUE THREAD

**Issue by braddonakowski** [aws-amplify/amplify-flutter#974]
**Describe the bug**

The issue we are having is that the data is not persistent when a user downloads the application from Apple Developer - TestFlight.

For example, we see the data is correct in the Amplify admin console and DynamoDB, but when a user downloads the application, the data displayed varies from user to user. Some Users see more Categories than others, some see more subcategories than others. 

Some devices seem to be syncing all of the data and some are not. From the application logs, we see that the sync process has been completed successfully. We currently have around 400 Categories, and 30,000 subcategories. Could this much data be an issue?

Packages installed:

amplify_flutter: ^0.2.2
amplify_datastore: ^0.2.2
amplify_api: ^0.2.2
amplify_storage_s3: ^0.2.2
amplify_auth_cognito: ^0.2.2

We believe the problem is with Amplify datastore, and when the application starts to sync the data. Specifically the two functions below:

```dart
Future<bool> _configureAmplify() async {
    // Once Plugins are added, configure Amplify
    try {
      await Future.wait([
        Amplify.addPlugin(
          AmplifyDataStore(
            modelProvider: ModelProvider.instance,
            syncMaxRecords: 80000,
          ),
        ),
        Amplify.addPlugin(AmplifyAPI()),
        Amplify.addPlugin(AmplifyAuthCognito()),
        Amplify.addPlugin(AmplifyStorageS3()),
      ]);
      await Amplify.configure(amplifyconfig);
      return Amplify.isConfigured;
    } catch (e) {
      print(e);
      return false;
    }
  }

 Future<List<Product>> _getProducts() async {
    try {
      this._products = (await Amplify.DataStore.query(
        Product.classType,
        pagination: QueryPagination(limit: 900000),
        where: Product.ISEXCLUDED.eq(false),
      ))
          .where(
            (p) => p.approvalStatus == ProductApprovalStatus.APPROVED,
          )
          .toList();
      return products;
    } catch (e) {
      return [];
    }
  }
```

**To Reproduce**
1) I am not receiving any errors, so I am unable to identify the problem.
2) When I download the application myself from Apple testflight, I am able to see each product and category as expected, but other users are not. 

**Expected behavior**
When downloading from testflight, each device should receive the same data from Amplify.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS
<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Users/Admin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Admin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/Admin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code
    • VS Code at /Users/Admin/Desktop/Dev/TOPCON/sar/topcon/lib/fonts/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code
    • VS Code at /Users/Admin/Desktop/Dev/TOPCON/sar/topcon/lib/fonts/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/Admin/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPad (mobile) • 00008020-001144CE26D3002E • ios • iOS 14.7.1 18G82

! Doctor found issues in 1 category.

</details>

**TABLET (please complete the following information):**
 - Device: [e.g. iPad Air (3rd Generation)]
 - OS: [e.g. iOS14.7.1]

**Additional context**

**Comment by HuiSF** [comment]
Hi @braddonakowski thanks for reporting this issue. Could you please try to answer below questions to help us triaging the issue?

You mentioned you have "400 Categories, and 30,000 subcategories"...
1. How are the `category` and ``subcategory` defined in your data model? Are they separate data model, or a field on your "item" model?
2. How many data entries in total under the "400 Categories"?
3. Did you define any sorting strategies when defining GraphQL schema?
4. Did you enable auth rules on data model?
5. Could you provide the schema for inspection? (if it's inconvenient to post the original code, you can rename the field names, and omit unimportant fields etc )

**Comment by braddonakowski** [comment]
Hi @HuiSF. Thank you for the response. Here is the additional information.


**How are the category and “subcategory” defined in your data model? Are they separate data model, or a field on your item model?**
	
We have a Category model (400 entries but we typically show less than 20 ) which CATEGORY model includes the fields: 

id ID!
categoryID String 
name String
imgID String
isSolutionCategory Bool
shouldDisplay Bool
visibilityGroups [String]

We have a Products model (about 30,000 entries) which includes the fields: 
id ID!
productID String
name String
description String
subtitle String
imgID String
models [String]
categoryID String
relatedProducts [String]
isKit Bool
visibilityGroups [String]
superCategories[String]
isExcluded Bool

….. Model goes on,

Then we have a Product Variant (Roughly 2000 entries) Model: 
id ID!
variantID String
name String	
description String
price Float
baseProductCode String
subtitle String
isExcluded bool

The way these models work together is each Category holds a variety of Products, and the Product will hold the ProductVariant


**How many data entries in total under the “400 categories”?**
Under Categories we hold products, which is roughly 30,000. Each Category typically holds 1 - 75 products. A lot of these products are being hidden as well.

**Did you define any sorting strategies when defining GraphQL schema?**
No

**Did you enable Auth rules on data model?**
	Yes, we enabled Auth. 

**Could you provide the Schema for inspection?** 
	Schemas are provided above. 

I do not think this is an issue with the way our tables are set up, but rather when we query the product table, not all results in backend are being returned.

**Comment by braddonakowski** [comment]
@HuiSF Email and password authentication
