### ISSUE TITLE
APIPluginInterface not found

### ISSUE THREAD

**Issue by Afunyah** [aws-amplify/amplify-flutter#976]
Hello,

I just noticed that version 0.2.4 of the amplify flutter packages is available.

After upgrading them and running flutter run,I get a long error stack.

The first message being:

/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_api-0.2.4/lib/amplify_api.dart:18:8: Error: Error when reading '/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_api_plugin_interface-0.2.4/lib/amplify_api_plugin_interface.dart': The system cannot find the path specified.

VS Code also gives an error when I try to add AmplifyAPI() to the plugin list. All the other plugins work fine.

Is this a known problem with the new version?

I even tried adding amplify_api_plugin_interface to the dependencies.

**Comment by HuiSF** [comment]
It looks like a local cache issue, Could you try

```
flutter clean
flutter pub get
flutter run
```
