### ISSUE TITLE
S3 File Download - Access Denied Exception

### ISSUE THREAD

**Issue by sirajudheen53** [aws-amplify/amplify-flutter#981]
I was trying to access S3 bucket protected contents from Flutter Amplify framework. I have configures Auth and Storage plugins in Amplify by following Amplify docs. But I was receiving access denied exception upon file download.

Exception:

StorageException(message: Something went wrong with your AWS S3 Storage download file operation, recoverySuggestion: See attached exception for more information and suggestions, underlyingException: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: F4297FA684QR5N34), S3 Extended Request ID: xKzvpdGmVuC+OErI5b9fVvqeZClQ0sMypw309F9Tcsx+948Q+s1ntkWigZxBlBhiCynaMV3OpcQ=)

**Comment by HuiSF** [comment]
Hi @sirajudheen53 thanks for opening this issue.

Could you please provide code examples that how you were trying to access the file in S3 bucket?

**Comment by vaibhavjoshi247** [comment]
Facing same issue

**Comment by orestesgaolin** [comment]
I have similar issue. Download fails with:

```
AccountBucketException (AccountBucketException - AccountBucketException - StorageException(message: Something went wrong with your AWS S3 Storage download file operation, recoverySuggestion: See attached exception for more information and suggestions, underlyingException: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: Q3WVK0Y4VCNVWWT0), S3 Extended Request ID: jkxscshaU37d7jjlSiwGCvZeVK0k1fO/clMcxAgHm8RxTMQM1GNisx9t8jK2MSP9UZy9KnNP9wI=))
```

And there's an interesting difference in URL generated with `getUrl()` vs one generated in the console:

`getUrl`:

```dart
      const sevenDays = 60 * 60 * 24 * 7;
      final options = GetUrlOptions(
        accessLevel: StorageAccessLevel.private,
        expires: sevenDays,
      );
      final result = await _storageCategory.getUrl(key: key, options: options);
```

```
https://[redacted]0.s3.eu-west-1.amazonaws.com/private/eu-west-1:fcb2250d-53e7-41ee-846f-6c436772ef02/image1.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjELr%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCWV1LXdlc3QtMSJGMEQCIB4vHVEGLxgcdCjwwX7LIuDNN0x8lngCPW%2Ft[redacted]y8vuJ4g5ZTe6MHhjk7f%2FiGgf26iyd6soPhTbpFa7bV6wRLTEIxE%2B6SJdkePBLtLnk%3D&
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Date=20211217T093950Z&
X-Amz-SignedHeaders=host&
X-Amz-Expires=604799&
X-Amz-Credential=ASIAYD[redacted]211217%2Feu-west-1%2Fs3%2Faws4_request&
X-Amz-Signature=280eae5[redacted]55b4f3bd58177f9453d7532e3edd
```

path: `private/eu-west-1:fcb2250d-53e7-41ee-846f-6c436772ef02/image1.jpg`


----

console:

```
https://[redacted]0.s3.eu-west-1.amazonaws.com/private/231559db-bd3a-42ae-a368-4a7ce6d1ab62/image1.jpg?response-content-disposition=inline&
X-Amz-Security-Token=IQoJb3JpZ2luX2VjELr%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmV1LW5vcnRoLTEiSDBGAiEA8ZKApycxBX24F7%2BUN6rHee1C%2FFQ[redacted]37LIF4IBYIH7haw05bmWEFrIdVroGlC1DrgvZdiuWEIDqMITJB5g91Dn9qfGbTfBnWTMz0hHCKAqlAmEWRa7G%2FWzhri2fQIKALdZussfe0klMKQzvOyqpIGfwdOwhv9IJe1609&
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Date=20211217T100349Z&
X-Amz-SignedHeaders=host&
X-Amz-Expires=900&
X-Amz-Credential=ASIAYDAP5ISG7A[redacted]%2Feu-west-1%2Fs3%2Faws4_request&
X-Amz-Signature=99d036b9f940ebed[redacted]dbef711b39d7ee66f6909b3fdfeb7

```

path: `private/231559db-bd3a-42ae-a368-4a7ce6d1ab62/image1.jpg`

The `231559db-bd3a-42ae-a368-4a7ce6d1ab62` is the user id passed when uploading image:

```dart
      final user = await _authCategory.getCurrentUser();
      final options = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.private,
        targetIdentityId: user.userId,
      );
      final fileName = file.path.split('/').last;
      final result = await _storageCategory.uploadFile(
        local: file,
        key: fileName,
        options: options,
      );
```

I'm happy to open another issue, but I'm not sure if I'm able to share reproducible example

**Comment by HuiSF** [comment]
Hi @orestesgaolin in which platform you are seeing this download failure? iOS or Android?

**Comment by dorontal** [comment]
FYI: This issue may be related to Issue #1853 -- @sirajudheen53 or @orestegaolin - do you no longer have this issue?
