### ISSUE TITLE
Failure encountered while attempting to start API sync

### ISSUE THREAD

**Issue by zamargab** [aws-amplify/amplify-flutter#984]
**Describe the bug**
My Datastore API sync fails with the error below, I have 6 modesl but only one model is experiencing this issue. The other ones sync just fine

E/amplify:aws-datastore( 5706): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore( 5706): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.util.concurrent.TimeoutException: Timed out while performing initial model sync., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at
E/amplify:aws-datastore( 5706): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that
E/amplify:aws-datastore( 5706): match your scenario, and file an issue with the details of the bug if there isn't.}
E/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:327)
E/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(lambda)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/amplify:aws-datastore( 5706): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/amplify:aws-datastore( 5706): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
E/amplify:aws-datastore( 5706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/amplify:aws-datastore( 5706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/amplify:aws-datastore( 5706): 	at java.lang.Thread.run(Thread.java:761)
E/amplify:aws-datastore( 5706): Caused by: java.util.concurrent.TimeoutException: Timed out while performing initial model sync.
E/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:323)
E/amplify:aws-datastore( 5706): 	... 18 more

W/amplify:aws-datastore( 5706): API sync failed - transitioning to LOCAL_ONLY.
W/amplify:aws-datastore( 5706): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.util.concurrent.TimeoutException: Timed out while performing initial model sync., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at
W/amplify:aws-datastore( 5706): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that
W/amplify:aws-datastore( 5706): match your scenario, and file an issue with the details of the bug if there isn't.}
W/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:327)
W/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(lambda)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
W/amplify:aws-datastore( 5706): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
W/amplify:aws-datastore( 5706): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/amplify:aws-datastore( 5706): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
W/amplify:aws-datastore( 5706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/amplify:aws-datastore( 5706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/amplify:aws-datastore( 5706): 	at java.lang.Thread.run(Thread.java:761)
W/amplify:aws-datastore( 5706): Caused by: java.util.concurrent.TimeoutException: Timed out while performing initial model sync.
W/amplify:aws-datastore( 5706): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:323)
W/amplify:aws-datastore( 5706): 	... 18 more
I/amplify:aws-datastore( 5706): Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
I/amplify:aws-datastore( 5706): Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore( 5706): Stopping subscription processor.
I/amplify:aws-api( 5706): No more active subscriptions. Closing web socket.

**To Reproduce**
1. Create 6 new Data models using the Amplify Admin UI
2. Pull the backend using the Amplify CLI
3. Use a Lambda function to import a csv file to populate database with data
4. Run app on Android emulator

**Expected behavior**
I expect to see all the tables with the data imported from the csv file when i query the tables in my flutter app, i happen to see the data in all tables except for just one particular model, the weird thing is that I used the same python code to upload all the data into all my tables. When i query this database in my flutter app, It return 0 results but when i check the database on my AWS console, i see the data just sitting right there. This is happenng with just one model.

**Platform**
[] Android

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.15063], locale en-GB)
    • Flutter version 2.5.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\GABRIEL\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.1)
    • VS Code at C:\Users\GABRIEL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81```

</details>

**Comment by dnys1** [comment]
Hi @zamargab - sorry you are experiencing this issue. Can you please share which version of `amplify_api` you are using (from your `pubspec.lock` file) as well as your schema (from `amplify/backend/api/<api name>/schema.graphql`). This will help greatly in diagnosing this problem. Thanks!

**Comment by dnys1** [comment]
Agree with @HuiSF - also, can you confirm you see no errors being printed in CloudWatch?

**Comment by zamargab** [comment]
![aws2](https://user-images.githubusercontent.com/75364779/137964065-4a013258-d92a-4a19-a948-0c5d45974691.png)
Above is another table i imported through Lambda, this table is fine, no issues
