### ISSUE TITLE
S3 bucket only returning 1000 files

### ISSUE THREAD

**Issue by braddonakowski** [aws-amplify/amplify-flutter#991]
**Describe the bug**
We are having an issue where only 1000 files are being retrieved from our S3 bucket. We have around 20,000 images in our bucket. I came across this question on StackoverFlow, https://stackoverflow.com/questions/44070580/not-all-data-only-1000-elements-retrieved-from-s3-using-amazon-sdk, but am unable to find something similar for the flutter platform.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

**Smartphone (please complete the following information):**
 - Device: [e.g. ipad air 3]
 - OS: [e.g. iOS14.7]

**Additional context**

**Comment by HuiSF** [comment]
Hi @braddonakowski ampify-ios maintainers are still working on this. Will keep you posted.

**Comment by cbs9md** [comment]
Hi @HuiSF.  2 things.

1. I wanted to know if there were any updates on your end concerning this issue.  

2. The reason we need to list files in s3 is to check the existence of a file before downloading.  The way we are currently doing this is listing the files, then checking if any of the files correspond with the key of the item we are trying to download.  Was also wondering if there is a better way to accomplish this that would circumvent the need to list files in s3.

**Comment by HuiSF** [comment]
Hey @cbs9md thanks for following up on this issue. amplify-ios maintainers are working on the feature request.

I believe if an object doesn't exist in s3 bucket, `downloadFile` and `getUrl` API calls should return corresponding error, which you should be able to catch and react accordingly.

Maybe I missed some context, for the second point what kind of specific use case you want to achieve?

**Comment by rabi-palmtree** [comment]
> 2. The reason we need to list files in s3 is to check the existence of a file before downloading.  The way we are currently doing this is listing the files, then checking if any of the files correspond with the key of the item we are trying to download.  Was also wondering if there is a better way to accomplish this that would circumvent the need to list files in s3.

About 2, is it not easier to do use the available key and getUrl   before downloadFile  ?
GetUrlResult result = await Amplify.Storage.getUrl(key: fileKey, options: options);

**Comment by Jordan-Nelson** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. Please see [the docs](https://docs.amplify.aws/lib/storage/list/q/platform/flutter/) to learn more about pagination in the Storage category.

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).
