### ISSUE TITLE
How to update GRAPHQLAPIKEYOUTPUT in lambda functions

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#998]
**Describe the bug**
My graphql API key got expired after 1 month, since I set it to 30 days, but now when I am trying to update it, nothing is happening. 
So, now I am not able to send any get,post or delete request from my app. This issue is also preventing `lambda functions` to perform any post axios operation.

What I tried: 
1. Navigate to AppSync console -> Settings ->  Default authorization mode -> new (I deleted old one, because it was saying it is expired). It obviously didn't worked on amplify pull beacuse it is not yet supported. So I tried with cli
2. From cli, `amplify update api`
```
amplify update api                                                   ✔  42s 
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Walkthrough all configurations
? Choose the default authorization type for the API API key
? Enter a description for the API key: this is a description 2nd
? After how many days from now the API key should expire (1-365): 365
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API Amazon Cognito User Pool, IAM
Cognito UserPool configuration
Use a Cognito user pool configured as a part of this project.
? Enable conflict detection? No

GraphQL schema compiled successfully.
```
Now `amplify status` shows nothing is changed. 

**To Reproduce**
1. Set api key expiration to 1 day
2. Next day try to execute your lambda function, you will get an error like this one: 
```
INFO	Error: Request failed with status code 401
    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
```
3. In cloud function I am using Axios to run graphql queries : 
```
await axios({
      url: process.env.API_MYAPPBACKEND_GRAPHQLAPIENDPOINTOUTPUT,
      method: "post",
      headers: {
        "x-api-key": process.env.API_MYAPPBACKEND_GRAPHQLAPIKEYOUTPUT,
      },
      data: updateTESTData,
    })
```
4. Check cloudwatch logs

**Expected behavior**
`amplifly update api` and `amplify push` should update the graphql api key.

**Screenshots**
 

**Additional context**
Pubsec.yaml
```
amplify_api: ^0.2.0
  amplify_flutter: ^0.2.1
  amplify_auth_cognito: ^0.2.0
  amplify_storage_s3: ^0.2.0
```
amplify-cli version: 
```amplify -version                                                     ✔  17s 
6.3.1```

**Comment by HuiSF** [comment]
Hi @hackrx I tired the steps you listed in the issue description, and I couldn't update the expiry date for the API key either. I noticed, however, after I executed the `amplify update api`, the Amplify backend config file (`amplify/backend/backend-config.json`) got updated, and it reflects my changes.

Then I found this document: https://docs.amplify.aws/cli/start/workflows/#optional-update-projects-using-latest-amplify-cli
and I tried
```
amplify push --force
```

I got my API key updated.

So according to the document, `--force` is expected to be used to update backend configuration. Could you try this to resolve your issue?

In addition, besides using the CLI, you can always update the API key via AppSync console.
1. Login to AppSync console (your account should have permission to alter configurations)
2. Select `settings` on the left panel
3. In the `Default authorization mode` select your API key item, then click "Edit" button

You can change the expiry date, or rename the API key, after you save the changes, don't forget to
```
amplify pull
```

**Comment by offlineprogrammer** [comment]
Hey @hackrx 

I am closing this issue for now as we didn't hear from you following the above comment from @HuiSF
We can reopen it if you are still facing the issue.

Regards
Mo
